### ISSUE TITLE
Make a ~ import alias

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#10]
This:

![image](https://user-images.githubusercontent.com/1500684/97505262-369f2c00-193e-11eb-9784-ffd1265be200.png)

**Comment by cyberwombat** [comment]
So this feature does not work for me - I am using it as part of @shopify/hydrogen but I think Remix is handling this. I have changed my package.json type to "module" which I suspect is the issue though I find very little info online to support the idea that this prevents the alias from working. Anyone try this with `"type"="module"`?

**Comment by kentcdodds** [comment]
You may be interested in the new approach taken by the Epic Stack: https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/031-imports.md

It's based on a Node.js standard.

**Comment by cyberwombat** [comment]
@kentcdodds 

Thanks but shopify hydrogen already makes use of ~ and this only works for # prefix.

**Comment by cyberwombat** [comment]
It actually turns out that the code works. Remix just throws errors that are meaningless evidently.
