### ISSUE TITLE
no doc about handleBotRequest

### ISSUE THREAD

**Issue by arnaudambro** [remix-run/remix#10028]
### Reproduction

someone started a discussion there -> https://github.com/remix-run/remix/discussions/5549

but nobody gives a damn about it

so I ask the questions here :
https://github.com/remix-run/remix/blob/main/templates/express/app/entry.server.tsx

1. what is the purpose of `handleBotRequest` ?
2. what is the difference in treatment with `handleBrowserRequest` ?

thanks !

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 102.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/64074_1727100163021/bin/node
    Yarn: 4.4.1 - ~/Library/Caches/fnm_multishells/64074_1727100163021/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/64074_1727100163021/bin/npm
    bun: 1.0.0 - /opt/homebrew/bin/bun
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 126.1.67.119
    Chrome: 129.0.6668.70
    Edge: 124.0.2478.97
    Safari: 17.6
  npmPackages:
    @remix-run/dev: ^2.12.1 => 2.12.1
    @remix-run/express: ^2.11.2 => 2.12.1
    @remix-run/node: ^2.12.1 => 2.12.1
    @remix-run/react: ^2.12.1 => 2.12.1
    @remix-run/serve: ^2.12.1 => 2.12.1
    vite: ^5.1.0 => 5.4.7
```

### Used Package Manager

yarn

### Expected Behavior

I ask because I have a problem setting up cors globally (https://remix.run/resources/remix-utils#cors) and I wonder if it's because of the "bot requests"

### Actual Behavior

preflight doesn't pass - I'd like to know if it's related, so I'd like to know more about `handleBotRequest`

**Comment by laishere** [comment]
`handleBotRequest` only sends the final html, so that the search engines like google can have the correct final page.
`handleBrowserRequest` sends the result immediately when the `shell` of the page is rendered, so that the user can see the results at once and keep revealing the whole page as loading.

For example, when your react tree has a suspense component. It shows the loading bar before real component is ready. If you don't wait until the full page is rendered completely, the google crawler will see a loading bar other than the real content.

The only difference between these two is when to send  the response: `onAllReady` and `onShellReady`.

Please check the react docs here:
https://react.dev/reference/react-dom/server/renderToPipeableStream#rendertopipeablestream
>onAllReady: A callback that fires when all rendering is complete, including both the [shell](https://react.dev/reference/react-dom/server/renderToPipeableStream#specifying-what-goes-into-the-shell) and all additional [content.](https://react.dev/reference/react-dom/server/renderToPipeableStream#streaming-more-content-as-it-loads) You can use this instead of onShellReady [for crawlers and static generation.](https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation) If you start streaming here, you won’t get any progressive loading. The stream will contain the final HTML.

>onShellReady: A callback that fires right after the [initial shell](https://react.dev/reference/react-dom/server/renderToPipeableStream#specifying-what-goes-into-the-shell) has been rendered. You can [set the status code](https://react.dev/reference/react-dom/server/renderToPipeableStream#setting-the-status-code) and call pipe here to start streaming. React will [stream the additional content](https://react.dev/reference/react-dom/server/renderToPipeableStream#streaming-more-content-as-it-loads) after the shell along with the inline <script> tags that place that replace the HTML loading fallbacks with the content.

**Comment by arnaudambro** [comment]
thanks a lot !

It's really interesting, especially as I'm building a SPA mode Remix app - so I'd rather go for the `onAllReady` there

I think it's worth being in Remix docs, wdyt ?

**Comment by brophdawg11** [comment]
I think this is documented sufficiently in the React docs since these are React APIs.  We would likely accept a PR that added a comment to the `entry.server.tsx` files in the templates that indicated why `handleBotRequest` uses `onAllReady`
