### ISSUE TITLE
[Feature]: How to integrate ant-design UI framework 

### ISSUE THREAD

**Issue by aofong** [remix-run/remix#1005]
### What is the new or updated feature that you are suggesting?

I want to use the ant-design framework. I don’t know how to integrate it. Now I can render the style normally, but the client cannot use javascript normally. 
This is the official website address: https://ant.design/ 

### Why should this feature be included?

Can you provide reference documents?

**Comment by qlniu** [comment]
My current approach is to install antd directly and introduce and use it. As for the component style, it is to introduce all antd styles.

**Comment by aofong** [comment]
thanks , Forgot to import `<Scripts />`
