### ISSUE TITLE
`useLoaderData` returns incorrect data when there is a file in the top-level project dir with the same name as one of the routes

### ISSUE THREAD

**Issue by hgossler** [remix-run/remix#10084]
### Reproduction

`git clone https://github.com/hgossler/remix-route-debug`

This repo is based on `create-remix@latest` with a new route in `/app/routes/myroute.tsx` and an unrelated file at `/myroute.ts`.

- Start the development server using `remix vite:dev`
- Load the initial page (`localhost:5173/myroute`). The loader function is correctly called, and the data is accessible in the route component.
- Navigate back and forth between the routes.
    

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 76.31 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/opt/node@20/bin/pnpm
    bun: 1.1.27 - /opt/homebrew/bin/bun
    Watchman: 2024.09.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.4.1
  npmPackages:
    @remix-run/dev: ^2.12.1 => 2.12.1 
    @remix-run/node: ^2.12.1 => 2.12.1 
    @remix-run/react: ^2.12.1 => 2.12.1 
    @remix-run/serve: ^2.12.1 => 2.12.1 
    vite: ^5.1.0 => 5.4.8
```

### Used Package Manager

npm

### Expected Behavior

 `useLoaderData` should consistently return the data from the `loader` function.

### Actual Behavior

 `useLoaderData` returns the file contents of the file in the top-level project directory instead of the expected data. This seems to be caused by vite's dev server. It does not happen in production.

**Comment by laishere** [comment]
I think it's the url resolving priority issue.
If you delete or rename the file `myroute.ts` in the root directory, it works normally.

**Comment by brophdawg11** [comment]
This is standard vite behavior - since it serves static files from the project root by default - you can see this via `url http://localhost:5173/myroute`.

You can control where it serves files via the [`server.fs.allow`](https://vite.dev/config/server-options#server-fs-allow) config, or you could use the `deny` config on any specific files you want to avoid serving.

Renaming the file is also a simple and valid solution.
