### ISSUE TITLE
Form component does not support submit button name/value

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#101]
I have a form with two submit buttons: Register and Sign In. To do this is pretty simple:

```html
<form action="/login" method="post">
  {/* email/password inputs */}
  <button type="submit" name="type" value="register">Register</button>
  <button type="submit" name="type" value="sign in">Sign in</button>
</form>
```

If I fill out the form and console.log the URLSearchParams in the action:

```
URLSearchParams {
'email' => 'email@example.com',
'password' => 'iliketwix',
'type' => 'register' }
```

If I change this to remix's upper-case `Form` then I don't get the `type` parameter. I also tried with `<input ... />` instead of `<button ... />` and got the same result.

**Comment by ryanflorence** [comment]
@kentcdodds we have this, now, right? If I'm wrong, re-open :)

**Comment by kentcdodds** [comment]
Yup, don't know when this was fixed, but it is now 🎉
