### ISSUE TITLE
[Bug]: Link in CONTRIBUTING.md is incorrect

### ISSUE THREAD

**Issue by pr7prashant** [remix-run/remix#1010]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

Not Applicable

### What version of Node are you using? Minimum supported version is 14.

Not Applicable

### Steps to Reproduce

Open CONTRIBUTING.md and click on the **our guide to contributing** link. 

It will give 404 as the link is pointing to _docs/contributing.md_ instead of _docs/pages/contributing.md_

### Expected Behavior

On clicking the **our guide to contributing** link in CONTRIBUTING.md file, it should redirect to contributing.md file present at _docs/pages/contributing.md_

### Actual Behavior

On clicking the **our guide to contributing** link in CONTRIBUTING.md file, it gives 404 as it redirecting to _docs/contributing.md_ instead of _docs/pages/contributing.md_

**Comment by machour** [comment]
Can be closed, fixed by #1065
