### ISSUE TITLE
Docs are incomplete regarding Content Security Policy with `v3_singleFetch` enabled

### ISSUE THREAD

**Issue by lensbart** [remix-run/remix#10111]
### Reproduction

The docs are incomplete regarding their Content Security Policy guidance, with `v3_singleFetch` enabled. See [here](https://github.com/remix-run/remix/issues/10110#issuecomment-2412336115)

### System Info

```shell
Not applicable
```

### Used Package Manager

npm

### Expected Behavior

Docs mention `nonce` being passed to both `<RemixServer />` and the second argument of `renderToPipeableStream`

### Actual Behavior

Docs mention `nonce` being passed to `<RemixServer />` only

**Comment by brophdawg11** [comment]
Thanks for the heads up!  I just added this in 11c2acc6d901442e07934fd78f1098040f616382
