### ISSUE TITLE
[Bug]: using @import in css files results in routes error

### ISSUE THREAD

**Issue by insuusvenerati** [remix-run/remix#1012]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

- Add `@material-tailwind/react` as a dependency
- Install tailwindcss https://tailwindcss.com/docs/installation
- Create a `./styles/tailwind.css` with the following code:
```css
@import "../node_modules/@material-tailwind/react/tailwind.css";
@tailwind base;
@tailwind components;
@tailwind utilities;
```
- Build the css using `tailwindcss -i ./styles/tailwind.css -o ./app/tailwind.css`
- Import `./app/tailwind.css` into the app using:
```tsx
// root.tsx
import styles from "./tailwind.css";

// https://remix.run/api/app#links
export let links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: styles }];
};
```
- Use a component from the library like `import Card from "@material-tailwind/react/Card";`

### Expected Behavior

Component library styles should be used.

### Actual Behavior

Component library styles are not used and an error is produced in the console:
```
No routes matched location "/build/node_modules/@material-tailwind/react/tailwind.css" 
```

**Comment by ryanflorence** [comment]
Remix doesn't process your CSS, so your `@import` url just goes wholesale into the generated stylesheet. Once in the browser, your CSS file is looking for `/build/node_modules/...` on your web server, which doesn't exist.

Import the styles in your root links export and then Remix will add those styles styles to the web server's public build directory:

```js
import material from "@material-tailwind/react/tailwind.css";
import styles from "./tailwind.css";

export let links: LinksFunction = () => {
  return [
    { rel: "stylesheet", href: material }, 
    { rel: "stylesheet", href: styles }
  ];
};
```
