### ISSUE TITLE
remix.run website bug

### ISSUE THREAD

**Issue by japrogramer** [remix-run/remix#10147]
### Reproduction

scroll to the blue screen part 
and this happens

![Screenshot 2024-10-21 at 6 52 32 AM](https://github.com/user-attachments/assets/7e9d9bd0-5bca-4e3d-aee6-6f867280f766)

### System Info

```shell
Updating Chrome
Version 126.0.6478.127 (Official Build) (arm64)
```

### Used Package Manager

npm

### Expected Behavior

no bugs

### Actual Behavior

visual bug

**Comment by brophdawg11** [comment]
Keep scrolling 😉 

![Screenshot 2024-10-21 at 1 31 55 PM](https://github.com/user-attachments/assets/fd8acfae-82e9-4c1b-b45c-81c792213ace)
