### ISSUE TITLE
Trailing slashes added to routes whose name matches subdirectory in public directory

### ISSUE THREAD

**Issue by mattrothenberg** [remix-run/remix#10163]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-xqcugh?file=app%2Froutes%2Fabout.tsx

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 487.45 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.asdf/installs/nodejs/21.7.3/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.8.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 129.1.70.119
    Chrome: 130.0.6723.70
    Safari: 17.6
  npmPackages:
    @remix-run/dev: ^2.12.1 => 2.13.1
    @remix-run/node: ^2.12.1 => 2.13.1
    @remix-run/react: ^2.12.1 => 2.13.1
    @remix-run/serve: ^2.12.1 => 2.13.1
    vite: ^5.4.7 => 5.4.7
```

### Used Package Manager

npm

### Expected Behavior

When visiting a route `/about`, I don't expect to be redirected to `/about/`. But I am consistently redirected to `/about/` when there's a subdirectory in public with a name that matches the route name `about`.

### Actual Behavior

We (Replicate) noticed that a handful of routes in the application were immediately redirecting to {ROUTE_NAME}/ with a trailing slash on the end.

```
➜  frontend git:(des-188-dig-into-frontend-slash-redirect-issue) ✗ curl http://localhost:3000/playground
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to /playground/</pre>
</body>
</html>
```

We could reproduce this in production and locally, after running npm run build and npm run start, the latter of which starts up Remix's server via the `remix-serve` library.

Because this library has basic logging built in, we noticed that curiously NO requests were being logged for /playground; only the requests for /playground/.

```
[remix-serve] http://localhost:3000/ (http://192.168.86.48:3000/)
GET /playground/ 200 - - 23.525 ms
GET /playground/ 200 - - 12.561 ms
GET /playground/ 200 - - 10.262 ms
GET /playground/ 200 - - 10.451 ms
GET /playground/ 200 - - 10.245 ms
```

I added a bunch of logs myself to the following file, and I realized that the static middleware was doing something funky; before those middlewares, I could see the logs for `/playground` but afterwards, it was nowhere to be found.

https://github.com/remix-run/remix/blob/b98a53eeb551459062a076f14186951b1cae7fec/packages/remix-serve/cli.ts#L126-L146

I also noticed that the static middlewares supports passing a redirect option which does the following...But Remix doesn't expose an API for configuring this yourself.

![image](https://github.com/user-attachments/assets/5417aa3b-95bf-4bdf-bdea-f6710e118c78)

When I hardcoded `redirect: false` in that middleware, everything...just worked! But that wasn't a feasible fix without forking Remix. When I looked at how that middleware worked under the hood, I had an epiphany: the redirect behavior in the middleware only applied to _directories_. And it just so happened that we had both a `playground` URL in the Remix app, as well as a `playground` subdirectory in our app's public assets directory.

So in the end, I realized that Remix was just sort of confused here, and was treating this route (and `/docs` too, which had a docs directory in public) like a directory, adding the trailing slash.

This seems to me like unexpected or undocumented behavior, but I can't say that authoritatively. The simple fix was to rename the directory in my `public` directory. But I wonder if this is something that can be "fixed" even further?

Hope that helps!

**Comment by mattrothenberg** [comment]
Fair enough! We probably won't go the route of running our own server, as that's a much more heavy handed solution than renaming our subdirectories in `public` so that they their names don't clash with publicly accessible routes.

Would you at least be open to a PR that resolves/clarifies this issue, either by way of a change to the static middleware itself, or some documentation around `remix-serve` that cautions developers against this potential naming clash?

**Comment by brophdawg11** [comment]
I don't think we necessarily want to try to document/call out these types of default behaviors since then we're effectively duplicating the documentation for those common express middlewares in our docs, and then. it's something we have to try to keep up to date.  

I think we'd be open to maybe some extended wording on what middlewares are used by `remix-serve` and with links out to their docs so folks can find that type of info easier?

**Comment by mattrothenberg** [comment]
Understood, thanks for the prompt reply @brophdawg11 👍

**Comment by brophdawg11** [comment]
Added some clarity in https://github.com/remix-run/remix/commit/80fd7e7a2c49829e56ec955c45580843b9e7e331

**Comment by mattrothenberg** [comment]
Fantastic. Thanks!
