### ISSUE TITLE
Dev server in SPA mode crashes in Safari

### ISSUE THREAD

**Issue by MustafaHaddara** [remix-run/remix#10181]
### Reproduction

Create a brand new Remix app, using the SPA mode template

Add a `<Link to="/a">` and corresponding route component

Run `npm run dev`

Open `http://localhost:5173` in Safari

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 355.64 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.asdf/installs/nodejs/22.9.0/bin/node
    npm: 10.8.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
  npmPackages:
    @remix-run/dev: ^2.13.1 => 2.13.1 
    @remix-run/node: ^2.13.1 => 2.13.1 
    @remix-run/react: ^2.13.1 => 2.13.1 
    vite: ^5.1.0 => 5.4.10
```

### Used Package Manager

npm

### Expected Behavior

Application does not crash

note: the application does not crash in Chrome, only Safari

### Actual Behavior

The entire application crashes

<img width="930" alt="image" src="https://github.com/user-attachments/assets/b7bc227e-da29-4632-a7af-7259a1023ab6">

<img width="556" alt="image" src="https://github.com/user-attachments/assets/5dc1800b-55a4-4a3a-95d3-68be753f0db2">

```
React Router caught the following error during render 
Error: useHref() may be used only in the context of a <Router> component.
invariant — history.ts:494
useHref — hooks.tsx:61
Link — components.js:162
renderWithHooks — react-dom.development.js:15486
updateForwardRef — react-dom.development.js:19245
beginWork$1 — react-dom.development.js:27465
performUnitOfWork — react-dom.development.js:26596
workLoopSync — react-dom.development.js:26505
renderRootSync — react-dom.development.js:26473
recoverFromConcurrentError — react-dom.development.js:25889
performConcurrentWorkOnRoot — react-dom.development.js:25789
workLoop — scheduler.development.js:266
flushWork — scheduler.development.js:239
performWorkUntilDeadline — scheduler.development.js:533
```

**Comment by joshbuddy** [comment]
I believe this is a dupe of https://github.com/remix-run/remix/issues/10156

**Comment by MustafaHaddara** [comment]
> I believe this is a dupe of #10156

Can confirm, the workaround in that issue works in my case as well. 

Thanks!
