### ISSUE TITLE
[Bug]: Nested CatchBoundaries not getting called on router 404

### ISSUE THREAD

**Issue by grapereader** [remix-run/remix#1019]
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.17.6

### Steps to Reproduce

I have a simple hierarchy like so:

```
root.tsx (CatchBoundary A)
routes
| main
| | index.tsx
| index.tsx (redirects to /main) (CatchBoundary B)
| main.tsx (CatchBoundary C)
```

I can navigate to /main and see my DOM correctly root -> main -> main/index

Now, when trying a route that does not exist: /main/foo, I would expect the CatchBoundary inside main.tsx (CatchBoundary C) to handle the error. Instead, the error bubbles all the way up to root CatchBoundary A. It skips CatchBoundary C and B.

Removing CatchBoundary A will result in an "unhandled thrown response" error.

Each CatchBoundary is declared the same way:
```
export function CatchBoundary() {
    console.log('[A/B/C]');
    return (<p>Caught at [A/B/C]</p>);
}
```

Here is the test project: https://stackblitz.com/edit/node-ztn5tq?file=app/routes/index.tsx

### Expected Behavior

A 404 for non-existent route /main/foo should be handled by the CatchBoundary at /main before bubbling to /

### Actual Behavior

404 always bubbles up to root.

**Comment by grapereader** [comment]
Originally misfiled this in react-router project as https://github.com/remix-run/react-router/issues/8474

May be related, but I am using remix.

**Comment by oliverjam** [comment]
Yeah I'm still struggling with the exact same problem on latest Remix (`v1.3.5`). It's pretty easy to reproduce this: the "Nested Catch Boundaries" section of the [Not Found](https://remix.run/docs/en/v1/guides/not-found) docs doesn't work.

[Reproduction on Stackblitz](https://stackblitz.com/edit/node-r7alz9?file=app%2Froutes%2Fpages%2FpageId.jsx). This is pretty much the official example with a bunch of unrelated stuff stripped out.

Visit `/pages/3`—the loader always throws a 404, and Remix always renders the default CatchBoundary, _not_ the one defined in `app/routes/pages/$pageId.jsx`.

<img width="1142" alt="Screenshot 2022-04-14 at 17 20 01" src="https://user-images.githubusercontent.com/9408641/163431594-7b8f2085-322f-4a2b-bef2-265f925e3e02.png">

**Comment by knoefel** [comment]
I'm also facing this problem right now - still an issue with `@remix-run@1.4.3`.

**Comment by parisholley** [comment]
so the issue is that when remix defines routes, it isn't [splatting](https://remix.run/docs/en/v1/guides/routing#splats) by default (which is by design). in order for `CatchBoundary` to trigger, it has be part of a known router path which will never happen in the case of a 404. 

in order to make nested 404's to work, you need a folder structure like this:

```
routes/
  nested/
    foo.tsx
    bar.tsx
    *.tsx
  nested.tsx
```

where `*.tsx` effectively enables path matching  and looks like this:

```tsx
import { Links, Meta, Scripts } from '@remix-run/react';

export function CatchBoundary() {
  return (
    <html>
      <head>
        <title>My Nested Error</title>
        <Meta />
        <Links />
      </head>
      <body>
        HELP!
        <Scripts />
      </body>
    </html>
  );
}

export function loader() {
  throw new Response('Not Found', { status: 404 });
}

export default function () {
  return <></>;
}
```

**Comment by brophdawg11** [comment]
@parisholley is correct - you will need a `main/$.tsx` splat route defined here if you want to specifically handle 404s beneath `main/*` urls.  

Errors bubble up through _matched_ routes, but without `main/$.tsx` you don't actually match anything.
