### ISSUE TITLE
handling of redirects encountered in `serverLoader` changes with Single Fetch

### ISSUE THREAD

**Issue by rossipedia** [remix-run/remix#10208]
### Reproduction

https://github.com/rossipedia/await-single-fetch-shenanigans

https://stackblitz.com/~/rossipedia/await-single-fetch-shenanigans

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 26.83 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/43462_1731267897329/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/43462_1731267897329/bin/yarn
    npm: 10.9.0 - ~/.local/state/fnm_multishells/43462_1731267897329/bin/npm
    pnpm: 9.12.0 - ~/.local/state/fnm_multishells/43462_1731267897329/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 111.1.49.132
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 18.1
```

### Used Package Manager

`npm`

### Expected Behavior

> [!NOTE]
> I originally thought this was an issue with the `<Await>` component, but I've since realized that the underlying behavioral change is with `serverLoader()`, and I assume by extension `turbo-stream`

With `v3_singleFetch` enabled, a redirect `Response` received from `serverLoader()` should result in a rejected `Promise`.

### Actual Behavior

With `v3_singleFetch` enabled, a redirect `Response` received from `serverLoader()` results in a resolved `Promise`.

When used with `<Await>`, note that the `Response` instance is passed to the `children` function if provided, which breaks the type contract for `<Await>`:

```tsx
export function loader() {
  if (someCondition) {
    throw redirect('/');
  }

  return {
    foo: 'bar',
  };
}

export function clientLoader({ serverLoader }: ClientLoaderFunctionArgs) {
  return {
    promise: serverLoader<typeof loader>(),
  }
}

clientLoader.hydrate = true;

export default function RouteComponent() {
  const { promise } = useLoaderData<typeof clientLoader>();

  return (
    <Suspense fallback={<>Loading...</>}>
      <Await resolve={promise}>
        {/*
        Here, the typings say that data is of type `{ foo: string }`, but at runtime
        if `someCondition` is true it will be a `Response` instance with a 302 status
        and `Location` header.
        */}
        {(data) => <Render data={data} />}
      </Await>
    </Suspense>
  );
}
```

**Comment by brophdawg11** [comment]
This will be included in the next release
