### ISSUE TITLE
Remix (Vite?) loses styles on save (even without changes)

### ISSUE THREAD

**Issue by danthegoodman1** [remix-run/remix#10224]
### Reproduction

Any time I save a file (even with no changes), the styles in remix are lost. This has pretty much always happened, through many versions. Nothing special about this setup, using the default remix setup.

https://github.com/user-attachments/assets/5473c380-55dd-4966-a01a-10a34a6b2520

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Memory: 21.57 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 131.0.6778.69
    Safari: 17.5
  npmPackages:
    @remix-run/dev: ^2.13.1 => 2.13.1
    @remix-run/node: ^2.12.0 => 2.13.1
    @remix-run/react: ^2.12.0 => 2.13.1
    @remix-run/serve: ^2.12.0 => 2.13.1
    vite: ^5.4.9 => 5.4.9
```

### Used Package Manager

npm

### Expected Behavior

Styles are not lost

### Actual Behavior

Styles are lost

**Comment by danthegoodman1** [comment]
It seems to be when I save on a higher level route.

E.g. if Im on `http://localhost:5173/dash/overview` and I save `dash.tsx` it does that, but if I save `dash.overview.tsx` it flashes no styles but comes back within a few hundred ms

**Comment by danthegoodman1** [comment]
https://github.com/user-attachments/assets/716a5ac8-a3de-4124-a8a5-63ef85ce93d8

Actually, it only comes back if I save a route that I am NOT currently on...

**Comment by arjunyel** [comment]
Are there errors in the browser console?

**Comment by danthegoodman1** [comment]
lmao yeah... not sure why I didnt' think to check that, have been in the backend for too long
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/be7230b5-e248-45a9-ba67-5109cedb2978">

There definitely needs to be a better way to figure out what was wrong, was a bit of a nightmare to fix because the line numbers in the console were not matching where the error was in the actual code (issue with sourceMaps I guess)

**Comment by danthegoodman1** [comment]
Issue was with nested buttons

**Comment by arjunyel** [comment]
@danthegoodman1 happy to help and that you got it fixed :D
