### ISSUE TITLE
docs say to install fs-routes as a dev dep, but its used at runtime

### ISSUE THREAD

**Issue by robcresswell** [remix-run/remix#10273]
### Reproduction

The docs at https://remix.run/docs/en/main/start/future-flags#v3_routeconfig list

```
npm install -D @remix-run/fs-routes
```

This is used at runtime though, so any application that prunes dev deps will fail to start i.e. most container builds

### System Info

```shell
This is not relevant
```

### Used Package Manager

npm

### Expected Behavior

Things run

### Actual Behavior

A pruned application cannot start

**Comment by brophdawg11** [comment]
Isn't this only used at build time via `routes.ts`?  You should be able to build and then prune dev deps and run your app without issue in the container.

**Comment by robcresswell** [comment]
@brophdawg11 I'm not sure I understand. If its used in `routes.ts`, doesn't that mean it'll get invoked at runtime?

**Comment by brophdawg11** [comment]
No, `routes.ts` is just a build time config, once you build the compiled route tree lives in the server and client builds.  `routes.ts` is not accessed at runtime I'm pretty sure.

**Comment by brophdawg11** [comment]
`routes.ts` is really just an extracted version of the `routes` config that used to live in `remix.config.js` if that makes it clearer that it's just a build time thing

**Comment by robcresswell** [comment]
Ah, okay. I'm pretty new to all this so I'd imagine you are correct.
