### ISSUE TITLE
`[vite:css-post] css content for "" was not found` on invalid ascii/emoji icons sets.

### ISSUE THREAD

**Issue by christoph-kluge** [remix-run/remix#10283]
### Reproduction

Will try later to provide a reproducible example via stacklitz.

```ts
// root.tsx
import styles from "~/styles.css?url"; // (tested with tailwind but also plain empty css file fails)

export const links: LinksFunction = () => [
    {rel: "stylesheet", href: styles},
];
```

```ts
// vite.config.ts
export default defineConfig({
    plugins: [
        remix({
            future: {
                v3_routeConfig: true,
            }
        }),
    ],
});
```

---- 

https://github.com/remix-run/remix/issues/10024 might be correlating because I see an absolute path for key of the  tailwind.css file, while all others are not. 

```json
{
  "/Users/user/absolute/path/to/remix-app/app/tailwind.css": {
    "file": "assets/tailwind-DcNBeDpG.css",
    "src": "/Users/user/absolute/path/to/remix-app/app/tailwind.css"
  },
  "_browser-ponyfill--M1DaTTc.js": {
    "file": "assets/browser-ponyfill--M1DaTTc.js",
    "name": "browser-ponyfill",
    "isDynamicEntry": true,
    "imports": [
      "_jsx-runtime-BNSfpw-k.js"
    ]
  },
  "_components-B_Mcmd8H.js": {
    "file": "assets/components-B_Mcmd8H.js",
    "name": "components",
    "imports": [
      "_jsx-runtime-BNSfpw-k.js"
    ]
  },
  // [...]
}
```

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 1.80 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.2.0 - ~/.nvm/versions/node/v23.2.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v23.2.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
  npmPackages:
    @remix-run/dev: ^2.15.0 => 2.15.0 
    @remix-run/node: ^2.15.0 => 2.15.0 
    @remix-run/react: ^2.15.0 => 2.15.0 
    @remix-run/route-config: ^2.15.0 => 2.15.0 
    @remix-run/routes-option-adapter: ^2.15.0 => 2.15.0 
    @remix-run/serve: ^2.15.0 => 2.15.0 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

Running `remix vite:build` does not work (while `remix vite:dev` does).

```
% npx remix vite:build
[...]
vite v5.4.11 building for production...
✓ 333 modules transformed.
[...]
✓ built in 1.09s
vite v5.4.11 building SSR bundle for production...
✓ 37 modules transformed.
x Build failed in 73ms
[vite:css-post] css content for "" was not found
    at Object.renderChunk (file:///Users/user/absolute/path/to/remix-app/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36388:19)
    at file:///Users/user/absolute/path/to/remix-app/node_modules/rollup/dist/es/shared/node-entry.js:20812:40
    at processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:css-post',
  hook: 'renderChunk'
}
```

### Actual Behavior

Removing `v3_routeConfig` correctly builds.

```
% npx remix vite:build
[...]
vite v5.4.11 building for production...
✓ 116 modules transformed.
[...]
✓ built in 766ms
vite v5.4.11 building SSR bundle for production...
✓ 11 modules transformed.
build/server/.vite/manifest.json            0.45 kB
build/server/assets/tailwind-DcNBeDpG.css  29.07 kB
build/server/index.js                       9.60 kB
✓ built in 44ms
```

**Comment by christoph-kluge** [comment]
After digging deeper it seems it's not a remix issue at all and perhaps related to vite + postcss and parsing of .tsx files. I had some special chars in place (apple's cmd icon). Removing it, started 

```diff
- <span>⌘K</span> (also &#8984; does not work)
+ <span>CMD K</span>
```

I guess the error-message could be improved `[vite:css-post] css content for "" was not found`, hence it's not remix related at all.

**Comment by azizmb** [comment]
hey @christoph-kluge I'm hitting the same error. How did you narrow down which file is causing this?

**Comment by christoph-kluge** [comment]
@azizmb very boring: I started commenting out `<Outlet/>` inside the root.tsx and it suddently started to work. This indicated it was related to some component.

So re-added `<Outlet/>`, went into the next component being rendered commented something else out, repeat. To be honest it was a very fresh remix app and I was working on the Home/Dashboard-Screen. So landed pretty quickly at the command pallete.

**Comment by christoph-kluge** [comment]
@azizmb moving to react-router@7.0.2 + vite@6.0.3 solved this issue for me.

**Comment by azizmb** [comment]
@iloveitaly I narrowed it down to how I was including the stylesheet. I removed the `?` when importing the stylesheet and that seemed to fix it. 

Here is how I'm importing and what's working for me: 

In the root.tsx I have: 

```
import '~/styling/global.css';
```

That's it, remove all the stylesheets in your links export, just including this fixed the error for me.
