### ISSUE TITLE
parent route loader being called on simple navigation of child routes

### ISSUE THREAD

**Issue by JasonColeyNZ** [remix-run/remix#10281]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-m4usjj?file=app%2Froutes%2Fclients.%24clientId.detail.tsx
https://github.com/JasonColeyNZ/remix-215-test

### System Info

```shell
macOSX Chrome 131.0.6778.86
```

### Used Package Manager

npm

### Expected Behavior

The parent loader should not be affecting the leaf route navigation.

### Actual Behavior

The delay in clients is 3 seconds, and the suspense is working, when this is first run, npm run dev, the delay works as expected, then navigate to the leaf routes all good, now if you refresh the browser (in stackblitz use the refresh icon) now navigate to leaf routes, all of them are awaiting on the clients parent route loader.
Sometimes in VSCode when I resave the clients or children routes this then allows the app to work as expected (after HMR).

In my app I am working on, sometimes saving in a leaf route will cause the parent loader to begin incorrectly load again on navigation, then i go to the parent route, re-save (no changes) and all is good again. Unfortunately this can't happen on the production site, so the parent route loader is being fired on all leaf route navigations.

**Comment by JasonColeyNZ** [comment]
I have just upgraded a large chunk of my app to RR7, and the issue is present on RR7, on a simple page navigation, all routes loaders (parent and children) are being refreshed. This I am sure should not be happening?

_By default, all routes are revalidated after actions. This function allows a route to opt-out of revalidation for actions that don't affect its data._

No actions are taking place during navigation.

**Comment by JasonColeyNZ** [comment]
Ahh ok the point about the requirement of middlewares might shed some light on why they did this.
When you say the simulate document requests, so this is to keep it closer aligned to Web Standards?
Pity, as its added a layer of complexity, I liked the idea that if I made a change to the underlying data I would force using the useRevalidator. Well I shall move on now with this knowledge, thank you.

**Comment by lucasrothman** [comment]
This seems to go against what the docs say here - https://remix.run/docs/en/main/guides/data-loading#remix-optimizations. Have they just not been updated?

> If you click a link in the sidebar, Remix knows that the parent route will remain on the page - but the child route's data will change because the url param for the document will change. With this insight, Remix will not refetch the parent route's data.

As a follow up, I have a relatively large user config that I fetch in the root loader (and I'm seeing it get re-fetched at every navigation), what would be the correct way to handle this as I may add more config options in the future and would rather just slow down the initial load (and form submissions) but not basic navigations. I use this to populate context such as light/dark mode so do want to have it on initial render and don't want to defer it.
