### ISSUE TITLE
Cannot install/get started with remix

### ISSUE THREAD

**Issue by dhruvkaushik305** [remix-run/remix#10299]
### Reproduction

Open a terminal and try bootstrapping an empty remix project. I ran `bunx create-remix@latest`. Alternatively i also tried npm and pnpm and got the same error that `error: Cannot find package 'fs-extra' from '/tmp/bunx-1000-create-remix@latest/node_modules/create-remix/dist/index.js'`

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 14.93 GB / 19.20 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    bun: 1.1.38 - ~/.bun/bin/bun
```

### Used Package Manager

npm

### Expected Behavior

The expected behavior is that the installation prompt for remix appear

### Actual Behavior

The actual behavior is that this module not found error is thrown in all these package managers

**Comment by solauraindia** [comment]
I've found that manually setting up the Remix project is working as a temporary workaround for this issue. This involves creating a new directory, initializing an npm project, and manually installing Remix and its dependencies. While it's not as convenient as the create-remix command, it does allow you to get started with development.

**Comment by Mahii1972** [comment]
I've found that manually setting up the Remix project is working as a temporary workaround for this issue. This involves creating a new directory, initializing an npm project, and manually installing Remix and its dependencies. While it's not as convenient as the create-remix command, it does allow you to get started with development.

**Comment by tarangpatil** [comment]
Have been experiencing same issue. Meanwhile, can someone suggest me how to setup a project manually?

**Comment by dhruvkaushik305** [comment]
https://remix.run/docs/en/main/start/quickstart
This goes through setting up things manually

**Comment by tarangpatil** [comment]
I found a way around this error!
The error message I got was:
```
node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- /home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js
- /home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/cli.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (/home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js:19:11)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js',
    '/home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/cli.js'
  ]
}

Node.js v22.12.0
```
The first line in require stack was `/home/tarangpatil09/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js`, so I `cd`ed to the folder `/home/tarangpatil09/.npm/_npx/5164864a48bff686/` and ran `npm install fs-extra` manually and that solved my issue.
Note: Doing this, I think, maybe risky and should be done at your own risk. Or just setup your remix project manually like @dhruvkaushik305 said.

**Comment by stephen776** [comment]
Manual setup is not an acceptable workaround as all of the remix stack template rely on the CLI to bootstap the project. I assume this will break some popular templates like epic-stack as well (if created via the `create-epic-app` cli which wraps `create-remix`

**Comment by AndreiBadescu** [comment]
Have the exact same issue

**Comment by tungrix** [comment]
Workaround is to install `create-remix` and `fs-extra` as local dependency, then call it via `npx create-remix`.

e.g. `package.json`:
```javascript
{
  "dependencies": {
    "create-remix": "^2.15.0",
    "fs-extra": "^10.1.0"
  }
}
```

**Comment by RaphaelMagnux** [comment]
Why did you closed the issue?

Is still appearing the error 😨

<img width="868" alt="Screenshot 2024-12-05 at 10 25 51 p m" src="https://github.com/user-attachments/assets/672581c9-f3c7-40de-88cb-a8d37f3547a0">

**Comment by RaphaelMagnux** [comment]
> Workaround is to install `create-remix` and `fs-extra` as local dependency, then call it via `npx create-remix`.
> 
> e.g. `package.json`:
> 
> ```js
> {
>   "dependencies": {
>     "create-remix": "^2.15.0",
>     "fs-extra": "^10.1.0"
>   }
> }
> ```

This worked fine for me! 🎉

<img width="683" alt="Screenshot 2024-12-05 at 10 28 59 p m" src="https://github.com/user-attachments/assets/2cce984a-f4e7-4a7c-8011-6b52817d55a5">

**Comment by JoshZA** [comment]
👍 Getting this too

**Comment by hiteshjoshi** [comment]
+1

**Comment by Cavdy** [comment]
same here... I am getting this error during installation

`node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- /Users/cavdy/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js
- /Users/cavdy/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/cavdy/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js:19:11)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cavdy/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/index.js',
    '/Users/cavdy/.npm/_npx/5164864a48bff686/node_modules/create-remix/dist/cli.js'
  ]
}

Node.js v21.2.0`

**Comment by pealmeid** [comment]
I'm having the same issue.

**Comment by bartgrundeken** [comment]
Getting this also, with `pnpm`, using `pnpx create-remix@latest`.

**Comment by md-abid-hussain** [comment]
Easier way is to 
```sh
npm install -g create-remix
npm install -g fs-extra
```
After that 
```sh
create-remix
```

**Comment by jjneely** [comment]
+1  As a fairly new person to react and remix, this wasn't the experience I was expecting.  I think this is worth a patch release.

**Comment by lil5** [comment]
I'm shocked this isn't released by now, anyway `npx create-remix@2.14.0` still works too.

If anything unrelease 2.15.0 from npm create-remix so that people don't get this error.

**Comment by SihenZhang** [comment]
I encountered the same error while following the official tutorial using npx create-remix@latest. As someone new to Remix and looking to transition from Next.js, this experience is a bit discouraging and not what I had hoped for.

**Comment by Toxe** [comment]
@SihenZhang Same. I am in the process of getting back into React, looking for a CRA replacement and want to compare Next.js, Remix and pure Vite and running into this issue right off the bat is a bit jarring. This problem should have been fixed ASAP weeks ago.

But here is a simple and easy workaround:

```
$ npm install -g create-remix
$ npm install -g fs-extra
$ npx create-remix my-app-name
```

**Comment by SihenZhang** [comment]
> @SihenZhang Same. I am in the process of getting back into React, looking for a CRA replacement and want to compare Next.js, Remix and pure Vite and running into this issue right off the bat is a bit jarring. This problem should have been fixed ASAP weeks ago.同样。我正在重新学习 React，寻找 CRA 的替代品，并想比较 Next.js、Remix 和纯 Vite，刚开始遇到这个问题有点令人不安。这个问题应该在几周前尽快解决。
> 
> But here is a simple and easy workaround:但这里有一个简单易行的解决方法：
> 
> ```
> $ npm install -g create-remix
> $ npm install -g fs-extra
> $ npx create-remix my-app-name
> ```

Yes, I managed to temporarily resolve the issue using the workaround mentioned above, but I believe this could leave a poor first impression on newcomers to Remix. Problems with the CLI can affect many new users, and even if they eventually find a solution, it could still cause significant frustration. I hope the development team can address this issue promptly.

**Comment by brophdawg11** [comment]
This is resolved in [2.15.1](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v2151)

**Comment by brophdawg11** [comment]
Also, for new projects we recommend starting with React Router v7 not Remix v2.  RR v7 is everything from Remix v2 plus some new goodies, and also where all new functionality will be landing moving forward.

https://remix.run/blog/react-router-v7
https://reactrouter.com/start/framework/installation

**Comment by Toxe** [comment]
> Also, for new projects we recommend starting with React Router v7 not Remix v2. RR v7 is everything from Remix v2 plus some new goodies, and also where all new functionality will be landing moving forward.

What does that mean? That Remix is obsolete now?

**Comment by janhaa** [comment]
@Toxe: https://remix.run/blog/merging-remix-and-react-router

**Comment by Toxe** [comment]
@janhaa Thanks!
