### ISSUE TITLE
[Bug]: The last CTA of the homepage is broken on Firefox ESR

### ISSUE THREAD

**Issue by RoneoOrg** [remix-run/remix#1031]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

nc

### What version of Node are you using? Minimum supported version is 14.

nc

### Steps to Reproduce

1. open the Homepage: https://remix.run with Firefox ESR (78.15.0esr (64 bits))
2. Browse to the bottom
3. Click on "Go Play"

### Expected Behavior

The URL https://remix.run/docs/en/v1 should be opened

### Actual Behavior

The URL is correctly updated in the address bar, but **the page content stays unchanged**.

Tested with Firefox 78.15.0esr (64 bits) with every add-ons disabled

**Comment by machour** [comment]
@RoneoOrg is this still happening for you? If it is, could you check the console / network tab for any pointers to the problem?
