### ISSUE TITLE
Tutorial uses not recommended FunctionComponent type

### ISSUE THREAD

**Issue by ka-avl-tailor** [remix-run/remix#10355]
### Reproduction

read tutorial

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Expected Behavior

tutorial uses:

```
function Favorite({contact}: { contact: Pick<ContractRecord, "favorite"> }) {
```

### Actual Behavior

tutorial uses:

```
const Favorite: FunctionComponent<{
  contact: Pick<ContactRecord, "favorite">;
}> = ({ contact }) => {
```

**Comment by MichaelDeBoey** [comment]
@ka-avl-tailor Please provide some documentation about why we shouldn't use `FunctionComponent`

**Comment by ka-avl-tailor** [comment]
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/
