### ISSUE TITLE
allow useMatches to disambiguate root route from index route

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#1046]
Right now if you add `console.log(useMatches())` to the root route and land on the index route, you get something like this:

```json
[
    {
        "pathname": "/",
        "params": {},
        "data": {
            "ENV": {
                "NODE_ENV": "development"
            },
            "categories": [
                {
                    "id": "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzM5NDUzMzIwODI5Ng==",
                    "name": "Home page",
                    "slug": "frontpage",
                    "path": "/frontpage"
                }
            ],
            "cart": [],
            "customer": null
        }
    },
    {
        "pathname": "/",
        "params": {}
    }
]
```

We may be able to rely on the fact that the first element in this array will always be the root, but we'll have the same problem with nested routes and their index as well. It would be nice if `useMatches` added a property on the match object to allow me to disambiguate matches for the index route and it's parent.

**Comment by sergiodxa** [comment]
IMO the root route should have `pathname: "root"` (without any slash) and for index routes it could do the same Remix does for submitting a form, add `?index` so it would be `pathname: "/?index"`, for nested routes it can look like `pathname: "/admin"` for the layout and `pathname: "/admin?index"` for the index.

**Comment by ryanflorence** [comment]
I'd use the route id. I've been fooling myself that route ids have never been part of the public API, but they are in meta `parentsData` 🤦🏼‍♂️ https://github.com/remix-run/remix/blob/90479a8182f7342f14d78973eafacfcf22dcc357/packages/remix-react/components.tsx#L614

**Comment by ryanflorence** [comment]
Just drop the route id on `id` of the match and I'll merge it.

**Comment by jacob-ebey** [comment]
https://github.com/remix-run/remix/pull/1348
