### ISSUE TITLE
Support for more file types

### ISSUE THREAD

**Issue by CarlOlson** [remix-run/remix#106]
I'm trying to integrate ReScript with Remix. The current `config.js` implementation only checks for JS and TS files. It would be nice to push the configuration of extensions and core files to the user config.

Something like the following: 

```js
{
  entryClient: "ClientEntry",
  entryServer: "ServerEntry",
  extensions: ["bs.js", "js"]
}
```

This isn't urgent because I can create symlink, but some languages (like Rescript), give little control over the naming conventions of files. This would be a nice quality of life improvement.

---
EDIT:

~~Same thing for `routeModuleExts` in `routeConventions.js`.~~ It could also be good to change `routeConventions.js` to ignore unrecognized files instead of erroring. And client/server checks inside `compiler/rollup/clientServer.js` could also be adjusted to allow a custom naming convention.

**Comment by tom-sherman** [comment]
Hi! Thought I'd drop in to say that I have remix and rescript working pretty nicely together - hopefully it helps you!

https://github.com/tom-sherman/remix-rescript-example

I'm looking to expand on the bindings and will likely publish a package, with some corresponding docs on how to get started with Remix + Rescript

**Comment by CarlOlson** [comment]
@tom-sherman You repo looks like a good starting point for most people, but my issue was working within a monorepo where we needed to keep the `.bs.js` extensions.

Remix wasn't a good fit at the time and we switched to NextJs. This can be closed if desired.
