### ISSUE TITLE
sub-path support with baseName

### ISSUE THREAD

**Issue by williamtstanley** [remix-run/remix#107]
I would like to to include a remix app alongside an existing legacy application by adding it to a sub-path. In this instance it would take over a section of our administration tool set. https://our-web-app.com/admin/preferred-gift <-- remix `/` path

I attempted a direct proxy-pass with nginx however as the expected relative paths were to `https://our-web-app.com/build` instead of `https://our-web-app.com/admin/preferred-gift/build` I ran into some issues. 

If remix could accept a baseName such as `/admin/preferred-gift` and use that for routing and relative path resolution it would help.

There might also be a super simple solution that I am not seeing

**Comment by nkas17** [comment]
This is also a  feature that I am looking for.

**Comment by dusty** [comment]
@williamtstanley did you ever find a solution for this?

**Comment by dusty** [comment]
Actually it looks like this might be on the radar, with https://github.com/remix-run/remix/issues/759

**Comment by machour** [comment]
Closing in favor of #759
