### ISSUE TITLE
Improve error messages when actions don't return a response

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#1078]
As seen in this video: https://youtu.be/d_BhzHVV4aQ?t=2223

![image](https://user-images.githubusercontent.com/1500684/146412113-deb83741-1bd3-4b46-a687-81e6bfc029bf.png)

**Comment by machour** [comment]
The error displayed now reads:

```
Error: You defined an action for route "routes/foo/bar" but didn't return anything from your `action` function. Please return a value or `null`.
```
