### ISSUE TITLE
[Bug]: Server error not being caught by `ErrorBoundary`

### ISSUE THREAD

**Issue by jon301** [remix-run/remix#1083]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

- Go to https://remix-playground-jon301.vercel.app/demos/params
- Click on `Param: one` , `two`, then use the browser's `prev` & `next` buttons until you get a 500 error
- The error is not caught by the `ErrorBoundary`

https://user-images.githubusercontent.com/122108/146431623-29fd7e4a-2529-42eb-ab87-def58ffdad7d.mp4

### Expected Behavior

The server error should be caught by the `ErrorBoundary`

### Actual Behavior

The component is rendered partially (with no data)

**Comment by chaance** [comment]
Hi! I'm not a bot, but I'm closing out old issues that have long grown stale and are likely not up-to-date with recent versions. Feel free to ping me if this is still an issue and I can reopen.
