### ISSUE TITLE
Unable to import from libs using ESM

### ISSUE THREAD

**Issue by gmencz** [remix-run/remix#109]
The following error is thrown when trying to import from libs using ESM (like [unist-util-visit](https://github.com/syntax-tree/unist-util-visit)):
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /my-app/node_modules/unist-util-visit/index.js
require() of ES modules is not supported.
require() of /my-app/node_modules/unist-util-visit/index.js from /my-app/build/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /my-app/node_modules/unist-util-visit/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /my-app/node_modules/unist-util-visit/package.json.
```

Code which caused the error to be thrown:
```ts
// mdx.server.ts
import { visit } from "unist-util-visit"
```

**Comment by Ferdzzzzzzzz** [comment]
Hey, getting an error that looks kind of similar for some ReScript libraries (my knowledge on modules vs commonjs etc is somewhere between very patchy and nonexistent). Has this problem been addressed, and can anyone tell me if I'm facing the same problem as this issue? :)

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/rescript/lib/es6/caml_exceptions.js from .../build/index.js not supported.
Instead change the require of caml_exceptions.js in .../build/index.js to a dynamic import() which is available in all CommonJS modules.
```

Changing the Rescript build from `es6` to `commonjs` removes the server error but gives a browser error: 

```
Uncaught Error: Dynamic require of "fs" is not supported
```
(amongst others)

Thanks in advance! 😄

**Comment by Girish21** [comment]
@Ferdzzzzzzzz try to move the ReScript module to a `.server.{ts|js}` file so that the module will not be included in client bundle

```ts
export async function someFunction() {
  const {default} = await import(/* some_module */)

  /**
  * rest of the function
  */
}
```

**Comment by leepowelldev** [comment]
Hitting this same issue ... our internal UI library is ESM only, so no option to use the CJS version. Is there any kind of option available at the moment to allow certain dependencies in `node_modules` to be transpiled to CJS?

**Comment by mdingena** [comment]
> our internal UI library is ESM only

We have the same issue with our Google Analytics integration and UI libraries.

**Comment by redrockhorse** [comment]
@jacob-ebey  Has this work been completed?

**Comment by nialldbarber** [comment]
Just to add a +1. I'm having the same issue as @edmundhung with [react-markdown](https://github.com/remarkjs/react-markdown)

```bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/niall.barber/Git/projects/react/ndb-remix/node_modules/react-markdown/index.js
require() of ES modules is not supported.
require() of /Users/niall.barber/Git/projects/react/ndb-remix/node_modules/react-markdown/index.js from /Users/niall.barber/Git/projects/react/ndb-remix/api/build/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/niall.barber/Git/projects/react/ndb-remix/node_modules/react-markdown/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/niall.barber/Git/projects/react/ndb-remix/node_modules/react-markdown/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/niall.barber/Git/projects/react/ndb-remix/api/build/index.js:185:40)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /Users/niall.barber/Git/projects/react/ndb-remix/node_modules/@remix-run/serve/index.js:39:17
    at Layer.handle [as handle_request] (/Users/niall.barber/Git/projects/react/ndb-remix/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/niall.barber/Git/projects/react/ndb-remix/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/niall.barber/Git/projects/react/ndb-remix/node_modules/express/lib/router/route.js:131:14)
```

**Comment by brumm** [comment]
Looks like: https://github.com/remix-run/remix/pull/239#pullrequestreview-726906749

My working setup
```js
// esm-modules.js
module.exports = {
  importUnified: async () => import('unified'),
  importParseMarkdown: async () => import('remark-parse'),
  importGfm: async () => import('remark-gfm'),
  importEmoji: async () => import('remark-emoji'),
  importSlug: async () => import('remark-slug'),
  importGithub: async () => import('remark-github'),
  importRemarkToRehype: async () => import('remark-rehype'),
  importRehypeStringify: async () => import('rehype-stringify'),
}
```
```js
import {
  importUnified,
  importParseMarkdown,
  importGfm,
  importEmoji,
  importSlug,
  importGithub,
  importRemarkToRehype,
  importRehypeStringify,
} from './esm-modules'

// in some async context
const { unified } = await importUnified()
const { default: parseMarkdown } = await importParseMarkdown()
const { default: gfm } = await importGfm()
const { default: emoji } = await importEmoji()
const { default: slug } = await importSlug()
const { default: github } = await importGithub()
const { default: remarkToRehype } = await importRemarkToRehype()
const { default: rehypeStringify } = await importRehypeStringify()
```

it's not pretty, but it works

**Comment by pcattori** [comment]
I use `const { unified } = await import('unified')` (and similar for the other ESM modules) and that has worked for me locally. 

But when I deploy to Netlify I see my `ErrorBoundary` getting rendered and a console error: `Error: Cannot find package 'unified' imported from /var/task/netlify/functions/server/build/index.js`.

Some googling pointed me to [the Netlify docs on `[functions]`](https://docs.netlify.com/configure-builds/file-based-configuration/#functions), specifically setting:

```toml
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["unified"]
```

With that^ it looks like now Netlify does find `unified`, but unfortunately its still an ESM module being `import()`ed from CJS, so I get `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:` like others above.

Looks like [the Unified ecosystem is firmly in the "only publish ESM" camp](https://github.com/unifiedjs/unified/issues/121). The [options suggested in that thread](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) seem to rely on access to the compiler, which I know Remix doesn't want to open up too soon (which I agree with).

Would love to see a tutorial where `unified` is used within a Remix app and the app is successfully deployed to Netlify!

**Comment by pcattori** [comment]
I should mention that with the `netlify.toml` above, I get a warning:

```
6:00:35 PM: ❯ The following Node.js modules use dynamic expressions to include files:
6:00:35 PM:    - @remix-run/react
6:00:35 PM: ​
6:00:35 PM:   Because files included with dynamic expressions aren't bundled with your serverless functions by default,
  this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
6:00:35 PM:   modules as external in the [functions] section of your `netlify.toml` configuration file:
6:00:35 PM: ​
6:00:35 PM:   [functions]
6:00:35 PM:     external_node_modules = ["@remix-run/react"]
```

But adding `@remix-run/react` to `external_node_modules` results in a successful deploy, but a site that just displays:

```
Unexpected Server Error

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by pcattori** [comment]
Did some more digging. Getting mostl consistent results locally and in Netlify. When I try to hit a route that uses my `unified` processor in the `loader`:

- Without `node_bundler = "esbuild"`
  - Locally: everything works!
  - Netlify deploy: `Error: Cannot find package 'unified' imported from /var/task/netlify/functions/server/build/index.js
`
- With `node_bundler = "esbuild"`:
  - Locally & Netlify Deploy: `Error: Must use import to load ES Module: <path to my project>/.netlify/functions-serve/server/src/node_modules/unified/index.js`

**Comment by RazvanRauta** [comment]
@edmundhung & @nialldbarber it worked for me after I downgraded react-markdown to [v6.0.3](https://github.com/remarkjs/react-markdown/releases/tag/6.0.3)

**Comment by tom-sherman** [comment]
@Ferdzzzzzzzz I have ReScript working with Remix here: https://github.com/tom-sherman/remix-rescript-example but the solution was not pretty...

It required a patch to Remix's compile step to exclude remix from a specific transpilation step: https://github.com/tom-sherman/remix-rescript-example/blob/7625c5562b0bbe7a5cd435693ac2bb69c58b2b66/patches/@remix-run+dev+1.1.1.patch

After applying this patch, you can set `transpileModules: ["rescript"]` in the remix config and everything should work...

This is essentially a port of [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) but for Remix. Judging by the number of downloads of that package (and my anecdotal experience) it's a very common requirement.

@kentcdodds What are your thoughts on supporting something like a `transpileModules` option?

**Comment by Ferdzzzzzzzz** [comment]
@tom-sherman appreciate it! Will give it a go to see just how ugly it is 😅

**Comment by pcattori** [comment]
Finally got things working with Netlify deploy. See netlify/zip-it-and-ship-it#869 for the solution.

**Comment by ShafSpecs** [comment]
@pcattori How were you able to workaround the dynamic imports error?

**Comment by pcattori** [comment]
@ShafSpecs I reproduced my issues/solution here: https://github.com/pcattori/remix-netlify-dynamic-imports . Specifically, I got everything working in my setup in the [`shiki` branch](https://github.com/pcattori/remix-netlify-dynamic-imports/tree/shiki) of that repo. YMMV if you use different `unified` plugins than I do, but should be a good reference nonetheless.

**Comment by codejet** [comment]
I also had the issue with `react-markdown` and the solution @RazvanRauta worked for me (https://github.com/remix-run/remix/issues/109#issuecomment-996203134). But I wonder why the newer versions of the package won't, even when adding it to `remix.config.js` (`serverDependenciesToBundle: ["react-markdown"]`)? See https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages.

**Comment by ikawka** [comment]
> I also had the issue with `react-markdown` and the workaround of @RazvanRauta worked for me ([#109 (comment)](https://github.com/remix-run/remix/issues/109#issuecomment-996203134)). But I wonder why the newer versions of the package won't, even when adding it to `remix.config.js` (`serverDependenciesToBundle: ["react-markdown"]`)? See https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages.

Having the same issue with `remark-gfm`

**Comment by hgeldenhuys** [comment]
+1 I have the same issue with React-Flow. I've tried multiple workaround but unsuccessful so far..

https://github.com/wbkd/react-flow/issues/1953

**Comment by lukeshiru** [comment]
Is there anything we can do as a community to help Remix have support for ESM modules? From a framework like this that advocates for using standards, the expectation from the community is for it to support ESM modules without any workarounds. We should be able to just do:

```js
import { somthing } from "an-esm-module";
```

And it should just work™. Maybe a first good step would be to make remix itself an ESM module (`"type": "module"`) and if folks actually want to use CommonJS, the can simply change the extension of their files to `.cjs`.

**Comment by Girish21** [comment]
@lukeshiru Remix already exports ESM modules for the browser bundle. The problem is with the server bundle. Still, Node's ESM vs CJS situation is a bit iffy, and lots of dependencies still don't support native ESM yet. Remix has a workaround, though; you can list the ESM only packages to be compiled to CJS during the build for the server bundle using [serverdependenciestobundle](https://remix.run/docs/en/v1/api/conventions#serverdependenciestobundle). You can also take a look at [importing esm packages](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages)

**Comment by lukeshiru** [comment]
@Girish21 thanks a lot for that `serverDependenciesToBundle` option. I was looking for something like that and couldn't find anything! ... I understand Node's limitations with CJS/ESM (one of my personal packages is still in CJS because ESLint, Prettier and similar packages haven't migrated yet to ESM), but as I mentioned in my previous comment, is kinda weird to have to update a config in `remix.config.js` to make ESM work properly when the idea of Remix is to use standards. Don't take this as a critique to Remix itself, but just as an observation of something that's "unintuitive" about it. Hope the ecosystem keeps evolving so we don't have to deal with this kind of things in the future.

**Comment by codejet** [comment]
@Girish21 the thing is, that for some packages the `serverDependenciesToBundle` option also didn't seem fix the issue (see https://github.com/remix-run/remix/issues/109#issuecomment-1047146581)

**Comment by Girish21** [comment]
@codejet yup, Remix does not know the dependency graph of modules included in `serverDependenciesToBundle`. For now, we have to manually add it as shown in this example [stackblitz](https://stackblitz.com/edit/node-ydjuwx?file=remix.config.js)

**Comment by codejet** [comment]
@Girish21 thanks, but could you elaborate on that? what apart from adding the dep to `serverDependenciesToBundle` is actually happening there?

**Comment by Chensokheng** [comment]
@codejet 
> I also had the issue with react-markdown and the workaround of @RazvanRauta worked for me (https://github.com/remix-run/remix/issues/109#issuecomment-996203134). But I wonder why the newer versions of the package won't, even when adding it to remix.config.js (serverDependenciesToBundle: ["react-markdown"])? See https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages.


Do you have the code that work with react-markdown? I can't make it works

**Comment by joakimbeng** [comment]
> > I also had the issue with react-markdown and the workaround of @RazvanRauta worked for me ([#109 (comment)](https://github.com/remix-run/remix/issues/109#issuecomment-996203134)). But I wonder why the newer versions of the package won't, even when adding it to remix.config.js (serverDependenciesToBundle: ["react-markdown"])? See [remix.run/docs/en/v1/pages/gotchas#importing-esm-packages](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages).
> 
> Do you have the code that work with react-markdown? I can't make it works

Don't know about `react-markdown` but I got `micromark` (with GitHub Flavoured Markdown) to work by adding each of the packages there was an error for and ended up with this:
```js
{
  serverDependenciesToBundle: [
    "character-entities",
    "decode-named-character-reference",
    "micromark",
    "micromark-core-commonmark",
    "micromark-extension-frontmatter",
    "micromark-extension-gfm",
    "micromark-extension-gfm-autolink-literal",
    "micromark-extension-gfm-footnote",
    "micromark-extension-gfm-strikethrough",
    "micromark-extension-gfm-table",
    "micromark-extension-gfm-tagfilter",
    "micromark-extension-gfm-task-list-item",
    "micromark-extension-mdx-expression",
    "micromark-extension-mdx-jsx",
    "micromark-extension-mdx-md",
    "micromark-extension-mdxjs",
    "micromark-extension-mdxjs-esm",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-mdx-expression",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-events-to-acorn",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
  ],
}
```

And now it works like a charm both in the browser and on the server!

**Comment by codejet** [comment]
@Chensokheng All I did was to stick to an older version of react-markdown (6.0.3) as suggested by another commenter (https://github.com/remix-run/remix/issues/109#issuecomment-996203134)

**Comment by DPangerl** [comment]
I have the same problem with `react-markdown`. Version downgrade didn't work for me. 

But also other packages like `@apollo/client` are suggesting me to add it to `serverDependenciesToBundle` in `remix.config.js`. If i do so, more and more packages show up – additionally to the ones already  added to `serverDependenciesToBundle`.

**Comment by emipc** [comment]
One of the libs I've added to `serverDependenciesToBundle` is using `import.meta.url`, making it to throw an error because it's `undefined`. This is preventing me to use this dependency just because of that.

**Comment by fourcolors** [comment]
Yeah I'm getting this too after adding it to `serverDependenciesToBundle` doesn't solve the issue

**Comment by fourcolors** [comment]
> > > I also had the issue with react-markdown and the workaround of @RazvanRauta worked for me ([#109 (comment)](https://github.com/remix-run/remix/issues/109#issuecomment-996203134)). But I wonder why the newer versions of the package won't, even when adding it to remix.config.js (serverDependenciesToBundle: ["react-markdown"])? See [remix.run/docs/en/v1/pages/gotchas#importing-esm-packages](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages).
> > 
> > 
> > Do you have the code that work with react-markdown? I can't make it works
> 
> Don't know about `react-markdown` but I got `micromark` (with GitHub Flavoured Markdown) to work by adding each of the packages there was an error for and ended up with this:
> 
> ```js
> {
>   serverDependenciesToBundle: [
>     "character-entities",
>     "decode-named-character-reference",
>     "micromark",
>     "micromark-core-commonmark",
>     "micromark-extension-frontmatter",
>     "micromark-extension-gfm",
>     "micromark-extension-gfm-autolink-literal",
>     "micromark-extension-gfm-footnote",
>     "micromark-extension-gfm-strikethrough",
>     "micromark-extension-gfm-table",
>     "micromark-extension-gfm-tagfilter",
>     "micromark-extension-gfm-task-list-item",
>     "micromark-extension-mdx-expression",
>     "micromark-extension-mdx-jsx",
>     "micromark-extension-mdx-md",
>     "micromark-extension-mdxjs",
>     "micromark-extension-mdxjs-esm",
>     "micromark-factory-destination",
>     "micromark-factory-label",
>     "micromark-factory-mdx-expression",
>     "micromark-factory-space",
>     "micromark-factory-title",
>     "micromark-factory-whitespace",
>     "micromark-util-character",
>     "micromark-util-chunked",
>     "micromark-util-classify-character",
>     "micromark-util-combine-extensions",
>     "micromark-util-decode-numeric-character-reference",
>     "micromark-util-decode-string",
>     "micromark-util-encode",
>     "micromark-util-events-to-acorn",
>     "micromark-util-html-tag-name",
>     "micromark-util-normalize-identifier",
>     "micromark-util-resolve-all",
>     "micromark-util-sanitize-uri",
>     "micromark-util-subtokenize",
>     "micromark-util-symbol",
>     "micromark-util-types",
>   ],
> }
> ```
> 
> And now it works like a charm both in the browser and on the server!

this worked for me. I need to add all reps to the list, not just the parent one. Bravo!

**Comment by ariofrio** [comment]
I'm getting the following error when trying to use `rehype-remark` with the `serverDependenciesToBundle` workaround:

```
Error: Package subpath './lib/parser/index.js' is not defined by "exports" in .../node_modules/parse5/package.json
    at new NodeError (node:internal/errors:377:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.../build/index.js:1623:29)
```

[This `parse5` issue](https://github.com/inikulin/parse5/issues/861) suggests that it's a bundler or mismatched versions problem. In particular, `rehype-parse` depends on `parse5": "^6.0.0"` which has that file, but `jsdom` depends on `"parse5": "^7.0.0"`. **It seems like somehow `serverDependenciesToBundle` is making node forget to use the correct version of parse5 (which is in ./node_modules/rehype-parse/node_modules/parse5).**

My package.json:

```json
{
  "dependencies": {
    "jsdom": "^22.0.0",
    "rehype-parse": "^8.0.4",
    "rehype-remark": "^9.1.2",
    "remark-stringify": "^10.0.3",
  }
}
```

My remix.config.js:

```json
{
  "serverDependenciesToBundle": [
    "bail",
    "character-entities",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "hast-util-embedded",
    "hast-util-from-parse5",
    "hast-util-has-property",
    "hast-util-is-body-ok-link",
    "hast-util-is-element",
    "hast-util-parse-selector",
    "hast-util-phrasing",
    "hast-util-to-mdast",
    "hast-util-to-text",
    "hast-util-whitespace",
    "hastscript",
    "is-plain-obj",
    "longest-streak",
    "mdast-util-phrasing",
    "mdast-util-to-markdown",
    "mdast-util-to-string",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "property-information",
    "rehype-minify-whitespace",
    "rehype-parse",
    "rehype-remark",
    "remark-stringify",
    "space-separated-tokens",
    "trim-trailing-lines",
    "trough",
    "unified",
    "unist-util-find-after",
    "unist-util-is",
    "unist-util-stringify-position",
    "unist-util-visit-parents",
    "unist-util-visit",
    "vfile-location",
    "vfile-message",
    "vfile",
    "web-namespaces",
    "zwitch",
  ],
}
```

I continue to get the same error even if I add "parse5" to "serverDependenciesToBundle".

**Comment by ariofrio** [comment]
My work around for now is to downgrade jsdom to 19.0.0 and @types/jsdom to 16.2.15 in my package.json, before they upgraded to parse5 v7, and remove node_modules and package-lock.json before running `npm i` again, to ensure that parse5 v6 is at the root of my node_modules so that the "serverDependenciesToBundle"-ed `rehype-parse` module can find it.

This seemed to work. However, a bit later on I realized I needed to install `remark-gfm`. By the way, a cool trick I've found is to run `npm run build` after adding a dependency, and it'll list packages to add to "serverDependenciesToBundle". After you add those packages and you run `npm run build` again, it'll detect additional packages (basically doing a breadth first search, one layer at a time). This is faster (O(log n) vs O(n)?) than potentially seeing each package fail individually.

But now I have a new problem, that "mdast-util-to-markdown" doesn't seem to work with "serverDependenciesToBundle". I put it in `remix.config.js`:

```json
{
  serverDependenciesToBundle: [
    "bail",
    "ccount",
    "character-entities",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "escape-string-regexp",
    "hast-util-embedded",
    "hast-util-from-parse5",
    "hast-util-has-property",
    "hast-util-is-body-ok-link",
    "hast-util-is-element",
    "hast-util-parse-selector",
    "hast-util-phrasing",
    "hast-util-to-mdast",
    "hast-util-to-text",
    "hast-util-whitespace",
    "hastscript",
    "is-plain-obj",
    "longest-streak",
    "markdown-table",
    "mdast-util-find-and-replace",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-table",
    "mdast-util-gfm-task-list-item",
    "mdast-util-gfm",
    "mdast-util-phrasing",
    "mdast-util-to-markdown", // <=====
    "mdast-util-to-string",
    "micromark-core-commonmark",
    "micromark-extension-gfm-autolink-literal",
    "micromark-extension-gfm-footnote",
    "micromark-extension-gfm-strikethrough",
    "micromark-extension-gfm-table",
    "micromark-extension-gfm-tagfilter",
    "micromark-extension-gfm-task-list-item",
    "micromark-extension-gfm",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "parse5",
    "property-information",
    "rehype-minify-whitespace",
    "rehype-parse",
    "rehype-remark",
    "remark-gfm",
    "remark-stringify",
    "space-separated-tokens",
    "trim-trailing-lines",
    "trough",
    "unified",
    "unist-util-find-after",
    "unist-util-is",
    "unist-util-stringify-position",
    "unist-util-visit-parents",
    "unist-util-visit",
    "vfile-location",
    "vfile-message",
    "vfile",
    "web-namespaces",
    "zwitch",
  ],
}
```

But even after `rm -rf build node_modules package-lock.json && npm i`, I still get the following error on `npm run build`:

```
mdast-util-to-markdown is possibly an ESM only package and should be bundled with "serverDependenciesToBundle" in remix.config.js.
```

And the following on `npm run dev`:

```

.../build/index.js:8360
var import_association = require("mdast-util-to-markdown/lib/util/association.js"), import_container_flow = require("mdast-util-to-markdown/lib/util/container-flow.js"), import_indent_lines = require("mdast-util-to-markdown/lib/util/indent-lines.js"), import_safe = require("mdast-util-to-markdown/lib/util/safe.js"), import_track = require("mdast-util-to-markdown/lib/util/track.js");
                         ^
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/mdast-util-to-markdown/lib/util/association.js from .../build/index.js not supported.
Instead change the require of association.js in .../build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (.../build/index.js:8360:26)
    at Server.<anonymous> (.../build/server.js:44855:3)
    at Object.onceWrapper (node:events:641:28)
    at Server.emit (node:events:527:28)
    at emitListeningNT (node:net:1448:10)
ERROR: "dev:server" exited with 1.
```

**Comment by SangeetAgarwal** [comment]
@ariofrio take a look at what I've done at https://github.com/SangeetAgarwal/tailwind-remix-run-mdxjs-typescript-starter-blog/blob/main/app/lib/mdx.server.ts. This uses the indie stack and I constructed another repository that uses the blues stack and this is how I do it [there](https://github.com/SangeetAgarwal/tailwind-remix-run-blues-starter-blog/blob/main/app/lib/mdx.server.ts)

Both these are deployed to [here ](https://tailwind-remix-run-mdxjs-typescript-starter-blog.fly.dev/) and [here](https://tailwind-remix-run-blues-starter-blog.fly.dev/)

**Comment by n8agrin** [comment]
@ariofrio thanks for posting that. Saved me a couple hours. I had the exact same issue, downgrading jsdom, sadly, was the fix.

**Comment by ErikSom** [comment]
For anyone that is forced to stick with commonjs with remark-gfm I present an alternative dirty solution;
https://github.com/eriksom/remark-gfm-commonjs
