### ISSUE TITLE
[Bug]: link prefetch only works for routes with a loader

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#1091]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

1. Create a route that does not export a loader
2. Add `<Link to="that-route" prefetch="intent">Go to the route</Link>` to another route
3. Hover the link and notice that the JS/CSS is not prefetched

### Expected Behavior

I expect that JS modules and things in the `links` export to be prefetched.

### Actual Behavior

Nothing is prefetched.

Here's the part in the code that limits this functionality to routes with loaders only: https://github.com/remix-run/remix/blob/1da0e00c5a3e4293bab524a351d796d9ce32d6a7/packages/remix-react/links.ts#L324

I *think* we could just remove the `hasLoader` check and be fine, but I'm not sure what other impacts that would have.

**Comment by ch4nd4n** [comment]
@kentcdodds how about updating the docs and leaving it as is? Do you think removing the loader will have bad UX?

**Comment by brophdawg11** [comment]
Fixed in #2096
