### ISSUE TITLE
[Feature]: Don't throw error if target directory exists but is empty

### ISSUE THREAD

**Issue by jameskerr** [remix-run/remix#1093]
### What is the new or updated feature that you are suggesting?

I was following the remix getting started docs and created the directory for my remix app before running `npx create-remix@latest`. I completed the prompts, but then got the error that the directory already exists. I suggest that if the directory is empty, remix should use it. If it is not, throw the error.

This was essentially my shell session:
```
mkdir brim-remix

npx create-remix@latest
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./brim-remix
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change
 deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
 ️🚨 Oops, "brim-remix" already exists. Please try again with a different directory.
```

### Why should this feature be included?

This will help with onboarding. I'd be happy to work on this.

**Comment by machour** [comment]
I think it's fair that `create-remix` create its own directory, and errors if it exists, like most tool of this kind do.

Closing this issue for now, feel free to open a [Discussion](https://github.com/remix-run/remix/discussions) to gather some feedback if you still think that this should be included 🙏🏼
