### ISSUE TITLE
[Bug]: after .clone() on remix Request we end up with a nodeFetch.Request

### ISSUE THREAD

**Issue by andreafdaf** [remix-run/remix#1106]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [X] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

v14.15.1

### Steps to Reproduce

```ts
export const action: ActionFunction = async ({ request }) => {
  const clonedRequest = request.clone()
  const body1 = await request.formData() // ok
  const body2 = await clonedRequest.formData() // formData is undefined
}
```

### Expected Behavior

I would expect "clonedRequest" to be a remix Request, not a node-fetch Request

```diff
diff --git a/node_modules/@remix-run/node/fetch.js b/node_modules/@remix-run/node/fetch.js
index 2a973cd..814f60d 100644
--- a/node_modules/@remix-run/node/fetch.js
+++ b/node_modules/@remix-run/node/fetch.js
@@ -29,6 +29,9 @@ class Request extends nodeFetch.Request {
     return new formData.RemixFormData(body);
   }
 
+  clone() {
+    return new Request(this)
+  }
 }
 /**
  * A `fetch` function for node that matches the web Fetch API. Based on
```

### Actual Behavior

It is a node-fetch Request and formData() is missing

**Comment by chaance** [comment]
This should be fixed in 1.1.0
