### ISSUE TITLE
feat: Yarn PnP support in monorepo

### ISSUE THREAD

**Issue by ksorv** [remix-run/remix#1111]
### What is the new or updated feature that you are suggesting?

Supporting the yarn's PnP arch. I dont know how this can be done, So no more to say, sorry.don't

### Why should this feature be included?

Most of the libraries like React, Gatsby, Next, etc support yarn's PNP arch.

_Also, I can work on it if directions are provided._

**Comment by chaance** [comment]
Do you think you could make an example monorepo with Yarn PnP to illustrate the current behavior vs. expectations?

**Comment by ksorv** [comment]
Here @chaance https://github.com/ksorv/remix-monorepo-example

Please run: `yarn run setup` and then `yarn start` on the root.

Also plz ignore the react-router-dom as that I've not looked into, Might have to raise an issue for that :)

**Comment by penx** [comment]
Related https://github.com/remix-run/remix/issues/683

**Comment by lensbart** [comment]
Somewhat related: when running `yarn dlx create-remix@latest` instead of `npx create-remix@latest`, you get the following error:

> Error: @remix-run/dev tried to access .bin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

`yarn dlx` is the idiomatic way to run packages without installing when using Yarn, and is analogous to `npx`.

**Comment by MichaelDeBoey** [comment]
Closed by #1316
