### ISSUE TITLE
[Bug]: v1.1.0 - npx create-remix creates a project with a missing "app/styles" folder

### ISSUE THREAD

**Issue by ronb1982** [remix-run/remix#1126]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.0

### What version of Node are you using? Minimum supported version is 14.

14.16.1

### Steps to Reproduce

- Create a new project by running `npx create-remix@latest`
- Notice that there is no `styles` folder anymore in the `app` directory. 

I was able to create a full project successfully (including the styles folder) on 1.0.6.

This problem began occurring on Dec 17th, 2021 around 8 PM Eastern time.

### Expected Behavior

I can create a Remix project with all necessary components, folders, and files.

### Actual Behavior

- missing "app/styles" folder
- other files might also be missing, but I'm not sure

**Comment by chaance** [comment]
This is intended. We decided that new projects should be a blank slate so that it's easier to move faster with your new app. Folks were always expected to delete our starter files anyway :)
