### ISSUE TITLE
feat: Detect when Remix tries to start on a running port

### ISSUE THREAD

**Issue by royanger** [remix-run/remix#1127]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.0

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

This happens on a Windows 10/11 platform.

1. Start a React project (in this case I started something created from create-react-app) and it launches on port 3000.
2. Start Remix with 'npm run dev' and it also starts on port 3000. 

### Expected Behavior

When remix starts, I would expect an error, a prompt to run an another port, etc.

### Actual Behavior

Remix runs 'in  the background'. The original project continues to run on port 3000 and the remix project is inaccessible. Once I Ctrl-C and stop the original app, then a reload on the same browser results in the remix app loading.

**Comment by chenc041** [comment]
Has a pr already [#871](https://github.com/remix-run/remix/pull/871)

**Comment by royanger** [comment]
I saw the PR, but still reported this as in my case it wasn't erroring out/detecting that the port wasn't free. I didn't dig in too much, but I wasn't sure that the PR would resolve this issue.

**Comment by chenc041** [comment]
I am not sure what your situation is, maybe you can check this issue [#752](https://github.com/remix-run/remix/issues/752)

**Comment by royanger** [comment]
Remix is starting on the same port as another, already running app. No errors, no fail, no message. It just runs and until I stop the other App the remix app in inaccessible. https://streamable.com/7thnlf

**Comment by machour** [comment]
This have been fixed, starting remix on a running port now prints errors in the console:

```
Error: listen EADDRINUSE: address already in use :::3080
```

Let us know if you're still facing this issue on the newest version !
