### ISSUE TITLE
[Bug]: Hot Reload not working with Cloudflare Pages

### ISSUE THREAD

**Issue by wallyfaye** [remix-run/remix#1137]
### What version of Remix are you using?

^1.1.1

### What version of Node are you using? Minimum supported version is 14.

v17.0.1

### Steps to Reproduce

>
    npx create-remix@latest
    # choose Cloudflare Pages
    cd [whatever you named the project]
    npm run dev

- Edit the file `app/routes/index.jsx`
- Observe the `File changed` log in your console as well as the related logs
- Observe that http://127.0.0.1:8788/ has not changed
- Refresh the page
- Observe that http://127.0.0.1:8788/ has not changed
- Ctrl+C to stop the npm script
- run `npm run dev` again
- Observe that the edit to `app/routes/index.jsx` is now present
- edit the file again
- observe that the change are still not present

### Expected Behavior

We'd expect the changes to be immediately apparent

### Actual Behavior

The changes are not visible until the process has be stopped and restarted using the `npm run dev` command

**Comment by jacob-ebey** [comment]
This is a known issue and is in Cloudflare's hands to get Wrangler@v2 to support additional watch directories: https://github.com/cloudflare/wrangler2/issues/49

**Comment by drewdecarme** [comment]
If you haven't seen it, checkout [this comment](https://github.com/cloudflare/wrangler2/pull/71#issuecomment-1002921960) where you can now install `wangler@pages` and hot reloading should work. It doesn't seem like other attached issues have been updated... but for now, installing the pages package enables hot reloading for me.

**Comment by schpet** [comment]
@drewdecarme appreciate the tip! that worked for me as well

**Comment by dan-cooke** [comment]
Hot reload is not working on Architect Sandbox either. #1601  I mentioned this here.

**Comment by and3rsonsousa** [comment]
Not working on o remix 1.1.3 and 1.2.2 even with wrangler@pages.

**Comment by tulup-conner** [comment]
For me, the browser needs to refresh twice in order to see updates.

So each hot reload shows the second-most-recent update, not the one I just made.

This is pretty annoying for my workflow. :(

```
"@remix-run/cloudflare": "^1.5.1",
"@remix-run/cloudflare-pages": "1.5.1",
"@remix-run/dev": "^1.5.1",
"@remix-run/react": "1.5.1",
"wrangler": "^0.0.0-bafa5ac"
```

I started another project with Remix + Cloudflare Pages about 8 weeks ago and I remember noticing that one of the version upgrades I made caused this to start happening. I don't really know enough about what's going on to say if this might be an issue with `wrangler` also/instead.

**Comment by lili21** [comment]
not working with cloudflare workers too.

![image](https://user-images.githubusercontent.com/4456380/199641687-73dd41e6-5bc7-4130-884b-f697cf0754de.png)

**Comment by acoreyj** [comment]
Anyone making any progress on this or can point me in the right direction to make a fix? having the issue myself.

**Comment by pcattori** [comment]
We've implemented a new platform-agnostic dev server in #5133 which will be available under the `unstable_dev` flag in the next minor release.

**Comment by kishanhitk** [comment]
@pcattori Can you help me make it work with cloudflare-pages? 
[Here](https://github.com/remix-run/remix/discussions/5462) is the discussion.

**Comment by acusti** [comment]
i’m trying to make the new dev server + HMR work with cloudflare-workers (using miniflare). i would love to help debug by testing any suggestions and combinations / permutations of configs to see if i can get it to work. my current issue is that i cannot get the websocket server to run, or at least not on any port that i can identify. i documented some of my attempts in [this discussion](https://github.com/remix-run/remix/discussions/2384#discussioncomment-5194900).

**Comment by pcattori** [comment]
Obsoleted by #6133 .

You should now be able to use the `-c`/`--command` to run miniflare or any other local app server w/ the Remix dev server.
Be sure to follow the [instructions in the 1.16 release notes](https://github.com/remix-run/remix/releases/tag/remix%401.16.0) to set up the dev server correctly.

**Comment by jacob-ebey** [comment]
You can give the unstable dev server a run on cf pages and cf workers with the following commands:

Pages
```sh
npx create-remix@latest --template https://github.com/remix-run/remix/tree/templates_v2_dev/templates/cloudflare-pages
```

Workers
```
npx create-remix@latest --template https://github.com/remix-run/remix/tree/templates_v2_dev/templates/cloudflare-workers
```
