### ISSUE TITLE
Can't import node builtins in a route module

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#114]
I tried with crypto/fs, both broken. You have to move it to a different file and import from there.

https://discord.com/channels/770287896669978684/771068344320786452/828673055777095720

**Comment by Haroenv** [comment]
`events` also has this issue. I was using a package that uses the npm version of events, but somehow it still resolves to the node builtin in the browser (unless I alias it to something else, but it's hard to do in this case, as it's quite deep in the module tree)

```
Watching Remix app in development mode...
It appears you're using a module that is built in to node, but you installed it as a dependency which could cause problems. Please remove events before continuing.
💿 Built in 10ms
```

**Comment by Haroenv** [comment]
When I use a package that transitively depends on `events`, I get this:

https://github.com/Haroenv/remix-bug-report/blob/487e5b242e5ee377165e77da80f526d00c95191b/app/routes/index.tsx#L3

<img width="1440" alt="Screenshot 2021-11-23 at 11 36 52" src="https://user-images.githubusercontent.com/6270048/143009287-3b38c54d-acf5-49cc-91a8-2568dfc21ca7.png">

> Dynamic import of "events" is not supported

I guess somehow it tries to import the builtin still?

**Comment by jtsiskin** [comment]
Same here: 
![image](https://user-images.githubusercontent.com/11904459/143153182-5ca5cb32-17a8-4ac9-aab6-1f57b66c9644.png)

within /public/build it tries to import events module:
![image](https://user-images.githubusercontent.com/11904459/143153335-33eb5ae5-1f54-470b-9932-e66b71e084e2.png)
![image](https://user-images.githubusercontent.com/11904459/143153358-05c37573-55ef-4666-a9b3-c30c6d0fb940.png)

**Comment by jtsiskin** [comment]
@mjackson are you able to fix this? You currently can't use any module which uses the 'events' in the browser in remix. 
It needs to be bundled not external
For the simplest repo just `var EventEmitter = require("events");` and `console.log(EventEmitter)`

https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler.ts#L310

![image](https://user-images.githubusercontent.com/11904459/143658222-9434baf9-538f-4796-b2cc-276eebc02d34.png)

**Comment by jtsiskin** [comment]
For anyone who needs a temporary workaround while this is fixed, here's my hack:
`npm i patch-package`
`npm install @esbuild-plugins/node-modules-polyfill`
`npm install @esbuild-plugins/node-globals-polyfill`

add this patch to patches/ : https://gist.github.com/jtsiskin/9f661fc35d5c4d1e91239f9b319693e0
`npx patch-packages`

Inside my root.tsx, within my <head>, I then added
`<script> var global = global || window; </script>`

After than I had no more dependency issues

**Comment by arthuryeti** [comment]
@jtsiskin for some reason, it looks my remix setup is not using my patch version of @remix-run/dev. Do you `npm install @remix-run/dev`? I've tried many setup, but it doesn't seems to work.

**Comment by arthuryeti** [comment]
@jtsiskin thank you! I'll update your gist for remix 1.1.3

**Comment by arthuryeti** [comment]
@afk-mario thank you ser

**Comment by teopalva** [comment]
Team, any way we can prioritize this fix? I'm seeing several projects blocked by the lack of polyfills for node globals, eg https://github.com/status-im/status-web/pull/290 https://github.com/DePayFi/widgets/issues/62#issuecomment-1212702271
