### ISSUE TITLE
[Bug]: Can no longer access header values sent through JSON helper via `loaderHeaders.get`

### ISSUE THREAD

**Issue by rjgux** [remix-run/remix#1140]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.14.0

### Steps to Reproduce

If I try to access headers sent via the JSON HTTP helper within my exported `headers` function, the values are always null -

```
import { json } from 'remix'

export let loader: LoaderFunction = async () => {
  let data = await getData()

  return json(data, {
    headers: {
      'Cache-Control': 'max-age=300, s-maxage=300, stale-while-revalidate',
      'Some-Random-Header': 'some-random-value',
    },
  })
}

export function headers({ loaderHeaders }: { loaderHeaders: Headers }) {
  console.log(loaderHeaders.get('Cache-Control')) // null
  console.log(loaderHeaders.get('Some-Random-header')) // null
  return {
    'Cache-Control': loaderHeaders.get('Cache-Control'),
  }
}
```

### Expected Behavior

`loaderHeaders.get('Cache-Control')` value is `'max-age=300, s-maxage=300, stale-while-revalidate'`
`loaderHeaders.get('Some-Random-header')` value is `'some-random-value'`

### Actual Behavior

`loaderHeaders.get('Cache-Control')` value is `null`
`loaderHeaders.get('Some-Random-header')` value is `null`

**Comment by Xiphe** [comment]
having the same issue in a regular route. 

(Same code as above but with a default component export)

**Comment by marbiano** [comment]
Can confirm that this is happening to me too.

**Comment by ryanflorence** [comment]
I'm not getting anything here, can ya'll make a reproduction on `https://remix.run`?

```js
import { json } from "remix";
import type { HeadersFunction } from "remix";

export function loader() {
  return json(null, { headers: { "X-Test": "SUCCESS!" } });
}

export let headers: HeadersFunction = ({ loaderHeaders }) => {
  return {
    "X-Test": loaderHeaders.get("X-Test") || "FAILED!"
  };
};

export default function HeadersRoute() {
  return <div>Check the headers, should have X-Test: "SUCCESS!".</div>;
}
```

^ that works for me.

**Comment by ryanflorence** [comment]
Please reopen when you

**Comment by xstevenyung** [comment]
I found a workaround by making sure your parents' routes have loaders to prevent this issue.

e.g.:

if you are trying to use `loaderHeader.get` in `app/routes/my-awesome-route@headers` make sure that your `app/root@loader` is defined.

From what I can see, you need to make sure all parents have a loader if your route is nested.

Here a StackBlitz with Ryan's example working after adding the root loader function: https://stackblitz.com/edit/node-nndrjq?file=app/root.tsx
