### ISSUE TITLE
[Bug]: Deploying to Vercel fails with MDX: no such file or directory, scandir '/var/task/output/server/pages/api/_build/posts'

### ISSUE THREAD

**Issue by moniac** [remix-run/remix#1144]
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.8.1

### Steps to Reproduce

1. Setup project, select Vercel as deployment target
2. Added MDX content (locally, in a `posts` folder.
3. Load said content through mdx-bundler
`const postsPath = path.join(__dirname, "posts");`
4. Deploy to Vercel
5. Navigate to any page that uses the blog

### Expected Behavior

For it to load the blog posts successfully when deployed.

### Actual Behavior

`There was an error
ENOENT: no such file or directory, scandir '/var/task/output/server/pages/api/_build/posts'`

I have tried moving the posts folder to the root as well, but it always returns this error.

The repository in question is [here](https://github.com/moniac/portfolio-2022).

**Comment by techmind-git** [comment]
This issue is discussed on the discord channel of Remix and some have confirmed that it works (haven't tested myself though): https://discord.com/channels/770287896669978684/778004202282287104/970206208311054356
Maybe it helps.
