### ISSUE TITLE
useFetcher load() shows confusing message when invoked improperly

### ISSUE THREAD

**Issue by arvigeus** [remix-run/remix#1148]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.2

### Steps to Reproduce

```tsx
// routes/index.tsx
import { useFetcher } from "remix";

export default function Index() {
  const fetcher = useFetcher();
  fetcher.load("/data");
  if (!fetcher.data) return null;
  return <div>{JSON.stringify(fetcher.data)}</div>
}
```

### Expected Behavior

Error that hints the incorrect usage of `fetcher.load()`.

This code is taken from the [example docs](https://remix.run/docs/en/v1/api/remix#fetcherload). Addressed in ##1152

### Actual Behavior

`ReferenceError: AbortController is not defined`

**Comment by geocine** [comment]
I am actually calling `fetcher.load()` outside of a hook and it works well but I call it inside an event handler like so
```jsx
<button onClick={() => fetcher.load("/data")} />
```

**Comment by zachdtaylor** [comment]
@geocine yeah, as long as `fetcher.load()` isn't called during the server render, it's fine. So calling it in a callback like you have there is the correct way to use it 🙂

**Comment by kiliman** [comment]
```ts
const fetcher = useFetcher();
useEffect(() => {
  if (fetcher.type === 'idle') {
    fetcher.load("/data");
  } else if (fetcher.type === 'done') {
    console.log(fetcher.data)
  }
}, [fetcher]);
```
fetcher.load should be called in an event handler or useEffect().

**Comment by machour** [comment]
This is now properly documented, thank you @zachdtaylor !
