### ISSUE TITLE
[Feature]: Document how to use SASS with Remix (similar to PostCSS/Tailwind)

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#1170]
### What is the new or updated feature that you are suggesting?

Add to the [Styling guide](https://remix.run/docs/en/v1/guides/styling) in the docs how to run SASS in a separate process to output CSS and then load it into the app.

### Why should this feature be included?

A lot of people is asking this since a lot of people still uses SASS or SCSS. There's an issue #707 asking for support where the approach to build and link is explained too and I have saw more people on Discord asking for it.

**Comment by chenc041** [comment]
I found @mcansh create a repository [remix-examples](https://github.com/mcansh/remix-examples)
That repository includes two examples, one of sass and another tailwind

**Comment by sergiodxa** [comment]
> I found @mcansh create a repository [remix-examples](https://github.com/mcansh/remix-examples)
> That repository includes two examples, one of sass and another tailwind

An external repo wouldn’t help, I think this should either be in the docs site or at least move the example app to the examples folder in this repo, new users will probably not find that repo or will not niños Logan works at Remix at that’s the recommended approach.

**Comment by mcansh** [comment]
@sergiodxa plan is to move it over, just wanted a sample repo before hand :)

**Comment by machour** [comment]
Examples were added to the repo.
