### ISSUE TITLE
[Feature]: Documentation for enabling ESM Server bundle

### ISSUE THREAD

**Issue by Girish21** [remix-run/remix#1183]
### What is the new or updated feature that you are suggesting?

Add documentation for enabling ESM for server bundle

### Why should this feature be included?

ESM for server bundle is supported from [`V1.1.0`](https://github.com/remix-run/remix/releases/tag/v1.1.0) but documentation for enabling ESM and pitfalls are missing in the main documentation.

**Comment by mecurc** [comment]
Hm, looks like it didn't work atm
https://github.com/remix-run/remix/issues/1279

**Comment by machour** [comment]
Documented in https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages
