### ISSUE TITLE
[Bug]: Failed to load resources deployed to the secondary directory 

### ISSUE THREAD

**Issue by aofong** [remix-run/remix#1198]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

I need to deploy to a secondary directory, but the file fails to load after deployment 
address : http://127.0.0.1/nisweb/

```js
module.exports = {
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  publicPath: "./build/",    //Modified to relative path 
  serverBuildDirectory: "build",
  devServerPort: 8002,
  ignoredRouteFiles: [".*"],
};
```

### Expected Behavior

success 

### Actual Behavior

![image](https://user-images.githubusercontent.com/3070161/147112088-b8794194-95e3-4e32-a185-d59bca1a2e3f.png)

**Comment by prencher** [comment]
To add a data point to this, it appears to 404 if you change `publicPath` at all - e.g. changing it to `/public/` from `/build/` also breaks.

**Comment by machour** [comment]
So much have changed since Remix 1.1.1 .. 
I'm going to close this issue, please open a new one if this is still a problem on the latest remix version 🙏🏼
