### ISSUE TITLE
Image assets are not generated if path is passed from loader

### ISSUE THREAD

**Issue by arvigeus** [remix-run/remix#1200]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.2

### Steps to Reproduce

```tsx
import { LoaderFunction, useLoaderData } from "remix";

import imageSrc from "./image.jpg";

export const loader: LoaderFunction = () => {
  return imageSrc;
};

export default function Index() {
  // This does not work
  // const imageSrc = useLoaderData<string>();
  // return <img src={imageSrc} alt="img" />;

  // This works
  return <img src={imageSrc} alt="img" />;
}
```

NOTE: Clear `/public/build/`, restart server, and `Ctrl+F5` to force refresh.

Use case: I have bunch of images I want to pass a json objects.

### Expected Behavior

Should generate image assets both times

### Actual Behavior

String paths are generated both cases. When using loader to pass the path no assets are generated.

**Comment by machour** [comment]
Seems to be working on 1.11.1 👍🏼
