### ISSUE TITLE
[Feature]: user-defined plugins add to `remix.config.js`

### ISSUE THREAD

**Issue by vuesets** [remix-run/remix#1209]
### What is the new or updated feature that you are suggesting?

Add user-defined plugins to project.

I found that MDX was added in the source code in the form of plug-in. Is it possible to develop this interface so that users can customize the content of plug-in  

### Why should this feature be included?

We often need to add features to enrich the capabilities of the project.  A lot of functionality can be developed by the community if you can customize plug-ins.

**Comment by vuesets** [comment]
- #707 
- #1170

**Comment by pupudu** [comment]
A much needed feature. One good example is SVGR.

**Comment by chaance** [comment]
We have plans to expand the scope of our compiler, but we're still exploring the implications of that. We do not plan to open it up for plugins in the mean time as implementation details are likely to change often between stable releases. In the mean time, users will need to run processing for things like CSS and MDX as a separate Node process.

**Comment by pupudu** [comment]
@chaance if there are plans to add support, but not ready yet, can we keep the issue open? Thanks.

**Comment by chaance** [comment]
@pupudu We would like to keep issues reserved for bugs and features that are actively in progress. Discussions are a great place to share ideas for new features and get feedback before we decide to move on anything.
