### ISSUE TITLE
[Feature]: remix routes command

### ISSUE THREAD

**Issue by Weyker** [remix-run/remix#1211]
### What is the new or updated feature that you are suggesting?

a command to print the actual routes defined with the layout or the type of route
for example:

```
$ npx remix routes
Route               File                         Layout
/blog               blog/index.tsx               routes/blog.tsx
/blog/categories    blog/categories.tsx          routes/blog.tsx
/blog/authors       blog.authors.tsx             root.tsx
/product            __marketing/product.tsx      routes/__marketing.tsx
/dashboad           __app/dashboard.tsx.         routes/__app.tsx
/$userId/profile    __app/$userId/profile.tsx    routes/__app.tsx
```

### Why should this feature be included?

Sometimes its needed to see what its happening with routes, fast debug, fast bug fixes in production, etc

**Comment by tchak** [comment]
It's already there: `remix routes --json`

**Comment by Weyker** [comment]
My God! Thanks @tchak 
It will be better if this and other remix commands were explained in the documentation 😆
