### ISSUE TITLE
fetcher.load is causing the whole page to reload

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#1220]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1 (1.0.6 also)

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

```js
  let movies = useFetcher();
  useEffect(() => {
    movies.load(`/api/movies?q=Lord+of+the+rings`);
  }, []);
```

### Expected Behavior

The document shouldn't reload

### Actual Behavior

The document is reloading!

Whether I call `load` from a combobox input or simply on mount in a `useEffect`, the whole document reloads.

I've added a default export to the route, and also removed it, thinking maybe it had to do with our resource routes, but in both cases it reloads.

It might have something to do with our auto `window.reload` if an asset isn't found and maybe my build hashes got out of whack? Not sure yet.

![image](https://user-images.githubusercontent.com/100200/147260039-7e5475d6-ddb1-4911-b805-84f057da614d.png)

**Comment by ryanflorence** [comment]
Oh yep, I'm getting into this code:

https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/remix-react/routeModules.ts#L109-L117

Not sure why yet.

**Comment by kentcdodds** [comment]
Would this cause useFetcher to follow redirects? (Which I didn't think they were supposed to do): https://github.com/remix-run/remix/discussions/1204

**Comment by ryanflorence** [comment]
Found it. It's because I had server code in my movies route so the try/catch around loading the module reloaded the page. Once I got that out it worked fine.

Our work to automatically mark our route entries as side-effect free (or the better error message) that we're already working on will make this a non-issue.

Anyway, solution is like any other time you get server code in browser bundles, move the imports into a separate file (and if you feel like, it, tack on `*.server.js` to the file.

@kentcdodds `useFetcher().load` should not follow redirects in the fetch, but instead redirect the app (especially for unauthenticated calls), but a raw `fetch` to a resource route will *follow the redirect for the fetch* but not redirect the app.

**Comment by nickjs** [comment]
@ryanflorence Thanks for the follow up and clarification, glad you found your issue 😄. Just to make sure I'm understanding correctly, `useFetcher()` _should_ navigate the app if a loader or action explicitly `return redirect()`s?

If that's correct, then I believe https://github.com/remix-run/remix/discussions/1204 is still a valid RFC to improve UX for users without javascript and DX for developers who want to use fetchers.
