### ISSUE TITLE
[Bug]: During postinstall, "remix is not recognized as a command" error

### ISSUE THREAD

**Issue by skitterm** [remix-run/remix#1233]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

17.3.0

### Steps to Reproduce

When attempting to setup a project as part of the [Blog tutorial instructions](https://remix.run/docs/en/v1/tutorials/blog), things fail on the `postinstall` step, preventing me from continuing on with the project.

To reproduce:
1. Run `npx create-remix@latest`
1. Make the following choices:
```
? Where would you like to create your app? ./my-remix-app
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server     
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```
1. Observe that the command fails (on the `postinstall` step by the looks of it), with the following error:
```
'remix' is not recognized as an internal or external command,
operable program or batch file
```

I'm on Windows 10, build 19043.1415. I'm wondering if this is OS/OS-version-specific since no-one else has run across the same issue.

I also tried using v1.0.6 instead, but same result.

### Expected Behavior

The `postinstall` script should run successfully.

### Actual Behavior

The `npx create-remix` command fails. Full console error below:

```
$ npx create-remix@latest

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./my-remix-app
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript       
? Do you want me to run `npm install`? Yes

> postinstall
> remix setup node

'remix' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\<path-to-the-project>\my-remix-app
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c remix setup node

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Local\npm-cache\_logs\2021-12-24T20_32_23_844Z-debug-0.log
Error: Command failed: npm install
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (C:\Users\curly\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:205:19) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2968,
  stdout: null,
  stderr: null
}
```

**Comment by luffy84217** [comment]
@skitterm Could you provide the version of npm? I'm on Windows 10 Home, build 19042.1415, and using version of node 17.3.0  the same but cannot reproduce.

**Comment by skitterm** [comment]
@luffy84217 thanks for reaching out. I'm on NPM v`8.3.0`.

**Comment by luffy84217** [comment]
@skitterm Have you ever tried running `npm cache clean --force` before running `npx create-remix@latest`? If it doesn't work, I think you should inspect `my-remix-app/node_modules/.bin/remix.cmd` to check environment variables...

**Comment by ssisk** [comment]
I ran into this issue as well when docker-izing a remix express app. I haven't run into the issue outside of docker (I'm running on MacOs)

The solution I found was to move the @remix-run/dev entry in package.json  from devDependencies over into dependencies   

https://github.com/ssisk/create-remix-docker has a repro of the issue (see debug-notes.md for a bit more discussion of how I set the repro up and what else I tried)

**Comment by mabadir** [comment]
I am having the same issue, and I think the issue is related to having this `postInstall` command:
`"postinstall": "remix setup node"`
This command depends on `@remix-run/dev` which is a devDependency.

So basically running install command with `production` flag removes remix cli, and the postInstall command fails.

I hope that helps.

For the time being, for those impacted, moving `@remix-run/dev` as a production dependency is probably going to fix that. Not sure if the remix team has any thoughts about that, if that will pose any security concerns.
