### ISSUE TITLE
[Bug]: Fails to initialise when "." is used as app name inside a pre-initialed git repo

### ISSUE THREAD

**Issue by AbhinavRobinson** [remix-run/remix#1242]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.17.3

### Steps to Reproduce

- Create a git repo with `.gitignore` and clone to local
- `cd` into repo folder
- `npx create-remix@latest`  or use `@1.1.1`
- `? Where would you like to create your app? ./`
- (choose which ever option moving ahead, I used typescript and vercel)

### How I created my repo

```
➜  remix-apps gh repo create test_remix
? Visibility Internal
? Would you like to add a .gitignore? Yes
? Choose a .gitignore template Node
? Would you like to add a license? No
? This will create the "test_remix" repository on GitHub. Continue? Yes
✓ Created repository AbhinavRobinson/test_remix on GitHub
? Clone the remote project directory "AbhinavRobinson/test_remix"? Yes
```

### Expected Behavior

Created remix app in `./` dir with vercel and typescript config.

### Actual Behavior

```
➜  test_remix git:(main) npx create-remix@latest

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.
? Where would you like to create your app? ./
? Where do you want to deploy? Choose Remix if you're unsure
, it's easy to change deployment targets. Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
Error: dest already exists.
    at /Users/abhinavrobinson/.npm/_npx/5164864a48bff686/node_modules/fs-extra/lib/move/move.js:49:31
    at /Users/abhinavrobinson/.npm/_npx/5164864a48bff686/node_modules/universalify/index.js:22:54
    
➜  test_remix git:(main) ✗ yarn             
yarn install v1.22.17
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@remix-run/vercel > @remix-run/server-runtime@1.1.1" has unmet peer dependency "react@>=16.8".
warning "@remix-run/vercel > @remix-run/server-runtime@1.1.1" has unmet peer dependency "react-dom@>=16.8".
warning "@remix-run/serve > @remix-run/express > @remix-run/server-runtime > react-router-dom@6.2.1" has unmet peer dependency "react@>=16.8".
warning "@remix-run/serve > @remix-run/express > @remix-run/server-runtime > react-router-dom@6.2.1" has unmet peer dependency "react-dom@>=16.8".
warning "@remix-run/serve > @remix-run/express > @remix-run/server-runtime > react-router-dom > react-router@6.2.1" has unmet peer dependency "react@>=16.8".
warning " > @remix-run/vercel@1.1.1" has unmet peer dependency "@vercel/node@^1.8.3".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ remix setup node
/bin/sh: remix: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    
➜  test_remix git:(main) ✗ yarn dev
yarn run v1.22.10
warning package.json: No license field
$ remix dev
/bin/sh: remix: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sbernheim4** [comment]
This looks like you need to run an npm install. No was selected when the remix setup script asked if you wanted it to install. That's why the remix command can't be found. 

Run 

npm install

in the root of your project folder.

**Comment by AbhinavRobinson** [comment]
Oh my bad, I had run `yarn` but forgot to include in this, will edit this.

**Comment by AbhinavRobinson** [comment]
Added `yarn` command output  ✅

**Comment by AbhinavRobinson** [comment]
To my understanding something `might` but going wrong here

```
Error: dest already exists.
    at /Users/abhinavrobinson/.npm/_npx/5164864a48bff686/node_modules/fs-extra/lib/move/move.js:49:31
    at /Users/abhinavrobinson/.npm/_npx/5164864a48bff686/node_modules/universalify/index.js:22:54
```

Maybe a conflict with the existing .gitignore file? Not sure.

**Comment by AbhinavRobinson** [comment]
@sbernheim4 Please let me know if this is a user error, in which case I will close this :)

**Comment by sbernheim4** [comment]
Hi, just to clarify I'm not a contributor or maintainer. Just was browsing through the issues and thought this might have been an easier fix. Sorry its not :(. 

From the error - the first thing I'd be curious to know is what shows up if you run `ls -al` in the same folder as you're trying to create a project. If so removing any old files or folders sticking around may solve the issue. 

If that doesn't work, from your previous comment I would go into that file  `move.js:49:31` and see what folder or file it's trying to create - that might inform what's going wrong.

**Comment by AbhinavRobinson** [comment]
I don't believe this is a critical bug, one solution is to delete the `.gitignore` and then run it. But again, it seems like a bug that can be fixed, and is more of a quality of life issue. 

Thanks for the reply and look around.
Cheers.

**Comment by sbernheim4** [comment]
Oh - I bet then that the the setup process attempts to create the gitingore file for you and fails when it sees one already exists.

**Comment by AbhinavRobinson** [comment]
Created a PR for this [#1336](https://github.com/remix-run/remix/pull/1336)
