### ISSUE TITLE
[Bug]: apps generated by cli should not be set private

### ISSUE THREAD

**Issue by veritem** [remix-run/remix#1243]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### What version of Node are you using? Minimum supported version is 14.

latest

### Steps to Reproduce

N/A

### Expected Behavior

N/A 

### Actual Behavior

I don't know why all apps generated by remix cli are set to private. This field should be removed, it doesn't make sense

**Comment by revelt** [comment]
The `private` setting prevents the package from accidentally ending up published to npm. It is not a bug!
