### ISSUE TITLE
[Bug]: error on vercel adapter when returning a stream

### ISSUE THREAD

**Issue by mbarto** [remix-run/remix#1244]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.3.0

### Steps to Reproduce

Use the following Resource Route to fetch a remote image and return it as a response:

```typescript
import { LoaderFunction } from "remix"

export const loader: LoaderFunction = async ({ params }) => {
    const imageRes = await fetch(<link to any remote PNG image>)

    return new Response(imageRes.body, {
        status: 200,
        headers: {
            "Content-Type": "image/png",
        },
    })
}
```

### Expected Behavior

When calling the Resource Route, I expect to get back the remote image in the browser. 
It works locally with Remix App Server

### Actual Behavior

When deployed on Vercel, I get an error:

```
ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","reason":{"errorType":"TypeError","errorMessage":"The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","code":"ERR_INVALID_ARG_TYPE","stack":["TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","    at new NodeError (internal/errors.js:322:7)","    at ServerResponse.end (_http_outgoing.js:811:13)","    at sendRemixResponse (/var/task/output/server/pages/node_modules/@remix-run/vercel/server.js:109:16)","    at /var/task/output/server/pages/node_modules/@remix-run/vercel/server.js:49:5","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Server.<anonymous> (/var/task/output/server/pages/api/___vc/__helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred
```

Maybe the error is here in vercel adapter source code: https://github.com/remix-run/remix/blob/main/packages/remix-vercel/server.ts#L130

```typescript
return res.end(response.body.pipe(res));
```

Should it be the following?

```typescript
return res.end(response.body.pipe(res.body));
```

**Comment by roelandmoors** [comment]
Vercel (aws lambda) only supports NodeJS 14. Maybe try that locally to see if you get the same error?

**Comment by christianhg** [comment]
Thank you for opening this issue. I can confirm that I have the same problem for the same scenario, and it works locally with Node.js v.14, but not on Vercel with Node.js v14.

**Comment by christianhg** [comment]
I've made a fresh repository to replicate the bug. The only code needed to do so is this: https://github.com/christianhg/remix-vercel-bug/commit/e27018c71738b0df5898a9c12ba692664aa0256c

On the frontpage, an `<img src="/unsplash">` tag is added. The `/unsplash` resource route makes an external request to `unsplash.com` to fetch the image. 

This works locally, but when deployed to Vercel, the image request results in an error `500`: https://remix-vercel-bug.vercel.app/

The log for the request shows this on Vercel:

```
[GET] /unsplash
10:49:45:20
2021-12-29T09:49:45.305Z	b2195f75-fa20-40cb-ac19-809b6c2cf549	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","reason":{"errorType":"TypeError","errorMessage":"The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","code":"ERR_INVALID_ARG_TYPE","stack":["TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","    at new NodeError (internal/errors.js:322:7)","    at ServerResponse.end (_http_outgoing.js:811:13)","    at sendRemixResponse (/var/task/output/server/pages/node_modules/@remix-run/vercel/server.js:109:16)","    at /var/task/output/server/pages/node_modules/@remix-run/vercel/server.js:49:5","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Server.<anonymous> (/var/task/output/server/pages/api/___vc/__helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer. Received an instance of ServerResponse","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred
```

**Comment by christianhg** [comment]
I couldn't get this to work on Netlify either. I don't know a lot about serverless functions, but it seems that they don't support this scenario. I've tried deploying a Remix App Server to Heroku, and there it works.

**Comment by mbarto** [comment]
@christianhg @roelandmoors I did some more testing and I could make it work by chaing the vercel adapter sendRemixResponse final part from:

```typescript
function sendRemixResponse(res: VercelResponse, response: NodeResponse): void {
  ...
  res.writeHead(response.status, response.headers.raw());
  if (Buffer.isBuffer(response.body)) {
    return res.end(response.body);
  } else if (response.body?.pipe) {
    return res.end(response.body.pipe(res));
  }
  return res.end();
}
```

to:

```typescript
function sendRemixResponse(res: VercelResponse, response: NodeResponse): void {
  ...
  res.writeHead(response.status, response.headers.raw());
  if (Buffer.isBuffer(response.body)) {
    res.end(response.body);
  } else if (response.body?.pipe) {
    response.body.pipe(res);
  } else {
    res.end();
  }
}
```

I would be very happy to prepare a PR for this fix, but I have some difficulties with writing a proper unit test for it. Any suggestion from developers?

**Comment by valerie-makes** [comment]
I can reproduce this bug. My use case is more or less the same as @mbarto's - I have an image resource route which essentially proxies another origin, using `fetch()` to get the image and directly returning the response object.
