### ISSUE TITLE
@remix-run/firebase

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#125]
Probably just grab David East's template and go.

**Comment by ccssmnn** [comment]
What features should this template include?

Probably Auth & Firestore.

I would love to help.

**Comment by Ehesp** [comment]
The template is probably reference to https://github.com/davideast/remix-starter-firebase (Remix adapter for running on Firebase Functions)

**Comment by ccssmnn** [comment]
Alright, so this Issue is about firebase as a deployment target, not about an example on how to use remix and firebase together.

**Comment by Ehesp** [comment]
I'd assume so yeah given the title :) 

Although a Remix + Firebase example would probably be worthwhile too.

**Comment by chaance** [comment]
Probably not going to add an adapter for this anytime soon, though something in the `examples` directory would be great. Also a great candidate for someone to build a stack on top of. Closing for now since there's nothing actionable for us.
