### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by drFabio** [remix-run/remix#1262]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

17.0.2

### What version of Node are you using? Minimum supported version is 14.

v14.18.2

### Steps to Reproduce

Programatically submit a post form to index, it will not work by default.

Take this form 
```jsx
import { ActionFunction, useActionData, useSubmit } from "remix";

export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();

  return {
    values: formData.get("fromClient"),
  };
};
export default function Index() {
  const submit = useSubmit();
  const data = useActionData();

  const handleClick = () => {
    const formData = new FormData();
    formData.set(`fromClient`, `someValue`);
    submit(formData, { method: "post"  });
  };
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <h1>Trying to programatically submit</h1>
      <p>Result: {data?.values}</p>
      <input type="hidden" name="fromClient" value="someValue"></input>
      <button type="button" onClick={handleClick}>
        Send it
      </button>
    </div>
  );
}

```

On clicking it it will show the following error:

> Error: Route "root" does not have an action, but you are trying to submit to it. To fix this, please add an `action` function to the route

Consider the declarative variant:
```jsx
import { ActionFunction, Form, useActionData } from "remix";

export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();

  return {
    values: formData.get("fromClient"),
  };
};
export default function Index() {
  const data = useActionData();
  return (
    <Form method="post">
      <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
        <h1>Trying to programatically submit</h1>
        <p>Result: {data?.values}</p>
        <input type="hidden" name="fromClient" value="someValue"></input>
        <button type="submit">Send it</button>
      </div>
    </Form>
  );
}
```

### Expected Behavior

The action behavior of the declarative form and the hook one should be identical.
A useSubmit on index should work with Post with just the method change

### Actual Behavior

Submiting with the useSubmit hook from index will misguidedly search for a action on "root" not on index.

The error seems to come [from here](https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/remix-react/transition.ts#L923-L928) on the matches selection.

I am not so sure on the details but this seems like a missbehavior in my opinion.

**Comment by jacob-ebey** [comment]
"index" routes are special and require a `?index` param to post too. The reason for this is as you described above: layout and index routes have the same path and to distinguish what what to post too, the `?index` param is used.

To submit to your "index" route, you would set your action to be `/?index`.
