### ISSUE TITLE
How to update data in loader?

### ISSUE THREAD

**Issue by MoNSTRiKcom** [remix-run/remix#1271]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

last

### What version of Node are you using? Minimum supported version is 14.

-

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

There is a loader with data:
```js
export async function loader() {
  return { ok: `Hello` };
}
```

There is an action through which I want to update the data in the loader so that they are available in child components:
```js
export const action: ActionFunction = async ({ request }) => {
  return { ok: `Hello` };
}
```

How to do it?

**Comment by sergiodxa** [comment]
You need to store that date somewhere else, update in the action and read in the loader.

Some ideas:
- A variable in the same file (if you don't need persistence between server reloads)
- A cookie (if you are cookie with the data going back to the original after the cookie expires or is cleared)
- A database (this is the safest and probably what you should do)

**Comment by MoNSTRiKcom** [comment]
Thank you friend! I assumed that it was possible only by such methods, but I hoped that magic exists. I will use an effector
