### ISSUE TITLE
[Bug]: Remix cannot build/start with esm

### ISSUE THREAD

**Issue by dima-takoy** [remix-run/remix#1279]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

Just test here — https://stackblitz.com/edit/github-ve8jgl?file=package.json (i set `"type": "module"` and `serverModuleFormat: 'esm'`

Steps to reproduce:
1. Try `npm run build` and/or `npm start`

### Expected Behavior

It can build and start

### Actual Behavior

Error loading Remix config because require cannot be used in inside esm module

https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/remix-dev/config.ts#L201

**Comment by heyymarco** [comment]
me too. importing ESM node_modules causing [ERR_REQUIRE_ESM] because the generated **build/index.js** is a common JS.

**Comment by machour** [comment]
Tracked in #109
