### ISSUE TITLE
[Bug]:  cloudflare pages adapter does not support livereload?

### ISSUE THREAD

**Issue by willin** [remix-run/remix#1280]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [X] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

@remix-run/cloudflare-pages 1.1.1

### What version of Node are you using? Minimum supported version is 14.

17.2

### Steps to Reproduce

minial project: https://github.com/w2fs/remix-blog-demo

```js
"scripts": {
    "build": "cross-env NODE_ENV=production remix build",
    "build:css": "postcss styles/**/*.css --base styles --dir app/styles",
    "build:css:prod": "npm run build:css -- --env production",
    "dev": "cross-env NODE_ENV=development run-p dev:*",
    "postinstall": "remix setup cloudflare-pages",
    "dev:css": "npm run build:css -- --w",
    "dev:remix": "remix watch",
    "dev:wrangler": "wrangler pages dev ./public --watch ./build ./styles",
    "start": "npm run dev:wrangler"
  }
```

use  `yarn dev`

### Expected Behavior

when styles or components changed, page should livereload.

### Actual Behavior

even fresh manually cannot take effect. 

only `⌃ + C` and restart works

**Comment by rvcas** [comment]
I am also experiencing this issue

**Comment by lawrencecchen** [comment]
You can temporarily fix this by installing `wrangler@pages`

https://github.com/cloudflare/wrangler2/pull/71#issuecomment-1002921960

**Comment by rvcas** [comment]
Thanks I'll test this in a few minutes

**Comment by rvcas** [comment]
@lawrencecchen ok I can confirm, that worked

**Comment by simontong** [comment]
This worked for me also
