### ISSUE TITLE
[Bug]: Cookies unable to encode UTF-8 strings

### ISSUE THREAD

**Issue by shamsup** [remix-run/remix#1282]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [X] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

any

### What version of Node are you using? Minimum supported version is 14.

14+

### Steps to Reproduce

from https://github.com/sergiodxa/remix-auth/issues/115 (@thangngoc89)

Try to encode a cookie  with a UTF-16 string - ie `"Nguyễn Văn A"`

Essentially `btoa` expects a string to be binary, so encountering characters that are UTF-16 encoded with more than 8 bits will throw an error. This is well-documented by [Mozilla](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem). In JSON and JavaScript, strings are UTF-16, so representing the characters is not an issue. However, this means that `JSON.stringify`ing a string does not make it safe for `btoa`.

### Expected Behavior

Cookie properly set :sunglasses:

### Actual Behavior

Cookie is not set _and_ error is swallowed

**Comment by nimaa77** [comment]
some one missed reading this section while they were developing remix
 https://developer.mozilla.org/en-US/docs/Web/API/btoa#unicode_strings

**Comment by machour** [comment]
Fixed in #2257 🎉
