### ISSUE TITLE
[Bug]: importing ESM node_module causing ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by heyymarco** [remix-run/remix#1283]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

v16.13.1

### Steps to Reproduce

install @nodestrap/navbar using NPM:
npm i @nodestrap/navbar

then import & render the <Navbar>
import { Navbar } from '@nodestrap/navbar'

....
<Navbar></Navbar>
....

### Expected Behavior

it should run perfectly. Tested in nextjs / react app with no problem

### Actual Behavior

error [ERR_REQUIRE_ESM]: require() of ES Module ..... from ....index.js not supported.
Instead change the require .... to a dynamic import() which is available in all CommonJS modules.

I saw the problem is the generated **build/index.js** is a common js.
It tries to import an **ESM module** using `require('some-esm-module')`

Is there any way to change the generated **build/index.js** as ESM module?
CommonJS **cannot import** ESM but ESM **can import** CommonJS.

**Comment by egoist** [comment]
should also add esm support for `remix.config.js`

**Comment by egoist** [comment]
Seems you can use `serverModuleFormat: "esm"` in remix config to build the server in esm format, but ideally it should automatically output as esm if  `type: "module"` is set in `package.json` (which is required to run esm module in Node.js unless you also output the server build as `.mjs`). 

However currently Remix uses `require` to load `remix.config.js`, which won't work with `type: "module"` 😅

**Comment by heyymarco** [comment]
`serverModuleFormat: "esm"` => still doesn't work.

nowadays there are a lot of esm modules in npm, so all of them don't work in remix.
I'm going back to NextJS, not as futuristic as remix, but it works.

**Comment by tchak** [comment]
I am not going back to `NextJS` but I will be very happy when I can remove from my `package.json` all the pinning on previous versions for `npm` packages that migrated to `esm`...

**Comment by Adam-Collier** [comment]
I am also having this issue

**Comment by sjones6** [comment]
According to the source code `serverModuleFormat: 'esm'` specifies the output mode (i.e., to output either esm or cjs) and not whether or not it will compile ES modules from `node_modules`:

https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/remix-dev/config.ts#L170

**Comment by wanbinkimoon** [comment]
+1 esm support is needed

**Comment by pradeepa45** [comment]
+1 esm supprt is needed

**Comment by zayenz** [comment]
See documentation on gotchas for how to import ESM-modules: https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages

**Comment by machour** [comment]
Tracked in #109

**Comment by Ricky428** [comment]
I tried this gotcha approach mentioned in the remix documentation while I was using nanoId() and it didn't work and today itself when I was trying to use swiper it didn't work.
Any Solution to this?

**Comment by yehudamakarov** [comment]
@Ricky428 I'm also trying [the solution](https://remix.run/docs/en/1.19.0/file-conventions/remix-config#serverdependenciestobundle) but the CLI tells me 
> `my package` is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
meanwhile the exact string of the package is in `serverDependenciesToBundle` and I get the same error

**Comment by yehudamakarov** [comment]
i just opened #6928

**Comment by yarapolana** [comment]
This might not work for everyone, but it worked for me.

```
module.exports = {
  ...
  serverModuleFormat: 'cjs', // or 'esm' both worked
  serverDependenciesToBundle: [
    /^@uppy.*/, // 👈🏼 notice the way its written
    /^nanoid.*/,
  ],
  ...
```

**Comment by seungha-0709** [comment]
@yarapolana Thanks! You nailed it!! Your solution worked for me and I don't get this error anymore.

**Comment by deadcoder0904** [comment]
> This might not work for everyone, but it worked for me.
> 
> ```
> module.exports = {
>   ...
>   serverModuleFormat: 'cjs', // or 'esm' both worked
>   serverDependenciesToBundle: [
>     /^@uppy.*/, // 👈🏼 notice the way its written
>     /^nanoid.*/,
>   ],
>   ...
> }
> ```

Adding `esm` worked for me instead of `cjs`. Before that, I got this error:

```bash
 💿  remix dev

 info  building...
 info  built (2.8s)
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'D:\Code\Remix\example.com\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/Code/Remix/example.com/build/<stdin>:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at run (D:\Code\Remix\example.com\node_modules\.pnpm\@remix-run+serve@2.5.1_typescript@5.3.3\node_modules\@remix-run\serve\dist\cli.js:113:15)
```

Previously, I got the filename here so I changed it from `.js` to `.cjs` but now no filenames so was confused.
