### ISSUE TITLE
`useFetcher().submit` client side validation is wrong

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#1291]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

```js
// in routes/some-layout
// URL at /some-layout/some-param

let fetcher = useFetcher()
let action = useFormAction()
console.log(action)
fetcher.submit({}, { method: "post", action })
```

### Expected Behavior

It should post to the layout route.

### Actual Behavior

It doesn't ever submit to the server and logs this error in the browser:

> transition.js:858 Uncaught (in promise) Error: Route "routes/some-layout/index" does not have an action, but you are trying to submit to it. To fix this, please add an action function to the route

What's really strange is that the `action` string is correct, it's `"/some-layout"`. Looks like calling `fetcher.submit()` does some validation in the client against the route manifest and incorrectly validates the an action on "routes/some-layout/index" instead of "routes/some-layout".

## Two Bugs To Fix 

1. The error boundary should have caught this, but didn't, fix that first.
2. (my guess is) the validation is just wrong, have it look for the correct route, or just skip validation in the client and let the server handle it.

**Comment by ryanflorence** [comment]
@jacob-ebey I think we missed a spot with our `?index` action disambiguation in 0.19 (0.20?)

**Comment by anonrig** [comment]
Hi @ryanflorence 

I'm seeing a familiar problem where the route has an action function but using fetcher.submit with URLSearchParams throws the same error. I'm attaching the logs.

[remix-error.log](https://github.com/remix-run/remix/files/7849821/remix-error.log)

**Comment by LANCENET** [comment]
What is it

**Comment by chaance** [comment]
Closed in https://github.com/remix-run/remix/pull/2271
