### ISSUE TITLE
Rewrite line number / file in error server error logging

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#131]
Would be sweet too get these to point to the real file, then in VSCode you can just click the file and go right to the line :D

Would definitely need source maps, but I think I've seen this done before, I have no idea how to do it though.

![image](https://user-images.githubusercontent.com/100200/96357424-c92b0a00-10b8-11eb-82d6-d10e73986812.png)

**Comment by chikamichi** [comment]
Hi @ryanflorence and the team :)

Any idea how high (or low…) this would get prioritized now that the v1 has been released?

**Comment by chaance** [comment]
We're tracking this internally so I'm going to close it for now. This is a DX enhancement we will absolutely improve soon.
