### ISSUE TITLE
[Bug]: loader in a nested route returns `undefined` when a `Form` is submitted in a parent route

### ISSUE THREAD

**Issue by sairajchouhan** [remix-run/remix#1317]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.1

### Steps to Reproduce

- Open the sandbox 👉 https://codesandbox.io/s/zealous-chihiro-72x1f?file=/README.md
- Navigate to `/cart` page
- Click on `submit` button

### Expected Behavior

1. Mutation due to `Form` submission in  `routes/cart.jsx`  **should** re-execute the `loader` functions in
   1. `routes/cart.tsx`
   2. `routes/cart/index.tsx`
2.  And the return value of the loader function in `routes/cart/index.tsx` **should not** be `undefined`

### Actual Behavior

1. Mutation due to `Form` submission in  `routes/cart.jsx`  **does not** re-execute the `loader` function in
   1. `routes/cart/index.tsx`
2.  And the return value of the loader function in `routes/cart/index.tsx` **is** `undefined`

**Comment by revelt** [comment]
Similar thing is going on with `links`, I filed #1326

**Comment by sairaj2119** [comment]
I just did some hack to fix my current problem but this has to work

**Comment by brophdawg11** [comment]
Thanks for the reproduction @sairajchouhan!  This should have been fixed in [v1.3.4](https://github.com/remix-run/remix/releases/tag/v1.3.4) via #2466.  I ran a quick test locally and it looks resolved to me, so I'm going to close this - please let me know if it's still an issue for you

**Comment by revelt** [comment]
good job @brophdawg11 !
