### ISSUE TITLE
Make the build/run script delete the build output after making the new files

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#132]
That way we don't end up with huge build directories like this:

![image](https://user-images.githubusercontent.com/1500684/117054544-6fe29b00-acd7-11eb-97da-db184a346689.png)

**Comment by chaance** [comment]
Hi! I'm not a bot, but I'm closing out old issues that have long grown stale and are likely not up-to-date with recent versions. Feel free to ping me if this is still an issue and I can reopen.
