### ISSUE TITLE
0.17 Docs - Nested Routes and Params, Styling

### ISSUE THREAD

**Issue by epitaphmike** [remix-run/remix#133]
I am confused about a line in this portion of the docs

> We'll talk about that <Outlet> in a sec. First let's make a loader at data/routes/team.ts.
https://github.com/remix-run/remix/blame/master/docs/tutorial/4-nested-routes-params.md#L59

And there is a typo pointing users to `members` instead of `team`
https://github.com/remix-run/remix/blame/master/docs/tutorial/4-nested-routes-params.md#L146

Another typo "Buld"
https://github.com/remix-run/remix/blame/master/docs/guides/styling.md#L61

Add link to [postcss-cli](https://github.com/postcss/postcss-cli)
https://github.com/remix-run/remix/blame/master/docs/guides/styling.md#L60

**Comment by machour** [comment]
Not applicable anymore
