### ISSUE TITLE
Docs Issue: Async missing from data loader example 

### ISSUE THREAD

**Issue by MuddyBootsCode** [remix-run/remix#136]
I know this is super nit-picky but async is missing from this data loader example on https://docs.remix.run/v0.17/tutorial/3-loading-data/ on line 23:
`export let loader: LoaderFunction = () => {
  let res = await fetch("https://api.github.com/gists");
  let gists = await res.json();
  return json(gists, {
    headers: {
      "Cache-Control": "max-age=300"
    }
  });
};`

Should be:
`export let loader: LoaderFunction = async () => {
  let res = await fetch("https://api.github.com/gists");
  let gists = await res.json();
  return json(gists, {
    headers: {
      "Cache-Control": "max-age=300"
    }
  });
};`

**Comment by machour** [comment]
Not applicable anymore
