### ISSUE TITLE
[Bug]: Error information is lost in the client when throwing from the server

### ISSUE THREAD

**Issue by ivosabev** [remix-run/remix#1360]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

```tsx
import type {LoaderFunction} from 'remix';

class CustomError extends Error {
  constructor(message?: string) {
    super(message);
    this.name = 'CustomError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export const loader: LoaderFunction = async () => {
  const error = new CustomError();
  console.log('Server', error instanceof CustomError);
  throw error;
};

export default function Play() {
  return null;
}

export function ErrorBoundary({error}: {error: Error}) {
  console.log('Client', error instanceof CustomError);
  return null;
}
```

### Expected Behavior

```
Server true
Client true
```

### Actual Behavior

```
Server true
Client false
```

When testing the error object in the client it has lost its identity of CustomError.

Maybe related to https://github.com/remix-run/remix/issues/1357

**Comment by Xilonz** [comment]
Ran into the same issue. 
The errors get serialized during while passed to the error boundary. I too would like have the original Error so we can catch an authorization error from our graphql client and handle it appropriately. 

Serialization:
https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/errors.ts#L65
on the document request:
https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/server.ts#L268

**Comment by jongbelegen** [comment]
It's interesting that this only happens when making an SSR request. Loaders do not lose information when you navigate to a next page from a already rendered app for example .

**Comment by machour** [comment]
Remix 1.11.1 currently outputs : 

```
Server true
Client true
```

so it seems like this is fixed.

**Comment by penx** [comment]
If you end up here for the same reason I did... you may want to read about [Error Sanitization](https://remix.run/docs/en/main/guides/errors#error-sanitization) and consider using `throw json` from your loaders and actions.
