### ISSUE TITLE
Referer header value change when submitting a form with JS

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#137]
If you submit a form without JS the Referer headers is the correct URL including the query string, but if you use the Form component with JS the Referer is set to the pathname only and it strips the query string

**Without JS**

```
Referer: http://localhost:3000/write?id=6092de7ab361c7ceac921cc2
```

**With JS**

```
Referer: http://localhost:3000/write
```

**Comment by mcansh** [comment]
does this still happen @sergiodxa?
