### ISSUE TITLE
More and Better Types!

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#138]
Can collect all of our the type enhancements we need here:

- [ ] `MetaFunction` receive a generic for the type of the data argument and maybe the parentsData too so you don't have to cast:

    ```ts
    // boo
    const { article } = data as FooData;

    // instead do this
    export let meta: MetaFunction<FooData?, BarParentsData?>  = ({ data }) => {}

    // which pairs nicely with this
    let data = useRouteData<FooData>;
    ```

**Comment by chaance** [comment]
Closing this as we've done a lot already to enhance many of the types discussed. I would encourage folks who still have issues with specific types to open a separate issue or submit a PR!
