### ISSUE TITLE
[Feature]: Link that renders a component instead of HTMLAnchor

### ISSUE THREAD

**Issue by SferaDev** [remix-run/remix#1382]
### What is the new or updated feature that you are suggesting?

Right now navigation requires to use anchors with ``<Link />`` or ``<NavLink />``, for some use cases, though, we have interactive UIs where a click on a component triggers navigation instead of an anchor.

### Why should this feature be included?

We can currently use ``useNavigate`` hook for those scenarios, but we loose the ability to prefetch without adding more code. An exposed component that renders children and handles navigation + prefetch would simplify a lot the usage.

```tsx
interface ComponentLinkProps {
    to: string;
    prefetch?: PrefetchBehavior;
}

const ComponentLink: React.FC<ComponentLinkProps> = ({ to, prefetch = "none", children, ...props }) => {
    const navigate = useNavigate();
    const href = useHref(to);
    const [shouldPrefetch, prefetchHandlers] = usePrefetchBehavior(prefetch, props);

    return (
        <>
            <span {...prefetchHandlers} {...props} onClick={() => navigate(href)} role="link">
                {children}
            </span>
            {shouldPrefetch ? <PrefetchPageLinks page={href} /> : null}
        </>
    );
};
```

**Comment by ccssmnn** [comment]
Navigating with anchor elements is what HTML does. You can wrap anything in an anchor element, or make them look like whatever you would want. Do you have an example, where an interactive UI is not possible with the `Link` or `NavLink` component?

**Comment by ccssmnn** [comment]
And there is the example. #1609 

Sorry, that wasn't clear to me.

**Comment by sergiodxa** [comment]
The correct option is to wrap that component in an anchor tag so it’s clickable

Navigation should be triggered by a link click or form submit only.
