### ISSUE TITLE
[Docs]: Notify user to install package `front-matter`. 

### ISSUE THREAD

**Issue by jmjpro** [remix-run/remix#1390]
### Which Remix packages are impacted?

- [x] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

Read instructions for https://remix.run/docs/en/v1/tutorials/blog#pulling-from-a-data-source

### Expected Behavior

When adding a new package front-matter, instruct the user to install this package.

### Actual Behavior

No instruction is given. The user receives a runtime error  `Cannot find module 'front-matter'`.

**Comment by arrudaricardo** [comment]
The tutorial is asking to install front-matter as `npm add front-matter`, however, **npm add** is not a valid command, you need to `npm install front-matter` or `yarn add front-matter`.

**Comment by kennethvdberghe** [comment]
I think this is instructed in the docs?
![image](https://user-images.githubusercontent.com/68184728/148822607-3c1868e3-8d8f-45b7-8980-2d17c7b5c5a2.png)

**Comment by machour** [comment]
Yes it is
