### ISSUE TITLE
[Bug]: Loader data requests should have the same response headers as page requests

### ISSUE THREAD

**Issue by ccssmnn** [remix-run/remix#1392]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

v16.13.1

### Steps to Reproduce

1. Create remix project
2. Create two pages with loaders and use data from loaders in the page
3. Set custom response headers ( Cache Control Headers ) using the exported headers method
4. Add Navigation between these pages with the link component.
5. Start the dev server.
6. Navigate from one page to the other using the link and check the response headers
7. Refresh the page and check response headers again.

### Expected Behavior

The data request which only calls the loader has default (cache-control) headers.

The request to the route has custom (cache-control) headers.

### Actual Behavior

Both should have the same headers.

---

The current workaround looks like this:

```javascript
const loader = () => {
  return "Hello World";
}
```

should be changed to

```javascript
import { json } from "remix";
const loader = () => {
  return json("Hello World", { headers: headers() });
}
```

to manually set the same headers in the loader response.

---

I think it should be the default to send the same headers for both the route call and the data call. Remix-Users could manually set different headers using a method like the current workaround. This not being the default makes the experience of navigating remix pages slower than it should be, unless developers find out and use this workaround.

**Comment by JClackett** [comment]
Can confirm this as well, if I don't specify cache headers in the loader (even though I am exporting a headers function with cache headers) client side navigation/fetch doesn't cache the loader response, so navigating to any page with a loader becomes quite laggy.

The initial load on some pages is fast though as the server side rendered document is cached.

Not sure if this is the desired functionality but it may catch a few people out (as it has for me!)

**Comment by jacob-ebey** [comment]
The flow goes like this:

Document request -> loader -> headers({loaderHeaders}) -> response
Data request -> loader -> response

You want to attach headers to the `json` return from the loader and propagate those to the document via the headers export.

**Comment by ryanflorence** [comment]
This docs goes into detail about all of this: https://remix.run/docs/en/v1/api/conventions#headers

> That is all to say that Remix has given you a very large gun with which to shoot your foot.

**Comment by ccssmnn** [comment]
@jacob-ebey that clarifies the situation, even though I don't see why the data requests headers should differ from the document requests by default, when a headers method is present.

@ryanflorence I don't see this behaviour explained in the docs. When using the `Link` components extensively, visitors usually navigate with data requests. Not being aware of this behaviour could produce extra compute costs and slower websites. The docs could be clearer about this in the header section or we could change the behaviour of data requests to include the headers, that are defined for the document, by default.

**Comment by JClackett** [comment]
Yeah makes sense now, but I agree with @ccssmnn, I think it might be worth clarifying in the docs that the headers function is for the document only (i.e initial load), and headers returned in the loader function  are for the fetch/xhr only (unless you pass them to the headers function as well). I read the docs and I still thought that the headers function was for headers in general but you could override them if you wanted to from the loaders.

**Comment by jacob-ebey** [comment]
> @jacob-ebey that clarifies the situation, even though I don't see why the data requests headers should differ from the document requests by default, when a headers method is present.
> 
> @ryanflorence I don't see this behaviour explained in the docs. When using the `Link` components extensively, visitors usually navigate with data requests. Not being aware of this behaviour could produce extra compute costs and slower websites. The docs could be clearer about this in the header section or we could change the behaviour of data requests to include the headers, that are defined for the document, by default.

The "headers" export will always be just for document requests. Data defines any headers it needs itself, the whole point of the "headers" export is to filter out / combine headers from the multiple loader / action calls that make up the data of the HTML document. For example: if you may have multiple cache control headers from "root.js", "routes/__layout.js" and "routes/__layout/the-route.js", you'll want to take the one with the smallest value. When these loaders are called in a data request, they naturally return and use their own headers. Hope this helps explain why this is the case and why it won't change.

**Comment by JClackett** [comment]
I don't think it should change but do think the docs need to be a bit clearer, I'm willing to bet this won't be the last time someone misunderstands this :)
