### ISSUE TITLE
[Bug]: Vercel deployment does not work in monorepo

### ISSUE THREAD

**Issue by joshuaellis** [remix-run/remix#1398]
### Which Remix packages are impacted?

- `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

* Clone this repo – https://github.com/joshuaellis/remix-monorepo
* run `yarn` from the project root
* deploy to a vercel server as you normally would with a monorepo

### Expected Behavior

It should run fine as if it were not in a monorepo setting

### Actual Behavior

This error runs when the project is deployed to vercel. You can see the crash at this url – https://remix-monorepo.vercel.app/

And see the function log here:

![image](https://user-images.githubusercontent.com/37798644/148517927-dbdd0a6d-885c-410e-b2b0-956853304516.png)

Additionally it could be linked to this issue:
- https://github.com/vercel/turborepo/discussions/496

And you can see (what i think to be) a `semi-hack` here:
- https://github.com/remix-run/remix/pull/1375/files#diff-4a9f202e0d83dc1b2a10e568207faba0438f5d020d7ca34a848d25259629b4d4R16

**Comment by julesmils** [comment]
Another workaround/hack would be to disable dependency hoisting just on the remix child package. This will make your dependencies messier but unless Vercel changes their implementation this is the more straightforward solution.

so in the child package.json:

```
"workspaces": {
    "nohoist": ["**"]
},
```

**Comment by airjp73** [comment]
@julesmils, When I tried `nohoist`, it didn't work with other local packages from the monorepo - just `node_modules`.

The issue ultimately comes down to the fact that `remix` doesn't bundle server dependencies. (See @ryanflorence's discord comment [here](https://discord.com/channels/770287896669978684/770287896669978687/928351150552518708)). Vercel includes the whole monorepo in the build step, but not in the actual deployment, so we lose all the dependencies in the root `node_modules`. I think on Vercel's end this kinda makes sense.

If we were able to enable server bundling in `remix.config.js` or if that's just how it worked, that would solve this issue. That's also why the `turborepo-vercel` example works. Remix doesn't bundle the server dependencies, but we can do it ourselves as a workaround.

**Comment by julesmils** [comment]
@airjp73 got it. `nohoist` won't work in that case.

**Comment by zifahm** [comment]
I tried the rollup hack too, but it still says missing "react"

**Comment by Tanner-Scadden** [comment]
I have tried the rollup hack as well as using the new transpileModules option in remix.config. I get missing module "react" or "@remix-run/vercel". Has anyone been able to get a monorepo with remix to work on vercel?

**Comment by zifahm** [comment]
@Tanner-Scadden I retried the rollup hack and it worked.

Just clone the tuborepo-vercel example and also use this as your config file https://github.com/airjp73/remix-validated-form/blob/main/apps/docs/remix.config.js

**Comment by tirthGajjar** [comment]
adding 
```
...
  "serverDependenciesToBundle": [/.*/],
...
```
to remix.config.js worked for me.

**Comment by joshuaellis** [comment]
> adding
> 
> ```
> ...
>   "serverDependenciesToBundle": [/.*/],
> ...
> ```
> 
> to remix.config.js worked for me.

It would be helpful to know your version of `remix` so people can try the fix correctly :)

**Comment by wladiston** [comment]
@tirthGajjar solution actually did work!

https://github.com/wladiston/remix-vercel-monorepo

**Comment by zifahm** [comment]
The missing thing in that example is `serverBuildDirectory: "api/_build",` on your remix.config.js file

**Comment by joshuaellis** [comment]
spoke to Lee over twitter, who's saying this PR – https://github.com/vercel/vercel/pull/8077#issuecomment-1179634396, should resolve the issue. I have not tested yet, hope to give it a go over the next week & will report back if it's solved.

**Comment by MichaelDeBoey** [comment]
This should work now
