### ISSUE TITLE
[Feature]: Custom package path resolver

### ISSUE THREAD

**Issue by jaysoo** [remix-run/remix#1405]
### What is the new or updated feature that you are suggesting?

It would be useful to have support for custom path mappings when importing packages. Currently, you could customize some paths in tsconfig or jsconfig, but there are limitations (see below).

### Why should this feature be included?

In most build systems, users have the ability to customize package resolution. For example,

* webpack alias: https://webpack.js.org/configuration/resolve/#resolvealias
* TS `compilerOptions.paths`: https://www.typescriptlang.org/tsconfig#paths
* rollup `resolveId`: https://rollupjs.org/guide/en/#resolveid
* metro resolve: https://facebook.github.io/metro/docs/configuration#resolverequest

It would  be useful for Remix to allow this type of configuration as well, and would give [Nx](https://nx.dev) the ability to support lightweight workspace libs for Remix apps.

## Current solution and limitations

You can map paths in `tsconfig.json` or `jsconfig.json`, however there are some limitations.

1. Remix currently treats modules not prefixed with `.` or `~` as external, so they are not bundled at compile time (https://github.com/remix-run/remix/blob/7d1dda3/packages/remix-dev/compiler.ts#L411-L413).
2. In a monorepo setup you would configure the paths in a base config, not per-project. e.g. in `tsconfig.base.json` at the root of the monorepo. This conflicts with Remix's default paths as TS does merge paths.

## Example

Given a monorepo as follows:

```treeview
acme/
├── apps/
│   └── my-remix-app/
│       └── app/
│           ├── ...
│           └── routes/
│               └── index.tsx
└── libs/
    └── mylib/
        └── src/
            ├── ...
            └── index.ts
```

We want to map `@acme/mylib` to `libs/mylib/src/index.ts` so we can import it as such in our app.

```typescript
// apps/my-remix-app/routes/index.tsx
import { something } from '@acme/mylib`';
```

## Alternative solutions

1. Allow custom esbuild plugins so we can do the mappings ourselves via `onResolve` callback (https://github.com/remix-run/remix/issues/717).
2. Use yarn/npm workspaces. This adds the requirement that libraries must be compiled, and is highlighted as an issue with the current Nx support for Remix. https://twitter.com/victorsavkin/status/1478769919676268552

**Comment by Knaackee** [comment]
This and I could try remix. Monorepo support is essential to me.
