### ISSUE TITLE
[Bug]: useFetcher submit buttons don't include value when clicking on SVG children

### ISSUE THREAD

**Issue by AustinBrunkhorst** [remix-run/remix#1409]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

1. Create a `<button type="submit" />` with `name` and `value` for submitting a form managed by `userFetcher()`.

```jsx
const fetcher = userFetcher();

<fetcher.Form method="post">
  <button type="submit" name="vote" value="Upvote">
    <svg> ... </svg>
  </button>
</fetcher.Form>
```

2. Submit the form _**by clicking on the SVG element within the button**_.

Code sandbox repro: https://codesandbox.io/s/upbeat-mirzakhani-mq0bj?file=/app/routes/index.tsx

Notice how you can get the expected behavior by clicking outside of the SVG, but the bug occurs when you click on the icon.

### Expected Behavior

The form should be submitted with vote=Upvote when the button is clicked.

### Actual Behavior

The click event uses the form as the event target instead of the button. This omits the submitted button's value from the form data.

**Comment by AustinBrunkhorst** [comment]
A workaround is to use `pointer-events: none` on the `svg` element, but I wonder if this can/should be handled in `useSubmitImpl()`

**Comment by zachdtaylor** [comment]
+1, just ran into this bug as well

**Comment by chaance** [comment]
This was fixed at some point but we didn't catch this issue! Quick repro for you: https://stackblitz.com/edit/node-wu7qb4?file=app%2Froutes%2Findex.tsx
