### ISSUE TITLE
[Bug]: Unexpected "<"

### ISSUE THREAD

**Issue by mjr** [remix-run/remix#1412]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [x] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.2

### Steps to Reproduce

Create a default project. (`npx create-remix@latest`)
Rename the `root.jsx`, `entry.server.jsx`, `entry.client.jsx` and `routes/index.jsx` files to `.js`.
Run the project. (`npm run dev`)

https://codesandbox.io/s/goofy-kapitsa-8v7en

### Expected Behavior

Use `.js` extension and everything works as expected.

### Actual Behavior

I get error renaming files to `.js`.

```
Build failed with 2 errors:
error: Build failed with 1 error:
app/root.js:9:4: error: Unexpected "<"
error: Build failed with 1 error:
app/routes/index.js:3:4: error: Unexpected "<"
```

**Comment by MichaelDeBoey** [comment]
You need to keep using `.jsx` extension when you're using JSX in your file

**Comment by mjr** [comment]
It's not what @mjackson said here: https://github.com/remix-run/remix/discussions/1208#discussioncomment-1867972

**Comment by MichaelDeBoey** [comment]
`.js` files are supported, but whenever you are having components in your files, you need `.jsx` (see https://github.com/remix-run/remix/discussions/1208#discussioncomment-1861819)

**Comment by mjr** [comment]
What was said here https://github.com/remix-run/remix/discussions/1208#discussioncomment-1861819 is not true, you can check it in the `esbuild` [documentation](https://esbuild.github.io/content-types/#:~:text=This%20loader%20is%20enabled%20by%20default%20for%20.jsx%20and%20.tsx%20files.%20Note%20that%20JSX%20syntax%20is%20not%20enabled%20in%20.js%20files%20by%20default.%20If%20you%20would%20like%20to%20enable%20that,%20you%20will%20need%20to%20configure%20it:) and you can look at the Remix code [here](https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler/loaders.ts#L12) that the loader is used to accept `JSX` in a `.js` file.

**Comment by pazguille** [comment]
@mjr check this comment: https://github.com/remix-run/remix/discussions/1208#discussioncomment-2011376

**Comment by jacob-ebey** [comment]
JSX is only valid in `.jsx` files in the Remix compiler similar to how JSX is only valid in `.tsx` files, not `.ts`.

**Comment by pazguille** [comment]
Are you sure? https://github.com/remix-run/remix/discussions/1208#discussioncomment-1867972

**Comment by jacob-ebey** [comment]
> Are you sure? [#1208 (comment)](https://github.com/remix-run/remix/discussions/1208#discussioncomment-1867972)

Yes, I'm positive. You can use `.js` files obviously, but you can *not* use JSX is a `.js` file. We *could* make it so you can use jsx in `.js` files, but we did not. /end

**Comment by pazguille** [comment]
It’s weird and confused. I can use JSX in .js files like root.js, entry.server.js and entry.client.js but not in routes files. Honestly, it looks more like a bug.

**Comment by MichaelDeBoey** [comment]
@jacob-ebey is part of the Remix team, so I guess you can't be more right than he is 🤷‍♂️

**Comment by jacob-ebey** [comment]
> It’s weird and confused. I can use JSX in .js files like root.js, entry.server.js and entry.client.js but not in routes files. Honestly, it looks more like a bug.

Good catch, I'll make sure the rules also apply to convention files.

**Comment by pazguille** [comment]
> @jacob-ebey is part of the Remix team, so I guess you can't be more right than he is 🤷‍♂️

@MichaelDeBoey 👀
