### ISSUE TITLE
`*.json` imports get cast to strings

### ISSUE THREAD

**Issue by holic** [remix-run/remix#142]
https://github.com/remix-run/remix/blob/f1d6557511368c8832439235dc9a235ac7d95127/packages/remix-node/assetImportTypes.ts#L29-L32

I believe if we just remove this and [add `resolveJsonModule: true` to `tsconfig.json`](https://www.typescriptlang.org/tsconfig#resolveJsonModule), we'll get the right types for these imports.

I'm happy to open a PR if this seems reasonable!

**Comment by mcansh** [comment]
sorry for the delay on replying to this! this was fixed in #314 and released in [0.20.0](https://github.com/remix-run/remix/releases/tag/v0.20.0)
