### ISSUE TITLE
[Feature]: Support transpiling external modules

### ISSUE THREAD

**Issue by airjp73** [remix-run/remix#1423]
### What is the new or updated feature that you are suggesting?

It would be great to have the ability to have the remix compiler transpile local modules when working in a monorepo. Essentially this would be a remix equivalent to [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules).

One way to get this done currently is via a patch outlined [in this gist](https://gist.github.com/cj/c6d7a3b1fcf238073951762747c201ba). In the patch, there's a new config option in `remix.config.js`.

I believe this issue is also related to #1398. Looking at the compiler code, if we had the ability the bundle all server dependencies that might also solve the issue.

The exact implementation is not super important to me -- I'm more interested in the ability to do this than the api itself.

### Why should this feature be included?

It would be very useful for monorepos containing a remix app to be able to have the remix compiler transpile local modules from the monorepo. This makes it really simple & easy to create internal packages to share across multiple apps without the added friction of setting up a build step for each one.

This change also doesn't require opening up esbuild configuration options directly. The patch does touch remix's custom externals plugin, but this shouldn't impact remix's ability to switch compilers. If the remix team decided to switch another compiler, this could be done without breaking the api for this feature (though the functionality would have to be replicated with the other compiler).

**Comment by hannadrehman** [comment]
i m having same issue. need an ability to transpile local modules in a monorepo.

**Comment by hannadrehman** [comment]
thanks to [this](https://github.com/remix-run/remix/issues/717#issuecomment-1026030797) solution given to overide esbuild config i was able to build my local packages. 

i created `esbuild-overrides.js` 

added following code to allow custom packages

```js
const esbuild = require('esbuild');
const Module = require('module');

function manualExternalsPlugin() {
  return {
    name: 'manual-externals-overide',
    setup(build) {
      build.onResolve(
        {
          filter: /@YourNamespaceOrPackageName/,
        },
        (args) => {
          return {
            external: false,
            namespace: args.path,
          };
        },
      );
    },
  };
}

const originalRequire = Module.prototype.require;
const originalBuild = esbuild.build;

function build(options) {
  if (options.platform === 'node') {
    const { plugins } = options;
    const externalPlugin = plugins.find(
      (plugin) => plugin.name === 'manual-externals',
    );
    const localPlugins = plugins.filter(
      (plugin) => plugin.name !== 'manual-externals',
    );
    localPlugins.push(manualExternalsPlugin());
    localPlugins.push(externalPlugin);
    return originalBuild({
      ...options,
      plugins: localPlugins,
    });
  }
  return originalBuild({
    ...options,
  });
}

Module.prototype.require = function (id) {
  // when remix requires esbuild, it will get our modified build function from above
  if (id === 'esbuild') {
    return { ...esbuild, build };
  }
  return originalRequire.apply(this, arguments);
};
```

then added following scripts 

```json
"scrips": {
      "dev:patched": "NODE_OPTIONS='-r ./esbuild-overrides' remix dev",
     "build:patched": "NODE_OPTIONS='-r ./esbuild-overrides' remix build"
}
```

**Comment by cj** [comment]
fyi - transpile modules can be added to remix by just updating a few lines of code I came up with this a few months ago https://gist.github.com/cj/c6d7a3b1fcf238073951762747c201ba you can now just add `transpileModules` to your remix.config.js i.e.:

```javascript
/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  appDirectory: 'app',
  browserBuildDirectory: './public/build',
  publicPath: '/build/',
  serverBuildDirectory: './server/build',
  devServerPort: 8002,
  transpileModules: ['ui', 'lib', 'env'],
}
```

**Comment by cj** [comment]
@airjp73 @hannadrehman I created a pull request here https://github.com/remix-run/remix/pull/1806

**Comment by hannadrehman** [comment]
@cj  this is great. thanks.

**Comment by badeAdebayo** [comment]
> thanks to [this](https://github.com/remix-run/remix/issues/717#issuecomment-1026030797) solution given to overide esbuild config i was able to build my local packages.
> 
> i created `esbuild-overrides.js`
> 
> added following code to allow custom packages
> 
> ```js
> const esbuild = require('esbuild');
> const Module = require('module');
> 
> function manualExternalsPlugin() {
>   return {
>     name: 'manual-externals-overide',
>     setup(build) {
>       build.onResolve(
>         {
>           filter: /@YourNamespaceOrPackageName/,
>         },
>         (args) => {
>           return {
>             external: false,
>             namespace: args.path,
>           };
>         },
>       );
>     },
>   };
> }
> 
> const originalRequire = Module.prototype.require;
> const originalBuild = esbuild.build;
> 
> function build(options) {
>   if (options.platform === 'node') {
>     const { plugins } = options;
>     const externalPlugin = plugins.find(
>       (plugin) => plugin.name === 'manual-externals',
>     );
>     const localPlugins = plugins.filter(
>       (plugin) => plugin.name !== 'manual-externals',
>     );
>     localPlugins.push(manualExternalsPlugin());
>     localPlugins.push(externalPlugin);
>     return originalBuild({
>       ...options,
>       plugins: localPlugins,
>     });
>   }
>   return originalBuild({
>     ...options,
>   });
> }
> 
> Module.prototype.require = function (id) {
>   // when remix requires esbuild, it will get our modified build function from above
>   if (id === 'esbuild') {
>     return { ...esbuild, build };
>   }
>   return originalRequire.apply(this, arguments);
> };
> ```
> 
> then added following scripts
> 
> ```json
> "scrips": {
>       "dev:patched": "NODE_OPTIONS='-r ./esbuild-overrides' remix dev",
>      "build:patched": "NODE_OPTIONS='-r ./esbuild-overrides' remix build"
> }
> ```

This did not work for me.  I get an error `SyntaxError: Unexpected token 'export'` it looks like esbuild does not transpile the typescript file before loading it.  any idea on how to get it to do that from esbuild?

**Comment by adonaicandido** [comment]
This feature has been implemented in the latest release, although would be also helpful to watch those files and hot reload the browser.

Someone currently was a workaround here: #issuecomment-1033366665

**Comment by machour** [comment]
Implemented.
If the new implementation still doesn't fit your needs, please open a new issue 🙏🏼

**Comment by penx** [comment]
> This feature has been implemented in the latest release
@adonaicandido

> Implemented.
@machour 

Which feature is this in reference to? https://github.com/remix-run/remix/pull/1806 was closed without merge. I can see a reference to https://github.com/remix-run/remix/pull/1839 but `serverDependenciesToBundle` doesn't seem to be working for me (transpiling typescript from another package in a monorepo).


If I add

```json
 serverDependenciesToBundle: ["@my-namespace/other-package"],
```

I still get

```
Error: Cannot find module '@my-namespace/other-package'
```

(Where the entry point to this package is a ts file)

**Comment by ianwremmel** [comment]
@garretteklof not sure if this will help with your issue, but I just ran into it: I'm working in a monorepo and remix is one of many packages laid out via npm workspaces. I had `serverDependenciesToBundle` set to be an array of strings of the package names of each package defined in the repo. That stopped working after a recent update. I was able to fix it by changing those strings to RegExps. I believe it's matching individual filenames rather than the package.json names that worked previously.

**Comment by osdiab** [comment]
I am getting this warning in the console (though the dev server seems to work nonetheless):

```
The path "@shared/ui/styles" is imported in app/routes/index.tsx but "@shared/ui/styles" was not found in your node_modules. Did you forget to install it?
```

If I change the import in the route to `import styles from "@shared/ui/styles.ts"` then the warning goes away, but TypeScript says I shouldn't be importing a file with the `ts` extension. I'm not bothering transpiling the shared UI library since it's only being consumed inside my monorepo and I can control the transpilation.

I had added  `serverDependenciesToBundle: [/^@shared\//]` to my remix config, doesn't seem to be affecting things at a glance. Thoughts on how to get rid of this warning?
