### ISSUE TITLE
[Bug]: Compiling Cloudflare Worker results in error from Wrangler

### ISSUE THREAD

**Issue by kpalmvik** [remix-run/remix#1426]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

Create a new Remix `npx create-remix@latest` and select "Cloudflare Pages" / "TypeScript" / "Run npm".

Run `npm run dev` to start the dev server.

### Expected Behavior

The dev server starts without any errors.

### Actual Behavior

An error occurs:

```
...
> remix watch

Watching Remix app in development mode...
Compiling worker to "/var/folders/5w/rj0_j25j70g2_qcfpnr8w6m40000gn/T/functionsWorker.js"...
✘ [ERROR] Expected ";" but found ":"

    build/assets.json:2:11:
      2 │   "version": "25ffdec3",
        │            ^
        ╵            ;

1 error(s) and 0 warning(s) when compiling Worker.
Build failed with 1 error:
build/assets.json:2:11: ERROR: Expected ";" but found ":"
ERROR: "dev:wrangler" exited with 1.
```

This might be related to changes to the [most recent version of Wrangler `0.0.7`](https://github.com/cloudflare/wrangler2/releases/tag/wrangler%400.0.7), since everything works if I pin the version to `0.0.6`

**Comment by universse** [comment]
Same thing happens with Cloudflare Pages. Probably a wrangler issue.

**Comment by Rocinante89** [comment]
Cloudflare Pages is throwing the below for me on `npm run dev`

```
Watching Remix app in development mode...
Compiling worker to "/tmp/functionsWorker.js"...
✘ [ERROR] Could not resolve "../build"

    functions/[[path]].js:4:23:
      4 │ import * as build from "../build";
        ╵                        ~~~~~~~~~~

1 error(s) and 0 warning(s) when compiling Worker.
Build failed with 1 error:
functions/[[path]].js:4:23: ERROR: Could not resolve "../build"
ERROR: "dev:wrangler" exited with 1.
```

**Comment by markshenouda** [comment]
Same problem here

**Comment by traviseden** [comment]
I came across issue doing with Cloudflare Pages and solved it by running `npm run build` first. Then it worked as expected for `npm run dev`.

Wow! Remix is even faster than I was expecting.

**Comment by markshenouda** [comment]
Nope it didn't work for me :/

**Comment by universse** [comment]
From Remix discord, can try `wrangler@beta` instead of `alpha`.

**Comment by baezor** [comment]
I had the same issue when running 'npm run dev' for the first time. I fixed the issue by running the command twice.

**Comment by kpalmvik** [comment]
>@traviseden: I came across the same issue with Cloudflare Pages and solved it by running `npm run build` first. Then it worked as expected for `npm run dev`.

I can confirm this to work! ✅ 

Following the reproduction steps today I now get [the same `Could not resolve "../build"` error](https://github.com/remix-run/remix/issues/1426#issuecomment-1008432943) as @Rocinante89 mentioned. But if I then run `npm run build` followed by `npm run dev` the local server starts as expected, including automatic component reloading (still using Wrangler `alpha`).

>@baezor: I had the same issue when running `npm run dev` for the first time. I fixed the issue by running the command twice.

This does not work for me. Following the reproduction steps today I get exactly [the same `Could not resolve "../build"` error](https://github.com/remix-run/remix/issues/1426#issuecomment-1008432943), even if I run `npm run build` multiple times.

**Comment by markshenouda** [comment]
I found the bug! The problem is Wrangler requires Node 16 and I'm using Node 14 :(
```
Wrangler requires at least Node.js v16.7.0. You are using v14.18.2.
You should use the latest Node.js version if possible, as Cloudflare Workers use a very up-to-date version of V8.
```

**Comment by markshenouda** [comment]
Yes it works fine with me now! What I did:
- Uninstalled the current node version
- Installed NVM
- Installed the latest version of node with it

Then installed the version 14 because I need it for other projects

**Comment by liviuzachin** [comment]
> I came across the same issue with Cloudflare Pages and solved it by running `npm run build` first. Then it worked as expected for `npm run dev`.
> 
> Wow! Remix is even faster than I was expecting.

running `npm run build` to create the `build` folder worked for me too

**Comment by MichaelDeBoey** [comment]
@kpalmvik Is this still valid with the latest version of the templates?
