### ISSUE TITLE
Interop with webpack-style module federation

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#143]
Some larger sites that have bought into "micro frontend" (MFE) architecture with webpack's module federation feature may have a hard time adopting Remix for a portion of their site because we don't currently use webpack 5.

I had a discussion about this with the lead dev on Lululemon: https://twitter.com/ScriptedAlchemy/status/1390091785800589314

My understanding of how module federation works in webpack 5 is that in order to use it, you have to be using webpack and you have to build your giant site all at the same time so that webpack knows everything at once and is able to split up the modules in a deterministic way. This means that if we wanted to support webpack module federation, we would essentially need to use webpack. :/

**Comment by brendonco** [comment]
Would love to see Remix  collaborate with Module Federation. How can we help to scalable modularity both in component and page level?

**Comment by luistak** [comment]
The overall usage of module-federation is for micro frontends(MFs), so does Remix intend to support MFs in any other way? 

Maybe something like remote routes or sub-routes, which we could deploy different remix apps and maybe merge them using a container app, for example:

```tsx
const URL = 'https://my-micro-front-in-other.hostname';

export default function SomeRoute() {
  return (
    <main>
      {/* Normal route content */}
      <div>
        {/* Render my micro frontend */}
        <RemoteOutlet url={URL} />
      </div>
    </main>
  );
}
```

cc: @kentcdodds, @ryanflorence
