### ISSUE TITLE
[Bug]: Server Fetch API does not work behind proxy

### ISSUE THREAD

**Issue by jeremy-london** [remix-run/remix#1456]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [X] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

17.2.0

### Steps to Reproduce

When behind a proxy this call will fail to reach internet-based endpoint as the fetch polyfill does not support the use of proxy

-- Note browsers use the systems proxy by default so this only affects server side loads
```
const res = await fetch("https://swapi.dev/api/people/1/?format=json")
    const json = await res.json()
    console.log('json', json);
```

### Expected Behavior

Expected to use HTTP_PROXY, HTTPS_PROXY and NO_PROXY variables when making calls on server side

### Actual Behavior

Did not use HTTP_PROXY, HTTPS_PROXY and NO_PROXY variables when making calls on server side

**Comment by jeremy-london** [comment]
Just a follow-up, our company uses an HTTP proxy to route all traffic to the internet.. local machines are configured with these settings but Node processes generally do not use these settings unless configured to do so.

Generally this is solved using https://www.npmjs.com/package/global-agent

**Comment by mcansh** [comment]
> Generally this is solved using https://www.npmjs.com/package/global-agent
> 
> I do not see a way to inject any code into the server-side runtime as the server is running (In our case using the `@remix-run/architect` model)

have you tried adding `require('global-agent/bootstrap')` to your `server/index.js`?

**Comment by jeremy-london** [comment]
@mcansh That solved the proxy portion thank you!
