### ISSUE TITLE
[Bug]:  missing content on - https://remix.run/docs/en/v1/tutorials/blog

### ISSUE THREAD

**Issue by CoderCarl1** [remix-run/remix#1457]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

remix/latest

### What version of Node are you using? Minimum supported version is 14.

15.8

### Steps to Reproduce

Following the tutorial on remix site - [https://remix.run/docs/en/v1/tutorials/blog#your-first-route](https://remix.run/docs/en/v1/tutorials/blog#your-first-route)

- It advises the user to remove everything except the link to the posts. 
- This prevents the load of Children inside of index with the Outlet component.

> **It is mentioned inside the Jokes tutorial to use the Outlet component** - [https://remix.run/docs/en/v1/tutorials/jokes](https://remix.run/docs/en/v1/tutorials/jokes)

### Expected Behavior

With the <Outlet /> present inside the app/root.tsx the code works.

Maybe a code snippet to replace the contents of the <body> tag would work instead of just the Link
This keeps the Link and the Outlet present.

### Actual Behavior

no Children are rendered and a blank page.

**Comment by machour** [comment]
The documentation have been fixed
