### ISSUE TITLE
[Feature]: Add starter Templates like Next.js and Gatsby.js needs

### ISSUE THREAD

**Issue by ShafSpecs** [remix-run/remix#1469]
### What is the new or updated feature that you are suggesting?

New feat. 🚀: Allow for users to scaffold an app template through the CLI when installing the Remix app and allow users to install PostCSS plugins.

My idea for this is something like: `npx create-remix@latest --template-ecommerce --tailwind-enable`, where the template flag would allow users to choose from a predefined set of templates (that would be maintained by the community) and the tailwind (or postcss) flag would let users automatically set up default tailwind configs and scripts easily that they can edit and add to.

### Why should this feature be included?

Most times, when setting up a remix project, you have a pre-defined template in mind, or you are just a beginner who wants to try out a *particular* feature in Remix and the thing I face when I install a new app is an empty boilerplate. Some people want to start a project from blank  (that's why the flags would be optional) but others want to create a particular thing based on a theme (an authentication page, an ecommerce app, a blog, a tracker app, etc.) and I feel the ability for the users to have this feature of scaffolding plain, but usable and functional templates would be a great addition to remix.

**Comment by ShafSpecs** [comment]
I personally would love to work on this feature as templates and scaffolding I am passionate about when users attempt to use a product

**Comment by machour** [comment]
Closing this since we now have [Remix Stacks](https://remix.run/docs/en/v1/pages/stacks).
