### ISSUE TITLE
[Feature]: Custom routes declaration

### ISSUE THREAD

**Issue by luxferoo** [remix-run/remix#1480]
### What is the new or updated feature that you are suggesting?

Declare routes based on a custom routes builder or a Json file 

### Why should this feature be included?

This is mandatory for websites that support i18n and and which must have routes translated for SEO purposes .

For example : 

https://www.mister-auto.es/aceite-de-motor/
https://www.mister-auto.com/huile-moteur/

**Comment by sergiodxa** [comment]
You can do that right now using the routes function in remix.config.js

See https://remix.run/docs/en/v1/api/conventions#routes
