### ISSUE TITLE
[Bug]: ESBuild cannot resolve package

### ISSUE THREAD

**Issue by willin** [remix-run/remix#1508]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

https://github.com/willin/willin.wang/tree/feat/layout

```bash
yarn
npx contentlayer build
yarn dev
```

### Expected Behavior

start and work.

### Actual Behavior

`node_modules/.contentlayer/data` is auto generated.

```bash
Build failed with 1 error:
app/utils/posts.ts:1:25: error: Could not resolve ".contentlayer/data" (mark it as external to exclude it from the bundle)
💿 Rebuilt in 31ms
💿 Rebuilding...

 > app/utils/posts.ts:1:25: error: Could not resolve ".contentlayer/data" (mark it as external to exclude it from the bundle)
    1 │ import { allPosts } from '.contentlayer/data';
      ╵                          ~~~~~~~~~~~~~~~~~~~~

```

**Comment by silvenon** [comment]
```js
import { allPosts } from '.contentlayer/data/index.mjs';
```

**Comment by willin** [comment]
wonderful!

**Comment by needcaffeine** [comment]
@willin - do you still use contentlayer with remix? I’m encountering this “mark it as external” issue right now and unable to get past it. Thank you!
