### ISSUE TITLE
[Bug]: File uploads make app fail

### ISSUE THREAD

**Issue by veritem** [remix-run/remix#1510]
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

^1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

as it's documented [here](https://remix.run/docs/en/v1/api/remix#parsemultipartformdata-node), creating upload handler should work but it makes the app fail. 
![image](https://user-images.githubusercontent.com/53856673/149629219-215555f8-4293-42e3-8b10-99a9cfa82c3e.png)
an 

### Expected Behavior

It should have successfully created upload handler- without causing app to fail the 

### Actual Behavior

It doesn't allow creating an upload handler so that uploading files  can be seamless

**Comment by CanRau** [comment]
Could you please share a public repo or code snippet or something?

**Comment by machour** [comment]
Closing since no response was provided
