### ISSUE TITLE
[Bug]: invalid document id in url throws error in SSR

### ISSUE THREAD

**Issue by audiolion** [remix-run/remix#1511]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

Make a new remix app, start dev server, then append an id to the url #foo and it will throw an error on refresh.

### Expected Behavior

no errors to be thrown, people can append whatever they want to urls, it shouldn’t break SSR of your page

### Actual Behavior

page crashes and without an error boundary in place nothing is rendered besides the error

**Comment by silvenon** [comment]
I wasn't able to reproduce this, I created a new Remix app and selected Remix App Server as the deployment target.

**Comment by audiolion** [comment]
Maybe this is an issue with remix + wrangler. I will try to check soon

**Comment by chenc041** [comment]
I guess the same problem as this issue [#935](https://github.com/remix-run/remix/issues/935)

**Comment by audiolion** [comment]
@chenc041 ah yep, that is it. ill close this
