### ISSUE TITLE
[Feature]: Support loader functions for any component, not just routes

### ISSUE THREAD

**Issue by ryanking1809** [remix-run/remix#1514]
### What is the new or updated feature that you are suggesting?

Maybe there's a good reason not to do this, but it'd be great to be able to support the `loader` function in any component and have it work the way `<Outlet />` does in Route Components. (And perhaps the `action` function as well)

Say I had a Project Management app, with a `<InvoiceList />` component. The invoice list can be displayed in 3 routes, `./invoices`,`./project/{projectId}/invoices`, and `./client/{clientId}/invoices`. To display the invoice list we make the same api call with optional filters for client and project based on the context.

I can manually create each of the three pages and add the api to the invoice loader but if the data can be it can automatically be loaded with `<Outlet />` why not do the same with `<InvoiceList />`?
Maybe you could crawl .tsx / .jsx imports for `loader` functions?

For example:

_./components/InvoiceList.jsx_
```jsx
export let loader = async ({ params }) => {
   let { clientId, projectId } = params // unecessary but here for clarity
   return await getInvoiceList({clientId, projectId})
}

export let InvoiceList = () => {
    let invoices = useLoaderData();
    return <div>{invoices.map(i => <InvoiceItem invoice={i} /></div>
}
```

_./invoices.jsx, ./project/$projectId/invoices.jsx, ./client/$clientId/invoices.jsx_
```jsx
import { InvoiceList } from "~/components/InvoiceList.jsx"
// no need to worry about the data required from child components
// just render them and remix reads the child loaders
export let Invoices = () => {
    return <InvoiceList />
}
```

### Why should this feature be included?

I can manually pull in the loader of the `<InvoiceList />` for each of the 3 routes, adding it to their loaders. However, this gets more complex if say a child of `<InvoiceList />` needs an additional api request. If each component could define the data it needed then you would be able to spend less time preparing the data to be loaded beforehand in higher-level components.

**Comment by ccssmnn** [comment]
Each Loader is a route. Defining loaders inside your components would make no sense.

What would be nice though: consuming custom loaders which are defined as a [Resource Route](https://remix.run/docs/en/v1/guides/api-routes#resource-routes) from the route component.

We would be able to make calls like this:

```javascript
const routeData = useLoaderData() // default is the route loader
const invoiceData = useLoaderData("/api/invoices") // call resource routes
const userData = useLoaderData("/user") // call loaders from other components
```

I think this would also fit your use case quite nicely.

**Comment by ryanking1809** [comment]
Yeah, maybe it doesn't make sense. I believe you could use `useFetcher()` in your scenario if I'm not correct?

```js
const fetcher = useFetcher();
fetcher.load("/some/route");
fetcher.data;
```

**Comment by ccssmnn** [comment]
@ryanking1809 `fetcher` loads the data client side, not server side. You need to implement loading states in your Invoices-Component, which is a thing remix aims to avoid.

You could write a `getInvoices`-Method and an `Invoices` Component, then use the method in the loaders and the Component in your routes. Just add an `invoices`-key to your LoaderData-Type.

The idea is, that a loader provides all data that the route needs.

**Comment by gijsroge** [comment]
@ccssmnn thanks for clearing this up a bit. But would it be opportune to provide some sort of official stance on how to do this on the Remix docs?

Let's say you have a newsletter form in a separate component, it would be unpractical to handle this on every route, how would one go about doing this?

I think this is a pretty common pattern that lots of people will run into, and right now I can't really find allot of input on how to best approach this.

**Comment by ccssmnn** [comment]
Yeah, I can feel that. The remix data flow works optimal when you look at it on a per-route basis.

Get data ➡️ Loader ➡️ **Route** ↔️ Action ➡️ manipulate data

Loaders and actions are only defined routes. So, your options are:

1. Write data loading/manipulating code and reuse them in the actions/loaders.
2. Write a resource route, point your components to that route. For loaders, this means client-side data fetching. Actions should still work, but you might need to get fancy with redirects.

Overall, it only feels unpractical because remix made the data flow so seamless for routes. Option 1 is still frictionless. Option 2 is what other frameworks default to for most cases, e.g. writing all API routes in a different folder with no tooling for loading states and data refresh.

**Comment by gijsroge** [comment]
@ccssmnn cheers yes that makes sense. Thanks!

**Comment by chaance** [comment]
> Each Loader is a route. Defining loaders inside your components would make no sense.

This is correct. `<Form>`, `useSubmit` or `useFetcher` can all post to a route from any component, but you can't post to something that isn't itself a route.

> Let's say you have a newsletter form in a separate component, it would be unpractical to handle this on every route, how would one go about doing this?

You don't need to handle this in every route. You create one route that handles the newsletter submission in its action, and you can post to that route from anywhere in your app code.

```jsx
// app/routes/submit-newsletter.jsx
export async function action({ request }) {
  // do whatever you need w/ the request and return a response
  return handleNewsletterSubscription(request);
}

// app/components/subscribe-form.jsx
import { Form } from "@remix-run/react";

export function SubscribeForm() {
  // set action to the "/submit-newsletter" route
  // you can use this component anywhere now
  return (
    <Form action="/submit-newsletter" method="post">
      {/* form fields and stuff */}
    </Form>
  );
}
```
