### ISSUE TITLE
[Bug]: refresh again and again

### ISSUE THREAD

**Issue by willin** [remix-run/remix#1518]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13

### Steps to Reproduce

https://github.com/willin/willin.wang/blob/init/app/routes/%24lang/__main.tsx

change it into:

```tsx
import { loader, meta, page } from '~/routes/index';

export { loader, meta };

export default page;
```

### Expected Behavior

work properly with i18n routes

- /xxx - for default locale
- /en/xxx 
- /ru/xxx - for other locales

### Actual Behavior

visite `/zh`, `/en`, `/ru` works ok.

but when visit '/' , this page is refreshing again and again.

**Comment by 0x219** [comment]
.. 你这么写肯定出问题啊

**Comment by willin** [comment]
or copy the codes, the same behavior

**Comment by machour** [comment]
@willin link not accessible, please include a minimalistic reproduce case directly in the comments if possible

**Comment by quantuminformation** [comment]
happening with 2.9.0 for me now
