### ISSUE TITLE
[Bug]: Port conflicts despite setting devServerPort

### ISSUE THREAD

**Issue by pckilgore** [remix-run/remix#1520]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

v17.3.1

### Steps to Reproduce

Create a remix project.  Run it.

Create a second remix project but configure it to run in a different port via devServerPort.

### Expected Behavior

Two projects run fine on separate ports, or some configuration allows this.

### Actual Behavior

Node crash `EADDRINUSE` on port 3000.

Regardless that this particular issue report is remix<>remix, I would prefer to have some way to configure remix dev to use a different port than 3000 should there be a preexisting conflict.

<details>
<summary>
Click for CLI demonstration / crash output.
</summary>

```console

(✓) 11:22:50 [~/[snip]/remixquickstart]
$ rg devServerPort remix.config.js
9:  devServerPort: 8332,

(✓) 11:22:57 [~/[snip]/remixquickstart]
$ yarn dev
yarn run v1.22.17
$ remix dev
(node:25019) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Watching Remix app in development mode...
💿 Built in 153ms
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at Function.listen (/[snip]/remixquickstart/node_modules/express/lib
/application.js:618:24)
    at onInitialBuild (/[snip]/remixquickstart/node_modules/@remix-run/dev/cli/commands.js:184:22)
    at Object.watch (/[snip]/remixquickstart/node_modules/@remix-run/dev/compiler.js:128:69)
    at async watch (/[snip]/remixquickstart/node_modules/@remix-run/dev/cli/commands.js:112:22)
    at async Object.dev (/[snip]/remixquickstart/node_modules/@remix-run/dev/cli/commands.js:182:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v17.3.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by silvenon** [comment]
In the documentation you can see that [`devServerPort`](https://remix.run/docs/en/v1/api/conventions#devserverport) refers to the port of the websocket server, and defaults to 8002, so this is not a bug, just a misnomer in my opinion.

It would be nice to be able to configure the 3000 port, though.

**Comment by mcansh** [comment]
> It would be nice to be able to configure the 3000 port, though.

try `PORT=3333 npm run dev`, windows will require cross-env to do that though

**Comment by silvenon** [comment]
It works, thanks! 👌
