### ISSUE TITLE
[Bug]: useSumit causes rerender multiple times.

### ISSUE THREAD

**Issue by alfredreynold** [remix-run/remix#1524]
### Which Remix packages are impacted?

- [x] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

Please find the [sandbox link here](https://codesandbox.io/s/flamboyant-colden-wzpkk?file=/app/routes/forms.jsx)

Whenever I use the `useSubmit` or `useFetcher` hook and submit a form the entire component gets re-rendered multiple times. 

### Expected Behavior

The number of renders should be one.

### Actual Behavior

Renders the page multiple times.

**Comment by jacob-ebey** [comment]
The number of renders should not actually be 1! When you submit a form there are multiple loading states that occur: "idle" -> "submitting" -> "loading" -> "idle".

For more information please refer to: https://remix.run/api/remix#transitionstate

**Comment by alfredreynold** [comment]
But I'm not using the `useTransistion` hook...

**Comment by jacob-ebey** [comment]
Currently these are "global" states that surface at are consumed at the route level, meaning any time that internal state updates your routes will re-render. It's not a re-mount so this is less impactful to your perf / end user than tracking an input state with `value` and `onChange` callbacks.

**Comment by shadowgroundz** [comment]
> Currently these are "global" transition states that are consumed at the route level, meaning any time that internal state updates your routes will re-render. `useSubmit` ultimately is a transition. It's not a re-mount so this is less impactful to your perf / end user than tracking an input state with `value` and `onChange` callbacks. Really not something to worry about unless you run into performance issues, and at that point you have a bigger issue than Remix re-rendering your routes.

I understand about flow state: idle → submitting → loading → idle. But sometimes I want to insert some notification when failed on API call for example. When I use Form imported from remix, It causes multiple catch state changing from idle to submitting (1), submitting to loading (2), and loading to idle(3). It's normal? I use `CatchBoundary` because I need proceed notification on clientside. Please advice

**Comment by shadowgroundz** [comment]
And in my case, when I use Form imported from remix, sometimes useActionData cannot receive anything instead actionData success return obj

**Comment by MatthieuCoelho** [comment]
> Currently these are "global" transition states that are consumed at the route level, meaning any time that internal state updates your routes will re-render. `useSubmit` ultimately is a transition. It's not a re-mount so this is less impactful to your perf / end user than tracking an input state with `value` and `onChange` callbacks. Really not something to worry about unless you run into performance issues, and at that point you have a bigger issue than Remix re-rendering your routes.

With this pattern, we need to memoize each object inside route to avoid recreating it. I understand that transition state is changing, but why force a render if the route doesn't use the hook useTransition ?
