### ISSUE TITLE
[Bug]: remix-architect hard codes URL scheme in requests to https, even for dev / sandbox server where requests are made using http

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#1536]
### Which Remix packages are impacted?

- `@remix-run/architect`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.2

### Steps to Reproduce

1. Start an architect project using create-remix.
2. Start `arc sandbox`.
3. Start `npm run dev`.
4. Retrieve `request.url` from any loader.

### Expected Behavior

The URL scheme should be `http://`.

### Actual Behavior

The URL will start with `http://`, even though the actual request was made using `http://`, because the URL scheme is hardcoded in: https://github.com/remix-run/remix/blob/776cb79b97bdfba42f802c2f583b1ec5d4dcb785/packages/remix-architect/server.ts#L116

**Comment by mcansh** [comment]
https://github.com/remix-run/remix/pull/1537 was merged to dev, will be out next week

**Comment by lpsinger** [comment]
Indeed, it is fixed now. Thank you!
