### ISSUE TITLE
[Bug]: Cannot use name="attributes" for select items.

### ISSUE THREAD

**Issue by martijnburger** [remix-run/remix#1551]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

17.4.0

### Steps to Reproduce

Include the following code in a page

```
  <Form>
      <select name="attributes">
        <option key="bar" value="bar">Bar</option>
      </select>
    </Form>

```

Execute the page with the `<Scripts />` tag enabled.

### Expected Behavior

Display select box with one argument.

### Actual Behavior

The browser gets stuck in an error logging loop. The start of my error log is here:
[error.txt](https://github.com/remix-run/remix/files/7897771/error.txt)

**Comment by Shumuu** [comment]
I reproduced this bug and published a repo

https://github.com/Shumuu/remix-form-select-name

**Comment by martijnburger** [comment]
> https://github.com/Shumuu/remix-form-select-name

I cannot see the repo. Is it public?

**Comment by Shumuu** [comment]
> 

Whoops. It wasn't. Thanks!

**Comment by hollandThomas** [comment]
Pretty sure this is a React issue, _maybe_ somewhat related to this stale issue
https://github.com/facebook/react/pull/10076

**Comment by martijnburger** [comment]
It is happing within the remix Form component. I don't know how I should reproduce that in react, as react has no Form component and the issue is not happing in a normal form. Also, the actual behavior of the linked issue is very different from what is happening here.

**Comment by martijnburger** [comment]
Anyone that can help me out here?

**Comment by chaance** [comment]
This is likely a bug upstream somewhere, but it has nothing to do with the `<Form>` component. The same issue persists if you use a regular DOM `<form>`.

**Comment by machour** [comment]
The provided reproduction case correctly works for me on Remix 1.11.1
