### ISSUE TITLE
[Bug]: Fly Deployment on jokes app doesn't detect SQLite

### ISSUE THREAD

**Issue by joshmedeski** [remix-run/remix#1557]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

^1.1.1

### What version of Node are you using? Minimum supported version is 14.

v16.13.0

### Steps to Reproduce

Run the following command on the [jokes tutorial deployment section](https://remix.run/docs/en/v1/tutorials/jokes#deployment):

```sh
fly launch
```

### Expected Behavior

I expected fly to automatically detect `sqlite` from my prisma configuration and create a fly volume:

```
Created a 10GB volume vol_18l524yj27947zmp in the dfw region
```

### Actual Behavior

The fly cli created the app and wrote the config file without creating a volume.

```
Created app remix-jokes-jame2 in organization personal
Wrote config file fly.toml
```

**Comment by mkrtchian** [comment]
I did the tutorial yesterday (with remix v1.1.3 and flyctl v0.0.292) and the Fly.io project creation detected the sqlite db for me.

I think this is rather handled by [flyctl](https://github.com/superfly/flyctl) though. Maybe [somewhere here](https://github.com/superfly/flyctl/blob/master/internal/sourcecode/scan.go#L473), but that part of their code has not changed for the previous two months.

**Comment by crhampton1** [comment]
The issue for me was here:

> Remix can be deployed in a large and growing list of JavaScript environments. The "Remix App Server" is a full-featured [Node.js](https://nodejs.org/) server based on [Express](https://expressjs.com/). It's the simplest option and it satisfies most people's needs, so that's what we're going with for this tutorial. Feel free to experiment in the future!

I selected the Remix App Server at the beginning as the tutorial said. I created a new app and selected "Fly" this time and copied over all the code, and the deployment went flawlessly. 

I would recommend we change the docs so that people select "Fly" since the tutorial is deploying to that. I could make that change if nobody else wants to.!
