### ISSUE TITLE
[Bug]:error with upload blog developer example to vercel

### ISSUE THREAD

**Issue by Adbib** [remix-run/remix#1559]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

I upload my remix website like the developer blog example and its not found the posts folder and files

### Expected Behavior

show posts in posts index

### Actual Behavior

not showing blogs posts list and return an error I try to go back and into folders without any result

There was an error

ENOENT: no such file or directory, scandir '/var/task/output/server/pages/api/posts'

**Comment by dg1234uk** [comment]
[Vercel Docs - How can I use files in Serverless Functions on Vercel?](https://vercel.com/support/articles/how-can-i-use-files-in-serverless-functions?) I haven't tried this fully myself as I missed the step where you need to synchronously read the file system `readFileSync()` (the blog tutorial has `readFile()`) before I switched to [fly.io](https://fly.io). Also assume you may have to change `readdir()` to `readdirSync()` as well?

**Comment by DennisKo** [comment]
We had a discussion related to that topic over here: https://github.com/remix-run/remix/discussions/1492. We couldnt find a real solution though.

**Comment by Adbib** [comment]
yeah I think it is a problem that has not been solved yet 
if you see deeper in files you can find your .mdx posts also compiled to js files but you can't work with them

**Comment by Adbib** [comment]
solved my posts.ts file

`import fs from "fs/promises";
import path from "path";

import parseFrontMatter from "front-matter";
import { marked } from "marked";

export async function getPosts() {
  const postOrSeriesBasenames = await fs.readdir(
    `${__dirname}/../../app/posts`,
    { withFileTypes: true }
  );

  const posts = await Promise.all(
    postOrSeriesBasenames
      // .filter((dirent) => dirent.name !== "__tests__")
      .map(async (dirent) => {
        const file = await fs.readFile(
          path.join(`${__dirname}/../../app/posts`, dirent.name)
        );
        // console.log("dirent", file);
        const { attributes } = parseFrontMatter(file.toString());
        return {
          slug: dirent.name.replace(/\.mdx/, ""),
          title: attributes.title,
        };
        //dirent.isFile() && (await getPost(dirent.name));
        // : await getSeries(dirent.name);
      })
  );

  return posts;
}

export async function getPost(slug: string) {
  const postPath = `${__dirname}/../../app/posts/`;
  const filepath = path.join(postPath, slug + ".mdx");
  const file = await fs.readFile(filepath);
  const { attributes, body } = parseFrontMatter(file.toString());

  const html = marked(body);
  return { slug, html, title: attributes.title };
}
`

**Comment by Adbib** [comment]
solved my posts.ts file

`import fs from "fs/promises";
import path from "path";

import parseFrontMatter from "front-matter";
import { marked } from "marked";

export async function getPosts() {
  const postOrSeriesBasenames = await fs.readdir(
    `${__dirname}/../../app/posts`,
    { withFileTypes: true }
  );

  const posts = await Promise.all(
    postOrSeriesBasenames
      // .filter((dirent) => dirent.name !== "__tests__")
      .map(async (dirent) => {
        const file = await fs.readFile(
          path.join(`${__dirname}/../../app/posts`, dirent.name)
        );
        // console.log("dirent", file);
        const { attributes } = parseFrontMatter(file.toString());
        return {
          slug: dirent.name.replace(/\.mdx/, ""),
          title: attributes.title,
        };
        //dirent.isFile() && (await getPost(dirent.name));
        // : await getSeries(dirent.name);
      })
  );

  return posts;
}

export async function getPost(slug: string) {
  const postPath = `${__dirname}/../../app/posts/`;
  const filepath = path.join(postPath, slug + ".mdx");
  const file = await fs.readFile(filepath);
  const { attributes, body } = parseFrontMatter(file.toString());

  const html = marked(body);
  return { slug, html, title: attributes.title };
}
`

**Comment by Adbib** [comment]
make you Posts function like this i solve this problem

```js

export async function getPosts() {
  const postOrSeriesBasenames = await fs.readdir(
    `${__dirname}/../../app/posts`,
    { withFileTypes: true }
  );

  const posts = await Promise.all(
    postOrSeriesBasenames
      .map(async (dirent) => {
        const file = await fs.readFile(
          path.join(`${__dirname}/../../app/posts`, dirent.name)
        );
        const { attributes } = parseFrontMatter(file.toString());
        return {
          slug: dirent.name.replace(/\.mdx/, ""),
          title: attributes.title,
        };
      })
  );

  return posts;
}
```

**Comment by khushal87** [comment]
@Adbib Any fix for it?

**Comment by Adbib** [comment]
> @Adbib Any fix for it?

yeah, the code above solve it for me 
https://github.com/remix-run/remix/issues/1559#issuecomment-1017954002
if you have any problems,  please share with us your code
