### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by stevebarakat** [remix-run/remix#1567]
### What is the new or updated feature that you are suggesting?

Add `.DS_Store `to the `.gitignore` that's included with `npx create-remix@latest`.

### Why should this feature be included?

This would be a nice feature because all Mac users have to add this file to their`.gitignore` file.

**Comment by s-oram** [comment]
Hi Steve, if you're looking for a quick solution, there is a way to ignore files globally. 
https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer
