### ISSUE TITLE
[Bug]: Problem getting hash params in loader

### ISSUE THREAD

**Issue by 9gustin** [remix-run/remix#1574]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

^1.1.1

### What version of Node are you using? Minimum supported version is 14.

v16.13.2

### Steps to Reproduce

Try to read a hash param into a component loader. 

```
export const loader: LoaderFunction = async ({ request }) => {
	const url = new URL(request.url)
	console.log(url.hash);

	return null;
}
```

### Expected Behavior

I want to get the hash of actual url in the loader of my component.

If i try to access it into my component (using `useLocation`) the value it's here, so i can access to the hash in the client but no in the server, i would like to use it in the server.

### Actual Behavior

The value uf loader request.url hash is null, but the url contains a hash.

**Comment by mcansh** [comment]
URL hashes (fragments) are not sent to the server and are used generally for application state https://en.wikipedia.org/wiki/URI_fragment

**Comment by 9gustin** [comment]
Thanks 👍🏼

**Comment by a3diti** [comment]
> URL hashes (fragments) are not sent to the server https://en.wikipedia.org/wiki/URI_fragment

ok but we want it to send it from the client. Related to #1641
