### ISSUE TITLE
[Bug]: run create-remix command, but build the empty project folder

### ISSUE THREAD

**Issue by liwuhou** [remix-run/remix#1575]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.2

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

I just follow the quick start doc, run the `npx create-remix@latest`, and then it builds an empty folder!

### Expected Behavior

I don't know what happens next

### Actual Behavior

just make an empty folder

**Comment by liwuhou** [comment]
wow, amazing, v1.1.3 fix this bugs

**Comment by mcansh** [comment]
sorry about that!
