### ISSUE TITLE
[Feature]: Implement a Node minimum version check upon running 'npx create-remix@latest'

### ISSUE THREAD

**Issue by damiensedgwick** [remix-run/remix#1583]
### What is the new or updated feature that you are suggesting?

Minimum Node version detection and better error messages when this requirement is not met.

### Why should this feature be included?

Not aware of the minimum node version requirement I was trying to follow the official guides and unfortunately not getting very far.

It would have been much simpler on running the initial remix script if it would have either checked for the node / npm version being used and informed me accordingly.

**Comment by tom-sherman** [comment]
I think the simplest place to start would be to add the minimum supported node version to the getting started docs.

**Comment by damiensedgwick** [comment]
This was actually fixed pretty shortly after the issue was created in this PR: #1586
