### ISSUE TITLE
`request.url` passed to a loader doesn't have port

### ISSUE THREAD

**Issue by jorupp** [remix-run/remix#159]
Using built-in remix app server - `remix run`.

```
export let loader: LoaderFunction = async ({ request }) => {
  console.log(request.url);
  return null;
}
```

Remix app console:
```
http://localhost/
```

Server is running on http://localhost:3000/

**Comment by mcansh** [comment]
sorry for the delay! this was fixed in #241, and released in 0.18.0 :)
