### ISSUE TITLE
[Bug]: need to remove node_modules after turning off pc on macOS Monterey 12.1 to npm run dev

### ISSUE THREAD

**Issue by lukasalvarezdev** [remix-run/remix#1597]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

17.4.0

### Steps to Reproduce

I have a project with the following config: https://github.com/lukasalvarezdev/remix-bug-example
It only happens to me if I choose the Vercel deploy after running `npx create-remix@latest`

In local, run `npm run dev` after restarting or turning off your machine.

------

The solution for now is to remove `node_modules` and then run `npm install` again.

on macOS Monterey 12.1, MacBook Air M1.

### Expected Behavior

Run `npm run dev` after restarting my machine without having to remove `node_modules`

### Actual Behavior

In my local machine, everything works fine, but when I restart or turn off the computer, and try again to start the project with `npm run dev`, I get the following error, and the project doesn't start

`Package "esbuild-darwin-arm64" could not be found, and is needed by esbuild.`

**Comment by machour** [comment]
Are you still experiencing this with latest release?
