### ISSUE TITLE
Cannot sign in to Remix dashboard on mobile

### ISSUE THREAD

**Issue by dbanisimov** [remix-run/remix#16]
OS/Browser: Android Chrome 86

When logging in with GitHub a popup (new tab) opens up. This is a firebase auth handler that redirects me to GitHub. After signing in on GitHub it redirects me back to the auth handler that shows `The requested action is invalid.`. No error messages in the console of the popup.

On the desktop it works well - same flow with a popup.

Not sure what's going on here, as I haven't seen this error working with Firebase before.

**Comment by MichaelDeBoey** [comment]
Since we're going OSS, there won't be any dashboard anymore
