### ISSUE TITLE
[Bug]: MultipartFormData 

### ISSUE THREAD

**Issue by kikiondo117** [remix-run/remix#1620]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [X] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

 1) Import the next methods  from `remix` or `@remix-run/node`.   
 * `unstable_parseMultipartFormData`
 *  `unstable_createFileUploadHandler`

2) Use those methods into **ActionFunction**  to work with a **form multipart**
  ```
    const formData = await unstable_parseMultipartFormData(
      request,
      uploadHandler
    );

  ```

3) Watch the error
![image](https://user-images.githubusercontent.com/49052662/150665590-da040ff0-9775-4d44-8c01-9086a9d7ee1a.png)

Browser Console:

![image](https://user-images.githubusercontent.com/49052662/150665962-dd31f7c3-c326-4f04-b11f-c8b51320b908.png)

🆘  Note: The documentation mentions a function called **parseMultipartFormData** but to be used you need to use the alias  **unstable_parseMultipartFormData**.  The documentation needs to be updated -

Documentation Link: (https://remix.run/docs/en/v1/api/remix#parsemultipartformdata-node)

### Expected Behavior

Control the values as the documentation mentions: 

` let avatarUrl = formData.get("avatar");`

...

### Actual Behavior

Errors when you use the methods.

![image](https://user-images.githubusercontent.com/49052662/150665590-da040ff0-9775-4d44-8c01-9086a9d7ee1a.png)

Browser Console:

![image](https://user-images.githubusercontent.com/49052662/150666008-ed482373-5c81-44c8-895f-039f906d0fef.png)

**Comment by ccssmnn** [comment]
Possibly, the same underlying bug as in #669

Can you try importing this to `entry.server.tsx` first, and then import it from there into the routes?

**Comment by stropitek** [comment]
I ran into the same issue. The error is triggered by importing (and using) `unstable_createFileUploadHandler`.

> Can you try importing this to `entry.server.tsx` first, and then import it from there into the routes?

I tried this and the issue remains

**Comment by DavideCarvalho** [comment]
Not only that, but if you try to make your own handler, the stream just gets stuck.

Below is a simple code I did. Sorry, couldn't reproduce on codesandbox, looks like the action is never called on codesandbox.

In this code, the log "after for...of" never gets called.


```tsx
import { Form } from "@remix-run/react";
import type { ActionFunction } from "remix";
import { UploadHandler } from "@remix-run/node/formData";
import { parseMultipartFormData } from "@remix-run/node/parseMultipartFormData";

const uploadHandler: UploadHandler = async ({ name, stream, filename }) => {
  try {
    if (name !== "documents") {
      stream.resume();
      return;
    }

    console.log("before for...of", name, filename);
    const chunks = [];
    for await (const chunk of stream) {
      console.log("inside for...of");
      chunks.push(chunk);
    }
    console.log("after for...of");
    const buffer = Buffer.concat(chunks);

    return "it worked";
  } catch (e) {
    console.log(e);
    return "it did not worked";
  }
};

export const action: ActionFunction = async ({ request }) => {
  console.log("im at the action");
  const body = await parseMultipartFormData(request, uploadHandler);

  console.log("body", body);
};

export default function Index() {
  return (
    <div className="remix__page">
      <Form method="post" encType="multipart/form-data">
        <input name="documents" type="file" />
        <button type="submit">Submit</button>
      </Form>
    </div>
  );
}
```

**Comment by bsanders343** [comment]
I'm having this issue as well. I would attach screenshots but what's already posted is exactly the same thing I'm seeing. Please let me know what other info I can provide to assist with investigating further. Thanks!

**Comment by josuevalrob** [comment]
any update here? is this related? [#1628 https://github.com/remix-run/remix/issues/1620](https://github.com/remix-run/remix/issues/1620#issue-1111777002)

**Comment by jacob-ebey** [comment]
https://github.com/remix-run/remix/pull/1766

**Comment by jacob-ebey** [comment]
https://github.com/remix-run/remix/pull/1764

**Comment by edmbn** [comment]
Hello everyone! I had the same issue only when importing it from `'remix'` inside a resource route. When I was on a route that exported template this error never showed up. To solve the problem on the resource route I import what I need from remix (ActionFunction, redirect) from `'remix'` and `import { unstable_parseMultipartFormData as parseMultipartFormData } from '@remix-run/node'
`. Hopefully it helps meanwhile.
