### ISSUE TITLE
[Bug]: Remix tutorial: link not working with version 1.1.3

### ISSUE THREAD

**Issue by Steppico** [remix-run/remix#1621]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

14.16.1

### Steps to Reproduce

1. `npx create-remix@latest` (this should get you the version 1.1.3)
2. select all default options to `Remix App Server`, `TypeScript`, `run npm install`
3. run `npm run postinstall`
4. following the tutorial @ https://remix.run/docs/en/v1/tutorials/blog, add a link to Posts in `root.tsx`
``` <Link to="/posts">Posts</Link> ```
5. in the **routes** folder, create a **posts** folder and in it, an **index.tsx** file. The content of the file should be a simple function:
```
export default function Posts() {
    return (
        <div>
            <h1>Posts</h1>
        </div>
    );
}
```
6. run `npm run dev`

### Expected Behavior

in localhost I should see a Posts link that, when clicked, should render the **Posts** component (hence, a simple H1 saying "Posts").

### Actual Behavior

Once clicked the link, nothing appears. In the devtool there's no error.
Further info:
- NODE_ENV is on `development`
- I'm on macOS Monterey 12.1 (not M1), using Chrome version 97.0.4692.99

For full disclosure, I tried the same tutorial with a previous version of Remix (1.0.4), and it worked as expected.

**Comment by JohanAltamar** [comment]
Duplicated with https://github.com/remix-run/remix/issues/1601

**Comment by Steppico** [comment]
@JohanAltamar not really, if I restart the server there's no changes.

**Comment by machour** [comment]
@Steppico are you still able to reproduce this issue with latest version ?
If so, would you mind sharing a repository reproducing the issue?

**Comment by xxCosta** [comment]
im also having this issue. all my routes work expect the ones with loader functions. when i click on the link it just reloads the page im already on

**Comment by BianLee** [comment]
Yes facing the same issue. can't route to files with loader functions. Exactly like how @xxCosta described

**Comment by ShlokDesai33** [comment]
I'm facing the same weird bug. Did any of you manage to fix it @xxCosta @BianLee ?

**Comment by machour** [comment]
This issue is 2 years old and probably won't be reopened. 
Would you mind filling a new issue @ShlokDesai33 and provide a repo + your os/environment information?
