### ISSUE TITLE
Good point.

### ISSUE THREAD

**Issue by LANCENET** [remix-run/remix#1648]
Good point.

I forgot to mention that the Remix logs do not show any hits for that endpoint when it shows a stuck pending state.

Meanwhile in the browser the Network Timing shows it stalls on the Connection Start -> Initial Connection.

_Originally posted by @39digits in https://github.com/remix-run/remix/discussions/1642#discussioncomment-2042344_

**Comment by 39digits** [comment]
Why did you create an issue out of my Discussion comment, random Internet stranger?

Are you also experiencing pending fetch requests under WSL2?  If so I see it's related to the keep-alive timeout
