### ISSUE TITLE
support multipart/form-data and file uploads

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#165]
This can be tricky w/ all the different deployment targets, but we intend to support it.

**Comment by chaance** [comment]
Closing since we support this now!

**Comment by SaraVieira** [comment]
I know this is closed, mostly asking here to see if i am doing something wrong or i should create an issue 

Trying to upload files and it works fine untill i had the multiple attribute, if i do that remix still only sends me one file 

Is it not supported yet?

**Comment by SaraVieira** [comment]
This was my bad, I was using `get` instead of `getAll`
