### ISSUE TITLE
[Feature]: Don't break Docs links when new API versions are released

### ISSUE THREAD

**Issue by jinglesthula** [remix-run/remix#1654]
### What is the new or updated feature that you are suggesting?

Maintain the API docs (at least for a while) at their URLs so that links in the tutorials don't 404 once they become stale.

I experienced this when opening the Jokes app tutorial which, when the page loaded, had a link to the docs for `useActionData` with a URL of https://remix.run/docs/en/v1.1.1/api/remix#useactiondata.  A newer version of the API docs was subsequently published, and the 1.1.1 docs were no longer available.  Since I still had the page up as it initially loaded, when I clicked the now-obsolete link, it went to a 404 page.

Could older versions (perhaps up to a certain point in time or number of releases, if not indefinitely) be maintained so that links to them don't break?  I'd love also a sticky banner on older versions linking from to the equivalent page of the current version.

Perhaps even better would be to simply display the API version number in the page itself, but not include it in the URL, so that permalinks can always go to the current version of the docs. Then the only time links would break is if a given API is actually removed and its docs page is nerfed in the process.

### Why should this feature be included?

As links to the API docs are shared on social media or linked to in blog posts (or from w/in the Remix tutorials, as described above), the links will break if what's behind them goes away every time a new API version is released and the docs URLs get a version bump.

**Comment by mcansh** [comment]
> I experienced this when opening the Jokes app tutorial which, when the page loaded, had a link to the docs for `useActionData` with a URL of [remix.run/docs/en/v1.1.1/api/remix#useactiondata](https://remix.run/docs/en/v1.1.1/api/remix#useactiondata).

hm, this should definitely work and is how we designed it to work... I'll take a look! sorry about the inconvenience

**Comment by jinglesthula** [comment]
re: updated link w/ "v1" in the URL

iirc, when I refreshed the tutorial page, the link came back as "v1.1.3" (which worked).  It looks like v1 and v1.1.3 are available - just not v1.1.1, if that helps.

**Comment by IanWitham** [comment]
The fake BSOD on the remix.run landing page has a QR code which 404's: https://remix.run/docs/en/v0.20/api/app#errorboundary

**Comment by ToniMaunde** [comment]
Hi. On the same note, certain links in the authentication section of the Jokes App are broken.
Section link: https://remix.run/docs/en/v1/tutorials/jokes#authentication

**Comment by chaance** [comment]
Not to suggest that this isn't important, but the issue itself isn't very specific and so hard for us to take action on it to close. @ToniMaunde I didn't see a bad link in the jokes tutorial as the one you posted works just fine, but if it's still a problem somewhere please create a new issue or PR that points to the source of the bad link so we can fix it. 🙏
