### ISSUE TITLE
[Bug]: Cookie header is not created correctly for AWS Lambda

### ISSUE THREAD

**Issue by chanan** [remix-run/remix#1663]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [X] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

1. Create a remix that saves more than one cookie
2. Deploy the site to AWS
3. Try to read back the cookies

### Expected Behavior

You should get back all the cookies that were saved

### Actual Behavior

All attempts to read the cookies return null

I did a bit of tracing and it looks like the cookies that are returned created by Architect and sent to the lambda are separated by commas instead of semi colons.

**Comment by LANCENET** [comment]
- Good

**Comment by confix** [comment]
Absolutely correct, just stumbled across that one... I've dug a little deeper.

The issue seems to be right here:
https://github.com/remix-run/remix/blob/db2c31f64affb2095e4286b91306b96435967969/packages/remix-architect/server.ts#L102-L104


Replacing the the loop with
```javascript
headers.append("Cookie", requestCookies.join("; "));
```
should do the trick.

I am going to be prepare a PR anytime soon.

**Comment by mcansh** [comment]
thanks for taking the time to debug this @chanan & @confix 🙏

**Comment by chanan** [comment]
@confix did you end up submitting a PR? If not I can do so.

**Comment by confix** [comment]
@chanan yes. It is merged already to dev. No clue why the issue did not close.

**Comment by confix** [comment]
I see, thanks!

**Comment by machour** [comment]
The fix have been released.
