### ISSUE TITLE
Docs issue: delete is not is not a valid formMethod

### ISSUE THREAD

**Issue by nickdima** [remix-run/remix#167]
[The example](https://github.com/remix-run/remix/blame/master/docs/api/remix.md#L219) for `useFormAction` is not correct as `delete` is not a valid value for the `<button>`'s `formMethod` attribute. Only `get` and `post` are browser supported values.

**Comment by machour** [comment]
This is the updated link : https://github.com/remix-run/remix/blob/main/docs/api/remix.md#useformaction
