### ISSUE TITLE
[Bug]: session cookie parse error

### ISSUE THREAD

**Issue by willin** [remix-run/remix#1677]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

https://github.com/Authing/authing-remix (which is my plugin, with an example project.)

https://github.com/Authing/authing-remix/blob/main/src/lib/authenticate.ts#L18

### Expected Behavior

after login, cookie is already set.

in my browser it works... however, most of my co-workers, cannot get the user object from cookie session.

### Actual Behavior

![middle_img_v2_e9997c5f-8898-468d-8f8d-bde8f40390bg](https://user-images.githubusercontent.com/1890238/151397886-3b901748-2968-4445-b4bf-f9ed4f1e0e88.png)

```
GET /user 302 - - 1.177 ms
GET /login 302 - - 0.699 ms
GET /authing/callback?code=_I3uUjsa4HVZcq9U4CICNsSkQhTELsDb4eT507P6MQQ 302 - - 389.188 ms
{
  appDomain: [Getter],
  clientId: [Getter],
  clientSecret: [Getter],
  logoutRedirectUri: [Getter],
  redirectUri: [Getter]
}
__session=eyJ1c2VyIjp7InJvbGVzIjpbXSwicGhvbmVfbnVtYmVyIjoiMTY2MTk3OTY2ODEiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiO
nRydWUsInVzZXJuYW1lIjoiZG9uZ21pbmdsZWkiLCJiaXJ0aGRhdGUiOm51bGwsImZhbWlseV9uYW1lIjpudWxsLCJnZW5kZXIiOiJNIiwi
Z2l2ZW5fbmFtZSI6bnVsbCwibG9jYWxlIjpudWxsLCJtaWRkbGVfbmFtZSI6bnVsbCwibmFtZSI6ImMOyiIsIm5pY2tuYW1lIjoiYw7KIiw
icGljdHVyZSI6Imh0dHBzOi8vczEtaW1maWxlLmZlaXNodWNkbi5jb20vc3RhdGljLXJlc291cmNlL3YxL3YyXzZhM2EzOTA4LWQ1MjQtNG
Y0MS04MTMyLWRhYWJlOThkZmM2Z34%2FaW1hZ2Vfc2l6ZT1ub29wJmN1dF90eXBlPSZxdWFsaXR5PSZmb3JtYXQ9cG5nJnN0aWNrZXJfZm9
ybWF0PS53ZWJwIiwicHJlZmVycmVkX3VzZXJuYW1lIjpudWxsLCJwcm9maWxlIjpudWxsLCJ1cGRhdGVkX2F0IjoiMjAyMi0wMS0yN1QxMT
o1NDoyNi45NTVaIiwid2Vic2l0ZSI6bnVsbCwiem9uZWluZm8iOm51bGwsInN1YiI6IjYxOTRlNTQ2N2M2MjBmMGMxMzEwNjU5YyJ9LCJva
WRjIjp7ImFjY2Vzc190b2tlbiI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW5SNWNDSTZJa3BYVkNJc0ltdHBaQ0k2SW1sS1ZFWmxaR2s1VjJG
MWNqVXhTVmswYjBVd01HMWhZazEwVkdsVE4wbFliM1J5U2kxYVR6QjZPV2NpZlEuZXlKcWRHa2lPaUpSZERWd2JFZFBkVVE1TTJWQ2VITnh
XRmRITWtVaUxDSnpkV0lpT2lJMk1UazBaVFUwTmpkak5qSXdaakJqTVRNeE1EWTFPV01pTENKcFlYUWlPakUyTkRNeU9UUTVNamNzSW1WNG
NDSTZNVFkwTkRVd05EVXlOeXdpYzJOdmNHVWlPaUp5YjJ4bGN5QndhRzl1WlNCMWMyVnlibUZ0WlNCd2NtOW1hV3hsSUc5d1pXNXBaQ0lzS
W1semN5STZJbWgwZEhCek9pOHZZWE5oTFdobGJIQmxjaTVoZFhSb2FXNW5MbU51TDI5cFpHTWlMQ0poZFdRaU9pSTJNV1l5TkRneU1ERmtZ
amt4TmpCak1XVXpPV1UxWlRnaWZRLlo2eDhWazVEdHI3V0xYMV81bVJpRlk1VHZ1MzZ5azVDeEFpT3M2Y1ZHTWJGampBLURzZ1VlMF9xakt
uSEpRTGZpMzlzbXk4WFJreVFUZ0dZN19zd1JuelF1cG9RSnJLUmhPSVdaVHBHWlFLcDZNOTg3OWpJcUZhejktWHgxdFNYWld2Q1JtMF9jU0
8wWDJKLVZhSlkwcWhHdF9XcURJQWZPUGRBTmpaN3htRFZ6Mjd2SFRLV0ZMNlhqMy0xTHZReHBHdjBuYzI2TjVHYXZBWVZQVE9QQ0pwZHNNN
mF0SGN4Q0lERjRDeGJtaUUtdm1wU2Vpd3o3a2JsdEU3c0RVMExUM1RJR3BSS3NlSkd2T0JyMVdMQjBaODkzUy1aLWZkclppdkx3ak5qRnpX
U0I1TGJZeGFRdDJ1N0RrdVh5YUVwWFJkTElMckxBc2hGTWZaRm5WSkRXZyIsImV4cGlyZXNfaW4iOjEyMDk2MDAsImlkX3Rva2VuIjoiZXl
```

**Comment by willin** [comment]
https://github.com/Authing/authing-remix/commit/9e4b727f8b91f00b4a2442b78a26492b2744f483

i think it's something about json parser.  i'll have a try.

**Comment by willin** [comment]
set session: 
![image](https://user-images.githubusercontent.com/1890238/151490416-da168f38-4999-435b-81bb-2ebb983f930c.png)

```js
Callback User {
  sub: '6194e5467c620f0c1310659c',
  email: 'dongminglei@authing.cn',
  email_verified: true,
  birthdate: null,
  family_name: null,
  gender: 'M',
  given_name: null,
  locale: null,
  middle_name: null,
  name: '董明磊',
  nickname: '董明磊',
  picture: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_6a3a3908-d524-4f41-8132-daabe98dfc6g~?image_siz
e=noop&cut_type=&quality=&format=png&sticker_format=.webp',
  preferred_username: null,
  profile: null,
  updated_at: '2022-01-28T05:03:56.698Z',
  website: null,
  zoneinfo: null,
  phone_number: '16619796681',
  phone_number_verified: true
}
```

undefined when try to get :

![image](https://user-images.githubusercontent.com/1890238/151490375-d76e7cb2-cf0c-43ea-b32b-9d0443d5b30e.png)

```
Session User undefined
```

**Comment by shamsup** [comment]
duplicate #1282 I think. The characters in `name` and `nickname` cannot be encoded by `btoa` (naïve browser base64 encode utility)

**Comment by willin** [comment]
https://github.com/Authing/authing-remix/commit/a1b0f4531aff45d115669bc4e091474128a15d0f

**Comment by willin** [comment]
i've added to binary function
but still the same

![image](https://user-images.githubusercontent.com/1890238/151497355-524f77c8-92f6-4866-b0bb-07a3675b1b32.png)

**Comment by machour** [comment]
Tracked in #1282
