### ISSUE TITLE
[Bug]: TS error in `remix.env.d.ts` file on a fresh scaffolded remix app

### ISSUE THREAD

**Issue by jon301** [remix-run/remix#1694]
### Which Remix packages are impacted?

- `@remix-run/node`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

17.4.0

### Steps to Reproduce

- npx create-remix@latest
- install packages
- open `remix.env.d.ts` : a TS error is highlighted
- also, run `./node_modules/.bin/tsc --noEmit -p tsconfig.json` : same error on the console

<img width="1440" alt="CleanShot 2022-01-28 at 14 10 04@2x" src="https://user-images.githubusercontent.com/122108/151552444-fc7c9992-2a36-45f2-bc80-6a83f84d42e1.png">

### Expected Behavior

No TS errors on a fresh scaffolded remix app

### Actual Behavior

```
~/tmp/my-remix-app 
❯ ./node_modules/.bin/tsc --noEmit -p tsconfig.json
remix.env.d.ts:2:23 - error TS2688: Cannot find type definition file for '@remix-run/node/globals'.

2 /// <reference types="@remix-run/node/globals" />
                        ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by kirbysayshi** [comment]
Although I'm new to Remix, it appears that adding `"@remix-run/node": "^1.2.2",` to package.json will fix this issue. Not sure if there are negative consequences to this though.

**Comment by gulewei** [comment]
Same thing happens to me. Add `"@remix-run/node"` to package.json could work, but I think this should be adding in the template.

**Comment by MichaelDeBoey** [comment]
@jon301 Can you explain the steps you chose when running `npx create-remix@latest`?

Just ran them with the default values and everything seems to work here.

**Comment by kirbysayshi** [comment]
This is likely a result of using a stricter package manager that does not hoist transitive dependencies by default, such as yarn and pnpm. I used pnpm, like the original reporter of this issue, and encountered the error.
