### ISSUE TITLE
Clarify where .npmrc should live

### ISSUE THREAD

**Issue by BurntCaramel** [remix-run/remix#17]
The installation [docs say](https://remix.run/dashboard/docs/tutorial/installation):

> ## Edit .npmrc
>
> In order for yarn/npm on your computer to be able to install Remix, you need to add your license key to the npmrc. You'll find it on the dashboard.

It’s no clear what the “the npmrc” is. Perhaps the docs should change to:

> ## Edit .npmrc
>
> In order for yarn/npm on your computer to be able to install Remix, you need to add your license key to your project’s `.npmrc` file. Create a `.npmrc` in the root of your project if you don’t have one. You'll find your license key in the dashboard.

BTW have you considered having the docs as a repo we can PR to?

**Comment by MichaelDeBoey** [comment]
This won't be necessary anymore
