### ISSUE TITLE
[Bug]: Incorrect sourcemaps in dev

### ISSUE THREAD

**Issue by zardoy** [remix-run/remix#1700]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

1. Scaffold an app from `create-remix`
2. Create a loader in `app/routes/index.ts`:
```ts
export const loader = () => {
    // debugger
    return [] // set breakpoint here via IDE
}
```
3. (in case of vscode): Run *Debug: JavaScript Debug Terminal* (`extension.js-debug.createDebuggerTerminal`), run `npm run dev` in it
4. Open the page

### Expected Behavior

- The code will stop the execution in case if debugger is uncommented
- Breakpoint won't bound and I think this might happen because of incorrect paths to source files in sourcemaps. I also suppose stacktrace on errors should show real files paths

### Actual Behavior

The code should stop the execution on breakpoints from IDE

**Comment by zardoy** [comment]
Probably https://github.com/remix-run/remix/issues/367 already got it covered.

**Comment by machour** [comment]
Yes, closing in favor of #367
