### ISSUE TITLE
[Feature]: Add generics for LoaderFunction and ActionFunction

### ISSUE THREAD

**Issue by g4rcez** [remix-run/remix#1703]
### What is the new or updated feature that you are suggesting?

Loader/Action functions cannot have a type of `State`. We can't know how object are delivery by these functions. 
I suggest to add generics for LoaderFunction and ActionFunction. Using generics in these remix functions, we can know the shape of objects.

- For LoaderFunctions, we can know which object to return
- For ActionFunctions, we can know which objects we have in request. No matter how they are send to server (as JSON or FormData)

If this issue is approved, I can do a PR with the typing 😄 

Use case: 

```typescript
// copy some parts from routeModules.d.ts (@remix-run/server-runtime/routeModules)
type RemixRequest<Body = any> = Omit<Request, "json"> & {
  json: () => Promise<Body>;
};

export interface DataFunctionArgs<Body> {
  request: RemixRequest<Body>;
  context: any;
  params: any;
}

// instead of AppData, I use the Res generics
type LoaderFunction<Req = any, Res = any> = (ctx: DataFunctionArgs<Req>) => Promise<Response> | Response | Promise<Res> | Res;

type User = {
  name: string;
};

type UserResponse = {
  firstName: string;
  lastName: string;
};

export const loader: LoaderFunction<User, UserResponse> = async (ctx) => {
  const userJson = await ctx.request.json();
  const names = userJson.name.split(" ");
  return {
    firstName: names[0],
    lastName: names.pop()!,
  };
};
```

### Why should this feature be included?

With strict types in LoaderFunction, we can know which object to return. With this, we can sync the data with `useLoaderData`. The curious thing is that useLoaderData already has a generics and we don't have generics in LoaderFunction. 

The same argument for ActionFunction, but in this case we need know the type of body in request.

**Comment by akomm** [comment]
Looks like this: https://github.com/remix-run/remix/discussions/1401
I know its discussion not issue, just wanted to link to the proposal to what seems like the thing you want here, just with 1 generic param instead of 2.

**Comment by akomm** [comment]
I don't understand the use of `User` and `UserResponse` in the example. `User` is nowhere related to the loader function. Did you forget something in the example to make it clear?

**Comment by g4rcez** [comment]
@akomm in my example, the type `User` is the body of request received in LoaderFunction. `UserResponse` is used for response in loader function.

**Comment by sergiodxa** [comment]
Here’s a comment from Ryan explaining why actions and loaders can’t be genetics https://github.com/remix-run/remix/pull/1254#issuecomment-1034475233
