### ISSUE TITLE
[Bug]: useBeforeUnload TypeScript issue

### ISSUE THREAD

**Issue by alexluong** [remix-run/remix#1719]
### Which Remix packages are impacted?

- `@remix-run/react`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

Use `useBeforeUnload` like so:

```tsx
useBeforeUnload(
    useCallback((e) => {
      e.preventDefault();
      e.returnValue = "";
    }, [])
  );
```

### Expected Behavior

There is no type error

### Actual Behavior

Error: `Argument of type '(e: any) => void' is not assignable to parameter of type '() => any'.ts(2345)`

<img width="630" alt="CleanShot 2022-01-29 at 14 37 51@2x" src="https://user-images.githubusercontent.com/26750127/151679807-d46539da-71ed-45be-b157-eb6240bbe754.png">

**Comment by alexluong** [comment]
I'd love to open a PR and fix if yall are open to contribution here

**Comment by chaance** [comment]
Merged 🥳 https://github.com/remix-run/remix/pull/1723
