### ISSUE TITLE
[Question]: Filter warning logs ?

### ISSUE THREAD

**Issue by raskyer** [remix-run/remix#1737]
### What is the new or updated feature that you are suggesting?

Be able to filter out some of the consol warnings (in the dev server's terminal).

### Why should this feature be included?

I am currently building a backoffice with Remix for my company.

But, in order to make the process easier I am currently using AntD ui library. For some reasons, the components they expose use : 
`useLayoutEffect` which "throws" a warning in the terminal telling that `useLayoutEffect` will not work correctly with SSR.

In general, we want to have these issues in order to fix them in the code, but here, it's in the library and in the dependencies of the library 'rc-select', so those warning are turning the terminal console into a real nightmare.

Especially because for each impacted components, we have the warning displayed in the consol. It makes it harder to read the server consol for debugging purpose or even when the server will be in "production".

In consequence, I think it would be valuable to be able to filter out these logs.
Maybe there's a possible way to do that already ? (And I'm sorry to ask if that's the case).

Anyway, keep going with your wonderful project ! It's a real pleasure to code with Remix.

Thanks !

**Comment by kiliman** [comment]
The Remix App Server uses a built-in Express server, but they don't expose the config. I would recommend using the Express adapter so you have full control. 

In your server/index.js file
```ts
const oldLogger = console.error
console.error = (...args) => {
  // check to see if it should be filtered
  if (args.any(arg => arg.includes('useLayoutEffect'))) return
  // no, so output it
  oldLogger(args)
}

**Comment by raskyer** [comment]
Thanks !

**Comment by juddydev** [comment]
Hello
what is the advantages using remix than react?
