### ISSUE TITLE
[Feature]: Please expose the request to the LinksFunction

### ISSUE THREAD

**Issue by mwidmann** [remix-run/remix#1755]
### What is the new or updated feature that you are suggesting?

It would be great to expose the Request object to a LinksFunction to programmatically change certain links (e.g the favicon based on data in the cookie)

### Why should this feature be included?

I allow the users of [my app](https://github.com/mwidmann/m2022_remix) to choose which icon they'd like to see in the header. The information is stored in the settings cookie. If I had access to the request Object I could access the cookies and set the favicon programmatically.

**Comment by mwidmann** [comment]
@sergiodxa thanks for the information. That's a neat library you created with a couple of handy functionality.

While it is great to have the option to have LoaderData available in the DynamicLinks component you created, it is not exactly what I need. The Request object should be available for free at every moment in the remix lifecycle, so it would just need to be passed on as a parameter to the links function.

**Comment by sergiodxa** [comment]
Links can’t have access to the Request because they run both client and server side, same with Meta, that’s why if you need data from the request you should return it in the loader.

**Comment by mwidmann** [comment]
Oh my, thanks for the clarification. Somehow I thought the Links part was only running server side, which on second thought doesn't make sense. 

Therefore I'm closing this as a non feature request and will use the remix-utils DynamicLinks functionality for my endeavor.

**Comment by chiptus** [comment]
> Links can’t have access to the Request because they run both client and server side, same with Meta, that’s why if you need data from the request you should return it in the loader.

@sergiodxa 
while I understand the logic, the meta function does get the loader data, so I don't understand why links can't get it too
