### ISSUE TITLE
[Bug]: Using pg package causes error. An optional peer dependency of pg must be marked as external?

### ISSUE THREAD

**Issue by scalisi** [remix-run/remix#1770]
### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

17

### Steps to Reproduce

1. Create a new Remix app (`npx create-remix@latest`).
2. Install and require [pg](https://www.npmjs.com/package/pg) (see [this Remix app](https://github.com/scalisi/remix-pg/commit/e5e868033c14ddb6ae1a0410c679cb3fc1f95ae0)).

### Expected Behavior

There should be no errors (e.g., there are no errors when using pg in a Next.js app).

### Actual Behavior

When [pg](https://www.npmjs.com/package/pg) is [used in a Remix app](https://github.com/scalisi/remix-pg/commit/e5e868033c14ddb6ae1a0410c679cb3fc1f95ae0), the following error occurs:

> Build failed with 1 error:
> node_modules/pg/lib/native/client.js:4:21: error: Could not resolve "pg-native" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)

[pg-native](https://www.npmjs.com/package/pg-native) is an [optional peer dependency of pg](https://github.com/brianc/node-postgres/blob/master/packages/pg/package.json). pg-native is not used in our Remix app.

I couldn't find a way to mark pg-native as [external](https://esbuild.github.io/api/#external) in a Remix app. Is it not possible to mark packages as external in Remix apps?

This error doesn't occur when using pg in a Next.js app (which doesn't use esbuild).

Installing pg-native as a dependency of our Remix app resolves the error. But when pg-native is a dependency, our app's container must use the full [node](https://hub.docker.com/_/node) image, not the `<version>-slim` variant that we use for our Next.js apps.

Thanks for your time!

**Comment by axel-xitaso** [comment]
Is this fixed? I still need to add the following to `package.json`'s `dependencies` property: `"pg-native": "npm:pg"`

**Comment by scalisi** [comment]
@axel-xitaso One solution is to rename the file in which `pg` is imported so that the file ends with `.server.js` or `.server.ts`.  The Data Loading page in the Remix docs [states](https://remix.run/docs/en/v1/guides/data-loading#basics):

> If your server side modules end up in client bundles, move the imports for those modules to a file named {something}.server.ts with the .server.ts suffix to ensure they are excluded.

Also, the Remix Jokes tutorial by Kent Dodds [states](https://remix.run/docs/en/v1/tutorials/jokes#connect-to-the-database):

> The .server part of the filename informs Remix that this code should never end up in the browser. This is optional, because Remix does a good job of ensuring server code doesn't end up in the client. But sometimes some server-only dependencies are difficult to treeshake, so adding the .server to the filename is a hint to the compiler to not worry about this module or its imports when bundling for the browser. The .server acts as a sort of boundary for the compiler.

**Comment by axel-xitaso** [comment]
@scalisi: Thanks, that does probably indeed fix the problem in most real-world scenarios. When evaluating/testing Remix, however, it's quite likely that you would just use `pg` directly in the route file, as that is supposed to work out-of-the-box. That's not a good first impression on one of Remix' core features.

**Comment by clintonwoo** [comment]
> Is this fixed? I still need to add the following to `package.json`'s `dependencies` property: `"pg-native": "npm:pg"`

This workaround in package.json is working for me but even after this issue is closed I'm still getting the error without it on latest Remix 1.3.5
