### ISSUE TITLE
[Bug]: Remix.run website docs CSS doesn't load when navigating from homepage under certain circumstances

### ISSUE THREAD

**Issue by jorupp** [remix-run/remix#1777]
### Steps to Reproduce

1. Go to https://remix.run/ with an old version of https://remix.run/build/routes/docs/$lang.$version-5PGTYVVM.js in cache (in my case, it has a docs CSS url of `/build/_assets/docs-QW57RZDF.css`).
2. Click "Read the docs"

### Expected Behavior

It should look the same as when loading the docs page directly (or when an old version of the $lang.$version JS isn't cached):
![image](https://user-images.githubusercontent.com/3874909/152221834-f6bf1b84-1e08-4358-bf0f-d5edf0cc915d.png)

### Actual Behavior

The docs-specific CSS doesn't load because it's using the wrong URL - `https://remix.run/build/_assets/docs-QW57RZDF.css` vs. `https://remix.run/build/_assets/docs-XP2CWPRA.css`.
![image](https://user-images.githubusercontent.com/3874909/152221805-0fdf823a-1fec-4d49-86ea-b8ccb3639f21.png)

This looks to be because `https://remix.run/build/routes/docs/$lang.$version-5PGTYVVM.js` changed (I get the updated version in an incognito window), but the old version was sent with a `cache-control: public, max-age=31536000, immutable` header, so my browser isn't loading it.

**Comment by emadabdulrahim** [comment]
I'm getting a similar behavior on localhost for a remix project. Not sure yet how to fix it nor what's the culprit.

**Comment by machour** [comment]
Moving this issue to our private website repository, thank you for reporting it.
