### ISSUE TITLE
[Bug]: Subscription form isn't responsive specifically on blog posts 

### ISSUE THREAD

**Issue by kogan007** [remix-run/remix#1779]
### Steps to Reproduce

iPhone 12 pro, go to a blog post page of the remix.run website. Scroll down to the footer and you'll see that the subscription form isn't responsive. Tested in chrome with several emulated devices and it seems to be affecting most of them. 

### Expected Behavior

Responsive subscription form styles on mobile 

### Actual Behavior

Looks to be at about roughly 400 pixels screen width and below where the form loses its padding. 
![image](https://user-images.githubusercontent.com/3247999/152225306-3a561031-8919-4eca-b630-52f0f28d1495.png)

**Comment by machour** [comment]
Seems to be fixed now

![Screen Shot 2022-06-13 at 8 26 15 PM](https://user-images.githubusercontent.com/304450/173429572-a785721d-9a1e-4d88-b0af-1ac04eea4df3.png)
