### ISSUE TITLE
The package `remix` can't resolve `./client` and `./server` since v0.17.1

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#178]
If you install the package `remix` to import things from there instead of all of `@remix-run/*` individual packages it throw an error because it can't resolve `./client` and `./server`. This only happens with the v0.17.1 and v0.17.2, the version v0.17.0 works without issues.

```sh
> node_modules/remix/browser/index.js:2:14: error: Could not resolve "./client"
    2 │ export * from './client';
      ╵               ~~~~~~~~~~

 > node_modules/remix/browser/index.js:3:14: error: Could not resolve "./server"
    3 │ export * from './server';
      ╵               ~~~~~~~~~~

Error: Build failed with 2 errors:
node_modules/remix/browser/index.js:2:14: error: Could not resolve "./client"
node_modules/remix/browser/index.js:3:14: error: Could not resolve "./server"
```

I'm using the latest release of Node v14 and both `npm` (v7) and `yarn` (v1) to install the package and run the commands to build the app or run it in dev-mode.

**Comment by jonaskuske** [comment]
> I noticed that Prisma uses the `node_modules/.prisma` folder instead of mutating the `node_modules/prisma` folder directly. Maybe we should be doing the same and modifying `node_modules/.remix` instead of `node_modules/remix`...

I think that's a good idea! Especially with some install strategies like PnP enforcing that packages are read-only.

**Comment by iamstiil** [comment]
I have the same issue. When upgrading from `1.0.4` to `1.1.0` or from `1.0.4` to `1.1.1`, it breaks for me. Downgrading to `1.0.4` again seems to solve it. I already had the `postinstall` script in place and `ignore-scripts` is not set aswell.

My `tsconfig.json` looks like this:
```json
{
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2019"],
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "target": "ES2019",
    "strict": true,
    "paths": {
      "~/*": ["./app/*"]
    },

    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}
```

Any suggestions?

**Comment by sdalonzo** [comment]
@mjackson I'm hopeful the `.remix` approach might solve the problem I'm having too. I am trying to use Remix with Rush + PNPM workspaces, but every time I run `remix setup`, it breaks builds of unrelated projects in the monorepo and I need to purge my pnpm cache and reinstall from the registry. 

With PNPM, node_modules for a project is hardlinked back to a central store, and I suspect some of the magic of remix setup is affecting that store.

**Comment by kiliman** [comment]
Hmm.. modifying the exports to use the `.remix` package would literally break every Remix app ever written. 

It seems it would be better to simply disable the `remix` package, and write to `remix` as if it was just a folder and not a package. Even that would force every package to remove the `remix` dependency. I'm not sure there is a "simple" solution here.

**Comment by chaance** [comment]
Closing this now as our approach moving forward will be to use direct imports from the remix scoped package instead of the core module.
