### ISSUE TITLE
support scss out of the box

### ISSUE THREAD

**Issue by craigcosmo** [remix-run/remix#1790]
### What is the new or updated feature that you are suggesting?

please support support scss out of the box.

Also please allow to put scss file in the same folder with components/routes.

### Why should this feature be included?

most css just belongs to one component or routes. So put it in it relevant folder will make it easy to nagivate file tree while we looking for it, because we know it justs sit next the the component we working on.

And when you need to delete a routes or component, you just need to delete the whole folder, don't have to go back to styles folder and look for that relating css files to delete.

**Comment by kiliman** [comment]
When you say "support scss out of the box" what do you mean?

I doubt Remix will ever natively compile scss to css for you.

This is what I would do. You should add a file watcher that watches the app folder for all .scss files, and will compile them and put the output in the same folder with the .css extension.

Then in your component file, you can:
```ts
import css from './mycomponent.css' // import the generated .css file
export const links = () => [
  { rel: 'stylesheet', href: css }
]
export default function Component() {}
```

Then in your route file
```ts
import Component, { links as componentLinks } from '~/components/mycomponent'

export const links = () => [
 { add your route links here },
 ...componentLinks()     // include component links in route links
]
```

**Comment by chaance** [comment]
We have plans to expand the scope of our compiler to include some CSS processing, but we don't know exactly what that will look like yet. We are considering SCSS but have no immediate plans to tackle it. You'll need to run it directly as a separate process in the meantime.

**Comment by nadiTime** [comment]
request: also add support for css map files generated by sass
