### ISSUE TITLE
[Bug]: Failed build does not return the right exit code

### ISSUE THREAD

**Issue by gopeter** [remix-run/remix#1792]
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.2

### Steps to Reproduce

- Write code that should break (e.g. import a missing file)
- Run `npm run build`

### Expected Behavior

Since the build script returns "Build failed with [...] errors:", I expect it to throw a proper exit code. I'm building my Remix app with GitHub actions, but the script doesn't stop even if the build breaks.

### Actual Behavior

It doesn't throw the right exit code and processes like GitHub actions continue with the broken/missing build.

**Comment by jenseng** [comment]
Oof yeah, just ran into this on 1.3.4 as well, I'll take a stab at a PR if nobody is working on this yet

**Comment by jenseng** [comment]
Looks like https://github.com/remix-run/remix/pull/1822 should fix it

**Comment by machour** [comment]
Fixed by #1822
