### ISSUE TITLE
Getting parent data into child loaders

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#18]
We were discussing in Remix Chat #help how to get parent data into child loaders (remix.run already needs this).

I was talking about how we might have some way to indicate that a child needs the parent data, and then rearrange our async work to load those loaders serially, instead of in parallel like we normally do:

```js
exports.needsParentData = true;

module.exports = ({ params }, parentData) => {
  // can use parentData now
}
```

We could use an exports flag, or check the length of the function args to decide to do serial or parallel.

Then Tima had a really great idea: pass the parent loader promise to the child

```js
module.exports = ({ params}, parentPromise) => {
  let parentData = await parentPromise();
  // tada!
}
```

It's really great because now you can do your own data fetching that isn't dependent in parallel, and then await the stuff that is.

```js
module.exports = ({ params }, parent) => {
  let [myStuff, parentStuff] = await Promise.all([
    fetchMyStuff(params.whatev),
    parent
  ]);
  let more = await getMore(parent.thing, myStuff.more);
  return more
}
```

We'd want to unwrap the response for them, so that `parentPromise` is awaiting the unwrapped response, not the response itself (otherwise the loader is going to have to become an http consumer, but we've already got code in remix to do that part).

## Some use cases:

In remix run we fetch the user for the `dashboard/` layout to make sure they're authenticated, and then we fetch the user again in `dashboard/index` to then be able to fetch their licenses, stripe customer data, etc.

Instead of verifying their session, hitting the google oauth endpoint, and hitting our DB in both routes, we'd only do that work in the parent route and the child would look like this:

```js
module.exports = async (_, parent) => {
  let user = await parent
  let [licenses, stripeProfile] = await Promise.all([
    getLicenses(user),
   getStripeProfile(user)
  ]);
  return { licenses, stripeProfile };
}
```

Also consider redirecting (after we fix it). Let's say you have a master/detail list and you don't want an index route, but instead want to redirect to the first post in the list. So if the user lands at `/forum/remix` you want to redirect them to the first post `forum/remix/123`.

With our (coming soon) fixed loader redirect handling, this could be done pretty easily in your `forum/$forum/index.js` loader.

```js
module.exports = async ({ params }, parent) => {
  let parentData = await parent;
  return redirect(`/forum/${params.forum}/${parentData[0].id}`);
}
```

## Implementation notes

This seem straightforward for the initial HTML page since we call all the matching route loaders together, but the client transitions may prove difficult.

If routes `A -> B -> C` match, and we transition to `A -> B -> D` in the client, it's unclear to me how we'll get `B`'s data into `D` on the server when we're only calling `D`.

**Comment by richardscarrott** [comment]
@ryanflorence I wonder if something like [data loader](https://github.com/graphql/dataloader) would be beneficial for the initial HTML request so that, if a parent and child route both need to fetch the user, they'd only make a single DB. They'd additionally benefit from batching if the parent needed user A and a child user B etc.

I'm only just getting started with remix, but looks like remix loader `context` might be a suitable place to store a request-level data loader cache?

Aside, the name is unfortunate 😆

**Comment by richardscarrott** [comment]
Ok, just found this in the examples https://github.com/remix-run/remix/tree/main/examples/dataloader which a) does use dataloader to solve this issue and b) does store the data loaders on `context`.

**Comment by acusti** [comment]
i stumbled across this issue looking for how to get parent data into a child route component (not a child’s loader). to save time for anyone else looking for that as well: you can get the data from all parent routes in a child route by using the [`useMatches` hook](https://remix.run/docs/en/v1/api/remix#usematches).
