### ISSUE TITLE
[Feature]: Migrate from xdm to mdx-js v2

### ISSUE THREAD

**Issue by benseitz** [remix-run/remix#1802]
### What is the new or updated feature that you are suggesting?

A few days ago **MDX 2** got released! 

I propose to migrate from `xdm` to `mdx-js` v2.

### Why should this feature be included?

As far as I understand all features from `xdm` are now part of `mdx-js` v2.
Also, it seems like `xdm` could not be supported sometime in the future.
(see: wooorm/xdm/issues/94 and  kentcdodds/mdx-bundler/issues/137)

For me, it would make sense to migrate to the _official_ `mdx-js` for these reasons.

Is this something you would want as well?
Or is someone already working on this? Would you be interested in a _PR_?

**Comment by mayank99** [comment]
xdm now [explicitly](https://github.com/wooorm/xdm/commit/9bd282c3a4831f6f4ace30e81945a18210776e5e) recommends using mdx 2 as well.

**Comment by chaance** [comment]
Happy to take a PR to address this. Going to close the issue as it's not a top priority in the meantime.

**Comment by jacobwgillespie** [comment]
Hey, I have opened a PR for this here: https://github.com/remix-run/remix/pull/4054. As a bonus, removing `xdm` will remove `deasync`, which is a native dependency that requires compilation (which can break).
