### ISSUE TITLE
[Bug]: Auto submit on select tag

### ISSUE THREAD

**Issue by hibangun** [remix-run/remix#1807]
### Which Remix packages are impacted?

- [x] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

```
<fetcher.Form
        method="get"
        action="/search"
        reloadDocument
      >
  <select
        value={initialValue}
        onChange={() => 'this.form.submit()'}
      >
        {options.map(({ key, value }: Option) => {
          return (
            <option key={key} value={key}>
              {value}
            </option>
          )
        })}
      </select>
</fetcher.Form>
```

For the context, this is for table filter function
how to make it autosubmit when there is change on select element?

### Expected Behavior

It will auto submit when user select any option

### Actual Behavior

No response

**Comment by AbePlays** [comment]
I was able to do it using useRef. 

```
const formRef = useRef<HTMLFormElement>(null)

{/* ... */}

<Form ref={formRef}>
      <select
        value={initialValue}
        onChange={() => formRef.current?.submit()}
      >
        {options.map(({ key, value }: Option) => {
          return (
            <option key={key} value={key}>
              {value}
            </option>
          )
        })}
      </select>
</Form>
```

**Comment by kiliman** [comment]
@hibangun Not sure if the code you pasted is the actual code. You `onChange` handler has single quotes around the submit. This will simply return a string, and not execute the code.

Anyway, since you're using `fetcher.Form` you can do this:
```ts
const fetcher = useFetcher()

return (
  <fetcher.Form>
    <select onChange={() => fetcher.submit()}>
    ...
```

**Comment by hibangun** [comment]
@kiliman that much simpler i guess using `fetcher`

but thanks to @AbePlays 
your solution solved my issue

**Comment by isc30** [comment]
> <select onChange={() => fetcher.submit()}>

hey @kiliman that doesnt work in the latest version of remix (even shows a TS error, and runtime doesnt do anything)

**Comment by kiliman** [comment]
I think the API may have changed. Sorry, that was a while ago.

Anyway, this works:
```ts
      <fetcher.Form method="post">
        <select name="item" onChange={(e) => fetcher.submit(e.target.form)}>
          <option>Item 1</option>
          <option>Item 2</option>
          <option>Item 3</option>
          <option>Item 4</option>
        </select>
      </fetcher.Form>
```

⚡️ StackBlitz https://stackblitz.com/edit/remix-run-remix-kermgg?file=app%2Froutes%2F_index.tsx
