### ISSUE TITLE
[Feature]: Is there a tutorial for rule based authorization of the Remix Auth package?

### ISSUE THREAD

**Issue by zwl1619** [remix-run/remix#1812]
### What is the new or updated feature that you are suggesting?

Is there a tutorial for rule based authorization of the [Remix Auth](https://github.com/sergiodxa/remix-auth) package?

### Why should this feature be included?

Is there a tutorial for rule based authorization of the [Remix Auth](https://github.com/sergiodxa/remix-auth) package?

**Comment by sergiodxa** [comment]
This are the issues of Remix, could you ask in the issues/discussions of Remix Auth? Remix Auth is maintained by myself not by the Remix team
