### ISSUE TITLE
[Feature]: In dev mode, only purge the require cache on file changes

### ISSUE THREAD

**Issue by cmd-johnson** [remix-run/remix#1818]
### What is the new or updated feature that you are suggesting?

When running `remix dev`, instead of purging the `require` cache on every single request, only do so when any of the source files were changed.

### Why should this feature be included?

Right now, the `require` cache is cleared [on every single request](https://github.com/remix-run/remix/blob/dev/packages/remix-dev/cli/commands.ts#L169-L174) when running `remix dev`.

This is very un-intuitive for me, and also different from the [documented behavior](https://remix.run/docs/en/v1/other-api/serve).

`createMemorySessionStorage` is intended to be used only during development, but doesn't actually work with `remix dev` because of this (or at least not without additional code to e.g. store it in the `global` object, which isn't documented either).

I can see that this change was made in #431, but without any comments as to _why_.

If purging the cache on every request is the actually intended behavior, it would be great if this could be documented somewhere, including some instructions on how to get `createMemorySessionStorage` working in dev mode.

**Comment by confix** [comment]
Probably @jacob-ebey can tell us why the behavior was changed. Looking at the code probably due to some race condition where the cache would be purged on build start and a new request populates the cache before the build is completed? That indeed would be bad DX.

Anyhow, agreed that it would be worth documenting.

**Comment by jacob-ebey** [comment]
This was changed when the purging code moved packages. I'd be happy to accept a PR that updated it to be "only on rebuild".

**Comment by confix** [comment]
Very well. Thanks for your input. I am going to look into it and prepare a PR in the next couple of days in case no one else picks it up earlier.

**Comment by kiliman** [comment]
I added the following to my Express adapter
```ts
app.all(
  '*',
  MODE === 'production'
    ? createRequestHandler({ build: require('./build') })
    : (req, res, next) => {
        if (req.url === '/build/__purge__') {
          console.log('💿 Purging require cache')
          purgeRequireCache()
          return res.send('ok')
        }
        const build = require('./build')
        return createRequestHandler({ build, getLoadContext, mode: MODE })(
          req,
          res,
          next,
        )
      },
)
```
Then I modified `<LiveReload/>`
```ts
if (e1vent.type === "RELOAD") {
  console.log("💿 Reloading window ...");
  window.location.reload();
  fetch("/build/__purge__").finally(() => {
    window.location.reload();
  });
}
```

**Comment by chaance** [comment]
Closing, but we will review and work through the changes in #2046

**Comment by kiliman** [comment]
The way I do it is I added a special route in my Express adapter `/build/__purge` that does the actual purge.

Then in my `<LiveReload/>` I patched it to call that route before doing the reload.

```diff
             if (event.type === "RELOAD") {
               console.log("💿 Reloading window ...");
-              window.location.reload();
+              fetch("/build/__purge__").finally(() => {
+                window.location.reload();
+              });
             }
```
