### ISSUE TITLE
Add ability to control which loaders get called on transitions?

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#182]
If you've got a slow parent loader and then have a search/filter page below it, every change to the search params causes the parent loaders to re-render.

This is the right thing to do because search params span across loaders, so the safest thing is to call all of them.

But now you're paying a penalty to fetch that expensive thing in the parent every time your filter page changes.

This is silly, but kneejerk reaction:

```tsx
export function loader() {}

type Thing = {
  params: Params,
  location: Location
}

export function shouldReload(prev: Thing, next: Thing) { return boolean }
```

Then the route can decide if it should update or not. This would only run on the client because document requests are stateless, no concept of "reload".

Something like that, I dunno.

**Comment by buffaybu** [comment]
About `shouldReload`

1. Adding a route that needs search to the route tree causes all the innocent parents have to implement `shouldReload`.
2. `shouldReload` looks like remix of function components and class components.

Here's my proposal:

```js
export let searchKeys = ['title'];

export default function Route() {
  // Only reload when "title" search change
  const data = useLoaderData();
}
```

I think of a loader refetch as an effect. Like React's `useEffect`, effects have dependencies that should be declared explicitly, no more no less. A loader's dependencies are what makes up a URL, however for now we can only delcare path pattern (by filenames and folders) so the behaviour looks like

```js
React.useEffect(() => {
  fetch(new URL({
    pathname: compile(pathPattern, location.params),
    search: location.search
  }));
}, [pathPattern, location.params, location.search]);
```

But actually we want this

```js
React.useEffect(() => {
  fetch(new URL({
    pathname: compile(pathPattern, { ...locationRef.current.params, ...paramsThatThisRouteCares }, ),
    search: searchThatThisRouteCares
  }));
}, [pathPattern, paramsThatThisRouteCares, searchThatThisRouteCares]);
```

So Remix can ask developers for help to provide the accurate search dependency.

```js
// Tells Remix what search keys do we care 
export let searchKeys = ['title', /^var-/];
export let params = ['region'];

export default function Route() {
  // Only reload when "$region" param changes and "title" or /^var-/ search change
  const data = useLoaderData();
}
```

It looks boilerplate so we can have some defaults:

- `searchKeys` defaults to `[]` (search changes won't fire any reload)
- `params` defaults to all the params in the pattern (any param's change will fire a reload)

This covers most cases, at the cost of asking developers to explicitly declare what search keys do they need, which, as a developer myself, I think is acceptable.

Further more, we can have something like eslint-plugin-react-hooks to help write dependencies:

```js
export let loader = ({ request, params }) => {
  let url = new URL(request.url);
  return fetch(`${API}/${params.region}?title=${url.searchParams.get("title")}`);
}
export let searchKeys = ['lang']; // error: unnecessary "lang", missing "title"
```

Maybe we can bake it into Remix's builder to automatically add the exports.

---

As for reload after form submission, it's more like invoking a callback, so I think #175 is a good direction.
