### ISSUE TITLE
[Bug]: Button value doesn't get passed to action when used outside form

### ISSUE THREAD

**Issue by dzonatan** [remix-run/remix#1820]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

Kinda related to https://github.com/remix-run/remix/issues/101

Button value isn't passed if it's used outside the `<Form />`. Example:

```tsx
// Works (answer comes to the `action` function) ✅ 
<Form method="post">
  <button name="answer" value="chicken">Chicken</button>
  <button name="answer" value="rabbit">Rabbit</button>
</Form>

// Doesn't ❌ 
// However, works if `Form` is changed to `form` or javascript is disabled
<Form id="myForm" method="post"></Form>
<button form="myForm" name="answer" value="chicken">Chicken</button>
<button form="myForm" name="answer" value="rabbit">Rabbit</button>
```

https://stackblitz.com/edit/github-phkwq6?file=app/routes/demos/actions.tsx

### Expected Behavior

Should work the same way when button is used outside the form.

### Actual Behavior

Button value doesn't get passed to action when used outside the `<Form />`.

**Comment by LukasGerm** [comment]
This is quite funny, because in theory, the buttons should be handled equally https://github.com/remix-run/remix/blob/3b6ea7e9defc5af3b44eb61be2137b2bb06b14e2/packages/remix-react/components.tsx#L1065-L1067 I will try to create tests which reproduce the error and also will try to find and fix the bug.

**Comment by dzonatan** [comment]
Duplicate of #1720
