### ISSUE TITLE
esbuild externals not accessible

### ISSUE THREAD

**Issue by Industrial** [remix-run/remix#1823]
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

17

### Steps to Reproduce

When using MikroORM, i get build errors from esbuild:

```
Build failed with 8 errors:
node_modules/.pnpm/registry.npmjs.org+@mikro-orm+core@4.5.10_4c746656b7f7a21ae58d5630207e3edf/node_modules/@mikro-orm/core/utils/Configuration.js:237:61: error: Could not resolve "@mikro-orm/mongodb" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/.pnpm/registry.npmjs.org+@mikro-orm+core@4.5.10_4c746656b7f7a21ae58d5630207e3edf/node_modules/@mikro-orm/core/utils/Configuration.js:238:61: error: Could not resolve "@mikro-orm/mysql" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/.pnpm/registry.npmjs.org+@mikro-orm+core@4.5.10_4c746656b7f7a21ae58d5630207e3edf/node_modules/@mikro-orm/core/utils/Configuration.js:239:65: error: Could not resolve "@mikro-orm/mariadb" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/.pnpm/registry.npmjs.org+@mikro-orm+core@4.5.10_4c746656b7f7a21ae58d5630207e3edf/node_modules/@mikro-orm/core/utils/Configuration.js:241:63: error: Could not resolve "@mikro-orm/sqlite" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/.pnpm/registry.npmjs.org+@mikro-orm+core@4.5.10_e93952d69f1164f307a4f6806ae7c0b3/node_modules/@mikro-orm/core/utils/Configuration.js:237:61: error: Could not resolve "@mikro-orm/mongodb" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
...
💿 Built in 667ms
```

I found that here: https://github.com/remix-run/remix/blob/c746c6f75fb8a74da92df91113df5af7bf87adea/packages/remix-dev/compiler.ts#L341

There isn't any option for externals used which can be passed to esbuild.

I would like to request to add an option to pass an array of externals so that esbuild may ignore them.

### Expected Behavior

Build :ok: 

### Actual Behavior

Build :bomb: :boom:

**Comment by chaance** [comment]
We have no plans to expose esbuild APIs at this time.

**Comment by russelldavis** [comment]
@Industrial you should be able to hack around this using the technique described at https://github.com/remix-run/remix/issues/2208#issuecomment-1059177247, or https://github.com/aiji42/remix-esbuild-override

**Comment by Acen** [comment]
Curious as to how people doing cloudflare workers have been handling this?
As to handle assets you need to import from a not-real package:
e.g. `import manifestJSON            from '__STATIC_CONTENT_MANIFEST';`

But esbuild will throw an error, and report that you need to mark it as external so esbuild doesn't freak the crap out.

**Comment by Acen** [comment]
Here's how I fixed it:

```
const { withEsbuildOverride } = require('remix-esbuild-override')

withEsbuildOverride((option) => {
  if (
    option.entryPoints &&
    Array.isArray(option.entryPoints) &&
    option.entryPoints.includes('./server.ts')
  ) {
    if (!option.external) {
      option.external = ['__STATIC_CONTENT_MANIFEST']
    }
  }
  return option
})
```
