### ISSUE TITLE
[Bug]: Resource routes don't get server-side pruning, compiled browser code contains server-side code

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#1828]
### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.2

### Steps to Reproduce

If you write a [resource route](https://remix.run/docs/en/v1/guides/resource-routes) (a route with server-side methods like `loader` and `action` but no default export and no React components returned), then [server code pruning](https://remix.run/docs/en/v1/guides/constraints#server-code-pruning) is not performed: the browser build contains the server-side code.

```sh-session
$ npx create-remix@latest

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./my-remix-app
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to chang
e deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes

> postinstall
> remix setup node

Successfully setup Remix for node.

added 439 packages, and audited 440 packages in 25s

143 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into "my-remix-app" and check the README for development and deploy instructions!
$ cd my-remix-app/
$ cat > app/routes/foobar.ts <<EOF
> import { LoaderFunction } from "remix";
> export const loader: LoaderFunction = () => ({foo: 'bar'})
> EOF
$ cat public/build/routes/foobar-ITNQTQOS.js 
import{f as o}from"/build/_shared/chunk-AKSB5QXU.js";o();o();var e=()=>({foo:"bar"});export{e as loader};
```

### Expected Behavior

There should be no browser build output at all for resource routes, or at least the browser build output should not include the server-side `loader` and `action` methods.

### Actual Behavior

See example above.

**Comment by tasos-neten** [comment]
Taken from the docs:
[https://remix.run/docs/en/v1/guides/resource-routes](https://remix.run/docs/en/v1/guides/resource-routes#linking-to-resource-routes
)

It’s imperative that you use reloadDocument on any Links to Resource Routes.

There's a subtle detail to be aware of when linking to resource routes. You need to link to it with `<Link reloadDocument>` or a plain `<a href>`. If you link to it with a normal `<Link to="pdf">` without reloadDocument, **then the resource route will be treated as a UI route**. Remix will try to get the data with fetch and render the component. Don't sweat it too much, you'll get a helpful error message if you make this mistake.

**Comment by lpsinger** [comment]
I don't see what that has to do with the server-side pruning. There is no link here at all.

**Comment by akomm** [comment]
@tasos-neten it would suprise me if the compiler would decide pruning also on whether there are links and how they are defined. As usual its just based on imports and in this case where the "symbols" from the imports are used in code - for example inside loader function.

**Comment by lpsinger** [comment]
At the Advanced Remix Workshop, there were some examples of resource routes that exported no default function but did export React components. Has this bug been fixed?

**Comment by lpsinger** [comment]
Kinda seems to be working now... see tachgsfc/gcn.nasa.gov#79. What did you all do to fix this?

**Comment by ZeldOcarina** [comment]
Any news on this? I am still getting issues here when I try to use native node modules as it's not seen as server only by vite.

**Comment by kiliman** [comment]
@ZeldOcarina you may want to consider creating a new issue/discussion since this one is closed. Also, when you say "native node modules", are you referring to something like `fs`? If so, you should re-export from a `.server` file.

**Comment by ZeldOcarina** [comment]
Oh sorry for that!

Yes I meant that and I understand the concept.

For now I figured if I need a complete server-only route instead of using a resource route I can use a native Express route since I am using that..
