### ISSUE TITLE
[Bug]: createMemorySessionStorage doesn't actually work in development

### ISSUE THREAD

**Issue by pckilgore** [remix-run/remix#1832]
### Which Remix packages are impacted?

- `remix` (Remix core)
- `@remix-run/dev`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

use createMemorySessionStorage

### Expected Behavior

sessions are preserved for the duration of the development session `remix dev` (or at least, preserved between changes to the underlying source). 

### Actual Behavior

in-memory session storage wiped after each request, even if no source code has changed.

### Elaboration

I expected this API to be usable like:

```ts
export default process.env.NODE_ENV === "production"
    ? createCustomDBStore(cookie)
    : createMemorySessionStore(cookie)
```

Perhaps if this is not the intent and it is only intended for the case of "deployed development" environments, more clearly document that fact.

**Comment by pckilgore** [comment]
Worked around in development with createFileSessionStorage

**Comment by akomm** [comment]
When something in the file where you create the storage OR a file it depends on changes, it will be rebuild and reloaded. That might cause the wipe of the instance. I just guess because I only see the export, but it depends on cookie, so there is more, than just the default export, right? Can you check?

**Comment by confix** [comment]
As of [remix-serve](https://remix.run/docs/en/v1/other-api/serve)

> In development, remix-serve will ensure the latest code is run on each request by purging the require cache of your application modules when files change.

this might be what you are seeing.

**Comment by pckilgore** [comment]
Purging occurs per request.  I don't think it's unreasonable to have the in-memory store refresh if a code change occurs. 

But this literally logs me out between the response to the POST and the GET to the authenticated route.

**Comment by akomm** [comment]
You might stick and load the storage from global variable in development. But it might become stale and cause problems when you change things. As long as dependencies don't change in an incompatible way, this includes also configuration from environment set once on instantiation, there should be no problem.

**Comment by akomm** [comment]
You might stick and load the storage from global variable in development. But it might become stale and cause problems when you change things. As long as dependencies don't change in an incompatible way, this includes also configuration from environment set once on instantiation, there should be no problem.

**Comment by itacirgabral** [comment]
funny warning:
> This should only be used in development (...)
https://remix.run/docs/en/v1/utils/sessions#creatememorysessionstorage

But it only works in prod :s

- https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/sessions/memoryStorage.ts#L35

maybe this code above could be workarounded like the prisma hack
https://remix.run/docs/en/v1/tutorials/jokes#connect-to-the-database

```typescript
type SessionFactoryMap = Map<string, {
    data: SessionData;
    expires?: Date | undefined;
}>
declare global {
  var __sfm: SessionFactoryMap | undefined;
}

let map: SessionFactoryMap

if (process.env.NODE_ENV === "production") {
  map = new Map<string, { data: SessionData; expires?: Date }>();
} else {
  if (!global.__sfm) {
    global.__sfm = new Map<string, { data: SessionData; expires?: Date }>();
  }
  map = global.__sfm;
}
```

**Comment by akomm** [comment]
This is basically my proposal above, but without the notice to track the dependencies. Many copy the workaround proposed for prisma, without realizing that in the other case their instantiation has parameters (dependencies) which might change. If they want them to update, they need to track them in global as well. Otherwise you need to restart the server.

**Comment by mjackson** [comment]
This shouldn't be a problem with the `v2_dev` server since we don't purge modules after every request anymore. With `v2_dev`, if you don't change your app code, in-memory stuff just works ootb.

Please give this a shot with the `v2_dev` flag and let us know how it goes 🙏  Thanks!
