### ISSUE TITLE
Import CSS/assets from node_modules

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#185]
I know with the old compiler this didn't work, doubt it works with the new one, but you should be able to:

```tsx
import dialogStylesHref from "@reach-ui/dialog/styles.css"
```

**Comment by jacargentina** [comment]
I'm using `semantic-ui-react` and there are fonts for the Icon component.

I tried doing the import like this for the .ttf, .woff2, etc to be included on the assets folder. No luck.

```js
import iconsFont from 'semantic-ui-css/themes/default/assets/fonts/icons.woff2';

export let links = () => {
  return [
      { rel: 'preload', href: iconsFont },
  ];
};
```

I get this error:

```
/Users/ .... /myProject/node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff2:1
wOF2
    
SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/javiercastro/git/web-site/build/index.js:188:37)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/javiercastro/git/web-site/node_modules/@remix-run/serve/index.js:39:17
```

Only way I've found for the fonts to be where thy should:

`cp ./node_modules/semantic-ui-css/themes ./public/build/_assets/`

**Comment by lineldcosta** [comment]
Issue still exists when i imported library, which has dependency with css-modules to be enabled during build time.

C:\code\test\feedback\node_modules\@sapphire\css\components\button\button.module.css:4
.sapphire-button {
^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\code\test\feedback\node_modules\@sire2-react\core\build\cjs\main.js:12:16)

**Comment by ryanflorence** [comment]
this works now

**Comment by tobad357** [comment]
@ryanflorence is things like inter-ui expected to work where you include a css which in turn includes fonts from node_modules. When trying it out the CSS includes fine but the fonts don't get copied to the assets folder.

```
npm add inter-ui
```

```
import intercss from "inter-ui/inter.css";

export function links() {
  return [
    { rel: "stylesheet", href: intercss },
  ];
}
```

Expected behavior (I think) would be that the fonts in the inter.css file would be pulled in as well.
Currently the css gets pulled in but the fonts become 404 as they are not copied into the correct assets folder

**Comment by jacargentina** [comment]
Please re open! The bug is like @tobad357 (and I) stated

**Comment by tobad357** [comment]
Looking at the code at https://github.com/remix-run/remix/blob/a69a631cb5add72d5fb24211ab2a0be367b6f2fd/packages/remix-dev/compiler/loaders.ts#L6

Shouldn't css use the [css loader](https://esbuild.github.io/content-types/#css) instead of file loader?
That way esbuild should resolve the urls inside instead of just copying

**Comment by tpmarc** [comment]
Same bug here, getting 404 when trying to load my fonts =(

**Comment by letuwang** [comment]
same issue here, please open

**Comment by shadowgroundz** [comment]
Same issue. Please re-open. Does anyone know what version can run normally? Thank you

**Comment by jacob-ebey** [comment]
We do not currently do any processing of CSS files. We just copy them to the build directory and fingerprint them. If the CSS you are trying to consume from a node module needs co-located fonts or some sort of pre-processing this is something you will have to do manually today. This issue should not be re-opened unless you can't import a .css file from a node module, whether it works is not the concern of this issue.

What you believe should be done to pre-process these imported css files is another discussion, and one we are happy to have, just not on this issue.

**Comment by liho00** [comment]
> We do not currently do any processing of CSS files. We just copy them to the build directory and fingerprint them. If the CSS you are trying to consume from a node module needs co-located fonts or some sort of pre-processing this is something you will have to do manually today. This issue should not be re-opened unless you can't import a .css file from a node module, whether it works is not the concern of this issue.
> 
> What you believe should be done to pre-process these imported css files is another discussion, and one we are happy to have, just not on this issue.

could you try use react swiper in remix js? Its hard to use quite a many packages which require import it's css file from node_modules, however remix didnt helping to processing it, would you like to take a look, if we using vite js we dont have to worry about it.

**Comment by iDVB** [comment]
Also having this same issue. Not quite sure what the resolution was here now that it was closed?

**Comment by lasseaeggen** [comment]
You can fetch the CSS from e.g. jsdelivr.net, the URL provided in Swiper's Get Started guide.

```
export const links: LinksFunction = () => [
  {
    rel: "stylesheet",
    href: "https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css",
  },
];
```

**Comment by machour** [comment]
We are currently working on supporting CSS modules. 
Locking this outdated issue. 
https://github.com/remix-run/remix/discussions/4631
