### ISSUE TITLE
[Bug] Weird behavior of Remix in dev mode

### ISSUE THREAD

**Issue by lagz0ne** [remix-run/remix#1884]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

Environment
Windows 11
WSL2

Reproducible code https://github.com/lagz0ne/remix-bug

The code doesn't really work in Dev mode but works well in Production mode
The action part seems to be called but didn't persist the change to the content. As such, the loader takes the content from the original stage, not sure this has anything to do with the model of rebuilding (please have a look at the index route in the repository).

### Expected Behavior

Works in Dev mode

### Actual Behavior

Doesn't function in dev mode

**Comment by cmd-johnson** [comment]
See #1818 and #1832.
In dev mode, Remix currently purges the `require` cache on every single request, meaning your `cache` object will be initialized to `["1"]` every time you navigate to your Index route.

You can work around this by attaching your cache to the `global` object. This is how I did it:
```ts
const cache = (() => {
  const globalCache = global as { cache?: string[] };
  if (!globalCache.cache) {
    globalCache.cache = ["1"];
  }
  return globalCache.cache;
})();
```

This might be a bit verbose, but it's probably the best you can do for now. Just remember that when using the `global` object, the cache will only be re-created when you restart your dev server. So every time you change your cache initialization code, you'll have to manually restart your app.

**Comment by balzdur** [comment]
It may be similar to [this issue](https://github.com/remix-run/remix/issues/1555).

A promising solution is proposed [here](https://github.com/remix-run/remix/pull/4294).

In the meantime, you can use `patch-package` as proposed [here](https://github.com/remix-run/remix/issues/1555#issuecomment-1259976507).

**Comment by pcattori** [comment]
Fixed by https://github.com/remix-run/remix/pull/5133 which will make the new dev server available in the next minor release under the `unstable_dev` future flag.
