### ISSUE TITLE
Docs: `─`  character is too narrow in Source Code Pro font

### ISSUE THREAD

**Issue by Aprillion** [remix-run/remix#1917]
### What version of Remix are you using?

N/A

### Steps to Reproduce

* navigate to https://remix.run/docs/en/v1/api/conventions#ignoring-search-params on Windows

### Expected Behavior

* all characters in a monospace font have the same width

### Actual Behavior

* character `─` is too narrow
  * screenshot from Windows 10 (same on Firefox 98.0b3 and Chrome 98.0):
    <img src="https://user-images.githubusercontent.com/1087670/153714585-00507dc8-ecd8-40ad-a0a1-0e94dc3667a2.png" width="25%">
  * kinda better on Mac (or uncanny-valley-worse?):
    <img src="https://user-images.githubusercontent.com/1087670/153714924-ae4e8bfc-c36c-4c67-a98e-1d327aa51cab.png" width="25%">

**Comment by BasixKOR** [comment]
Isn't this a problem with the font itself?

**Comment by Aprillion** [comment]
it probably is, but I don't care whether it's a wrong character, wrong font, or a bug in build steps, blaming some external cause won't improve the user experience for me ¯\\\_(ツ)_/¯

**Comment by sobrinho** [comment]
Created a PR using ascii chars to avoid this, it is currently broken on my macOS too.

**Comment by machour** [comment]
Tracked in #2150

**Comment by Aprillion** [comment]
Still looks 💩 on Windows:
![image](https://user-images.githubusercontent.com/1087670/162574696-83316afe-dbef-44ff-8044-d862dd3d98bb.png)
