### ISSUE TITLE
Feature request: Add direct PostCSS support

### ISSUE THREAD

**Issue by kvnwolf** [remix-run/remix#192]
It would be nice if Remix could support custom ESbuild plugins. In that way, plugins like [`esbuild-plugin-postcss`](https://github.com/deanc/esbuild-plugin-postcss) could be included to avoid the need to spawn a second process (i.e. for compiling files from `./styles` to `./app/styles`) and overall project structure will look cleaner.

Another suggestion could be to enable PostCSS plugin by default to offer more of an out-of-the-box configuration with optimization in mind for people who want to minify/autoprefix their CSS.

By the way, awesome project. So far I have really liked it, keep it rocking 🤘🏻

**Comment by hipstersmoothie** [comment]
We currently have a very large codebase with a hundreds of components written in css modules and webpack style css importing.

without this support we can’t really move any of our website to remix, I really hope you guys add support! Love the tool so far

**Comment by berrylover03** [comment]
Thanks

**Comment by elkevinwolf** [comment]
@ryanflorence @mjackson is there any plans to implement this? I can give a hand if needed!
