### ISSUE TITLE
Future idea: Remix Experiments

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#193]
One thing I've always wanted to be able to do easily is to run experiments (like A/B tests) on stuff that I build.  The base requirements for something like this would be to:

- identify the user
- load + run some custom code based on who they are
- track some success metric

We already have the ability to identify the user and establish a session. And we have the ability to load/run code dynamically. It might be as simple as just loading some custom js/css in the `links` function or rendering custom markup based on the session data.

Just spitballing some sample code here:

```ts
export function loader({ request }) {
  let user = await getUser(request);
  return {
    runSomeExperiment: shouldRunExperiment(user)
  };
}

// Load a custom stylesheet if the user is enrolled in the experiment...
export function links({ data }) {
  let links = [];
  if (data.runSomeExperiment) {
    links.push({ rel: 'stylesheet', href: 'experimental.css' });
  }
  return links;
}

// Render some custom markup if the user is enrolled in the experiment...
export default function MyPage() {
  let data = useRouteData();
  return (
    <div>
      {data.runSomeExperiment && <Experiment />}
    </div>
  );
}
```

Related: apparently it's difficult to run experiments on Twitter web right now because of the way they do bundling, see https://twitter.com/paularmstrong/status/1399805454663008258. We could show how Remix makes this really easy to do.

**Comment by mcansh** [comment]
added a ticket in linear

**Comment by benjaminsehl** [comment]
Did you guys ever end up putting together any content on this? Would love to check that out!
