### ISSUE TITLE
Out-of-the-box Remix app not working

### ISSUE THREAD

**Issue by SantiSnow** [remix-run/remix#1936]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

I was trying Remix for the first time. Installation steps from docs:

- npx create-remix@latest
- Where would you like to create your app? remix-app
- Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix
- App Server
- TypeScript or JavaScript? TypeScript
- Do you want me to run npm install? Yes
- cd remix-app
- code .
- npm run build
- npm start

This was tested on 3 different pcs, Ubuntu 20, MacOS and Windows 10. Others node/npm related technologies work fine since I work with them daily, so I don't think this is related to my npm/node.

### Expected Behavior

Run successful

### Actual Behavior

remix-serve build

internal/modules/cjs/loader.js:818
throw err;
^

Error: Cannot find module 'fs/promises'
Require stack:

/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/node/errors.js
/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/node/index.js
/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/express/globals.js
/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/express/index.js
/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/serve/index.js
/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/serve/cli.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object. (/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/node/errors.js:16:11)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/node/errors.js',
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/node/index.js',
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/express/globals.js',
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/express/index.js',
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/serve/index.js',
'/home/santiago/Documents/Trabajo/Personal/my-remix-app/node_modules/@remix-run/serve/cli.js'
]
}

**Comment by SantiSnow** [comment]
I am running Node 14 and 15, on different pcs with this result.
Docs recommend: Node.js 14 or greater

but I will try with upgrading to 16 check. If this needs 16 to work, docs should be updated.

**Comment by MichaelDeBoey** [comment]
@SantiSnow I just tried this out with Node 14 and all seems to work.

```sh
node --version
v14.18.3
```

**Comment by kinkwilde** [comment]
node -v = 16.13.1
npm -v = 8.1.2
yarn -v = 3.1.1

All works for me.

**Comment by SantiSnow** [comment]
With Node 14, didn't work for me. After upgrade to node 17, works fine, looks like it's something in that specific version or something from previous versions in my computer.
