### ISSUE TITLE
Disable (or provide option to disable) X-Powered-By: Express

### ISSUE THREAD

**Issue by hugo** [remix-run/remix#194]
Express, by default, adds the header: `X-Powered-By: Express` to its server. For various reasons (some better than others), sometimes we don't want that.

This can be disabled by calling `app.disable('x-powered-by')`. It also will not override a user-supplied value for the header, so I'm just setting it myself in `entry.server.ts` for now. 

Personally, I would prefer if Remix disabled this header by default, but I'm not dogmatic about that by any means. Calling ithis quirk out in the docs for the build-in server might be sufficient?

**Comment by mjackson** [comment]
Fixed in #1712
