### ISSUE TITLE
Unexpected "Error: cannot clone body after it is used" when error thrown in action

### ISSUE THREAD

**Issue by alexblack** [remix-run/remix#199]
I was using an action, and without realizing it an error was being thrown in my code, but I kept seeing `Error: cannot clone body after it is used`, which really confused me, and led me incorrectly to believe I was somehow using remix wrong, and kept trying to fix my code that was retrieving the form POST values.

It looks like if you throw an error after consuming the body, that your error gets eaten and not displayed anywhere that I can see.

```
export const action: ActionFunction = async ({ request }) => {
  const body = new URLSearchParams(await request.text());
  const email = body.get('email') || '';
  throw Error('Oops');
}
```

Expected result: I expected to see my error `Oops` in the console.

**Comment by kiran-bhalerao** [comment]
request.clone().formData()
