### ISSUE TITLE
default cookies to `SameSite: Lax`

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#200]
Chrome recently started defaulting to `SameSite: Lax`, and if you don't do it in your remix cookies/sessions, you get this error in the devtools:

![image](https://user-images.githubusercontent.com/100200/122257894-afcb9f00-ce8d-11eb-9283-de36fa1b7ed0.png)

We should probably add this as the default in Remix to get rid of the error and makes sites more secure by default for browsers that aren't doing this yet.

**Comment by MichaelDeBoey** [comment]
Closed by #2388
