### ISSUE TITLE
 Warning: Prop `dangerouslySetInnerHTML` did not match

### ISSUE THREAD

**Issue by techandmedia** [remix-run/remix#2002]
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

Follow the official tutorial
[https://remix.run/docs/en/v1/tutorials/blog](url)

Create a new app and chose Remix App Server
```
npx create-remix@latest
npm run dev
```

### Expected Behavior

Should the error occurred?

### Actual Behavior

Observe the error in browser console

![Screenshot 2022-02-17 172629](https://user-images.githubusercontent.com/15700861/154446019-463d4bd9-e3d7-4a69-9fda-c3ce11d3a3e4.png)

**Comment by kiliman** [comment]
Here's the commit where this change was made: 12d770cc9466bbe6c8f8dffae65219ce8f97815a

Scroll down near the bottom. It's supposed to set that env var from config value.
https://github.com/remix-run/remix/blob/12d770cc9466bbe6c8f8dffae65219ce8f97815a/packages/remix-dev/compiler.ts#L367-L369

The odd thing is that the way the commit was worded, I thought it was automatically finding an unused port, so if you run multiple Remix apps, you don't have to specify ports.

**Comment by kiliman** [comment]
Anyway, not sure why it didn't pull the port from config.

**Comment by georgehenderson** [comment]
It is likely due the env var not being defined in the server build esbuild config

[Missing here?](https://github.com/remix-run/remix/blob/12d770cc9466bbe6c8f8dffae65219ce8f97815a/packages/remix-dev/compiler.ts#L445)

**Comment by kiliman** [comment]
Probably. Because the server is rendering that component SSR, so would need the port in addition to the client bundle for hydration.

You can test it by simply updating the the file `node_modules/@remix-run/dev/compiler.js` and add that line. Then see if it works properly. If so, you should submit a PR.

**Comment by georgehenderson** [comment]
Looks like my idea was already fixed 22 days ago, so probably not that. 

https://github.com/remix-run/remix/pull/1745

**Comment by georgehenderson** [comment]
I console logged `LiveReload.toString()` to see what was getting imported on the server. I was curious to know if the server dependencies were getting transformed or bundled.

<img width="522" alt="Screen Shot 2022-02-22 at 7 59 28 PM" src="https://user-images.githubusercontent.com/1379792/155250496-188a9a31-75e7-4640-aa21-130f56cd0682.png">

It seems like they are just imported from node modules and not transformed. I don't expect this would ever work for the dev server build unless I fundamentally am misunderstanding something.
```
"process.env.REMIX_DEV_SERVER_WS_PORT": JSON.stringify( 
   config.devServerPort 
 ) 
 ```
 Seems like we need a way of creating these env vars from the remix config and sourcing them when using the cli.

**Comment by IgnisDa** [comment]
Any updates on how to fix this? Facing the same problem myself.

**Comment by machour** [comment]
A lot of issues have been fixed with the LiveReload component & ports since this issue was posted.
If this is still a problem with latest Remix version, please open a new issue 🙏🏼
