### ISSUE TITLE
Catch-all Route Doesn't Support Special Characters

### ISSUE THREAD

**Issue by knpwrs** [remix-run/remix#2012]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

Create a catch-all route handler at `app/routes/$.ts`.

### Expected Behavior

All routes should be handled by `app/routes/$.ts`.

### Actual Behavior

Routes like `<host>/foo` and `<host>/foo/bar` work, but routes like `<host>/~foo` and `<host>/@foo/bar` return 404.

**Comment by knpwrs** [comment]
Note that encoding `@` as `%40` leads to the same result.

**Comment by knpwrs** [comment]
I attempted to create a file called `@$.ts` as a workaround, but it did not work:

```ts
export { loader } from './$';
```

**Comment by knpwrs** [comment]
This appears to be a bug with React Router: https://github.com/remix-run/react-router/issues/8525

**Comment by chaance** [comment]
This is currently as designed. Note https://github.com/remix-run/react-router/issues/8525#issuecomment-1054819661, but we may yet be convinced change this behavior. In any event, this is related to React Router so I'm going to close this and refer folks to comment in the linked issue there instead.
