### ISSUE TITLE
Warning about unsupported fetch options

### ISSUE THREAD

**Issue by Aprillion** [remix-run/remix#2015]
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

* create new remix project for cloudflare workers
* in a loader, use an unsupported fetch option, e.g. `await fetch(..., {cache: 'force-cache'})` in 
   https://github.com/Aprillion/stampy-ui/blob/9487ca0319a79f313a38de3744396b3534cacac0/app/routes/index.tsx

### Expected Behavior

Some warning about unsupported fetch options, e.g.:
* a type check if possible
* fail in the same way in local dev server as it fails after deployment
* maybe a chapter in documentation about all the differences of non-native fetch from server?

Additionally, if some server environments (will) support native-like HTTP Cache, it would be nice to be able to debug server side fetch requests (similar to browser Network tab) => any documented advice how to debug server fetch would be appreciated too.

### Actual Behavior

Everything worked fine locally, then I got an error after deployment to workers:
<img width="647" alt="Screenshot 2022-02-17 at 19 11 31" src="https://user-images.githubusercontent.com/1087670/154546404-a52e3039-acc7-495d-9147-a67f86d35981.png">

**Comment by Aprillion** [comment]
FTR: Original discussion started in https://discord.com/channels/770287896669978684/943924040962306098

**Comment by Aprillion** [comment]
Actually, I found the CF workers' version of `fetch` has more differences from the spec => https://github.com/cloudflare/cloudflare-docs/issues/3578 to track documentation of those differences that are on purpose.

Once that is documented, we could add a note to https://github.com/remix-run/remix/blob/dev/packages/create-remix/templates/cloudflare-workers/README.md to improve the developers' expectation when working with this particular deployment target.. (though, not sure how `fetch` behaves for other targets 🤔)

And if those differences get fixed in CF, we could even close this issue 😅

**Comment by machour** [comment]
@Aprillion Hey ! More than a year passed since you opened that issue, do you know if it's still applicable today? 🙏🏼

**Comment by Aprillion** [comment]
no idea, once I stopped using the then-unsupported fetch options, I never had a use case to use those again

**Comment by machour** [comment]
Fair enough :)
I'm closing this for now, someone will eventually open a new issue if this is still a problem, thanks!
