### ISSUE TITLE
Experimental Deno support fails with the latest version (1.18.0)

### ISSUE THREAD

**Issue by synaptiko** [remix-run/remix#2053]
### What version of Remix are you using?

v1.2.1

### Steps to Reproduce

I wanted to give the new deno server a try but it failed right away with the following errors:
```
Watcher Process started.
Check file:///xyz/build/index.js
Watching Remix app in development mode...
💿 Built in 708ms
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std/testing/asserts.ts:384:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std/testing/asserts.ts:385:29

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std/path/constants.ts:51:26
```

By checking Deno's changelog it seems that `EOF` support was removed in [v0.42.0 / 2020.04.29 ](https://deno.land/x/deno@v1.7.5/Releases.md#v0420--20200429) which is quite a long time ago.

I used `yarn create remix@latest` and choose `Deno`, no special other steps.

### Expected Behavior

Even though it's an experimental support I would expect it to work :-)

### Actual Behavior

There are the errors as described above.

**Comment by lucacasonato** [comment]
@synaptiko Run `deno info` and delete the folder specified as `DENO_DIR`. You are using an outdated version on deno.land/std (and remix is using an unversioned import - this is the real problem).

**Comment by synaptiko** [comment]
Thank you @lucacasonato, makes sense and works.

**Comment by melkir** [comment]
Using the latest version available on brew
```
❯ deno --version
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```
I got the following error even after removing the `DENO_DIR`
```
Watcher Process started.
error: Relative import path "@remix-run/deno" not prefixed with / or ./ or ../
    at file:///Users/melkir/Projects/my-remix-app-versel/build/index.js:31:42
Watcher Process failed. Restarting on file change.
```

**Comment by CanRau** [comment]
Same here as @melkir
though I just upgraded via `deno upgrade`
```
deno 1.19.2 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```
and I'm on Remix 1.2.3

**Comment by aarbi** [comment]
Same issue here, the generated `index.js` under build folder doesn't follow the way deno does imports.

**Comment by synaptiko** [comment]
I can confirm, having the same issue with the latest remix & deno as the others above.

**Comment by sohcfst** [comment]
come across this issue as well

**Comment by pcattori** [comment]
Official support for Deno came out on May 18th, 2022 with version 1.5.0.

If Deno support is not working, feel free to reopen or create a new issue.
