### ISSUE TITLE
Action or Loader code on client side

### ISSUE THREAD

**Issue by roydigerhund** [remix-run/remix#2058]
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

1. Create a new remix project (I'm using Remix App Server and TypeScript)
2. Add the file `~/app/cookies.ts` with the following content

```ts
import { createCookie } from 'remix';

export const testCookie = createCookie('user', {
  maxAge: 60 * 60 * 24 * 365, // 1 year
  secrets: [process.env.APP_SECRET!],
});
```
3. Add the file `~/app/routes/api.tsx` with the following content
```ts
import { ActionFunction, json } from "remix";
import { testCookie } from "~/cookies";

export const action: ActionFunction = async ({ request }) => {
  const cookie = await testCookie.serialize('username');
  return json({ cookie });
};
```
4. Add this loader function to `~/root.tsx`
```ts
export const loader: LoaderFunction = async ({ request }) => {
  const auth = await testCookie.serialize("cookieHeader");
  return { auth };
};
```
5. Run `yarn dev` and open `localhost:3000` in your browser

This will result in the error `Can't find variable: process` because somehow the code from `~/app/cookies.ts` got into the client side code. 

The error will not occur if: 
- loader function is removed from `~/app/root.tsx`
- `~/app/routes/api.tsx` is removed
- a default export is added to `~/app/routes/api.tsx`

I couldn't find any explanation in the docs why this happens. I think code from loader or action functions should never be shipped to the client. Especially if it contains code like the cookie secrets.

I created a repository with the applied changes for testing: https://github.com/roydigerhund/loader-action-code-client-side

### Expected Behavior

Code from action or loader functions is only computed on server side and will not be shipped to the client.

### Actual Behavior

Code from action or loader functions is shipped and executed on client side.

**Comment by xstevenyung** [comment]
I think this is already addressed in the documentation: https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles

You can rename your file: `cookies.server.ts` to prevent the issue

**Comment by roydigerhund** [comment]
I tested it and the solution with renaming the file to `cookies.server.ts` works. 

However, I'm not sure if the documentation already addresses this. The documentation link you sent is about importing third-party packages without `"sideEffects": false` in the `package.json` file. In this case, it is a file inside the project repository.

**Comment by kiliman** [comment]
The problem is that your function has a side effect:
```ts
export const testCookie = createCookie('user', {
  maxAge: 60 * 60 * 24 * 365, // 1 year
  secrets: [process.env.APP_SECRET!],
});
```
You're calling a function `createCookie()` in module scope. So just the act of importing from this module means that code will execute, which results in it being in the bundle (and also includes the APP_SECRET).

**Comment by kiliman** [comment]
It's the same reason you can't wrap your loaders/actions in a higher-order function. Since those functions would execute in module scope, it would not tree-shake them out of the client bundle.
```ts
// bad
export const loader = withAuth(({request}) => { // loader })
```

**Comment by roydigerhund** [comment]
Thanks for the explanation, this makes sense 👍
