### ISSUE TITLE
Setting headers when returning json in action has no effect 

### ISSUE THREAD

**Issue by windkomo** [remix-run/remix#206]
When using the json function in an action, it seems setting headers in the second parameter has no effect:

```ts
 return json(
            {
              errors: {
                email: 'Email error message'
              },
            },
            {
              headers: {
                "Set-Cookie": await commitSession(session),
              },
            }
);
```
Seeing this with a session.flash not being set in a parent loader.
Headers are set properly when json is replaced by the redirect function.

```
"remix": "0.0.0-experimental-1a6f09f"
```

**Comment by chaance** [comment]
Unable to reproduce this with any recent versions. Feel free to reply with a minimal reproduction if you're still having issues.
