### ISSUE TITLE
Public assets not fully covered on Express template

### ISSUE THREAD

**Issue by manzano78** [remix-run/remix#2069]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

1. Create a new Remix project (`npx create-remix@latest`)
2. Choose the Express template, with or without typescript
3. Open the project and start it (`npm run dev`). The problem also exists in production mode
4. Open a new browser tab to see the result

### Expected Behavior

We should see the Remix favicon on the browser tab

### Actual Behavior

The favicon is not displayed.
I think the problem is on this line:
https://github.com/remix-run/remix/blob/c03d0fd0efa4aef57e79c6811eadee5383200e24/packages/create-remix/templates/express/server.js#L23

Indeed, we don't declare the rest of the `/public` folder, where the favicon is and where other assets could potentially be. Consequently, we get HTTP 404 errors when the browser tries to get these assets.

**Comment by arunavabasu-03** [comment]
hey, I would like to work on this issue.

**Comment by machour** [comment]
Fixed in https://github.com/remix-run/remix/commit/b1ce044f812a9bd47a1cffbc1e598bfb2a2e5868
