### ISSUE TITLE
Architect starter favicon.png gives 404

### ISSUE THREAD

**Issue by rogerchi** [remix-run/remix#207]
Using the default Architect starter, favicon.png does not load, giving a 404 error.

**Comment by cfranklin11** [comment]
I came across this issue while trying to figure out how to display the favicon and figured out that Architect doesn't include existing `public` files like `favicon.ico` in its built assets, all of which come from the `app` directory. I'm not sure if it's the best way to do it, but I was able to include the favicon in the built assets and get it to show up in the browser tab by doing the following:
1. Move `favicon.ico` to the `app` directory (I put it in `app/images/`, but it's up to you), and change its name to `favicon.png` (this might only be necessary if you're using Typescript; I haven't tried it on vanilla JS).
2. Add the following code snippet to `app/root.tsx` (be sure to import `LinksFunction` from `remix`):
```
import favicon from "./images/favicon.png";

export const links: LinksFunction = () => {
  return [
    {
      rel: "icon",
      href: favicon,
      type: "image/png",
    },
  ];
};
```

When you refresh the page, you should see the favicon appear.

I'm not sure what implication this has for the Remix/Architect starter, as in whether this should be added to the boilerplate or the `@remix-run/architect` package changed to include `public` files in the build.

**Comment by acairns** [comment]
I hit this also. I managed to get it to work by prepending `/_static` - but not entirely sure if this was going to work when arc deployed.

Instead, I took a similar approach to @cfranklin11.

Documented here: https://remix.run/docs/en/v1/api/conventions#asset-url-imports

**Comment by mcansh** [comment]
hey all, architect uploads the `/public` folder to an s3 bucket during the deployment and rewrites requests to `/_static` to the s3 bucket. in development arc sandbox will load them from public directory prefixed with `/_static`

https://arc.codes/docs/en/guides/frontend/static-assets
