### ISSUE TITLE
Express template: Live reload happens before server is restarted

### ISSUE THREAD

**Issue by na2hiro** [remix-run/remix#2093]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

1. Set up templates with `npx create-remix@latest`. Choose Express template, TypeScript, and then choose to let it run `npm install`
2. In the newly created repo, run `npm run dev`, and open the page
3. Modify `app/routes/index.tsx`, then let Remix do live-reload

### Expected Behavior

Remix live-reloads the page and the page is loaded correctly. Live reload is triggered once server has restarted after compilation.

### Actual Behavior

Remix live-reloads the page, but it sometimes results in "The site can't be reached". This happens because the live reload is triggered prematurely while the server is still restarting.

#### Root cause: Live reload is triggered before server has restarted

Remix triggers live reload when build is done. At this moment, `nodemon` notices it should restart the server, and it's about to or has shut down the server. Browser could hit the server while the server is restarting. This happens more often and a lot more distractive to the development iteration as the code size grows.

[![remix-premature-live-reload-colored](https://user-images.githubusercontent.com/736244/155282877-a0bd93d9-1da6-40f3-8b60-cebb179df467.png)](https://sequencediagram.org/index.html#initialData=C4S2BsFMAICVILYgB7QA4CdEENgFctoAZEANxnnAHtsATAKHoBFJSBaAPgCMMqB3AM6QMALgDyaSADt02AOaR6PfkIydaraKvKisARzyQBwZq04AxEFC0BPY4hEB1DGBgAzK0egAKAPTY0NABKengkZAtPW3sEEQA5KlAAY3copIALbCkFAVDEFEjrATtgB2dXaA8oAR9fLjwrWgAaaF80PC5wECS6hvBaELCCgGIsWhEAFm5eQWERZTok7GNoLGo6ADpoAAVYMQAhIgBRAFloEBr04UgtgElgLXSqPH7oTMDpaGw3UoxoYCuWmEOlWRmA2AwJikVA0CCoUkKMGKMXiiW6qWsGSyOXo0Nh8PUmm0cwAyuk8A9aPwZMSMEoZqpkKNIOMAMxsZSzXSQdbNIEYEF4KRYbBYzqKPGIAkcDSkfk6ETwYwQh60oA)

Remix should instead trigger live reload once server has restarted.

#### Multiplying factor: `nodemon` watches entire `public/build`

One thing I noticed is that server takes too long time to restart. Too many `[nodemon] restarting due to changes...` indicates there are some issues (Note: I edited only one file)

```sh
nodemon] restarting due to changes...
[nodemon] starting `node ./build/index.js`
💿 File changed: server.js
💿 Rebuilding...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
💿 Rebuilt in 1s
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
(...abbreviated...)
```

I debugged with `--verbose` option to `nodemon` and it revealed that `nodemon` watches unnecessary files under `public/build`

<img width="641" alt="nodemon-watches-public-build-unnecessarily" src="https://user-images.githubusercontent.com/736244/155276610-3e30aa19-6c26-43aa-a0cb-dbe22722ee98.png">

I believe Remix bundles server to a single file `build/index.js`, and `nodemon` basically needs to watch only that file.

The fix would for this would be like following
```diff
-    "dev:node": "cross-env NODE_ENV=development nodemon ./build/index.js",
+    "dev:node": "cross-env NODE_ENV=development nodemon ./build/index.js --watch ./build/index.js",
```

This fix itself is nice in order to reduce time to rebuild the server, but it won't fundamentally fix the problem unless cause 1 is addressed.

**Comment by na2hiro** [comment]
I made a PR https://github.com/remix-run/remix/pull/2094 for the "multiplying factor" issue. However, we need another solution for the root cause.

**Comment by kiliman** [comment]
Prior to 1.2, Remix didn't bundle the server build. You would simply run `node server/index.js` and it would purge the require cache on each request. This way it would pickup any changes you make in your app folder. But now that they support server bundling, you would need to restart the express app on every change. I'm not even sure why you would want to bundle (at least on dev).

Anyway, there is a *remix.config* option for `devServerBroadcastDelay` if you need it to wait a second before reload.

https://remix.run/docs/en/v1/api/conventions#devserverbroadcastdelay

**Comment by na2hiro** [comment]
Thanks @kiliman, once I bumped `devServerBroadcastDelay` up, it now refreshes smoothly. I won't need to think about this for now.

Purging cache on requests sounds pretty nice. It's changed like this in https://github.com/remix-run/remix/pull/1504, probably needed for aligning the way things are built? I'm going to try if I can still do that with `1.2`.

**Comment by na2hiro** [comment]
@machour I confirmed it's fixed, because https://github.com/remix-run/remix/pull/2569 changed the Express template back to the previous no-bundle server setting which @kiliman described. I migrated the new setting into My project, which I had to set 3s delay, now refreshes pretty quickly like 1s.
