### ISSUE TITLE
Splat root route is not working

### ISSUE THREAD

**Issue by vndre** [remix-run/remix#2098]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

repo to reproduce it: https://github.com/vndre/rmx-splat
(this is a basic repo scaffolded with `create-remix`)

- run local dev
- go to localhost:3000

### Expected Behavior

`/routes/$path.jsx` should catch all routes starting from `/*` 

### Actual Behavior

remix doesn't load splat route for `/` (root)

**Comment by mkrtchian** [comment]
Is your issue the same as #2012 ?

**Comment by vndre** [comment]
> Is your issue the same as #2012 ?

No, that issue is for specific route names (like /~foo), but my splat route is not catching any route at all. Please note that the linked issue is using version 1.1.3 so maybe this bug is from a more recent version.

I created a stackblitz to demostrate my issue: https://stackblitz.com/edit/node-u7vc8f?file=app%2Froutes%2F%24.tsx

**Comment by vndre** [comment]
> Is your issue the same as #2012 ?

Sorry I think I made a vague description of the issue before going to bed. catchall route IS working on all routes but root, `/a` works but not `/`. 

I remember I saw someone doing something similiar in Nextjs, and they fixed it by duplicating the catchall logic in a separate `index.jsx`, I tried it, having a `$.jsx` besides `index.jsx` and the index just importing the exports of the other file but is there a more elegant fix? Can duplicating a route (two routes pointing to the same path) lead to more problems in the future?

**Comment by mkrtchian** [comment]
You have some explanation in the docs, with files examples, and the corresponding routes that should be matched:
- you are using here the [Dynamic Route Parameters](https://remix.run/docs/en/v1/api/conventions#dynamic-route-parameters) with `/routes/$path.jsx`.
- but you also have the [Splat Routes](https://remix.run/docs/en/v1/api/conventions#splat-routes) with `/routes/$.jsx`.

In both cases the examples show separate files for the index. And when testing with an app we can see that the behavior is that in both cases the catch-all route files don't match the index, even if `index.jsx` doesn't exist.

I don't know if this is an intended behavior or not.

For the splat routes we have the following sentence:
> These routes will map to any URL not matched by other route files in the same directory.

If the current behavior is the correct one, we may precise in the docs that it maps any URL not matched by any other files in the same directory **except for the index**.

**Comment by vndre** [comment]
I see now, thanks for the clarification!
