### ISSUE TITLE
"Extra attributes from the server" and other hydration warnings

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#21]
Browser extensions mess w/ `<html>` and `<body>` sometimes and React hates it, and kicks out errors in the console.

Definitely to document what this is about and how to suppress these (and avoid issues with plugins messing w/ your document):

```jsx
<html suppressHydrationWarnings>
```

And maybe add that to the starter boilerplate.

**Comment by MichaelDeBoey** [comment]
This can be closed as d0b61e4 is in `main` I guess?
