### ISSUE TITLE
Architect deployment seems broken, cannot resolve `./client`

### ISSUE THREAD

**Issue by abelozerov** [remix-run/remix#210]
Hi there!

I am investigating Remix and faced issue with Architect deployment
My local environment: macOS 11.4, node v14.13.1 (npm v6.14.8), AWS CLI 2.2.13, Architect 8.7.2, Remix 0.17.5

Steps to reproduce:
1. Install Remix from scratch with `npm init remix`, choose "Architect (AWS Lambda)" as deployment target
2. Ensure all works locally by running `arc sandbox` and `npm run dev` in parallel, and opening `localhost:3333`
3. Now deploy: `npm run build`, then `arc deploy`. Wait until deployment successfully finished

Expected behaviour:
1. Deployed version works
2. Local version still works with `arc sandbox`

Actual behaviour:
1. Deployed version returns `{"message":"Internal Server Error"}`.
In AWS CloudWatch log I see `Unknown application error occurred. Runtime.ImportModuleError`:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './client'\nRequire stack:\n- /var/task/node_modules/remix/index.js\n- /var/task/build/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './client'",
        "Require stack:",
        "- /var/task/node_modules/remix/index.js",
        "- /var/task/build/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

2. Local version is broken now too, it returns:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './client'
Require stack:
- /Users/xxx/remix-ts-aws/server/node_modules/remix/index.js
- /Users/xxx/remix-ts-aws/server/build/index.js
- /Users/xxx/remix-ts-aws/server/index.js
- /Users/xxx/remix-ts-aws/server/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object. (/Users/xxx/remix-ts-aws/server/node_modules/remix/index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xxx/remix-ts-aws/server/node_modules/remix/index.js',
    '/Users/xxx/remix-ts-aws/server/build/index.js',
    '/Users/xxx/remix-ts-aws/server/index.js',
    '/Users/xxx/remix-ts-aws/server/[eval]'
  ]
}
```

Let me know if any additional information required

Thank you,
Alex

**Comment by jfsiii** [comment]
I'm seeing the same behavior following the directions in the doc and architect README

<details><summary>Logs from installation</summary>

### local install
```
○ ~/repos ‣ npx create-remix@latest

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./my-remix-app
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Architect (AWS Lambda)
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> postinstall
> remix setup node

Successfully setup Remix for node.

added 563 packages, and audited 564 packages in 30s

128 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
💿 That's it! `cd` into "my-remix-app" and check the README for development and deploy instructions!
○ ~/repos ‣ cd my-remix-app/
○ ~/repos/my-remix-app ‣ arc sandbox
         App ⌁ remix-architect-app
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 9.4.0
         cwd ⌁ /Users/jfsiii/repos/my-remix-app

✓ Sandbox Found Architect project manifest: app.arc
✓ Sandbox Found testing environment variables: preferences.arc
✓ Sandbox Started service discovery emulator
✓ Sandbox @http server started
✓ Sandbox Project files hydrated into functions
✓ Sandbox Available @http (HTTP API mode / Lambda proxy v2.0 format) routes
    any /* ................................ server

    http://localhost:3333

✓ Sandbox Started in 26ms
❤︎ Local environment ready!


No routes matched location "/favicon.ico"
○ ~/repos/my-remix-app ‣
```

Local build with `arc sandbox` and `npm run dev` worked fine
</details>

Seems to deploy OK
<img width="982" alt="Screen Shot 2021-11-22 at 7 23 08 PM" src="https://user-images.githubusercontent.com/57655/142962832-882c516b-e54b-47d9-8ff8-d1e177fa0e64.png">
<img width="445" alt="Screen Shot 2021-11-22 at 7 23 23 PM" src="https://user-images.githubusercontent.com/57655/142962847-b204b36d-1d56-4188-bc21-57b2566e6e99.png">

But visiting the `*execute-api*` site shows the `Internal Server Error` message from the OP (1). The static assets resolve fine.

Taking a look at the arc logs show the same message as OP (2)
```
arc logs --production server
         App ⌁ remix-architect-app
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 9.4.0
         cwd ⌁ /Users/jfsiii/repos/remix-arc

Nov 22, 07:15:42 PM
ERROR
Uncaught Exception
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module './client'\nRequire stack:\n- /var/task/node_modules/remix/index.js\n- /var/task/build/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "stack": [
    "Runtime.ImportModuleError: Error: Cannot find module './client'",
    "Require stack:",
    "- /var/task/node_modules/remix/index.js",
    "- /var/task/build/index.js",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

```

and now the local install (using `arc sandbox` and `npm run dev`) fails with the error from OP (2) even though it was working before the `arc deploy` call.

**Comment by jfsiii** [comment]
I was able to prevent this error (but face another) by updating my `~/.aws/credentials` file and env vars as mentioned in https://arc.codes/docs/en/get-started/detailed-aws-setup

In my case, I only had one set of credentials which were for work. The failing logs above show `Profile ⌁ default`. I moved those under `[work]` and added a new set under `[personal]`. Now the deploy command shows `Profile ⌁ personal` and fails with a permissions problem but that seems better(?). Either way, just wanted to update.

**Comment by jfsiii** [comment]
The credentials thing was a distraction. Once I resolved them I was right back to the original issue. @tbeseda can reproduce the issue, has identified the cause, and is working on a fix.

**Comment by tbeseda** [comment]
<details>

<summary>Pasting my recent update in the Remix#architect Discord channel</summary>

We narrowed it down to the `postinstall` scripts in `create-remix/templates/*`. From what I can tell `remix setup node` ( [https://github.com/remix-run/remix/blob/main/packages/remix-dev/setup.ts](https://github.com/remix-run/remix/blob/main/packages/remix-dev/setup.ts) ) moves a few things into `node_modules/remix`. Namely the client and server deps. This is where the 500 error comes from.
So in the normal course of local development, this script is run and the “server function” has what it needs in the expected locations in the project root.

However, hydrating with Arc (part of deployment) does some treeshaking without lifecycle hooks from the root `package.json`. 
Also, it runs `npm ci --production` which doesn’t install devDependencies. So `remix setup node` isn’t available even if the `postinstall` script were to run as part of deployment.

Arc does let a developer be explicit about a function’s specific requirements by adding a `package.json` directly to the function’s source. In this case I added this to `./server/package.json`:

```json
{
  "scripts": {
    "postinstall": "remix setup node"
  },
  "dependencies": {
    "@remix-run/architect": "^1.0.6",
    "@remix-run/dev": "^1.0.6",
    "@remix-run/react": "^1.0.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "remix": "^1.0.6"
  }
}
```

This works!  [https://exapvvnkrl.execute-api.us-west-2.amazonaws.com/](https://exapvvnkrl.execute-api.us-west-2.amazonaws.com/) 

Fixing this for the end user isn’t too difficult, but I’m still thinking through the best way to approach how Remix and Arc interact. In theory it might be possible to avoid running both `arc sandbox` and `remix watch` at the same time in development. The goal might be to just run Remix while developing locally and configuring Arc to know how to deploy a Remix server function (Lambda) and the static `./public` directory (S3) correctly.

</details>

**Comment by Xiphe** [comment]
currently fixing this by running

```
node -e "
  const { dependencies, scripts } = require('./package.json');
  const { writeFileSync } = require('fs');
  writeFileSync(
    './server/package.json',
    JSON.stringify(
      {
        scripts: { postinstall: scripts.postinstall },
        dependencies,
      },
      null,
      2,
    ),
  );
"
```

before `npx arc deploy production`
