### ISSUE TITLE
require is not defined when using miniflare

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#2117]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

1. Clone [this repository](https://github.com/nicholaschiang/tweetscape].
2. Install deps and start the dev server: `yarn && yarn dev`
3. Open up the site.
4. Make a change to the classes of any element in `/app/routes/$topic.tsx`
5. See error:

![image](https://user-images.githubusercontent.com/20798889/155616317-506d73bd-4a28-4c58-afaf-1887c8288438.png)

And you should see the following (or something similar) logged to the console:

```
[dev:miniflare] [mf:err] /home/nchiang/repos/tweetscape/build/index.js:39
[dev:miniflare]     React = __toESM(require("react"));
[dev:miniflare]     ^
[dev:miniflare] 
[dev:miniflare] ReferenceError: require is not defined
[dev:miniflare]     at node_modules/@remix-run/dev/compiler/shims/react.ts (/home/nchiang/repos/tweetscape/node_modules/@remix-run/dev/compiler/shims/react.ts:1:1)
[dev:miniflare]     at __init (/home/nchiang/repos/tweetscape/build/index.js:9:56)
[dev:miniflare]     at /home/nchiang/repos/tweetscape/build/<stdin>:1:1
[dev:miniflare]     at Script.runInContext (node:vm:139:12)
[dev:miniflare]     at VMScriptRunner.runAsScript (/home/nchiang/repos/tweetscape/node_modules/@miniflare/runner-vm/src/index.ts:25:12)
[dev:miniflare]     at VMScriptRunner.run (/home/nchiang/repos/tweetscape/node_modules/@miniflare/runner-vm/src/index.ts:84:12)
[dev:miniflare]     at EventTarget.#reload (/home/nchiang/repos/tweetscape/node_modules/@miniflare/core/src/index.ts:737:42)
[dev:miniflare]     at /home/nchiang/repos/tweetscape/node_modules/@miniflare/core/src/index.ts:925:9
[dev:miniflare]     at Mutex.runWith (/home/nchiang/repos/tweetscape/node_modules/@miniflare/shared/src/sync/mutex.ts:34:48)
```

### Expected Behavior

There should be no build error.

### Actual Behavior

Quite intermittently, CloudFlare's Miniflare dev server will throw the following error when running with Remix:

```
[dev:miniflare] [mf:err] /home/nchiang/repos/tweetscape/build/index.js:39
[dev:miniflare]     React = __toESM(require("react"));
[dev:miniflare]     ^
[dev:miniflare] 
[dev:miniflare] ReferenceError: require is not defined
[dev:miniflare]     at node_modules/@remix-run/dev/compiler/shims/react.ts (/home/nchiang/repos/tweetscape/node_modules/@remix-run/dev/compiler/shims/react.ts:1:1)
[dev:miniflare]     at __init (/home/nchiang/repos/tweetscape/build/index.js:9:56)
[dev:miniflare]     at /home/nchiang/repos/tweetscape/build/<stdin>:1:1
[dev:miniflare]     at Script.runInContext (node:vm:139:12)
[dev:miniflare]     at VMScriptRunner.runAsScript (/home/nchiang/repos/tweetscape/node_modules/@miniflare/runner-vm/src/index.ts:25:12)
[dev:miniflare]     at VMScriptRunner.run (/home/nchiang/repos/tweetscape/node_modules/@miniflare/runner-vm/src/index.ts:84:12)
[dev:miniflare]     at EventTarget.#reload (/home/nchiang/repos/tweetscape/node_modules/@miniflare/core/src/index.ts:737:42)
[dev:miniflare]     at /home/nchiang/repos/tweetscape/node_modules/@miniflare/core/src/index.ts:925:9
[dev:miniflare]     at Mutex.runWith (/home/nchiang/repos/tweetscape/node_modules/@miniflare/shared/src/sync/mutex.ts:34:48)
```

**Comment by sobrinho** [comment]
@IshanKBG https://github.com/nicholaschiang/tweetscape

**Comment by IshanKBG** [comment]
@sobrinho Hey I  cloned your repository on my local machine and also tested it out but it seems to be working fine for me 
Could you try deleting .cache, build and public/build and restart miniflare?
Please tell me what happens after you do what I requested for

**Comment by sobrinho** [comment]
@IshanKBG I just correct the URL that the author originally submitted! :)

**Comment by IshanKBG** [comment]
Hey I cloned your repository on my local machine and also tested it out but it seems to be working fine for me
> Could you try deleting .cache, build and public/build and restart miniflare?
> Please tell me what happens after you do what I requested for

 @nicholaschiang Not sure what is causing this issue as it looks perfectly fine but could you do the steps I mentioned above ?
 Btw I used npm instead of yarn in my case

**Comment by nicholaschiang** [comment]
Yeah, no longer applicable as I'm using Fly instead of Cloudflare. Thanks though!
