### ISSUE TITLE
Support React.lazy in react 18

### ISSUE THREAD

**Issue by jacob-ebey** [remix-run/remix#213]
React lazy support can be achieved in Remix but the compiler currently bombs out on dynamic imports:

https://github.com/remix-run/remix/blob/9021fab2aa727ea423ed089550998227796f777c/packages/remix-dev/compiler/assets.ts#L80

Updating the linked "else" above to:

```js
} else if (output.entryPoint.startsWith("browser-route-module:"))
```

takes care of filtering out dynamically imported modules from the routes in the asset manifest and stops compilation from blowing up, as well as makes React.lazy "just work" with these relevant changes:

entry.client.tsx

```tsx
import { createRoot } from "react-dom";
import { RemixBrowser } from "remix";

const root = createRoot(document, { hydrate: true });
root.render(<RemixBrowser />);
```

entry.server.tsx

```tsx
import { PassThrough } from "stream";
// @ts-ignore
import { pipeToNodeWritable } from "react-dom/server";
import type { EntryContext } from "remix";
import { RemixServer } from "remix";

function renderToStringWithWritable(element: any, timeout = 10000) {
  return new Promise<string>((resolve, reject) => {
    const writable = new PassThrough();
    let res = "";
    writable.on("data", (d) => {
      res += String(d);
    });

    writable.on("end", function () {
      resolve(res);
    });

    const { startWriting, abort } = pipeToNodeWritable(element, writable, {
      onCompleteAll() {
        startWriting();
      },
      onError(err: Error) {
        reject(err);
      },
    });

    setTimeout(abort, timeout);
  });
}

export default async function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  let markup = await renderToStringWithWritable(
    <RemixServer context={remixContext} url={request.url} />
  );

  return new Response(markup, {
    status: responseStatusCode,
    headers: {
      ...Object.fromEntries(responseHeaders),
      "Content-Type": "text/html",
    },
  });
}
```

**Comment by tom-sherman** [comment]
> It seems to me that pipeToNodeWritable is just an alternative API to renderToString that doesn't really replace it.

I believe this is incorrect. From https://github.com/reactwg/react-18/discussions/22

> [`renderToString`] continues to work. It doesn’t support new features so we recommend switching to `pipeToNodeWritable`.

**Comment by tom-sherman** [comment]
@jacob-ebey I have `React.lazy` working with React 18 streaming SSR here: https://github.com/tom-sherman/remix-react-18/commit/4f0dab8383945bea6968e60a4967de21755fbc5e

I think this can be closed maybe?
