### ISSUE TITLE
Support older build targets

### ISSUE THREAD

**Issue by milamer** [remix-run/remix#215]
ESBuild supports [different build targets](https://esbuild.github.io/content-types/#javascript) to make the code backwards compatible with older devices. Currently remix only provides a [target](https://esbuild.github.io/api/#target) in the build command for the server build, but not the client build.

See [compiler.ts](https://github.com/remix-run/remix/blob/9021fab2aa727ea423ed089550998227796f777c/packages/remix-dev/compiler.ts#L213)

**Comment by vijaybritto** [comment]
I'm trying to port part of our Enterprise app to Remix and the browser support we need is ES2018 at least. Is adding `target` property going to be supported any time? Or there any technical reasons for this?
I can open a PR.

**Comment by machour** [comment]
@vijaybritto we always welcome PRs :)

**Comment by sergiodxa** [comment]
> You can define the build target in the remix.config.js as browserBuildTarget. It can either be a single string with the desired target (e.g. es2018) or an array of targets. It also supports browser versions!

I think using [.browserlist](https://github.com/browserslist/browserslist) for this would be better since that's also used by other tools.
