### ISSUE TITLE
Bug in tutorial code

### ISSUE THREAD

**Issue by Myrmod** [remix-run/remix#2154]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

I followed the tutorial and found a small mistake:

See https://remix.run/docs/en/v1/tutorials/blog#dynamic-route-params at 
```ts
// app/post.ts
import path from "path";
import fs from "fs/promises";
import parseFrontMatter from "front-matter";
import invariant from "tiny-invariant";
import { marked } from "marked";

//...
export async function getPost(slug: string) {
  const filepath = path.join(postsPath, slug + ".md");
  const file = await fs.readFile(filepath);
  const { attributes, body } = parseFrontMatter(
    file.toString()
  );
  invariant(
    isValidPostAttributes(attributes),
    `Post ${filepath} is missing attributes`
  );
  const html = marked(body);
  return { slug, html, title: attributes.title };
}
```

### Expected Behavior

The `slug` variable is defined

### Actual Behavior

The `slug` variable is not defined

**Comment by LyDawei** [comment]
`slug` is defined as a parameter of the `getPost` call. I'm not sure what you mean by the actual behavior being `undefined`.

**Comment by PascalGalle** [comment]
Yea fuck, I think I made a copy paste mistake somewhere and didn't check properly. Sorry, my bad.

**Comment by PascalGalle** [comment]
Seems like I made a copy paste mistake and didn't check properly. Sorry my bad.

**Comment by Myrmod** [comment]
Seems to have been a stupid copy paste mistake, which I didn't check properly. My bad.
