### ISSUE TITLE
development mode error at [@remix-run/architect]

### ISSUE THREAD

**Issue by insik-han** [remix-run/remix#2177]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

1. npx create-remix myapp
2. select aws
3. select Typescript
4. select npm install
5. npm run dev (npm run dev has dev:remix and dev:arc)

### Expected Behavior

development mode activate

### Actual Behavior

![image](https://user-images.githubusercontent.com/63291908/156283943-1602b1d6-766a-4335-b684-e0c8fafdfaf0.png)

**Comment by voltron2112** [comment]
Seeing same problem on windows 10. Haven't tried on Mac yet.

**Comment by voltron2112** [comment]
Oh just saw this notice on the getting started guide: https://remix.run/docs/en/v1/tutorials/blog#quickstart

`# IMPORTANT: Choose "Remix App Server" when prompted`

So looks like architect/aws is not ready for use. I went through CLI again and selected Remix App Server and it started up fine now.

**Comment by insik-han** [comment]
> Oh just saw this notice on the getting started guide: https://remix.run/docs/en/v1/tutorials/blog#quickstart
> 
> 
> 
> `# IMPORTANT: Choose "Remix App Server" when prompted`
> 
> 
> 
> So looks like architect/aws is not ready for use. I went through CLI again and selected Remix App Server and it started up fine now.
> 
> 

Thanks. It's not quite solution but I'll try it. 👍

**Comment by mcansh** [comment]
the readme says to install `@architect/architect` :) https://github.com/remix-run/remix/tree/main/templates/arc#architect-setup

however it should be a devDependency as of v10 - there was a PR to update the template but it included other changes, i'll update the template with just that

**Comment by machour** [comment]
Fixed in https://github.com/remix-run/remix/commit/af74549dfe14a77e0487a41d304dd0d0b46bc035
