### ISSUE TITLE
Server Error messages: show more useful info?

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#218]
It would be really nice to get the route loader that threw the error as well as any params. Would help debugging a lot :)

**Comment by Pitasi** [comment]
Is this working (or maybe I didn't understand the problem that was solved in #242, totally possible :))?

I'm in dev mode, but I see stacktraces pointing at the bundled js:

```ts
// add-vote.tsx

export const action: ActionFunction = async ({
	request,
}): Promise<Response> => {
	throw new Error("sample message");
};
```

![image](https://user-images.githubusercontent.com/15048443/151321704-94d91017-40ee-4733-a24d-132f1950b1fe.png)

![image](https://user-images.githubusercontent.com/15048443/151321851-1ad1dd18-1a0f-4c06-9d3d-d750d31d15e6.png)

One thing I noticed though: the error is showing for the route `/add-vote` (the browser address bar says that) but in the browser source panel I cannot see the sourcemap for that route:

![image](https://user-images.githubusercontent.com/15048443/151322389-a793f4e0-91cb-452c-bae8-8b918bd5c2c2.png)

I can only see the `/sessions/10` route (`$sessionId.tsx`) which is the one the brought me to `/add-vote`.
