### ISSUE TITLE
Unable to create Remix project using Vercel as provider

### ISSUE THREAD

**Issue by ajay-paramlogic** [remix-run/remix#2202]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

 npx create-remix@latest
 Choose Vercel
 Choose TypeScript
 Choose Yes

### Expected Behavior

The project should get created and all the dependencies should be installed

### Actual Behavior

```sh
➜  cmca npx create-remix@latest


R E M I X - v1.2.3

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./my-remix-app
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm ERR! code ENOVERSIONS
npm ERR! No versions available for undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mystical/.npm/_logs/2022-03-04T05_34_00_052Z-debug.log
Error: Command failed: npm install
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.createApp (/Users/mystical/.npm/_npx/5164864a48bff686/node_modules/create-remix/index.js:135:19)
    at async run (/Users/mystical/.npm/_npx/5164864a48bff686/node_modules/create-remix/cli.js:199:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 45737,
  stdout: null,
  stderr: null
}
```

**Comment by girishk21** [comment]
> To the maintainers

It's a problem with the `"@remix-run/eslint-config"` package. It throws the error:

```sh
npm ERR! code ENOVERSIONS
npm ERR! No versions available for undefined
```

@ajay-paramlogic can you remove `"@remix-run/eslint-config"` from your `package.json` and as well as the entry from `.eslintrc.js`, and run

```sh
npm i
```

it should work as expected in the mean time the team fixes the eslint package issue

**Comment by ajay-paramlogic** [comment]
> > To the maintainers
> 
> It's a problem with the `"@remix-run/eslint-config"` package. It throws the error:
> 
> ```shell
> npm ERR! code ENOVERSIONS
> npm ERR! No versions available for undefined
> ```
> 
> @ajay-paramlogic can you remove `"@remix-run/eslint-config"` from your `package.json` and as well as the entry from `.eslintrc.js`, and run
> 
> ```shell
> npm i
> ```
> 
> it should work as expected in the meantime the team fixes the eslint package issue

@girishk21 thanks for quick response. removing the package `@remix-run/eslint-config` does fix the problem. Hope the issue gets resolved so that I can enable the remix linting again.
