### ISSUE TITLE
More flexibility with meta tags

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#224]
There are already some special cases for different kinds of meta tags:

https://github.com/remix-run/remix/blob/9021fab2aa727ea423ed089550998227796f777c/packages/remix-react/components.tsx#L576-L585

I'm not sure how much bigger that would need to grow to support all the use cases people will have. For example, I need to set this header for one of my pages:

```html
<meta http-equiv="refresh" content="1740">
```

I'll probably have to use `handle` and `useMatches` for this today. But it would be nice if I could use the regular `meta` function.

I think something more flexible would cover all use cases. Maybe something like this could be supported:

```tsx
export const meta: MetaFunction = () => {
  return [
    <meta httpEquiv="refresh" content="1740" />,
  ]
}
```

Would be pretty flexible I think :) And perhaps the existing API could stick around for the more common use cases?

**Comment by MichaelDeBoey** [comment]
Closed by #2331
