### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by abdessamadelhamdany** [remix-run/remix#2248]
### What version of Remix are you using?

v1.2.3

### Steps to Reproduce

The examples in the docs https://remix.run/docs/en/v1/api/remix#uploadhandler

Just after adding this code inside a route

```javascript
let uploadHandler = unstable_createFileUploadHandler({
  maxFileSize: 5_000_000,
  file: ({ filename }) => filename,
})
```

### Expected Behavior

To work, as expected from the docs

### Actual Behavior

Log the error to the the browser console on page load

<img width="612" alt="Screen Shot 2022-03-07 at 23 30 32" src="https://user-images.githubusercontent.com/20196583/157131749-404bb25c-13a9-4a0b-b79b-ef208fff7571.png">

**Comment by mzaatar** [comment]
I have had the same problem for a few days now. following...

**Comment by abdessamadelhamdany** [comment]
I think some `node` code end-up in the client side, as Buffer available for node but not for the browser
But i can't find where's it's coming from, currently looking for a way to handle uploads with external express server

**Comment by Jaikant** [comment]
I am facing a similar error, while trying to include [graphql-ws](https://github.com/enisdenjo/graphql-ws) in my app.
```
constants.js:5 Uncaught ReferenceError: Buffer is not defined
    at node_modules/ws/lib/constants.js (constants.js:5:17)
    at __require2 (chunk-FDP6WGZF.js:19:44)
    at node_modules/ws/lib/buffer-util.js (buffer-util.js:3:26)
    at __require2 (chunk-FDP6WGZF.js:19:44)
    at node_modules/ws/lib/permessage-deflate.js (permessage-deflate.js:5:20)
    at __require2 (chunk-FDP6WGZF.js:19:44)
    at node_modules/ws/lib/receiver.js (receiver.js:5:27)
    at __require2 (chunk-FDP6WGZF.js:19:44)
    at wrapper.mjs:2:22
```

**Comment by Jaikant** [comment]
I think my issue is documented [here](https://remix.run/docs/en/v1/pages/gotchas) (I need to try it though)

**Comment by kiliman** [comment]
I show a way to import the `buffer` polyfill package. NOTE: it does require a patch of Remix compiler since it complains about importing package of node built-ins.

https://github.com/kiliman/remix-walletconnect

**Comment by fergusmeiklejohn** [comment]
yeah I have the same problem :-( 
It's a difficultly of working with Remix that the app actually crashes (no JS) but still renders the html so it's not clear that it's crashed.

**Comment by abdessamadelhamdany** [comment]
I have moved to Next.js for the moment as i already have some working examples of what i'm trying to do.

Please @fergusmeiklejohn  if this solution is working for you, let me know so i can close this issue.

Thanks

**Comment by fergusmeiklejohn** [comment]
putting the code in a server only file solves the problem but the Remix team should still be made aware of this bug. It's probably a problem the Buffer package authors need to fix

**Comment by Shaquu** [comment]
Same problem for me. Using `@emotion/server/create-instance` leads to `ReferenceError: Buffer is not defined`

**Comment by Jaikant** [comment]
I moved on to nextjs mainly because remix doesn't have websockets connecting its node server to client.

**Comment by drewdecarme** [comment]
@Shaquu I'm having roughly the same issues as well. I'm using Cloudflare Pages as my preferred Remix setup. I tried the example locally and it seems to build fine in dev mode using the `@remix-run/serve` package.

I also tried to change the emotion context files to `context.server.ts` and `context.client.ts` to better model their documentation to see if the compiler would leave out the that code but it appears that it's not.

Hopefully that info helps others who are troubleshooting this. TBH, I tried styled-components first but ran into SSR issues and inconsistencies between the server and client generated classes. I tried shimming Linaria but there's too many unknowns with that so I came to emotion. It seems like a fully baked example but this one issue is holding me up.

**Comment by Shaquu** [comment]
@drewdecarme to be honest, I just removed emotion references from the code and I am going forward.
It is not that important to stop me from getting to know remix.

**Comment by drewdecarme** [comment]
Yeah I'm completely with you on that one. I'm fine with writing the styles I need outside the context of the component. I just love the convenience of co-locating the styles with the component which I've gotten accustomed to over the years.

**Comment by Shaquu** [comment]
> Yeah I'm completely with you on that one. I'm fine with writing the styles I need outside the context of the component. I just love the convenience of co-locating the styles with the component which I've gotten accustomed to over the years.

Maybe try this one?

https://github.com/emotion-js/emotion/issues/2554#issuecomment-1066068218

**Comment by mocon** [comment]
Thanks a lot for the fix @fergusmeiklejohn! Do you know if it's possible to update the `maxFileSize` for a custom `uploadHandler`? I'm trying to allow large video file uploads, but it seems to be inheriting the default `3_000_000` from `unstable_createFileUploadHandler`.

**Comment by fergusmeiklejohn** [comment]
Sure you just do something like this:
```ts
const uploadHandler = unstable_createMemoryUploadHandler({
  maxFileSize: 5_000_000,
});
```

**Comment by chaance** [comment]
Is anyone able to reproduce this with the latest release? We added some node browser polyfills and removed some node-specific code from the runtime package in the last few updates.

**Comment by kiliman** [comment]
Checked on 1.3.2 and still can't use `Buffer` on client. 

If you just try to use Buffer on the client, it compiles but you get runtime error: `ReferenceError: Buffer is not defined`

If you install polyfill `buffer` package, you get the error: `It appears you're using a module that is built in to node, but you installed it as a dependency which could cause problems. Please remove buffer before continuing.`

This is why I have the patch that removes the check for node builtins.

**Comment by julienmonnard** [comment]
Hello! 
I was trying to achieve the same as in the doc here https://remix.run/docs/en/v1/api/remix#unstable_createfileuploadhandler and this `Buffer is not defined` error happened to me as well...

But I noticed that if instead of this:
```javascript
// Code from the doc
const uploadHandler = unstable_createFileUploadHandler({
    maxFileSize: 5_000_000,
    file: ({ filename }) => filename,
});

export const action: ActionFunction = async ({ request }) => {
    const formData = await unstable_parseMultipartFormData(
        request,
        uploadHandler
    );

    const file = formData.get('avatar');

    // file is a "NodeFile" which has a similar API to "File"
    // ... etc
};
```
you do this:
```javascript
// Notice the uploadHandler being defined INSIDE the action function
export const action: ActionFunction = async ({ request }) => {
    const uploadHandler = unstable_createFileUploadHandler({
        maxFileSize: 5_000_000,
        file: ({ filename }) => filename,
    });

    const formData = await unstable_parseMultipartFormData(
        request,
        uploadHandler
    );

    const file = formData.get('avatar');

    // file is a "NodeFile" which has a similar API to "File"
    // ... etc
};
```

Then the error doesn't appear anymore and the file is available with `formData.get('avatar')`

I just started using Remix, so not sure it's a correct approach, but maybe it's at least a step in the right direction 🙂

**Comment by clintonwoo** [comment]
I actually got this error on 1.3.3 also when only using the regular formData parser like `await request.formData();` in an action but downgrading to 1.3.2 fixed it.

Pretty big bug since crashes all the client side js.

**Comment by s-oram** [comment]
I'm also running into this error since upgrading to Remix 1.3.4. Downgrading to Remix 1.3.2 resolves the error.

(Unfortunately Remix 1.3.1 to 1.3.3 all throw a different, unrelated, error when deployed to AWS. 😂)

**Comment by jacargentina** [comment]
Same error, but not using `unstable_parseMultipartFormData` at all.

**Comment by timfee** [comment]
I have a very trivial example where it appears React 18 is the culprit, https://github.com/cloudflare/wrangler2/issues/754 -- not sure if anyone else has such an issue

**Comment by chaance** [comment]
FYI, I am working on this, but in the mean time you can either create a separate `.server.js` file as mentioned before, or initialize your server code inside your loader or action instead of the top-level scope of the route module.

```js
// instead of this...
let uploadHandler = unstable_createFileUploadHandler({
  maxFileSize: 5_000_000,
  file: ({ filename }) => filename,
});

export async function action({ request }) {
  let formData = await unstable_parseMultipartFormData(request, uploadHandler);
  // ...
};

// do this...
export async function action({ request }) {
  let uploadHandler = unstable_createFileUploadHandler({
    maxFileSize: 5_000_000,
    file: ({ filename }) => filename,
  });
  let formData = await unstable_parseMultipartFormData(request, uploadHandler);
  // ...
};
```

Understand that this may be affecting code aside from `unstable_createFileUploadHandler` but this should work for *any* server-side-only code you are working with until we can properly address this.

**Comment by jacargentina** [comment]
@chaance 

i dont get it: why the same route code, migrating to react18 + latest remix throws the error? I’m not using any '[](https://github.com/jacargentina)@[jacargentina](https://github.com/jacargentina) jacargentina commented [7 days ago](https://github.com/remix-run/remix/issues/2248#issuecomment-1086412432)
Same error, but not using unstable_parseMultipartFormData' as i posted early.

**Comment by chaance** [comment]
> @chaance
> 
> i dont get it: why the same route code, migrating to react18 + latest remix throws the error? I’m not using any `unstable_parseMultipartFormData` as i posted early.

I'm unsure how React 18 specifically would cause an issue like this, but this isn't just about `unstable_parseMultipartFormData`, it's about *any* code that should only be in your server bundle.

If you can create a new issue with a minimal repro showing your problem with React 18 we can try to help out there.

**Comment by drewdecarme** [comment]
@chaance Unfortunately, I'm still getting the same issues when trying to follow the emotion example in the examples directory for Remix. I've tried a few of the fixes that you have mentioned before but still experiencing the issue when using emotion.

Do you have any guidance based upon how the emotion example is setup in the docs at the moment?

**Comment by danthareja** [comment]
@drewdecarme - I was also having this same issue when trying to set up emotion.

In my case, I was following the docs for [Chakra UI](https://chakra-ui.com/guides/getting-started/remix-guide#2-provider-setup) which had a shared `context.ts` file for both client and server contexts.

I was able to fix my issue by making sure each context was within their own file, and therefore loaded within their old bundle.

**Comment by shymarrai** [comment]
for me what worked was:

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import inject from '@rollup/plugin-inject'

export default defineConfig({
	plugins: [vue()],
	resolve: {
		alias: {
			'@': path.resolve(__dirname, 'src'),
		}
	},
	build: {
		rollupOptions: {
			plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
		},
	},
})


reply to this comment:

https://github.com/vitejs/vite/discussions/2785#discussioncomment-1452855

**Comment by artokun** [comment]
I'd like to point out that if you're a dummy like me, and googling `Uncaught ReferenceError: Buffer is not defined` brought you here while setting up WebSockets in the Remix client. You might have done this:

```ts
// ws.client.ts
import WebSocket from 'ws';
const ws = new WebSocket('ws://localhost: 3000');
```

Turns out `WebSocket` is _native_ to modern browsers, so you really just need to omit the import and you're good to go
I hope this helps at least one other dev out there!

**Comment by mhmdunl1** [comment]
Use this on the page or function where you get an error:

`window.Buffer = window.Buffer || require("buffer").Buffer;`

**Comment by makerovski** [comment]
Thank you @mhmdunl1, your solution helped me :)

**Comment by jdnichollsc** [comment]
Hey folks, check my example to fix this issue https://gist.github.com/jdnichollsc/b73eca1f34bdd1e3a95283774fda2212
