### ISSUE TITLE
ScrollRestoration doesn't go to top after GET form submission

### ISSUE THREAD

**Issue by gaetansnl** [remix-run/remix#2263]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

- Go here https://codesandbox.io/s/github/remix-run/remix/tree/main/examples/search-input
- Type "breaking" in the input
- Press Enter
- Add " bad" to the input
- Scroll to the bottom of the page
- Press "Enter"
![97OP6Z4JL5zValcMKLrSGLJsh](https://user-images.githubusercontent.com/8348807/157287750-25b9a8c2-84e5-4ad4-920f-0978ca09a7c4.gif)

### Expected Behavior

The scroll goes to the top of the page

### Actual Behavior

The scroll stays at bottom

Current workaround : 
- Copy past ScrollRestoration source
- Remove the two useEffect with ` wasSubmissionRef.current = true;`
- Replace the Remix exported ScrollRestoration with custom ScrollRestoration

I guess this workaround might break other behaviors

**Comment by udasitharani** [comment]
This isn't really a remix issue. Even if you build this app with plain react, you will find it sticking to its place.
The thing is, you are using a `<Form />` and it uses javascript to get the content and updates your page, its not navigating or refreshing on submission.
If you still want this behavior, you can do 2 things.
1. Pass a function to `onSubmit` in `<Form />` which scrolls back to the top on submission.
2. Or, you can simply use `<form />` which will make sure that user navigates to a new page everytime they search - not recommended way

**Comment by udasitharani** [comment]
Think of `<Form />` as Remix's way of abstracting the logic for fetching data and updating things :)

**Comment by gaetansnl** [comment]
Thank you for your answer. I posted this example because it was minimal. But the problem also exists when navigating between different pages with different search params.

**Comment by udasitharani** [comment]
I just tried this:
1. Search `a`
2. scroll down to bottom
3. change url to -> `http://localhost:3000/?search=b` and hit enter

This worked and the scroll position was restored to 0. 
Are you talking about something else?

**Comment by kiliman** [comment]
I tried your repro steps on codesandbox and Remix worked correctly. Pressing enter on form while scrolled to the bottom moved to top.

**Comment by udasitharani** [comment]
I could reproduce the reported behavior though.

**Comment by gaetansnl** [comment]
The screen recording is on Firefox Windows. Here is the same problem across different pages. I'm on a page, search something new, when the route change back to the result list, it scrolls at the bottom.
![PMvZOmCbiNfHcTCjML2pSFkAH](https://user-images.githubusercontent.com/8348807/157616437-061aaefa-d91c-41ba-86d5-727c4906c55b.gif)

**Comment by udasitharani** [comment]
Can you share a minimal example for this?

**Comment by IanWitham** [comment]
Here's the TV example with a "sticky" search bar to make the problem easier to see: [CodeSandbox](https://codesandbox.io/s/hardcore-kate-29o01q)

Steps to reproduce:

1. Search cat.
2. Scroll to bottom of results
3. Search dog.
4. Notice the scroll has not been restored
5. Scroll to the bottom of the results
6. Change the search to "fish" in the url and press enter
7. Notice that when the page reloads the scroll has restored to the top (!)
8. Scroll to the bottom of the page and click the link (it's a Remix Link component)
9. Notice that the scroll has now been restored
10. Wonder why a get submission and a link with url parameters should behave differently.

The point of the ScrollRestoration component should be to emulate the browser behaviour exhibited in step 6, is it not?

**Comment by SleeplessByte** [comment]
This also happens with POST method.

**Comment by brophdawg11** [comment]
This should be fixed now as the underlying `ScrollRestoration` component in `react-router-dom` differentiates between `<Form>` GET/POST submissions and should be resetting scroll on GET submissions.  I tested Remix 1.11.1 on the above CodeSandbox and it worked as expected.
