### ISSUE TITLE
Running bug-report-test fails

### ISSUE THREAD

**Issue by joms** [remix-run/remix#2287]
### What version of Remix are you using?

HEAD of dev branch

### Steps to Reproduce

Clone the project and follow the instructions for using the bug-report-test as a bug report.

### Expected Behavior

The test should run

### Actual Behavior

```
~/code/remix dev 12s
❯ jest integration/bug-report-test.ts
(node:17441) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17441) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
 FAIL   integration  integration/bug-report-test.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'close')

      63 |   });
      64 |
    > 65 |   // This creates an interactive app using puppeteer.
         |                          ^
      66 |   app = await createAppFixture(fixture);
      67 | });
      68 |

      at Object.<anonymous> (integration/bug-report-test.ts:65:26)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.304 s
Ran all test suites matching /integration\/bug-report-test.ts/i.
```

**Comment by nicksrandall** [comment]
Can confirm this is an issue. If it's helpful, I have an Apple Silicon MBP running node 14 (LTS).

**Comment by nicksrandall** [comment]
The bug appears to stem from that the`beforeAll` hook is not being run thus `app` is undefined when `app.close` in `afterAll` hook.

**Comment by nicksrandall** [comment]
#2360 fixed the issue for me. I also had to `rm -r build && yarn build`.

**Comment by machour** [comment]
@joms seems to be working fine now on M1 (is that was your CPU)
Feel free to open a new issue if that still fails for you, providing more information about your setup 🙏🏼
