### ISSUE TITLE
Redirecting back to request's URL causes destination to lose HTTPS

### ISSUE THREAD

**Issue by adwinying** [remix-run/remix#2306]
### What version of Remix are you using?

1.1.1

### Steps to Reproduce

Assume that I have a route `foo` accessible at `https://example.org/foo` that has an action function:

```jsx
export const action = async ({ request }) => {
  return redirect(request.url);
};

export default Foo() {
  return (
    <form action="POST">
      <button type="submit"> Submit Form</button>
    </form>
  );
}
```

### Expected Behavior

When the submit button is pressed, the POST request should redirect to `https://example.org/foo`

### Actual Behavior

When the submit button is pressed, the POST request redirects to `http://example.org/foo`

**Comment by kiliman** [comment]
Have you confirmed that `request.url` contains *https*?

**Comment by machour** [comment]
@adwinying I'm seeing the same thing as you. It may be related to https://github.com/remix-run/remix/issues/420

In `entry.server.tsx`, could you log request.url at the start of `handleRequest()` and confirm that you're seeing http instead of https ?

How did you configure https://example.org in your server? Is it proxying a http url ? (this is my case)

**Comment by adwinying** [comment]
@kiliman 
`request.url` did not contain https.

@machour 
Oh, #420 seems like a workaround. I’ll try it out 👍 

> In entry.server.tsx, could you log request.url at the start of handleRequest() and confirm that you're seeing http instead of https ?
yep, I’m seeing http instead of https.

> How did you configure https://example.org/ in your server? Is it proxying a http url ? (this is my case)
I deployed my app to heroku so I assume some kind of reverse proxy is in effect.

**Comment by adwinying** [comment]
Thanks for the replies, the workaround in #420 worked flawlessly.
Hopefully a more robust solution would be out soon.
Will close this since it's a duplicate of #420

**Comment by machour** [comment]
@adwinying but you're still doing an extra redirect for nothing all the time : https => http => https
Another solution is to use a relative redirect if you're able to: `redirect('/foo')`

**Comment by oliverjam** [comment]
In case anyone else stumbled across this like me, my solution in the end was to just redirect to the relative path+search:

```js
let { pathname, search } = new URL(request.url);
redirect(pathname + search);
```
