### ISSUE TITLE
Actions in routes that are in Layouts

### ISSUE THREAD

**Issue by PoofyFoopy** [remix-run/remix#2307]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

Say you have an app with the following file structure:
```
app/
├── routes/
│   └── __general
│   │   └── signin.tsx
│   ├── index.tsx
│   ├── __general.tsx
└── root.tsx
```
You have an action in signin to handle POST sign in requests
signin.tsx
```tsx
...

export const action: ActionFunction = async ({ request }) => {
	const formData = await request.formData();
	console.log(formData);
};
...
```

### Expected Behavior

I would expect for the POST request to go through and data be accessible in the action.

And since `__general.tsx` is a layout route, there should be no reason for it to need the data, i.e. no reason for an action to be exported in the file.

### Actual Behavior

When you make the actual POST request to the server, you receive the following error:
```
There was an error running the action for route routes/__general
Error: You made a POST request to http://localhost:3000/signin but did not provide an `action` for route "routes/__general", so there is no way to handle the request.
```
According to the error, you should add an acction to `__general.tsx` which doesn't make sense since it's a layout route file.

When you do add the action, you receive the following error:
```
✘ [ERROR] [plugin browser-route-module] Actions are not supported in layout routes: routes/__general
```

So the action in `__general.tsx` is required yet not supported?
How are you supposed to handle non-GET requests to a route that is included in a layout?

**Comment by acoreyj** [comment]
I ran into a similar issue, but my signin route was at /app/routes/signin/index.tsx and the error said I needed an action at root even though signin/index.tsx had an action.

Moving signin/index.tsx to just /routes/signin.tsx allowed it to find the action.

**Comment by kiliman** [comment]
When you have nested layouts with an index route, you need to explicitly specify you want the index route.

`/signin` will match both `routes/signin.tsx` and `routes/signin/index.tsx` so to disambiguate, you should add `?index` to your action.
```ts
<Form action="/signin?index" method="post">
```
https://remix.run/docs/en/v1/api/conventions#action
> If you want to post to an index route use ?index in the action: `<Form action="/accounts?index" method="post" />`

**Comment by acoreyj** [comment]
> /signin will match both routes/signin.tsx and routes/signin/index.tsx so to disambiguate, you should add ?index to your action.

Ah that makes sense, but to be clear routes/signin.tsx did not exist only routes/signin/index.tsx so nothing was really ambiguous but due to the logic it was finding /app/root.tsx as the parent route which is a bit confusing but now that I'm understanding the nested routing a bit more it makes sense

**Comment by PoofyFoopy** [comment]
> 

Thanks, this worked for me. My actual file structure was
```
app/
├── routes/
│   └── __general
│   │   └── signin
│   │   │   ├── index.tsx
│   │   │   └── signin.tsx
│   ├── index.tsx
│   ├── __general.tsx
└── root.tsx
```
And specifying the POST request to `localhost:3000/signin?index` fixed the issue.
Also, exporting the action defined in `signin.tsx` in `index.tsx` made the action reachable.

I'd think that in this situation it would default to using the `__general/signin/index.tsx` file since there is no `__general/signin.tsx`. This would allow for you to POST to `localhost:3000/signin` without the param, since it would default to the `__general/signin/index.tsx`.

**Comment by kiliman** [comment]
I think for index routes, it always defaults to the parent layout (even if that parent is not a direct parent but all the way to root 😳)

This way it is consistent and you should always explicitly state you want the index route with `?index`.

This only applies to POST since a POST can only be processed by a singled route/action, unlike GET where it will call all loaders for the matching routes.
