### ISSUE TITLE
Upgrading from 1.2.1 to 1.2.2 (and beyond) breaks react-live

### ISSUE THREAD

**Issue by selbekk** [remix-run/remix#2321]
### What version of Remix are you using?

1.2.2 (and 1.2.3)

### Steps to Reproduce

I've created a reproduction here: https://github.com/selbekk/remix-react-live-repro

Steps I followed to create this repro:

- Run `npx create-remix@latest`
- Choose Remix App Server, install deps and enter folder
- Run `npm install react-live@next`
- Add the code below to show a very basic live code editor
- Downgrade to 1.2.2 and see that the error is there still
- Downgrade to 1.2.1 and see that the error is _not_ there anymore.

This sounds like a [`react-live`](https://github.com/FormidableLabs/react-live) bug, but when I debugged this (for daaaays), it looks like a compilation bug.

This crashes because of a compilation error. It says the `import_NameManager.default` is not a constructor. That's correct (even though it should be) - it's an object containing the "default" property, which in turn includes the NameManager constructor. So it looks like it has something to do with compiling [Sucrase](https://github.com/alangpierce/sucrase)!

Here's a typical place in the compiled code (found in `public/build`) where it's used:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1307267/158321146-b5114386-67cc-4773-b6ef-07dbf327cbb7.png">

After fixing this one-off mistake, I notice that this happens with all default exports - and that's why I think it's a compilation level issue that might be addressed here.

It definitely sounds like it has something to do with #1998, but as far as I can see, Sucrase [doesn't do the faulty default export thing](https://github.com/alangpierce/sucrase/blob/main/src/NameManager.ts) this issue warns about. I can't see it in the compiled code either, so I'm not sure where to look next. However, [this issue in Sucrase](https://github.com/alangpierce/sucrase/issues/644) also sounds related - it's the same issue, just a different class.

Any help would be greatly appreciated!

### Expected Behavior

I would expect it to work

### Actual Behavior

I get a compilation error!

**Comment by nihgwu** [comment]
I proposed the solution in the licked issue, but it only works for Vite, how can I alias module resolution in Remix?

**Comment by MichaelDeBoey** [comment]
This seems to be a bug in `react-live` in combination with `esbuild`, so I'm going to close this one for now.

**Comment by nihgwu** [comment]
@MichaelDeBoey can you open the ticket, [here](https://github.com/evanw/esbuild/issues/2128) is the answer from the author of `esbuild`, it would be nice we can config esbuild via remix.config 
related to https://github.com/remix-run/remix/issues/1405, it would be nice if we can provide a way to alias module resolution
