### ISSUE TITLE
Links to Remix Source Repo and Remix Roadmap error

### ISSUE THREAD

**Issue by BurntCaramel** [remix-run/remix#233]
1. Visit https://remix.run/dashboard/support
2. Click on Visit Remix Repo
3. <img width="559" alt="image" src="https://user-images.githubusercontent.com/2635733/128098390-35143d1e-89ca-49f2-83e2-a70ca0073ee0.png">

Same happens for Visit Remix Roadmap

**Comment by machour** [comment]
Not applicable anymore
