### ISSUE TITLE
Glowing Logo doesn't render correctly

### ISSUE THREAD

**Issue by Richienb** [remix-run/remix#2337]
### What version of Remix are you using?

N/A

### Steps to Reproduce

When opened in the browser, `1200x627 - Glowingsvg.svg` from the [Logo folder](https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c) has a barely visible black border around the letters:

![Remix](https://user-images.githubusercontent.com/29491356/158528207-043216d1-1cad-43aa-9e8f-dee227862906.png)

### Expected Behavior

The logo should look like the png version:

![Remix](https://user-images.githubusercontent.com/29491356/158528328-c1dd4f37-bc1a-4aa2-ab0c-94191c1fdfd6.png)

### Actual Behavior

There shouldn't be a slight border around the letters.

**Comment by chaance** [comment]
Closing this as issues should pertain to Remix itself. We do our best with the assets in our Drive and may update them in the future 🙂
