### ISSUE TITLE
vercel-plugin-node.build  vercel fail to deploy remix

### ISSUE THREAD

**Issue by veritem** [remix-run/remix#2338]
### What version of Remix are you using?

^1.2.3

### Steps to Reproduce

Deploy any remix project using tailwindcss

### Expected Behavior

It should deploy seamlessly 

### Actual Behavior

![image](https://user-images.githubusercontent.com/53856673/158658149-04202b37-8e6e-466e-bdeb-586e0279cfeb.png)

**Comment by machour** [comment]
it's seems your screenshot didn't go through :
![Screen Shot 2022-03-16 at 6 46 50 PM](https://user-images.githubusercontent.com/304450/158654529-23d0881e-2f3d-49ac-9907-007a770c43ca.png)

**Comment by veritem** [comment]
sorry update :)

**Comment by brandonpittman** [comment]
Just to prove OP isn't crazy, I'm see this too. Just using the demo plus Tailwind and a couple pages. [Here's a repo.](https://github.com/brandonpittman/remix-blog)

**Comment by machour** [comment]
@veritem looks like some sort of problem was fixed with vercel last week: https://github.com/vercel/vercel/discussions/4711
Did this fix your problem with pnmp?
