### ISSUE TITLE
Allow other loader endpoints

### ISSUE THREAD

**Issue by BurntCaramel** [remix-run/remix#234]
I would like to have endpoints to say render CSS on the fly, or generate images/icons on the fly, or talk to another server and proxy the response back.

I could do this I suppose by creating new routes, and in their loader returning the response I like. But then I’m not using the actual page route for anything (unless I turned it into documentation for the endpoint… interesting)

So is there a way to create other loader endpoints? All I know of is the global loader and the route specific loaders. Another sort of loader that can be shared across different routes, while not just throwing stuff into the global route, would be useful. It would be nice to have a hook for this too, say `useSharedData("some-identifier")`.

**Comment by chaance** [comment]
Closing since you can now do this with resource routes 🎉
