### ISSUE TITLE
[code ETARGET] npx create-remix@latest failed

### ISSUE THREAD

**Issue by dpyzo0o** [remix-run/remix#2371]
### What version of Remix are you using?

1.3.1

### Steps to Reproduce

npx create-remix@latest --template remix-run/indie-stack

### Expected Behavior

It works

### Actual Behavior

![image](https://user-images.githubusercontent.com/24768249/158957743-3a387ec6-b4b0-4f5c-8562-945715460e95.png)

**Comment by MichaelDeBoey** [comment]
Just ran it and it doesn't happen for me.
Could you try again and see if it persists?
If so, I think it's something on your end.

**Comment by dpyzo0o** [comment]
@MichaelDeBoey I tried with node 14 and 16, both failed with the same error. If it's something on my end, how could I debug it?

**Comment by MichaelDeBoey** [comment]
@dpyzo0o Not sure how you could debug it tbh.

Have you tried using the latest version of Node v14 & v16?

**Comment by TheGreyRaven** [comment]
Ill hijack this issue as I have a very similar error:
```
D:\>npx create-remix@latest
💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? wallbang_remix
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
Error: Cannot find module 'D:\wallbang_remix\package.json'
Require stack:
- C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js
- C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js
- C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createApp (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js:156:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js:68:3)
    at async run (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js:324:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\create.js',
    'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli\\commands.js',
    'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli.js'
  ]
}
Error: Command failed: npx --yes @remix-run/dev@1.3.1 create
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (C:\Users\Oscar\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\Oscar\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5804,
  stdout: null,
  stderr: null
}
```
Its my first time running Remix command and running Node: v16.11.1

**Comment by mcansh** [comment]
> Ill hijack this issue as I have a very similar error:
> 
> ```
> D:\>npx create-remix@latest
> 💿 Welcome to Remix! Let's get you set up with a new project.
> 
> ? Where would you like to create your app? wallbang_remix
> ? What type of app do you want to create? Just the basics
> ? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
> ? TypeScript or JavaScript? TypeScript
> ? Do you want me to run `npm install`? Yes
> Error: Cannot find module 'D:\wallbang_remix\package.json'
> Require stack:
> - C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js
> - C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js
> - C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.createApp (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js:156:16)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.create (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js:68:3)
>     at async run (C:\Users\Oscar\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js:324:9) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\create.js',
>     'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli\\commands.js',
>     'C:\\Users\\Oscar\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli.js'
>   ]
> }
> Error: Command failed: npx --yes @remix-run/dev@1.3.1 create
>     at checkExecSyncError (node:child_process:826:11)
>     at Object.execSync (node:child_process:900:15)
>     at run (C:\Users\Oscar\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:30:17)
>     at Object.<anonymous> (C:\Users\Oscar\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:35:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
>     at node:internal/main/run_main_module:17:47 {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 5804,
>   stdout: null,
>   stderr: null
> }
> ```
> 
> Its my first time running Remix command and running Node: v16.11.1

we're releasing a fix for windows today :smile:

**Comment by TheGreyRaven** [comment]
> we're releasing a fix for windows today 😄

Thanks, hopefully dpyzo0o will have their issue solved too!

**Comment by mcansh** [comment]
> @dpyzo0o Not sure how you could debug it tbh.
> 
> Have you tried using the latest version of Node v14 & v16?

same, deno-cache@0.2.12 does exist, but i am wondering where we use the esbuild plugin that uses it..

**Comment by dpyzo0o** [comment]
> @dpyzo0o Not sure how you could debug it tbh.
> 
> Have you tried using the latest version of Node v14 & v16?

Just tried with node 16.14.2, same error

**Comment by dpyzo0o** [comment]
@mcansh I'm on Mac actually, I tried with create-remix@1.3.2-pre.0, still the same error -_-

**Comment by mcansh** [comment]
> @mcansh I'm on Mac actually, I tried with create-remix@1.3.2-pre.0, still the same error -\_-

I know, just replying to the windows issue above, I'm not sure how to debug this quite honestly, sounds like a problem with npm's cache

**Comment by MichaelDeBoey** [comment]
> sounds like a problem with your npm cache

Maybe `npm cache clean --force` can solve this problem then.

**Comment by chaance** [comment]
Unable to confirm with `create-remix@1.3.3` released this morning. @dpyzo0o Mind clearing your npm cache again and using the latest release?

**Comment by dpyzo0o** [comment]
Just confirmed the bug was caused by my company's npm registry. Switched to the official registry and it works now. Thanks for everyone here, have a nice weekend!
