### ISSUE TITLE
Errors from root aren't bubbled to root `<ErrorBoundary>`

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#2383]
### What version of Remix are you using?

1.3.1

### Steps to Reproduce

1. Create a new Remix app.
2. Define a component that has a `useFetcher()` that calls an API that throws an error.
3. Import and use that component in `app/root.tsx`.
4. Define an `<ErrorBoundary>` function in `app/routes/index.tsx`.
5. Open the app.
6. Open the browser console and see how the app continuously requests that API.

I've created a repro of this using `create-remix@latest`:
1. Clone it:
```
$ git clone https://github.com/nicholaschiang/fetcher-error.git
```
3. Install deps:
```
$ cd fetcher-error && yarn install
```
5. Start dev server:
```
$ yarn dev
```
7. See error:

![image](https://user-images.githubusercontent.com/20798889/159069852-c910ba88-b6db-46a0-bc58-193ecd40df0b.png)

### Expected Behavior

Errors from components within `<Root>` should bubble up to the `<ErrorBoundary>` defined and exported from `app/root.tsx`.

### Actual Behavior

Errors from components within `app/root.tsx` are shown in the nested `<ErrorBoundary>` defined in `app/routes/index.tsx` which causes an infinite loop (as `<Root>` continues to be rendered) that endlessly calls the erroring API.

**Comment by nicholaschiang** [comment]
Temporary fix is to just move that component outside of `app/root.tsx` and into `app/routes/index.tsx`.

**Comment by machour** [comment]
Hi @nicholaschiang, would it be possible to create a failing PR, as described in the issue template? 
This will help the team tremendously!

**Comment by F3n67u** [comment]
I can reproduce this problem on my side. But there is not `<ErrorBoundary>` defined in `root.tsx` @nicholaschiang

**Comment by nicholaschiang** [comment]
@F3n67u even if you do put an `<ErrorBoundary>` there, it won't be called (the nested one will be called).

**Comment by machour** [comment]
@nicholaschiang Tested on 1.11.1, not reproducible anymore 👍🏼
