### ISSUE TITLE
process.env.NODE_ENV can't be overwritten after build

### ISSUE THREAD

**Issue by jaschaio** [remix-run/remix#2399]
### What version of Remix are you using?

1.3.2

### Steps to Reproduce

Create a new remix app:

`npx create-remix@latest`

Choose `Just the basics` and `express` (shouldn't make a difference)

Run `npm install`.

Edit the `package.json` start script:

```diff
- "start": "cross-env NODE_ENV=production node ./build/index.js"
+ "start": "cross-env NODE_ENV=development node ./build/index.js"
```

Add a simple `console.log` to the `server.js` script:

```diff
+ console.log( 'rocess.env.NODE_ENV', process.env.NODE_ENV );
```

Run `npm run build` and `npm run start`

It will log:

```
process.env.NODE_ENV production
```

### Expected Behavior

I should be able to overwrite the NODE_ENV at runtime after build

### Actual Behavior

`remix build` always sets `process.env.NODE_ENV` to `production`

**Comment by machour** [comment]
Afaik, the only two accepted values are `development` and `production`

**Comment by jaschaio** [comment]
It happens as well with:

```
- "start": "cross-env NODE_ENV=production node ./build/index.js"
+ "start": "cross-env NODE_ENV=development node ./build/index.js"
```

**Comment by machour** [comment]
I'm not sure why you're trying to change the env var **after** the build.
What's your use case?

**Comment by jaschaio** [comment]
I run a remix app in a Docker container. I build it as part of the Dockerfile. I want to run the same container within both staging and production environments. But I obviously want some stuff (sending out emails, etc.) not to happen within staging envrionments. I differentiate between environments with the environment variable `NODE_ENV` which should be able to be overwritten at runtime.

**Comment by kiliman** [comment]
You will need to create two separate builds. `esbuild` replaces *all* references to `process.env.NODE_ENV` with the actual value at build time.

You can verify this but looking at the *build/index.js* and searching for your console.log statement.
```ts
// routes/index.tsx
  console.log("NODE_ENV", process.env.NODE_ENV);

// build/index.js
  console.log("NODE_ENV", "development");
```
If you need some type of run-time check, then you should use a different variable name.

**Comment by jaschaio** [comment]
Ok I see that this seems to be done by esbuild. Not sure why it works in my other applications that are using esbuild as well, but using a different variable name is a reasonable workaround.
