### ISSUE TITLE
Clarify Typescript integration

### ISSUE THREAD

**Issue by nicolasrenon** [remix-run/remix#24]
Hi there!

It was quite a surprise to open `my-remix-app` and find out that some files are using the`.tsx` extension and some others are not. I haven't found anything in the documentation related to Typescript.

- Is Typescript mandatory to use remix-run?
- What files should use the .tsx extension?
- I'm not familiar with TS, but I didn't notice anything in these files that justify the extension, am I wrong?

**Comment by Anishpras** [comment]
@mjackson Can I work on this issue?

**Comment by mjackson** [comment]
@Anishpras You should ask @kentcdodds. He's the one heading up our documentation efforts. I'm not sure if he'd prefer a separate page about this or what.

**Comment by kentcdodds** [comment]
I think we should have a page under "Guides" called "TypeScript" that describes basically what @mjackson said. @Anishpras, you can go ahead and get things started if you don't mind me making edits to whatever you write :)

**Comment by Anishpras** [comment]
@kentcdodds Okay! Will start ASAP.

**Comment by Anishpras** [comment]
@kentcdodds I have opened a PR for the issue discussed above [PR 1378](https://github.com/remix-run/remix/pull/1378).

**Comment by kentcdodds** [comment]
Thanks everyone! https://remix.run/docs/en/v1/guides/typescript
