### ISSUE TITLE
useLoaderData() hook doesn't run when route is prefetched

### ISSUE THREAD

**Issue by andrecasal** [remix-run/remix#2477]
### What version of Remix are you using?

1.3.2

### Steps to Reproduce

1. Create a default index.ts route and a posts route (as per the [official tutorial](https://remix.run/docs/en/v1/tutorials/blog#loading-data))

2. Load the website from the root. The /posts route will be prefetched. Navigate to the /posts route with a <Link> or a <NavLink>
```
const Header = () => {
	return <header>
		<Link to="/"><Logo /></Link>
		<Link to="/posts">Posts</Link>
	</header >
}
```

3. Notice the posts route doesn't have posts to load
```
// /app/routes/posts/Posts.tsx
export const loader: LoaderFunction = async () => {
	return json(await getPosts())
}

const Posts = () => {
	const posts = useLoaderData<Post[]>()
	return <main>
		<h1>Posts</h1>
		<ul>
			{posts.map(post => <li key={post.slug}>
				<Link to={post.slug}>{post.title}</Link>
			</li>)}
		</ul>
	</main >
}
``` 
```
// localhost:3000/posts
Application Error

Posts@http://localhost:3000/build/_shared/chunk-JJQAWQ3C.js:17:180
renderWithHooks@http://localhost:3000/build/entry.client-GSXBJFCI.js:11070:35
mountIndeterminateComponent@http://localhost:3000/build/entry.client-GSXBJFCI.js:13190:36
callCallback2@http://localhost:3000/build/entry.client-GSXBJFCI.js:3680:27
dispatchEvent@[native code]
invokeGuardedCallbackDev@http://localhost:3000/build/entry.client-GSXBJFCI.js:3705:37
invokeGuardedCallback@http://localhost:3000/build/entry.client-GSXBJFCI.js:3739:44
beginWork$1@http://localhost:3000/build/entry.client-GSXBJFCI.js:17086:36
performUnitOfWork@http://localhost:3000/build/entry.client-GSXBJFCI.js:16317:31
workLoopSync@http://localhost:3000/build/entry.client-GSXBJFCI.js:16268:30
renderRootSync@http://localhost:3000/build/entry.client-GSXBJFCI.js:16243:27
performSyncWorkOnRoot@http://localhost:3000/build/entry.client-GSXBJFCI.js:15983:40
performSyncWorkOnRoot@[native code]
@http://localhost:3000/build/entry.client-GSXBJFCI.js:8517:42
unstable_runWithPriority@http://localhost:3000/build/entry.client-GSXBJFCI.js:351:32
flushSyncCallbackQueueImpl@http://localhost:3000/build/entry.client-GSXBJFCI.js:8513:34
flushSyncCallbackQueue@http://localhost:3000/build/entry.client-GSXBJFCI.js:8503:37
scheduleUpdateOnFiber@http://localhost:3000/build/entry.client-GSXBJFCI.js:15757:39
dispatchAction@http://localhost:3000/build/entry.client-GSXBJFCI.js:11868:34
dispatchAction@[native code]
onChange@http://localhost:3000/build/_shared/chunk-6255QIDR.js:2455:23
update@http://localhost:3000/build/_shared/chunk-6255QIDR.js:1439:18
@http://localhost:3000/build/_shared/chunk-6255QIDR.js:2044:11
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
``` 

4. If you access the /posts route directly, the useLoaderData() calls the loader and the posts are loaded
<img width="248" alt="Screen Shot 2022-03-24 at 10 50 06" src="https://user-images.githubusercontent.com/22457463/159900592-e6c6311a-4dd8-4699-8544-0926518c09bb.png">

### Expected Behavior

I would expect that the /posts route, when prefetched, would include the data from the useLoaderData() hook.

### Actual Behavior

I would expect that the /posts route, when prefetched, would include the data from the useLoaderData() hook.

**Comment by andrecasal** [comment]
I was using an `index.ts` file to export my routes:
```
// /app/routes/posts/index.ts
export * from './Posts'
export { default } from './Posts'
```

And defining the actual route on its respective `Posts.tsx` file.


I then realized the way nested routes work in Remix is by having the main route in `/app/routes/posts/index.tsx` and any nested routes in `/app/routes/posts/nestedRoute.tsx`. So me having an `/app/routes/posts/index.tsx` that just exports what's in `/app/routes/posts/Posts.tsx` doesn't work because Remix can't call the loader function on `/app/routes/posts/index.tsx` (because, even thought index.ts exports everything, the loader is not there).

I wonder if we can find a way to avoid having a bunch of 'index.tsx' files on the editor for each route:
<img width="718" alt="Screen Shot 2022-03-24 at 11 01 05" src="https://user-images.githubusercontent.com/22457463/159902732-4215f744-0340-44ed-a13d-7cfc48c8d107.png">

I would rather see each route like this:
<img width="556" alt="Screen Shot 2022-03-24 at 11 01 32" src="https://user-images.githubusercontent.com/22457463/159902768-211a8917-b4de-46a1-b812-d5aa1dbf8e32.png">

**Comment by machour** [comment]
@andrecasal I would advise reading the [routing section](https://remix.run/docs/en/v1/guides/routing) of the documentation to have a better grasp at how Remix routing work.

Having a `Posts.tsx` inside the routes folder doesn't really make sense (at least to me), as you're supposed to have only "urls" in `routes/`

But importing from a file, and exporting in your route should definitely work if you do something like :

```jsx
import Render, {loader} from "Posts.ts";

export {
  loader
};

export default Render;
```

Don't hesitate to open a discussion or hop on the discord server to get some more guidance!

**Comment by andrecasal** [comment]
> But importing from a file, and exporting in your route should definitely work if you do something like :
> 
> ```js
> import Render, {loader} from "Posts.ts";
> 
> export {
>   loader
> };
> 
> export default Render;
> ```

Hum interesting, I'm definitely going to try that out, thank you @machour  👍
