### ISSUE TITLE
TypeScript types for @remix-run/cloudflare are missing; breaking all CF adapters since v1.3.3

### ISSUE THREAD

**Issue by 3x071c** [remix-run/remix#2478]
### What version of Remix are you using?

1.3.3 (latest)

### Steps to Reproduce

1. Create a new remix `cloudflare-pages` TypeScript app using `npx create-remix@latest`
2. Import `{createCloudflareKVSessionStorage} from ‘remix’` somewhere
3. Watch TypeScript claim the import does not exist
4. The transpiled JavaScript app works as expected 

### Expected Behavior

Correct typings

### Actual Behavior

TypeScript complains: `module ‘remix’ has no exported member ‘createCloudflareKVSessionStorage‘` -> no types

**Comment by 3x071c** [comment]
The exports from `@remix-run/cloudflare-pages` are missing in `remix`’s `index.d.ts`:
![DC3FD78A-0144-45B9-BCFA-49A13A991D61](https://user-images.githubusercontent.com/87198856/159911455-58265854-e349-4343-8145-9696831414bf.jpeg)
Running `remix setup cloudflare`(-pages) manually doesn’t help.

**Comment by 3x071c** [comment]
@machour This issue applies to Cloudflare in general (the Cloudflare Workers adapter is affected too).

**Comment by 3x071c** [comment]
#2359 (Commit [8cd7f65664d630b67975f9e574eab8521e5fd34f](https://github.com/remix-run/remix/blob/8cd7f65664d630b67975f9e574eab8521e5fd34f/packages/remix-dev/cli/setup.ts)) deprecated and unified the previously separate `cloudflare-pages` and `cloudflare-workers` options into a single `cloudflare` platform. This means that both deployment targets now use the same `magicExports` from `@remix-run/cloudflare` ([source](https://github.com/remix-run/remix/blob/735fc04ef9fb2cf6f070cbdd742c37540e082ac4/packages/remix-dev/cli/setup.ts#L32)). Unlike the other two, `@remix-run/cloudflare`'s build doesn't contain any typescript declaration files, which causes the whole bug.

**Comment by 3x071c** [comment]
The rollup configuration, which looks like it's responsible for the production build, diverges quite a bit for `@remix-run/cloudflare` in contrast to `@remix-run/cloudflare-workers`/`@remix-run/cloudflare-pages` ([reference](https://github.com/remix-run/remix/blob/735fc04ef9fb2cf6f070cbdd742c37540e082ac4/rollup.config.js#L385-L487)). @pcattori You have an idea of the culprit?

**Comment by 3x071c** [comment]
Comparing `remixCloudflareWorkers` ([4986844728e2ad98ebb6a679210b79a04e6e5648](https://github.com/remix-run/remix/blob/4986844728e2ad98ebb6a679210b79a04e6e5648/rollup.config.js#L386)) and the new `remixCloudflare` ([8cd7f65664d630b67975f9e574eab8521e5fd34f](https://github.com/remix-run/remix/blob/735fc04ef9fb2cf6f070cbdd742c37540e082ac4/rollup.config.js#L386)):

1. `index.ts` -> `esm` to `cjs` export

That can't be it...

**Comment by FritzTheDev** [comment]
Think I'm running into the same behavior on the "blues stack" - which targets fly. Every other module plays nicely with TS but the remix module only has one exported member (according to .d.ts): "RemixNotSetupError".

<img width="423" alt="Screen Shot 2022-03-24 at 8 59 30 AM" src="https://user-images.githubusercontent.com/19580939/159932652-af773dd5-7bc2-4fb9-8d2d-b57ff0a9536e.png">

**Comment by FritzTheDev** [comment]
Bumped remix package version down a patch to ^1.3.2 and  rm -rf'd n_m's then reinstalled.

Didn't think to do it one step at a time to figure out whether it was the reinstall or the rollback that fixed it but it's working now so I'm not gonna mess with it lol.

**Comment by 3x071c** [comment]
> Think I'm running into the same behavior on the "blues stack" - which targets fly. Every other module plays nicely with TS but the remix module only has one exported member (according to .d.ts): "RemixNotSetupError".

 @FritzTheDev Most likely the reinstall. Looks like you/your package manager didn't run the postinstall hook (`remix setup node`), which generates the types into `node_modules/remix/index.d.ts`. The `RemixNotSetupError` (default file content) refers to that.

**Comment by pcattori** [comment]
Looks like I forgot to add the new `cloudflare` package to the list of packages that we emit type declarations for 😬 .

Should be fixed by #2483 . I tested `yarn build` locally before and after the fix to confirm that it now does generate TS types for `@remix-run/cloudflare`.

If issue persists in the next release, feel free to reopen.
