### ISSUE TITLE
Idea: Custom templates

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#248]
I had a random idea of a feature for the `create-remix` package, right now to start a new Remix app I can use the `npm init remix` command, choose between a few options and I'm done.

Another options is to copy a public repository like [mcansh/remix-tailwind-starter](https://github.com/mcansh/remix-tailwind-starter).

It would be useful to have a way to tell the `create-remix` package to init the app with another repository as template.

```bash
npm init remix --template user/repo
```

**Comment by merelinguist** [comment]
@sergiodxa Guess you can close this now! 😄

**Comment by sergiodxa** [comment]
🥳
