### ISSUE TITLE
Action in root.tsx not executed when pathless index route present

### ISSUE THREAD

**Issue by styxlab** [remix-run/remix#2498]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

# Install
git clone https://github.com/styxlab/remix-issue-root-action
cd remix-issue-root-action
yarn
yarn dev

# Reproduce
Enter a text into the text field and press enter => Error: 405 Method Not Allowed
```
Route "routes/__layout" does not have an action, but you are trying to submit to it. To fix this, please add an `action` function to the route
```

### Expected Behavior

No error. The action in `root.tsx` should be executed.

### Actual Behavior

Error: 405 Method Not Allowed

**Comment by styxlab** [comment]
Note:
 1. the action in `root.tsx` is triggered, when you remove the pathless layout route structure
 2. the console error message is misleading because actions in pathless routes are not allowed.

**Comment by kiliman** [comment]
Yeah, when Remix posts to a route, it looks for an action on that route. If you're on an index route, it will look at the parent layout for an action unless you include `?index` in the form action. Looks like Remix isn't skipping pathless layouts as it looks for the "parent" layout route and just stops at the first parent.

**Comment by styxlab** [comment]
Thanks for explaining what's going wrong here. From a DX point of view I would expect that the action is always triggered in the same location where I define the <Form> unless it is changed in the form action attribute.

**Comment by styxlab** [comment]
Quote from the docs:

> Also note that forms without an action prop (<Form method="post">) will automatically post to the same route within which they are rendered ...

Thus I hope this issue will be fixed.

**Comment by numaga94** [comment]
please fix this +1

**Comment by maranomynet** [comment]
> when Remix posts to a route, it looks for an action on that route. If you're on an index route, it will look at the parent layout for an action unless you include `?index` in the form action.

This breaks the principle of least surprise.

IMO, matched routes should have their `action` method invoked regardless of whether the filename is `index.tsx` or something else.

**Comment by brophdawg11** [comment]
I think this is the same bug as [this issue](https://github.com/remix-run/react-router/issues/9284) over in react router.  Pathless routes should be ignored when matching for actions, so `/parent?index` should hit the index route, and `/parent` should use the `parent.jsx` match, not a potential `parent/__pathless.jsx` file.  Otherwise there's no way of differentiating between the parent route and it's child pathless routes.

**Comment by machour** [comment]
Should be fixed now that Remix sits on top of RR.
