### ISSUE TITLE
Fetcher not returning the data from `loader`

### ISSUE THREAD

**Issue by Arcath** [remix-run/remix#2511]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

I'm using a fetcher to build an infinate scroller and after upgrading from 1.3.2 to 1.3.3 it's started returning the wrong data.

My loader:

```ts
export const loader: LoaderFunction = async ({request}) => {
  const url = new URL(request.url)
  const param = url.searchParams.get('skip')

  const skip = param === null ? 0 : parseInt(param)

  const articles = await getArticles({count: 9, skip})
  const tags = await getTags()
  const {title, subTitle} = getSiteData()

  const total = await getArticlesCount()

  return json({articles, title, subTitle, tags, total})
}
```

My Component:

```tsx
const ArticlesPage = () => {
  const {
    articles: loaderArticles,
    tags,
    total
  } = useLoaderData<{
    articles: Awaited<ReturnType<typeof getArticles>>
    tags: Awaited<ReturnType<typeof getTags>>
    title: string
    subTitle: string
    total: number
  }>()

  const fetcher = useFetcher()

  const [articles, setArticles] = useState(loaderArticles)

  useEffect(() => {
    if (fetcher.data && fetcher.data.articles) {
      setArticles([...articles, ...fetcher.data.articles])
    }
  }, [fetcher.data])

  console.dir([articles.length, total])

  return (
    <div className="grid grid-cols-layout">
      <div className="col-start-2">
        <h1 className="text-3xl">Articles</h1>
      </div>
      <div className="col-start-2">
        <div className="grid grid-cols-6 gap-2 my-4">
          {tags.map(tag => {
            return (
              <ButtonLink key={tag.slug} to={`/articles/${tag.slug}`}>
                {tag.name} ({tag.articles.length})
              </ButtonLink>
            )
          })}
        </div>
        <div className="grid grid-cols-3 col-start-2 col-span-3 gap-4">
          {articles.map(article => {
            return <ArticleBlock article={article} key={article.slug} />
          })}
          {articles.length < total ? (
            <div className="col-span-3">
              <Button
                onClick={() => {
                  fetcher.load(`/articles?skip=${articles.length}`)
                }}
                className="w-full"
              >
                More...
              </Button>
            </div>
          ) : (
            ''
          )}
        </div>
      </div>
    </div>
  )
}
```

I can reproduce this by making a request to `http://localhost:3000/articles?_data=root` which is returning the incorect data.

### Expected Behavior

I'd expect `fetcher.data` to be the data returned by the loader so I can append the new articles to the page.

### Actual Behavior

`fetcher.data` only contains the keys `title` and `subTitle` and none of the others.

I don't have any loaders that only have those keys returned so I'm not sure where it is going to get that data.

**Comment by kiliman** [comment]
I created a codesandbox that appears to be working. It's using Remix v1.3.3

https://codesandbox.io/s/remix-fetcher-more-s2jf35?file=/app/routes/articles.tsx

**Comment by Arcath** [comment]
Thanks, looking at that example it seems like my code isn;t making requests to the right place.

When you hit the fetch link in your codesandbox remix logs:

```
GET /articles?skip=9&_data=routes%2Farticles 200 - - 4.930 ms
```

where as my site logs:

```
GET /articles?skip=9&_data=root 200 - - 10.705 ms
```

If I tweak the request to end `_data=routes%2Farticles%2Findex` the JSON response is correct.

I can confirm now that it is running the loader for `app/root.tsx` and not `app/routes/articles/index.tsx` like I'd expect it to (and your example does).

**Comment by kiliman** [comment]
If you need to get the index route, then append `?index` to your route. Otherwise Remix will fetch from the parent loader (which in your case is *root*).

**Comment by JonathanSMachado** [comment]
I also had the same problem. My application has infinite scroll and was working normally. After the update, it stopped working. I solved it by following @kiliman's tip, adding the ?index in fetcher.load.

**Comment by Arcath** [comment]
Thats fixed it thanks :)

**Comment by dan-cooke** [comment]
This still seems like a bug to me, surely the index file should be able to hit without `?index`

**Comment by kiliman** [comment]
@dan-cooke 

The reason you need the `?index`, is that the path `/` is ambiguous. It can refer to either *root.tsx* or *index.tsx*. For regular navigation, it doesn't matter so much as Remix will call the loaders for both routes. However on mutation (POST) or `fetcher.load`, Remix needs a single route to call. By default, Remix will always choose the parent route. So if you want the index route, you need to be explicit about it.

You may be wondering why the parent route. The reason is so it is deterministic.

Let's say you have a route `products.tsx`. You POST to `/products`, fetcher.load(`/products`), etc. Everything works great.

Then you decide you want to create nested layouts, so you create a `products` folder and add the `index.tsx` route. Now your `/products` route matches both `products.tsx` and `products/index.tsx`.

If Remix started calling the `index` route when you POST to `/products`, your app would break. You would be unhappy 😩 and Remix is all about making you happy 😁

Hope this makes sense.

**Comment by dan-cooke** [comment]
@kiliman that makes sense, obvious when you put it like that. Thanks 🙌
