### ISSUE TITLE
Non ascii characters in routes do not work or break remix

### ISSUE THREAD

**Issue by ssijak** [remix-run/remix#2523]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

Version one :
-Create any route with a non-ascii character in the name, for example `plaćanje.tsx`. 
-Visit the route in the browser

Version two:
-Url encode the same route that you want
-Create the file with the encoded name, for example `pla%C4%87anje.tsx`. 
-Visit the route in the browser

### Expected Behavior

Route works as any other route.

### Actual Behavior

In version one 404 is thrown.
In version two, the page loads but remix bugs out and javscript code stop working.

<img width="661" alt="CleanShot 2022-03-28 at 14 19 39@2x" src="https://user-images.githubusercontent.com/530127/160396948-f193d9db-eb81-4cef-b87b-8b6935befe47.png">

**Comment by machour** [comment]
Already reproduced in #2494 
Closing this issue in favor of that.
