### ISSUE TITLE
Sometimes page returns 404 or bad JS is generated after rebuild

### ISSUE THREAD

**Issue by HurricanKai** [remix-run/remix#2535]
### What version of Remix are you using?

1.3.3.

### Steps to Reproduce

I'm not sure - this only happens on my very slow laptop and I can't reliably reproduce it

### Expected Behavior

Rebuild works normally and the page is shown on reload

### Actual Behavior

![image](https://user-images.githubusercontent.com/22711887/160543600-96479748-339c-407e-a511-7bc3c60aa491.png)

I know this isn't a great bug report but I'm honestly not sure how to troubleshoot this / gather info

**Comment by lili21** [comment]
Maybe you can provide a reproduce repo?

**Comment by jacob-ebey** [comment]
The only way around this that I can think of is implementing a file lock and making sure that wrangler respects that lock. Would be a bit of coordination needed there though. How slow of a laptop are we talking here?

**Comment by Jaikant** [comment]
@HurricanKai This is not a remix issue.
I found this possibly related issue in the esbuild repo https://github.com/evanw/esbuild/issues/629
