### ISSUE TITLE
createCookieSessionStorage server-side not including cookie in redirect header

### ISSUE THREAD

**Issue by sfdc-ben** [remix-run/remix#2551]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

Similar implementation to the Jokes App: 

```js
const storage = createCookieSessionStorage({
    cookie: {
        name: "C360_Session",
        secure: process.env.NODE_ENV === "production",
        secrets: [sessionSecret],
        sameSite: "none", --> ( or 'lax' or 'strict')
        path: "/",
        maxAge: 60 * 60 * 24 * 30,
        httpOnly: true
    }
})

const createUserSession = async (userId, redirectto) => {
    const session = await storage.getSession()
    session.set("userId", userId)
    const cookie = await storage.commitSession(session)
    return redirect(redirectto, {
        headers: {
            "Set-Cookie": cookie
        }
    })
}
```

Fire request from mobile browser and the Set-Cookie header isn't applied and sent.

### Expected Behavior

Works fine on desktop browsers - redirects to the authenticated pages that use the following loader:

```js
const getUserId = async (request) =>  {
    const session = await getUserSession(request)
    console.log(session.get('userId'))
    if (!session.has('userId')) {
        throw redirect(`/auth`)
    }
}
```

### Actual Behavior

Server logs produce ... app[web.1]: GET /?_data=routes%2Findex 204 - - 1.845 ms
On Desktop produces a successful 200 status.

**Comment by sfdc-ben** [comment]
Repo to reproduce - deployed on heroku (created from Remix App Server)

**Comment by lili21** [comment]
![image](https://user-images.githubusercontent.com/4456380/161053225-3c043d2a-38d0-4f01-ba51-84e4edf1846f.png)
When I visit http://localhost:3000, it redirect to http://localhost:3000/auth

**Comment by lili21** [comment]
it due to the `sameSite: "none"` part. 

![image](https://user-images.githubusercontent.com/4456380/161056144-dfabe614-81fa-4bbd-8cb9-15f323e8fe74.png)

it was blocked by browser.

**Comment by sfdc-ben** [comment]
I needed to hardcode the secure value to true, and force to https and it works now. Thank you for the guidance!
