### ISSUE TITLE
Warning: ReactDOM.hydrate is no longer supported in React 18

### ISSUE THREAD

**Issue by nath1as** [remix-run/remix#2564]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

basic app
yarn run dev

### Expected Behavior

Remix uses hydrateRoot and behaves as if it's running React 18.

### Actual Behavior

Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by MichaelDeBoey** [comment]
Re-opening because it would be good to keep track of this as long as we don't support React v18

**Comment by nareshbhatia** [comment]
I tried updating `app/entry.client.tsx` like this, but it is not working:

```
import { RemixBrowser } from '@remix-run/react';
import { hydrateRoot } from 'react-dom/client';
hydrateRoot(document, <RemixBrowser />);
```

I get this error in the console:

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

The [suggestion in React docs](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) is to change hydrate as follows:

```
import { hydrateRoot } from 'react-dom/client';
const container = document.getElementById('app');
const root = hydrateRoot(container, <App tab="home" />);
```

This is slightly different compared to my remix code where I am passing the entire document to `hydrateRoot` - that's how the original Remix code was structured.

**Comment by chaance** [comment]
I'm going to close this again so we can consolidate problems with React 18 to a single issue, as this is very much a WIP already. Let's keep discussion of those issues in https://github.com/remix-run/remix/issues/577

**Comment by TakenHiduk** [comment]
How about this? 

```tsx
// entry.client.tsx
import { RemixBrowser } from "@remix-run/react";
import { hydrateRoot } from "react-dom/client";

hydrateRoot(document, <RemixBrowser />);
```

```json
// package.json
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "start": "remix-serve build"
  },
  "dependencies": {
    "@remix-run/node": "^1.5.1",
    "@remix-run/react": "^1.5.1",
    "@remix-run/serve": "^1.5.1",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.5.1",
    "@remix-run/eslint-config": "^1.5.1",
    "@types/react": "^18.0.12",
    "@types/react-dom": "^18.0.5",
    "eslint": "^8.15.0",
    "typescript": "^4.6.4"
  },
  "engines": {
    "node": ">=14"
  }
}
```
