### ISSUE TITLE
React 18 : Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by rphlmr** [remix-run/remix#2570]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

Update https://github.com/remix-run/indie-stack/tree/main

- react: 18.0.0
- react-dom: 18.0.0

Update entry.client.tsx : 

```jsx
import { hydrateRoot } from "react-dom/client";
import { RemixBrowser } from "remix";

hydrateRoot(document, <RemixBrowser />);
```

Run dev with  NODE_ENV=production

### Expected Behavior

No error

### Actual Behavior

White screen with errors : 

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (:3000/build/entry.client-K3EESZRH.js:10325:17)
    at tryToClaimNextHydratableInstance (:3000/build/entry.client-K3EESZRH.js:10335:15)
    at updateHostComponent$1 (:3000/build/entry.client-K3EESZRH.js:14601:13)
    at beginWork (:3000/build/entry.client-K3EESZRH.js:15679:22)
    at HTMLUnknownElement.callCallback2 (:3000/build/entry.client-K3EESZRH.js:3453:22)
    at Object.invokeGuardedCallbackDev (:3000/build/entry.client-K3EESZRH.js:3478:24)
    at invokeGuardedCallback (:3000/build/entry.client-K3EESZRH.js:3512:39)
    at beginWork$1 (:3000/build/entry.client-K3EESZRH.js:18903:15)
    at performUnitOfWork (:3000/build/entry.client-K3EESZRH.js:18367:20)
    at workLoopSync (:3000/build/entry.client-K3EESZRH.js:18307:13)
```

```
Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
```

```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at appendChildToContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:7946:24)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16695:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)
    at insertOrAppendPlacementNodeIntoContainer (http://192.168.1.17:3000/build/entry.client-K3EESZRH.js:16702:15)```

**Comment by rphlmr** [comment]
No error when NODE_ENV=development

**Comment by rphlmr** [comment]
🤷‍♂️ sorry can't reproduce. I close (maybe a caching issue ?)

**Comment by rphlmr** [comment]
@DAlperin  Yes I can ;) 
I reproduce if I `npm run dev` after a cypress run.
But if i clean build folder ans re run dev, no more problems 🤷‍♂️

**Comment by DAlperin** [comment]
@rphlmr I just tried `rm -rf tmp .cache build && npm run dev` and the problem persists. Any ideas?

**Comment by rphlmr** [comment]
@DAlperin  I have a [demo here](https://github.com/rphlmr/supa-fly-stack/tree/chore/react-18) but It works
I think I follow the react migration guide to adapt this.

If it can help, i'm on macos with node v16.14.2

**Comment by DAlperin** [comment]
@rphlmr I published my code to a branch of my repo. If you get the chance, do you think you could look it over or try running it?
https://github.com/DAlperin/dov.dev-remix/tree/react-18-broken

**Comment by rphlmr** [comment]
@DAlperin It works (react-18-broken) on my machine ^^"

**Comment by DAlperin** [comment]
@rphlmr figured it out! `remix-themes` seemed to be playing weirdly with the new hydration in some edge cases. (I think the useTheme hook was returning conflicted values on the client and the server). I'll open up a issue over there to track. Thank you for your help!

**Comment by Schular** [comment]
In my case `Apollo Client Devtools` was causing the app to crash after upgrade to React v18, because it was injecting a script tag on client side.

Who have this problem could try running in incognito mode in order to exclude browser extensions.

**Comment by ostwilkens** [comment]
"Dark Reader" extension also triggers this error. Of course, disabling extensions isn't a solution. I can't ask visitors to disable all extensions to view my site. 
@MichaelDeBoey could you reopen this issue?

**Comment by hrgui** [comment]
Something that I've been wondering about:

```tsx
hydrateRoot(document, <RemixBrowser />);
```

I don't think it's a good idea to hydrate the entire document because for chrome extensions that modify the DOM (e.g. Apollo Client DevTools, LastPass, Dark Reader), they will add / change the DOM significantly by injecting CSS / JS.

**Comment by danestves** [comment]
I have the same problem with `cypress` ended up doing this workaround

```tsx
// Dependencies
import { RemixBrowser } from "@remix-run/react";
import { hydrateRoot } from "react-dom/client";

if (process.env.NODE_ENV === "test") {
  require("react-dom").hydrate(<RemixBrowser />, document);
} else {
  hydrateRoot(document, <RemixBrowser />);
}

```

**Comment by CanRau** [comment]
Happened to me due to [Yoroi](https://addons.mozilla.org/en-US/firefox/addon/yoroi/)
And agree with @ostwilkens expecting user (and developers) to disable browser extensions is not a solution

@hrgui yea, though I love that Remix gives us the full control, maybe hydrating `document.head` & `document.body` instead might help? Well Yoroi is injecting before `<head>` not sure what others do, if they inject into `<head>` oder `<body>` same issue would happen I guess? 🤔

**Comment by hrgui** [comment]
@CanRau if we do hydrate document.body instead, we need to change how entry.server works, otherwise there will be a mismatch - because entry.server renders the entire document.

**Comment by CanRau** [comment]
Yeah I imagined it wouldn't be thaat simple, just a quick thought^^

**Comment by hrgui** [comment]
With a non-remix app, I was able to get it to work after observing what next.js and hydrogen does in regards to streaming:

They both have a div element they are hydrating.

https://github.com/hrgui/nodejs-react-sc-demo/commit/ac872341d5e2c93d80c562a0f4056e2ae757c7da

1. The server renders the entire document with a `<div id="root"></div>` wrapping the react app.
2. The client only hydrates the the `#root` element, and renders `<App />`

---

I tried replicating the same in `remix`, but an issue arises - both `<RemixServer />` and `<RemixBrowser />` return the entire document. `<RemixBrowser />` just needs to render the portion that has to be hydrated.

**Comment by DAlperin** [comment]
@rphlmr I think this issue should be reopened. I deployed my first production remix app and have gotten consistent reports from users who have any extension that mutated the DOM (many many of them) I'm going to revert to react 17 tomorrow, but this issue should be considered 'breaking'.

If you'd prefer, I can open another issue.

**Comment by machour** [comment]
@DAlperin you can comment on this new issue: https://github.com/remix-run/remix/issues/2947
Clearly, asking users to disable their extension can't be the solution.

**Comment by jacob-ebey** [comment]
Cross linking this https://github.com/facebook/react/issues/22833

**Comment by rphlmr** [comment]
> @rphlmr I think this issue should be reopened. I deployed my first production remix app and have gotten consistent reports from users who have any extension that mutated the DOM (many many of them) I'm going to revert to react 17 tomorrow, but this issue should be considered 'breaking'.
> 
> If you'd prefer, I can open another issue.

Sorry I'm unable to do that :/ (no reopen option)

**Comment by edwinvrgs** [comment]
> 

This worked for me!

**Comment by edwinvrgs** [comment]
> I have the same problem with `cypress` ended up doing this workaround
> 
> ```tsx
> // Dependencies
> import { RemixBrowser } from "@remix-run/react";
> import { hydrateRoot } from "react-dom/client";
> 
> if (process.env.NODE_ENV === "test") {
>   require("react-dom").hydrate(<RemixBrowser />, document);
> } else {
>   hydrateRoot(document, <RemixBrowser />);
> }
> ```

This worked for me!

**Comment by alireza-bonab** [comment]
Any update here?

**Comment by machour** [comment]
@alireza-bonab This issue is closed, #2947

**Comment by tanduong** [comment]
This issue still happens with react 18.2.0 as I init the project with the indie stack.

**Comment by dan-cooke** [comment]
This is happening but I don't get an error at all, very frustrating and hard to debug

**Comment by dan-cooke** [comment]
I just went back to using `hydrate` from `react-dom` instead of the new `hydrateRoot`.

Awaiting a fix in the meantime

**Comment by jgentes** [comment]
Taking the lead from @dan-cooke this seems to work nicely (using @emotion and not disabling browser plugins):

```
import { RemixBrowser } from '@remix-run/react'
import { hydrate } from 'react-dom'

hydrate(<RemixBrowser />, document)
```

**Comment by simmondsty** [comment]
This issue remains.

`import { hydrate } from 'react-dom'`

Is working for now but not ideal since it only allows you to make use of react v17 features.

**Comment by rphlmr** [comment]
I have a Remix stack following [indie stack](https://github.com/remix-run/indie-stack) and my cypress [runs fine](https://github.com/rphlmr/supa-fly-stack/actions/runs/3051085971/jobs/4918925858) (when it's not timed out 🤭) on GitHub action.

I just have to add this, [somewhere](https://github.com/rphlmr/supa-fly-stack/blob/main/cypress/support/e2e.ts) in `cypress/support` : 

```ts
Cypress.on("uncaught:exception", (err) => {
  // Cypress and React Hydrating the document don't get along
  // for some unknown reason. Hopefully we figure out why eventually
  // so we can remove this.
  if (
    /hydrat/i.test(err.message) ||
    /Minified React error #418/.test(err.message) ||
    /Minified React error #423/.test(err.message)
  ) {
    return false;
  }
});
```

**Comment by machour** [comment]
@diboune As you can see, this issue is closed... please open a new issue if you're facing a problem.
