### ISSUE TITLE
Support for .env files

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#258]
Right now to use a `.env` file I need to install the `dotenv` package and import it and run it inside the `entry.server` file, which is a simple thing to do but it would be nicer to have it already built-in by Remix (only server-side of course).

So if a project has a `.env` file it can use it automatically.

This should probably be added to the adapters, if using Vercel it already loads the .env (because `vercel dev` does it), for Express it could be added here https://github.com/remix-run/remix/blob/master/packages/remix-express/server.ts or in the Remix Serve package instead https://github.com/remix-run/remix/blob/master/packages/remix-serve/index.ts (which may be a better place).

---

Some extra step that may or may not be useful here could be to support `.env`, `.env.development`, `.env.production` and `.env.local` with this behavior:

- First load from `.env`, these are env shared everywhere
- Then load from `.env.development` or `.env.production` based on the NODE_ENV value (maybe also `.env.test`), these are env specific (as the `.env` should be)
- Then load from `.env.local` and these let you overwrite the previous one, useful to trying things

Each one should overwrite the previous one.

**Comment by brophdawg11** [comment]
Added in #2063 👍
