### ISSUE TITLE
Clarify that netlify needs to be installed globally

### ISSUE THREAD

**Issue by penx** [remix-run/remix#2580]
### What version of Remix are you using?

^1.3.4

### Steps to Reproduce

After choosing netlify as the deploy target, I get an error running `npm run dev`.

Is this because a netlify CLI needs to be globally installed? I wasn't expecting the build target to affect dev mode, but if that's the case, perhaps it could be made clearer during `npx create-remix` or the error message could be clearer?

```
npm --version
8.1.2
node --version
v16.13.2
```

```sh
npx create-remix
Need to install the following packages:
  create-remix
Ok to proceed? (y) 
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
? Where would you like to create your app? test-remix-2
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Netlify
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

> postinstall
> remix setup node

Successfully setup Remix for node.

added 784 packages, and audited 785 packages in 55s

195 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
💿 That's it! `cd` into "test-remix-2" and check the README for development and deploy instructions!
➜  cd test-remix-2
➜  npm run dev

> dev
> cross-env NODE_ENV=development netlify dev

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn netlify ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn netlify',
  path: 'netlify',
  spawnargs: [ 'dev' ]
}
```

### Expected Behavior

After running `npx create-remix` with a Netlify build target, I should be able to run `npm run dev` and it should either work or show an error message to help me recover.

### Actual Behavior

After running `npx create-remix` with a Netlify build target, running `npm run dev` shows an error message with no recommended steps to recover.

**Comment by jacob-ebey** [comment]
If you run `npm run build` then `npm run dev` does it work? `ENOENT` usually means something is trying to read / require a file that does not yet exist on disk.

If the above works, then we should update the template to first do a build before starting the netlify server.

**Comment by penx** [comment]
No that doesn't help:

```sh
➜  test-remix-3 npm run build

> build
> remix build

Building Remix app in production mode...
Built in 351ms
➜  test-remix-3 npm run dev  

> dev
> cross-env NODE_ENV=development netlify dev

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn netlify ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn netlify',
  path: 'netlify',
  spawnargs: [ 'dev' ]
}
```

**Comment by machour** [comment]
@penx `netlify` needs indeed to be installed globally, this is mentioned in the Netlify template's [README](https://github.com/remix-run/remix/tree/main/templates/netlify#netlify-setup) but not really obvious when configuring a new project.

@jacob-ebey could some additional output be logged depending on the chosen template in `create-remix`?

**Comment by penx** [comment]
Maybe I’m missing something, but if netlify is a _deploy target_, why is the cli needed during development?

**Comment by technoY2K** [comment]
> @penx `netlify` needs indeed to be installed globally, this is mentioned in the Netlify template's [README](https://github.com/remix-run/remix/tree/main/templates/netlify#netlify-setup) but not really obvious when configuring a new project.
> 
> @jacob-ebey could some additional output be logged depending on the chosen template in `create-remix`?

I second that. I think it will be really helpful if the README clearly states that `netlify-cli` needs to be installed globally along with the reason why. The Netlify Setup instructions as it reads now makes it seem as if the cli tool is optional.

**Comment by tcschiller** [comment]
Why not include `netlify-cli` as a local dev dependency by default in the template?

**Comment by MichaelDeBoey** [comment]
The CLI did have the following message though
```sh
💿 That's it! `cd` into "test-remix-2" and check the README for development and deploy instructions!
```
So we're already saying to people that they need to read the README.

The first step of the README literally says, that you need to install the Netlify CLI

````md
## Netlify Setup

1. Install the [Netlify CLI](https://www.netlify.com/products/dev/):

```sh
npm i -g netlify-cli
```
````

I don't think we can do anything about people not reading the instructions provided tbh 🤔

---

> could some additional output be logged depending on the chosen template in `create-remix`?

@machour That's something that should be done in the `remix.init` script from the template then, which is another thing people seem to not run for some reason 😅🙈

**Comment by machour** [comment]
> The CLI did have the following message though
> 
> ```shell
> 💿 That's it! `cd` into "test-remix-2" and check the README for development and deploy instructions!
> ```
> 
> So we're already saying to people that they need to read the README.
> 
> The first step of the README literally says, that you need to install the Netlify CLI (globally)

Closing this issue as README mentions that 🙏🏼
