### ISSUE TITLE
Firefox `network.preload: false` kills navigation

### ISSUE THREAD

**Issue by icatalina** [remix-run/remix#2619]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

In Firefox:

1. Type `about:config` to edit firefox configuration.
2. Disable `network.preload`
3. Navigate to https://remix.run
4. Click one of the CTAs

Nothing happens

It happens both, using remix, and in the remix website.

I'm not entirely sure if this is a remix or a firefox issue though 🤷 

### Expected Behavior

Navigation works correctly

### Actual Behavior

Links do not navigate, pressing "back" doesn't navigate either.

**Comment by Jaikant** [comment]
@icatalina I tried this in the latest release of firefox i.e 99.0, released on April 5, 2022.

The issue you mentioned, is not reproducible on this version of firefox (99).

**Comment by machour** [comment]
@icatalina What version of firefox are you using?

**Comment by icatalina** [comment]
Hi @machour and @Jaikant, 

I was using firefox 98, I'm using firefox 99 and I've tried in firefox 100. The issue is still happening in all 3 of them.

I'm sorry I didn't give much information in my original issue, this is using MacOS Monterrey, and those 3 versions of firefox.


https://user-images.githubusercontent.com/4542735/162609499-fb223773-8e23-43ff-a234-85092d4e555a.mov

As I mentioned in the original ticket, I don't really know if this is an issue with remix or firefox... 🤷

**Comment by FrecksterGIT** [comment]
I can reproduce this on Firefox 99.0.1 (64-Bit) on Windows 11.

**Comment by brophdawg11** [comment]
Another option @jacob-ebey suggested which is still not ideal but potentially better than the above alternative, is to do a quick "feature detection"-esque check and stick an invalid `<link rel="preload" href="some-junk-url-that-should-error">` in the DOM and see if it fires an `onerror` within a few ms and set a boolean of like `preloadSupported=false` that disbales the use of stylesheet preloads for that session.  The downside though is that when preloading is supported, users will get a bogus 404 in their network tab.

Maybe there's a combination of the above and this idea where we let a few preloads timeout, and then do the feature detection check.  That way when preload is working fine there will never be a a bogus 404.  And when preload is disabled, only after 3 timeouts would we start the 404 approach.

**Comment by brophdawg11** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1847811 just in case this ends up being a bug in firefox, but I suspect this might be expected on their end if you go disabling features of your browser.

**Comment by brophdawg11** [comment]
We've added a "fix" for this in #7106 that will be available in Remix v2
