### ISSUE TITLE
`useMatches` response type is incorrect

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#2673]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

I think the return type of `useMatches` is incorrect:
```typescript
export declare function useMatches(): {
    id: string;
    pathname: string;
    params: import("react-router").Params<string>;
    data: RouteData;
    handle: any;
}[];
```
And then `RouteData` is defined as:
```typescript
export interface RouteData {
    [routeId: string]: AppData;
}
```
When in reality `RouteData` could be a `string` or an `array` or anything else in `AppData`:

```typescript
export function useMatches(): Matches {
  const matches = useRemixMatches();
  console.log('Matches:', matches);
  return matches;
}
```

![image](https://user-images.githubusercontent.com/20798889/162083267-ea9f4999-89ea-411a-9bbe-1df7708e9c4b.png)

In that :point_up: scenario, the `data` key in the objects in the array returned by `useMatches()` is a `string` not a `{ [routeId: string]: AppData }` object.

### Expected Behavior

You should declare the `data` field as being of type `AppData` instead of `RouteData`.

### Actual Behavior

It's declared incorrectly: `data` is defined as an object with the `routeId` as keys and their corresponding data as values while in reality it's just the corresponding data value itself.

**Comment by rossipedia** [comment]
I think you're right:
<img width="1192" alt="Screen Shot 2022-04-06 at 4 53 19 PM" src="https://user-images.githubusercontent.com/96213/162085939-b8d3622c-299e-4d58-b883-7ee0342d2733.png">

In this example, the data returned from the loader is a `number`, and indeed is serialized and deserialized as a number, but the typings are defined as: `{ [routeId: string]: AppData }`

**Comment by machour** [comment]
`data` is now correctly typed as `any`

<img width="364" alt="Screenshot 2023-01-22 at 10 16 19 AM" src="https://user-images.githubusercontent.com/304450/213908566-09d83a6b-fcca-4214-b044-1a65749173c7.png">
