### ISSUE TITLE
Massive js chunks generated in one page

### ISSUE THREAD

**Issue by swwind** [remix-run/remix#2675]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

in `app/routes/index.tsx`

```tsx
import { Prism } from "react-syntax-highlighter";
import light from "react-syntax-highlighter/dist/esm/styles/prism/prism";

const code = `fn main() {
  println!("Hello, world!");
}
`;

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <h1>Welcome to Remix</h1>
      <Prism language="rust" style={light}>{code}</Prism>
    </div>
  );
}
```

### Expected Behavior

Remix build can bundle multiple dependencies into one single (or a few) js chunks.

### Actual Behavior

Remix generated almost 300 js chunks, and most of them are only 1~2kb size.

![image](https://user-images.githubusercontent.com/26316494/162127880-8a150b3f-0e66-4560-9292-49127de09b89.png)

**Comment by Jaikant** [comment]
@swwind I tried to reproduce the issue, using your code. The files created in public/build were
```
drwxr-xr-x  755 jai  staff   24160 Apr  8 11:28 _shared
-rw-r--r--    1 jai  staff  124534 Apr  8 11:28 entry.client-E33ZOQLS.js
-rw-r--r--    1 jai  staff   10389 Apr  8 11:28 manifest-F7F35376.js
-rw-r--r--    1 jai  staff     585 Apr  8 11:28 root-4UOYECCD.js
drwxr-xr-x    3 jai  staff      96 Apr  8 11:28 routes

```

The routes directory also had only a single chunk.

**Comment by Jaikant** [comment]
@swwind Your issue could be related to https://github.com/remix-run/remix/issues/2432

**Comment by swwind** [comment]
> @swwind I tried to reproduce the issue, using your code. The files created in public/build were
> 
> ```
> drwxr-xr-x  755 jai  staff   24160 Apr  8 11:28 _shared
> -rw-r--r--    1 jai  staff  124534 Apr  8 11:28 entry.client-E33ZOQLS.js
> -rw-r--r--    1 jai  staff   10389 Apr  8 11:28 manifest-F7F35376.js
> -rw-r--r--    1 jai  staff     585 Apr  8 11:28 root-4UOYECCD.js
> drwxr-xr-x    3 jai  staff      96 Apr  8 11:28 routes
> ```
> 
> The routes directory also had only a single chunk.

Most of them located in `_shared` folder, and was required for page to load.

I created a repo [swwind/remix-build-issue](https://github.com/swwind/remix-build-issue) for this issue, you can clone and try to build it.

**Comment by Jaikant** [comment]
@swwind yes, I could see the bunch of files getting created in `_shared`.
This directory contains the JS [chunks](https://esbuild.github.io/api/#chunk-names) generated by esbuild as per [this](https://github.com/remix-run/remix/blob/46b96f53e8477dd9404d55e75b320775c3a8a7a4/packages/remix-dev/compiler.ts#L380)

This issue could be related to https://github.com/evanw/esbuild/issues/1581

**Comment by machour** [comment]
I don't think this is a bug.

If you want to avoid loading **all** languages definitions for Prism, just to use a single one, you should lighten your build:
   https://github.com/react-syntax-highlighter/react-syntax-highlighter#light-build

Feel free to open a new Proposal if you want to be able to fine-tune default esbuild chunking 🙏🏼
