### ISSUE TITLE
Warning: Expected server HTML to contain a matching <head> in <html>.

### ISSUE THREAD

**Issue by miguderp** [remix-run/remix#2681]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

Run `npx create-remix@latest` and inspect the Developper Tools

### Expected Behavior

Not having this error out of the box

### Actual Behavior

I wanted to start my project using the basic setup for Remix but no matter what I instantly get this error message, even if I pick "Remix App Server". What am I missing?

![image](https://user-images.githubusercontent.com/7307687/162225060-26ff27bf-e7a7-418e-91c5-c437298cb1dc.png)

![image](https://user-images.githubusercontent.com/7307687/162224183-c1e0d012-93a7-4046-a100-d50f131dfabe.png)

**Comment by machour** [comment]
Hi @miguderp, can you try in Incognito Mode? Some browser extension is maybe injecting something in `<head>`

**Comment by designbyadrian** [comment]
We can't expect our users to use Incognito Mode or uninstall their extensions! How do we go about fixing this?
