### ISSUE TITLE
Any use of react-three/drei results in Cannot read properties of undefined (reading 'root') error

### ISSUE THREAD

**Issue by dalelotts** [remix-run/remix#2692]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

1. Clone this repo: https://github.com/dalelotts/r3f
2. Uncomment use of `OrbitControls` in this file https://github.com/dalelotts/r3f/blob/main/app/pano/canvas-wrapper.client.tsx#L10
3. Run `npm run dev`
4. Visit `http://localhost:3000/r3f` - TypeError: Cannot read properties of undefined (reading 'root') is displayed

### Expected Behavior

It should looks something like this project I copied : https://codesandbox.io/s/sky-dome-with-annotations-wbrfs?file=/src/index.js:234-267

Or at least no error.

### Actual Behavior

TypeError: Cannot read properties of undefined (reading 'root') is displayed

I have read this error is the result of importing server side code, I did everything I could think of to isolate this to client side - wrapped in <ClientOnly> and files are named .client.tsx

**Comment by kiliman** [comment]
The underlying error is typically the one just before you get the `TypeError: Cannot read properties of undefined (reading 'root') is displayed`

In your case, I'm seeing this error: `Uncaught SyntaxError: Identifier 'React' has already been declared`

This is from the route bundle. When it's importing @react-three/fiber.
![image](https://user-images.githubusercontent.com/47168/162459780-f021a7ad-812f-437b-bfd3-da3a39fe13a5.png)

What's odd is that I don't see any other instance of React in that file, and the script is loaded as a module, so shouldn't impact anything else.

I've created a codesandbox where I patched the `@react-three/fiber` and `@react-three/drei` packages to rename the `React` import so they don't conflict.

I'm assuming this is an `esbuild` issue.

Anyway, after the patch, it is working. I can move through the panorama with the mouse.

https://codesandbox.io/s/remix-three-drei-r8lkg6?file=/README.md

**Comment by dalelotts** [comment]
I just learned about `patch-package`, that's very cool, thanks. 

I assume you are correct because the code works with `create-react-app`, I'll move this close this bug reopen it in `esbuild`. 

It's also interesting to note that the size of the image is full height without drei but 1/3 height in CRA and also with the patches. 🤷‍♂️

**Comment by dalelotts** [comment]
@kiliman thanks for this!

**Comment by kiliman** [comment]
Yeah, `patch-package` is magic. It lets you get unblocked while waiting for a fix to land.

Anyway, it's definitely odd that the bundle is breaking. That's table stakes for a compiler/bundler. esbuild is converting ESM->CJS for the browser build so it's possible there's something broken there.

**Comment by dalelotts** [comment]
Doh! 🤦‍♂️

**Comment by machour** [comment]
Thank you @kiliman for your help on this one, we struggled without you!
Closing this issue as this isn't Remix fault !

**Comment by agcty** [comment]
I'm having the same issue, any updates on this?

Problem seems to that React is declared multiple times. 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/12101091/170891252-5571c2a8-b2fa-40c5-9b81-bdcc5287e34a.png">

Not sure what the issue exactly is or how to fix it. @dalelotts and @kiliman seem to have done some digging and could be that this is an esbuild issue? https://github.com/evanw/esbuild/issues/2168. Or maybe this? https://github.com/remix-run/remix/issues/2691

Any help is very much appreciated.

remix 1.5.1 + react-three-fiber 8.0.19 with either react 17 or 18 is not usable at the moment

**Comment by machour** [comment]
@agcty the best thing would be to open a Q&A discussion for your problem. Closed issues aren't likely to get much attention.
