### ISSUE TITLE
useFetcher Form submit reloads page instead of throwing an error

### ISSUE THREAD

**Issue by stijnvanderlaan** [remix-run/remix#2697]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

https://codesandbox.io/s/zen-mestorf-hqkc18?file=/app/routes/index.jsx

In the example above there is an error in api.jsx because when you submit it is being called client side (?). 
Because of api.jsx being called client side getData.server.js is not available, which results in an error, but this error is never thrown, instead the page reloads. 

This bug is related to another issue where the route is not found by remix when you name it api.server.js, also you need a default export component.

### Expected Behavior

When you submit the form, I expect an error to be thrown.

### Actual Behavior

The browser reloads, which makes it very hard to debug what's going wrong.

**Comment by wyemun** [comment]
I have encountered this as well. Page reload upon receiving the http status..

**Comment by xingxinglieo** [comment]
i have the same problem... but it didn't reload before two months ago.

**Comment by wyemun** [comment]
I have downgraded this to 1.3.0 to work around this for now.

**Comment by brophdawg11** [comment]
Thanks for the reproduction @stijnvanderlaan!  I think there's a few things going on here that are contributing to this behavior.  

First, the usage of a higher order function (`getData`) for your `action` is problematic from a tree-shaking/pruning perspective.  Check out the docs here explaining why this is an issue: https://remix.run/docs/en/v1/guides/constraints#higher-order-functions.  You should instead declare your `action` as a function calling `getData` internally:

```js
export const action = () => getData();
```

The usage of the higher order function was causing the action not to get tree-shaken, and then the import of a pruned `.server` module from this client bundle was causing the client-side error when trying to load the route bundle.

The second, more minor issue is that the `<Form action="/api">` will default to a `GET` so it wouldn't call your `action`.  Instead, change that to `<Form method="post" action="/api">` to trigger the `action`.

I hope this helps!  I'm going to close this out but please feel free to re-open if you still run into issues.
