### ISSUE TITLE
Using MemoryRouter throws an error

### ISSUE THREAD

**Issue by crisshaker** [remix-run/remix#2707]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

It's rather simple to reproduce this. Just embed MemoryRouter from 'react-router-dom'. This is an example reproducing this issue: [link](https://stackblitz.com/edit/node-v8efyf)

### Expected Behavior

This is expected to work as remix is built on react router.

### Actual Behavior

This throws an error.

**Comment by machour** [comment]
Closing this as this is not how we're expecting you to use Remix.
