### ISSUE TITLE
useFetcher() submit doesn't work with an object of type FormData

### ISSUE THREAD

**Issue by kemicofa** [remix-run/remix#2715]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

1. Create a Form component
2. `onSubmit` get the form element and `const formData = new FormData(form);`
3. Then add anything `formData.set('hello', 'world');`
4. Then `fetcher.submit(formData)`

And you'll notice we never arrive in the action handler. If I pass the form element directly to `submit`, then it works as expected.

### Expected Behavior

Since the submit function's signature accepts a FormData object, I expect it to call my action handler.

### Actual Behavior

Does nothing. No error. No logs. All I see is that the `fetcher.state` goes to `submitting` and then goes back to `idle` without doing anything.

**Comment by silvenon** [comment]
Could one of you (or both of you) reproduce what your saying as a PR as described in "[Think You Found a Bug?](https://remix.run/docs/en/v1/pages/contributing#think-you-found-a-bug)"?

That will help maintainers resolve this issue.

**Comment by Jaikant** [comment]
@silvenon I don't think this is a bug, atleast based on information provided by @kemicofa

**Comment by kemicofa** [comment]
I'll reproduce on a clean project later and share it here.

**Comment by silvenon** [comment]
I meant, with that PR you can prove to maintainers that there is indeed no problem, as you've already done the work of reproducing for them anyway. 🙂

At least that's how I understood [Kent's tweet](https://twitter.com/kentcdodds/status/1512077446828355593?s=21&t=0bx9xg6gzPATM4YS59i_Ag).

**Comment by Jaikant** [comment]
@silvenon understood! I shall probably wait for @kemicofa to provide more information. Just in case there are some boundary cases I didn't cover in my repro.

**Comment by FrecksterGIT** [comment]
The action method is only called for POST requests. In your error report you use `fetcher.submit(formData)` which results in a GET-Request. Changing it to `fetcher.submit(formData, { method: "post" })` should do the trick.
