### ISSUE TITLE
Bug: `npx create-remix@latest` doesn't work

### ISSUE THREAD

**Issue by chaance** [remix-run/remix#2729]
### Discussed in https://github.com/remix-run/remix/discussions/2709

<div type='discussions-op-text'>

<sup>Originally posted by **wingsmastr** April  8, 2022</sup>
When I ran `npx create-remix@latest` with the following options, the project wasn't created. 
It worked fine the other day but not working today (4/8/2022).

The options that I selected:
```
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Fly.io
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
```

Then, I got the following error:
```
⠹ Creating your app…🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in...
```

Another quick question.
Will `npx create-remix@latest` create the application structure using **React 18** soon? 
When?

Thank you.</div>

**Comment by machour** [comment]
Already tracked in #2714
