### ISSUE TITLE
deployment to vercel fails with: "/bin/sh: remix: command not found"

### ISSUE THREAD

**Issue by mechanicMo** [remix-run/remix#2734]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

create fresh remix app
deploy to vercel via github import

### Expected Behavior

app is deployed

### Actual Behavior

build fails with "/bin/sh: remix: command not found"

**Comment by theMosaad** [comment]
seems to work now with the 1.6.5

**Comment by machour** [comment]
@mechanicMo Could you try again with 1.6.5 and see if it works for you?

**Comment by machour** [comment]
Closing this as no response was provided from the original issue author. If you're still feel like something is wrong on our side, please open a new issue using the latest remix version.
