### ISSUE TITLE
`remix.config.js` seems to not support devServer directives mitigating CORS issues in local dev

### ISSUE THREAD

**Issue by hantusk** [remix-run/remix#2773]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

In `remix.config.js` add `devServer` config to set up a proxy to mitigate CORS issues when sending requests to other microservices in a local environment.

`remix.config.js` looks like this:
```javascript
  module.exports = {
  ignoredRouteFiles: [".*"],
  devServer: {
    public: 'localhost',
    proxy: {
      '/searchservice': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        pathRewrite: {
          '^/searchservice': ''
        },
        logLevel: 'debug'
      }
    }
  }
```

Run `npm run dev` in shell. It opens your Remix app at http://localhost:3000.
Send a request to http://localhost:3000/searchservice

### Expected Behavior

Expected that the remix devserver would send a request to microservice running at http://localhost:3001, and return its response. Microservice shows no incoming requests although log level is in debug mode, and direct calls to it directly on http://localhost:3001 works fine.

### Actual Behavior

Remix dev server returns its default 404 message
Microservice running at http://localhost:3001 shows no incoming requests in logs

Would also expect this doc: https://remix.run/docs/en/v1/api/conventions to reflect, how to work around CORS issues in local dev.

**Comment by hantusk** [comment]
Giving this a think more, i might not be designing my pattern here to Remix conventions. I suspect if i make a `<Form>` instead, and run the `fetch` call on the server side, i won't have CORS issues.

Of course creating this feature and its directives in the "Remix App Server" has other benefits (easy incremental ports of existing React apps and perhaps some other problems), i will re-write it to a <Form> and see if that solves my issues here.

**Comment by cliffordfajardo** [comment]
What version of Remix were you using at the time of this pull request?

I don't see `devServer` defined in the config anymore
- https://github.com/remix-run/remix/blob/main/packages/remix-dev/config.ts


![CleanShot 2022-09-13 at 15 10 17@2x](https://user-images.githubusercontent.com/6743796/190018329-5687f89e-dffe-446d-bb1e-81aae40da8b1.png)

**Comment by pcattori** [comment]
With `v2_dev` enabled in 1.19+ , you can create your own custom app server (e.g. check out the [custom app server for the express template](https://github.com/remix-run/remix/blob/main/templates/express/server.js)) where you can configure CORS to your hearts content and `remix dev` will use your custom app server in development.
