### ISSUE TITLE
Consuming actually all CPU resources

### ISSUE THREAD

**Issue by ZetraDev** [remix-run/remix#2774]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

Run `remix dev` / make it reload

### Expected Behavior

Not consuming many CPU resources

### Actual Behavior

It consuming actually all CPU resources (showing 90%+ utilization in task manager) when build / rebuild, which cause editor not response

**Comment by machour** [comment]
Can you share a bit more information about your setup ? Os, RAM, etc ..

**Comment by machour** [comment]
Would you mind testing with 1.4.0 ? 
AFAIK you're the only user with this problem, so it's kind of hard to pinpoint the issue..

**Comment by ZetraDev** [comment]
somehow it not using all cpu resources now, so i think the problem is solved
