### ISSUE TITLE
`--no-typescript` not quite 100% there

### ISSUE THREAD

**Issue by isaacs** [remix-run/remix#2781]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

```
npx create-remix@latest --template blues-stack --no-typescript
```

Then try to `npm run dev` in the app it creates.

### Expected Behavior

It should start the dev server.

### Actual Behavior

Complains about a bunch of stuff:

- `server.ts` is missing
- `prisma seed` command fails because `prisma/seed.ts` is actually `prisma/seed.js`
- many problems with trying to use `import` in commonjs contexts

Recommendation:

- Ensure that all typescript references are converted in package.json when using the no-typescript option
- Set `"type": "module"` in package.json and name all commonjs modules `.cjs`
    - alternative 1: name all esm modules `.mjs`
    - alternative 2: use `"type":"module"`, leave everything `.js`, but add this bit at the top of any file that references `require()`:
        ```js
        import { createRequire } from 'node:module'
        const require = createRequire(import.meta.url)
        ```
         Maybe ideal? it's the way I prefer anyway, "Use The Platform" and all that.

**Comment by mryechkin** [comment]
Running into the same issue with the Indie Stack as well: `Error: Cannot find module './seed.ts'`

**Comment by JorgeMadson** [comment]
I got the same error, but I don't know where it comes from?
Is an error related to npm run setup? https://github.com/remix-run/blues-stack/blob/main/package.json#L21

**Comment by MichaelDeBoey** [comment]
I've created https://github.com/remix-run/indie-stack/pull/63, https://github.com/remix-run/blues-stack/pull/57 & https://github.com/remix-run/grunge-stack/pull/50 in order to fix this.

Closing this issue as it can be tracked in the stack repos itself now

**Comment by JorgeMadson** [comment]
Thank you @MichaelDeBoey I was trying to figure out how to fix this, I will read your code to understand it.
