### ISSUE TITLE
npx create-remix@latest downloading remix repo 

### ISSUE THREAD

**Issue by shortnd** [remix-run/remix#2798]
### What version of Remix are you using?

latest

### Steps to Reproduce

npx create-remix@latest
select just the basics
name folder `my-remix-app`
wait for npm to install
cd my-remix-app

### Expected Behavior

Should be a bare bones remix template, with basic setup

### Actual Behavior

It looks to be downloading and installing the remix repo its self, with all the examples and tests. Instead of a bare bones project

**Comment by MichaelDeBoey** [comment]
https://github.com/remix-run/remix/pull/2733 will fix this in the next release
