### ISSUE TITLE
Github-Token missing from template validation call

### ISSUE THREAD

**Issue by FrecksterGIT** [remix-run/remix#2801]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

When trying to use a stack from a private GitHub repository the template validation step fails.

The authentication header is missing:
https://github.com/remix-run/remix/blob/7492b9beabb75f2f3af108942253e0a28b57c1ef/packages/remix-dev/cli/create.ts#L446

### Expected Behavior

Private Stacks should work out of the box.

### Actual Behavior

Error: 🚨 There was a problem verifying the template file. Please ensure you are connected to the internet and try again later.

**Comment by machour** [comment]
Fixed by @bgschiller ❤️
