### ISSUE TITLE
npx create-remix@latest is not working

### ISSUE THREAD

**Issue by ttatoni26** [remix-run/remix#2820]
### What version of Remix are you using?

latest

### Expected Behavior

Create a remix app

### Actual Behavior

Getting the error: `Creating your app…🚨 The provided template must be a Remix project with a package.json file, but that file does not exist in ...`

**Comment by machour** [comment]
Hi, are you using windows ?

**Comment by ttatoni26** [comment]
> Hi, are you using windows ?

Yes

**Comment by assoft** [comment]
I am also getting error... I can confirm that this error has nothing to do with package managers. I have no problem installing other applications.

![ss](https://user-images.githubusercontent.com/835239/163606060-c4a7e3c6-73fd-4355-b649-56a71d5f3c86.png)

**Comment by ttatoni26** [comment]
@assoft
You typed: "reate-remix"

**Comment by assoft** [comment]
Owww shittt 🫢.

**Comment by machour** [comment]
Duplicate of #2714
