### ISSUE TITLE
Cannot run Remix applications on a port > 3100. 

### ISSUE THREAD

**Issue by ryanlabouve** [remix-run/remix#2821]
### What version of Remix are you using?

^1.2.3

### Steps to Reproduce

```bash
export PORT=3900
npm run dev
```

### Expected Behavior

Remix server starts

### Actual Behavior

```
RangeError: `to` must be greater than or equal to `from`
    at AsyncFunction.module.exports.makeRange (/Users/ryanlabouve/code/ctnft-app/node_modules/get-port/index.js:99:9)
```

Introduced by https://github.com/remix-run/remix/commit/39d0dbf5c4ce102a9ba9448c8854bd465309803e.

**Comment by ryanlabouve** [comment]
I'd be happy to fix this by adjusting [this](https://github.com/remix-run/remix/commit/39d0dbf5c4ce102a9ba9448c8854bd465309803e#diff-f63e3a7b23edb5474980c4253ebbbf0810018688ed15afcbb1010652513f3c4aR245) to something like:

```
port: process.env.PORT ? Number(process.env.PORT) : makeRange(3000, 3100),
```

**Comment by vieira** [comment]
Can confirm, it is easy to reproduce by running, e.g., `env PORT=8000 npm run dev`, which will produce:

```
RangeError: `to` must be greater than or equal to `from`
    at AsyncFunction.module.exports.makeRange (/home/vieira/code/mix/node_modules/get-port/index.js:99:9)
    at Object.dev (/home/vieira/code/mix/node_modules/@remix-run/dev/cli/commands.js:249:19)
    at Object.run (/home/vieira/code/mix/node_modules/@remix-run/dev/cli/run.js:499:7)
```

**Comment by eldarshamukhamedov** [comment]
@ryanlabouve that works. I run dev servers on ports 10000+ 😅

**Comment by mcansh** [comment]
sorry folks! totally my fault and @ryanlabouve fix is what i actually wanted 😅
