### ISSUE TITLE
Can't run `npx create-remix@latest` with `.` current directory

### ISSUE THREAD

**Issue by TheKnarf** [remix-run/remix#2828]
### What version of Remix are you using?

npx create-remix@latest

### Steps to Reproduce

```
mkdir testdir
cd testdir
npx create-remix@latest
? Where would you like to create your app? (./my-remix-app) .
>> 🚨 The directory provided already exists. Please try again with a different directory.
```

### Expected Behavior

For it to work with the current directory when that directory is empty

### Actual Behavior

It refuses to do so.

**Comment by ttatoni26** [comment]
I am having the same issue.

**Comment by severomerfaruk** [comment]
I'm having the same issue. how to fix it?
