### ISSUE TITLE
Action methods ignored for index routes

### ISSUE THREAD

**Issue by gregbty** [remix-run/remix#2832]
### What version of Remix are you using?

1.4.0

### Steps to Reproduce

1. Create a bare remix project
2. Add `test/index.tsx` under `routes` and paste the following code:

```typescript
import { redirect } from '@remix-run/node'

export const action = () => {
  return redirect("/");
};
```

3. Update `index.tsx` in `routes` with the following code:

```typescript
import { Form } from "@remix-run/react";

export default function Index() {
  return (
    <Form method="post" action="/test">
      <button type="submit">Submit</button>
    </Form>
  );
}

```

4. Run the app and click on the "Submit" button on the root index page

### Expected Behavior

Browser redirects back to the index page.

### Actual Behavior

`405 Method Not Allowed` error is shown.

**Comment by machour** [comment]
You need to target `/test?index` 

#2808 will enhance the documentation for this behavior

**Comment by machour** [comment]
Documentation updated, please refer to https://remix.run/docs/en/v1/guides/routing#what-is-the-index-query-param

**Comment by gregbty** [comment]
Thanks!
