### ISSUE TITLE
Cannot get threejs working with remix run, despite ClientOnly & .client 

### ISSUE THREAD

**Issue by harrisrobin** [remix-run/remix#2833]
### What version of Remix are you using?

1.4.0

### Steps to Reproduce

Clone and run the following repo: https://github.com/harrisrobin/remix-run-three

### Expected Behavior

I would expect remix to be able to work with a library such as three, especially when using <ClientOnly> and .client extension.

### Actual Behavior

If you try to load a file that uses threejs, you will encounter the following error: 
<img width="1168" alt="CleanShot 2022-04-16 at 19 47 23@2x" src="https://user-images.githubusercontent.com/3880008/163698094-1253fb6a-0593-461c-a40f-f542a86be768.png">

```sh
marked is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.

✘ [ERROR] Could not resolve "three/examples/jsm/controls/OrbitControls"

    app/components/harris-model/harris-model.client.tsx:3:30:
      3 │ ... { OrbitControls } from "three/examples/jsm/controls/OrbitControls"
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./examples/jsm/controls/OrbitControls" was not found on the file system:

    node_modules/three/package.json:14:24:
      14 │     "./examples/jsm/*": "./examples/jsm/*",
         ╵                         ~~~~~~~~~~~~~~~~~~

  You can mark the path "three/examples/jsm/controls/OrbitControls" as external to exclude it from the bundle, which will remove this error.

 ✘ [ERROR] Could not resolve "three/examples/jsm/loaders/GLTFLoader"

    app/components/harris-model/model.client.ts:1:27:
      1 │ import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./examples/jsm/loaders/GLTFLoader" was not found on the file system:

    node_modules/three/package.json:14:24:
      14 │     "./examples/jsm/*": "./examples/jsm/*",
         ╵                         ~~~~~~~~~~~~~~~~~~

  You can mark the path "three/examples/jsm/loaders/GLTFLoader" as external to exclude it from the bundle, which will remove this error.
```

This is despite me adding 'three' to the   serverDependenciesToBundle inside remix.config.js

**Comment by agcty** [comment]
Have you tried using a regex that matches everything that comes after three as well? Like /three.*/

**Comment by chenc041** [comment]
You can copy the OrbitControls and GLTFLoader source files to the app directory and resolve this issue...

**Comment by bushblade** [comment]
I am having the same issue, is this really the solution though to copy the three loader code into the application?

**Comment by bushblade** [comment]
Copying the GLTFLoader to the Remix application code does work for me initially but when I refresh the app I get an error from three...
`ReferenceError: ProgressEvent is not defined`
It works fine in Vite with React but not in Remix.

**Comment by chaance** [comment]
Hey @bushblade, can you open a new issue with a minimal reproduction we can inspect? We've released a few new versions since this issue was opened that should have fixed it, but if there are bugs remaining we can take a look at your specific case.

**Comment by bushblade** [comment]
Thank you, yeah I'll get on a minimal reproduction and let you know.

**Comment by bushblade** [comment]
[Ok here is a minimal reproduction](https://github.com/bushblade/Remix-Import-from-ThreeJS-minimal-example)

**Comment by WesleyTheGeolien** [comment]
@bushblade Looking at how [drei](https://github.com/pmndrs/drei) create the loaders it looks like it is possible to import directly from `three-stdlib` for example: https://github.com/pmndrs/drei/blob/master/src/core/useFBX.tsx not sure if this helps?

**Comment by bushblade** [comment]
Hi @WesleyTheGeolien 
Yes that is exactly what I did.
Though I still feel that Remix should be able to import from threejs.

**Comment by designbyadrian** [comment]
I'm getting the same issue. I cannot import three packages directly, since it's part of a different package.
