### ISSUE TITLE
Some docs & examples use top-level `Date.now()` for cookie expiration

### ISSUE THREAD

**Issue by guillaumervls** [remix-run/remix#2848]
### What version of Remix are you using?

1.4.0

### Steps to Reproduce

(Problem is the docs, see below)

### Expected Behavior

Hi and thanks for the great work on Remix !

In the docs https://remix.run/docs/en/v1/api/remix#using-sessions and in some examples https://github.com/remix-run/remix/tree/main/examples/redis-upstash-session the proposed session storage code uses calls to top-level `Date.now()` for cookie expiration date.

While it may seem to work in development because it looks like the modules are re-imported for every request, it does not in production. `Date.now()` then does not have much sense, since it is only the timestamp when the server was started, not the timestamp of the request. 

Also, I found it confusing to create a cookie _outside_ the request/response lifecycle. As I understand, it's not _actually_ a cookie, but _cookie options_ instead. But it's weird, because the `expires` option doesn't make sense. (Unless we recreate the session storage for every request. And the docs & examples don't seem to go that way).

Hope I'm not missing something...

Cheers !

### Actual Behavior

(Problem is the docs, see above)

**Comment by machour** [comment]
Fixed by #3091
