### ISSUE TITLE
LiveReload doesn't work when TLS is enabled

### ISSUE THREAD

**Issue by isaacs** [remix-run/remix#2859]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

1. Create a server with TLS keys
2. Attach remix route handler to it
3. Load site
4. Error appears in console:

    ```
    WebSocket connection to 'wss://moxy.cow-augmented.ts.net:8002/socket' failed: An SSL error has occurred and a secure connection to the server cannot be made.
    ```

5. Change files, observe that they are not reloaded live.  (Server rebuilds, but the ws push doesn't work.)

### Expected Behavior

Expect that WebSocket.Server would be able to listen over https somehow.

### Actual Behavior

> WebSocket connection to 'wss://moxy.cow-augmented.ts.net:8002/socket' failed: An SSL error has occurred and a secure connection to the server cannot be made.

Tracked it down to this bit in `./node_modules/@remix-run/dev/cli/commands.js`

```js
  let wss = new WebSocket__default["default"].Server({
    port: config$1.devServerPort
  });
```

It appears that the only way for a ws server to speak tls is to attach to an existing server.

Something like this:

```js
  const server = config.devServerCert && config.devServerKey ? https.createServer({
    cert: config.devServerCert,
    key: config.devServerKey,
  }) : http.createServer()
  server.listen(config.devServerPort)
  let wss = new WebSocket.Server({ server });
```

**Comment by mstaicu** [comment]
@isaacs [this](https://github.com/traefik/traefik/issues/7111#issuecomment-1094679207) _might_ help. I'm running a different setup than yours, but I still serve the client via HTTPS and the live reload server has to connect via `wss` due to `https` being used as the protocol

**Comment by tadeaspetak** [comment]
Being able to run a `dev` server on an `https` domain (`localhost`, `lvh.me`) would be wonderful 👌

**Comment by EBruchet** [comment]
Is there any chance of the above commit being accepted in the near future? Using `https` configuration locally with an Express server setup is blocking access to the `wss://` for hot reloading at the moment.

Not sure if there's another known workaround.

**Comment by kiliman** [comment]
Have you tried simply including the `<LiveReload/>` component in your project and removing the protocol check (i.e., always using `ws:`).

https://github.com/remix-run/remix/blob/40a7a390063836607c76aad9754b7881f8c82303/packages/remix-react/components.tsx#L1498-L1561

**Comment by EBruchet** [comment]
I've been using `<LiveReload />` in the project (worth noting it works great without this HTTPS config) but unfortunately tweaking the `LiveReload` component directly produces the following error

```
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

Additionally as this is an organisation repository, editing the library files directly probably wouldn't be a maintainable approach going forward.

**Comment by petomalina** [comment]
I made this change for gitpod.io env, and it started working flawlessly.

- [First commit](https://github.com/petomalina/chakra-components/commit/388dd8dd01a3a25f2c8ae7bbc6c63490efd71672) is just copying the component into a custom one and importing instead of the official one
- [Second commit](https://github.com/petomalina/chakra-components/commit/fa3c64feb95e8f6645f2794727f52c2ce906b986) adds an expression to see whether I am running on gitpod.io and changes the URL

You can do the same easily with the protocols :)

**Comment by bderblatter-qualtrics** [comment]
@kiliman I need HTTPS for Marketo which requires a custom domain for certain functions to work (for security reasons). If I use a custom domain for localhost without HTTPS on my computer the page won't load because it is not secure.

**Comment by kiliman** [comment]
@petomalina I had to do a similar thing for CodeSandbox. If you look at my `LiveReload` component, you'll see that I had to change the URL since CSB encodes the port in the host name.
https://codesandbox.io/s/remix-starter-template-xs4z6?file=/app/components/LiveReload.tsx

**Comment by eladchen** [comment]
Doesn't seem like #4123 or #4107 will be merged anytime soon... so I solved it using the attached snippet.

```js
const { WebSocket } = require("ws");

// ... [some code that spins up an https server with express]

if (NODE_ENV !== "production") {
    const connectToRemixSocket = (cb, attempts = 0) => {
        const remixSocket = new WebSocket(`ws://127.0.0.1:8002`);

        remixSocket.once("open", () => {
            console.log("Connected to remix dev socket");

            cb(null, remixSocket);
        });

        remixSocket.once("error", (error) => {
            if (attempts < 3) {
                setTimeout(() => {
                    connectToRemixSocket(cb, attempts += 1);
                }, 1000);
            }
            else {
                cb(error, null);
            }
        });
    };

    connectToRemixSocket((error, remixSocket) => {
        if (error) {
            throw error;
        }

        const customSocket = new WebSocket.Server({ server: httpsServer });

        remixSocket.on("message", (message) => {
            customSocket.clients.forEach((client) => {
                if (client.readyState === WebSocket.OPEN) {
                    client.send(message.toString());
                }
            });
        });

        remixSocket.on("close", () => {
            customSocket.close();
        });
    });
}
```

**Comment by pcattori** [comment]
The new v2 dev server now fully supports TLS, as [described in the docs](https://remix.run/docs/en/main/other-api/dev-v2#how-to-set-up-local-https).

**Comment by lopugit** [comment]
Use Vite and you don't need LiveReload 🙏💯🙌
