### ISSUE TITLE
Socket.io example development server does not connect to socket.io websocket in server/index.js

### ISSUE THREAD

**Issue by EddyVinck** [remix-run/remix#2860]
### What version of Remix are you using?

1.4.0-pre.2

### Steps to Reproduce

Clone the Remix repo and navigate to the Socket.Io example: https://github.com/remix-run/remix/tree/main/examples/socket.io

Start the app server:

```sh
npm run start:dev
```

Run the development server:

```sh
npm run dev
```

Visit http://localhost:3000, and notice the connected log from the websocket in your terminal.
Then try making a change in the app's `app/routes/index.tsx` like changing some text.
The text will not update.

Visit http://localhost:3001, and try making a change again in `app/routes/index.tsx` and you will notice that the changes are reflected in your browser, however, you will not have a connection to the websocket.

### Expected Behavior

The websocket should connect on a localhost port and the development changes in the app should also be reflected on the same port, without manually restarting the server.

I just want to run `npm run dev` and not have to worry about what port I am visiting my app on.

### Actual Behavior

The "start:dev" script starts the server with websocket on localhost:3000
The "dev" script starts the development server in watch mode on localhost:3001

When visiting port 3000 you get the websocket, but no reloading of the server when you make changes in your app

When visiting port 3001 the changes in your app are reflected, but the websocket does not connect

Having these two separate servers makes it harder to develop an application.

My current workaround is to close my server and run `npm run dev:start` whenever I am making changes to the websocket code in `server/index.js`

**Comment by sergiodxa** [comment]
The dev script should run `remix watch` instead so it builds the app without running a server

**Comment by EddyVinck** [comment]
Is that all? @sergiodxa 

I just tested it with the `watch` command and now everything seems to work fine on localhost:3000

- [x] Connects to websocket, pinging works
- [x] Changes are reflected on the same port 

Unless I'm missing something I think this can be closed when a PR changes it. 

I can create it and submit the PR.
