### ISSUE TITLE
`npx create-remix@latest` fails, says that `filePath.replaceAll` is not a function

### ISSUE THREAD

**Issue by mubaraqwahab** [remix-run/remix#2868]
### What version of Remix are you using?

The latest (I guess?)... installing Remix fails

### Steps to Reproduce

1. Run `npx create-remix@latest`
2. Answer all the questions until "Do you want me to run `npm install`?"

OS: Windows 10
Node version: 14.17.6

### Expected Behavior

Remix creates a new project.

### Actual Behavior

After answering Yes to the `npm install` question, Remix fails and says that filePath.replaceAll is not a function. Nothing happens after that:

```console
$ npx create-remix@latest
? Where would you like to create your app? ./Hello-Remix
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? Do you want me to run `npm install`? Yes
⠋ Creating your app…filePath.replaceAll is not a function
```

**Comment by chaance** [comment]
Fixed in https://github.com/remix-run/remix/pull/2867. Between now and the next release, try using Node v15+ to set up a new project. You can switch back to 14 if needed for running the project.

**Comment by mubaraqwahab** [comment]
Okay, thank you!
