### ISSUE TITLE
<Outlet /> is not working after 'npm init remix'  in v0.18

### ISSUE THREAD

**Issue by charlieworld** [remix-run/remix#287]
After I finished setup using 

```
npm init remix
```
then run 
```
yarn dev
yarn start:dev  
```

There are not rendering contents  in index.jsx (only the `<Footer />`  in root.jsx)
![error_1](https://user-images.githubusercontent.com/10896707/134491044-520790ee-44de-4cdd-8312-6f3eacf7dd2b.png)

The other pages as well.

So I think maybe there is something wrong with `<Outlet />` ?

Then I notice that the dependencies in `package.json` only install `react-router-dom`

```
{
   "react-router-dom": "6.0.0-beta.0",
}
```

So I added `react-router` and `yarn` again

```
{
    "react-router": "^6.0.0-beta.3",
    "react-router-dom": "^6.0.0-beta.3",
}
```

The index page just work fine !
![error_2](https://user-images.githubusercontent.com/10896707/134491684-92839009-cecc-4227-8e84-bf4f1b6a6fce.png)

So I think maybe the `react-router` package is missing in the `npm init remix` ?

**Comment by machour** [comment]
Not applicable anymore
