### ISSUE TITLE
After 0.18 upgrade, css imports show error

### ISSUE THREAD

**Issue by Graham42** [remix-run/remix#291]
After the 0.18 upgrade, I noticed my css imports showing TypeScript errors, for example:
```
Cannot find module '../styles/index.css' or its corresponding type declarations.
```

Currently the 0.18 release uprade instructions say to add this line to the `tsconfig.json` file
```json
{
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"]
}
```
But if the `tsconfig.json` file is in the `app/` folder, then `"remix.env.d.ts"` is not resolved. This can be fixed by changing the include statement to 
```json
{
  "include": ["../remix.env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

I spun up a new test project with `npm init remix` and I see that the `tsconfig.json` file is now in the root of the project by default, so I think the 0.18 release notes are missing step to move `app/tsconfig.json` to the root of the project.

**Comment by machour** [comment]
Not applicable anymore

**Comment by joshuagraber** [comment]
Why is this not applicable anymore? I'm using `1.6.7` and keep getting import errors with CSS files. Have tried this solution and it feels like a zillion others, no luck. is there any documentation on how to solve this?

**Comment by machour** [comment]
@nabeelpkl please open a new [Q&A question](https://github.com/remix-run/remix/discussions/new?category=q-a) in the discussion tab.
