### ISSUE TITLE
process not defined

### ISSUE THREAD

**Issue by ZetraDev** [remix-run/remix#2927]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

use process inside a component like below:
```tsx
function Component() {
    return (
        <div>
            {process.env.DOMAIN === "example.com" ? "Is main domain" : "Not main domain"}
        </div>
    )
}
```

### Expected Behavior

Should be work as it work before

### Actual Behavior

Somehow it start throwing `process is not defined`

**Comment by brightpixels** [comment]
What was solution to this? Facing the same issue

**Comment by sergiodxa** [comment]
@brightpixels `process.env` only works server-side (it's a Node thing) with the exception of `process.env.NODE_ENV` which is hardcoded on build, for any other env variable use the loader to read the value and return it.

This is documented here https://remix.run/docs/en/v1/guides/envvars

**Comment by brightpixels** [comment]
@sergiodxa I have followed https://remix.run/docs/en/v1/guides/envvars and there are several probelms:
- console.log(window) results in `ReferenceError: window is not defined` in the terminal and browser BUT console.log(global.window) log in the browser console and undefined in the terminal.
- When I take this further and try to console.log(global.window.ENV) it results in this error: `Cannot read property 'ENV' of undefined` both in the terminal and browser.

**Comment by sergiodxa** [comment]
> @sergiodxa I have followed https://remix.run/docs/en/v1/guides/envvars and there are several probelms:
> 
> * console.log(window) results in `ReferenceError: window is not defined` in the terminal and browser BUT console.log(global.window) log in the browser console and undefined in the terminal.
> * When I take this further and try to console.log(global.window.ENV) it results in this error: `Cannot read property 'ENV' of undefined` both in the terminal and browser. However console.log(global.window?.ENV) works. Is it possible to prevent the rest of the code running till window object has the ENV object?

You should access window only inside useEffects or .client files because window is only available in the browser.

**Comment by sergiodxa** [comment]
If you need the value of an env variable inside the render of the function return it from the loader access it from there.

**Comment by brightpixels** [comment]
I have a app/config.ts file that looks like this:
```
const CONFIG = {
  MAIN_URL: process.env.MAIN_URL,
};

```
I am trying to access it inside the config file first. Then components or helper functions are importing this file and access the values.

**Comment by kiliman** [comment]
If you're going to import your config, you need to make sure to add .server to the filename. Otherwise, it'll end up in your client bundle and break, because `process` only exists on the server.

```ts
// config.server.ts
export const CONFIG = {
  MAIN_URL: process.env.MAIN_URL,
} as const

export type Config = typeof CONFIG

declare global {
  interface Window {
    CONFIG: Config
  }
}

// root.tsx
<body>
  <Outlet />
  <ScrollRestoration />
  <script dangerouslySetInnerHTML={{__html: `window.CONFIG=${JSON.stringify(CONFIG);}`}></script>
  <Scripts />
  <LiveReload />
</body>
```
You can now access your config from `window.CONFIG.MAIN_URL`

**Comment by chang-ryan** [comment]
i get this problem when trying to import another package.

for example 

```
import { PaperSDKProvider, LoginWithPaper } from "@paperxyz/react-client-sdk";
```

this is a package that uses `process` in its code. and it's breaking when using `npm run dev` with `remix`

any ideas on how to workaround this? can be put a `process` into global vars for the client side?
