### ISSUE TITLE
Browser `publicPath` totally ignored in `@remix-run/serve`

### ISSUE THREAD

**Issue by fguitton** [remix-run/remix#2933]
Hello,
I hope you are having a great day !
🌴 

### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Create a remix application and set the `remix.config.js` field `publicPath` to something other than `/build/`.
Upon running `remix dev` and accessing the URL in a browser, assets cannot be found.

### Expected Behavior

It should be possible to customize the asset serving path while developing.

### Actual Behavior

Currently the `publicPath` is being ignored and prevents the use of a custom path while developing.
No mention of this limitation is made in the documentation as far as I know.
Behavior is consistent with the hardcoded path in the codebase.

https://github.com/remix-run/remix/blob/b1ce044f812a9bd47a1cffbc1e598bfb2a2e5868/packages/remix-serve/index.ts#L13-L18

**Comment by samlaycock** [comment]
I'm seeing the same problem as well, using the Cloudflare Workers runtime. Seems as though the `publicPath` value in the Remix config is just not being regarded in the serving of static assets of any runtime.

If the intention of this is to simply support CDN domains for static assets, and I'm not sure if it is or not, the docs really should say so... the presumption is we can use this to add route prefixes to the static URLs to allow for more complex routing scenarios (behind proxies/load balancers etc.)

https://github.com/remix-run/remix/blob/99fbb9917da6146578a4f0cfb8289d4a3ef15deb/packages/remix-cloudflare-workers/worker.ts#L63-L64

**Comment by machour** [comment]
This have been fixed by https://github.com/remix-run/remix/pull/3349
