### ISSUE TITLE
Happens "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." on https://remix.run/ 

### ISSUE THREAD

**Issue by regchiu** [remix-run/remix#2943]
### What version of Remix are you using?

v1.4.1?

### Steps to Reproduce

1. Convert any language with Google Translate  of Chrome extension.

2. Keep scrolling down

![image](https://user-images.githubusercontent.com/25433868/164290371-f6c2a807-a02c-4691-a060-d37b8dabf5e7.png)

3. Will see errors on the website.

![image](https://user-images.githubusercontent.com/25433868/164290490-715d2337-7f29-455f-a50d-052ca0b40967.png)

### Expected Behavior

No errors are displayed.

### Actual Behavior

Console
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ys (https://remix.run/build/_shared/chunk-AGZHEPHC.js:7:5603)
    at Yf (https://remix.run/build/_shared/chunk-AGZHEPHC.js:9:3820)
    at L.unstable_runWithPriority (https://remix.run/build/_shared/chunk-AGZHEPHC.js:1:4026)
    at rn (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38448)
    at Ge (https://remix.run/build/_shared/chunk-AGZHEPHC.js:9:1807)
    at yi (https://remix.run/build/_shared/chunk-AGZHEPHC.js:7:11071)
    at https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38670
    at L.unstable_runWithPriority (https://remix.run/build/_shared/chunk-AGZHEPHC.js:1:4026)
    at rn (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38448)
    at Cs (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38616)
ui @ chunk-AGZHEPHC.js:7
```

**Comment by machour** [comment]
Seems to be https://github.com/facebook/react/issues/17256

**Comment by machour** [comment]
Issue migrated to the remix website (private) repo.

**Comment by tmhuyy** [comment]
So, what is the correct solution for this problem?

**Comment by tmhuyy** [comment]
@regchiu Did you fix this problem already ?

**Comment by regchiu** [comment]
> @regchiu Did you fix this problem already ?

No. This issue should have been listed as a special issue by the team to deal with. Probably not solved yet.

**Comment by tmhuyy** [comment]
> > @regchiu Did you fix this problem already ?
> 
> 
> 
> No. This issue should have been listed as a special issue by the team to deal with. Probably not solved yet.

- I have no idea about this bug. Would you mind to explain that for me 😄 ? @regchiu 
- I try to use i18next to changing multi-language (by choose language in app setting and detect by web browser settings).
- Then I try to use npm run build and deploy this web. The problem happens when I turn on gg translate in Chrome and Safari in iPhone @@. It said the same error with your case. 
Thank you very much @regchiu. Please help me explain this error 😥

**Comment by regchiu** [comment]
@tmhuyy 

It should be that Google Translate will change the DOM, causing such an error.(https://github.com/facebook/react/issues/11538#issuecomment-390386520)

I saw someone discussing that currently preventing browsers from automatically asking for translation can temporarily solve this problem caused by users accidentally using Google Translate.(https://github.com/facebook/react/issues/17256#issuecomment-1022045269)

**Comment by tmhuyy** [comment]
@regchiu 
Thanks for your help 😀 Have a great day
