### ISSUE TITLE
Security vulnerability with @remix-run/dev 1.4.1

### ISSUE THREAD

**Issue by morsmodr** [remix-run/remix#2959]
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

`npm i` in a remix project which has `^1.4.0` in package.json

Then run `npm audit`. Following results are shown

![Screen Shot 2022-04-21 at 10 15 06 PM](https://user-images.githubusercontent.com/7231256/164607899-dc7c423c-631a-42a8-9068-81ed3f4f2aeb.png)

### Expected Behavior

Resolve by upgrading to unset-value version 2.0.1

### Actual Behavior

Resolve by upgrading to unset-value version 2.0.1

**Comment by machour** [comment]
This appears to have been fixed.
