### ISSUE TITLE
Cannot run `remix run` on multiple apps at once

### ISSUE THREAD

**Issue by chaance** [remix-run/remix#296]
Because the port used by the WebSocket server is hard-coded, there's currently no way to concurrently run dev for two Remix apps at once.

https://github.com/remix-run/remix/blob/c1821e4f2c7e844f3b7462bbd6ae7711479c1c7d/packages/remix-dev/cli/commands.ts#L52

The `run` and `watch` commands would need to be updated to accept an alternative argument to set the WebSocket's server port. It would be nice if we could also pass these as command line arguments as needed.

```bash
# easily override either the port passed to @remix-run/serve or the watch command
# bikeshed the APIs, obviously!
$ remix run --port 3030 --socket-port 3002
```

Thoughts?

**Comment by jamesmall** [comment]
Pilfered through the source code and found that you can set it via command line. If you update the devServerPort in the remix.config.js file in conjunction with setting REMIX_DEV_SERVER_WS_PORT via command line you can run multiple apps at once. You would also have to set the PORT to be different than the other app, of course.


```
// remix.config.js
...
module.exports = {
  appDirectory: 'app',
  browserBuildDirectory: 'public/build',
  publicPath: '/build/',
  serverBuildDirectory: 'build',
  devServerPort: [NEW WS PORT],
};


// command line
PORT=3001 REMIX_DEV_SERVER_WS_PORT=[NEW WS PORT] remix dev
```

The issue can be found in @remix-run/dev/config.js file. The config is being read but for whatever reason, the devServerPort isn't being set on appConfig causing the devServerPort to be the new port when compiled but the ws port remains 8002.

**Comment by mcansh** [comment]
> Pilfered through the source code and found that you can set it via command line. If you update the devServerPort in the remix.config.js file in conjunction with setting REMIX_DEV_SERVER_WS_PORT via command line you can run multiple apps at once with live reload. You would also have to set the PORT to be different than the other app, of course.
> 
> ```
> // remix.config.js
> ...
> module.exports = {
>   appDirectory: 'app',
>   browserBuildDirectory: 'public/build',
>   publicPath: '/build/',
>   serverBuildDirectory: 'build',
>   devServerPort: [NEW WS PORT],
> };
> 
> 
> // command line
> PORT=3001 REMIX_DEV_SERVER_WS_PORT=[NEW WS PORT] remix dev
> ```
> 
> The issue can be found in @remix-run/dev/config.js file. The config is being read but for whatever reason, the devServerPort isn't being set on appConfig causing the devServerPort to be the new port when compiled but the ws port remains 8002.

you are absolutely right, I've resolved it here :) #2456

**Comment by kiliman** [comment]
The funny thing is that the WebSocket server port is the one that I don't care about and Remix should just pick a random port.

Oddly though, Remix App Server was updated to pick a random port if the default was already open. This is rarely what I want. I'd much rather RAS just exit with error and force me to pick a PORT.

**Comment by mcansh** [comment]
> The funny thing is that the WebSocket server port is the one that I don't care about and Remix should just pick a random port.

we do, it just wasn't making it to LiveReload 🙈

**Comment by MichaelDeBoey** [comment]
Closing as #2456 is merged now

**Comment by mcansh** [comment]
> Closing as #2456 is merged now

that didn't fix it 😢

**Comment by machour** [comment]
Fixed by #3447 ?

**Comment by machour** [comment]
Should be ok by now, please reopen if not.

**Comment by abubakarasifmughal** [comment]
Why change the package.json scripts by adding more Env Vars 
I linked my `.env` as following, feel free to add you port if you don't want to link `.env` file

```
export default {
  tailwind: true,
  ignoredRouteFiles: ['**/.*'],
  dev: {
    port: Number(process.env.REMIX_DEV_PORT),
  },
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  watchPaths: () => createWatchPaths(__dirname),
};

```
