### ISSUE TITLE
action formData not working as expected with modals.

### ISSUE THREAD

**Issue by rodrigofuentes** [remix-run/remix#2978]
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Build a multi-form route but with each form rendered in a modal pop-up.
Reproduction: https://stackblitz.com/edit/github-fn9naa?file=app%2Froutes%2Finvitations.tsx

The work around is to pass an hidden `input` that holds the value and name of the `button`.
Workaround: https://stackblitz.com/edit/github-fn9naa-shsnbv?file=app%2Froutes%2Finvitations.tsx

### Expected Behavior

When building a form within a modal. I would expect formData to have the same shape as it would without the modal.

```sh
formData: { email: 'asdf@asdf.com', _action: 'send' }
```

### Actual Behavior

The formData loses the value for the button. 

```sh
formData: { email: 'asdf@asdf.com' }
```

**Comment by mcansh** [comment]
hey @rodrigofuentes i was able to replicate this on stackblitz but wasn't able to once i downloaded and ran it locally

**Comment by mcansh** [comment]
@rodrigofuentes, my apologies, it works in safari, but not Firefox or Chrome 😅

**Comment by mcansh** [comment]
okay! it is us 😅, when calling `new FormData()` it doesnt know which button triggered it, expect a fix soon!

**Comment by mcansh** [comment]
ok! another update for you, it seems chrome/firefox are "correct" https://stackoverflow.com/questions/48322876/formdata-doesnt-include-value-of-buttons, but we do account for this in our `<Form />`, `useSubmit`, and `useFetcher().submit` implementations, but for some reason the button we're resolving to is the one that opens the modal so it doesn't add the button name/value - we're looking into it!

**Comment by penspinner** [comment]
Pretty sure this is related to the [failing test](https://github.com/remix-run/remix/pull/2309) I created a while ago.

**Comment by mcansh** [comment]
@penspinner just updated your PR with the changes on dev (#3094) - and all passed! feel free to try out `v0.0.0-nightly-b797f54-20220506` - I'll tidy up your PR and merge it as an extra test :)
