### ISSUE TITLE
Fails To Create Remix App

### ISSUE THREAD

**Issue by udasitharani** [remix-run/remix#2991]
### What version of Remix are you using?

create-remix@latest

### Steps to Reproduce

1. Run `npx create-remix@latest`.
2. Enter a directory name, in my case - `web` or `./web` both fail.
3. Select `Just the basics`.
4. Select any option. In my case - `Remix App Server` (tried express too, to no avail).
5. Enter yes or no to run npm install, doesn't matter.

### Expected Behavior

It should create a remix app in the web directory.

### Actual Behavior

Fails to create the app and exits with the error - `filePath.replaceAll is not a function`. Refer to screenshot attached.
<img width="1270" alt="Screenshot 2022-04-26 at 11 55 10 PM" src="https://user-images.githubusercontent.com/56196911/165367947-847b844a-e37e-487f-8740-f5daf8c8b0b1.png">

**Comment by udasitharani** [comment]
Using `create-remix@1.4.0` didn't cause this issue though.
Must be something with `1.4.1`

**Comment by kiliman** [comment]
`string.replaceAll` is only available in Node v15+. They have fixed it so you can still use Node v14. It'll be in the next release.

https://github.com/remix-run/remix/issues/2868

**Comment by MichaelDeBoey** [comment]
Closed by #2868
