### ISSUE TITLE
useTransition, isCreating does not work in Safari

### ISSUE THREAD

**Issue by cabello** [remix-run/remix#2993]
### What version of Remix are you using?

1.4.1

### Other software version

Safari: v15.4

<img width="396" alt="Screen Shot 2022-05-02 at 11 19 57 AM" src="https://user-images.githubusercontent.com/60936/166260044-1054c0ec-8a87-4d88-b9c1-d0ac11b28b0a.png">

macOS Monterey v12.3.1

### Steps to Reproduce

Follow the tutorial and complete the Progressive Enhancement step: https://remix.run/docs/en/v1/tutorials/blog#progressive-enhancement

### Expected Behavior

Clicking the button should disable the button and transition if from "Create" to "Creating..."

### Actual Behavior

The button is never disabled and remains labeled as "Create"

**Comment by mikkpokk** [comment]
Tested with MacOS Monterey (12.2.1) - Safari Version 15.3 (17612.4.9.1.8) and **works as expected** with Remix 1.4.0 & 1.4.3.

**Comment by alexamy** [comment]
Had the same problem with Remix 1.5.1, on dev server in Chrome and Firefox.
You can check [this commit](https://github.com/alexamy/remix-tutorial/commit/6937a7b96c12491cb122477bcfd200e7d0ad43cb) in my tutorial repo and try it yourself on http://localhost:3000/posts/admin/new.

**Comment by machour** [comment]
@cabello is this issue still affecting you?
