### ISSUE TITLE
firebase-admin package cannot be used in remix app

### ISSUE THREAD

**Issue by th-m** [remix-run/remix#2995]
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

- npx create-remix@latest
- just the basics
- netlify set up
- npm install - yes
- typescript
- cd into project
- npm i firebase-admin
- import * as admin from "firebase-admin";
- 
```
export const adminDB = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://mysite.firebaseio.com"
});
```

### Expected Behavior

including firebase-admin should allow me to use the firebase-admin library.

### Actual Behavior

A sub package of firebase-admin throws errors and prevents the packages from working.
✘ [ERROR] Could not resolve "@firebase/database-compat/standalone"

**Comment by grundius** [comment]
Just tried this with Netlify deployment, I get the same issue (used the default app, so just `admin.initializeApp()` without options). I run into the same error. I _do not_ get this error when running the Remix Server or with a Fly.io targeted deployment.

This phrase:
```
None of the conditions provided ("node") match any of the currently active conditions ("browser", "default", "require"):
```
and the a quick look on the Netlify forums (a sample: https://answers.netlify.com/t/firebase-admin-sdk-with-netlify-server-side-lambda/22627) makes me think this is more an issue with Firebase Admin not being compatible out-of-the-box with the Netlify runtime environment than with Remix itself.

**Comment by cairin** [comment]
The firebase admin SDK requires node, which isn't present in the browser. The [Module constraints](https://remix.run/docs/en/v1/guides/constraints) docs go into more detail.

But basically you need to ensure you're not trying to use the admin SDK client side. The easiest way to do this is to use the `.server.ts` file extenstion.

For example, you have the following folder structure:
```
├── components
│   └── button.tsx
├── lib
│   └── firebaseAdmin.server.ts
├── root.tsx
└── routes
    └── index.tsx
```

**Comment by th-m** [comment]
@cairin that fixed it. Bless you 🙏

**Comment by mercpls** [comment]
> The firebase admin SDK requires node, which isn't present in the browser. The [Module constraints](https://remix.run/docs/en/v1/guides/constraints) docs go into more detail.
> 
> But basically you need to ensure you're not trying to use the admin SDK client side. The easiest way to do this is to use the `.server.ts` file extenstion.
> 
> For example, you have the following folder structure:
> 
> ```
> ├── components
> │   └── button.tsx
> ├── lib
> │   └── firebaseAdmin.server.ts
> ├── root.tsx
> └── routes
>     └── index.tsx
> ```
> 
> `firebaseAdmin.server.ts` will look something like this:
> 
> ```ts
> import * as admin from "firebase-admin";
> export const adminDB = admin.initializeApp({
>   credential: admin.credential.cert(serviceAccount),
>   databaseURL: "https://mysite.firebaseio.com"
> });
> ```
> 
> and your `routes/index.tsx` (Or wherever you want to use it) will look something like this:
> 
> ```ts
> import { adminDB } from '~/lib/firebaseAdmin.server'
> 
> export const loader: LoaderFunction = async ({ request }) => {
>   // Make sure you only use the adminDB here
>   adminDB.someFunc()
> }
> 
> export default function Page() {
>   return (
>     <>
>         Some HTML
>     </>
>   )
> }
> ```
I'm getting this error after following exactly what you wrote, any ideas?

Using vite w/ remix
Cannot read properties of undefined (reading 'cert')

**Comment by mercpls** [comment]
Fix: import admin from "firebase-admin"; and not `* as admin`
