### ISSUE TITLE
Unable to host remix at a subpath / subfolder

### ISSUE THREAD

**Issue by gitn00b1337** [remix-run/remix#2996]
### What version of Remix are you using?

latest

### Steps to Reproduce

I want to host my remix app under a subfolder, i.e. mydomain.com/remixapp.

Using the blues server.ts as an example, express routing is configured with:

```
app.all(
  "*",
  MODE === "production"
    ? createRequestHandler({ build: require(BUILD_DIR),  })
    : (...args) => {
        purgeRequireCache();
        const requestHandler = createRequestHandler({
          build: require(BUILD_DIR),
          mode: MODE,
        });
        return requestHandler(...args);
      }
);
```
But following the request handler, it matches routes using this function: 

https://github.com/remix-run/remix/blob/c34f6af4bb7d9ef590e5e46ac08281de50ef5404/packages/remix-server-runtime/routeMatching.ts#L12

I can't see any way to get around this as it's using react-router-dom. Looking at the method there, it seems there's a basename prop, but it's not passed from remix:

https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/router.ts

If I've understood correctly, it seems the fix is to simply add basename to remix-server-runtime?

### Expected Behavior

Hosting my app at mydomain.com/remixapp should work as expected.

### Actual Behavior

When hosting the app at a subfolder it no longer renders, as the /build/ directory is expected to be at mydomain.com/build not mydomain.com/remixapp/build

**Comment by kiliman** [comment]
You can try `remix-mount-routes` to set the basePath. You will probably want to change the 
`publicPath` and `assetsBuildDirectory` as well.

```ts
const { mountRoutes } = require('remix-mount-routes')

const basePath = process.env.REMIX_BASEPATH ?? ''

module.exports = {
  ignoredRouteFiles: ['.*'],
  publicPath: `${basePath}/build/`,
  assetsBuildDirectory: `public${basePath}/build`,
  routes: defineRoutes => {
    return mountRoutes(basePath, 'routes')
  },
}
```
https://github.com/kiliman/remix-mount-routes

**Comment by gitn00b1337** [comment]
Ah perfect, I had no idea this existed. Thanks!

**Comment by yracnet** [comment]
I have send a PR for this case. https://github.com/remix-run/remix/pull/4459
