### ISSUE TITLE
Cache initial HTML page data in service worker cache?

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#30]
When the user visits "/some/page" we stick the data in the HTML payload.

If they navigate to "/other/page" we do a client side fetch for the data.

If they then click "back", we fetch the data client side, even though we already got it in the initial payload.

With our old data cache we didn't do this.

## Service workers

Service worker caching can help us here. I don't know the APIs but it's goes something like this:

1. put the loader's headers on __remixcontext
2. take data on `__remixContext` and shove it into a "fetch" cache with the `__remix_data?...` url and the headers from the loaders

Boom! Now when the user clicks back to the initial html page, it's as though they fetched from the client.

**Comment by chaance** [comment]
Tracking in REM-896
