### ISSUE TITLE
Suggestion: Default installation should point to "Just the Basics" by default

### ISSUE THREAD

**Issue by codeser** [remix-run/remix#3000]
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Run npx create-remix@latest

### Expected Behavior

You are asked, "What type of app do you want to create?"
The default one that is selected is the more advanced option.

It might be better for beginners to remix if the default option was "Just the Basics"

### Actual Behavior

My suggestion is for the question "What type of app do you want to create?" make the default option "Just the Basics"

**Comment by machour** [comment]
Fixed by #3078
