### ISSUE TITLE
Remix disregards tsconfig extend clause

### ISSUE THREAD

**Issue by ivosabev** [remix-run/remix#3010]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

I have `tsconfig.json` in the root of my project that extends`scripts/shared-tsconfig.json`.

## tsconfig.json
```json
{
  "files": [],
  "exclude": ["node_modules"],
  "extends": "./scripts/shared-tsconfig.json",
  "references": [
    {
      "path": "app"
    }
  ],
  "compilerOptions": {
    "baseUrl": "app",
    "paths": {
      "~/*": ["./*"]
    },    
  }
}

```

## scripts/shared-tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importsNotUsedAsValues": "remove",
    "incremental": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noErrorTruncation": true,
    "noImplicitAny": false,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext",
    "typeRoots": ["../types", "../node_modules/@types"],
    "useUnknownInCatchVariables": false
  }
}
```

### Expected Behavior

Do not add anything to my root `tsconfig.json`

### Actual Behavior

When I run remix, it adds a bunch of compiler options to my root `tsconfig.json`, which already has them by extending the `shared-tsconfig.json`

**Comment by mcansh** [comment]
sorry! have a pr for this #2961

**Comment by mcansh** [comment]
> That's quick, thanks!

👍 no problem, wanted to add tests before merging it and by doing that i missed our release window haha, once it gets merged, you'll get a notification here to try out a nightly release later that night :)
