### ISSUE TITLE
Deployment to Vercel is broken

### ISSUE THREAD

**Issue by ananni13** [remix-run/remix#3028]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

- Create a new Remix App with `npx create-remix@latest`
- Select "Just the basics" and "Vercel"
- Push to a Github repo, deploy to Vercel with "Remix" preset

### Expected Behavior

- Project builds and deploys without issues

### Actual Behavior

- Project apparently builds without issues
- Visiting the deploy will throw the default Vercel 404:
  ![404](https://user-images.githubusercontent.com/37385837/165967181-79c8313e-82bf-4357-80e8-77bec8b83969.png)
- Trying to view the deploy Function Logs will show "**No Serverless Functions**":
  ![sf](https://user-images.githubusercontent.com/37385837/165967770-837b6682-85c0-4d2c-9147-328ae6d44c77.png)
- The deploy source output has no "**api**" folder:
  ![outerr](https://user-images.githubusercontent.com/37385837/165968969-2a9cc62c-5f30-4192-96e6-c0c915053892.png)

This could be an issue with Vercel since everything was working fine just days ago.

**Comment by davidsoderberg** [comment]
@ananni13 try redeploy now it worked for me, Vercel did an update yesterday

**Comment by ananni13** [comment]
Yes now it's working again, looks like it was an issue on Vercel side.

**Comment by cdoshi** [comment]
Getting the same issue. Any ideas on how to fix it. Followed the guide here https://vercel.com/changelog/remix-projects-can-now-be-deployed-with-zero-configuration

**Comment by submetu** [comment]
+1 Getting the same error :( 404. Everything looks fine on vercel.

**Comment by cdoshi** [comment]
@submetu Managed to fix it with help of vercel support. Refer this repo https://github.com/vercel/vercel/tree/main/examples/remix
Specifically, you will need to api directory with index.js and update remix.config.js

**Comment by cdoshi** [comment]
@mocon So when I had setup the project, the api directory in the root folder was absent. I had to add it manually that contained the index.js file. That made the 404 go away.
