### ISSUE TITLE
data revalidating doesn't work for index route

### ISSUE THREAD

**Issue by lili21** [remix-run/remix#3058]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

[codesandbox example](https://codesandbox.io/s/pedantic-leftpad-g2ehv0?file=/app/routes/test/index.jsx)

input the form field, and click the submit button, 

### Expected Behavior

the loader inside the `test index` route module should return `index loader data` after form submit.

### Actual Behavior

the loader inside the `test index` route module should return undefined.

**Comment by mikkpokk** [comment]
I took your code from your example and added a `Form` with a empty `action` handler.

Everything works as expected. Loader still returns a string "index loader data" after a form submission.

```Javascript
import {Form, useLoaderData} from '@remix-run/react'

export const action = () => {
    return null
}

export const loader = () => {
    return 'index loader data'
}

export default function TestIndex() {
    const data = useLoaderData()
    console.log(data)
    return (
        <div>
            <div>test index page</div>
            {data}
            <Form method={'post'}>
                <button type={'submit'}>Test</button>
            </Form>
        </div>
    )
}
```

**Comment by lili21** [comment]
I guess the problem is the parent route's form submission.

**Comment by brophdawg11** [comment]
Thank you for the example @lili21!  I wasn't able to reproduce this issue - is this still a problem for you?  I couldn't get the code sandbox to run, but I downloaded the files and created a simplified stackblitz and it seems to run the `test/index.jsx` loader correctly during revalidation after a form submission from `test.jsx` - https://stackblitz.com/edit/node-qpu3ak

Could you let me know if that's working for you and if we can close this issue?
