### ISSUE TITLE
Documentation perusal V0.19

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#306]
Just jotting down anything I notice going through the new docs!

After going through it all it's 🔥 and all flows really nicely, only a few little things that I came across:

[Route Filenames](https://docs.remix.run/v0.19/api/app/#route-filenames) - 404 file name description missing the end of the last sentence:
> routes/404.tsx: When a URL can't be matched to a route, Remix uses this file to render a 404 page. We don't like this convention because "/404" should be a valid URL (maybe you're showing the best BBQ in Atlanta!). This is what we've got right now though. This will probably.

[Loader arg: request](https://docs.remix.run/v0.19/api/app/#loader-arg-request) - Extra URL? I might just be reading this the wrong way
>You can also use this to read URL URLSearchParams from the request like so:

[Returning Response Instances](https://docs.remix.run/v0.19/api/app/#returning-response-instances) - Bottom "see also" links are broken

> See also:
> (Remix Web Fetch API)["../other/fetch"]
> (headers)["#headers"]
> MDN Response Docs

[Headers](https://docs.remix.run/v0.19/api/app/#headers) - This one is a nitpick, the term "leaf route" comes out of nowhere after using Layout / Child route everywhere else in the docs... I think it could easily be used/explained in the nested routes tutorial along with Layout / Index routes.

>All that said, you can avoid this entire problem by not defining headers in layout routes and only in leaf routes.

[transition.submission](https://docs.remix.run/v0.19/api/remix/#transitionsubmission) - Still needs it's example

[createCookie](https://docs.remix.run/v0.19/api/remix/#createcookie) - Typo 'there'
>Creates a logical container for managing a browser cookie from there server.

[createSession](https://docs.remix.run/v0.19/api/remix/#createsession) - TODO
[isSession](https://docs.remix.run/v0.19/api/remix/#issession) - TODO

[Types](https://docs.remix.run/v0.19/api/remix/#types) - Is this meant to have any words? It's just the huge title and some function types haha

[Starter Templates](https://docs.remix.run/v0.19/other-api/adapter/#starter-templates) - Title but no content

[What are nested routes](https://docs.remix.run/v0.19/guides/routing/#what-are-nested-routes) - Need me them sweet Animated SVG's that have been hinted at for a while now

[Higher Order Functions](https://docs.remix.run/v0.19/other-api/constraints/#higher-order-functions-in-loaders) - The Throwing responses update would create new best practices for handling a few of the examples shown in this section now.

**Comment by samstanding** [comment]
Still seeing the TODO for createSession: https://remix.run/docs/en/v1/api/remix#createsession and the missing animations and a TODO for Nest Routes: https://remix.run/docs/en/v1/guides/routing#what-are-nested-routes.
