### ISSUE TITLE
`npm init remix` - version number

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#310]
Just a quick thing that caught me the other day, NPM can work off a local cached version so it'd be good to surface the version number in the welcome text like:

> R E M I X - v0.19.0
> 
> 💿 Welcome to Remix! Let's get you set up with a new project.
> 
> ? Where would you like to create your app? (./my-remix-app)

**Comment by imrishabh18** [comment]
@mjackson Can I take up this issue?
