### ISSUE TITLE
Remix CLI does not properly detect package manager

### ISSUE THREAD

**Issue by alvinthen** [remix-run/remix#3108]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

1. `yarn create remix`

### Expected Behavior

CLI should ask

Do you want me to run `yarn install`?

### Actual Behavior

CLI is asking

Do you want me to run `npm install`?

### More information

In #2562, it is checking for `npm_user_agent` in the environment. However, in my setup, the env should be `npm_config_user_agent`

node version: v14.18.1 (via nvm)
npm version: 7.24.2
yarn version: 1.22.18

I haven't done any other custom env setup

**Comment by MichaelDeBoey** [comment]
Closed by #3109
