### ISSUE TITLE
Fly.io template broken / Fly can't use `remix serve`

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#3147]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

`npx create-remix@latest`

Install the basic Fly template, and follow normal `flyctl launch` steps to deploy a new fly instance.

### Expected Behavior

Deployment should work without any updates to the template

### Actual Behavior

Due to [this PR](https://github.com/remix-run/remix/pull/2415) the `HOST` environment variable is now reserved by `@remix-run/dev` and `@remix-run/serve`.

This means you can no longer run `"start": "remix-serve build"` on a fly instance, as the `HOST` variable on your fly instance will cause remix-serve to fail:

`2022-05-10T05:21:22Z   [info]Error: getaddrinfo ENOTFOUND https://my-fly.fly.dev/
2022-05-10T05:21:22Z   [info]    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)`

I'm unsure if the benefit of that PR is worth this side effect of requiring everyone using Fly to migrate onto express... It should really have used `DEV_HOST` or something similar

**Comment by mcansh** [comment]
👋 did you manually set a `HOST` on fly? i just booted a fresh app and only have these set
```https://black-morning-7608.fly.dev/
FLY_ALLOC_ID=[redacted]
FLY_APP_NAME=black-morning-7608
FLY_PUBLIC_IP=[redacted]
FLY_REDIS_CACHE_URL=[redacted]
FLY_REGION=lax
FLY_VCPU_COUNT=1
FLY_VM_MEMORY_MB=256
HOME=/root
NODE_ENV=production
NODE_VERSION=16.15.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PORT=8080
SSH_DNS_SERVER=[redacted]
SSH_LISTEN=[redacted]
TERM=xterm
YARN_VERSION=1.22.18
cgroup_enable=memory
FLY_SSH=1
```

**Comment by TheRealFlyingCoder** [comment]
No, I didn't do anything other than my reproduction steps.

Fly creates a global HOST variable automatically as far as I'm aware?

**Comment by mcansh** [comment]
> No, I didn't do anything other than my reproduction steps.
> 
> 
> 
> Fly creates a global HOST variable automatically as far as I'm aware?

not that i can tell, i just made an app using the Remix App Server on fly and it deployed and booted fine. do you happen to have a fly wireguard connection set up? https://fly.io/docs/reference/private-networking/#step-by-step

**Comment by TheRealFlyingCoder** [comment]
Interesting... you might be right and it's just failing on the fresh app for another reason, I can see it try to spin up on localhost:3000 which means there's no HOST variable.

If you had a successful `flyctl deploy` off the latest create-remix template than it must work and I'm just unlucky haha

I do have a HOST set on the project i'm upgrading, and i'm trying to remember why I had to set it if it wasn't automatically created.

I'm going to close this ticket for now @mcansh, if I remember how I came to have `HOST` set i'll reopen :D
