### ISSUE TITLE
create-remix fails behind proxy

### ISSUE THREAD

**Issue by danilofes** [remix-run/remix#3159]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

Run `npx create-remix` when you are behind a corporate proxy.

### Expected Behavior

`create-remix` should work, either getting proxy config from environment variables or allowing users to pass it as a parameter.

### Actual Behavior

After answering the questions, the installation fails with the following message:

```
>npx create-remix
Need to install the following packages:
  create-remix
Ok to proceed? (y) y
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? Do you want me to run `npm install`? No
| Creating your app…request to https://codeload.github.com/remix-run/remix/tar.gz/main failed, reason: connect ETIMEDOUT 20.201.28.149:443
```

I confirmed the problem is actually proxy config by modifying the function `downloadAndExtractTarball` in `node_modules\@remix-run\dev\cli\create.js`. I just added my proxy config hard-coded with the help of `https-proxy-agent` package. With the following change create-remix succeeded.

```js
var HttpsProxyAgent = require('https-proxy-agent');

async function downloadAndExtractTarball(projectDir, url, {
  token,
  filePath
}) {
  const proxyAgent = new HttpsProxyAgent('http://my.proxy.server:3128');
  let response = await fetch__default["default"](url, token ? {
    agent: proxyAgent,
    headers: {
      Authorization: `token ${token}`
    }
  } : {
    agent: proxyAgent
  });
  // rest of the method
}
```

**Comment by rrgomide** [comment]
Please, guys. Fix this. It also happened to me. I think this is extremely important to be fixed since we're trying to incorporate Remix on enterprise-level projects. 

There are a lot of companies that use corporate proxies for security and we just can't disable it.

My solution was to scaffold a Remix project at home and bring all files to the company, which is really annoying.

**Comment by kiliman** [comment]
Yuck. It's 2022. I can't believe we're still dealing with proxy issues like it's 1999.

Shouldn't the O/S be responsible for proxy config at this point? Why does every network-capable software need to deal with proxies?

**Comment by machour** [comment]
> Please, guys. Fix this.

@rrgomide Feel free to open a PR to fix this. I don't think this is on the team priority list, having a PR will definitely help speed things up.

**Comment by brendonco** [comment]
For the meantime, you can try my starter kit by downloading the code and install. This is very basic, and add library as you go along.

https://github.com/brendonco/remix-starterkit

**Comment by rdscott-vrsk** [comment]
Still having the same issue with that nightly build.
```
❯ npx create-remix@v0.0.0-nightly-eebaa56-20221013
Need to install the following packages:
  create-remix@v0.0.0-nightly-eebaa56-20221013
Ok to proceed? (y) 
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
⠹ Creating your app…request to https://codeload.github.com/remix-run/remix/tar.gz/main failed, reason: unable to get local issuer certificate
```

**Comment by machour** [comment]
@rdscott-vrsk are you behind a proxy? This seems to be an SSL issue in your case, not a timeout

**Comment by machour** [comment]
@rdscott-vrsk Apologies, this should have been closed after this fix was released and the original issue fixed.

Could you [open a new issue](https://github.com/remix-run/remix/issues/new/choose) giving us more information about your proxy setup? I'm sure we'll sort it up!
