### ISSUE TITLE
public/build directory is getting bloated

### ISSUE THREAD

**Issue by thomasverleye** [remix-run/remix#3166]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

- Run `remix dev` and change some files.
- Multiple files get generated inside `public/build`.

### Expected Behavior

`public/build` folder should be cleared on each build.

### Actual Behavior

Multiple files get generated inside `public/build` which make the folder bloated.
See https://github.com/remix-run/remix/discussions/3156 and https://github.com/remix-run/remix/discussions/2425 for reports on this.

**Comment by machour** [comment]
Thank you for reporting this @thomasverleye, but there's already an issue filled-in! See #2432
