### ISSUE TITLE
Preloading Resources (`links` or `head` export)

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#32]
Browsers now support preloading with `<link rel="preload">` and preload headers. The browser will automatically download the resources in idle time and then use the cached resource when the user performs an action that causes the resource to be loaded for real (like clicking a link).

We'd like to take advantage of that.

When Remix navigates to a new page, it loads three categories of resources, and since multiple nested routes can match, there might be multiple resources in each category:

1. Route JavaScript Module
2. Route CSS
3. Route Data

Unlike next/gatsby, Remix doesn't automatically preload the JavaScript modules for every link on the page. We have a strong philosphy that the size of your app will not effect the footprint of any single page. Preloading all of the modules for every link on the page is just not a default behavior we want.

However, we do want to give you the ability to preload whatever resources you want to speed up the transition to that page.

Enter: `<link rel=preload>`. You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

The trouble with `<link rel=preload>` is that it's pretty useless without intimate knowledge of your build. Remix has exaclty that, so it's positioned wonderfully to expose a simple API for you to preload resources.

### The API

Like the route module `headers` and `meta` functions, you can export a `links` function to define the links you'd like to preload (or any other kind of link).

While tempting to use JSX for these links, JSX has limited static analysis (we can't know what's inside a component until it's rendered, we need to know it sooner). Because of this, the API is just objects, but the attributes are the same as `<link>`.

#### A basic preload link

You can put any kind of link you want:

```js
export function links() {
  return [
    {
      rel: "preload",
      href: "/img/some-image.jpg",
      as: "image",
    },
  ];
}
```

#### Route specific links

It's more interesting however to preload resources that Remix itself built, like route modules, css, and even data.

```js
export function links() {
  return [
    // preload just the JS modules
    {
      route: "routes/pricing",
      as: "script",
    },

    // preload script and styles
    {
      route: "routes/pricing",
      as: "script,style",
    },

    // preload script, styles, and data
    {
      route: "routes/pricing",
      as: "script,style,fetch",
    },
  ];
}
```

We use `script`, `style`, and `fetch` because that's what the link preload api uses.

If you use `script,style,fetch`, then when the user clicks the link, the transition will be immediate!

#### Preloading routes with params

```js
export function links() {
  return [
    // loading script,style is the same
    {
      route: "routes/projects/$projectId",
      as: "script,style",
    },

    // inject params to use for data
    {
      route: "routes/projects/$projectId",
      as: "script,style,fetch",
      params: { projectId: 123 },
    },
  ];
}
```

#### Preloading based on route data

Like `meta()`, the links function will receive the route data, so if you wanted to preload a bunch of data driven stuff you can:

```js
export function links({ data }) {
  return data.map((project) => ({
    route: "routes/projects/$projectId",
    as: "script,style,fetch",
    params: { projectId: project.id },
  }));
}
```

Ofc, be careful with that one, you don't want to make the user download your entire website all at once!

#### Implementation notes

- use the asset manifest to look up assets by route id
- include preload assets in the initial `partialManifest`
- include preload assets in `_remix/manifest?` requests.
- transform `fetch` into `_remix/data?` URLs, no need to cache anywhere ourselves though because that's the whole point of `<link rel=preload as=fetch>`! The browser does it.

## Perhaps just use `head`

Right now we merge `meta` down the route tree, but with `headers` we pass in the parent headers and let the child route do the merge or not.

Maybe `headers` is the right approach for everything, let the app decide to merge or not. And if so, we can combine `meta` and `links` into head, keeping api surface area of route modules a little smaller:

```tsx
interface RouteHead {
  title: string,
  meta: { [name: string]: string };
  links: HeadLink[]
}

export function head(parent: RouteHead) {
  return {
    // override title:
    title: "My title",

    // merge meta, change description
    meta: {
      ...parent.meta,
      description: "My description"
    },

    // concat links:
    links: parent.concat([
      { route: "routes/whatev", as: "script" }
    ])
  }
}
```

**Comment by CanRau** [comment]
Not sure, maybe I missed something, but it seems that the `links` export doesn't receive any (loader) data, which is kinda a pity, curious if there's a particular reason?

**Comment by jacob-ebey** [comment]
> Not sure, maybe I missed something, but it seems that the `links` export doesn't receive any (loader) data, which is kinda a pity, curious if there's a particular reason?

If we passed data we'd be introducing a waterfall where we couldn't start loading styles until after data resolves. We currently run data, styles, scripts all in parallel.

**Comment by CanRau** [comment]
Uh yeah understand, a recommended workaround? `useEffect` to manually link to styles?

**Comment by lilouartz** [comment]
Related question https://github.com/remix-run/remix/discussions/9880
