### ISSUE TITLE
Unable to deploy Remix with Nodejs 16 on Vercel

### ISSUE THREAD

**Issue by janekwunderlich** [remix-run/remix#3219]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

1. Have a project with @remix-run/vercel
2. vercel.json contains the following content: 
`{
    "build": {
      "env": {
        "ENABLE_FILE_SYSTEM_API": "1"
      }
    }
  }`
3. Deploy with Nodejs version 16 on Vercel

### Expected Behavior

It deploys and content gets properly passed to output that Vercel expects.

### Actual Behavior

<img width="1086" alt="Screenshot 2022-05-18 at 02 09 23" src="https://user-images.githubusercontent.com/41242501/168931838-a11f59a5-cf38-455c-92f2-d23c263cc0fb.png">

**Comment by machour** [comment]
Seems like we need to switch from the File System API V2 to the [Build Output API](https://vercel.com/docs/build-output-api/v3)

**Comment by silvenon** [comment]
To me it seems like you have `engines` set to v16, but your Vercel project set to v14, and that might be the reason for the failure. Is this correct?

Either way, to use v16 you'd need Build Output API. However, I'm not sure if it's necessary to enable by default it in the template, I think it makes more sense to leave it up to people to do it themselves if they need to, no?

**Comment by MichaelDeBoey** [comment]
Going to close this as the Vercel template will be officially deprecated once #5964 is released
