### ISSUE TITLE
@remix-run/cloudflare does not export installGlobals

### ISSUE THREAD

**Issue by silvenon** [remix-run/remix#3222]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

Create a Remix app by choosing "Cloudflare Pages" and import `installGlobals` from `@remix-run/cloudflare` in the test setup file, [as suggested by the documentation](https://remix.run/docs/en/v1/other-api/node#polyfills):

```js
// test/setup-test-env.ts
import { installGlobals } from '@remix-run/cloudflare'

installGlobals()
```

### Expected Behavior

Same as with `@remix-run/node`, I would expect this to install polyfills.

### Actual Behavior

This fails because `@remix-run/cloudflare` doesn't export `installGlobals`. I thought about reproducing this as a `bug-report-test.ts` PR instead, but it isn't appropriate because `installGlobals` isn't for the app itself, just for stuff like tests. You can easily verify the bug by just looking at the code.

My current workaround is to simply use `@remix-run/node` instead.

**Comment by OrToR-KJM** [comment]
2022년 5월 18일 (수) 20:50, Matija Marohnić ***@***.***>님이 작성:

**Comment by MichaelDeBoey** [comment]
@kentcdodds This to me seems more like a documentation problem? 🤔

**Comment by kentcdodds** [comment]
We need more thought on this actually because it's weird that a cloudflare project would use the node adapter at all. Currently this is just a workaround. I think we need to discuss this further as a team.

**Comment by MichaelDeBoey** [comment]
@silvenon We only have polyfills for Node as these APIs are natively available in Cloudflare/Deno

Updated the docs in #7228 to avoid confusion
