### ISSUE TITLE
Events never show to the browser when using a `ReadableStream` with the `text/event-stream` content type

### ISSUE THREAD

**Issue by hugo** [remix-run/remix#3232]
### What version of Remix are you using?

1.5.0

### Steps to Reproduce

Create an app using `@remix-run/serve` that returns a `ReadableStream` body in a `loader`, with the content-type `text/event-stream`. Send events.

On the client side connect to this endpoint using an `EventSource`.

See [this reproduction repository](https://github.com/hugo/remix-event-source-example) for a full example.

The issue appears to be compression in the Express server. If you cURL the endpoint you'll see events streaming as expected:
```
curl -N http://localhost:3000/api/events
data: asdfghjkl

data: asdfghjkl
```

This pointed me to the underlying problem. cURL doesn't do compression by default. If you enable it, with `curl --compressed` you'll also have a connection that hangs. I'm not sure _why_ but the compression middleware in Express borks streaming responses somehow.

If you edit the "@remix-run/serve" server to disable compression for "text/event-stream" content types, things work as expected:
```ts
app.use(compression({filter: (req) => req.headers['content-type']?.startsWith('text/event-stream')}))
```
(n.b. there may be a preferable way to do this, I'm not sure.)

---

While I'm here I should just add that this new streaming functionality is delightful.

### Expected Behavior

Events would start to appear via the EventSource connection.

### Actual Behavior

No events appear.

**Comment by jangerhofer** [comment]
The `express` `compression` library documentation explicitly [calls out the need to flush](https://github.com/expressjs/compression#server-sent-events) entries in an SSE stream.  I'm not sure how to square that against the `ReadableStream` `controller`'s interface, but my first thought is that a middleware in `@remix/serve` may be able to call `flush` on application code's behalf.

**Comment by jacob-ebey** [comment]
The express adapter now calls flush appropriately: https://github.com/remix-run/remix/blob/main/packages/remix-node/stream.ts#L23 

If this is still an issue, please re-open the issue or file a new one.

**Comment by vidjuheffex** [comment]
Yes but what if we're not using the Express adapter? Just using the remix default server and this issue still exists.
