### ISSUE TITLE
[Tutorial] Suggest `prisma migrate dev` to generate migration file somewhere

### ISSUE THREAD

**Issue by donrsh** [remix-run/remix#3246]
### What version of Remix are you using?

irravalent

### Steps to Reproduce

Hi. I just followed the tutoral (https://remix.run/docs/en/v1/tutorials/blog) to deploy an indie app to fly.io.

In the tutorial, there is a section on adding Post model, and it goes with `prisma db push`. After deploying, the post page shows an error since there is no migration file to be run. 

I guess there are some reasons the for the author not do so? Perhaps it would add some complexity to learn, or it gets hard to explain the seed? Anyway, it breaks the deployment, and I think at lease it should be mentioned about using `prisma migrate dev` somewhere.

### Expected Behavior

The post page should works after deployment.
See also: https://github.com/remix-run/indie-stack/issues/77

### Actual Behavior

The post page in  the tutorial (https://remix.run/docs/en/v1/tutorials/blog) breaks after deployment.

**Comment by kentcdodds** [comment]
Agreed we should do this. If anyone would like to open a PR to add something to the tutorial that would be welcome :)
