### ISSUE TITLE
Enhancement - `json<T>({})` generic

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#327]
So this one was mentioned in #138 but I can't see any comment since may or move to add it in so wanted to give it a ticket of it's own.

This is especially necessary now with Actions also using json().

Current:

`export declare function json(data: any, init?: number | ResponseInit): Response;`

Proposed:

`export declare function json<T>(data: T, init?: number | ResponseInit): Response;`

**Comment by machour** [comment]
`json()` now accepts a generic
