### ISSUE TITLE
Page scrolls back to top when changing search params

### ISSUE THREAD

**Issue by Jannis-Morgenstern** [remix-run/remix#3275]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Navigate using either a `<Link />` or the navigation function from `useNavigate` and only change the search params. Also make sure you render `<ScrollRestoration />` in `root.tsx`.

```tsx
export default function TestRoute() {
  return (
    <div>
      <div style={{height: '100vh'}} />
      <Link to="?param=test">Update Search Params</Link>
    </div>
  );
}
```

### Expected Behavior

The scroll position of the page should not be affected, since the user is not visually navigating.

### Actual Behavior

The scroll position gets restored to `0, 0`. This also happens if the location does not even change the search params - so the only thing that changes in the `location` object of react-router is the `key`.

**Comment by machour** [comment]
I'm not sure I understand your reasoning. `/` and `/?param=test` are two different urls, so the navigation should definitely happen.

**Comment by nilscox** [comment]
To avoid resetting the scroll position, you can render the `<ScrollRestoration />` component conditionally, as stated [here](https://github.com/remix-run/remix/issues/186#issuecomment-1031778216). Doing so without having to do conditional rendering is a feature requested in [this issue](https://github.com/remix-run/remix/issues/2810).

**Comment by machour** [comment]
@nilscox I think it's coming to RR, then to Remix https://twitter.com/ryanflorence/status/1527775882797907969

**Comment by Jannis-Morgenstern** [comment]
> I'm not sure I understand your reasoning. `/` and `/?param=test` are two different urls, so the navigation should definitely happen.

Sure it's a different url but the pathname is still the same. In my case I was rendering search results in the same route module that were still a major enough part of the content to get an entry in the history stack. But it looks like `<Link resetScroll={false} />` in a future release will likely solve such edge cases.

**Comment by MrSucik** [comment]
This is part of the framework now. You may use it like this:
`setSearchParams({ a: 'b' }, { preventScrollReset: true })`

**Comment by jbbalmont** [comment]
Thanks @MrSucik  I had the same bad comportment and yes it's the perfect solution !
