### ISSUE TITLE
Request body empty within the loader

### ISSUE THREAD

**Issue by Leo843** [remix-run/remix#3280]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

- Create a new remix project
- Create a `test` route that exports only a loader
```
import { json } from '@remix-run/node'
export const loader = async ({ request }) => {
  const body = await request.text()
  console.log(body)
  return json({ success: true }, 200)
}
```
- Send a GET request with some content
`curl -X GET -d '{ "content":"something" }' http://localhost:3000/test`

### Expected Behavior

The content of the request `{ "content":"something" }` should be printed in the console (server side).

### Actual Behavior

An empty string is printed in the console (server side). Furthermore, the `body` property of the `request` object within the loader is `null`.

**Comment by MichaelDeBoey** [comment]
This is expected behavior as `GET`/`HEAD` requests shouldn't have a `body` according to the spec

This was changed in #3207
