### ISSUE TITLE
Consider moving the "remix setup" script in the remix package

### ISSUE THREAD

**Issue by BenoitAverty** [remix-run/remix#330]
Hello !

I'm not sure it's doable because I don't fully understand the remix package yet, but i'm having an issue where `npm ci --production` doesn't work because the postinstall script calls `remix setup` which doesn't exist when dev dependencies are not installed.

A workaround is to move the `@remix-run/dev` package in dependencies instead of devDependencies but that makes the deployed app so much bigger.

Is there a way to solve this ? Since the `remix` binary is owned by the dev package, maybe it would require the postinstall script to become `remix-setup` instead of `remix setup`

Thanks in advance

**Comment by chaance** [comment]
Closing since we are moving away from magic imports and now have a migrate script to handle this for you 👍
