### ISSUE TITLE
useTransition for route loading is always idle

### ISSUE THREAD

**Issue by aviasd** [remix-run/remix#3300]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

Go to the root route, and place this in the Document function:
```
let transition = useTransition();
```
<img width="494" alt="image" src="https://user-images.githubusercontent.com/41818563/170150492-2892c715-9c93-4058-b197-0677d6723564.png">

And add this to the return elements:
```
<h1>{transition.state}</h1>
```
<img width="212" alt="image" src="https://user-images.githubusercontent.com/41818563/170150578-3af20dde-2544-49ac-a0ba-79728028ce4f.png">

When using a `Form` inside the root route, the transition is working and changing as expected from `idle` to `submitting` and `loading`.
But, when we move from a route to a different route using a `Link`, the transition is always `idle` without any change.

### Expected Behavior

When loading a new route, the transition state should change from `idle` to `loading`.
As can be seen in the [useTransition docs](https://remix.run/docs/en/v1/api/remix#usetransition):
<img width="436" alt="image" src="https://user-images.githubusercontent.com/41818563/170151423-65ffa60e-59a2-42f7-bdf5-fb310d6dff2d.png">

### Actual Behavior

The transition is always `idle` when using a `Link` for loading.

### Attempts to Solve
I was looking at the issues, and I found an [issue](https://github.com/remix-run/remix/issues/584) that used [NProgress](https://www.npmjs.com/package/nprogress).
So I tried to use it, but again, it worked only for `Form` submissions and not for route loadings.
You can also try [this](https://sergiodxa.com/articles/use-nprogress-in-a-remix-app) as a reproduction. 

### Comparison to Other Frameworks
In Next.js they have events for route changes: `routeChangeStart`, `routeChangeComplete`, `routeChangeError`.
There are a lot of guides like this [guide](https://levelup.gitconnected.com/improve-ux-of-your-next-js-app-in-3-minutes-with-page-loading-indicator-3a422113304d), on how to get the requested effect in Next.js, I think Remix should have too.

**Comment by aviasd** [comment]
I found the problem.
When adding a `Link` to the site, do not add `reloadDocument` if it is a UI route (only if it is a [resource route](https://remix.run/docs/en/v1/guides/resource-routes#linking-to-resource-routes)).
In the documentation for `Form`, there is an explanation on the `reloadDocument`:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/41818563/170386468-74b502c2-b01f-42bd-bdcc-df3267d0eb92.png">
So, I think that if you add the `reloadDocument` to a `Link`, the browser will handle the loading and not the JavaScript, so the `useTransition()` won't work.

There is still a small problem; we should have a way to detect the end of the loading state even when accessing the site with a URL from the browser.

**Comment by machour** [comment]
@aviasd The root problem have been identified, and I'm going to close this issue.
Feel free to reopen a bug report for the side problem you noted at the end.

**Comment by prince272** [comment]
In Next.js they have events for route changes: routeChangeStart, routeChangeComplete, routeChangeError.
There are a lot of guides like this [guide](https://levelup.gitconnected.com/improve-ux-of-your-next-js-app-in-3-minutes-with-page-loading-indicator-3a422113304d), on how to get the requested effect in Next.js, I think Remix should have too.

**Comment by machour** [comment]
@prince272 please open a [new discussion](https://github.com/remix-run/remix/discussions/new), a closed issue is not the best place to start one or to get heard :)
