### ISSUE TITLE
Recommend adding @aws section to .arc file

### ISSUE THREAD

**Issue by wildcat63** [remix-run/remix#3301]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

1. have multiple AWS profiles locally (i.e. not just a single "default" profile)
2. npx create-remix --template remix-run/grunge-stack
3. add required secrets in GitHub actions for a non-default AWS profile
4. create the "npx arc env --add --env staging ARC_APP_SECRET $(openssl rand -hex 32)" set of variables in architect
5. git push to run the GitHub action

### Expected Behavior

success

### Actual Behavior

missing SESSION_SECRET error in lambda function 

error occurs in line 7 of session.server.ts: invariant(process.env.SESSION_SECRET, "SESSION_SECRET must be set");

Note that this will be fixed if the .arc file has an @aws section 

Example:
@aws
region us-east-2
profile default

With that entry in the .arc file, it would be clear to a user what needs to be changed (i.e. change default to the desired profile)

Documentation could be amended to suggest that is where to change the region and profile if needed.

**Comment by jonparker** [comment]
Sorry, I'm very new to Remix but I am interested in getting it running with AWS & DynamoDB.

Do you mean the instructions for step 4 should be something like this: 

If you want to deploy to staging with a non-default AWS profile run:

```bash
export AWS_PROFILE=nonedefaultprofile
npx arc env --add --env staging ARC_APP_SECRET $(openssl rand -hex 32)
npx arc env --add --env staging SESSION_SECRET $(openssl rand -hex 32)
```

otherwise run:

```bash
npx arc env --add --env staging ARC_APP_SECRET $(openssl rand -hex 32)
npx arc env --add --env staging SESSION_SECRET $(openssl rand -hex 32)
```

**Comment by wildcat63** [comment]
Sorry - follow the instructions in the README.md file to the letter.  However, if you are deploying (either directly or with GitHub Actions) **and** you are deploying to a different profile, then you need an @aws section in your app.arc file that should look like the one in my comment with the exception of the profile line not being "profile default" but "profile my-other-aws-config-profile".   Note that this only works if your aws config has multiple profiles in it.  Hope that helps.

**Comment by jonparker** [comment]
Ok, thanks. I looked in https://github.com/remix-run/grunge-stack and couldn't see any app.arc file so I'm guessing it is generated by one of the setup steps.
I've never used Architect so will have to do a bit more reading to get my head around what it is doing.
