### ISSUE TITLE
Hydrate Issue when setting up an Express subapp using mountpath

### ISSUE THREAD

**Issue by christophior** [remix-run/remix#3309]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

I've created an example repo https://github.com/christophior/remix-express-mountpath-example

Steps include:
- create a basic Remix app using Express as the server
- update server.js to mount a subapp which will be used for our app
- update our remix.config.js so that our public path is updated to hit the new subpath

### Expected Behavior

Application loads when hitting subpath instead of quickly flashing rendered page followed by a white page.

### Actual Behavior

When you run the application and hit a route in the subpath, for instance `/example` or `/example/counter` you will see the page render for a split second before displaying a white page.

Currently my example repo shows the following error in the console:
```
Warning: Did not expect server HTML to contain a <script> in <html>.
```

but I have also seen the following error in another project:
```
Warning: Did not expect server HTML to contain a <div> in <div>.
```

**Comment by kiliman** [comment]
Try using `remix-mount-routes` to mount your app to a base path other than root. It ensures your routes are defined properly. 

https://github.com/kiliman/remix-mount-routes

**Comment by christophior** [comment]
Hey @kiliman thanks for the suggestion. 

I actually gave `remix-mount-rotues` a try but that is to have your routes setup to all be under a path like `/example` without having to have a high level folder in your routes but express is still running on `/`.

What i'm trying to do is have your express app running on a path like `/example` so that your routes will be setup without `/example` but they will all live under `/example` since that's where the express app is mounted.

I'll give it another shot just to verify that this doesn't accomplish what i'm trying to do but that you for the suggestion. 🙂

**Comment by kiliman** [comment]
Ok whatever you choose you need to make sure that Remix routes match the URL in the browser. That is you cannot do URL rewriting on the server.

**Comment by christophior** [comment]
Hey @kiliman, once again thanks for your help. After your comment I decided to check out the req.url that was being passed into `createRequestHandler` and as expected the url was not matching the expected url since the request was not aware of the mount path. Manually updating the url along with updating the routes using your lib helped get this working but it feels a little hacky. 


If you're interested I made a PR into the repo I made to reproduce this issue to show the changes needed to make it work. 
https://github.com/christophior/remix-express-mountpath-example/pull/1

Still interested in hearing from others if there's a better way to handle this usecase.

**Comment by chaance** [comment]
I wouldn't say this is hacky, rather it's exactly why we expose lower level APIs like `createRequestHandler` in the first place. This isn't an extremely common use-case, but it is something we want to enable if you are running your own server!
