### ISSUE TITLE
Better AppData type

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#331]
https://github.com/remix-run/remix/blob/d9e2ddd93cf5ef11325d42f3993ca013b69cabac/packages/remix-server-runtime/data.ts#L12-L15

That AppData type used as the return value of the loader (and one of the parameters of the MetaFunction) is not really correct, because that any is not really any, if you return something that it's not serializable, some examples:
- A BigInt throw the error `TypeError: Do not know how to serialize a BigInt`
- If you add a function to the returned object it's silently stripped from the response
- If you only return a function it throw `FetchError: invalid json response body at  reason: Unexpected end of JSON input`

So what that type should be is anything that it's serializable.

```ts
// copied from https://github.com/sindresorhus/type-fest/blob/1fa8872ae0bf261ec857a18b39ed9a157e320237/source/basic.d.ts#L15-L45
type JsonObject = {[Key in string]?: JsonValue};
type JsonArray = JsonValue[];
type JsonPrimitive = string | number | boolean | null;
type JsonValue = JsonPrimitive | JsonObject | JsonArray;

/**
 * Data for a route that was returned from a `loader()`.
 */
export type AppData = JsonValue;
```

This should correctly warn when trying to return a BigInt, or a function or anything that it's not serializable.

This should also prevent a case when you do `return json({ date: new Date() })` and in the component or MetaFunction you try to call methods of the Date object which are not available anymore because the Date was converted to string.

**Comment by kiliman** [comment]
I believe they are deprecating returning naked objects from loaders and actions, opting to use the `json` helper instead. So loaders should no longer use the `AppData` type.
