### ISSUE TITLE
Strange error dependent on position of CSS class

### ISSUE THREAD

**Issue by TobyEalden** [remix-run/remix#3312]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Add the tailwind class `items-center` at a specific position in the `className` and the application crashes (see attached capture in actual behaviour).

If I add the class name at a slightly different location in the `className` string, the application works as expected.

### Expected Behavior

The css class name is added and takes effect.

### Actual Behavior

See attached screencast:

https://user-images.githubusercontent.com/1628365/170638800-9f5ef50d-6da5-4b3e-95e5-9f0d1c4ca239.mov

**Comment by machour** [comment]
Hi @TobyEalden, could you setup a public repository reproducing the issue ?

**Comment by kiliman** [comment]
Also, can you include the console error message before the 'cannot initialize' error. That's typically the root cause.

**Comment by TobyEalden** [comment]
I've moved things around a bit and done some refactoring and the issue appears to have gone.

I'll close this now and re-open if it reappears.

**Comment by ngbrown** [comment]
I've had this same error too. It seems to be a caching issue with the hashed names of the built javascript modules. A hard refresh in the browser cleared it.

See https://github.com/remix-run/remix/issues/3015#issuecomment-1128233168
