### ISSUE TITLE
Live reload doesn't work with a custom Express setup

### ISSUE THREAD

**Issue by illright** [remix-run/remix#3314]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Create a new Remix app and configure a custom Express server as described in [this example](https://github.com/remix-run/remix/tree/main/examples/socket.io).

Run the development server and change some code. See the error in the browser console about not being able to connect to port 8002 and see no live reloading happen.

Terminate the development server and restart it, this time with an explicitly set environment variable, `REMIX_DEV_SERVER_WS_PORT=8002`. See no errors in the console and see live reloading happen upon code changes.

### Expected Behavior

Live reloading defaults to port 8002 and works without explicitly setting the port, even for custom Express-based server setups.

Alternatively, I'd like this behaviour to be mentioned in the README of the repos that have a custom Express server because I had to figure this out by reading the source code. 

### Actual Behavior

Live reloading requires extra steps on every run for custom Express-based server setups.

**Comment by kiliman** [comment]
I did come up with a work-around if you need random ports with the Express adapter. The trick is to set the random port *before* calling `run-p dev:*`.

There's a CLI version of `get-port` which output the random port to *stdout*.
`npm i -D get-port-cli`

I wrote a script that sets the port, before calling remix/express (had to rename it to `start:dev`).

```json
  "scripts": {
    "build": "remix build",
    "dev": "cross-env-shell NODE_ENV=development ./start-remix-dev",
    "start:dev": "run-p dev:*",
    "dev:node": "nodemon ./server.js --watch ./server.js",
    "dev:remix": "remix watch",
    "start": "cross-env NODE_ENV=production node ./server.js"
  },
```
`start-remix-dev` script
```bash
#!/usr/bin/env bash
REMIX_DEV_SERVER_WS_PORT=$(npx get-port)
echo "REMIX_DEV_SERVER_WS_PORT: $REMIX_DEV_SERVER_WS_PORT"
export REMIX_DEV_SERVER_WS_PORT
npm run start:dev
```

**Comment by illright** [comment]
Thanks for your input! I'd rather stick to a hardcoded port in `remix.config.js` for now to keep complexity out of my repo and keep it cross-platform.

```diff
 /**
  * @type {import('@remix-run/dev').AppConfig}
  */
 module.exports = {
   cacheDirectory: "./node_modules/.cache/remix",
+  devServerPort: 8002,
   ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
   serverBuildDirectory: "./server/build",
 };
```

P.S. I wish the Remix config would accept promises, then one could simply call `getPort` from inside the config and avoid the hassle with scripts.

**Comment by mcansh** [comment]
i think this is caused by our LiveReload script being inline thus not being ran through esbuild, you should also be able to use `<LiveReload port={Number(process.env.REMIX_DEV_SERVER_WS_PORT)} />` – looking into a better solution

**Comment by kiliman** [comment]
@mcansh The main reason is the Remix is setting `REMIX_DEV_SERVER_WS_PORT` with the random port, but since Express and other adapters like Netlify, run the web server portion in a separate process, it's not being read there, so it's using the default of 8002. So basically the random port thing only works on Remix App Server, where remix dev is managing both process and the variable is in scope.

The default templates for all the other adapters should be reverted to include the hard-coded `devServerPort`.

**Comment by lukasa1993** [comment]
can it be some /dec/hot_reload endpoint and long pulling instead of separate port ? would also help with docker dev setups

**Comment by PabloRosales** [comment]
I just switched to using Remix with Node/Express and also have this issue. I'm using docker-compose / Docker and expected the 8002 default to work too.

**Comment by PabloRosales** [comment]
> ```diff
> devServerPort: 8002,
> ```

Adding this solved the issue for me.

**Comment by tarngerine** [comment]
For others who stumble here: in my particular setup with docker, the port 8002 wasn't in the docker compose file as an allowed port, adding that to docker-compose.yml fixed LiveReload.

**Comment by pcattori** [comment]
Next minor release should include the new dev server https://github.com/remix-run/remix/pull/5133 under the `unstable_dev` future flag, which wires up the live reload port at build-time automatically, so you don't have to set up any env vars for it at all.
