### ISSUE TITLE
VSCode shouting: Add import from "build"

### ISSUE THREAD

**Issue by arnaudambro** [remix-run/remix#3344]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

In VSCode, try to import `json`

<img width="905" alt="in VSCode the suggestion proposes to import `json` from `build` instead of `remix`, but `build` shouldn't propose anything" src="https://user-images.githubusercontent.com/31724752/171090442-2aaec33a-76cc-4f48-b84e-fc9be5280cd0.png">

### Expected Behavior

`build` shouldn't propose anything to be imported from

### Actual Behavior

in VSCode the suggestion proposes to import `json` from `build` instead of `remix`, but `build` shouldn't propose anything

**Comment by machour** [comment]
Sounds more like and IDE configuration problem than a Remix issue to me. Any reason why you would think otherwise?
