### ISSUE TITLE
Bug: `Form`  and `useSubmit` doesn't respect HTML form grouping syntax `key[]` 

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#335]
Just raising this as a bug from the discussion last week with @ryanflorence [(Discord link)](https://discord.com/channels/770287896669978684/771068344320786452/898356207654424587)

TLDR:

FormData is converted to SearchParams:

```
  let body = new URLSearchParams();
  for (let [key, value] of formData) {
    invariant(
      typeof value === "string",
      "File inputs are not supported right now"
    );
    body.set(key, value);
  }
```
This breaks the html standard process of grouping fields with `[]` keys:

```
      <Form method="post">
        <input name="keys[]" type="input" defaultValue="1"/>
        <input name="keys[]" type="input" defaultValue="2"/>
        <input name="keys[]" type="input" defaultValue="3"/>
        <button type="submit">submit</button>
      </Form>
```

Should result in a form submission of:

```
{
   keys[]: '1',
   keys[]: '2',
   keys[]: '3'
}
```

instead we get:

```
{
   keys[]: '3'
}
```

**Comment by brophdawg11** [comment]
This looks like it is no longer an issue and was fixed in https://github.com/remix-run/remix/pull/814 - going to close this out 👍
