### ISSUE TITLE
Error. Redirects to relative path in the actions are not working, the are made absolute

### ISSUE THREAD

**Issue by luispuig** [remix-run/remix#3372]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

* Create a nested route with a button that calls the action. For instance `/admin/login`
* In the action do a redirect with a relative path, for instance `export const action = async () => redirect("relative");`
* The redirection is made to "/relative" instead of to `/admin/relative` or `/admin/login/relative`

```
import type { ActionFunction } from "@remix-run/node";
import { redirect } from "@remix-run/node";
import { Form, Link } from "@remix-run/react";

export const action: ActionFunction = async ({ request }) => {
  return redirect("relative");
};

export default function ExamplePage() {
  return (
    <>
      <Link to="relative">Go to relative with Link</Link>
      <Form method="post">
        <button type="submit">Go to relative with Action</button>
      </Form>
    </>
  );
}
```

### Expected Behavior

The redirections in an action to a relative path are made relative and not absolute.

![Jun-03-2022 00-39-41](https://user-images.githubusercontent.com/24297787/171749864-5b7f9ef6-1aa6-47de-b765-8f41dd36189f.gif)

### Actual Behavior

The redirections in an action to a relative path are made absolute.

![Jun-03-2022 00-40-05](https://user-images.githubusercontent.com/24297787/171749899-f443f5de-1881-484b-86b7-f7ea593215e8.gif)

**Comment by luispuig** [comment]
A typical use case is the `/notes/new` action, redirecting to the note page after creating the new one. `redirect(note.id)`. Using the relative way, the notes "module/folder" doesn't need to know its position in the whole tree.

**Comment by luispuig** [comment]
I found this related issue: https://github.com/remix-run/remix/issues/91

**Comment by machour** [comment]
Would you mind opening a PR with a failing test case? https://github.com/remix-run/remix/blob/dev/integration/bug-report-test.ts

**Comment by luispuig** [comment]
Created

**Comment by machour** [comment]
CI ran and it's failing, perfect 👌🏼 

Closing this issue in favor of the bug-PR
