### ISSUE TITLE
Remix Netlify starter is not live reloading.

### ISSUE THREAD

**Issue by emred2700** [remix-run/remix#3394]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

1. Create a new project with `npx create-remix@latest`
2. Choose Netlify as server/deploy target
3. Follow all the README instructions for Netlify setup
4. Run `npm run dev` and kickstart the localhost
5. Change any file in app folder
6. You will see that it's not reloading.

### Expected Behavior

It should live reload when we do changes to files and save.

### Actual Behavior

The live reload is not working. It doesn't show any errors on the console. When you reload the browser by hand you see the changes.

**Comment by kenyontu** [comment]
I had the same problem and solved it by following what [jornejongsma](https://github.com/jornejongsma) wrote here: https://github.com/remix-run/remix/issues/1601#issuecomment-1155437269

**Comment by codePassion-dot** [comment]
this still happening using create-remix@latest and netlify as deploy target, you need to refresh the webpage manually. Any update in this?

**Comment by codePassion-dot** [comment]
> I had the same problem and solved it by following what [jornejongsma](https://github.com/jornejongsma) wrote here: https://github.com/remix-run/remix/issues/1601#issuecomment-1155437269

Not working for me

**Comment by kenyontu** [comment]
Did a few tests by creating new projects with different versions:

App type: Just the basics
Deployment target: Netlify

Did a few tests with different versions:

- `create-remix@latest (1.6.1)`: Live-reload worked with no problem.
- `create-remix@1.5.1`: This is the version I the issue with, but surprisingly the live-reload worked without problem.

It seemed like a dependency problem, so I did this in the project I was having this issue:

- Deleted both the **node_modules** folder and the **package-lock.json** file
- Reinstalled the dependencies with `npm install`

With this the live-reload worked without the `devServerPort: 8002` parameter in the **remix.config.js** file.

**Comment by emred2700** [comment]
Natively it's not working but there is a workaround. Go to your `remix.config.js` file and export `devServerPort: 8002` from the module. 

And then when you first run the dev server simply hand refresh the browser first, then it will work with no problem. When you run your dev server you should not see any websocket error on your console. If your console doesn't throw any error, it means it's working :)

**Comment by kellypacker** [comment]
I tried a thousand different things and the thing that finally fixed it for me was to update `netlify-cli`:

```
npm i -g netlify-cli@latest
```
