### ISSUE TITLE
Exporting links function doesn't work in MDX files

### ISSUE THREAD

**Issue by andreiduca** [remix-run/remix#3423]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

1. create new Remix app
2. add an `.mdx` file
3. export a `links` function at the top as usual

Example: https://codesandbox.io/s/ancient-darkness-w3fvvm?file=/app/routes/special.mdx

### Expected Behavior

App should build and run successfully. Exported links should be added to the `head` for this page only.

### Actual Behavior

Build fails with the following errors:

```
ERROR: Multiple exports with the same name "links"
ERROR: The symbol "links" has already been declared
```

The reason for this failure seems to be the MDX plugin which exports a hardcoded `links` variable set to `undefined`. This prevents any MDX page from exporting its own custom `links` function: https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler/plugins/mdx.ts#L74

**Comment by machour** [comment]
Closed by #3763
