### ISSUE TITLE
[@deferred] Error on client navigation when using streaming APIs with large data payloads

### ISSUE THREAD

**Issue by itsMapleLeaf** [remix-run/remix#3452]
### What version of Remix are you using?

0.0.0-experimental-9784dd06

### Steps to Reproduce

1. Run the app:
   ```sh
   git clone https://github.com/itsMapleLeaf/remix-deferred-big-data
   cd remix-deferred-big-data
   pnpm install
   pnpm run dev
   ```
1. Open https://localhost:3000/
1. Click "another page"
1. Click "back to home"

### Expected Behavior

The app should print the number of items (1,000,000)

### Actual Behavior

The app continues to show a "Loading..." fallback, never displaying the view. In the console, there's an "Unexpected end of JSON input" error.

The JSON that's streamed down is indeed invalid:
```json
["(many entries truncated)","hey there","hey there","hey there","hey th
```
Seems like the browser is chunking it up more than expected?

I found this happening in [my personal project](https://github.com/itsMapleLeaf/anigreen) only in Firefox, but my minimal reproduction also encounters the issue in Chrome.

**Comment by machour** [comment]
Tagging @jacob-ebey which is handling deferred

**Comment by jacob-ebey** [comment]
This should be fixed in the re-implementation. There was an issue with how I was buffering (or not buffering) the stream.

**Comment by jacob-ebey** [comment]
I'm going to close this for now. If this re-surfaces please re-open this issue or create a new one.
