### ISSUE TITLE
documentation website spits out random 404

### ISSUE THREAD

**Issue by tombohub** [remix-run/remix#3456]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Reading documentation

### Expected Behavior

To read documentation

### Actual Behavior

All of a sudden giant 404 appears:

![image](https://user-images.githubusercontent.com/3029412/173253575-64651d49-1574-4539-a7ff-c4aa05d82cf6.png)

**Comment by MichaelDeBoey** [comment]
@tombohub Could you explain a bit more how this happened please?

**Comment by tombohub** [comment]
@MichaelDeBoey  I was reading documentation and it just happened on it's own. I tried multiple times and it kept happening. I was only scrolling and moving cursor if anything. I was reading this one https://remix.run/docs/en/v1/api/conventions

**Comment by machour** [comment]
@tombohub can you provide more information about your OS / Chrome version?
Does this also happens in private navigation mode? (aka, is this one of your extension causing a problem?)

**Comment by machour** [comment]
also, if you can inspect the network tab when it happens, and provide us with the "Initiator" stack trace.
I'm talking about this tab:

![Screen Shot 2022-06-13 at 9 16 55 AM](https://user-images.githubusercontent.com/304450/173310282-e10eb713-4716-4ed0-aa5f-6a16a3dc6da2.png)

**Comment by tombohub** [comment]
@machour I have I screenshot of Initiator. I don't know how to copy that:
![image](https://user-images.githubusercontent.com/3029412/173472392-d2b336cc-eb00-4639-9c0d-63ff6898d7e2.png)


I couldn't reproduce in private mode, but it was hard in normal too. It just happens randomly

**Comment by kiliman** [comment]
Yeah, that URL looks wrong. The `%3Ca%20href=` is actually `<a href=`, so somewhere the links (prefetch?) is building the URL incorrectly.

**Comment by tombohub** [comment]
I can't reproduce in incognito mode. I'll presume it's some chrome extension and close this until more info.
