### ISSUE TITLE
AWS Lambda ALB Support

### ISSUE THREAD

**Issue by parisholley** [remix-run/remix#3457]
### What version of Remix are you using?

1.4.0

### Steps to Reproduce

follow standard architect adapter settings

### Expected Behavior

works

### Actual Behavior

doesn't :)

this is what I am doing to work around:

```javascript
const {createRequestHandler} = require("@remix-run/architect");
const node = require("@remix-run/node");
const qs = require('querystring');

const handler = createRequestHandler({
  build: require("./build/remix.js"),
});

exports.handler = async (event) => {
  const response = await remixHandler({
    ...event,
    body: event.httpMethod === 'POST' ? event.body : null,
    rawPath: event.path,
    rawQueryString: qs.stringify(event.queryStringParameters, '&', '=', {encodeURIComponent: (s) => s}),
    requestContext: {
      http: {
        method: event.httpMethod
      }
    }
  });

  if (response.cookies.length) {
    response['headers']['Set-cookie'] = response.cookies[0];
  }

  return response;
};
```

**Comment by machour** [comment]
Could you describe what's not working? Is there an error when you run the app? What is it?

**Comment by parisholley** [comment]
the request payload on ALB vs Gateway is not the same, my code above is what I am using to transform it. the errors are a bunch of invalid object access (undefined/null, etc)

**Comment by ryanflorence** [comment]
I believe this would require a new adapter, we're already stretched to thin as a team on maintaining adapters, but anybody can create one!
