### ISSUE TITLE
Dependency Issues when using Vercel

### ISSUE THREAD

**Issue by royanger** [remix-run/remix#3475]
### What version of Remix are you using?

1.6.0

### Steps to Reproduce

PS F:\websites\projects> npx create-remix@latest
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y)
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
? Where would you like to create your app? destiny-watch3
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change
deployment targets. Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @vercel/node@2.1.0
npm ERR! node_modules/@vercel/node
npm ERR!   @vercel/node@"^2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @vercel/node@"^1.8.3" from @remix-run/vercel@1.6.0
npm ERR! node_modules/@remix-run/vercel
npm ERR!   @remix-run/vercel@"^1.6.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\royan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\royan\AppData\Local\npm-cache\_logs\2022-06-15T07_35_05_141Z-debug.log
Command failed: npm install

### Expected Behavior

Complete 'npm install' without errors

### Actual Behavior

See error log above

**Comment by lnittman** [comment]
seconded

**Comment by mikemadruga** [comment]
@remix-run/vercel peer dependency @vercel/node is  ^1.8.3. 

per [vercel issue 7865](https://github.com/vercel/vercel/pull/7865), node 12 support was dropped and vercel/node  version bumped to 2.0.0

temp workaround
npm install --legacy-peer-deps

**Comment by machour** [comment]
This is a known issue from vercel side: https://github.com/vercel/vercel/pull/9011/files/9b9b0f259b68a57e89ac2939a39f9519b18e903f..ab0e0aef6cfc518979720a4d5830718fc7d004c7

You can fix it by adding the @remix-run/vercel to your package, at the same versions as your other remix deps.
