### ISSUE TITLE
Bug/Feature: ESBuild Dynamic Require upgrade

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#348]
Coming from [this chat](https://discord.com/channels/770287896669978684/771068344320786452/903090207891529799) with @ryanflorence on Discord. ESBuild isn't set up to handle dynamic requires in npm packages.

The ESBuild dependancy is a little out of date to start with and could use an update.

Assuming that doesn't fix the following issue (I patched and it didn't seem to work), a simple reproduction step is:

1. `npm init remix`
2. `npm install @slack/web-api`
3. Add to the index route:

```
import { WebClient } from "@slack/web-api";

export default function Index() {
  const web = new WebClient();

  return (
    <div style={{ textAlign: "center", padding: 20 }}>
    </div>
  );
}
```

ESBuild probably just needs a config tweak or something after the update to accept the dynamic requires?

**Comment by chaance** [comment]
I believe this should be resolved in recent updates, but please let me know if not and I can take a look with a minimal reproduction!
