### ISSUE TITLE
Referer header not set correctly for internal routing when JS is enabled

### ISSUE THREAD

**Issue by kenneth-gray** [remix-run/remix#3510]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Create 2 routes:
- page-1.tsx
- page-2.tsx

Add a link from page-1 to page-2 and make sure that page-2 either logs or displays the referer header. Select the page-2 link from page-1 when JS is enabled.

### Expected Behavior

The referer header should be set to the URL of page-1.

### Actual Behavior

The referer header will be set to the URL of page-2.

When JS is disabled the behaviour is as expected.

**Comment by brian-dlee** [comment]
I can confirm we are seeing this happen in 1.6.5. I created this project to illustrate a pattern on how to implement this functionality despite the existing issue. I'm not sure if this package will be widely used or anything, but if anything it's a place for others to look at so we can avoid the whole wheel re-invention.

**Comment by brian-dlee** [comment]
Also, I came across a note where the remix folk described wanting to know use cases for `useLocation` as it implied custom routing. In my case, the solution relies on `useLocation` but I wouldn't say it does any kind of custom routing. Food for thought for anyone that comes across this.

**Comment by machour** [comment]
@kenneth-gray could you check if this still happens on Remix 1.11.1 ?
If it's the case, please provide a repository reproducing the problem 🙏🏼

**Comment by kenneth-gray** [comment]
Fixed in 1.11.1, thanks!
