### ISSUE TITLE
fetcher.load not working in {$id folder}->index.ts (/api/client/0)

### ISSUE THREAD

**Issue by edouardglanum** [remix-run/remix#3519]
### What version of Remix are you using?

1.6.0

### Steps to Reproduce

1: Having API route like '/api/client/0' returning json()
![Screenshot_1](https://user-images.githubusercontent.com/60732294/174589278-6974b83f-3d2e-4a9c-8e23-5f07c3e1dd8b.jpg)
2: Request with useFetcher
```
    const fetcher = useFetcher<any>()
    const [url, setUrl] = useState<string>('/api/client/0')
    useEffect(() => {
        fetcher.load(url)
    }, [tab])
    useEffect(() => {
        console.log(fetcher)
    }, [fetcher])
```
   3: Did not work.
   
   It's not understandable since I have another API route returning similar json and working fine. Seems to be a route problem.
   Everything works but not this actual URL.

### Expected Behavior

Having fetcher.data with data of /api/client/0 screenshot

### Actual Behavior

Fetcher is loading and then is done, but returns undefined data while the API route returns well json.

**Comment by edouardglanum** [comment]
I just found the solution, it's very tricky:

Accessing manually the route works in thoses cases:
 - /api/client/{folder $id}/index.ts
 - /api/client/{file $id.ts}
  
useFetcher does not work in the following case : 
 - /api/client/{folder $id}/index.ts

**Comment by machour** [comment]
It seems to me like you were missing the `?index` on the url called by fetcher:
  https://remix.run/docs/en/v1/guides/routing#what-is-the-index-query-param

If that's not it, please open a new issue provide a codesandbox reproducing this problem on the latest remix version 🙏🏼
