### ISSUE TITLE
GET /__vite_ping 404 - - x.xxx ms repeated in terminal console

### ISSUE THREAD

**Issue by tombohub** [remix-run/remix#3580]
### What version of Remix are you using?

1.6.1

### Steps to Reproduce

1. run `yarn create remix`
2. follow instructions to install base template, typescript on fly.io
3. run `yarn dev`
4. check the console terminal

### Expected Behavior

In terminal to display only:

```
yarn run v1.22.18
$ remix dev
Watching Remix app in development mode...
💿 Built in 389ms
Remix App Server started at http://localhost:3000 (http://192.168.2.39:3000)
```

### Actual Behavior

It keeps writing line `GET /__vite_ping 404 - - 3.195 ms` : 

```
yarn run v1.22.18
$ remix dev
Watching Remix app in development mode...
💿 Built in 389ms
Remix App Server started at http://localhost:3000 (http://192.168.2.39:3000)
GET /__vite_ping 404 - - 28.300 ms
GET /__vite_ping 404 - - 3.865 ms
GET /__vite_ping 404 - - 2.731 ms
GET /__vite_ping 404 - - 2.813 ms
GET /__vite_ping 404 - - 3.887 ms
GET / 200 - - 7.292 ms
GET /__vite_ping 404 - - 3.195 ms
GET /__vite_ping 404 - - 4.882 ms
GET /__vite_ping 404 - - 2.748 ms
GET /__vite_ping 404 - - 3.011 ms
GET /__vite_ping 404 - - 2.687 ms
GET /__vite_ping 404 - - 2.122 ms
GET /__vite_ping 404 - - 2.132 ms
GET /__vite_ping 404 - - 2.331 ms
GET /__vite_ping 404 - - 2.964 ms
GET /__vite_ping 404 - - 2.731 ms
GET /__vite_ping 404 - - 1.763 ms
GET /__vite_ping 404 - - 2.996 ms
GET /__vite_ping 404 - - 2.563 ms
GET /__vite_ping 404 - - 2.338 ms
....
```

![image](https://user-images.githubusercontent.com/3029412/175823346-a7fa2e66-ee8c-4707-a218-a6240f98aa48.png)

**Comment by sergiodxa** [comment]
Remix doesn’t use Vite, so you probably have a tab with anothwr project using Vite open which is doing the request, or you have a service worker which does the same thing.

**Comment by tombohub** [comment]
yes, now it's fine, thank you
