### ISSUE TITLE
Babel config

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#36]
Open up and use an application babel config, apps will just need to make sure to include our preset:

```js
{
  "presets": [
    "@remix-run/core/babel",
  ]
}
```

**Comment by chaance** [comment]
Closing for now since I don't think we have any intention of installing babel anytime soon, but feel free to reopen if I'm wrong!

**Comment by victordidenko** [comment]
Why not? There are things, that heavily depends on Babel.
Maybe this could be covered by #717 by adding possibility to add `esbuild-plugin-babel` manually?
