### ISSUE TITLE
[enhancement] Edge case for loader refetch errors (offline mode?)

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#360]
Ok, this one's tricky and I'm not sure what do about it. I got an email from one of my users with a situation they ran into on my site:

> I just recently pulled up a ton of blog posts to read offline on a flight which worked just fine...until I scrolled to the bottom of the page. Here is an example of the error:
> 
> 500 - Oh no, something did not go well.
> "/blog/how-to-give-rendering-control-to-users-with-prop-getters" is currently not working. So sorry.
> 
> Context:
> - I loaded up a bunch of blog posts pre-flight in Safari
> - Turned off Wifi
> - Verified I still could access the previously loaded page
> - Closed laptop and awaited flight
> - Aboard flight started reading said posts
> - Reads to the bottom...and...
> - Haha! No more blog post for you! Look at this nice error page instead!!

Here's what I said to them:

> The reason this happens is because when you reach the bottom of the article it marks it as "read" in the database. This is a mutation and Remix automatically refetches all data on the page to keep everything up-to-date (like the team rankings which changed because of your read). When that data fetch fails, remix renders my error boundaries which gives you the Kent grimacing 😬 face 😅

Like I said, I'm not sure what to do about this, but I *think* what I *might* want is the ability to say: "go ahead and refetch the data, but if it fails, then ignore it" ?? maybe? Definitely open to other ideas here. I'm not sure whether a change is needed in remix...

Thinking about the use case more holistically, if I wanted to build an offline supported version of my app, I would need some way to tell Remix to not attempt to make network requests when the user is offline.

**Comment by justrhysism** [comment]
Are there any plans for Remix apps to leverage Service Workers? This case could then be handled by responding to the app that the request was received and `200 All Good`, while the SW deals with the reconnection/resending in the background.

**Comment by mattveraldi** [comment]
Are there any updates on this issue? I am studying remix, and my only concern so far is that it might not be suitable for PWA apps that needs some offline functionalities (yet).

**Comment by manV** [comment]
I am using fetcher to load data periodically on a page to refresh it with latest information from the server. I am not sure how to handle network errors in this case. Currently if the browser goes offline while refresh is in progress, the error thrown is caught by error boundary, but in this case I would still like to show user the stale data. I am not sure if I am doing things in the "Remix way" so apologies in advance. Thanks.
