### ISSUE TITLE
wrong `globals.d.ts` path in `remix.env.d.ts` @remix-run/node 1.6.2

### ISSUE THREAD

**Issue by JHSeo-git** [remix-run/remix#3606]
### What version of Remix are you using?

1.6.2

### Steps to Reproduce

1. Run `npx create-remix@latest`.
2. Select `Just the basics` / `Vercel` / `TypeScript`.
3. Install dependencies. (`npm` or `yarn`)
4. see `remix.env.d.ts` file.

### Expected Behavior

```ts
/// <reference types="@remix-run/dev" />
/// <reference types="@remix-run/node/globals" />
```

no error in this `remix.env.d.ts`.

### Actual Behavior

but not found `"@remix-run/node/globals"`

![image](https://user-images.githubusercontent.com/61136724/176467623-b52ea5f9-90da-4c70-aaae-19beb9fc30e0.png)

To avoid the error, I tried to something:

**1. change path**
@remix-run/node/globals -> @remix-run/node/dists/globals
```ts
/// <reference types="@remix-run/dev" />
/// <reference types="@remix-run/node/dists/globals" />
```

**2. or typesVersions in package.json**
```
// @remix-run/node/package.json
{
  // ...
  "typesVersions": {
    "*": {
      "globals": ["./dist/globals.d.ts"]
    }
  },
  // ...
}
```

**Comment by brophdawg11** [comment]
Closing this out as this should be fixed in `1.6.3` - please re-open if you still run into issues!

**Comment by david-crespo** [comment]
I'm getting this bug in a slightly different context: my Vitest [setup file](https://vitest.dev/config/#setupfiles):

```ts
import { installGlobals } from '@remix-run/node/globals'

installGlobals()
```

Here's the error I'm getting.

```
Error: [vite-node] Failed to load @remix-run/node/globals
```

Just as above, it worked in 1.6.1 and broke in 1.6.2, and changing it to `@remix-run/node/dist/globals` works as a workaround.

**Comment by brophdawg11** [comment]
@david-crespo `installGlobals` is re-exported at the root do I don't think you should need the deep import.  Does `import { installGlobals } from '@remix-run/node' work for you?

**Comment by david-crespo** [comment]
Yes it does! Whoops!
