### ISSUE TITLE
Why every library causes: "Cannot initialize 'routeModules'"

### ISSUE THREAD

**Issue by liron-navon** [remix-run/remix#3608]
### What version of Remix are you using?

1.6

### Steps to Reproduce

Import frontend libraries like:
```
import WalletConnectProvider from "@walletconnect/web3-provider";
```

and remix goes crazy... this happens with every second library, not sure why this happens, but it's clearly a frontend library

I understand remix doesn't remove frontend code when doing the backend stuff, but you should provide a way to have client-only code somehow, not "initialize" function is needed here, just the import makes the app fail.

https://remix.run/docs/en/v1/guides/constraints

### Expected Behavior

should work..

### Actual Behavior

getting:
Error: Cannot initialize 'routeModules'. This normally occurs when you have server code in your client modules.

**Comment by kiliman** [comment]
Wallet Connect only runs in the browser, so it's causing issues since Remix renders both on server and client. You need to put your wallet connect code in a `*.client` file.

I have a codesandbox showing how to use this.

https://codesandbox.io/s/remix-walletconnect-h2l5so

**Comment by kiliman** [comment]
Yes https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles

**Comment by machour** [comment]
Closing this as it is a documented gotcha.

**Comment by ray-bun** [comment]
@kiliman any change you can show an example with this https://developers.ledger.com/docs/transport/web-hid-usb/ ? thanks
