### ISSUE TITLE
Disparity in HTTP referer header between <form> and <Form>

### ISSUE THREAD

**Issue by AustinGil** [remix-run/remix#3612]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

Create a <form> whose action submits to a resource route. Something like 

```html
<form action="/resource/route">
  <button>Submit</button>
</form>
```

In the resource route, read the `referer` header:

```js
export async function action({ request }) {
  console.log(request.headers.get('referer'));
  return null
}
```

Try submitting the form and reading the header.

Then change the <form> to <Form> and submit again.

The referer changes from the page containing the form to the page the form is submitting to.

The default form behavior is helpful for something like this: `return redirect(request.headers.get('referer'), 303);`

### Expected Behavior

The referer should be the same as the URL containing the form, as that is there the request originated from.

### Actual Behavior

The referer (when using <Form>) is set to the form's action.

**Comment by AustinGil** [comment]
Although this issue is related to forms, it looks like the same was already reported relating to navigation

https://github.com/remix-run/remix/issues/3510

**Comment by machour** [comment]
There's already a bug-PR reproducing this issue : #2110

**Comment by machour** [comment]
Fyi, this will be fixed when we're done remixing the react router. See Ryan's comment on #2110.

Keeping this bug reports open to avoid duplicates until then.

**Comment by machour** [comment]
Should have been fixed by now, please re-open if you're still seeing this disparity.
