### ISSUE TITLE
Server side redirects restore scroll position of the previous page

### ISSUE THREAD

**Issue by DKeen0123** [remix-run/remix#3617]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

if you are at the top of a page, say the home page `/`, and follow a link to another page such as `login`, scroll down that page, and then submit an action which redirects the user, such as logging in, using the remix redirect function from `@remix-run/node`, then the user ends up back on the home page but scrolled down to where they were on the `login` page that initiated the redirect.

repliocateit by cloning my repo here , based off the indie stack: https://github.com/DKeen0123/remix-redirect-scroll-restoration, go to the home page, ensure you are at the top of the page and click sign up. Scroll down to the sign up form and sign up. You'll be redirected to the home page but be scrolled down the page.

### Expected Behavior

When redirected, I should be scrolled to wherever I was when I left the original page

### Actual Behavior

When redirected, I am scrolled down to wherever I was on the page that initiated the redirect:

I start at the top of the home page, which for the sake of this demo has a fixed height of 4000px to make it scrollable:
![image](https://user-images.githubusercontent.com/16704395/176652799-34bcf927-61d8-43c3-94fa-0de640d4c91d.png)
I click the sign up cta which takes me to `/join`. For the sake of this demo, I have forced the page to be 3000px high, and put the form at the bottom:
![image](https://user-images.githubusercontent.com/16704395/176653034-ec5ef749-4bbc-41eb-8193-5260f0d20a71.png)
Once I create an account, I will be scrolled down the home page, rather than at the top where I started:
![image](https://user-images.githubusercontent.com/16704395/176653182-61b74d1b-0ac0-4f4f-ae15-d8aa1d491d04.png)

**Comment by machour** [comment]
Related to #2263

**Comment by Mat-moran** [comment]
Hi, I am facing the same issue, any update on that?

**Comment by DKeen0123** [comment]
Hi - can I get an update on if this is on the Remix teams radar?

We use server side redirects quite often, and being redirected to a page scrolled half-way down is really weird behaviour for our users!

**Comment by SleeplessByte** [comment]
This even happens if you redirect to a never-visited page. 

Same reproduction steps: `<Form method="post" />` with or without server redirect.

**Comment by brophdawg11** [comment]
This is no longer an issue in the current Remix since we put it on top of the new React Router code which fixed a bunch of underlying scroll restoration issues.

> When redirected, I should be scrolled to wherever I was when I left the original page

Just wanted to clarify this is not what will happen - scroll restoration only _restores_ scroll when you go to a previously seen location.  And then it _resets_ scroll on _new_ locations.  When redirecting in an action, you're redirecting to a new location so scroll will reset back to the top.
