### ISSUE TITLE
Access denied for postgres user in Blues stack on fresh install.

### ISSUE THREAD

**Issue by wking-io** [remix-run/remix#3620]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

- Install remix blues stack using `npx create-remix` with the blues stack.
- Go through README steps
- Run `npm run docker`
- Run `npm run setup`

NOTE: I am using a M1 mac

### Expected Behavior

Command to run and Prisma database to be setup

### Actual Behavior

Get this error

> Error: P1010: User `postgres` was denied access on the database `postgres.public`

**Comment by wking-io** [comment]
See issue over at Blues stack repo sorry!

**Comment by mhchen** [comment]
Link to other issue for people who are here looking for it: https://github.com/remix-run/blues-stack/issues/49
