### ISSUE TITLE
Password prompt stalls deployment process

### ISSUE THREAD

**Issue by nuliknol** [remix-run/remix#3622]
### What version of Remix are you using?

1.3.3 (AppImage)

### Steps to Reproduce

Depoly a contract

### Expected Behavior

success

### Actual Behavior

When using Deploy & Run transaction plugin , when password dialog pops up, the "Ok" button doesn't work, it seems to be disconnected from the app, so no matter how much I click it, it doesn't do anything.

[
![remix-passwd-prompt](https://user-images.githubusercontent.com/1125368/176717943-611f74e0-9d26-42f8-8dfc-8ae0433116e2.png)
]

**Comment by sergiodxa** [comment]
This repository is for remix.run the web framework not Remix IDE the crypto thing.
