### ISSUE TITLE
Typechecking `tsc` , after running `npm run build` fails with `Error TS2691: An import path cannot end with a '.d.ts' extension`

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#3624]
### What version of Remix are you using?
1.6.3

### Steps to Reproduce
1. Run `npm run build`
2. Run `npm run typescript-typecheck` (which is essentially just running `tsc` command from typescript

Codesanbox of app (click + button to open new terminal tab session):
- https://stackblitz.com/edit/node-uegzhy?file=package.json

![CleanShot 2022-06-30 at 09 45 58@2x](https://user-images.githubusercontent.com/6743796/176733741-c4159758-c3d6-4a39-9286-5866f990a707.png)
![CleanShot 2022-06-30 at 09 54 03@2x](https://user-images.githubusercontent.com/6743796/176734333-a635aa10-9c07-4884-b41b-a7292b7e8fa5.png)

### Expected Behavior
`tsc` command should not fail. 
Maybe there is another recommended way we can run the type check?

### Actual Behavior
`tsc` command should not fail

**Comment by MichaelDeBoey** [comment]
Fixed by #3623
