### ISSUE TITLE
useLoaderData doesn't return Set data type

### ISSUE THREAD

**Issue by insectula** [remix-run/remix#3627]
### What version of Remix are you using?

1.6.3  (JavaScript)

### Steps to Reproduce

return set from loader
```
export const loader = () => {
  const data = new Set([1, 2, 3]);
  console.log('Loader:',  data);
    return data;
}
```
then get it in a route
```
export default function () {
  data = useLoaderData();
  console.log('Function:',  data);
    return null;
}
```

### Expected Behavior

I expected to have a Set passed as is
with the console output  like
```
Loader: Set(3) { 1, 2, 3 }
Function: Set(3) { 1, 2, 3 }
```

### Actual Behavior

but the Set becomes an empty object
```
Loader: Set(3) { 1, 2, 3 }
Function: {}
```

**Comment by insectula** [comment]
yet I use Array.from(new Set()) as a workaround

**Comment by Shumuu** [comment]
I am guessing this might be due to https://remix.run/docs/en/v1/guides/data-loading#gotchas

Since you can't properly serialize a `Set`, it'll turn into an empty object. You might want to create an array from the `Set`, send it to the client and create a new `Set` from it

**Comment by machour** [comment]
@Shumuu is correct on this one, you cannot send a Set as the json serialization won't work
