### ISSUE TITLE
strange action behaviour

### ISSUE THREAD

**Issue by JakovGlavac** [remix-run/remix#3650]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

```tsx
<fetcher.Form
  method="post"
  action="/notifications/"
>
  <input name="redirect" value={el.link} hidden />
  <input name="id" value={el.id} hidden />
  <button type="submit">klik</button>
</fetcher.Form>
```

the same result when using `action="/notifications"` and `action="/notifications/"`

Folder structure:
![image](https://user-images.githubusercontent.com/34971091/177167340-8fb65b62-1ca3-496d-ae53-a53d232631ea.png)

### Expected Behavior

It should make a post request to /notifications
Like it does when i have file called notifications.tsx in routes
![image](https://user-images.githubusercontent.com/34971091/177168051-15684da2-9799-4620-b2ff-cd8314b734d2.png)

![image](https://user-images.githubusercontent.com/34971091/177167983-79f69756-6962-4ee0-8b18-0fadee499b14.png)

### Actual Behavior

Returns: 405
![image](https://user-images.githubusercontent.com/34971091/177167401-c0705e7f-4e7e-4df8-b22a-e8d25b7dafab.png)

**Comment by JakovGlavac** [comment]
Yeah this works.
Thanks

**Comment by juniorforlife** [comment]
@JakovGlavac I face the same problem where I have to add `?index` to the action eg: `/register?index`. Why doesn't `/register` work?
