### ISSUE TITLE
Missing Cloudflare globals definitions

### ISSUE THREAD

**Issue by sergiocarneiro** [remix-run/remix#3669]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

1. `npx create-remix@latest`
   * Just the basics
   * Cloudflare Pages
   * Typescript
   * Install
2. Open `remix.env.d.ts`
3. The editor should highlight the problem with `/// <reference types="@remix-run/cloudflare/globals" />`

### Expected Behavior

Types are referenced with no issues.

### Actual Behavior

<img width="607" alt="image" src="https://user-images.githubusercontent.com/3398251/177795435-5e3ab01b-2149-4a7d-8391-471c8393baa3.png">

**Comment by ljwh** [comment]
```javascript
<reference types="@remix-run/cloudflare/dist/globals"
```
Add **dist**/globals works for me
