### ISSUE TITLE
Incorrect sourceMappingURL added to generated server bundle prevents debugging

### ISSUE THREAD

**Issue by kiliman** [remix-run/remix#367]
Updated my gist with patch to use `sourcemap: 'inline'`. This solves the issue.

Here's the gist:
https://gist.github.com/kiliman/a9d7c874af03369a1d105a92560d89e9

**Comment by ryanflorence** [comment]
I've also confirmed it's using the remix `publicPath` to generate that URL, which isn't right, but since we don't get to configure the path in esbuild (we just say `sourcemap: true`) we might want to either:

1. use "inline" for the server build
2. use "external" for the server build and then append the URL ourselves

Or there's some configuration that I'm unaware of that we're doing wrong in our esbuild server bundle.

**Comment by zigomir** [comment]
Pasting this here for context: https://github.com/evanw/esbuild/issues/1290

Changing `sourcemap: true,` to `sourcemap: 'inline', in `createServerBuild` works. If I open PR for it is it something you'd accept?

**Comment by kiliman** [comment]
I've updated my gist to add a patch for sourcemap to inline. Hopefully the PR will make it in.

https://gist.github.com/kiliman/a9d7c874af03369a1d105a92560d89e9

**Comment by kiliman** [comment]
Yes, PR #2065 fixes this as well as enables breakpoint debugging without any hacks.

**Comment by connor4312** [comment]
By the way, you can also make breakpoints work by doing something like this in your launch.json:

```
    {
      "type": "node-terminal",
      "request": "launch",
      "name": "Launch",
      "command": "npm run dev:remix",
      "skipFiles": ["<node_internals>/**"],
      "sourceMapPathOverrides": {
        "route:*": "*" // <-- fix up the paths, so route:<path> just becomes <path>
      },
      "outFiles": ["${workspaceFolder}/build/**/*.js"]
    }
```

**Comment by heiso** [comment]
Hi there ! Thanks for the amazing work.

Where can i find the documentation about enabling sourcemaps in dev mode ?

**Comment by kiliman** [comment]
@heiso Are you on the latest Remix? Sourcemaps should automatically generate in development. You have to opt-in to sourcemaps for production `remix build --sourcemap`
