### ISSUE TITLE
[Docs]: Broken links

### ISSUE THREAD

**Issue by AlonGvili** [remix-run/remix#368]
https://github.com/remix-run/remix/blob/e6e6e1cd6ad545aaf39c7780d58f3293fdfe8682/docs/index.md?plain=1#L12
https://github.com/remix-run/remix/blob/e6e6e1cd6ad545aaf39c7780d58f3293fdfe8682/docs/index.md?plain=1#L13

**Comment by machour** [comment]
This is an old MD file that should be removed.
