### ISSUE TITLE
remix build doesn't create /build folder and remix-serve build fails

### ISSUE THREAD

**Issue by andrecasal** [remix-run/remix#3682]
### What version of Remix are you using?

1.6.4

### Steps to Reproduce

1. Run `npx create-remix@latest`
2. Run `npx remix build`
3. Run `npx remix-serve build`

### Expected Behavior

Expected `remix build` to create the `/build` and the `/public/build` folders.

### Actual Behavior

Actual: `remix build` does not create the `/build` folder and `remix-serve build` errors:
`Error: Cannot find module '/Users/.../repositoryName/build'`

**Comment by kiliman** [comment]
Hmm.. well I can't repro it. What's the output of `rmx remix build`?

**Comment by andrecasal** [comment]
Here's the output:
<img width="1068" alt="Screen Shot 2022-07-08 at 15 55 02" src="https://user-images.githubusercontent.com/22457463/178017478-e56468e1-b4c5-474d-b33e-96b8a1d37f26.png">

**Comment by mcansh** [comment]
interesting... I'm also unable to reproduce on 1.6.4 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/11698668/178021874-cc9f0e2b-46fc-4ff0-a8ba-f075f8539544.png">


did you pick `Remix App Server`, or a different something else?

**Comment by andrecasal** [comment]
I picked Vercel on the initial installation. That's what I'm using on the main repo. You think that could change anything?

Also, uncommenting `serverBuildPath: "build/index.js",` on `remix.config.js` forced `npx remix build` to create the `/build` folder. However, `npx remix-serve build` still errors with:
```
/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/server-runtime/dist/routes.js:18
  return Object.entries(manifest).filter(([, route]) => route.parentId === parentId).map(([id, route]) => ({ ...route,
                ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.createRoutes (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/server-runtime/dist/routes.js:18:17)
    at Object.createRequestHandler (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/server-runtime/dist/server.js:26:25)
    at Object.createRequestHandler (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/express/dist/server.js:34:28)
    at Object.createApp (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/serve/dist/index.js:38:50)
    at Object.<anonymous> (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/serve/dist/cli.js:52:17)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

 *  The terminal process "/usr/local/bin/zsh '-c', 'npm run start'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by mcansh** [comment]
ah okay, yea that does make a difference :)

in the vercel template, we have `server` and `serverBuildTarget` so we take the server.ts file and compiled build, bundle them together, and throw it in `api/index.js`, which is unrunnable outside of vercel.

> The weird thing is that, even with my Vercel config, npx remix build and npx remix-serve build was working before

hm, yeah that is weird

**Comment by mcansh** [comment]
i haven't tried to deploy this, but something like this may work in your remix.config.js

```diff
- serverBuildTarget: "vercel",
+ serverBuildTarget: !process.env.VERCEL ? undefined : "vercel",
```

if i remember correctly, vercel will set the `VERCEL` environment variable for you when building

**Comment by andrecasal** [comment]
Yeah, I just figured that out. Does that mean I can't run a production build locally by running `npx remix-serve api`?

It does fail.

**Comment by andrecasal** [comment]
I tried it, but it gives out the same error.

If I understand correctly, if I'm not using Vercel-specific stuff, all the Vercel template does is point the build from `/build` to `/api`. That explains having the exact same error with `serverBuildTarget: !process.env.VERCEL ? undefined : "vercel",` and `npx remix-serve build`.

**Comment by andrecasal** [comment]
The output files `/api/index.js` and `/build/index.js` are exactly the same.

**Comment by mcansh** [comment]
sorry, updated my above diff and confirmed it works with `vc dev` and `vc deploy`

**Comment by mcansh** [comment]
`vercel dev` sets `VERCEL` to `1` and `remix dev` (maybe vercel does too) will set `NODE_ENV` to `development` so we can use either check to skip the custom server file.

`remix build` will set `NODE_ENV` to `production` so the custom server is included.

if you ran `vercel dev` and ran `remix-serve ./api/index` it would work with just the NODE_ENV check, but not after a build.

you could also just swap the NODE_ENV check for the VERCEL check and be alright too i think

**Comment by andrecasal** [comment]
> `remix build` will set `NODE_ENV` to `production` so the custom server is included.

Ah, the `server.js` can only be included in Vercel, so we need to make sure it's excluded when creating the production build locally.
