### ISSUE TITLE
Routes match error in Safari

### ISSUE THREAD

**Issue by dawiidio** [remix-run/remix#3695]
### What version of Remix are you using?

1.1.1

### Steps to Reproduce

1. create project based on `@remix-run/node`
2. create route with dynamic match (for example: `/blog/post/$slug`)
3. enter `/blog/post/any-post` page on iPad Safari (605.1.15) 
4. in server console you should see `GET /blog/post/any-post?_data=routes%2Fblog%2Fpost%2F%24slug`

### Expected Behavior

I want to see actual page under route `/blog/post/any-post`

### Actual Behavior

once you've entered page in Safari you will see error: `The string did not match expected pattern.`

**Comment by narutosstudent** [comment]
@dawiidio Could you try with the latest version of Remix?

**Comment by machour** [comment]
Closing as no feedback was provided.
If this is still a issue for you, please open a new issue and provide a repository reproducing the problem to help the team.
