### ISSUE TITLE
<PrefetchPageLinks /> crashes the page when there is a query param in the URL

### ISSUE THREAD

**Issue by samstanding** [remix-run/remix#3724]
### What version of Remix are you using?

1.6.1

### Steps to Reproduce

1. Add a `<PrefetchPageLinks />` to an active route.
2. Add some query params to your URL ie `?query` and hit return to reload the page
3. Observe: 
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/33382227/178798464-aeb1e49b-5cbd-442e-86ac-a7269ff08e49.png">

### Expected Behavior

I would expect the page to load, unless there's some behavior with PrefetchPageLinks I was not aware of where it can't be rendered on a page with query params. 

### Actual Behavior

The page crashes and we see the following `window is not defined error`
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/33382227/178799060-b7f20d39-4449-45df-b818-b1580d2c6b91.png">

**Comment by mcansh** [comment]
tracking this internally now, and I plan to look into it today!

**Comment by samstanding** [comment]
Hey @mcansh any updates? Is it possible to use my PR as a stopgap so that we can use PrefetchPageLinks if there's a query param?

**Comment by mcansh** [comment]
@samstanding not currently, do you have a use case where you can't conditionally render `<PrefetchPageLinks>`?

**Comment by samstanding** [comment]
> @samstanding not currently, do you have a use case where you can't conditionally render `<PrefetchPageLinks>`?
> 
> skipping them during the server render and applying them during hydration would more than likely cause a hydration warning

@mcansh I can conditionally render it but we're using it to help a slow endpoint so it would be preferred to use it across the board. Right I'm doing something like `{!location.search && <PrefetchPageLinks />}`

**Comment by danielgangl** [comment]
This is still broken for me. Any updates?

**Comment by danielgangl** [comment]
using 'typeof document !== "undefined"' now to conditionally render the PrefetchPageLinks component as a workaround

**Comment by brophdawg11** [comment]
I don't think this is an issue anymore since `1.10.0` and the incorporation of `RouterProvider` from `react-router-dom`
