### ISSUE TITLE
`Error: [vite-node] Failed to load @remix-run/node/globals` when trying to run tests

### ISSUE THREAD

**Issue by jjhiggz** [remix-run/remix#3749]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

1. Have `"@remix-run/node": "1.6.5"` set in your package.json dependencies
2. Have `"vitest": "^0.12.8"` set in your package.json dependencies
3. Run `npx vitest`

### Expected Behavior

runs tests

### Actual Behavior

Will throw error `Error: [vite-node] Failed to load @remix-run/node/globals`

When I change the version back down to `1.6.0` it is no longer a problem. It may be a reccurence of a Vitest issue as per [this issue](https://github.com/vitest-dev/vitest/issues/1286).

**Comment by iamvictorli** [comment]
I ran into this issue as well with vitest, and fixed by removing `/globals` from `@remix-run/node/globals`
Before `import { installGlobals } from '@remix-run/node/globals'`
After `import { installGlobals } from '@remix-run/node'`
https://remix.run/docs/en/v1/other-api/node

**Comment by jjhiggz** [comment]
@iamvictorli Perfect!
![image](https://user-images.githubusercontent.com/59105254/179322575-ff884822-df2a-40c9-8598-f0ec497ab977.png)
