### ISSUE TITLE
Incorrect documentation for `filter` on `uploadHandler`

### ISSUE THREAD

**Issue by dcramer** [remix-run/remix#3756]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Previously `filter` had `mimetype` in the params, and the documentation still reflects this. However the new parameter is named `contentType`.

https://remix.run/docs/en/v1/api/remix#unstable_createfileuploadhandler-node

**Comment by kiliman** [comment]
@dcramer feel free to submit a documentation PR. Make sure you're on the `main` branch.
