### ISSUE TITLE
Type error when inferring the type of `ReadonlyArray`s returned from `useLoaderData`

### ISSUE THREAD

**Issue by JNaftali** [remix-run/remix#3762]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

I've reproduced it as a minimal fork of the stackblitz remix starter - https://stackblitz.com/edit/node-d35hmw

1. return a `ReadonlyArray` from a loader
2. attempt to access that array using `useLoaderData<typeof loader>()`
3. observe the type error when attempting to use array methods

### Expected Behavior

The array should be typed correctly and methods such as `array.map` should be allowed. Either the array should come through typed as `Array` or as `ReadonlyArray`

### Actual Behavior

the object is typed as a bare object with numeric properties and lacking all array methods.

**Comment by JNaftali** [comment]
cc @colinhacks since you might be able to quickly clarify if this is indeed a bug or just things working as intended - seems like not ideal behavior to me

**Comment by kiliman** [comment]
If you use my `superjson` version, it is correctly typed:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/47168/179362227-9d78aa65-963b-4545-bda3-877e454d1f0a.png">

https://stackblitz.com/edit/node-cx46b4?file=app%2Froutes%2Findex.tsx

**Comment by machour** [comment]
Fixed in https://github.com/remix-run/remix/pull/3774 and released in 1.6.6
