### ISSUE TITLE
Instruct to restart the dev server after marked install in blog tutorial

### ISSUE THREAD

**Issue by Drew-Daniels** [remix-run/remix#3769]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Follow the [Quickstart](https://remix.run/docs/en/v1/tutorials/blog) documentation, and after the step covering installing `marked` on line 576 of `docs/tutorials/blog.md`, validate that the markdown is not rendered into HTML onto the page when you are on a post-specific route (i.e., `http://localhost:3000/posts/90s-mixtape`).

### Expected Behavior

The tutorial makes it appear that just by installing the `marked` npm package, your development server will automatically then rebuild and show the markdown on the page (if you are currently navigated to a post slug page).

### Actual Behavior

It was not until shutting down and restarting my development server with `npm run dev` that I saw the markdown rendered into HTML upon navigating to a post route.

I think including a sentence explaining that users will need to restart their development server would help prevent any confusion around this step. It was not until a few manual page refreshes that I felt I might need to restart my dev server to see these changes.

**Comment by kiliman** [comment]
True. But in defense, it is always advisable to restart processes when adding new packages via npm/yarn.
