### ISSUE TITLE
Cookie Header append order affects what cookie/session you can read

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#377]
I'm adding Cookie and Session support to remix-i18next to allow me to store the user preferred language there, and I found out this.

If I want to send a request with both my cookie and session the order in which I run `headers.append` affect what I can read. See this:

```ts
let headers = new Headers();
headers.append("Cookie", await sessionStorage.commitSession(session)); // session first
headers.append("Cookie", await cookie.serialize("jp")); // cookie second
```

I get the following Cookie header:
```
session=IjEi.VQs%2B7DmwI0KKzuKIThT9uUj6oisQn5sChGiXXTxf%2FOY, cookie=ImpwIg%3D%3D
```

If I then do this:

```ts
await cookie.parse(request.headers.get("Cookie")) ?? ""
```

The result is the empty string, I can't get the cookie value. If I try to get the value from the session doing this:

```ts
let session = await this.options.sessionStorage.getSession(request.headers.get("Cookie"));
session.get("lng");
```

I get the correct value stored in the session. But if I invert the `headers.append` order to do it this way:

```ts
headers.append("Cookie", await cookie.serialize("jp")); // cookie first
headers.append("Cookie", await sessionStorage.commitSession(session)); // session second
```

The cookie value in the header becomes:

```
cookie=ImpwIg%3D%3D, session=IjEi.VQs%2B7DmwI0KKzuKIThT9uUj6oisQn5sChGiXXTxf%2FOY
```

So now the cookie comes first and when I try to get the value from the cookie it works, but the value from the session is always empty. If I do `session.data` to check the session value I also get an empty object.

So the first cookie I append to the header is the only one I can read.

**Comment by AhmedBHameed** [comment]
I feel like a parser issue (not sure TBH).

However, If you get the cookies as a string then you can use this approach which works fine with me.

in my `root.tsx` I call `load` function to access `request` object:

```typescript
import Cookies from 'universal-cookie';

/**
 * You can load any data you need for your app in the loader function.
 * Server side rendering will call the loader function with the the request object
 * @param param0
 * @returns
 */
export let loader: LoaderFunction = ({request}) => {
  const cookies = new Cookies(request.headers.get('Cookie'));
  const COOKIE_VALUE = cookies.get(COOKIE_KEY_NAME);

  return {cookieName: COOKIE_VALUE};
};
```

Then in `Document` component I use `useLoaderData` hook to get what I've parse before

```typescript
  let loaderData = useLoaderData<ThemeContext>();

console.log(loaderData.cookieName) // <<= that should give you what you've asked in your component.
```

Hopefully that might help you?

**Comment by machour** [comment]
@sergiodxa is this bug report still accurate after all this time?

**Comment by sergiodxa** [comment]
@machour it's not anymore, I have been able to use multiple cookies without issues on a production app.
