### ISSUE TITLE
Public folder with Avif image serves it as octet-stream

### ISSUE THREAD

**Issue by BleedingDev** [remix-run/remix#3771]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

1. Put AVIF image into public folder.
2. Use that image (I use it from CSS as a background image).
3. Image does not work.
4. Check Network tab in Devtools.
5. Image is loaded, but with type `octet-stream`.

Might be related to issue already created for Gatsby https://github.com/gatsbyjs/gatsby/issues/31068

### Expected Behavior

Correct Content-Type, so image can be loaded.

### Actual Behavior

Content-Type == octet-stream

**Comment by kiliman** [comment]
If you're using Remix App Server, you'll need to switch over to Express, so you can configure the MIMI types.

In you server.js file, you would add:
```ts
const mime = require('mime') // install the mime package
mime.define({'image/avif': ['avif']})
```

[`mime` package](https://www.npmjs.com/package/mime)

To eject from RAS to Express, I have a script:
https://rmx.fyi/ejectras

**Comment by coreyward** [comment]
I was able to solve this by ejecting to Express (thanks for the script, @kiliman!) and adding the following to my `server.js`:

```
express.static.mime.define({ "image/avif": ["avif"] });
```

With this change, requests to `/thumbs/some-image.avif` are routed to `public/thumbs/some-image.avif` and served with a `Content-Type: image/avif` header, allowing them to be viewed directly in Chrome and work in `img` tags.

I tried with `mime.define` directly, but got the same error that is reported in the Gatsby thread linked by the OP (`Error: "Attempt to change mapping for "avif" extension from "image/avif" to "image/avif"`).

**Comment by machour** [comment]
Fixed on Vercel's side.

**Comment by coreyward** [comment]
@machour I don't use Vercel and experienced this issue. Can you help unpack how Vercel fixed something Remix does outside of Vercel?

**Comment by machour** [comment]
Sorry @coreyward, got confused with multiple issues tabs opened, and closed the wrong one :)

> Can you help unpack how Vercel fixed something Remix does outside of Vercel?

"I think closing this issue was a mistake." instead of passive-agressive stances for next times please 🙏🏼

**Comment by coreyward** [comment]
I had no idea it was a mistake, and didn't intend for it to come across as passive aggressive, but sorry that's how it landed. For clarity, I assumed you knew what you were doing, and I sought to understand while making it easy to see why I was confused.

**Comment by pcattori** [comment]
Closing as `remix-serve` is intended to be a minimal server to get you off the ground. As recommended above, if you want to customize your app server, you can use Express or any other app server.
