### ISSUE TITLE
Typecasting useLoaderData doesn't work in blog tutorial

### ISSUE THREAD

**Issue by dca123** [remix-run/remix#3772]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Follow the [tutorial](https://remix.run/docs/en/v1/tutorials/blog) till the [Dynamic routing section](https://remix.run/docs/en/v1/tutorials/blog#dynamic-route-params). I was able to use generic to resolve the issue. I've attatched a PR to this issue that should fix this problem

P.S, I'm a fresh contributer, so I'd appreciate any tips !
Regards,
Dev

### Expected Behavior

Able to continue as shown in the tutorial

### Actual Behavior

Using `const { posts } = useLoaderData() as LoaderData;`  results in the following error 

```
Conversion of type '{ posts: { slug: string; title: string; markdown: string; createdAt: string; updatedAt: string; }[]; }' to type 'LoaderData' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'posts' are incompatible.
    Type '{ slug: string; title: string; markdown: string; createdAt: string; updatedAt: string; }[]' is not comparable to type 'Post[]'.
      Type '{ slug: string; title: string; markdown: string; createdAt: string; updatedAt: string; }' is not comparable to type 'Post'.
        Types of property 'createdAt' are incompatible.
          Type 'string' is not comparable to type 'Date'.
```

**Comment by dca123** [comment]
Here is my PR #3773 https://github.com/remix-run/remix/pull/3773

**Comment by jtushman** [comment]
FYI -- I also ran into this as a +1
