### ISSUE TITLE
Run `remix setup` in a way where it doesn't add duplicate exports if they already exist.

### ISSUE THREAD

**Issue by jensmeindertsma** [remix-run/remix#380]
I'm running into an issue where if I run `postinstall` multiple times ( which runs `remix setup` ), it adds the exports multiple times leading to TypeScript errors. Perhaps the `remix setup` script could detect existing exports and not re-add them?

**Comment by chaance** [comment]
We are suggesting that folks move away from running `remix setup` altogether in favor of direct module imports, and we now have a script to help ease the transition. See our [release notes for 1.4.0](https://github.com/remix-run/remix/releases/tag/v1.4.0) for details.
