### ISSUE TITLE
docs: prettier.config.js file appears as a page on the docs website

### ISSUE THREAD

**Issue by abdulaziz13234** [remix-run/remix#3806]
### What version of Remix are you using?

Does not matter

### Steps to Reproduce

Go to: https://remix.run/docs/en/v1
and scroll down in the side navigation bar

### Expected Behavior

It doesn't appear as a page

### Actual Behavior

![Screen Shot 2022-07-20 at 12 56 23 PM](https://user-images.githubusercontent.com/104041136/179954601-456714e9-17a9-4df8-89be-f2e28beb8062.png)

**Comment by machour** [comment]
Thank you for reporting this !
