### ISSUE TITLE
[Docs v0.20 - Tutorial (Start Here!)]: Syntax errors and other small caveats

### ISSUE THREAD

**Issue by jgarplind** [remix-run/remix#381]
Found a couple of issues while going through the Tutorial last night. I'll put them here in the same issue, and will happily help resolve them if there is a way for me to do so at some point.

## [Defining routes](https://docs.remix.run/v0.20/tutorial/2-defining-routes/)
In general, since `npx create-remix@latest` creates an application with React 17, `import React from "react";` is obsolete and has no effect. This is the case in several code examples (over several sections), and while not a bug, might distract new learners slightly. 

### [Finished product](https://docs.remix.run/v0.20/tutorial/3-loading-data/#finished-product)
In this section, the `headers` function is missing a `)` (trailing paranthesis), making it not compile.

It also wouldn't hurt to include the snippet `interface Gist { id: string, html_url: string, files: `:thinking:` }` to make the code example complete.

Third and last as far as potential code issues go, the `loader` function is not `async` which seems to make the `await`s contained in the function not work too well.

On a somewhat unrelated note, it was a bit confusing as a newcomer to understand how we ended up in said finished product. Many details felt like they popped up from nowhere. That, I suppose, is something that will be resolved in the future when the docs are more thoroughly maintained.

## [Styling](https://docs.remix.run/v0.20/tutorial/5-styling/)
The link with the following clickable text: "several different styling options," leading here https://docs.remix.run/v0.20/styling/ ends up on a Not Found-page.

### [Make a new route](https://docs.remix.run/v0.20/tutorial/6-actions/#make-a-new-route)
This might just be me not understanding exactly what you are trying to communicate, but I spent a good minute or two figuring out why the `<form method="post">` didn't have an `action` attribute, despite the text reading: 

> [...] with an action that points to our /gists route

I assume the proper example code would read `<form method="post" action="/gists">`, but this might just be my inexperience with the unabstracted web platform shining through!

**Comment by machour** [comment]
Thank you for putting time to make this PR. 🙏🏼 
This is however not applicable anymore, so I'm going to close it without merging.
