### ISSUE TITLE
formData in action function is having undefined value of a value attribute of a checkbox when checked attribute is true

### ISSUE THREAD

**Issue by rajeshde** [remix-run/remix#3819]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

```
import {useRef} from 'react';
import {Form} from '@remix-run/react';
import type {ActionFunction} from '@remix-run/node';

export const action: ActionFunction = async ({request}) => {
  const formData = await request.formData();
  const {_action} = Object.fromEntries(formData);

  console.log('_action', _action);

  return null;
};

const Test = () => {
  const ref = useRef<HTMLFormElement>(null);

  const handleOnChange = () => {
    ref.current?.submit();
  };

  return (
    <Form ref={ref} method="post">
      <label>
        Check
        <input
          name="_action"
          value="update"
          type="checkbox"
          checked={true}
          onChange={handleOnChange}
        />
      </label>
    </Form>
  );
};

export default Test;
```

1. Click on the checkbox and notice the log in the action function. This will return `undefined` as `checked={true}`
2. Change the value to `checked={false}` and click on the checkbox again. Log will return the correct value `update`

https://user-images.githubusercontent.com/22252320/180326126-2d3a2a52-2c67-432c-a40f-73f8be35af4c.mp4

`

### Expected Behavior

`_action` must log the correct `value` being passed in the input element regardless of the value of `checked` attribute. Be it true or false, `_action` must return `update` always.

### Actual Behavior

`_action` is returning `undefined` when `checked={true}` which is incorrect.

**Comment by kiliman** [comment]
For `<input type=checkbox>` the *value* attribute is the value that will be submitted when the checkbox is checked, otherwise, the name/value will *not* be submitted.

If you need it to submit the same value regardless of checked state, then why are you using a checkbox? If you need that value to always be submitted, then add a hidden input.

Here's a codesandbox showing you how checkbox works.

```js
export async function action({ request }: ActionArgs) {
  const formData = await request.formData()
  // formData will not include checkbox if not checked, so use default
  const checkbox = formData.get('checkbox') ?? 'false'
  const _action = formData.get('_action')

  return json({ checkbox, _action })
}

export default function Index() {
  const submit = useSubmit()
  const data = useActionData()
  const checked = data?.checkbox === 'true' ?? false

  const handleOnChange = (e) => {
    e.preventDefault()
    submit(e.target.form)
  }
  return (
    <div className="m-2">
      <h1 className="text-2xl font-bold">Welcome to Remix Starter!</h1>
      <Form method="post">
        <input type="hidden" name="_action" value="update" />
        <label>
          Check
          <input
            name="checkbox"
            value="true"
            type="checkbox"
            checked={checked}
            onChange={handleOnChange}
          />
        </label>
      </Form>
      <pre>{JSON.stringify(data, null, 2)}</pre>
      <pre>checked: {checked ? 'true' : 'false'}</pre>
    </div>
  )
}
```
https://codesandbox.io/s/remix-checkbox-ot0x1c?file=/app/routes/index.tsx

**Comment by machour** [comment]
Closing as invalid
