### ISSUE TITLE
Upload file error using axios

### ISSUE THREAD

**Issue by fatehwaharp** [remix-run/remix#3820]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Using example template from [remix/examples/file-and-cloudinary-upload](https://github.com/remix-run/remix/tree/main/examples/file-and-cloudinary-upload)

On the `app/routes/local-upload.tsx`'s action function 

add this code to send the uploaded file to api:

**Failed when using axios**

```
import axios from 'axios';

await axios.post("http://127.0.0.1:8000/api/upload", formData, {
  headers: { "Content-Type": "multipart/form-data" },
});
```

**Success when using fetch**
```
await fetch("http://127.0.0.1:8000/api/upload", {
  method: "POST",
  body: formData,
});
```

### Expected Behavior

On upload button clicked, the file will be uploaded to the api successfully

### Actual Behavior

Got this error response if using **axios** 

```
[AxiosError: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data',
      'User-Agent': 'axios/0.27.2'
    },
    method: 'post',
    url: 'http://127.0.0.1:8000/api/upload',
    data: FormData {}
  }
}
```

If using **fetch** everything works as expected

**Comment by machour** [comment]
This doesn't seem like a bug in remix, but rather a problem with your usage of axios: https://stackoverflow.com/a/47630754/732772
