### ISSUE TITLE
Can't create a new remix app

### ISSUE THREAD

**Issue by giopetris** [remix-run/remix#3822]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Run `npx create-remix --template remix-run/indie-stack blog-tutorial`

### Expected Behavior

Create a new remix app.

### Actual Behavior

It's failing with the following message:

<img width="598" alt="CleanShot 2022-07-23 at 11 47 58@2x" src="https://user-images.githubusercontent.com/1332141/180610126-769e54bb-77de-40c7-9367-218d1dc16cb3.png">

**Comment by MichaelDeBoey** [comment]
Closing this because this works for me if you run the following command (using `create-remix@latest` instead of just `create-remix`)

```sh
npx create-remix@latest --template remix-run/indie-stack blog-tutorial
```

**Comment by giopetris** [comment]
hi @MichaelDeBoey , I got the same error running with `@latest`:

<img width="613" alt="CleanShot 2022-07-26 at 09 41 13@2x" src="https://user-images.githubusercontent.com/1332141/181008216-d895f800-85a1-4046-be63-b6d73ef64ea4.png">

What npm version are you running with?

**Comment by kiliman** [comment]
@giopetris Do you have an `.npmrc` file somewhere that's trying to load Remix packages from somewhere else?

**Comment by giopetris** [comment]
Oh, it was exactly that, thanks so much @kiliman ! Btw, I heard your podcast a few weeks ago, so nice to see you here! 😅 

For anyone running into this, I fixed with the command: `npm config delete @remix-run:registry`
