### ISSUE TITLE
Remix overwrites existing files when opening another local folder

### ISSUE THREAD

**Issue by mushketyk** [remix-run/remix#3828]
### What version of Remix are you using?

Version 1.3.4 (1.3.4.825)

### Steps to Reproduce

1. Open Remix locally.
2. Click "Connect to Localhost"
3. Open a folder with a git repository (File -> Open Folder)
4. Select workspace "localhost"
5. Open a file by double-clicking on it (a file should be opened in a new tab)
6. Open a different local folder 

At this stage, Remix silently writes the content of an opened file to the current local folder.

I've tried this with a single open file, and it either creates a new file or overwrites an existing file if a file with this name exists in a new folder. It might also exhibit the same behavior with multiple files.

### Expected Behavior

1. It should not overwrite/create files
2. Either close all source code tabs or (if there is a file with the same name in the same path) load this content into an opened source file tab.

### Actual Behavior

It writes to files it should not write to.

**Comment by MichaelDeBoey** [comment]
Hello 👋
I think you may be in the wrong place. This GitHub repo is all about the Remix Web Framework which you can learn about at https://remix.run.
Closing this as you have mixed this up with the Remix IDE (https://remix-project.org) which is a completely different project.
