### ISSUE TITLE
Cmd+W should close a current tab

### ISSUE THREAD

**Issue by mushketyk** [remix-run/remix#3829]
### What version of Remix are you using?

Desktop app
Version 1.3.4 (1.3.4.825) 
macOS 12.0.1 (21A559)

### Steps to Reproduce

1. Open Remix
2. Open a file
3. Press Cmd+W

### Expected Behavior

Close the current file tab, as most (all?) other IDEs do.

### Actual Behavior

Closes the whole app.

**Comment by MichaelDeBoey** [comment]
Hello 👋
I think you may be in the wrong place. This GitHub repo is all about the Remix Web Framework which you can learn about at https://remix.run.
Closing this as you have mixed this up with the Remix IDE (https://remix-project.org) which is a completely different project.
