### ISSUE TITLE
ScrollRestoration access to session store error in iframe

### ISSUE THREAD

**Issue by puchesjr** [remix-run/remix#3844]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Create a fresh remix application and simply embed in an iframe on another site.

DOMException: Failed to read the 'sessionStorage' property from 'Window': Access denied for this document.

### Expected Behavior

Work or fail gracefully.

### Actual Behavior

Threw an error DOMException: Failed to read the 'sessionStorage' property from 'Window': Access denied for this document.

**Comment by machour** [comment]
Duplicate of #3659
