### ISSUE TITLE
hydration doesn't work after remix build on UC Browser

### ISSUE THREAD

**Issue by lili21** [remix-run/remix#3864]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

1. build the project
```
git clone https://github.com/lili21/remix-uc.git
cd remix-uc
npm i 
npm run build
npm run start
```

You can visit `http://localhost:3000` with [UC Browser](https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en_US&gl=US). the page should be like 

![image](https://user-images.githubusercontent.com/4456380/181728835-f31f1c8e-730e-41ce-84a0-a29fe0e6aa8b.png)

2. click the `add` button

### Expected Behavior

`0` should change to `1`

### Actual Behavior

`0` is still `0`

it works on dev mode, it just does't work after build

**Comment by machour** [comment]
@lili21 any errors logged to the console?

Also, could you please give this a try on 1.11.1? I know we had some kind of breakage for some browsers due to the use of the nullish coalescing operator, and we got it fixed.
