### ISSUE TITLE
Wrong units for Value when I am on a different Network from Ethereum

### ISSUE THREAD

**Issue by seaona** [remix-run/remix#3865]
### What version of Remix are you using?

Latest

### Steps to Reproduce

https://user-images.githubusercontent.com/54408225/181733226-46fe9b8b-31c1-4f9a-a43b-8f537c5e6943.mp4

1. Go to Remix
2. Unlock MetaMask
3. Change Network for Binance Chain testnet
4. Deploy a contract
5. Include value for a function call

### Expected Behavior

Value is represented in the unit of the Network I am connected.

### Actual Behavior

Value is always represented in ETH (and its different unit variations)

**Comment by pawelblaszczyk5** [comment]
It's a repository for a React framework not a Remix IDE. Here[Here](https://github.com/ethereum/remix-ide)  you can find proper repo

**Comment by seaona** [comment]
ouch, thank you @pawelblaszczyk5 !!
