### ISSUE TITLE
Node 14: Unexpected token '??='

### ISSUE THREAD

**Issue by alexketchum** [remix-run/remix#3877]
### What version of Remix are you using?

1.6.6

### Steps to Reproduce

Run `npx create-remix@latest`

### Expected Behavior

A new remix project is created after answering the questions

### Actual Behavior

After a few seconds of loading I'm met with the following message `Unexpected token '??='`

**Comment by alexketchum** [comment]
I was able to get around this by using v1.6.5 - `npx create-remix@1.6.5`

**Comment by machour** [comment]
@alexketchum What node version are you running?

**Comment by alexketchum** [comment]
14.16.1

I see that I need at least 14.17.0. I'll try updating node and running it again.

**Comment by machour** [comment]
I just tested 14.20 and I'm having the same error. Seems like we accidentally dropped node 14 support here:
   https://github.com/remix-run/remix/commit/befce4a3a7e0218183db6feb9bf4cfc739883e42#diff-08f1d402b3b2041674b10a474187115744ce554aa54e5055f36a0174d95ad15cR211

**Comment by machour** [comment]
This was an oversight and should be addressed shortly by the team, thank you for reporting this 🙏🏼

**Comment by machour** [comment]
Fixed in 1.6.7
