### ISSUE TITLE
Infinite-scrolling example not working using the scrollbar

### ISSUE THREAD

**Issue by rkulinski** [remix-run/remix#3894]
### What version of Remix are you using?

1.6.4

### Steps to Reproduce

Open `examples/infinte-scrolling` and select `page/simple`.

### Expected Behavior

When I scroll by grabbing scroll bar to bottom I should see all the elements loaded.

### Actual Behavior

Elements displays as `Nothing to see here...`
![Screen Shot 2022-08-01 at 10 13 51](https://user-images.githubusercontent.com/25184202/182104077-868160ed-382a-4e30-9c05-fd909b34c5f6.png)

I think you might want to change:
```
  const rowVirtualizer = useVirtual({
    size: data.totalItems,
    parentRef,
    estimateSize: useCallback(() => 35, []),
    initialRect: { width: 0, height: 800 },
  });
```
to
```
  const rowVirtualizer = useVirtual({
    size: items.length,
    parentRef,
    estimateSize: useCallback(() => 35, []),
    initialRect: { width: 0, height: 800 },
  });
```

Otherwise this is generating many problems like calling issues when scrolling fast or throwing warnings:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

**Comment by machour** [comment]
I just tried the example using Remix 1.6.7, and everything is working as expected:

![Screen Shot 2022-08-01 at 9 43 54 AM](https://user-images.githubusercontent.com/304450/182109779-f68dc02f-820b-4453-a6c6-9c3abaa1c6db.png)

In the network tab, I can see the XHRs being fired, and the response does contain `totalItems` entry, which is being correctly used here.

Can you share more details about your setup ? (node version, browser, etc)

Thanks !

**Comment by rkulinski** [comment]
Thanks for such a short reply. I cannot run this example on code sandbox - not sure what is wrong, but I'm getting blank screen. I downloaded repo and run it.

```Node v16.14.0
Firefox```

**Comment by machour** [comment]
I also encountered a problem with codesandbox, and ran the project locally using `yarn create remix --template https://github.com/remix-run/remix/tree/main/examples/infinite-scrolling`

I was using the touchpad, but I do see the problem now while using the scrollbar !

**Comment by machour** [comment]
I tested your change, and it seems to do the trick, although the scrollbar gets a little jumpy.
Would you mind opening a PR with your proposed fix so we can get to the root of the problem with the rest of the team?

**Comment by rkulinski** [comment]
Yeah it does. Although in my scenario I had to some more tweaks to make it work.

I agree that scrollbar is jumpy, but if there would be a wish to have scrollbar mimic fully loaded data set it would require refactoring of how items are loaded into array (currently the problem is that due to so many state changes some of them seems to be skipped, hence indexes mismatch).

Maybe, before making code changes it would be a good idea to discuss and have a clear goal for this example.

**Comment by machour** [comment]
Summoning @kentcdodds 🪄

**Comment by kentcdodds** [comment]
Can we compare what you're experiencing with other infinite scroll examples like Twitter? Do you experience the jumpiness there? It's it just an issue with infinite scroll in general?

**Comment by rkulinski** [comment]
I don't have a Twitter, but e.g. 9gag is using the same pattern:
https://9gag.com/

Although it seems like a cool thing to display scrollbar as if all items are already loaded it is causing many technical obstacles. And when I think about it more UX is not ideal as well. Let's say list is 30k elements. With such number of items scroll is not precise anyway, so I think it's not that useful.

**Comment by kentcdodds** [comment]
I'd like to see what code changes actually look like in a PR. I think I'd probably merge it 👍

**Comment by rkulinski** [comment]
@kentcdodds 
Really simple change:
https://github.com/remix-run/remix/pull/4003

**Comment by kentcdodds** [comment]
Merged. Thanks!
