### ISSUE TITLE
can you make create-remix to accept all parameters and not just the --dir ?

### ISSUE THREAD

**Issue by AlonGvili** [remix-run/remix#394]
currently, create-remix only accept the first parameter as input, so I can do `npx create-remix ./myapp`

for automation purposes if i can do `npx create-remix --dir='./myapp' --server='fly' --language='ts' --install=true`
i can use other scripting languages like PowerShell to generate projects with custom folder structure and add necessary packages & run more command like init tailwind, prisma etc...

**Comment by AlonGvili** [comment]
Bump

**Comment by AlonGvili** [comment]
bump

**Comment by machour** [comment]
@AlonGvili does [remix stacks](https://remix.run/blog/remix-stacks) answer your requirement or do you still need to be able to pass options to the regular CLI?

**Comment by mcansh** [comment]
these options are now available via the CLI as flags 😄 

`npx create-remix@latest ./my-app --template fly --typescript --install` 
you can see `npx create-remix@latest --help` for further options
