### ISSUE TITLE
Cannot use existing React's charting libraries [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by AsadSaleh** [remix-run/remix#3959]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

I'm trying to use React's charting library such as `recharts` or `react-charts`.

I npm installed it
```
npm install recharts
```
 Try to implement the basic chart in my code. And then this happens:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/asad/Projects/IDN/shikamaru/node_modules/d3-shape/src/index.js from /Users/asad/Projects/IDN/shikamaru/node_modules/react-charts/lib/seriesTypes/Line.js not supported.
Instead change the require of index.js in /Users/asad/Projects/IDN/shikamaru/node_modules/react-charts/lib/seriesTypes/Line.js to a dynamic import() which is available in all CommonJS modules.
```
I thought this is an SSR problem, so I try to use `ClientOnly` from `remix-utils`, but it doesn't help.

I also tried `react-charts` (another chart lib) and it produced the same error.

### Expected Behavior

I expect it to run smoothly.

### Actual Behavior

Error page shows up.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/31646255/183320371-e0f9d23d-43b8-4f8a-b1ba-53559f57c679.png">

**Comment by AsadSaleh** [comment]
I'm currently reading this https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages

I'll update it as soon as I get it working.

**Comment by AsadSaleh** [comment]
Okay, it's working ✅ 

What I need to do is to update the `serverDependenciesToBundle` in my `remix.config.js`.

So it looked like this:
```
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: ["react-charts", "d3-time-format"],
}

```

Sorry for not reading it first. Great docs actually!

**Comment by sapter** [comment]
@AsadSaleh what did you end up putting in `serverDependenciesToBundle` for Recharts?

**Comment by sapter** [comment]
@AsadSaleh what did you end up putting in `serverDependenciesToBundle` for Recharts?

**Comment by AsadSaleh** [comment]
> @AsadSaleh what did you end up putting in `serverDependenciesToBundle` for Recharts?

I ended up using `react-charts` instead of `recharts`.

**Comment by fourcolors** [comment]
I'm using Remix and getting this exact same error
