### ISSUE TITLE
Duplicate CSS files being generated outside of assetsBuildDirectory in server directory

### ISSUE THREAD

**Issue by miniplus** [remix-run/remix#3969]
### What version of Remix are you using?

1.6.6

### Steps to Reproduce

Initially started from the [Grunge stack starter](https://github.com/remix-run/grunge-stack) before Remix-run was on version `1.6.5`. After upgrading to `1.6.7`,  I noticed there's duplicate CSS files being generated in both `/public/build/_assets` and in `server/_assets`, having the same hash in their filename. The ones in the server directory seem to be redundant.

I managed to narrow the bug down to version `1.6.6` as `1.6.5` did not have it, while `1.6.6` and `1.6.7` did have it.
https://github.com/remix-run/remix/compare/remix%401.6.5...remix%401.6.6

# remix.config.js

```js
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  appDirectory: "app",
  cacheDirectory: "./node_modules/.cache/remix",
  assetsBuildDirectory: "public/build",
  publicPath: "/build/",
  serverBuildPath: "./server/index.js",
  ignoredRouteFiles: [".*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  routes(defineRoutes) {
    return defineRoutes((route) => {
      if (process.env.NODE_ENV === "production") return;

      console.log("⚠️  Test routes enabled.");
    });
  },
};
```

# app/root.tsx

have a links function in root.tsx

```ts
import tailwindStylesheetUrl from "./styles/tailwind.css";

export const links: LinksFunction = () => {
  return [
    { rel: "stylesheet", href: tailwindStylesheetUrl },
    { rel: "icon", href: "/assets/favicon.ico" },
  ];
};
```

`./styles/tailwind.css` is generated using the `tailwindcss -o ./app/styles/tailwind.css` command, but should have nothing to do with this specific use case. Even though I'm not entirely sure at this point, that's why I'm including it nonetheless.

Run the `remix dev` command to see the files being generated.

### Expected Behavior

The generated CSS files are only generated inside `/public/build/_assets` and not in `server/_assets`.

### Actual Behavior

There's duplicate CSS files being generated in both `/public/build/_assets` and in `server/_assets`, having the same hash in their filename. The ones in the server directory seem to be redundant.

**Comment by GregBrimble** [comment]
I haven't verified it, but this `1.6.6` commit certainly looks suspicious: https://github.com/remix-run/remix/commit/916caa6a25d5496de0c4de7331852bf279338017
