### ISSUE TITLE
Hook useResolvedPath on splat route is not working correctly

### ISSUE THREAD

**Issue by mathieukh** [remix-run/remix#3982]
### What version of Remix are you using?

1.6.7

### Steps to Reproduce

I have a splat route as app.$.tsx.
The page is used to explore a folder and the splat param is used to resolve the path to open within the folder.
For example: `app/folder1/file1.txt`.

I want to display link to the next folders / files in pages as *app/folder1*.
However, I have a problem to create the link to sub folder.
On the page *app/folder1*, the `<Link to="file1.txt" />` will generate a link to app/file1.txt.

I did try to use the *useResolvedPath* which seems to be the intended behaviour but the path remains the same.

### Expected Behavior

On the page *app/folder1*, I want to use `useResolvedPath("file1.txt")` to generate the path *app/folder1/file1.txt*.

### Actual Behavior

On the page *app/folder1*, `useResolvedPath("file1.txt")` resolves to *app/file1.txt*.

**Comment by kiliman** [comment]
I'm pretty sure `useResolvedPath` works on *route* segments, not *URL* segments.

Since `file.text` resolves the `*` (splat) segment, that's what gets replaced.

If you want to work against the current URL, then you'll need to resolve against the actual path (i.e., `useLocation`).

I created a hook to help with relative paths against the actual URL instead of the route config. To ensure things work the way the browser expects, make sure any "folder" routes end in `/` (e.g. `/app/folder1`)

```js
function useRelativePath() {
  const location = useLocation()
  const base = new URL(`http://dummy${location.pathname}${location.search}`)
  return (relativePath: string) => {
    const relative = new URL(relativePath, base)
    return `${relative.pathname}${relative.search}`
  }
}

// path = /app/folder1/
const getRelative = useRelativePath() 
console.log(getRelative('file.txt'))  // /app/folder1/file.txt
```

https://gist.github.com/kiliman/a5091662193574912d9673a4ea1e8e99

**Comment by mathieukh** [comment]
I did the same hook for now but thought there was an issue in the hook useResolvedPath as the documentation specifies:
[_This hook resolves the pathname of the location in the given to value against the pathname of the current location._](https://reactrouter.com/docs/en/v6/hooks/use-resolved-path)

**Comment by kiliman** [comment]
Yeah, I think they need to be consistent with their naming. They use location and route interchangeably a lot. When in doubt, assume they are referring to the route config.

**Comment by chaance** [comment]
@mathieukh we've had lots of conversations on this in recent days, and the behavior here is correct (our tests explicitly check for this behavior) but the docs need to be updated as you pointed out. I've created a ticket for that internally!
