### ISSUE TITLE
Action adds `index` query param indefinitely  -> ?index&index&index&index

### ISSUE THREAD

**Issue by ZiiMakc** [remix-run/remix#3998]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

A simple `<Form method='post'>` on index route adds  `index` query param for each action taken resulting in `?index&index&index&index...` after [3697](https://github.com/remix-run/remix/pull/3697) was merged.

This can be mitigated by adding `action='.'`, but then query params are not saved.

### Expected Behavior

No `index` param added or added only once.

### Actual Behavior

`index` param added for each action call.

**Comment by p-m-p** [comment]
I'm seeing the same behaviour with `useSubmit` in latest version update `1.6.8` https://stackblitz.com/edit/node-v3byq1?file=app/routes/index.tsx

**Comment by brophdawg11** [comment]
Should be fixed by #4000, which should go out in 1.6.9 soon 👍
