### ISSUE TITLE
Running Remix on Cloudflare Workers

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#40]
What if you could run Remix w/out a server? We can keep the current architecture of Remix, but serve everything out of a service worker instead of our usual server.

## Motivation

The main motivation for this right now would be to run Remix in Cloudflare Workers, which is built around the service worker API. The beauty of being able to deploy to Cloudflare Workers is that you can run your entire app at "the edge."

One nice side effect of Cloudflare choosing to build Workers using the service worker API is that if we can build Remix to run *there* it *should* be a relatively small jump to run Remix entirely in the browser in a real service worker. Now instead of running at the edge, you get run run the whole thing locally.

So basically, run all of Remix either at the edge, or straight up in your browser if you don't want/need a traditional server.

## API

We can provide a similar API in `@remix-run/service-worker` to what we currently do in `@remix-run/express`. Something like:

```ts
import { createFetchEventHandler } from "@remix-run/service-worker";

addEventListener(
  "fetch",
  createFetchEventHandler({
    getLoadContext(request: Request) {
      // Return whatever you want to be the `context` arg in your loaders...
    }
  })
);
```

Think of this file like `server.js` for an Express app.

We can build a small server with the `addEventListener` API that lets you run this locally, and then we'll use this file as input to generate all the relevant pieces we'll need to run the app in a real service worker.

## Building

Since neither Cloudflare Workers nor service workers have support for modules (though it's [being discussed for Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=824647)), we will need to bundle everything into a single file in the build: React, React DOM, React Router, Remix, etc.

In the bundled Remix code we'll need to avoid any node-isms (i.e. `process.env.NODE_ENV`, `fs`, etc.) and stick to just the service worker API.

In the build, we'll need to include:

- A lookup for route modules
- A lookup for loaders
- The build manifest (lookup for assets)

## Open Questions

- Is this even doable in Cloudflare Workers? What are the resource constraints?
- We'll need `ReactDOMServer.renderToString` in our `entry-server.js` but I'm guessing `react-dom/server` is not designed to be bundled...
- Instead of compiling on-demand like the server now does, do we just compile everything up front?

**Comment by chaance** [comment]
Cleaning up old
