### ISSUE TITLE
.env file not loaded when using 'Just the basics' and 'Remix App Server' Stack

### ISSUE THREAD

**Issue by limboy** [remix-run/remix#4007]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

1. create a new project using `npx create-remix@latest`, select "Just the basics" and "Remix App Server"
2. add `.env` file with content `FOO=BAR`
3. add `export const loader: LoaderFunction = () => { console.log(process.env.FOO); return null; };` to `root.tsx`
4. run `npm run dev`, visit `http://localhost:3000`, log `BAR` in console
5. run `npm run build`, `npm run start`, visit `http://localhost:3000`, log `undefined` in console.

### Expected Behavior

.env content is omitted when `NODE_ENV == 'production'` using `Just the basics` and `Remix App Server`. it should be loaded just as in dev mode.

### Actual Behavior

.env content is omitted when `NODE_ENV == 'production'`

**Comment by kiliman** [comment]
Environment files are only loaded in `development`. Your provider typically has a way to setup environment variables for `production`.

* Fly has Secrets
* Vercel has Settings > Environment Variables
* etc

## Fly
<img width="567" alt="image" src="https://user-images.githubusercontent.com/47168/184883318-870e0e5c-7be5-4f47-8706-8bb4620dcab6.png">

## Vercel
<img width="770" alt="image" src="https://user-images.githubusercontent.com/47168/184883359-fc292eba-7843-4f44-a019-670be3caa4d9.png">

**Comment by limboy** [comment]
get it, saw on doc, thanks for your reply.
