### ISSUE TITLE
when use search in `Link` component the parent component's loader will execute

### ISSUE THREAD

**Issue by myNameIsDu** [remix-run/remix#4011]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

```shell
git clone https://github.com/myNameIsDu/remix-query.git
cd remix-query
pnpm install
pnpm dev
```
click `front` link

### Expected Behavior

only load `type` route's loader

### Actual Behavior

will load `front` and `type`'s loader

**Comment by machour** [comment]
This is the expected behavior according to the documentation, since you changed the search params.

> During client-side transitions, Remix will optimize reloading of routes that are already rendering, like not reloading layout routes that aren't changing. In other cases, like form submissions or search param changes, Remix doesn't know which routes need to be reloaded so it reloads them all to be safe. This ensures data mutations from the submission or changes in the search params are reflected across the entire page.

This is documented in [`unstable_shouldReload`](https://remix.run/docs/en/v1/api/conventions#unstable_shouldreload), that you can use to prevent `front`'s loader from being called again.

**Comment by myNameIsDu** [comment]
Oh, I understand it now, I think I know how to optimize it. Thank you so much.
