### ISSUE TITLE
Duplicated button's name/value pair in FormData on Safari (ONLY)

### ISSUE THREAD

**Issue by raskyer** [remix-run/remix#4023]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

- Create a remix project
- Have a Form component looking like =>
```
<Form method="post" replace>
  <input type="hidden" name="id" value="1" />

  <button type="submit" name="_action" value="delete">
    x
  </button>
</Form>
```
- Open the url with the form in Safari
- Click the button
- FormData sent to action looks like : 
id => 1
_action => delete
_action => delete

This does not occur on : Chrome / Firefox.

### Expected Behavior

Form Data only contains the button name / value pair one time.

### Actual Behavior

Form Data contains the button name / value pair two time (duplicate).

**Comment by raskyer** [comment]
Probably caused by : https://github.com/remix-run/remix/blob/remix%401.6.8/packages/remix-react/components.tsx#L1162

Maybe on Safari the button key value pair is already in the form submission data ? Adding a little if to check if forms already contains the key / value pair might be a solid workaround ?

**Comment by raskyer** [comment]
Pull request : https://github.com/remix-run/remix/commit/5894598c75d0e542651dc92bc400320c108eae8d

**Comment by mcansh** [comment]
> Maybe on Safari the button key value pair is already in the form submission data?

yeah exactly this, safari already includes the "submitter" in the FormData, in other browsers, we check the `event.target.submitter` and add it manually

**Comment by mcansh** [comment]
however, i just pulled this up locally and i'm only getting a single "_action" value sent in Safari 16.

![image](https://user-images.githubusercontent.com/11698668/185960446-f22d0bb6-6f0b-42ea-a383-7b4aabb89222.jpeg)

**Comment by raskyer** [comment]
Have you test on your mobile with recent remix version : https://github.com/remix-run/remix/pull/4024#issuecomment-1222504413

**Comment by mcansh** [comment]
sorry, spoke too soon, the request data only shows one, but logging `formData.getAll('_action')` returns two

**Comment by mcansh** [comment]
also, didn't realize you opened a PR 😅, thanks! I'll check that out

**Comment by brophdawg11** [comment]
This looks like it's a bug in Safari that's been fixed in Safari 16: https://bugs.webkit.org/show_bug.cgi?id=239070
