### ISSUE TITLE
[bug]: architect binary types typo

### ISSUE THREAD

**Issue by kamtugeza** [remix-run/remix#4040]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

Open the [remix-architect/binaryTypes.ts](https://github.com/remix-run/remix/tree/main/packages/remix-architect) and take a look at line 36.

### Expected Behavior

There should be two types: `audio/wav` and `audio/webm`.

### Actual Behavior

There are concatenated types "audio/wavaudio/webm"

**Comment by MichaelDeBoey** [comment]
Fixed by #4041
