### ISSUE TITLE
Build failed when I try to deploy my app in Netlify

### ISSUE THREAD

**Issue by crtdaniele** [remix-run/remix#4055]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

My netlify.toml

[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

When I try to deploy the app in Netlify I have this error:

<img width="1099" alt="Schermata 2022-08-24 alle 07 58 57" src="https://user-images.githubusercontent.com/18217293/186342029-aed056d9-c290-48c7-9f4d-1ffaa8169774.png">

The repository: https://github.com/crtdaniele/danielecarta

### Expected Behavior

I expected to deploy the app in Netlify with the command "npm run build -> remix build"

### Actual Behavior

<img width="1099" alt="Schermata 2022-08-24 alle 07 58 57" src="https://user-images.githubusercontent.com/18217293/186341897-e65ab655-5082-4811-9b70-98383193e626.png">

**Comment by hakimLyon** [comment]
I tested them but I could not reproduce this issue.

Site deploy was successfully initiated.

<img width="1185" alt="Capture d’écran 2022-08-24 à 13 32 42" src="https://user-images.githubusercontent.com/64654633/186432349-0752fa99-802e-48c8-8751-32e8f7c2f327.png">

Link netlify ->> https://glittery-cobbler-997864.netlify.app/
the repo --> https://github.com/hakimLyon/danielecarta

**Comment by mcansh** [comment]
@crtdaniele sounds like netlify isn't using node 14

**Comment by pcattori** [comment]
[Node 14 is no longer in maintenance](https://github.com/nodejs/release#release-schedule). All active and maintenance versions of Node (16+) support nullish coalescing operator (`??`).
