### ISSUE TITLE
Relative Link not working with non-nested layouts

### ISSUE THREAD

**Issue by herecydev** [remix-run/remix#4065]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

Clone https://github.com/herecydev/remix-relative-routing.

1. Start on `/blogs/1`
2. Try "nested" link and use the back button which works correctly
3. Try "edit" link and use the back button, incorrect behavior

### Expected Behavior

Using relative links should behave consistently irrespective of what "system" of nested routing is used. In this case we're using a combination of nested routes and [nested urls](https://remix.run/docs/en/v1/guides/routing#nested-urls-without-nesting-layouts).

The back link on the edit page should have gone back to `/blogs/1`, instead of the home page.

### Actual Behavior

Remix is unable to interpret the relative link `../` and instead navigates to the index page instead of understanding the url structure correctly.

**Comment by kiliman** [comment]
Remix navigates the "route" hierarchy, not the URL. Although confusing if you're not expecting it, this is by design. I believe they are adding a new prop to `<Link>` to be able to navigate relative URLs as well as routes.

In the meantime, here's a function I wrote to help navigate relative URLs.
```ts
function useRelativePath() {
  const location = useLocation()
  const base = new URL(`http://dummy${location.pathname}${location.search}`)
  return (relativePath: string) => {
    const relative = new URL(relativePath, base)
    return `${relative.pathname}${relative.search}`
  }
}

// path = /parent/child/?a=1
const getRelative = useRelativePath() 
console.log(getRelative('..?b=2'))  // /parent/?b=2
```

https://gist.github.com/kiliman/a5091662193574912d9673a4ea1e8e99

**Comment by herecydev** [comment]
Do you have a link to the "new prop" docs or a commit or something? In the meantime whilst what you're saying makes sense, I think this needs to be added to the docs [here](https://remix.run/docs/en/v1/guides/routing#nested-urls-without-nesting-layouts) because that's quite a severe caveat and somewhat makes them difficult to use with linking.

**Comment by machour** [comment]
We can now use `<Link relative="path">` with Remix 🎉 
Documentation is at: https://reactrouter.com/en/main/components/link#relative

PS: Thank you, this drove me nuts a few days ago as I didn't know it existed 😅
