### ISSUE TITLE
`params` (from LoaderArgs) is not being populated with query params from the incoming request

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#4108]
### What version of Remix are you using?
1.7.0, 1.6.7
II tried the latest remix, but also another previous version, which makes me believe this affects more versions

### Steps to Reproduce
1. Make a request to the following resource route: `example.com/graphQL?gqlQueryString=query%7BgetSites%7D`
2. Attempt to access the `gqlQueryString` param in the loader like this:

```tsx
export async function loader({ request, params }: LoaderArgs) {
   const gqlQueryString = params?.gqlQueryString // ❌ showing up as empty
}
```

However, if you extract the search param like this, I am able to access my query params

```tsx
export async function loader({ request, params }: LoaderArgs) {
const gqlQueryString =
    new URLSearchParams(new URL(request.url).search).get('gqlQueryString') // ✅  query{getSites}
}
```

### Expected Behavior

The `params` object that get exposed to the `loader`, should contain the same values that is returned from the following:

```tsx
export async function loader({ request, params }: LoaderArgs) {
   const paramsTest1 = params.gqlQueryString // ❌ should exist but doesnt
   const paramsTest2 =  new URLSearchParams(new URL(request.url).search))).gqlQueryString  //  ✅ exists
}
```

### Actual Behavior

Below is a link to the Codesandbox reproducing the error:
https://codesandbox.io/s/params-object--not-getting-populated-v8whw6?file=/app/routes/api/v1/graphQL/index.ts:638-688

Please look at the server logs:

```
1. params
Result: {}
❌ ^^^

2. params?.gqlQueryString
Result:
❌ ^^^

3. new URLSearchParams(new URL(request.url).search).get('gqlQueryString')
Result: query{getSites}
✅ ^^^
```

**Comment by sergiodxa** [comment]
This is an intended behavior.

The `params` object doesn't include search/query params, only params on the route/pathname.

If your route is `routes/$something.tsx` then you will have `params.something` available there, but all search params needs to be read using the URLSearchParams object.

```ts
let { searchParams } = new URL(request.url)
let paramName = searchParams.get("param-name")
```

**Comment by cliffordfajardo** [comment]
>  but all search params needs to be read using the URLSearchParams object.

Ahhh ok

### Followups
So  `routes/$something.tsx`, the params look like this:

```tsx
export async function loader({ params }: LoaderArgs) {
   console.log(params) // {something: 'some_value'}
```

Is there a case where we might multiple entries in the params object?
What the be the case in something like `/people/$peopleid/orders/$orderId`?

```
export async function loader({ request, params }: LoaderArgs) {
   console.log(params) // {peopleid: 'some_value', orders: 'some_value'}
```

**Comment by kiliman** [comment]
Yes, the params object has ALL the params, not just the current route's params. Also note if you use the splat `$` route, the params value is accessed as `params['*']`.
