### ISSUE TITLE
add SerializeFrom to Developer Blog Tutorial

### ISSUE THREAD

**Issue by johnhooks** [remix-run/remix#4110]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

I followed the getting started instructions and began the [Developer Blog Tutorial](https://github.com/remix-run/remix/blob/493b6a06d483562840ffc5e41311f8c7d5bb5c7c/docs/tutorials/blog.md).

### Expected Behavior

I expected to not have type errors while following the tutorial.

### Actual Behavior

In the "A little refactoring" section, the return value of `useLoaderData` has a type error of "Type 'string' is not assignable to type 'Date'", because of a mismatch between `Date` and `string` types generated by Prisma and the serialized type of the `createdAt` and `updatedAt` properties.

I did a little digging and found the `SerializeFrom` type that is new to `1.7.0`. I was able to fix the type error using the following code. Though because there are no examples of this, I have no idea if this is the proper way to type LoaderData.

```ts
import type {SerializeFrom } from "@remix-run/node";
import { json } from "@remix-run/node";
import { Link, useLoaderData } from "@remix-run/react";

import { getPosts } from "~/models/post.server";

export const loader = async () => {
  return json({
    posts: await getPosts(),
  });
};

type LoaderData = SerializeFrom<typeof loader>;

export default function Posts() {
  const { posts } = useLoaderData() as LoaderData;
  return (
    <main>
      <h1>Posts</h1>
      <ul>
        {posts.map((post) => (
          <li key={post.slug}>
            <Link to={post.slug} className="text-blue-600 underline">
              {post.title}
            </Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
```

**Comment by machour** [comment]
We've got some documentation for [contributing](https://github.com/remix-run/remix/blob/main/docs/pages/contributing.md) and you can hop on the [discord server](https://discord.com/invite/remix) and ask on the #contributing channel anytime

**Comment by johnhooks** [comment]
@machour is the  `{}: LoaderArgs` parameter necessary? When it's included there is a `eslint` warning `no-empty-pattern`, there aren't any errors when it's removed.

```ts
export async function loader() {
  return json({
    posts: await getPosts(),
  });
}
```

**Comment by johnhooks** [comment]
It seems what should change in the tutorial, remove explicit `LoaderData` type and allow the type system to infer the return type of the loader. though out the example an use:

```ts
  const { posts } = useLoaderData<typeof loader>();
```
