### ISSUE TITLE
Links to React Router broken in docs

### ISSUE THREAD

**Issue by cmocanu** [remix-run/remix#4132]
### What version of Remix are you using?

Latest remix.run 4 September 2022

### Steps to Reproduce

https://remix.run/docs/en/v1/other-api/react-router

Links are broken. e.g. Outlet points to https://reactrouter.com/en/v6.3.0/components/outlet which is a 404.

### Expected Behavior

Should point to the router documentation.

### Actual Behavior

404

**Comment by machour** [comment]
Thank you for reporting this issue!

I think this will automatically be fixed once react-router v6.4 is officially released. In the meantime, you can browse the relevant documentation on the `dev` branch:  https://reactrouter.com/en/dev

**Comment by machour** [comment]
This is now fixed.
