### ISSUE TITLE
public folder not fully covered by express app

### ISSUE THREAD

**Issue by valotas** [remix-run/remix#4135]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

Run `start.js` from a different directory (monorepo case), for example:

```
node packages/remix/start.js
```

and then try to access favicon.ico:

```
curl http://localhost:3000/favicon.ico
```

### Expected Behavior

The created express app should be able to serve the favicon.ico. In order to do that something like the following is needed:

```js
app.use(express.static(`${remix_root}/public`, { maxAge: "1h" }));
```

### Actual Behavior

The current mapping is

```js
app.use(express.static(`/public`, { maxAge: "1h" }));
```

which covers only `${process.cwd()}/public`

**Comment by brophdawg11** [comment]
If you need to customize this behavior, you can use `@remix-run/express` directly instead of `@remix-run/serve`.

[`@remix-run/serve`](https://remix.run/docs/en/main/other-api/serve) is intended to be a small bare-bones setup.

> It's a production-ready, but basic Node.js server built with Express. If you find you want to customize it, use the @remix-run/express adapter instead.

**Comment by valotas** [comment]
Hi @brophdawg11, thanks a lot for the response. What I did was exactly what you suggested, yet I believe the reported issue is still valid as `@remix-run/serve` cannot be used in a monorepo setup. Yet, if you would like to support this or not, it is up to you.

**Comment by brophdawg11** [comment]
Yeah I think we'd prefer `@remix-run/serve` to be only for simple setups.  Complex setups such as a monorepo or custom Express configurations should be using `@remix-run/express`
