### ISSUE TITLE
Cloudflare KV namespaces expiration seems wrong

### ISSUE THREAD

**Issue by manzano78** [remix-run/remix#414]
Actually, if we set a maxAge to our cloudflare session's cookie, it makes the KV namespace entry being valid for less than a second and that throws an error.

I think there's an issue here:
https://github.com/remix-run/remix/blob/a69a631cb5add72d5fb24211ab2a0be367b6f2fd/packages/remix-cloudflare-workers/sessions/cloudflareKVSessionStorage.ts#L49

Indeed, `.getUTCMilliseconds()` returns milliseconds portion of the time object's value (between 0 and 999) whereas Cloudflare expects a time since UNIX epoch in seconds.

So I think the right code would be something like `.getTime() / 1000`.

**Comment by chaance** [comment]
This should be fixed in 1.1.0.
