### ISSUE TITLE
Hydration error in Firefox (but not in Chrome)

### ISSUE THREAD

**Issue by skywalkery** [remix-run/remix#4142]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

- create a basic app with `npx create-remix` and choose Express Server for deploy: https://github.com/skywalkery/my-remix-app-node
- add any link to css file in the routes/index.tsx, for example: 
```
export function links() {
  return [
    {
      rel: 'stylesheet',
      href: 'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css',
    },
  ];
}
```
- run app `npm run dev`
- open app in Chrome (_Version 104.0.5112.101 (Official Build) (64-bit)_)
- check that there are no errors in console
- turn on 'Disable cache' in devtools
- refresh page a few times and check that there are still no errors
- open app in Firefox (_104.0 (64-bit)_)
- check that there is no errors in console
- turn on 'Disable cache' in devtools
- refresh page a few times and check that there is a hydration error in console:
> Warning: Expected server HTML to contain a matching \<link\> in \<body\>.
link
Scripts

> Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

![Screenshot from 2022-09-06 12-12-13](https://user-images.githubusercontent.com/6942002/188596299-e691c355-692d-40f8-a346-fc873b7645cd.png)

### Expected Behavior

there is no hydration error

### Actual Behavior

there is a hydration error

**Comment by machour** [comment]
Do you happen to have a Firefox extension that's changing the HTML? https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code

**Comment by giltayar** [comment]
This is eerily similar to my issue: https://github.com/remix-run/remix/issues/4175. Check if the problem is LastPass?

**Comment by skywalkery** [comment]
@giltayar Thank you, yes, it is. Then I am closing this issue and will follow yours.
