### ISSUE TITLE
Express JavaScript starter template using .js instead of .jsx causing build failure [v1.0.0-rc.2]

### ISSUE THREAD

**Issue by georgehenderson** [remix-run/remix#415]
Steps to repro:

1. Create a new project `npx create-remix@v1.0.0-rc.2`
<img width="562" alt="Screen Shot 2021-11-20 at 11 05 24 AM" src="https://user-images.githubusercontent.com/1379792/142735152-eccffdc3-3b63-4742-99d5-0609c40148b1.png">

2. `npm run dev` 
<img width="525" alt="Screen Shot 2021-11-20 at 11 08 40 AM" src="https://user-images.githubusercontent.com/1379792/142735208-c2826071-9e3c-42b8-ae2a-774308843588.png">

### Fix
Rename all react files to `.jsx`

**Comment by MichaelDeBoey** [comment]
I just tried this locally and it seems to work for me
