### ISSUE TITLE
CatchBoundary throwing the caught

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#416]
Let's say Parent A has a CatchBoundary for 401s that Child B leverages. Then Child B adds a CatchBoundary to handle 404s. Child B can no longer leverage Parent A's CatchBoundary. It would have to implement 401 handling itself. I this this is unexpected/unfortunate.

I think a solution to this could be quite simple/natural from the user's side of things:

```tsx
export function CatchBoundary() {
  let caught = useCatch();

  switch (caught.status) {
    case 404: {
      return (
        <div>
          <p>There are no jokes to display.</p>
          <Link to="new">Add your own</Link>
        </div>
      );
    }

    default: {
      throw caught;
    }
  }
}
```

So if you don't handle the thrown response, you can throw it again and Remix will send it to the next closest CatchBoundary.

I'm not sure how feasible this is with React though. Thoughts?

**Comment by milamer** [comment]
[Discussion about this feature in the PR](https://github.com/remix-run/remix/pull/264#issuecomment-921992895)

**Comment by kentcdodds** [comment]
@jacob-ebey 

> I'm just not sure if it's something we want as the implementation would essentially be "pre-pass render until it succeeds". I.e: renderToString(...) throws -> pop leaf route and renderToString(...) throws -> pop leaf route and renderToString(...) throws -> pop leaf route and renderToString(...) succeeds -> send response.

I don't see this as a very big issue because it's on the error-path so hopefully less common, and rendering React is pretty fast anyway 🤷‍♂️
