### ISSUE TITLE
Cannot fetch data from  Netlify on-demand builders or functions in a loader (when using experimental-netlify-edge)

### ISSUE THREAD

**Issue by nicolaserny** [remix-run/remix#4176]
### What version of Remix are you using?

experimental-netlify-edge

### Steps to Reproduce

- Create a netlify on-demand builder
- Fetch the on-demand builder from a remix loader

This behavior is very useful when we work with third-party APIs with rate limits (to cache data in Netlify with the TTL attribute).
There is a discussion about this topic [here](https://answers.netlify.com/t/fetching-from-builder-serverless-function-within-an-edge-function/64190/12).

### Expected Behavior

I should get the data from the on-demand builder.
I expect the same behavior as the regular @remix-run/netlify deployment.

### Actual Behavior

You get the following error:  “Recursive requests to the same deployment cannot be processed.”

**Comment by devraj** [comment]
hey @nicolaserny wondering if you ever got to the bottom of this? I started [a discussion](https://github.com/netlify/remix-template/discussions/122) earlier with my findings using edge functions on netlify. I have been using their starter which would suggest that the edge functions should work?

Wondering if you had made the source [for this deployment](https://remix-playground-nico.netlify.app/withrewrite) public?

Thanks for your input.

**Comment by nicolaserny** [comment]
Hey, @devraj, it has been a while since I last played with the Netlify edge function deployment. It was experimental and did not work well with projects containing on-demand builders, so I stuck with the regular Netlify functions.
Now, Netlify edge functions are not in beta anymore. I should give it a try.
Sorry, I don't have the source of this deployment anymore.
I let you know if I have time to look deeper.

**Comment by devraj** [comment]
> Hey, @devraj, it has been a while since I last played with the Netlify edge function deployment. It was experimental and did not work well with projects containing on-demand builders, so I stuck with the regular Netlify functions.
> Now, Netlify edge functions are not in beta anymore. I should give it a try.
> Sorry, I don't have the source of this deployment anymore.
> I let you know if I have time to look deeper.

Thanks heaps for responding.

I tried to create an app and got the same error, wonder if I am missing something. I posted my findings on [this discussion](https://github.com/netlify/remix-template/discussions/122)

**Comment by MichaelDeBoey** [comment]
We now recommend using [the official Netlify Edge adapter](https://github.com/netlify/remix-compute/tree/main/packages/remix-edge-adapter)
