### ISSUE TITLE
Testing and the app/routes

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#42]
Typically we want to co-locate our tests to the files they're testing. Sometimes it's useful to test an individual component. Unfortunately, every file in `app/routes` is considered a route, including `app/routes/__tests__/dashboard.tsx` for example.

Curious what you think about allowing us to configure some ignorable files in that directory. Something like:

```javascript
exports.routeIgnore = ['**/__tests__/**', '**/__mocks__/**']
```

With tests, you have some freedom to put them outside the `routes` directory, but `__mocks__` *does* have to be located next to the file it's mocking, so even if you disagree that putting tests in the `routes` directory is necessary, we may still need this for `__mocks__`.

Thoughts?

**Comment by sombrerodecolores** [comment]
This issue can be closed IMO

I think it was done [here](https://github.com/remix-run/remix/pull/989)

You can accomplish this by using for example:
```
ignoredRouteFiles: [".*", "**/__tests__/**", "**/__mocks__/**"]
```
