### ISSUE TITLE
remix-serve should redirect HTTP traffic to HTTPS

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#420]
I had to do [this](https://github.com/remix-run/remix-jokes/blob/8f786d9d7fa7ea62203e87c1e0bdaa9bda3b28af/app/root.tsx#L25-L46) and it felt like something that should happen for me automagically.

**Comment by tahabesthive** [comment]
```
if(process.env.SSL_FORCE_REDIRECT){
  if(req.headers['x-forwarded-proto'] !== 'https'){ 
    res.redirect('https://' + req.headers.host) 
  }
}
```
