### ISSUE TITLE
Uncaught Error: Dynamic require of "fs/promises" is not supported

### ISSUE THREAD

**Issue by sibasishm** [remix-run/remix#4228]
### What version of Remix are you using?

1.7.1

### Steps to Reproduce

I am wrapping up the loader function with an util function `withAuth`
The implementation of which looks like:
```
import type {
	ActionFunction,
	DataFunctionArgs,
	LoaderFunction,
} from '@remix-run/node';
import type { SupabaseClient, User } from '@supabase/supabase-js';

import { redirect } from '@remix-run/node';
import { getSession } from '~/utils/cookies';
import supabase from '~/utils/supabase';

const withAuth = (
	fn: (
		args: DataFunctionArgs & { user: User; supabaseClient: SupabaseClient }
	) => ReturnType<LoaderFunction> | ReturnType<ActionFunction>
) => {
	return async (context: DataFunctionArgs) => {
		const session = await getSession(context.request.headers.get('Cookie'));
		const accessToken = session.get('accessToken');
		const { user } = await supabase.auth.api.getUser(accessToken);

		if (!user) {
			return redirect('/');
		}

		supabase.auth.setAuth(accessToken);

		return fn({
			...context,
			user,
			supabaseClient: supabase,
		});
	};
};

export default withAuth;
```

### Expected Behavior

The app should run without any console error and hence all my client side code should run for this route. I am not even using fileUploadHandler in any part of my app.
Reference to a related issue: https://github.com/remix-run/remix/issues/3103

### Actual Behavior

I don't understand why I am getting this error, due to which none of my client side code runs.
```
chunk-CUPSZOF3.js:12 Uncaught Error: Dynamic require of "fs/promises" is not supported
    at chunk-CUPSZOF3.js:12:9
    at node_modules/@remix-run/node/dist/upload/fileUploadHandler.js (fileUploadHandler.js:17:16)
    at __require2 (chunk-CUPSZOF3.js:18:50)
```

**Comment by sibasishm** [comment]
Code to reproduce this: https://github.com/BlackBox824/Blackbox.com

**Comment by kiliman** [comment]
You can't use HOFs with Remix loaders and actions. 

https://remix.run/docs/en/v1/guides/constraints#higher-order-functions
