### ISSUE TITLE
Documentation Highlight Error - tutorials/jokes.md

### ISSUE THREAD

**Issue by ryanjames1729** [remix-run/remix#4231]
### What version of Remix are you using?

n/a -> docs issue

### Steps to Reproduce

Error on viewing markup of documentation. Under the heading for 'Read from the database in a Remix loader' the wrong lines are being highlighted. On line 1618 of jokes.md, the correct lines are indicated but does not match what is being highlighted in web view.

![Screen Shot 2022-09-19 at 11 27 37 AM](https://user-images.githubusercontent.com/26652778/191054724-69e60c5c-b884-47ef-8907-52b6fc31bd7e.png)

### Expected Behavior

What should be expected is for lines=[3,5-6,10,13,20-22,24-29,32,56-60] to be highlighted. Lines, 3, 6, 8, etc. are being highlighted.

### Actual Behavior

Lines, 3, 6, 8, etc. are being highlighted.

**Comment by machour** [comment]
Seems to be fixed 👍🏼
