### ISSUE TITLE
Uncaught Error: Dynamic require of "fs/promises" is not supported - when importing json from @remix-run/node

### ISSUE THREAD

**Issue by meglio** [remix-run/remix#4236]
### What version of Remix are you using?

1.7.1

### Steps to Reproduce

```jsx
import { json } from "@remix-run/node";

export default function SomePage(props) {
    return <div>
        Page
    </div>
}
```

Then `yarn dev`.

### Expected Behavior

No errors in developer console.

### Actual Behavior

Error in developer console:

![image](https://user-images.githubusercontent.com/282177/191274209-88932318-4bf0-4f9d-a9d3-b3ae7365e3d7.png)

### package.json

```json
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "start": "remix-serve build"
  },
  "dependencies": {
    "@remix-run/node": "^1.7.1",
    "@remix-run/react": "^1.7.1",
    "@remix-run/serve": "^1.7.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.7.1",
    "@remix-run/eslint-config": "^1.7.1",
    "eslint": "^8.20.0"
  },
  "engines": {
    "node": ">=14"
  },
  "packageManager": "yarn@3.2.3"
}


```

### Yarn and Node

* node version: 18.9.0
* Yarn: 3.x

NB. I tried creating the project with using Yarn 1.x and it worked fine. The problem appears after migrating to yarn 3.x

Might be related:

https://github.com/yarnpkg/berry/issues/638#issuecomment-1124629341

Looks like Yarn 3.x supports ESM module loading.  So I tried the following in my `.yarnrc.yml` file, following the recommendations from the link above:

```yml
yarnPath: .yarn/releases/yarn-3.2.3.cjs
pnpEnableEsmLoader: true
nodeLinker: "pnp"
```

But this did not help.

So, the thread above makes me think that yarn 3.x should work with Remix. But it does not. I'm wondering if this is Remix or Yarn issue?

The only workaround that works for me is to rollback to using `nodeLinker: node-modules`.

**Comment by mwood23** [comment]
Just hit this. You need to import things from `@remix-run/cloudflare` instead

**Comment by meglio** [comment]
@mwood23 I am not using cloudflare.

**Comment by mkikets99** [comment]
> @mwood23 I am not using cloudflare.

I hit this too...
A temp workaround is just change how "fs/promises" imports...

You need to change in `node_modules/@remix-run/node/dist/upload/fileUploadHandler.js` next row:
```diff
var fs = require('fs');
-var promises = require('fs/promises');
+var promises = require('fs').promises;
var os = require('os');
```

it is at the top of the file... but still annoys...

**Comment by meglio** [comment]
> So... a fix for devs must be just updating a node version... or change how they import promises from fs...

Could you explain this part, please, @mkikets99 ?
What devs do you mean - the Remix devs? If so, what node version do you mean? I am the package user and my Node version is 18.9, but it does not prevent the error from happening.

**Comment by mkikets99** [comment]
> > So... a fix for devs must be just updating a node version... or change how they import promises from fs...
> 
> Could you explain this part, please, @mkikets99 ? What devs do you mean - the Remix devs? If so, what node version do you mean? I am the package user and my Node version is 18.9, but it does not prevent the error from happening.

Yes, i meant the Remix Devs.
But... i think on TS it will be better to use something like
```typescript
import { promises as fspromises } from "fs";
```
rather than 
```typescript
import fspromises from "fs/promises"
```
because that is causing the error...

**Comment by mkikets99** [comment]
Node changed the way how "sub-modules" are imported...
And `fs/promises` are now a part of `fs`... maybe from Node v12...
and Node trying to not use the "path-requirement" for integrated values...
But TypeScript skipped this part... and allowing to use path import while Node doesn't like it

**Comment by mkikets99** [comment]
I may rewrite that file on TS... a bit later...
Now i just added a script in `postinstall` section of scripts...

```shell
cat ./node_modules/@remix-run/node/dist/upload/fileUploadHandler.js | sed -e \"s/var promises = require('fs\\/promises');/var promises = require('fs').promises;/g\" | tee ./node_modules/@remix-run/node/dist/upload/fileUploadHandler.js >/dev/null
```
you can try run this command in your project root folder and this must solve it...
Maybe in 2-3 days ill make a PR with fix...

**Comment by naturalethic** [comment]
In my case, working with sessions, I had not specifically scoped my module to the server, e.g.: `session.server.ts` -- so the module had leaked to the client producing the titled error.

**Comment by meglio** [comment]
So, at the end of the day, is it something that Remix can/going to fix/improve?

**Comment by NRodriguezcuellar** [comment]
Also running into this problem

**Comment by ErlanBelekov** [comment]
also hit this problem

**Comment by ErlanBelekov** [comment]
This problem happened to me because server-only code was in the client.
I had to re-name the server-only files with `.server` extension and it worked!

I though Remix would do a better job at distinguishing the server/client JS bundles.

**Comment by pcattori** [comment]
[Remix requires Node v14 or newer](https://remix.run/docs/en/v1/tutorials/blog#prerequisites), so changing internal code should not be necessary since [importing from `fs/promises` was added in Node v14](https://nodejs.org/api/fs.html#promises-api)(click on "history" dropdown to see it).

As @ErlanBelekov points out, this is likely due to server code being incorrectly included in your browser/client bundle.

In the example from @meglio :

```tsx
import { json } from "@remix-run/node";

export default function SomePage(props) {
    return <div>
        Page
    </div>
}
```

The `@remix-run/node` import should be treeshaken from the browser bundle. I'll look into why its not.

**Comment by shubumpc91** [comment]
I was facing the same issue.

Solution that worked for me : moved **createCookie** helper to **.server** file

**Comment by alexpunct** [comment]
also facing it

**Comment by kiliman** [comment]
@alexpunct like the others, move the import into a `.server` file and re-export it. I think esbuild has issues tree-shaking node internal packages. I typically have a `node.server` file that I re-export from.

**Comment by jshay21** [comment]
@kiliman We have been struggling with this for a while.  Could you provide a brief example of how to import and re-export this?

**Comment by kiliman** [comment]
```ts
// app/libs/node.server.ts

import path from 'node:path';
export * as fs from 'node:fs';
export * as fsp from 'node:fs/promises';
export { path };

// route.tsx

import { fs } from '~/libs/node.server'
```

**Comment by capaj** [comment]
@mwood23 thanks for mentioning this.
I had used @remix-run/node by mistake and got this error when deploying to cloudflare.
Would be nice if remix could like validate when running a build for cloudflare and throw error when it sees `@remix-run/node` import
