### ISSUE TITLE
`fetcher.data` is `undefined` even if `fetcher.type === "done"`

### ISSUE THREAD

**Issue by nullndr** [remix-run/remix#4248]
### What version of Remix are you using?

1.7.1

### Steps to Reproduce

Using `fetcher.submit` will result in `Uncaught TypeError: fetcher.data is undefined`

```tsx
export const loader = () => {
  return { data: "Some data" };
};

export default function Index() {
  let { data } = useLoaderData<typeof loader>();
  const fetcher = useFetcher<ReturnType<typeof loader>>();

  if (fetcher.type === "done") {
    data = fetcher.data.data; // fetcher.data is undefined
  }

  return (
    <div>
      <div>{data}</div>
      <button onClick={() => fetcher.submit({}, { method: "get" })}>
        Click me
      </button>
    </div>
  );
}
```

Note that `fetcher.type` will results in `"done"` before the request has been done.

You can find [here](https://github.com/nullndr/remix-bug) a basic demonstration.

### Expected Behavior

`fetcher.type` is equal to `"done"`, so `fetcher.data` should contains the fetched data.

### Actual Behavior

Even if `fetcher.type` is equal to `"done"`, `fetcher.data` results in `undefined`.

**Comment by JuliusMoehring** [comment]
Hey, not sure what you are trying to achieve, but it looks like a little misunderstanding. If you need to load some data server-side to generate the HTML, you should use the `loader` function in combination with the `useLoaderData()` hook ([remix docs](https://remix.run/docs/en/v1/api/remix#useloaderdata)). If you want to load some data initiated by a user action (e.g. an onClick event on a button), you should create an `action` function and use either the `<Form>` element from Remix or the `useFetcher()` hook ((remix docs)[https://remix.run/docs/en/v1/api/remix#usefetcher]).

Following your example, the following code should work:

```typescript
import { ActionFunction, json } from "@remix-run/node";
import { useFetcher, useLoaderData } from "@remix-run/react";

export const loader = () => {
  return { data: "Some data" };
};

export const action: ActionFunction = async () => {
  return json({ data: "Some different data" });
};

export default function Index() {
  const { data } = useLoaderData<typeof loader>();

  const fetcher = useFetcher();

  return (
    <div>
      <div>{fetcher.data ? fetcher.data.data : data}</div>
      <button onClick={() => fetcher.submit({}, { method: "post" })}>
        Click me
      </button>
    </div>
  );
}
```

Please note that reassigning the data from the `useLoader()` hook to the data from the `useFetcher()` hook does not make sense. You can just conditionally render the initial data from the loader if there is no `fetcher.data` and if there is, render whatever `fetcher.data` is.

I hope that solves your problem.

If you have more questions, consider joining the [Remix Discord](https://discord.com/invite/remix)

**Comment by nullndr** [comment]
@JuliusMoehring the `useFetcher` hook can be used to call loaders.

The docs say

> But sometimes you want to call a loader outside of navigation, or call an action (and get the routes to reload) but you don't want the URL to change. [...]

However, I checked the new release (`1.7.2`) and this problem looks fixed, so I'm going to close this issue.
