### ISSUE TITLE
Discord gives INVALID INVITE

### ISSUE THREAD

**Issue by iangregsondev** [remix-run/remix#4278]
### What version of Remix are you using?

N/A

### Steps to Reproduce

go to https://discord.com/invite/remix

and it displays that its INVITE INVALID

### Expected Behavior

Allow me to register into discord

### Actual Behavior

Gives INVITE INVALID

**Comment by PiotrJander** [comment]
I'm having the same issue

**Comment by kiliman** [comment]
Try this one until they get around to updating it.

https://discord.com/invite/drKv3mWzcj

**Comment by iangregsondev** [comment]
Thanks @kiliman - Works great!
