### ISSUE TITLE
First loader not getting gists data

### ISSUE THREAD

**Issue by anglee** [remix-run/remix#43]
I am trying to go through the tutorial and at step [Your First Loader](https://remix.run/dashboard/docs/tutorial/loading-data#your-first-loader), after adding the file **loaders/routes/gists.js**, I am still seeing data being `null`, not seeing the gist
Here is what I have: https://github.com/anglee/my-remix-app
I tried to console.log in the gists loader but didn't see the log.
![image](https://user-images.githubusercontent.com/1767921/98494549-3ab72d80-220b-11eb-9610-ae491aba5bda.png)
![image](https://user-images.githubusercontent.com/1767921/98494735-ac8f7700-220b-11eb-99de-2e3b0e995aa7.png)
I have confirmed that I do see the gist when I visit https://api.github.com/gists in the browser or cURL in terminal.

**Comment by machour** [comment]
Not applicable anymore.
