### ISSUE TITLE
Importing from `baseUrl` breaks JS functionality

### ISSUE THREAD

**Issue by insuusvenerati** [remix-run/remix#4308]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

`git clone https://github.com/insuusvenerati/remix-baseurl-bug` 
`yarn install`
`yarn dev`

* Click the button labeled "test"
* Check browser console for "Hello World!"
* Observe error message in console `Uncaught TypeError: Error resolving module specifier “util/coolFunction”. Relative module specifiers must start with “./”, “../” or “/”.`
* Observe `app/routes/index.tsx` importing `myCoolFunction` from `"util/coolFunction` 

### Expected Behavior

I should be able to import modules from the `baseUrl` as configured in `tsconfig.json` and everything function normally. 

### Actual Behavior

When importing a module from the `baseUrl` from `tsconfig.json`, **all** JavaScript functionality breaks in the browser and an error is logged to the browser console

```
Uncaught TypeError: Error resolving module specifier “util/coolFunction”. Relative module specifiers must start with “./”, “../” or “/”.
```

**Comment by markdalgleish** [comment]
This isn't something we're aiming to support, but we do support `~` as an alias for your app directory. It works if I update `app/routes/index.ts` in your example like this:

```diff
-import { myCoolFunction } from "util/coolFunction";
+import { myCoolFunction } from "~/../util/coolFunction";
```

Obviously `~/../` is a bit awkward, so I'd recommend moving the `util` directory into your app directory so you can write it like this:

```ts
import { myCoolFunction } from "~/util/coolFunction";
```
