### ISSUE TITLE
Meta tags exported from route are getting overridden by the root page meta tags.

### ISSUE THREAD

**Issue by shailander** [remix-run/remix#4327]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

1. Default export some meta tags from root.tsx inside Document
 ```
 <meta property="og:title" content="Root title" />
 <meta property="og:description" content="Root Description" />Ï
```

2. Export meta tags from a route
```
export const meta: MetaFunction = () => {
  return {
    'og:title': `Custom Route Title`,
    'og:description': `Custom Route Description`,
  }
}
```

### Expected Behavior

The custom route meta tag should override or have high priority than the root page meta tags if they have the same property(Eg. og:title , og.description)

### Actual Behavior

Both the meta tags are there in the head but since the root meta tags are at the top, they are currently being displayed

**Comment by kiliman** [comment]
I'm on Remix 1.7.2 and it is working correctly. I'm not sure if this is a bug in 1.6.5 or not.

```ts
// root.tsx
export const meta: MetaFunction = () => ({
  charset: "utf-8",
  title: "New Remix App",
  viewport: "width=device-width,initial-scale=1",
  "og:title": `Root Title`,
  "og:description": `Root Description`,
});

// routes/parent/child.tsx
export const meta: MetaFunction = () => ({
  "og:title": `Custom Route Title`,
  "og:description": `Custom Route Description`,
});
```
<img width="741" alt="image" src="https://user-images.githubusercontent.com/47168/194115105-d7cc0f3d-d6d9-42d0-ad87-150491d08fde.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/47168/194115038-18a1e191-ee15-4c19-af33-06f328328a36.png">

**Comment by machour** [comment]
@shailander please try with the latest version of remix and tell us if it works correctly.

**Comment by shailander** [comment]
@kiliman @machour Yeah, the meta tags is working as expected. I was working on an authorized page and the crawler tools were being redirected to the homepage because of that and I was not able to see the meta tags on fetching. Locally I can see the tags being updated.✌🏻
