### ISSUE TITLE
Private GitHub stack templates don't work with the `releases/latest/download/{filename}` url structure

### ISSUE THREAD

**Issue by johnmberger** [remix-run/remix#4328]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

Instantiate a stack using a template from a private GitHub repo, an access token, and the "latest" release url:

```
npx create-remix@latest ./my-new-project --template https://github.com/owner/repo/releases/latest/download/stack.tar.gz --token myaccesstoken
```

### Expected Behavior

Since the `https://github.com/owner/repo/releases/latest/download/stack.tar.gz` url should always link to the latest release tag, I would expect the stack validation to work successfully and the remix project to initialize successfully. 

### Actual Behavior

The command fails with the following error: `🚨 The template file could not be verified. Please double check the URL and try again.`

However, if you do know the latest release tag, manually include it, and try again:
```
npx create-remix@latest ./my-new-project --template https://github.com/owner/repo/releases/download/v.1.1/stack.tar.gz --token myaccesstoken
```
Then it works just fine.

I suspect this is because there's a quirk in the Github URL structure between the latest tag and a specified version (`releases/latest/download` vs. `releases/download/version`) and the Remix code isn't handling the former.

My org maintains a private Github monorepo that includes a stack tarball and it would be great to allow users to link directly to the latest release instead of having to know the exact version number.

**Comment by machour** [comment]
Thank you @johnmberger!
