### ISSUE TITLE
Unable to deploy Remix to AWS using Architect

### ISSUE THREAD

**Issue by chanesteves** [remix-run/remix#4372]
### What version of Remix are you using?

1.0.6

### Steps to Reproduce

1. Create a remix app
2. Install @architect/architect
3. Run `arc init`
4. Run `arc deploy`

### Expected Behavior

Remix deploys successfully to AWS and website becomes accessible.

### Actual Behavior

Remix deploys successfully to AWS but site throws "Internal Server Error" when accessed. The log in _Cloudwatch_ says "Cannot find module '/var/task/node_modules/@remix-run/dev/server-build' imported from /var/task/index.mjs\nDid you mean to import @remix-run/dev/server-build.js?"

![Screenshot 2022-10-16 222909](https://user-images.githubusercontent.com/5785059/196042057-0724a1b2-7d15-4727-985f-4cd6838cfbb1.jpg)
![Screenshot 2022-10-16 222852](https://user-images.githubusercontent.com/5785059/196042059-b66c4e76-c286-424b-95bb-3ade98c6f35b.jpg)
![Screenshot 2022-10-16 222631](https://user-images.githubusercontent.com/5785059/196042061-9cc7a114-b531-4c6c-ba39-57a1a151d660.jpg)

**Comment by machour** [comment]
Could you please try with latest remix version and make sure you select the "Architect" template when creating the project?

**Comment by chanesteves** [comment]
@machour I tried upgrading _remix_ to the latest version and ran `arc init` but no luck. Unfortunately, I can't reselect `Architect` template because the app is created inside [Nx](https://nx.dev/) monorepo.

**Comment by chanesteves** [comment]
It turned out I only had to define `serverBuildTarget` inside `remix.config.js`. I've rebuilt it, ran `arc deploy` and the deployment was successful.

`/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
...
  serverBuildTarget: "arc",
...
};`
