### ISSUE TITLE
fetch() doesn't return correct Response type

### ISSUE THREAD

**Issue by christian-reichart** [remix-run/remix#4395]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

Inside the remix project try

```javascript
const a = await fetch('https://google.com')
console.log('a instanceof Response: ', a instanceof Response) // -> false
```

This probably has to do with this commit: 
https://github.com/remix-run/remix/commit/25b4c83b10c5bc4d84ea81407e7de1a0e4f43df4#diff-87ec1c3c130fe3481b9f1c542b1d8a53548882d33c73c68b894fd442d606afc0

A current workaround I found thanks to @milamer is to include 
```javascript
import { Response } from '@remix-run/web-fetch'
```
in the file.

### Expected Behavior

instanceof Response should be true

### Actual Behavior

instanceof Response is false

**Comment by machour** [comment]
Hi @christian-reichart, where are you importing `fetch` from?

**Comment by christian-reichart** [comment]
Hi @machour , I don't import it specifically, so it's the global fetch.

**Comment by machour** [comment]
Any reason why you're not using remix's fetch?

```js
import { fetch } from "@remix-run/node";
```

**Comment by christian-reichart** [comment]
Thanks for your response @machour ! Correct me if I'm wrong but I was under the impression that Remix is supposed to let you use fetch and Response without any import. https://remix.run/docs/en/v1/other-api/fetch Is the documentation outdated?

**Comment by machour** [comment]
Now I'm the one confused 😅 I'll circle back with the team on this point and let you know what's the right approach, and will update the docs if necessary.

In the meantime, does using `fetch` from `@remix-run/node` fix your original issue?

You might also be interested in reading the "Moving closer to The Platform™" part from the 1.5.0 release notes : https://github.com/remix-run/remix/releases/tag/v1.5.0

**Comment by acoreyj** [comment]
@machour I have run into this issue with reimix-run/node and external libraries that use globals and instanceof Response.

I have been able to work around but latest is in a nested dependency using oauth4webapi

Any thoughts from the team yet on how to fix the inconsistent globals?

**Comment by acoreyj** [comment]
Found fix and made a merge request.

Here is patch that can be used with patch-package https://gist.github.com/acoreyj/37eff1fdc459dbea31515d5d40be7b35

**Comment by jacob-ebey** [comment]
Should be closed by https://github.com/remix-run/remix/pull/7109
