### ISSUE TITLE
Cannot submit form to 3rd party host url when using useSubmit

### ISSUE THREAD

**Issue by drishit96** [remix-run/remix#4423]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

If my host is `example.com` and I want to submit a form to another host, let's say `foobar.com` and I write the following code:
```javascript
const formData = new FormData(event.currentTarget);
submit(formData, {
    action: "https://foobar.com/v1/order",
    method: "post",
});
```

### Expected Behavior

The form should be submitted to `foobar.com`

### Actual Behavior

Form is submitting to the same host, i.e `example.com`

If I use the browser default form: `<form action ="https://foobar.com/v1/order" method="post"></form>` it works. But I need to do fetch some additional data before submitting, so I want to use useSubmit.

**Comment by drishit96** [comment]
I think this is where it happens:
https://github.com/remix-run/remix/blob/3832d457b34d7a62633bf86a2606971263e710cb/packages/remix-react/components.tsx#L1256

**Comment by kiliman** [comment]
Also, note that if your external API returns data, it must be in JSON format, as that's what Remix expects. And if it returns a redirect response, it will most likely trigger a full page refresh. Remix sends a special status/header for redirects initiated by client-side fetch.

**Comment by jjebennett** [comment]
Did this get implemented? I'm using remix version 1.10 and if I try to use an external URL as the action of a form it appends the URL to the routes URL... eg.  action="https://foobar.com/v1/order" renders as action="myCurrentInternalURL/https://foobar.com/v1/order"

**Comment by jamalsoueidan** [comment]
Same here, I had to use the fetch webapi to handle this case :(

**Comment by brophdawg11** [comment]
This feels more like a feature request than a bug as the Remix hooks are intended to work against known Remix endpoints.  They do things such as append `?_data` and `?index`, as well as look for responses with specific headers, etc.  I think your best bet here is to just use the native form `submit` event and make your own `fetch` call.

**Comment by drishit96** [comment]
@brophdawg11 If the only way is to use a fetch call, then how will the page work if JavaScript is disabled?

**Comment by brophdawg11** [comment]
> But I need to do fetch some additional data before submitting, so I want to use useSubmit.

This also will not work with javascript disabled 😉 . Maybe you want to just use `<form>`?

**Comment by drishit96** [comment]
Oops, my bad, I totally missed that 😅. Thanks for mentioning it.

**Comment by nilansaha** [comment]
Kinda seems weird that you guys just wont add this and override actions. Any serious folks have separate backend url. Not sure why you guys are going out of your way to patch the origin and then not even provide a way out.
