### ISSUE TITLE
[Bug]: docs rerender when hovering over links

### ISSUE THREAD

**Issue by byCedric** [remix-run/remix#443]
### Which Remix packages are impacted?

- [x] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.3? (it's the docs website, but couldnt find the code)

### Steps to Reproduce

- Go to the [Jokes guide](https://remix.run/docs/getting-started/dev/tutorials/jokes#styling)
- Expand "💿 Copy this to `app/styles/global.css`" which is pretty long (360 lines)
- Scroll down
- Hover over random links

### Expected Behavior

Not to refresh

### Actual Behavior

It rerenders/refreshes and closes the collapsible, while still maintaining the same scroll position. I got a bit lost.

**Comment by jasonLaster** [comment]
@byCedric were you able to consistently reproduce the problem? I just tried and did not see it. Here's a quick [replay](https://app.replay.io/recording/1f0ad975-aa32-4a71-b0da-bb93b3fd55c0?point=2271629875609214213018499692888259&time=1309&hasFrames=false) of my attempt.

**Comment by byCedric** [comment]
Yes! Here is a video, with "Highlight updates" enabled from React Devtools. I'm on Windows 11 + chrome.

https://user-images.githubusercontent.com/1203991/143019726-93907d34-c3db-4b09-909d-a077a2357f28.mp4

**Comment by girishk21** [comment]
![image](https://user-images.githubusercontent.com/61074716/143020910-ffd6812a-db1a-47a2-a6b9-cf819acdb290.png)
 it's sending a request and immediately reloads the page 🤔

**Comment by mikebobadilla** [comment]
Keeps happening to me too

**Comment by SjoenH** [comment]
I think the repro is simpler than explained in the top description.

**Steps to Reproduce**    
- Go to the [Jokes guide styling section](https://remix.run/docs/getting-started/dev/tutorials/jokes#styling)
- Hover over the `the font`-link.

**Comment by chaance** [comment]
We made some changes to prefetching behavior in 1.1.0. Are you able to reproduce this after updating?

**Comment by SjoenH** [comment]
I cannot reproduce it anymore on the [live page.](https://remix.run/docs/getting-started/v1/tutorials/jokes#styling) :+1:
