### ISSUE TITLE
No loader is configured for .glb and .hdr files

### ISSUE THREAD

**Issue by ikarus-akhil** [remix-run/remix#4430]
### What version of Remix are you using?

1.7.3

### Steps to Reproduce

I am trying to put 3D models on my website using model viewer but getting `No loader is configured for ".glb" files` and `No loader is configured for ".hdr" files` errors.

### Expected Behavior

The webpage should have rendered the 3D model.

### Actual Behavior

Getting no loader is configured error.

**Comment by machour** [comment]
Related discussion: https://github.com/remix-run/remix/pull/4094

**Comment by machour** [comment]
@ikarus-akhil you could provide a PR to add support for both files extensions in order to speed up things. Check https://github.com/remix-run/remix/pull/3985 for an example on how to do that.

**Comment by ikarus-akhil** [comment]
@machour Thanks for the reply, have picked up the issue and will work on it.

**Comment by ikarus-akhil** [comment]
@machour Thanks for the reply, have picked up the issue and will work on it.
