### ISSUE TITLE
Sticky CSS Not Working

### ISSUE THREAD

**Issue by ikarus-akhil** [remix-run/remix#4458]
### What version of Remix are you using?

1.7.4

### Steps to Reproduce

I have a navbar that is rendered on all the pages and has `sticky` positioning using tailwind, but it does not work and goes away after scrolling a little. But when I change the positioning to `fixed` it works fine. I also used `!important`, but it did not work either.
Here is the navbar's code:
```js
<div className="z-20 bg-white sticky top-0 max-h-18">
  <ul>
    <li>Home</li>
    <li>ABout Us</li>
  </ul>
</div>
```
Here is the layout in `root` file:
```js
unction Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {/* <h1 className="z-60 sticky top-0 bg-red-500">HELLO</h1> */}
      {children}
      <Footer />
    </>
  );
}
```

### Expected Behavior

The navbar should stick at the top.

### Actual Behavior

The navbar goes away after scrolling a little.

**Comment by machour** [comment]
Hi @ikarus-akhil, this is not a Remix issue, but it's a tailwind usage problem.
I would advise asking on [Tailwind's discord](https://v1.tailwindcss.com/discord) for help!
