### ISSUE TITLE
🗺 Meta Export Updates

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4481]
Giving apps more control over the meta tags created by route meta exports and removing some limitations with the current API.

## Progress

- [x] [RFC Here](https://github.com/remix-run/remix/discussions/4462)
- [x] PR: https://github.com/remix-run/remix/pull/4610

## Related Issues

#4020 #4260 #2598 #3903

**Comment by machour** [comment]
Implemented in #4610
