### ISSUE TITLE
🗺 Flat Routes

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4483]
An improved file system route convention to help route visibility and module co-location.

## Progress

- [x] RFC: https://github.com/remix-run/remix/discussions/4482
- [x] PR: #4880

## Community Implementation

https://github.com/kiliman/remix-flat-routes

**Comment by ryanflorence** [comment]
@kiliman has offered to send a PR :)

**Comment by kiliman** [comment]
Yes I’ll be back from Thanksgiving vacation on Monday.

**Comment by kiliman** [comment]
Initial PR https://github.com/remix-run/remix/pull/4716

**Comment by mcansh** [comment]
Next Steps: @pcattori to review updates https://github.com/remix-run/remix/pull/4880

**Comment by mcansh** [comment]
merged!

**Comment by kiliman** [comment]
Awesome!

![image](https://user-images.githubusercontent.com/47168/210888517-c16121d5-5ef8-4d3f-9f5a-aab4e7146664.png)

**Comment by machour** [comment]
Awesome!
We need to document this before shipping it in a release
