### ISSUE TITLE
scroll-restoration breaks embedded iframe in chrome incognito

### ISSUE THREAD

**Issue by jjhiggz** [remix-run/remix#4494]
### What version of Remix are you using?

1.7

### Steps to Reproduce

1. create a remix app that uses scroll restoration (must be deployed)
2. create a static website that references that remix app with an iframe
3. open up that website in an incognito tab on chrome

This will cause issues because `sessionStorage` will not be defined inside of that iframe. The only spot I've yet to find it for sure is in `scroll-restoration` but will continue digging

### Expected Behavior

It should load the site no problems

### Actual Behavior

![Screen Shot 2022-11-02 at 8 06 33 AM](https://user-images.githubusercontent.com/59105254/199510377-41a7edcb-9fe8-4c6e-bd73-945207c64bc7.png)

A bunch of errors

**Comment by jjhiggz** [comment]
Digging into the code I found this line:

```ts
    try {
      let positions = JSON.parse(sessionStorage.getItem(STORAGE_KEY) || "{}");
      let storedY = positions[window.history.state.key];
      if (typeof storedY === "number") {
        window.scrollTo(0, storedY);
      }
    } catch (error) {
      console.error(error);
      sessionStorage.removeItem(STORAGE_KEY);
    }
 ```
 The problem is that in the catch, it assumes that sessionStorage is defined, which embedded in an iframe on incognito, it just isn't defined. I think this could be fixed with a simple
 
`sessionStorage?.removeItem?.(STORAGE_KEY)`

**Comment by jjhiggz** [comment]
For the record, I'm pretty new to open source and I genuinely have no idea how to 
A: write tests for this
B: reproduce the issue outside of a deployment

but I would really love to get more into open source work, so if anybody has pointers this seems like it would be an awesome learning opportunity

**Comment by jjhiggz** [comment]
The use case for us over at Remenu, is we are trying to embed restaurant menus into wordpress sites using iframes.

Something that should look like this 

 
![Screen Shot 2022-11-02 at 8 12 46 AM](https://user-images.githubusercontent.com/59105254/199511929-5245ed4a-b555-4336-bc97-6d0fba17168e.png)

**Comment by machour** [comment]
Hey @jjhiggz and thank you for this report and detective work 👌🏼 

I'm not sure on how to test this either, but opening a pull request with the suggested changes, and asking for guidance there will likely yield more results. Here's the relevant [contributing guide section](https://github.com/remix-run/remix/blob/main/docs/pages/contributing.md#making-a-pull-request), make sure you target the `dev` branch!

(If this is your first PR, I'll be more than glad to guide you, just let me know)

**Comment by machour** [comment]
Woops, there's already an issue logged for this problem: https://github.com/remix-run/remix/issues/3659

Closing your report as a duplicate, welcome to OSS 🎉 😅 

(don't hesitate to further comment here for guidance, or hop on [our Discord server](https://rmx.as/discord) and ask for guidance in #contributing)
