### ISSUE TITLE
npx create-remix@latest giving error

### ISSUE THREAD

**Issue by Daggron** [remix-run/remix#4519]
### What version of Remix are you using?

NA

### Steps to Reproduce

I am trying to create a remix application but when I am running the command `npx create-remix@latest` it is throwing an error.

run `npx create-remix@latest`

Node version 16
Npm version 8

### Expected Behavior

A blank template app should be created.

### Actual Behavior

Getting the below error

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @remix-run/dev@1.7.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhay/.npm/_logs/2022-11-05T09_21_30_182Z-debug-0.log

**Comment by machour** [comment]
Weird, as @remix-run/dev 1.7.5 seems to be published.

Just tried the command without problems over here, see below.
Can you `cd` into your app and try `npm install` there?

```
🍺  ~ $ npx create-remix@latest
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y
? Where would you like to create your app? bug-4519
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

added 1047 packages, and audited 1048 packages in 1m

225 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into "/Users/didou/bug-4519" and check the README for development and deploy instructions!
```

**Comment by Daggron** [comment]
> Weird, as @remix-run/dev 1.7.5 seems to be published.
> 
> Just tried the command without problems over here, see below. Can you `cd` into your app and try `npm install` there?
> 
> ```
> 🍺  ~ $ npx create-remix@latest
> Need to install the following packages:
>   create-remix@latest
> Ok to proceed? (y) y
> ? Where would you like to create your app? bug-4519
> ? What type of app do you want to create? Just the basics
> ? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
> ? TypeScript or JavaScript? TypeScript
> ? Do you want me to run `npm install`? Yes
> npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
> npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
> npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
> npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> 
> added 1047 packages, and audited 1048 packages in 1m
> 
> 225 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 💿 That's it! `cd` into "/Users/didou/bug-4519" and check the README for development and deploy instructions!
> ```

Can't do Cd or npm i as app is not generated

**Comment by machour** [comment]
Can you paste the whole installation log here please?

**Comment by Daggron** [comment]
Sure here is the entire log file
[2022-11-05T09_21_30_182Z-debug-0.log](https://github.com/remix-run/remix/files/9945239/2022-11-05T09_21_30_182Z-debug-0.log)

**Comment by MichaelDeBoey** [comment]
Going to close this one as I just tried this locally & it's working like it should

**Comment by MuddyBootsCode** [comment]
I'm getting this error locally as well.

**Comment by machour** [comment]
What error are you getting?
