### ISSUE TITLE
--watch is not working on bug-report-test

### ISSUE THREAD

**Issue by gijsroge** [remix-run/remix#4520]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

run `yarn && yarn build` and after that run `yarn bug-report-test --watch` in the root of this repo.

### Expected Behavior

-

### Actual Behavior

When you try to run the `bug-report-test` you get the error message `error: unknown option '--watch'`

**Comment by brophdawg11** [comment]
Playwright does not have a `--watch` command

https://playwright.dev/docs/running-tests

**Comment by gijsroge** [comment]
@brophdawg11 

Correct, I wasn't aware playwright was used my bad, the reason I created the issues was because the instructions reference a `--watch` parameter -> https://github.com/remix-run/remix/blob/dev/integration/bug-report-test.ts 

I can submit a quick PR to remove the part that mention's the `--watch` param if you like.

**Comment by brophdawg11** [comment]
Ohhh - yes that 's incorrect - a PR would be great!  Thank you!
