### ISSUE TITLE
File in a package (outside of /app) gets incorrectly emptied

### ISSUE THREAD

**Issue by Andarist** [remix-run/remix#4526]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

1. open a file in `/app`
2. add an import for `pkg/file.server`

### Expected Behavior

This import should not be emptied because it's coming from a package that might not use Remix `.server.js` convention

### Actual Behavior

The module gets emptied. The code responsible for this only checks the output of the `path.resolve()`:
https://github.com/remix-run/remix/blob/cb7416beb87f2f008f05bafb0c25d263bf59851f/packages/remix-dev/compiler/plugins/emptyModulesPlugin.ts#L18-L26

That only concatenates paths when the segment is a module specifier (with a subpath) and thus it passes through your check. The comment there suggests that this should not happen for things in `node_modules` though.

**Comment by pcattori** [comment]
Not reproducible in 1.19.2
