### ISSUE TITLE
Not able to serve build folder

### ISSUE THREAD

**Issue by tempcoderr** [remix-run/remix#4534]
### What version of Remix are you using?

1.7.4

### Steps to Reproduce

I have a remix app and I want to containerize it using Docker and to serve the static content from it I have created a `server.js` file with the following code:
```js
const express = require("express");
const app = express();
const remix = require("@remix-run/express");

app.all("*", remix.createRequestHandler({ build: require("./build") }));

const PORT = 3055;
app.listen(PORT, () => {
  console.log(`Server running at port ${PORT}`);
});

```
I don't know how or what to server, and the problem with this is that when I build the image and then run it, the resulting webpage is not complete. There are no images, css and even some written content is missing. I am not even able to change the build folder to `./public/build`.

### Expected Behavior

The resulting webpage should render correctly.

### Actual Behavior

Images, css and some content is missing.

**Comment by EternallLight** [comment]
I find myself in exactly the same situation here and would very appreciate if you had written a quick line or two instead of silently closing the issue.
