### ISSUE TITLE
Minified React error

### ISSUE THREAD

**Issue by tempcoderr** [remix-run/remix#4537]
### What version of Remix are you using?

1.7.4

### Steps to Reproduce

I had posted an issue #4534, and from that I made a few path changes to the build folder to get the app running using express(to serve the static app). Now the only issue that I am facing are:
1. It is not able to find the favicon no matter where I place it.
2. Minified React error (Check attached screenshot).
![Screenshot (22)](https://user-images.githubusercontent.com/117140065/200321172-6e967deb-2209-4b97-961b-9f6a7be32f1f.png)
How to resolve these issue?

### Expected Behavior

The app should run without error.

### Actual Behavior

Giving Minified React and favicon not found errors.

**Comment by quantuminformation** [comment]
just got this today - investigating

**Comment by pthieu** [comment]
got this today

**Comment by aldinokemal** [comment]
got this today +1
