### ISSUE TITLE
[Bug]: CF Workers broken with default template

### ISSUE THREAD

**Issue by marbiano** [remix-run/remix#458]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [x] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.3

### Steps to Reproduce

1. Run `npx create-remix@latest`
2. Select `cloudflare-workers`
3. Run `npm start`

### Expected Behavior

Miniflare should start a dev server normally, as it was doing it in `0.21`.

### Actual Behavior

![Screen Shot 2021-11-22 at 11 00 48 PM](https://user-images.githubusercontent.com/5664/142961930-6ea269ed-14ab-46bd-9dc2-971e92b34f95.png)

`crypto` is being used in the shared template, and since it's a Node dependency, it breaks CF workers.

**Comment by TheRealFlyingCoder** [comment]
Specifically the new `app/utils.server.ts` hash function for the Demo's

**Comment by ryanflorence** [comment]
fixed in https://github.com/remix-run/remix/pull/462
