### ISSUE TITLE
🗺️ Future Flags

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4598]
Flags in `remix.config.js` to opt-in to future APIs/behaviors.

- PR: #4566 
- Nightly: v0.0.0-nightly-95b7fd1-20221115

**Comment by ryanflorence** [comment]
#4482 will depend on this @kiliman.

I'm going to be out of town the next week, so won't be able to review any work there until next monday :)

**Comment by chaance** [comment]
Merged in https://github.com/remix-run/remix/pull/4566
