### ISSUE TITLE
[Bug]: Failed to start example with vercel integration

### ISSUE THREAD

**Issue by Zoomelectrico** [remix-run/remix#460]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.0.3

### Steps to Reproduce

Hi there! Thanks for your work 🎊!!!

I follow the steps on this [tutorial](https://remix.run/docs/en/v1/tutorials/blog)

```shell
npx create-remix@latest
# follow the prompts
cd ./remix-example
npm run dev
```

The prompts can be found [here](https://app.warp.dev/block/DL21ApqUl77vHD4LfebYp2) or down

```shell
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./remix-example
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes

> postinstall
> remix setup node

Successfully setup Remix for node.

added 422 packages, and audited 423 packages in 2m

115 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into "remix-example" and check the README for development and deploy instructions!
```

### Expected Behavior

I except to open my browser on port localhost:3000 and see the server running

### Actual Behavior

First thing I notice is that the example says

> Open up https://localhost:3000, the app should be running. If you want, take a minute and poke around the starter template, there's a lot of information in there.

But you the default port as I see in `AppConfig` is _8002_ so you need to add `devServerPort: 3000` to `remix.config.js`

Second is when you changed the port I got a _426_ error

![image](https://user-images.githubusercontent.com/12375252/142964767-c2dc1ec7-f330-4d92-a93e-80d71e4e5aee.png)

And when I try to open `https://localhost:3000` I got an `ERR_SSL_PROTOCOL_ERROR `

**Comment by ryanflorence** [comment]
Dang. @mcansh is actually wrapping up better Vercel integration with their new files API, should be out soon.

**Comment by Zoomelectrico** [comment]
@ryanflorence Thanks Ryan! No problem!! I just follow the demo with Remix App Server and already loving the work you've done!!

**Comment by leerob** [comment]
Our team will follow up here as well, sorry about this! 🙏

**Comment by Zoomelectrico** [comment]
Thanks @leerob!!

**Comment by machour** [comment]
Should be working as expected now with the updates to the vercel integration.
If not, please reopen a new issue 🙏🏼
