### ISSUE TITLE
Infinite requests when `fetcher` is in a `useEffect` dependency array

### ISSUE THREAD

**Issue by blittle** [remix-run/remix#4602]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

Load this stackblitz: https://stackblitz.com/edit/node-ktq7n5?file=app%2Froutes%2Fresource.tsx,app%2Froutes%2Findex.tsx

### Expected Behavior

Only one request goes to the server, as outlined in the docs: https://remix.run/docs/en/v1/api/remix#usefetcher

### Actual Behavior

There are infinite requests that hit the resource route.

**Comment by machour** [comment]
Thanks for logging this. This is a documentation issue, see #4386 for a resolution

**Comment by machour** [comment]
Docs have been reworked and they now include several examples avoiding the infinite loop, so I'm going to close this.
