### ISSUE TITLE
Submit of form made with useFetcher() triggers autoscroll of another component on the same page

### ISSUE THREAD

**Issue by anton-pas** [remix-run/remix#4637]
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Here is the link for reproducing - [Link to the sandbox](https://stackblitz.com/edit/node-rua5uz?file=packages/ui/autoscroll/index.tsx).

I have an index page with two components - `<TestForm />` and `<Autoscroll />`. 

Steps:
1. Follow the link I've provided above.
2. When the page has loaded, user will be scrolled down to the `<Autoscroll />` component. This is expected behaviour.
3. Scroll up the form with input field.
4. Fill in the input field.
5. Press submit button.
6. User is scolled down to the `<Autoscroll />` component (this is a bug).

### Expected Behavior

I expect the page to be scrolled to the `<Autoscroll />` component only when user lands on the page. `<TestForm />` submit event should NOT trigger `useEffect()` of `<Autoscroll />` component (and other `useEffect()` hooks of components on the same page with form). 

It sounds tricky bcz I can have a lot of components on the same page with my form. And each of those components can have its own interactivity/actions/logic inside `useEffect()` hook. And form submition can trigger logic inside those `useEffect()` functions.

### Actual Behavior

When I submit my form, it triggers `useEffect()` inside `<Autoscroll />` component. And `useEffect()` logic just scrolls user to that component on the same page.

**Comment by freewill777** [comment]
Same behavior in here.

**Comment by machour** [comment]
@anton-pas can you check with 1.7.6 if you still have the problem?

**Comment by anton-pas** [comment]
@machour I've tested it here with 1.7.6 - [link to the sandbox](https://stackblitz.com/edit/node-dc8lra). No luck(

**Comment by machour** [comment]
@anton-pas just tested on 1.11.1, seems like the problem was fixed 🎉 
https://stackblitz.com/edit/node-rekcnl?file=app%2Froutes%2Findex.tsx

Please reopen if you still see a problem on your side 🙏🏼
