### ISSUE TITLE
Use of TypeScript 4.9 satisfies breaks build process

### ISSUE THREAD

**Issue by TenkoSpirit** [remix-run/remix#4639]
### What version of Remix are you using?

1.7.6

### Steps to Reproduce

1. Create Remix app with yarn/your tool, I used blues stack
2. Install TypeScript 4.9.3
3. Create a type, something like 
```typescript
type SomethingCool = {
  foo: number;
}
```
5. Try to create an object and use the new `satisfies` keyword with `SomethingCool`
6. Try to build  

### Expected Behavior

The project builds

### Actual Behavior

The project doesn't build and there's an error being thrown 
```
$ remix build
Building Remix app in production mode...

✘ [ERROR] [plugin browser-route-module] Build failed with 1 error:
app/root.tsx:32:4: ERROR: Expected ";" but found "satisfies"
```

**Comment by jenseng** [comment]
Likely just need to bump esbuild to [0.15.13+](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#01513)

**Comment by machour** [comment]
Oh perfect, then #4301 should fix this too!

**Comment by pcattori** [comment]
Update: #4301 upgrades esbuild to 0.15.12. We were seeing tests hang or fail on 0.15.13+. We're working on fixing the underlying issues and then will upgrade to 0.15.13+

**Comment by MichaelDeBoey** [comment]
Closed by #4301

**Comment by pcattori** [comment]
@MichaelDeBoey we still haven't upgraded esbuild to 0.15.13+, so #4301 does not actually address this. I've edited the description of #4301 to make that more clear.

**Comment by MichaelDeBoey** [comment]
@pcattori Oh didn't know we reverted it to `0.15.12` again, I thought we were using `0.15.14` 🙈

**Comment by JClackett** [comment]
What's the latest with this? still getting:

`Expected ";" but found "satisfies"`

when running `remix build`

using:
`remix: 1.8.0`
`esbuild: 0.15.16`

**Comment by pcattori** [comment]
We're actively working on it, see https://github.com/remix-run/remix/pull/4754 .

Currently, the esbuild upgrade is causing some integration tests to hang indefinitely.
Once we have that fixed, we'll proceed with the upgrade to esbuild 0.15.13+.
