### ISSUE TITLE
Incorrect type inferred from loader only when nested in an object literal

### ISSUE THREAD

**Issue by simonsinclair** [remix-run/remix#4643]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

```ts
import type { LoaderArgs } from '@remix-run/node';
import { json } from '@remix-run/node';
import { useLoaderData } from '@remix-run/react';
import { ObjectId } from 'mongodb';

const Page = () => {
  const item = useLoaderData<typeof loader>();

  return null;
};

export const loader = ({}: LoaderArgs) => {
  /**
   * json(item) inferred incorrectly.
   */
  const item = {
    id: new ObjectId(),
  };

  /**
   * json(id) inferred correctly.
   */
  const id = new ObjectId();

  /**
   * json(ids) inferred correctly.
   */
  const ids = [new ObjectId(), new ObjectId()];

  return json(item);
};
```

### Expected Behavior

[MongoDB's ObjectId implements toJSON](https://github.com/mongodb/js-bson/blob/3d3d0dce161c326f394b8df5838fd4149120d4e6/src/objectid.ts#L202), so I would have thought returned instances of it would be inferred as a `string`.

#### Additional information
- Returning a single ObjectId on its own or in an array is inferred **correctly**.
- [type-fest](https://github.com/sindresorhus/type-fest)'s `Jsonify` infers the correct type in all cases.

### Actual Behavior

<img width="466" alt="Screenshot 2022-11-18 at 16 34 24" src="https://user-images.githubusercontent.com/1430787/202755151-a1925232-d9dc-4c64-9f05-678e2c008d60.png">

**Comment by machour** [comment]
@simonsinclair did you find an issue with your code? Please post it here for future travelers 😅

**Comment by simonsinclair** [comment]
> @simonsinclair did you find an issue with your code? Please post it here for future travelers 😅

Yeah, it's not a bug. A more complex type was being applied to my loader response data downstream. This and the resulting type in TypeScript's tooltip (which I find hard to read) lead me to believe it was being inferred incorrectly.
