### ISSUE TITLE
I use the npx create-remix@latest  when I run "yarn dev" I got this error

### ISSUE THREAD

**Issue by Alvazz** [remix-run/remix#4655]
### What version of Remix are you using?

1.7.6

### Steps to Reproduce

npx create-remix@latest
? Where would you like to create your app? remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No

That's it! `cd` into "/Users/jason/webProject/remix-app" and check the README for development and deploy instructions!
❯ cd remix-app
❯ yarn install
❯ yarn dev

then got this error

### Expected Behavior

I just follow the remix.run guide to try it.

### Actual Behavior

LOL

**Comment by Alvazz** [comment]
A framework that boasts such a powerful framework, comparable to Nextjs, should not have this kind of out-of-the-box error!

**Comment by Alvazz** [comment]
Grow up slowly, there is still a long way to go

**Comment by machour** [comment]
These are all hydration errors coming from React 18. One of your browser extension is modifying the DOM. 
Try opening the website in incognito and see if errors still appears.

**Comment by machour** [comment]
Closing as this for sorted out on discord.
