### ISSUE TITLE
Redirect triggers page reload in deployed version when redirecting with redirecting to a full URL

### ISSUE THREAD

**Issue by cjkooij** [remix-run/remix#4656]
### What version of Remix are you using?

1.7.4

### Steps to Reproduce

Have an action function with a redirect in which you redirect to to a full URL with the protocol/host.

### Expected Behavior

Page does not reload, as it does while running the code locally.

### Actual Behavior

Page does reload (when deployed).

Ryan's comment:
"_we have code to make sure to do a window.location =  instead of history.pushState in that case
we should add some code to be less naive and check if the window.origin is the same, too_"

**Comment by brophdawg11** [comment]
👋 Hey!  I think this is the same thing being asked for in this [Proposal](https://github.com/remix-run/react-router/discussions/9859) so I'm going to close this out in favor of that if you'd like to upvote that proposal.

If you need a workaround in the short term, I'd probably just do it through `actionData`/`useEffect` which is effectively what Remix does under the hood for different origins as is.

```jsx
export function action() {
  return json({ hardReloadUrl: 'https://www.currentorigin.com/whatever' });
}

export default function Component() {
  let actionData = useActionData();

  React.useEffect(() => {
    if (actionData?.hardReloadUrl && typeof window !== 'undefined') {
      window.location.replace(actionData.hardReloadUrl);
    }
  }, [actionData]);

  return <Form method="post>...</Form>
}
```
