### ISSUE TITLE
Lambda Deploy

### ISSUE THREAD

**Issue by roblox34** [remix-run/remix#4680]
Hi all,

Is there any way to deploy the application in an aws lambda WITHOUT Architect?
Because my deployment process is completely separate and automated. I don't have access to the AWS account.
I think I would have to generate a ZIP file of the application to run in a lambda or something like this.

Thanks.

**Comment by machour** [comment]
Don't double post please, there's a conversation with this question already.
https://github.com/remix-run/remix/discussions/4678
