### ISSUE TITLE
🗺️ Vanilla Extract

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4708]
## Progress

- [x] RFC https://github.com/remix-run/remix/discussions/5015
- [x] PR https://github.com/remix-run/remix/pull/5040

**Comment by ryanflorence** [comment]
@chaance to give it the beans and then if it's good we can merge.

**Comment by markdalgleish** [comment]
Merged!

**Comment by chaance** [comment]
I gave it the beans
