### ISSUE TITLE
Nondeterministic routeModules error despite attempts to prevent server from importing code

### ISSUE THREAD

**Issue by btslater** [remix-run/remix#4710]
### What version of Remix are you using?

1.7.6

### Steps to Reproduce

Unfortunately, I don't know how to give steps to reproduce this issue, as it is nondeterministic and I can't post the code from the 3rd-party that has side effects/browser API usage.

I have posted as much detail as I can [on the Remix discussions](https://github.com/remix-run/remix/discussions/4671).

### Expected Behavior

I am using a 3rd party library which has side effects and uses browser APIs, so this code _must not run on the server_. I expect that I should be able to limit this code to the client only, and prevent this code from importing/running on the server, using the following approach:

- Putting all code which imports from `ThirdParty.js` inside a `ThirdPartyWrapper.client.jsx` file,
- this wrapped component is `lazy`-loaded,
- wrapped in a `Suspense`,
- AND wrapped in a `ClientOnly`

(I have also tried simpler approaches involving, for example, only wrapping in `remix-utils`' `ClientOnly`, etc.)

### Actual Behavior

Everything works as expected when I run my app locally.

When deployed on a server, _approximately one-seventh of the time_, the server apparently tries importing `ThirdParty.js` code and throws errors; in the browser dev tools, these errors reference obfuscated 3rd-party code that tries to access `window` (a browser-only API). This is surprising to me because I have taken steps to ensure the import of this problematic code should only happen on the client.

These errors appear to be non-deterministic: sometimes the app works as expected, other times it crashes with a `routeModules` error, suggesting an issue with sharing code between client/server. In my hands, the crashes happen only in incognito mode, although my colleagues see crashes in non-incognito.

Is is possible that Remix is somehow aggressively bundling this code and running it on the server, despite my layered attempts to prevent this? The inconsistency/non-repeatability makes me wonder if there could be some kind of race condition, or (module?) cache issue?

**Comment by kiliman** [comment]
Without seeing some code, it's kind of difficult to know where to begin. Your list of things you are currently doing is everything I would already suggest.

**Comment by machour** [comment]
As kiliman mentioned, not much we can do without a reproduction. 
Feel free to reopen if you're ever able to give one.
