### ISSUE TITLE
Node server crashing when upgrade to 1.8 (@remix-run/web-fetch@4.3.2)

### ISSUE THREAD

**Issue by nicksrandall** [remix-run/remix#4737]
### What version of Remix are you using?

1.8

### Steps to Reproduce

If I have time, I'll try to create a minimal reproduction.

When I upgraded my app (deployed to fly.io as a Node service) to Remix 1.8 (from 1.7.6), I got alerts that my server was repeatedly crashing. The errror returned comes from `@remix-run/web-fetch@4.3.2` https://github.com/remix-run/web-std-io/blob/main/packages/fetch/src/fetch.js#L342 where the error message says "Premature Close". 

Reverting back to @remix-run/node@1.7.6 and @remix-run@web-fetch@4.31 solved the issue for me. 

### Expected Behavior

No fetch errrors. 

### Actual Behavior

Fetch errors.

**Comment by nicksrandall** [comment]
CC @jacob-ebey

**Comment by jacob-ebey** [comment]
Do you have a minimal example of the application code that is causing this codepath?

**Comment by nicksrandall** [comment]
I'll close this issue for now as the other ticket has a failing test case that can be used to debug.
