### ISSUE TITLE
[Bug]: Express CLI starter doesn't appear to run

### ISSUE THREAD

**Issue by antgonzales** [remix-run/remix#474]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [X] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

^1.0.4

### Steps to Reproduce

Create a new project and run through the prompts using the executable script and choose to create the project with Express in Typescript.

```
❯ node -v
v16.13.0
❯ npm -v
8.1.0
```

```
❯ npx create-remix@latest

R E M I X

💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./test-remix
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Express Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes

> postinstall
> remix setup node

Successfully setup Remix for node.

added 392 packages, and audited 393 packages in 21s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into "test-remix" and check the README for development and deploy instructions!
```

Try to run the development environment and see that the server never starts.

```
❯ npm run dev

> dev
> remix watch

Watching Remix app in development mode...
💿 Built in 323ms
```

### Expected Behavior

I expected to be able to see that localhost:3000 is ready in the logs but don't see it and can't access the site.

### Actual Behavior

The script halts and does not start the local development server.

**Comment by mikebobadilla** [comment]
I think remix-run:serve is missing from the dev-dependencies. I ran into the same thing. I added the following and installed. Seems to be working for now.

```
"devDependencies": {
    "@remix-run/dev": "^1.0.4",
    "@remix-run/serve": "^1.0.4",
    "@types/react": "^17.0.24",
    "@types/react-dom": "^17.0.9",
    "typescript": "^4.1.2",
    "vercel": "^21.2.2"
  },
  ```

**Comment by linbudu599** [comment]
I'm facing the same problem with Vercel template...

**Comment by girishk21** [comment]
for Vercel you have to serve the files through Vercel development CLI

In one terminal do

```sh
npm run dev
```

and, in another terminal

```sh
vercel dev
```

if you don't use anything that is specific to Vercel (eg: Environment variables from the Vercel CLI), you can install 

```sh
npm i -D @remix-run/serve
```

and run the server through Remix server by

```sh
npm run remix run
```

**Comment by pixelmund** [comment]
For express you have to run the `start:dev` command separately i guess.

**Comment by antgonzales** [comment]
@mikebobadilla Adding `@remix-run/serve` had no effect unfortunately. @pixelmund's solution appears to work tho. You have to build and then start dev. 

```
npm run build && npm run start:dev
```

**Comment by mikebobadilla** [comment]
@antgonzales I had already built I guess. Thanks!

**Comment by jellebouwman** [comment]
> @mikebobadilla Adding `@remix-run/serve` had no effect unfortunately. @pixelmund's solution appears to work tho. You have to build and then start dev.
> 
> ```
> npm run build && npm run start:dev
> ```

When I throw away the `/public/build` directory, `npm run start:dev` works fine too. I think the `npm run dev` script might not be working properly.
