### ISSUE TITLE
Redirect fails with 1.8.0 on Cloudflare

### ISSUE THREAD

**Issue by assaf** [remix-run/remix#4740]
### What version of Remix are you using?

1.8.0

### Steps to Reproduce

I'm getting `TypeError: Invalid URL string` errors from any loader or action has have a redirect. This will fail:

```
export async function loader() {
  return redirect("/");
}
```

Seeing this when deploying to Cloudflare pages with 1.8.0. No issues in development, or when using 1.7.6.

### Expected Behavior

Works fine with 1.7.6.

### Actual Behavior

Stack trace I'm getting:

```
TypeError: Invalid URL string.
    at ks (worker.mjs:553:10)
    at k1 (worker.mjs:839:89)
    at async Promise.all (index 0)
    at async l (worker.mjs:799:13)
    at async a (worker.mjs:750:15)
    at async Object.i [as queryRoute] (worker.mjs:736:13)
    at async FL (worker.mjs:1828:13)
    at async worker.mjs:1878:65
    at async o (worker.mjs:12998:22)
    at async worker.mjs:13002:14
```

**Comment by brophdawg11** [comment]
Thanks @assaf!  We found the issue here and will get a patch out next week with a fix 👍

**Comment by tulup-conner** [comment]
Wow, I spent the past two days beating myself up over this. Thank you for bringing me sanity. Downgrading to previous remix version again..

**Comment by JulienMelissas** [comment]
Haha, I also should have probably looked to see if this was a bug or if I was just crazy. Thank you for already being on this! 🎉

**Comment by tulup-conner** [comment]
I upgraded to 1.8.1 on Cloudflare Pages and I still receive the Unexpected Server Error warning.

**Comment by brophdawg11** [comment]
Hey folks - this fix wasn't in `1.8.1` :).  The merged PR above is over in `@remix-run/router` which is in pre-release and we'll be testing that updated dependency in Remix today and prepping a `1.8.2` with any other router changes.

**Comment by JulienMelissas** [comment]
Thanks @brophdawg11, I looked at the documentation for upgrade instructions, but didn't see anything. Should we be updating `@remix-run/cloudflare`, `@remix-run/cloudflare-pages`, or `@remix-run/react` (or a combination/all 3) to that version? Thank you!

**Comment by brandonpittman** [comment]
@JulienMelissas I believe that running a mix of versions would cause issues.

**Comment by machour** [comment]
@JulienMelissas you should always update all your remix packages to the same version

**Comment by brophdawg11** [comment]
This is released in 1.8.2 👍

**Comment by JulienMelissas** [comment]
Just confirming upgrading to 1.8.2 fixed it for me, thanks much for the quick fix, sorry I wasn't able to check the fix sooner.

**Comment by assaf** [comment]
Thanks for fixing this!
