### ISSUE TITLE
Error in vercel deploy: TypeError: Cannot read properties of undefined (reading 'v2_meta')

### ISSUE THREAD

**Issue by Lucas-Eduardo-Goncalves** [remix-run/remix#4759]
### What version of Remix are you using?

1.6.7

### Steps to Reproduce

clone repository by ssh: `git clone git@github.com:Lucas-Eduardo-Goncalves/pac.app.git`
then add this repository to vercel, and try.

### Expected Behavior

My site should work normally. On localhost I can't find it works normally.

### Actual Behavior

I find the error message: TypeError: Cannot read properties of undefined (reading 'v2_meta')

**Comment by meglio** [comment]
Same error for me in `1.8.0`. Wasn't a case with `1.7.2`

**Comment by machour** [comment]
Can you both provide a gist of you package.lock file?

**Comment by machour** [comment]
Can you add `future: {}` in your `remix.config.js` and see if the issue goes away?

**Comment by antoninbeaufort** [comment]
Had the same problem but adding `future: {}` solved the problem

**Comment by JClackett** [comment]
@machour Adding future doesn't fix, also broken in local for me

**Comment by ThanhPhat1080** [comment]
Seem you are missing edit the remix config while you want to deploy to Vercel.
In `remix.config.js`
```js
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverBuildTarget: "vercel",
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "api/index.js",
  // publicPath: "/build/",
};
```

Create new `server.js` file at your root folder (the same level of `remix.config.js`)

```js
import { createRequestHandler } from "@remix-run/vercel";
import * as build from "@remix-run/dev/server-build";

export default createRequestHandler({ build, mode: process.env.NODE_ENV });

```

**Comment by sjwinther** [comment]
Having the same problem, but adding `future: {}` does not solve the issue. I already have a `server.js` file as described by @ThanhPhat1080.

**Comment by machour** [comment]
@sjwinther are all your remix deps on 1.8.0? Can you share a gist of your package.json depedencies & devDependencies sections?

**Comment by sjwinther** [comment]
@machour Yup! Here you go: https://gist.github.com/sjwinther/643603e3c40273614f05855ff2ce90db

**Comment by machour** [comment]
@sjwinther just to confirm, you're seeing `Cannot read properties of undefined (reading 'v2_meta')` even tho you added `future: {}` to your remix.config.js file? (Please update the gist with its contents 🙏)

**Comment by sjwinther** [comment]
Looks like I got it resolved now, although it was pretty difficult to figure out from the error. I was returning `{ rel: "icon", href: "/favicon.png", type: "image/png" }` in one of the Link functions and for some reason Remix didn't like that? I was getting this error as well, which was also resolved when I removed the favicon.png link:

```
{
  data: 'No route matches URL "/favicon.ico"',
  status: 404,
  statusText: 'Not Found'
}
No routes matched location "/favicon.ico"
```

**Comment by AnthonyLzq** [comment]
> Seem you are missing edit the remix config while you want to deploy to Vercel. In `remix.config.js`
> 
> ```js
> /** @type {import('@remix-run/dev').AppConfig} */
> module.exports = {
>   serverBuildTarget: "vercel",
>   // When running locally in development mode, we use the built in remix
>   // server. This does not understand the vercel lambda module format,
>   // so we default back to the standard build output.
>   server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
>   ignoredRouteFiles: ["**/.*"],
>   // appDirectory: "app",
>   // assetsBuildDirectory: "public/build",
>   // serverBuildPath: "api/index.js",
>   // publicPath: "/build/",
> };
> ```
> 
> Create new `server.js` file at your root folder (the same level of `remix.config.js`)
> 
> ```js
> import { createRequestHandler } from "@remix-run/vercel";
> import * as build from "@remix-run/dev/server-build";
> 
> export default createRequestHandler({ build, mode: process.env.NODE_ENV });
> ```

This solution worked for me, in addition to adding the property `future: {}`. Besides I have installed `@remix-run/vercel` and `@vercel/node` according to @sjwinther 's gist.

**Comment by TheGreatRambler** [comment]
I'm also running into this issue with
```
		"@remix-run/node": "^1.7.2",
		"@remix-run/react": "^1.7.2",
		"@remix-run/serve": "^1.7.2",
```

**Comment by TheGreatRambler** [comment]
Fixed it by ensuring every remix package was up to date:
```
		"@remix-run/node": "^1.8.0",
		"@remix-run/react": "^1.8.0",
		"@remix-run/serve": "^1.8.0",
		"@remix-run/dev": "^1.8.0",
		"@remix-run/eslint-config": "^1.8.0",
```
AND including `future` in `remix.config.js`

**Comment by Lucas-Eduardo-Goncalves** [comment]
I was able to figure out the answer, to make it work I updated the packages to version 1.8.0 and also added the `@remix/vercel` package.

**Comment by chaance** [comment]
Closing in favor of https://github.com/vercel/vercel/issues/9010

**Comment by TheGreatRambler** [comment]
> AFAICT this should only be an issue if `@remix/vercel` is not explicitly installed. Adding `future: {}` to your config shouldn't make a difference if you do (and if it does cause an issue, it may be duplicate copies of the `dev` or `server-runtime` packages installed as a side effect of Vercel automatically installing the outdated version.

I should mention this error happened to me in the self hosted version, but not all remix dependencies were up to date so it makes sense

**Comment by antoninbeaufort** [comment]
I had the issue locally too (in prod I use fly.io)

**Comment by machour** [comment]
We have reported the issue to vercel and provided a fix for it there.
If you have an unrelated problem, please create a new issue.
