### ISSUE TITLE
Remix causes syntax errors in iOS 11

### ISSUE THREAD

**Issue by jfsiii** [remix-run/remix#4762]
### What version of Remix are you using?

1.8

### Steps to Reproduce

Visit a Remix app in iOS 11

e.g. create one with `npx create-remix@latest` and browse it on https://browserstack.com

### Expected Behavior

The site looks and functions as normal. No JS errors in the console

<img width="314" alt="Screenshot 2022-12-03 at 8 53 26 AM" src="https://user-images.githubusercontent.com/57655/205444281-06f050fe-9ce0-43bf-ab3f-b76546412f89.png">

### Why do I expect this?
https://remix.run/docs/en/v1/guides/browser-support says

> Remix only runs in browsers that support [ES Modules](https://caniuse.com/es6-module).

The linked page shows iOS on Safari supports ES Modules as of version `11.0`
<img width="1377" alt="Screenshot 2022-12-03 at 8 14 42 AM" src="https://user-images.githubusercontent.com/57655/205444404-e03421dd-e9df-4b37-ba8b-c869291630e4.png">

### Actual Behavior

I'm having a hard time finding an `11.0` browser for testing but there are syntax errors in both `11.2` and `11.3`

### iOS 11.3
JS Syntax error in the console (from optional chaining?)

<img width="1344" alt="Screenshot 2022-12-03 at 9 25 18 AM" src="https://user-images.githubusercontent.com/57655/205445815-e482d084-6c3c-4d76-80cd-4949dfd5f4bd.png">

<details>
I believe this is from the optional chaining operator (which [isn't in Safari until 13.4](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility)) 
<img width="1344" alt="Screenshot 2022-12-03 at 9 24 54 AM" src="https://user-images.githubusercontent.com/57655/205445855-257b392c-30fc-491f-9d4b-12e3122d14e6.png">

https://github.com/search?q=repo%3Aremix-run%2Fremix+%22%3F.data%22+path%3A%2F%5Epackages%5C%2F%2F&type=code&l=packages%2F

https://github.com/search?q=repo%3Aremix-run%2Fremix+%22%3F.formMethod%22+path%3A%2F%5Epackages%5C%2F%2F&type=code&l=packages%2F
</details>

### iOS 11.2
JS Syntax error in the console (from optional catch binding and spread in object literals?)

<img width="1601" alt="Screenshot 2022-12-03 at 9 48 36 AM" src="https://user-images.githubusercontent.com/57655/205447472-5f3e1056-3d74-4292-877a-ce96c327e22f.png">

<details>
I believe this is from the use of optional catch binding 

<img width="1601" alt="Screenshot 2022-12-03 at 9 49 36 AM" src="https://user-images.githubusercontent.com/57655/205447552-93dfd474-fdb6-4db4-85e9-8403d2064686.png">

which isn't available until iOS 11.3

<img width="1379" alt="Screenshot 2022-12-03 at 9 51 52 AM" src="https://user-images.githubusercontent.com/57655/205447551-bf3b4262-9da7-451c-a429-f9999adc7ebf.png">

It's not shown in the above screenshot, but in my own app I've seen this error

```
Unexpected token: '...'. Expected a property name.
```

I believe this is from using spread in object literals which also isn't supported until 11.3
<img width="1601" alt="Screenshot 2022-12-03 at 9 50 29 AM" src="https://user-images.githubusercontent.com/57655/205447895-eade7a91-6bbc-4eeb-9c33-5933b75b61fb.png">

<img width="1380" alt="Screenshot 2022-12-03 at 9 51 17 AM" src="https://user-images.githubusercontent.com/57655/205447894-f2957591-46d6-4049-9d49-282f7c0e45ae.png">

<img width="1477" alt="Screenshot 2022-12-03 at 9 53 45 AM" src="https://user-images.githubusercontent.com/57655/205447893-f14f2ea0-680e-4196-8be0-29b3903a8fed.png">

</details>

### Suggested / requested changes

I'm not sure if Remix should change the source files to avoid using these patterns or do transforms to change the distributed code, but it should be possible to use Remix in iOS 11.0 without syntax errors.

Also, is there a way to add tests/checks for this to prevent regressions?

**Comment by machour** [comment]
Thank you for the detailed report. This is already tracked in #1901

**Comment by jfsiii** [comment]
@machour I've seen that ticket (I mentioned this there)

However, that ticket references iOS 12 and some newer features than this ticket. To achieve the documented browse support Remix needs to run in iOS 11.0.

Perhaps that ticket could be updated to include the information from here?

**Comment by machour** [comment]
@jfsiii we have your latest comment there + a reference to this issue, it should be ok.
Team is planning on adding support for browserlist, which should allow everyone to fine-tune compatibility 👌🏼
