### ISSUE TITLE
Client side navigation interrupts loader revalidation

### ISSUE THREAD

**Issue by sjwinther** [remix-run/remix#4765]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

I have a webshop with a product page, which submits a form via a fetcher to add products to a cart. I need the updated number of items in the cart a bunch of places on the site, so I also have a loader which loads the cart.

When the form is submitted and items are added to the cart the loader function correctly runs again and the cart data gets revalidated across the site. However if I add something to the cart and then quickly navigate elsewhere on the page, the data revalidation gets interrupted and the cart data is now out of sync.

I've tried to log the data in the loader, and it looks like it still runs no problem and gets updated data. However the data never seems to get updated and sent to the `useLoaderData` hook.

### Expected Behavior

I would expect the updated data from the loader function to update the data on the page, even when the user navigates to a new page before the loader data gets back.

### Actual Behavior

Data on the client is out of sync until a) something happens so the loader gets called again or b) the page gets reloaded.

**Comment by brophdawg11** [comment]
@sjwinther Can you confirm if this is still an issue for you?  Remix `1.10.0` switched over to using `@remix-run/router` which was a complete rewrite to replace the old TransitionManager in earlier versions of Remix.  I have a hunch that the new implementation properly handles this case but please let us know if you're still seeing the issue.
