### ISSUE TITLE
Cloudflare pages create remix won't start dev server 

### ISSUE THREAD

**Issue by pavelcerveny** [remix-run/remix#4779]
### What version of Remix are you using?

Remix: 1.8.1
Npm 9.1.3
Windows 10

### Steps to Reproduce

- Run npx create-remix@latest
- Select Cloudflare Pages
- Run npm run dev

### Expected Behavior

The site will be available on localhost:8787 or 8788 (wrangler ports)

### Actual Behavior

"This site can’t be reached localhost refused to connect."

I assume, the problem is with the new version of "wrangler" in package-lock.json I have:
"node_modules/wrangler": {
      "version": "2.6.0",
      
Instead of 2.2.1 from package.json

When I downgrade it to 2.2.1, then it works

**Comment by pavelcerveny** [comment]
This seems to be problem with wrangler: https://github.com/cloudflare/wrangler2/issues/2334

**Comment by rozenmd** [comment]
This should be fixed as of https://github.com/cloudflare/wrangler2/releases/tag/wrangler%402.6.1
