### ISSUE TITLE
[Bug]: Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by davidsoderberg** [remix-run/remix#479]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [X] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Run `npx create-remix@latest` use netlify option.
Deploy to Netlify with Github.

### Expected Behavior

Site is live with the same view as running netlify dev.

### Actual Behavior

Loading my page displays this error instead.
```
{
errorType: "Runtime.ImportModuleError",
errorMessage: "Error: Cannot find module 'fs/promises' Require stack: - /var/task/node_modules/@remix-run/node/errors.js - /var/task/node_modules/@remix-run/node/index.js - /var/task/node_modules/@remix-run/netlify/globals.js - /var/task/node_modules/@remix-run/netlify/index.js - /var/task/netlify/functions/server/index.js - /var/task/server.js - /var/runtime/UserFunction.js - /var/runtime/index.js",
trace: [
"Runtime.ImportModuleError: Error: Cannot find module 'fs/promises'",
"Require stack:",
"- /var/task/node_modules/@remix-run/node/errors.js",
"- /var/task/node_modules/@remix-run/node/index.js",
"- /var/task/node_modules/@remix-run/netlify/globals.js",
"- /var/task/node_modules/@remix-run/netlify/index.js",
"- /var/task/netlify/functions/server/index.js",
"- /var/task/server.js",
"- /var/runtime/UserFunction.js",
"- /var/runtime/index.js",
" at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
" at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
" at Object.<anonymous> (/var/runtime/index.js:43:30)",
" at Module._compile (internal/modules/cjs/loader.js:999:30)",
" at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
" at Module.load (internal/modules/cjs/loader.js:863:32)",
" at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
" at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
" at internal/main/run_main_module.js:17:47"
]
}
```

**Comment by milamer** [comment]
Perhaps this is a [side effect in your module.](https://remix.run/docs/en/v1/other-api/constraints#no-module-side-effects)

**Comment by davidsoderberg** [comment]
I am basiclly running what the `npx create-remix@latest` command creates.

**Comment by christianhg** [comment]
What version of Node.js are you using? I was having similar problems with v12, but then I upgraded to v14 and it works fine. I couldn't find anything in the docs about minimum version required though.

So, if you are using a v12 or older, I would try to upgrade to v14 and create a new project using that version.

**Comment by davidsoderberg** [comment]
On local I user 14.16.1 and on Netlify it is 16.13.0. So that should not be a problem right?

**Comment by M0nica** [comment]
> On local I user 14.16.1 and on Netlify it is 16.13.0. So that should not be a problem right?

Did you set   `netlify env:set AWS_LAMBDA_JS_RUNTIME nodejs14.x`? I had a similar issue deploying to Netlify when I had just set the NODE_VERSION to 14 but not the AWS lambda runtime.

**Comment by davidsoderberg** [comment]
That did do the trick thank you :)

**Comment by SaraVieira** [comment]
I am having this issue as well but I set my laptop version to the same as netlifly and I still get the same error :/

Both places are using 16.13.0

You can check the code here: https://github.com/SaraVieira/random-simpsons-episode and here is the error I get:
https://musing-euler-49bd2c.netlify.app/

Also when I tried to set `netlify env:set AWS_LAMBDA_JS_RUNTIME nodejs17.x` before downgrading my computer to 16 I got this error on netlifly:

```
1:40:58 AM: Invalid AWS Lambda parameters. Reserved keys used in this request
```

Let me know if you need anything else to debug this

**Comment by mcansh** [comment]
hey @SaraVieira I forked and deployed your repo to netlify without any changes and it seems to be working except for the missing api key https://frosty-archimedes-0bc410.netlify.app. I believe the only 2 accepted values for `AWS_LAMBDA_JS_RUNTIME` are `nodejs12.x` and `nodejs14.x`

**Comment by SaraVieira** [comment]
Hmm, must be a cache issue 🤔

Will try again when I get home, thank you for trying!

**Comment by SaraVieira** [comment]
Hey! 

Tried it using `AWS_LAMBDA_JS_RUNTIME` with nodejs14.x and it works!

Any plans on supporting v16?

**Comment by mcansh** [comment]
> Any plans on supporting v16?

as soon as AWS lambda does, Netlify will be able to add support for it https://docs.netlify.com/functions/build-with-javascript/#runtime-settings https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by SaraVieira** [comment]
Sorry, I was really slow here, I was forgetting the different environments between netlifly builds and lambdas

Sorry about that
