### ISSUE TITLE
[Regression] Typescript `paths` resolution

### ISSUE THREAD

**Issue by KingSora** [remix-run/remix#4811]
### What version of Remix are you using?

1.8.1

### Steps to Reproduce

I was using `v1.7.0` before tried to upgrade to `v1.8.0`. I could pinpoint the change to be since `v1.7.1`.

My setup is a monorepo with the remix app and a component library. Both are separate packages and I'm using `npm workspaces` to be able to import the component library inside my app. Additionally I'm using typescript in both the app and the component library. Both have separate `tsconfig.json` files since they are separate packages and are not supposed to share anything.

Both `tsconfig.json` files look something like:
```json
{
  "compilerOptions": {
    "paths": {
      "~/*": ["./src/*"]
    }
  }
}
```
So I can use `~/*` imports to get rid of the relative imports.

How esbuild handled this setup before `v1.7.1` was that it looked for the nearest `tsconfig.json` file and used this as its base to resolve `path aliases`. So all `~/*` was resolved relative to the nearest `tsconfig.json`.

Since `v1.7.1` esbuild is configured to only use the apps `tsconfig.json` file. [Here is the related esbuild configuration](https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler/compilerServer.ts#L97-L100). This causes my setup to not work anymore because all `~/*` imports in my component library package can't be resolved anymore.

Its not really clear why this behavior is unwanted. To me this behavior is a huge selling point of esbuild and is enabling remix to be used inside monorepos with greater comfort.

### Expected Behavior

I would like to have the old behavior back. I would suggest to provide a `opt-in` or `opt-out` config for this behavior inside the `remix.config`.

### Actual Behavior

The behavior is fixed, you aren't able to change it. Before `1.7.1` it was different then after `1.7.1`.

**Comment by pcattori** [comment]
@KingSora can you share a reproduction?

**Comment by pcattori** [comment]
Could not reproduce on 1.19.3 nor `nightly`.

My setup:

```sh
mkdir repro-4811
cd repro-4811
npm init -y
npm init -y --scope pcattori -w packages/lib
(cd packages && npx create-remix@nightly remix --template https://github.com/remix-run/remix/tree/main/templates/express)
npm i
```

## packages/lib/tsconfig.json

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "noEmit": true,
    "strict": true,
    "target": "ESNext",
    "esModuleInterop": true,
    "paths": {
      "~/*": ["./*"]
    }
  }
}
```

## packages/lib/package.json

```json
{
  "name": "@pcattori/lib",
  "version": "1.0.0",
  "main": "./dist/index.mjs",
  "devDependencies": {},
  "scripts": {
    "build": "tsup --format esm index.ts"
  }
}
```

## packages/lib/index.ts

```ts
export { libHello } from "~/lib-hello";
```

## packages/lib/lib-hello.ts

```ts
export const libHello = "Lib says hello";
```

## packages/remix/app/lib/app-hello.ts

```ts
export const appHello = "App says hello";
```

## packages/remix/app/routes/_index.tsx

```tsx
import { appHello } from "~/lib/app-hello";
import { libHello } from "@pcattori/lib";

export default function Index() {
  return (
    <main>
      <h1>Welcome to Remix</h1>
      <h2>{appHello}</h2>
      <h3>{libHello}</h3>
    </main>
  )
}
```
