### ISSUE TITLE
[Bug]: Link with prefetch="intent" with query param is failing to hit the prefetch cache once clicked

### ISSUE THREAD

**Issue by ErickTamayo** [remix-run/remix#484]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

v1.0.3

### Steps to Reproduce

Having a Link with a search param like

```jsx
<Link to=".?device=desktop" prefetch="intent" />
```

Triggers the loaders with `_data` query param after the `device` query param like:

```
dashboard?device=desktop&_data=routes%2Fprojects%2F%24projectId

dashboard?device=desktop&_data=routes%2Fprojects%2F%24projectId%2Fdashboard
```

But then when you click, the _data param gets appended before the `device` query param. Causing the prefetch cache to not get hit.

```
dashboard?_data=routes%2Fprojects%2F%24projectId&device=desktop

dashboard?_data=routes%2Fprojects%2F%24projectId%2Fdashboard&device=desktop
```

### Expected Behavior

Get the data from the prefetch cache

### Actual Behavior

The prefetch cache is not getting hit

**Comment by chaance** [comment]
Hi! I'm not a bot, but I'm closing out old issues that have long grown stale and are likely not up-to-date with recent versions. Feel free to ping me if this is still an issue and I can reopen.
