### ISSUE TITLE
🗺 Make `entry.server` and `entry.client` files optional

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4845]
Quick thoughts:

We'll need an RFC with more details on this and probably don't want root to be optional.

### Discussed in https://github.com/remix-run/remix/discussions/4601

<div type='discussions-op-text'>

<sup>Originally posted by **mcansh** November 14, 2022</sup>
make `entry.server` and `entry.client` files optional would allow for quicker demos and getting started from nothing easier without having to use the remix cli to bootstrap an entire app. just install the dependencies and make a `app/routes/index.tsx` file and you're done. plus most folks don't touch these files anyways so making them optional and not need to be on disk* is an added bonus (they'll still be on disk, but you know what i mean)

by default it would look for the files and fallback to ones we have stored in `@remix-run/dev`, which would be copies from https://github.com/remix-run/remix/tree/main/templates/remix</div>

**Comment by mcansh** [comment]
PR: https://github.com/remix-run/remix/pull/4600

**Comment by ryanflorence** [comment]
j/k get trolled, @jacob-ebey to review

**Comment by ryanflorence** [comment]
j/k get trolled they'll review it *this* week.
