### ISSUE TITLE
`serverDependenciesToBundle` dependencies not being picked?

### ISSUE THREAD

**Issue by raulfdm** [remix-run/remix#4853]
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

1. Clone this repo: https://github.com/devraul/remix-query-string-8;
2. install the dependencies (I used `pnpm` there);
3. run the `dev` env : `pnpm run dev`
4. open `http://localhost:3000`

> Obs.:
> - node: v16.18.1
> - pnpm: 7.18.2 

### Expected Behavior

I expected `query-string` to be bundled/parsed when I included it in the `serverDependenciesToBundle` remix option

### Actual Behavior

It throws an error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/raulmelo/Library/pnpm/global/5/.pnpm/filter-obj@3.0.0/node_modules/filter-obj/index.js from /Users/raulmelo/development/sandbox/test-query-string-8/api/index.js not supported.
Instead change the require of /Users/raulmelo/Library/pnpm/global/5/.pnpm/filter-obj@3.0.0/node_modules/filter-obj/index.js in /Users/raulmelo/development/sandbox/test-query-string-8/api/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/raulmelo/development/sandbox/test-query-string-8/api/index.js:141:163)
```

**Comment by raulfdm** [comment]
I tried to add some consoles on the `serverBareModulesPlugin` file, and it seems it's matching, but I'm not sure why it isn't being picked up.

**Comment by machour** [comment]
Isn't the problem caused by `filter-obj` instead?

**Comment by raulfdm** [comment]
Oh, I haven't notice that the error was about `filter-obj`. By adding it also in the `serverDependenciesToBundle` it solves the problem.

```js
module.exports = {
  serverDependenciesToBundle: ['query-string', 'filter-obj']
 }
```
