### ISSUE TITLE
[Bug]: npm run dev does not seem to work

### ISSUE THREAD

**Issue by mohux** [remix-run/remix#488]
### Which Remix packages are impacted?

- [x] `remix` (Remix core)
- [x] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [x] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [x] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

npx create-remix@latest

### Expected Behavior

localhost:3000 to work

### Actual Behavior

terminal shows the tis built successfully but when visiting the url it doesn't

**Comment by rnnyrk** [comment]
Same issue over here. Building the project does nothing. Chose Netlify and Typescript from the cli wizard if that helps in any way
<img width="424" alt="Screenshot 2021-11-23 at 10 24 31" src="https://user-images.githubusercontent.com/4519142/142999227-1209410b-e83d-45b0-aca3-4ff65fccfd81.png">

**Comment by girishk21** [comment]
you also have to set up Netlify local development CLI and start the local dev server [Netlify Adapter README](https://github.com/remix-run/remix/tree/main/packages/create-remix/templates/netlify#netlify-setup). The static files will be served from the Netlify development server mirroring the cloud environment

**Comment by danielvanc** [comment]
I ran into this with setting it up with Vercel. Turns out there's extra steps to follow in the README. For instance, with Vercel setup, you have to have the Vercel dev mode started as well as `npm run dev`.  Check the README. It might be that you need to run another terminal with the netlify cli running at same time (which will give you access to local dev).

Probably could do with adding something to the cli instructions to view the README for extra steps to run local dev.

**Comment by mohux** [comment]
so yeah apparently  every hosting has different setup, follow README file and all will be good i think

**Comment by rnnyrk** [comment]
Using the default Remix App config for now works indeed. Gonna look into Netlify setup later. Maybe good to somewhere show or link to the extra required step for a different hosting setup. I wasn't aware the default dev script wasn't working when choosing Netlify 😓

**Comment by M0nica** [comment]
I opened a PR to add some additional language to the QuickStart Blog Tutorial to point in the direction of the README for deployment target specific instructions. https://github.com/remix-run/remix/pull/446
