### ISSUE TITLE
Regression in form submissions without JS in Remix 1.8.2

### ISSUE THREAD

**Issue by markgaze** [remix-run/remix#4890]
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

**Remix 1.8.2**
- Open https://stackblitz.com/edit/remix-forms-no-js-broken
- Navigate with the `Broken` link (this is a test page using a normal `form`)
- Click the `Test` button
- Observe that you are redirected to the login page and `No cookies` is logged to the console
- Login again and navigate to the `Working` link (this is a test page using a Remix `Form`)
- Click the `Test` button and observe that you are not redirected to the login page and the session is logged to the console

**Remix 1.8.1**
- Open https://stackblitz.com/edit/remix-forms-no-js-working
- Navigate with the `Broken` link (this is a test page using a normal `form`)
- Click the `Test` button
- Click the `Test` button and observe that you are not redirected to the login page and the session is logged to the console
- Login again and navigate to the `Working` link (this is a test page using a Remix `Form`)
- Click the `Test` button and observe that you are not redirected to the login page and the session is logged to the console

You can also recreate the issue on the "Working" page of the Remix 1.8.2 version by disabling JS and clicking the `Test` (you get redirected)

### Expected Behavior

Form submissions should work the same, with or without JavaScript, and I should be able to access the cookies regardless of whether I use `form` or `Form`

### Actual Behavior

Disabling JavaScript or using a plain old `form` means that I have no `headers` in the `Request` when submitting a form and I can therefore not validate that the user has a session.

**Comment by brophdawg11** [comment]
I'm pretty sure this is a duplicate of https://github.com/remix-run/remix/pull/4826, which is fixed in `1.9.0-pre.0` - would you mind seeing if that resolves your issue?  I think we're planning to release the stable `1.9.0` today

**Comment by markgaze** [comment]
> I'm pretty sure this is a duplicate of https://github.com/remix-run/remix/pull/4826, which is fixed in `1.9.0-pre.0` - would you mind seeing if that resolves your issue?  I think we're planning to release the stable `1.9.0` today

Apologies! Didn't see that issue when I did a search, will test 1.9.0 and let you know. Thanks for your speedy response! 🙂

**Comment by markgaze** [comment]
I can confirm that this is fixed in `1.9.0-pre.0` (https://stackblitz.com/edit/remix-forms-1-9) so I'll close this issue and look out for `1.9.0` being released 🙂 Thanks again!
