### ISSUE TITLE
[Bug]: "Developer Blog" quickstart `CatchBoundary` problem

### ISSUE THREAD

**Issue by miktap** [remix-run/remix#494]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Run the [Developer Blog](https://remix.run/docs/en/v1/tutorials/blog#creating-the-project) quickstart project and see the "URL Params and Error Boundaries" demo. Click "And this will be 401 Unauthorized" link.

### Expected Behavior

I'm expecting to see a custom error message with a webmaster email.

### Actual Behavior

I see generic "There was a problem with your request!" error message.

This [switch](https://github.com/remix-run/remix/blob/main/examples/blog-tutorial/app/routes/demos/params/%24id.tsx#L56) block is missing `break`s.

**Comment by machour** [comment]
This have been fixed by a PR
