### ISSUE TITLE
[Feature]: Document what version of Node Remix support

### ISSUE THREAD

**Issue by liywjl** [remix-run/remix#500]
### What is the new or updated feature that you are suggesting?

Document supported Node versions

### Why should this feature be included?

I was following the docs and using Node v12 (which did not work). Updating to Node 16 worked, it should be clear what versions of Node Remix support

**Comment by mnlfischer** [comment]
In this project there is a .nvmrc that specifies Version 14, I think this is also the latest supported version. But I think it would be great to inform the user about it.
