### ISSUE TITLE
[Bug]: [Docs site] Links go to incorrect path

### ISSUE THREAD

**Issue by ekafyi** [remix-run/remix#501]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)

### What version of Remix are you using?

n/a

### Steps to Reproduce

- Go to https://docs.remix.run (which redirects to `docs.remix.run/v1`) 
- Click any link in the body, eg. _Quickstart, Jokes App Deep Dive, Conventional APIs_

These links go to paths that don't exist eg. `https://docs.remix.run/v1/v1/tutorials/blog`

### Expected Behavior

The link should either use absolute path with initial slash or have the v1 path removed.

```html
<a href="/v1/tutorials/blog">Quickstart</a>

<a href="tutorials/blog">Quickstart</a>
```

### Actual Behavior

Current docs pages use relative links.

```html
<a href="v1/tutorials/blog">Quickstart</a>
```

**Comment by machour** [comment]
Not applicable anymore
