### ISSUE TITLE
🗺 Accept http `to` values in Link, treat like `<a>`

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5016]
### Discussed in https://github.com/remix-run/remix/discussions/4888

**Comment by mcansh** [comment]
PR for React Router support here 👉 https://github.com/remix-run/react-router/pull/9900 - in Remix we're _probably_ going to need to use the same regex there too in order to add `prerender` links

**Comment by ryanflorence** [comment]
@mcansh to get back to it for the Remix PR

**Comment by mcansh** [comment]
so browser prerendering is a little iffy, https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/prerender, but does work - however chrome now has this "speculation rules api", which uses a script tag and a custom `type=speculationrules` thing
