### ISSUE TITLE
Some file extensions are missing in compiler/loaders

### ISSUE THREAD

**Issue by staylor** [remix-run/remix#5019]
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

Try to import a `.mov` file. 

### Expected Behavior

URL is returned, like it is for `.mp4` and `.webm` files.

### Actual Behavior

Produces:
```
ERROR] No loader is configured for ".mov" files
```

**Comment by yamidsumer** [comment]
I have the same error but in version 1.9.0 and with .scss files
`No loader is configured for ".scss"`

**Comment by MichaelDeBoey** [comment]
Closed by #5030
