### ISSUE TITLE
`remix build` hangs after build when no tty is available.

### ISSUE THREAD

**Issue by tiagoad** [remix-run/remix#5021]
### What version of Remix are you using?

1.9.0

### Steps to Reproduce

Add a package.json script `build` that runs `remix build`, and another that runs `npm-run-all -l build`.

### Expected Behavior

Build finishes as usual.

### Actual Behavior

Build hangs after `Built in 2.3s`.

**Comment by tiagoad** [comment]
As a workaround, I changed the build script to `script -q /dev/null remix build`

**Comment by cdeath** [comment]
`remix build > /dev/null 2>&1` also works

**Comment by TrySound** [comment]
Remix build started to hang since https://github.com/remix-run/remix/releases/tag/remix%401.7.5. Probably in https://github.com/remix-run/remix/pull/4410

cc @pcattori

**Comment by TrySound** [comment]
Reproduced with `pnpm run --parallel --filter=@webstudio-is/builder build`

Found this incremental flag make build hang. With incremental: false all works.
https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler/compileBrowser.ts#L183

**Comment by TrySound** [comment]
@pcattori New esbuild version seems moved away from incremental flag so upgrade may solve the issue.

**Comment by pcattori** [comment]
Remix v1.16 shipped with more changes to compiler including upgrading to esbuild 0.17.6 and removing the `incremental` flag in favor of rebuilds via esbuild context. Can anyone here try things out with latest and see if this is still an issue?

**Comment by pcattori** [comment]
Tested on 1.18.1. Original issue seems to be resolved.

`package.json`:

```json
{
  "scripts": {
    "stuff": "npm-run-all -l build",
    "build": "remix build",
  }
}
```

Running `npm run stuff` finishes without hanging:

<img width="549" alt="Screenshot 2023-07-03 at 1 36 00 PM" src="https://github.com/remix-run/remix/assets/1477317/0bc9cd8a-488d-4840-b151-bda25120d441">

**Comment by pcattori** [comment]
@TrySound like I mentioned earlier, we've upgraded to esbuild 17 and are now using esbuild context (instead of `incremental` option) for incremental builds.

If issue reemerges, feel free to reopen.
