### ISSUE TITLE
Flatten route folders should not consider colocated files as routes

### ISSUE THREAD

**Issue by manzano78** [remix-run/remix#5028]
### What version of Remix are you using?

v0.0.0-nightly-45d4491-20230106

### Steps to Reproduce

- Install the nightly release which contains the new flatten routes convention:
`npx create-remix@v0.0.0-nightly-45d4491-20230106`
- Activate the future flag in the `remix.config.js` file: 
```
future: { 
  v2_routeConvention: true
}
```
- Apply the following routes. Make `footer.tsx` and `primary-nav.tsx` files export a default component. 
```
routes/
   app/
      _index.tsx
      primary-nav.tsx
      footer.tsx
```
- Execute the following command to see what are the resulting routes handled by Remix:
`npx remix routes`

### Expected Behavior

```
<Routes>
  <Route file="root.tsx">
    <Route path="app" index file="routes/app/_index.tsx" />
  </Route>
</Routes>
```

### Actual Behavior

```
<Routes>
  <Route file="root.tsx">
    <Route path="app" index file="routes/app/_index.tsx" />
    <Route path="app/footer" file="routes/app/footer.tsx" />
    <Route path="app/primary-nav" file="routes/app/primary-nav.tsx" />
  </Route>
</Routes>
```

Only `_index.tsx` should be considered as a route. Everything else should be ignored because considered as colocated files, as @kiliman says here:

https://github.com/remix-run/remix/pull/4880#issuecomment-1374909081

> @manzano78 You should probably create a new issue instead of commenting on a closed PR.
> 
> Anyway, yes. If you are using _flat-folders_ convention (where routes are folder names instead of filenames), then __index.tsx_ should be treated as the route and everything else as colocated files.
> 
> Can you run `npx remix routes` and paste the result? Please do so in another issue and reference this comment.
> 
> Thanks!

**Comment by kiliman** [comment]
Looks like a bug in the Remix core version. It's working fine with `remix-flat-routes` package.
```
❯ tree app/routes-remix-5028/
app/routes-remix-5028/
└── app
    ├── _index.tsx
    ├── footer.tsx
    └── primary-nav.tsx
```
```ts
❯ npx remix routes
<Routes>
  <Route file="root.tsx">
    <Route path="app" file="routes-remix-5028/app/_index.tsx" />
  </Route>
</Routes>
```
