### ISSUE TITLE
[Bug]: Could not resolve `"./client"`, `"./server"`, `"./platform"`

### ISSUE THREAD

**Issue by kubaprzetakiewicz** [remix-run/remix#504]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Just following the very first chapter of the tutorial:

```
npx create-remix@latest [./my-remix-app, Remix App Server, TypeScript, Yes]
cd my-remix-app
npm run dev
```

<details>
<summary>
Output:
</summary>

```
~/Projects/my-remix-app via ⬢ v16.13.0
➜ npm run dev

> dev
> remix dev

Watching Remix app in development mode...

 > node_modules/remix/browser/index.js:11:14: error: Could not resolve "./client"
    11 │ export * from './client';
       ╵               ~~~~~~~~~~

  > node_modules/remix/browser/index.js:12:14: error: Could not resolve "./server"
    12 │ export * from './server';
       ╵               ~~~~~~~~~~

  > node_modules/remix/browser/index.js:13:14: error: Could not resolve "./platform"
    13 │ export * from './platform';
       ╵               ~~~~~~~~~~~~


Build failed with 3 errors:
node_modules/remix/browser/index.js:11:14: error: Could not resolve "./client"
node_modules/remix/browser/index.js:12:14: error: Could not resolve "./server"
node_modules/remix/browser/index.js:13:14: error: Could not resolve "./platform"
💿 Built in 366ms
```

</details>

<details>
<summary>
Environment details:
</summary>

```
~/Projects/my-remix-app via ⬢ v16.13.0 took 2m 53s
➜ npm -v
8.1.4

~/Projects/my-remix-app via ⬢ v16.13.0
➜ node -v
v16.13.0

~/Projects/my-remix-app via ⬢ v16.13.0
➜ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

</details>

### Expected Behavior

The app would start properly and become available under http://localhost:3000 as per tutorial guidelines

### Actual Behavior

The app does not start due to build failing on module resolution

**Comment by Arcath** [comment]
I had the same problem with 1.0.4

Deleted my node_modules, package-lock.json and re-installed and its fine now.

The client.js, server.js and platform.js files where missing from the remix folder in my node_modules forlder.

**Comment by kubaprzetakiewicz** [comment]
Cleaning does not resolve the issue in my case - tried recreating the project several times, including installing it myself, trying with `pnpm`, etc.

Works with `yarn` though.

**Comment by girishk21** [comment]
to initialise the `remix` package, Remix has to be initialised by running a postinstall script. You can add the script to package.json as

```json
"postinstall": "remix setup <adapter>"
```

**Comment by EtienneGrall** [comment]
npm should automatically run the postinstall script after `npm install`. You probably set ignore-scripts to true in your local npm config. Running the script manually should make it work

**Comment by kubaprzetakiewicz** [comment]
```
➜ npm config list
; "user" config from /Users/kubaprzetakiewicz/.npmrc

ignore-scripts = true

; node bin location = /Users/kubaprzetakiewicz/.volta/tools/image/node/16.13.0/bin/node
; cwd = /Users/kubaprzetakiewicz/Projects/my-remix-app
; HOME = /Users/kubaprzetakiewicz
; Run `npm config ls -l` to show all defaults.
```

Of course, that's it! 🎉

I guess it's worth adding to the 101 section, I'll raise the PR.
