### ISSUE TITLE
Use of hammer operator crashes on node 14

### ISSUE THREAD

**Issue by lforst** [remix-run/remix#5043]
### What version of Remix are you using?

1.10.0

### Steps to Reproduce

Hi, `@sentry/remix` maintainer here.

We're observing test failures in our Node 14 Remix integration tests due to the use of the hammer operator in the `@remix-run/react` package: https://github.com/getsentry/sentry-javascript/actions/runs/3881841098/jobs/6621446961#step:6:1011

Is version 1.10.0 still supposed to be compatible with Node 14? The engines field in the package.json says so at least.

Let me know if you need more information! Thanks!

### Expected Behavior

`@remix-run/react` not to contain Node >=15 syntax.

### Actual Behavior

`@remix-run/react` has Node >=15 syntax.

**Comment by MichaelDeBoey** [comment]
Closed by #5047

**Comment by brophdawg11** [comment]
This is available in `1.10.0-pre.0` if you want to confirm it fixes your issue

**Comment by brophdawg11** [comment]
This is released in `1.10.1` 👍
