### ISSUE TITLE
leaf segment still loaded when parent segment caught response in catch boundary already

### ISSUE THREAD

**Issue by LOLBRUHNICE** [remix-run/remix#5060]
### What version of Remix are you using?

1.10.0

### Steps to Reproduce

Here is the example case: there are two routes, which is `/routes/$parent.tsx` and `/routes/$parent/leaf.tsx`
for `/routes/$parent.tsx`, the code is:
```tsx
import { Outlet } from "@remix-run/react";

export async function loader() {
    // this is just for example
    throw new Response("Not Found", { status: 404 });
}

export default function Parent() {
    return <div>
        <p>$parent</p>
        <Outlet />
    </div>
}

export function CatchBoundary() {
    return <p>Caught in $parent</p>;
}
```
for `/routes/$parent/leaf.tsx`, the code is:
```tsx
export default function Leaf() {
    return <p>Leaf</p>
}

export async function loader() {
    console.log("leaf");
    return null;
}
```

### Expected Behavior

The loader of leaf segment, which is `/routes/$parent/leaf.tsx`, should not be loaded since the loader in `/routes/$parent.tsx` already thrown a 404 Response and caught the 404 in catch boundary, so it shouldn't load the leaf segment

### Actual Behavior

The loader of leaf segment still loaded and logged `leaf` in the console

**Comment by machour** [comment]
Loading happens in parallel, to avoid the network waterfall.

This is why leaf gets called even if parent fails or throws.
