### ISSUE TITLE
[v1.10.0] TypeError: Cannot read properties of undefined (reading 'matches')

### ISSUE THREAD

**Issue by juniorforlife** [remix-run/remix#5073]
### What version of Remix are you using?

1.10.0

### Steps to Reproduce

- Upgrade to 1.10.0
- Reload the app
- The whole app crashes with this error 
`
TypeError: Cannot read properties of undefined (reading 'matches')
at Object.createStaticRouter (project-name/node_modules/@remix-run/react/node_modules/react-router-dom/server.js:189:25)
`

### Expected Behavior

No crashes

### Actual Behavior

Crashes with error `TypeError: Cannot read properties of undefined (reading 'matches')`

**Comment by machour** [comment]
Can you provide a reproduction somewhere?
Not much we can do with this report as it is.

**Comment by juniorforlife** [comment]
@machour  I can't share the source code because it's proprietary. Is it useful to upload a video recording?

**Comment by felixh10r** [comment]
@juniorforlife Do you access `EntryContext.matches` in your `entry.server.ts`?
f604197be74588c5bda1315443c47a2487e6e171 moved `EntryContext.matches` to `EntryContext.staticHandlerContext.matches`.

**Comment by juniorforlife** [comment]
I reverted to 1.9.0 and it works perfectly

**Comment by machour** [comment]
@brophdawg11 does this ring any bells?

**Comment by kiliman** [comment]
@juniorforlife v1.10 is the first version where Remix uses the new React Router.

I'm pretty sure if you scroll up in the dev console, you'll see additional errors which is most likely the root cause. Please report back with more info.

**Comment by kiliman** [comment]
Also, when you upgrade, make sure *ALL* your Remix dependencies are the same version. I see your dev dependencies are still at 1.7.6

**Comment by juniorforlife** [comment]
@kiliman @machour I've upgraded the dev dependencies and it works now. Thanks for your time

**Comment by juniorforlife** [comment]
@kiliman do I need to install @remix-run/router for 1.10.0?
Here's my package.json
```
"dependencies": {
    "@remix-run/node": "^1.10.0",
    "@remix-run/react": "^1.10.0",
    "@remix-run/vercel": "^1.10.0",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@vercel/node": "^2.6.2",
    "axios": "^1.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remix": "^1.10.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.10.0",
    "@remix-run/eslint-config": "^1.10.0",
    "@remix-run/serve": "^1.10.0",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.8",
    "autoprefixer": "^10.4.13",
    "concurrently": "^7.6.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.27.0",
    "postcss": "^8.4.19",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.8.4"
  },
```

**Comment by kiliman** [comment]
I don't think so. I believe that's an internal dependency.

**Comment by polarisdigitech** [comment]
Having the same issue with my deployment on Vercel, tried the suggestions on this thread but they didn't work for me

`
[GET] /
11:49:23:41
2023-01-13T10:49:24.049Z	368f560b-c5b3-4c5c-b676-ec78113658e1	ERROR	TypeError: Cannot read properties of undefined (reading 'matches')
    at Object.createStaticRouter (/var/task/node_modules/react-router-dom/server.js:189:25)
    at RemixServer (/var/task/node_modules/@remix-run/react/dist/server.js:59:23)
    at Uc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
    at Xc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Qc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:87:219)
    at Immediate._onImmediate (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:98:56)
    at processImmediate (node:internal/timers:471:21)
`

**Comment by binajmen** [comment]
> @juniorforlife Do you access `EntryContext.matches` in your `entry.server.ts`?
> [f604197](https://github.com/remix-run/remix/commit/f604197be74588c5bda1315443c47a2487e6e171) moved `EntryContext.matches` to `EntryContext.staticHandlerContext.matches`.

I hit the same wall. The answer was already given by @felixh10r above.

@polarisdigitech @juniorforlife You can access `matches` via `remixContext.staticHandlerContext`:
```diff
- remixContext.matches..
+ remixContext.staticHandlerContext.matches..
```
