### ISSUE TITLE
Vercel - TypeError: Cannot read properties of undefined (reading 'matches') at Object.createStaticRouter

### ISSUE THREAD

**Issue by polarisdigitech** [remix-run/remix#5089]
### What version of Remix are you using?

1.10.0

### Steps to Reproduce

- create remix app
- deploy to vercel

Can't really provide steps to reproduce cause it only happens on vercel. The app works fine locally on my machine.

### Expected Behavior

Should display the home page

### Actual Behavior

Every worked fine yesterday, but then I tried to deploy a change to the project, that's when I started having this issue.

ERROR	TypeError: Cannot read properties of undefined (reading 'matches') at Object.createStaticRouter (/var/task/node_modules/react-router-dom/server.js:189:25) at RemixServer (/var/task/node_modules/@remix-run/react/dist/server.js:59:23) at Uc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44) at Xc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253) at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89) at Qc (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:87:219) at Immediate._onImmediate (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:98:56) at processImmediate (node:internal/timers:471:21)

**Comment by AmirL** [comment]
I faced the same problem today with a fresh remix installation :(.

**Comment by loiccoenen** [comment]
I had the same issue. Now trying to kick off a new bare project. I have this error when using `npm start`:

```
Remix App Server started at http://localhost:3000 (http://192.168.50.8:3000)
TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
    at /home/jeanmouloud/code/sandbox/bastet-digital-sandbox/app/entry.server.jsx:85:4
    at new Promise (<anonymous>)
````

Not sure if it's related. Will attempt to reproduce and keep updated. Maybe will switch to deno if not working, looks like a webpack related error?

**Comment by AmirLatypov** [comment]
@loiccoenen I saw this either. You need to set NODE_ENV to production to run “npm run start”

**Comment by machour** [comment]
@AmirL I just bootstrapped a new project and it works: https://github.com/machour/test-vercel
Could you share a reproduction repo where it doesn't work?

**Comment by machour** [comment]
I'm able to reproduce the same issue if I remove the `@remix-run/vercel` dependency from my package.json
This is because Vercel have it harcoded to 1.6.1 in that case (see https://github.com/vercel/vercel/pull/9011)

So the problem might be an unaligned version of one of your remix dependencies 🤔

**Comment by polarisdigitech** [comment]
@machour I uninstalled all my remix dependencies and installed them again. I was on version 1.7 and then version 1.10 after the fresh installation, but the issue persisted across versions.

**Comment by polarisdigitech** [comment]
> @AmirL I just bootstrapped a new project and it works: https://github.com/machour/test-vercel Could you share a reproduction repo where it doesn't work?
> 
> @polarisdigitech can you do the same please? 🙏🏼

Not sure how to reproduce this given it's an issue that only happens on vercel

**Comment by machour** [comment]
@polarisdigitech do you have `@remix-run/vercel` in your dependencies at the same version? If not add it.

Vercel is using a fixed (and old) version of that package, it may have been compatible with 1.7, but it's not compatible with the new remix version.

Adding the dependency on your side make vercel take your required version instead of the old one

**Comment by AmirL** [comment]
Hi @machour
```npm i @remix-run/vercel```
It did help! Thanks.

**Comment by loiccoenen** [comment]
Weird, for me the error is still there and I don't have `vercel` in my deps, only: 

``` 
"@remix-run/dev": "^1.10.0",
    "@remix-run/node": "^1.7.5",
    "@remix-run/react": "^1.7.5",
    "@remix-run/serve": "^1.7.5",
```

Any other idea how to make that go away?

**Comment by machour** [comment]
@loiccoenen First thing first, you should **always** have the same version for all your remix dependencies.

Then, in order to fix this issue, you will have to add the @remix-run/vercel dependencies, as if you do not, vercel installs an old version, and it doesn't work.

**Comment by loiccoenen** [comment]
Thanks @machour that fixed the issue. It's just a workaround though, isn't there a way not to include vercel code altogether since i'm not using it (I have a custom drone CI).
