### ISSUE TITLE
useFetcher: fetcher.load doesn't revalidate when search params change

### ISSUE THREAD

**Issue by dT-Nick** [remix-run/remix#5090]
### What version of Remix are you using?

1.10.0

### Steps to Reproduce

[CodeSandbox URL](https://codesandbox.io/p/sandbox/loving-hugle-eiftb8?file=%2Fapp%2Froutes%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A53%2C%22endLineNumber%22%3A51%2C%22startColumn%22%3A53%2C%22startLineNumber%22%3A51%7D%5D)

Click the button `Change query string`. That submits a form that revalidates the index.tsx loader but doesn't revalidate fetcher.load. If you click the button `Run 'index.tsx' action`, it works as expected, and revalidates both.

The fetcher runs a resource route's loader - with the intent of using `shouldRevalidate` to manage whether it actually revalidates or not.

### Expected Behavior

I would expect a change in search params to revalidate all 'active' instances of fetcher.load by default (as per 1.10.0 updates, where fetcher.load revalidates). 

### Actual Behavior

Changing the search params doesn't seem to revalidate fetcher.load in this instance. I understand I could change the URL in `fetcher.load` to include the search params, but then the `shouldRevalidate` function in the resource route isn't run, and I'd have to stick any `shouldRevalidate` logic into the useEffect.

**Comment by brophdawg11** [comment]
Thanks @dT-Nick - I'm taking a look at this now.  I think this is a bug but confirming internally.  Fetchers have _slightly_ different `shouldRevalidate` logic at the moment and only fall into the `shouldRevalidate` flow on _explicit_ revalidations (after an action submission, a useRevalidate call, or a redirect that forced a revalidation by setting a cookie).  But it seems like they oughta respect the few additional scenarios that would cause a route loader to implicitly revalidate (route params changes, search params change, or clicking a link to the exact same current location)

**Comment by dT-Nick** [comment]
Great thanks! Perhaps this could go hand in hand with #5091. 

I know within a resource routes loader function you can access the referrer (the current URL a user is actually on) from the headers. So I'm hoping you might be able to access that (and the next referrer URL, similar to shouldRevalidate's `currentUrl` and `nextUrl`) from the `shouldRevalidate` function. I can see the `shouldRevalidate` function only runs on the client though, and I have no idea how it's working under the hood, so I'm assuming it's not that easy.

**Comment by brophdawg11** [comment]
Commented over there but yeah I think that's just a bug

**Comment by brophdawg11** [comment]
This should be fixed in Remix 1.12.0 which should be deployed in the next hour or two

**Comment by brophdawg11** [comment]
Released in 1.12.0
