### ISSUE TITLE
[Bug]: package.json repository and homepage links incorrect

### ISSUE THREAD

**Issue by ksmithut** [remix-run/remix#510]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [X] `create-remix`
- [X] `@remix-run/architect`
- [X] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [X] `@remix-run/express`
- [X] `@remix-run/netlify`
- [X] `@remix-run/node`
- [X] `@remix-run/react`
- [X] `@remix-run/serve`
- [X] `@remix-run/server-runtime`
- [X] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Go to npm for any of the above packages. The Repository and Homepage links link to https://github.com/remix-run/packages, which doesn't exist or is perhaps private

### Expected Behavior

I expect the links from npm to go to repositories to view the source code.

### Actual Behavior

It takes me to https://github.com/remix-run/packages, which is a github 404

**Comment by MichaelDeBoey** [comment]
This is fixed by #423

**Comment by ksmithut** [comment]
Thanks :)
