### ISSUE TITLE
useFetcher submit method is not passing submitted values as described in the docs

### ISSUE THREAD

**Issue by andersr** [remix-run/remix#5111]
### What version of Remix are you using?

1.10.1

### Steps to Reproduce

1. Create basic version of remix.
2. Replace the index page with the following code:

```javascript
import type { ActionArgs } from "@remix-run/node";
import { useFetcher } from "@remix-run/react";

export const action = async ({ request }: ActionArgs) => {
  const formData = await request.formData();
  const foo = formData.get("foo");
  console.log("foo: ", foo);

  return null;
};
export default function Index() {
  const fetcher = useFetcher();

  const onSubmit = () => {
    fetcher.submit(
      {
        foo: "bar",
      },
      { method: "post" }
    );
  };

  return (
    <div>
      <fetcher.Form>
        <button onClick={onSubmit} type="submit">
          Submit
        </button>
      </fetcher.Form>
    </div>
  );
}
```

3. Run the app and view the server logs

### Expected Behavior

Unless I am not following the docs at https://remix.run/docs/en/v1/hooks/use-fetcher
The passed value for `foo` should appear in the server logs.

### Actual Behavior

The passed value does not appear.

**Comment by andersr** [comment]
Reproduction using remix.new - https://stackblitz.com/edit/node-5yfppu?file=app/routes/index.tsx

**Comment by andersr** [comment]
Issue was that I was not including `method="post"` in `fetcher.Form`
This is somewhat confusing since I am including that in the `submit` method as per the docs.

**Comment by thedevbrian1** [comment]
The problem is that you can't have both onclick and type="submit" on the same button
