### ISSUE TITLE
Redirect with absolute path results in 404s

### ISSUE THREAD

**Issue by emilbryggare** [remix-run/remix#5117]
### What version of Remix are you using?

v1.10.1

### Steps to Reproduce

First clone PR https://github.com/remix-run/remix/pull/5116 with bug-report-test failing test case.

Then, make sure to install dependencies and build Remix. From the root of the project, run this:
```
yarn && yarn build
```

Now try running this test:

```
yarn bug-report-test
```

### Expected Behavior

A redirect to an internal absolute URL should work, and not result in a 404.

E.g. redirect('https://example.com/test') should work as well as redirect('/test')

### Actual Behavior

Currently, redirect('https://example.com/test') results in a 404.

This seems to be a regression, as it previously worked in my application before the React Router Remix.

@brophdawg11 tagging you based on the discussion with Michael Dem yesterday.

**Comment by brophdawg11** [comment]
Fixed in React Router: https://github.com/remix-run/react-router/pull/9913

**Comment by brophdawg11** [comment]
This should be available in `1.11.0-pre.1` shortly once CI finishes if you want to confirm it fixes your issue 👍

**Comment by emilbryggare** [comment]
@brophdawg11 works fine for my use case now! Thanks for swift work. 👍

**Comment by brandonpittman** [comment]
I had this as well, and the pre-release seems to have fixed it.

**Comment by brophdawg11** [comment]
Released in 1.11.0
