### ISSUE TITLE
Eliminate warnings from "unchanged files with check annotations"

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#5139]
### What version of Remix are you using?

Your mom's

### Steps to Reproduce

Check out https://github.com/remix-run/remix/pull/4860/files and scroll down a little. You'll see a large section with "unchanged files with check annotations" that are completely unrelated to that PR.

### Expected Behavior

No check annotations that are unrelated to the PR.

### Actual Behavior

A bunch of noise in PRs.

**Comment by chaance** [comment]
Fixed in https://github.com/remix-run/remix/pull/5141

**Comment by chaance** [comment]
For context, there is unfortunately no way to turn this off in GitHub. Logan switched out the puppeteer reporter to eliminate the output altogether when running in CI. This doesn't distinguish between annotations related to files changed within the PR or not, which is unfortunate. But we're limited by GitHub here.
