### ISSUE TITLE
styled-components fails in Facebook and TikTok browser

### ISSUE THREAD

**Issue by marianzburlea** [remix-run/remix#5144]
### What version of Remix are you using?

1.11.0

### Steps to Reproduce

- run `npx create-remix@latest project-name`
- select: `basic`, `typescript`, `netlify` and `n` so we can run **yarn**
- run `yarn add styled-components`
- run `yarn add -D @types/styled-components`
- create a basic styled component

```tsx
import styled from 'styled-components'

const H1 = styled.h1`
  border: 1px solid red;
`

export default function Index() {
  return (
    <div>
      <H1>test</H1>
    </div>
  )
}
```

update `entry.server.tsx` with:
```tsx
import { renderToString } from "react-dom/server";
import { RemixServer } from "@remix-run/react";
import type { EntryContext } from "@remix-run/node"; // or cloudflare/deno
import { ServerStyleSheet } from "styled-components";

export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  const sheet = new ServerStyleSheet();

  let markup = renderToString(
    sheet.collectStyles(
      <RemixServer
        context={remixContext}
        url={request.url}
      />
    )
  );
  const styles = sheet.getStyleTags();
  markup = markup.replace("__STYLES__", styles);

  responseHeaders.set("Content-Type", "text/html");

  return new Response("<!DOCTYPE html>" + markup, {
    status: responseStatusCode,
    headers: responseHeaders,
  });
}
```

inside `root.tsx` file update the **head** tag to include styles:

```tsx
    <head>
        <Meta />
        <Links />
        {typeof document === "undefined"
          ? "__STYLES__"
          : null}
    </head>

```

and deploy to **netlify**.

Here is an example project that replicates the issue:
https://github.com/marianzburlea/test-sc

and here is an example of the styled component receiving a red border.
https://steady-pixie-99fc00.netlify.app/

### Expected Behavior

actual styles to be displayed

![image](https://user-images.githubusercontent.com/1318985/213411948-98ecbf4c-70ba-494f-b6f8-dc39060d9f0c.png)

### Actual Behavior

hydration fails and no styles are applied, when I click on a link from Facebook and Tiktok. 

The BIG problem is not facebook messenger, it's how people that click paid ads see the website.

This is the same way users that click on an ad, end up on the website, with no styles.

![image](https://user-images.githubusercontent.com/1318985/213413509-316ab86d-cded-462f-bbe6-96c64a9fbbfe.png)

![image](https://user-images.githubusercontent.com/1318985/213413628-c3857730-c302-424d-89bf-117205c0d2fc.png)

**Comment by Xiphe** [comment]
Im experiencing similar issues outside of the context you describe.

Basically any hydration error where react is forced to rebuild the <head> will cause the styles of styled-components to be removed. While react itself recovers from this state, styled-components fails to do so.

As mentioned in #5159 I'd say this is not per se a remix bug but an architectural incompatibility as the issue can be reproduced with any react app failing to hydrate the whole document and might also happen to other libraries that inject things into the DOM.

**Comment by Xiphe** [comment]
related issue in react: https://github.com/facebook/react/issues/24430

**Comment by Xiphe** [comment]
I was able to work around the problem by adding by:

1. downgrading to react@17
2. ensuring that `{typeof document === "undefined" ? "__STYLES__" : null}` is rendered at the very end of the `<head>`

Would still love to use latest react features within my app.

**Comment by clgeoio** [comment]
+1 to this issue - Kent has responded to this issue [here](https://github.com/remix-run/remix/issues/1077#issuecomment-1117457264), stating that it is a React issue, which I think is fair enough.

There's a potential workaround, but it's not great - you can render Remix not at the document level, but within a <div> in the body.
By wrapping <RemixServer> in an HTML container you can solve this issue, however it comes at the cost of not being able to use <Meta> or <Links>.

**Comment by Xiphe** [comment]
Thanks for sharing. I was also tinkering around with rendering the remix app into a sub-element of the page but gave up because it caused too many things I love about remix to stop working.

As with the "who's problem is this": Yeah the issue lays between React and Styled Components. But Remix one the one hand made the architectural decision to work on the whole document which surfaces the problem and on the other hand advertises styled-components to work in remix apps (which it does but at the cost of react@18).

**Comment by clgeoio** [comment]
I have created a proposal / discussion for this issue https://github.com/remix-run/remix/discussions/5244

**Comment by Xiphe** [comment]
@kiliman figured out how to do this with the current tools and for me it solves the styled-components issues: https://github.com/remix-run/remix/discussions/5244#discussioncomment-4832036

**Comment by kiliman** [comment]
@Xiphe awesome... glad it resolved the styled-components issue for you.
