### ISSUE TITLE
nonce support for defer inline scripts

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#5156]
Because security please :)

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1500684/213620831-2658b8ba-bc44-4b9b-a451-f26cb2765758.png">

**Comment by kentcdodds** [comment]
Looks like this is a React issue as well: https://github.com/facebook/react/issues/26026

But Deferred will need these as well I think.

**Comment by kentcdodds** [comment]
Still relevant.

**Comment by jack-r-warren** [comment]
I'm hitting this issue too. I wasn't successful in writing any tests for `<Scripts />`+`<Await />` (JS beginner, sorry) so unfortunately can't make a PR but a tweak to https://github.com/remix-run/remix/pull/359/files to [pass the <Scripts /> props down through the internal DeferredHydrationScript](https://github.com/jack-r-warren/remix/commit/145600fff31d3b2367d2549b8c9313663d76a479) seems to solve this issue and #5539, in case it gives someone else a head-start here.
