### ISSUE TITLE
[Bug]: Errors when submitting fetcher.Form don't fall back to ErrorBoundary

### ISSUE THREAD

**Issue by airjp73** [remix-run/remix#517]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [x] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Add a route with the following code: ([stackblitz link](https://stackblitz.com/edit/github-6ofazo?file=app/routes/fetcher.tsx))

```jsx
import { useFetcher } from "remix";

export const action = () => {
  throw new Error("Whoops!");
};

export default function Component() {
  const fetcher = useFetcher();

  return (
    <div>
      <fetcher.Form method="post">
        <button type="submit">Submit fetcher form</button>
      </fetcher.Form>
      <form method="post">
        <button type="submit">Submit regular form</button>
      </form>
    </div>
  );
}
```

Open up the route and click the `Submit fetcher form` button.

### Expected Behavior

The error from the action should be handled by falling back to the nearest `ErrorBoundary`. The docs [here](https://remix.run/docs/en/v1.0.4/api/remix#usefetcher) back up this expectation.

> Handles uncaught errors by rendering the nearest ErrorBoundary (just like a normal navigation from \<Link\> or \<Form\>)

### Actual Behavior

The form submit fails (500 in network tab), but it does not fall back to the `ErrorBoundary`. If you submit the regular form, this is what happens.

### Failing Test

I've implemented a failing test in #523.

**Comment by ryanflorence** [comment]
Thanks for your help here @airjp73, sorry we didn't get to this sooner. Do you think #860 addresses this? If not, please reopen! (Or maybe send a new PR since we took a while to start paying attention to the PRs coming through after the release!)
