### ISSUE TITLE
Routing file version 2 nested layout path does not match

### ISSUE THREAD

**Issue by omakise** [remix-run/remix#5172]
### What version of Remix are you using?

1.11.1

### Steps to Reproduce

The problem has been solved.

### Actual Behavior

**Comment by mcansh** [comment]
not getting `post/about` in dev, but when using flat routes and folders, the route file must be `index`

```log
app/
├── routes/
│   └── _post.post/about
│       └── index.md
```

**Comment by kiliman** [comment]
@akun2333 Remember that once you start adding folders, flat routes will switch to flat-folders mode (it assumes you want colocation). The folder name itself is the route. The route _file_ must be `index.js` or (.tsx, .md, etc.). 

It's the same as the index file when doing imports from a folder. `import About from '~/routes/_post.post/about'`

Any other file, like _component.tsx, styles.css, logo.png_, etc. will be treated as a colocated file.

**flat-file**
`routes/_post.post.about.md`

**flat-folder**
`routes/_post.post.about/index.md`
