### ISSUE TITLE
Docs: Broken link in entry.client page

### ISSUE THREAD

**Issue by panteliselef** [remix-run/remix#5192]
### What version of Remix are you using?

latest

### Steps to Reproduce

Go to the [docs website > entry.client](https://remix.run/docs/en/v1/file-conventions/entry.client) click on the link with label "[server entry module]"

You get 404

### Expected Behavior

This link should redirect you to https://remix.run/docs/en/v1/file-conventions/entry.server

### Actual Behavior

Go to the [docs website > entry.client](https://remix.run/docs/en/v1/file-conventions/entry.client) click on the link with label "[server entry module]"

You get 404

**Comment by machour** [comment]
Fixed by #5194
