### ISSUE TITLE
route styles load after component renders

### ISSUE THREAD

**Issue by cdock1029** [remix-run/remix#52]
When navigating to route with its own css file defined, the styles seem to load after the route component is rendered by the browser, showing a flash of unstyled content.

A simplified example

https://github.com/cdock1029/remix-route-css

`about.css`

```css
.about-page {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 1rem;
}

```
`about.tsx`
```tsx
export default function About() {
  const items = useRouteData();
  return (
    <div className="about-page">
      <div style={{ border: "1rem solid green" }}>
        <ul>
          {items.map((it: any) => (
            <li style={{ padding: "1rem" }} key={it.id}>
              {it.data}
            </li>
          ))}
        </ul>
      </div>
      <div
        style={{
          border: "1rem solid red",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <h1>Detail route content</h1>
      </div>
    </div>
  );
}

```

![start](https://user-images.githubusercontent.com/802586/99329297-e4ba3980-284b-11eb-9387-d419b1027290.png)

![end](https://user-images.githubusercontent.com/802586/99329305-e84dc080-284b-11eb-831f-609fb615fcfc.png)

The network shows that the css is still loading for that component while it's displayed. Don't know the implementation details, but maybe there's a way to inject the styles before the component renders.

**Comment by chaance** [comment]
Hi! I'm not a bot, but I'm closing out old issues that have long grown stale and are likely not up-to-date with recent versions. Feel free to ping me if this is still an issue and I can reopen.

**Comment by martinmckenna** [comment]
i just opened another issue because funnily enough, i'm seeing this after upgrading from v1 to v2:

https://github.com/remix-run/remix/issues/7516
