### ISSUE TITLE
[Bug]: title of document in params example is showing `Param: undefined` when loading error screens

### ISSUE THREAD

**Issue by adnan-sheikh** [remix-run/remix#520]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

If we go through the Developer Blog quickstart project and after installing remix:
1. run the app `npm run dev`
2. go to `URL Params and Error Boundaries` link.
3. Now go to any error 404 / 401 / error page links, notice the title of the page: `Param: undefined`

### Expected Behavior

Travelling to any error page 404 / 401 / error page links, should display a document title `Oops...`

### Actual Behavior

Travelling to any error page 404 / 401 / error page links, displays a document title `Param: undefined`

**Comment by machour** [comment]
Already fixed according to Ryan's comment on #522
