### ISSUE TITLE
Flat Routes fixes and improvements

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5241]
PR: https://github.com/remix-run/remix/pull/5228

**Comment by ryanflorence** [comment]
add `route.js` since folks are confused by folder imports with node module resolution

**Comment by kiliman** [comment]
Be careful. Once you go down that rabbit hole, it's hard to go back.

Yeah, differentiating between index `routes` and an index `file` in a folder can be a little confusing to the uninitiated.

**Comment by ryanflorence** [comment]
@ryanflorence to give a thumbs up

**Comment by zifahm** [comment]
thumbs down, I support the remix-flat-route convensions
