### ISSUE TITLE
Do not remove server build file before rebuild on `remix dev`

### ISSUE THREAD

**Issue by izznatsir** [remix-run/remix#5248]
### What version of Remix are you using?

0.0.0-nightly-c9ff7ef-20230125

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I'm using the new dev server:

1. Clone this repository: [https://github.com/izznatsir/remix-nightly-cloudflare](https://github.com/izznatsir/remix-nightly-cloudflare).
2. `pnpm install`
3. `pnpm run dev`
4. Make change in `app/routes/index.tsx`.

### Expected Behavior

Server build file is not removed so Wrangler will not restart twice.

### Actual Behavior

Server build is removed first before rebuilding the server. Wrangler restart twice, first when the file is removed and second when the rebuild is done. This produce this warnings in the terminal:

![Screenshot from 2023-01-25 15-00-42](https://user-images.githubusercontent.com/32354148/214511775-dce03dbf-0f91-4505-ac61-a33abe06ba0b.png)

Notice that wrangler assumes that there is no route in `functions` directory because the `[[path]].js` is removed before being rebuilt.

It caused by changes in #5223. Assets build directory needs to be cleaned because it contains hash that are changed after rebuild, but server build file has static filename. I think we should bring back old behavior for server build which is replaced on write.

**Comment by izznatsir** [comment]
Confirmed to works just fine on version `0.0.0-nightly-c08f30f-20230123` (before #5223): [https://github.com/izznatsir/remix-nightly-cloudflare/tree/rollback](https://github.com/izznatsir/remix-nightly-cloudflare/tree/rollback)

**Comment by pcattori** [comment]
Good catch! 🙏

**Comment by pcattori** [comment]
Closed by #5251
