### ISSUE TITLE
Fetcher submit no longer following x-remix-redirect

### ISSUE THREAD

**Issue by Benjamin-Dobell** [remix-run/remix#5269]
### What version of Remix are you using?

1.11.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

In a non-root route add something like:

```ts
export async function action({ request }: ActionArgs) {
  return redirect("/");
}

export default function Thingo() {
  const { submit } = useFetcher<typeof action>();

  useEffect(() => {
    submit({}, { method: "post", replace: true });
  }, []);

  return <div/>;
})
```

### Expected Behavior

Should be redirected to the root.

### Actual Behavior

Redirect is ignored.

**Comment by Benjamin-Dobell** [comment]
Last working in 1.9.0.

**Comment by ratasorin** [comment]
I had the same issue. You can try `useSubmit()` when programmatically submiting forms: https://reactrouter.com/en/6.8.1/hooks/use-submit

**Comment by brophdawg11** [comment]
@Benjamin-Dobell Could you provide a reproduction of the issue you're seeing?  This is working for me in https://stackblitz.com/edit/remix-run-remix-8bderx?file=app%2Froutes%2Fpage.tsx.  Both with a button clicked `fetcher.submit` as well as an effect-driven `fetcher.submit`

**Comment by brophdawg11** [comment]
This is actually working for me in `1.11.0` as well so I am assuming it was a separate issue.  I'm going to close this out but please reopen with a minimal reproduction if this is still an issue for you!
