### ISSUE TITLE
blog - scroll is broken

### ISSUE THREAD

**Issue by tkrotoff** [remix-run/remix#5276]
### Steps to Reproduce

Go to https://remix.run/blog
Click on any article
The bottom of the article is displayed instead of the top because the input field from "Get updates on the latest Remix news" is focused

With Chrome 109, Firefox 109, Safari 16.2

Btw where is remix.run/blog source code? Do you plan to release it?

**Comment by machour** [comment]
Moved to the website repository, thanks!
The website repository isn't public yet, and no plans to release it so far.

**Comment by machour** [comment]
This problem should be fixed now.
