### ISSUE TITLE
[Bug]: Could not locate @remix-run/serve on npm run dev

### ISSUE THREAD

**Issue by ksorv** [remix-run/remix#529]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

- `npx create-remix@latest`
- npm run dev
- Selected `Remix App Server` and `Typescript`

### Expected Behavior

It should start a remix server and serve the app

### Actual Behavior

It exits the process with an error `Could not locate @remix-run/serve. Please verify you have it installed to use the dev command.`

More Info:

Node Version - 12.14.1
NPM Version  - 7.19.0
OS: 
<img width="600" alt="Screenshot 2021-11-23 at 10 31 01 PM" src="https://user-images.githubusercontent.com/34188267/143070041-0a4b6be4-7aa2-4aa2-ae1d-b4f5be07c565.png">

Please ask out if you need more info.

**Comment by ksorv** [comment]
IDK if this is intentional as this was not mentioned in [this](https://remix.run/docs/en/dev/tutorials/blog) official tutorial but it works just fine with node v14. So, I'll be closing this one.

**Comment by willin** [comment]
but node 16 occurs the same error

**Comment by franklinjavier** [comment]
I'm using Vercel template and occurs the same error

```sh
▲ remix-storefront (main) ✗ node -v
v16.13.0
▲ remix-storefront (main) ✗ yarn dev
yarn run v1.21.1
$ remix dev
Could not locate @remix-run/serve. Please verify you have it installed to use the dev command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

````

**Comment by Tanner-Scadden** [comment]
Running into this issue with the vercel template as well. Package wasn't included in the dependencies from the template.

**Comment by mcansh** [comment]
@Tanner-Scadden @franklinjavier sorry! will get a patch release out Monday with this included

**Comment by rjgux** [comment]
Having this issue too, using Vercel.

**Comment by Girish21** [comment]
as a temporary solution, run

```sh
npm install --save-dev @remix-run/serve
```

**Comment by alvaromartmart** [comment]
I'm facing the same issue on node v12

**Comment by girishk21** [comment]
> I'm facing the same issue on node v12

@alvaromartmart Remix requires Node version 14 or greater

**Comment by alvaromartmart** [comment]
> > I'm facing the same issue on node v12
> 
> @alvaromartmart Remix requires Node version 14 or greater

Is this documented somewhere? I couldn't find it

**Comment by girishk21** [comment]
@alvaromartmart they have specified it in [`package.json`](https://github.com/remix-run/remix/blob/main/packages/create-remix/templates/_shared_ts/package.json#L23) for the starter templates

**Comment by mcansh** [comment]
sorry about that 😅. fixed in [1.0.6](https://github.com/remix-run/remix/releases/tag/v1.0.6)

**Comment by mcansh** [comment]
> > I'm facing the same issue on node v12
> 
> @alvaromartmart Remix requires Node version 14 or greater

we should probably document this somewhere if we haven't already, but we do set the engine in package.json to `"node": ">=14"`

**Comment by m5r** [comment]
I'm facing the same issue with remix@1.0.6 and node@16.13.1 but it's working fine with node@14.18.2

I'll keep using node 14 for now but I'd prefer using the current LTS, could we reopen this issue?

**Comment by Elijah97** [comment]
> but node 16 occurs the same error

For me I updated from node 12 to node 16, then it automatically worked. Maybe you could also try to update npm then clean cache

**Comment by sbodi10** [comment]
Node 16 didn't work for me when deploying. I switched to Node 14 and it worked.

**Comment by kushalmahajan** [comment]
Node 15.x and node `v16.13.1` doesn't work. This issue should be reopened

**Comment by coreybruyere** [comment]
Having this issue. Tried all the above with no luck.

**Comment by oluwatobiadegoke** [comment]
> Having this issue. Tried all the above with no luck.

Same thing here

**Comment by cdeutsch** [comment]
Also make sure `@remix-run/serve` is in your regular dependencies (not just dev dependencies) 

Seemed to make a difference on Heroku.

**Comment by rashidtvmr** [comment]
same issue. Coudnt run remix express basetemplate but able to run Indie template which is express template.

**Comment by AvidDabbler** [comment]
Yup just ran `npx create-remix@latest ./my-app` went with `just the basics` and `express server`, installed, built and I am getting this error.

**Comment by jmims-magnusdigital** [comment]
> Yup just ran `npx create-remix@latest ./my-app` went with `just the basics` and `express server`, installed, built and I am getting this error.

Just did this recently, and found that it was missing; went looking for a reason and found this... oops...
