### ISSUE TITLE
docs: update vertical alignment of "Docs Navigation" in mobile header

### ISSUE THREAD

**Issue by dgurns** [remix-run/remix#5291]
### What version of Remix are you using?

1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- View https://remix.run/docs with mobile viewport
- In the header, "Docs Navigation" is not vertically aligned with the search icon and "Remix"

It's a small thing, but for a newcomer to Remix visiting the docs on mobile, it's not an ideal first impression.

Would be happy to fix this but it doesn't look like the docs site UI is part of the open source repo.

### Expected Behavior

- Would expect "Docs Navigation" to be vertically aligned with the search icon and "Remix"

Something like this...

<img width="398" alt="Screenshot 2023-01-28 at 11 44 08" src="https://user-images.githubusercontent.com/1173791/215264934-343f98b9-e7a2-425d-ac96-f245726c1f77.png">

### Actual Behavior

Screenshot of current behavior:

<img width="395" alt="Screenshot 2023-01-28 at 11 53 50" src="https://user-images.githubusercontent.com/1173791/215265131-1ae8746b-3d6d-498d-ab5d-1468686b2416.png">

**Comment by machour** [comment]
Moved to the website repository, thanks!
