### ISSUE TITLE
Cookies don't load on first page load after redirect from other site

### ISSUE THREAD

**Issue by SleeplessByte** [remix-run/remix#5296]
### What version of Remix are you using?

1.10.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Given the follow cookie session storage:

```typescript
import type { Session } from "@remix-run/node";
import { createCookieSessionStorage } from "@remix-run/node"; // or cloudflare/deno

const { getSession, commitSession, destroySession } =
  createCookieSessionStorage({
    // a Cookie from `createCookie` or the CookieOptions to create one
    cookie: {
      name: "__session",

      // all of these are optional
      // domain: "remix.run",
      // Expires can also be set (although maxAge overrides it when used in combination).
      // Note that this method is NOT recommended as `new Date` creates only one date on each server deployment, not a dynamic date in the future!
      //
      // expires: new Date(Date.now() + 60_000),
      httpOnly: true,
      maxAge: 60 * 60 * 24 * 14,
      path: "/",
      sameSite: "strict",
      secrets: ["BootingGauzePostnasalExtraditePagerChlorine"],
      secure: true,
    },
  });

export { getSession, commitSession, destroySession };
```

The following loader doesn't behave as expected:

```typescript
export async function loader({ request }: DataFunctionArgs) {
  const session = await getSession(request.headers.get("Cookie"));

  // There is no session data
  if (!session.has("token")) {
    return redirect("/login");
  }

  return json({})
}
```

You can experience this yourself (that's the actual code) on https://test.dashboard.groteprijsvan.nl/. (it's free to sign up, use dummy data as you wish). If you are logged in (if a cookie is stored) and you go to that URL directly, everything works as expected. If you click the link in this issue, the first page load will redirect to `/login`. Pressing F5 then works and "logs you in".

### Additional context

This is hosted and experienced on Netlify. There may be something fishy with their implementation? Caching? NO caching headers have been added in this project's loaders, nor in any netlify configuration. I experience this on a fresh project as well (which prompted me to open this issue).

### Expected Behavior

`console.log(session.get('token'))` has the value on every page load. This means it's consistent if you go there directly, or if you go there via another link.

### Actual Behavior

`console.log(session)` is completely empty when redirecting from another site. Fixed on refresh.

### Screenshots

Clicking on the link in this issue:

![image](https://user-images.githubusercontent.com/1964376/215301814-9e63bee7-0116-49c2-9161-9d52e4800461.png)

Pressing F5 (or navigating directly):

![image](https://user-images.githubusercontent.com/1964376/215301791-a93603e6-8a48-4341-a932-2bdccc5a277c.png)

**Comment by sergiodxa** [comment]
This is a browser expected behavior, when you set SameSite: Strict in a cookie the browser will not send that cookie when the user came from another origin, but it will do it after a refresh or on a same origin navigation.

**Comment by SleeplessByte** [comment]
Ah yeah, of course. I forgot that was set up here.

I'll report back and re-open if setting it to Lax doesn't solve this.

**Comment by SleeplessByte** [comment]
They reported it all works as expected. Thanks for the point @sergiodxa.
