### ISSUE TITLE
[Bug]: Demo - URL Params and Error Boundaries - Nested `<p>` console error in `CatchBoundary`

### ISSUE THREAD

**Issue by joshuadotson** [remix-run/remix#532]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

* nav to `./examples/basic`
* install dependencies `npm i`
* start dev server `npm dev`
* open `http://localhost:3000/`
* choose `URL Params and Error Boundaries` under `Demos In This App`
* open dev tools console
* select `This will be a 404` under `Click these Links`
* observe error in console

### Expected Behavior

No error occurs because the HTML structure is valid.

### Actual Behavior

`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

Above error occurs because the HTML structure is not valid.

**Comment by machour** [comment]
Fixed in #535
