### ISSUE TITLE
🗺️ Deprecate `serverBuildTarget`

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5334]
- Stop relying on it our templates
- un-deprecate `serverModuleFormat`

## Progress

- [ ] RFC: 
- [x] `@remix-run/dev` PR: https://github.com/remix-run/remix/pull/4841
- [x] templates PR: https://github.com/remix-run/remix/pull/4842

## Related Issues

- https://github.com/remix-run/remix/discussions/4615

**Comment by ryanflorence** [comment]
@mjackson and @jacob-ebey to get together to wrap this up, we'd like it done this week

**Comment by MichaelDeBoey** [comment]
Both #4841 & #4842 are merged now
