### ISSUE TITLE
Environment variables are not loading with remix-serve

### ISSUE THREAD

**Issue by andrecasal** [remix-run/remix#5341]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone https://github.com/andrecasal/testing-environment-variables and `npm i`
2. Run `npm run dev`
3. Notice the environment variable `SESSION_SECRET` is logged on the server console
4. Run `npm build` and `npm start`
5. Notice the environment variable `SESSION_SECRET` is undefined

### Expected Behavior

The environment variable `SESSION_SECRET` to be available.

### Actual Behavior

The environment variable `SESSION_SECRET` is undefined.

**Comment by kiliman** [comment]
With Remix App Server, environment variables are only loaded on development via `dotenv`

When you run `npm start`, Remix sets `NODE_ENV=production` automatically, but all other environment variables are handled by your host.

The assumption is that you will set up production environment variables via your hosting provider. For example, Fly has Fly Secrets https://fly.io/docs/reference/secrets/

**Comment by andrecasal** [comment]
Thanks for the clarification @kiliman 👍

I've got environment variables working correctly locally with `npm start` on another repo (with same 1.12.0 version of Remix), but I can't remember what I've done. Trying to isolate it so I can share here.

**Comment by kiliman** [comment]
If you're trying to run a production build of your app locally with .env files, you can install the `dotenv-cli` and update your start script:
```json
"start": "dotenv -e .env.production remix-serve build"
```
https://github.com/entropitor/dotenv-cli#readme

**Comment by andrecasal** [comment]
If you use Prisma, it will automatically load your .env variables:
1. `npm i @prisma/client` and `npm i -D prisma`
2. Copy this to root.tsx:
```tsx
import { Links, LiveReload, Meta, Scripts, ScrollRestoration } from '@remix-run/react'

import { PrismaClient } from "@prisma/client"
const prismaClient = new PrismaClient()

console.log(JSON.stringify(process.env))

export default function App() {
	return (
		<html lang="en">
			<head>
				<Meta />
				<Links />
			</head>
			<body>
				<h1>Hello world</h1>
				<ScrollRestoration />
				<Scripts />
				<LiveReload />
			</body>
		</html>
	)
}
```
3. Run `npm build` and `npm start`
4. Notice your .env variables will print to the server console:
```json
{
	...
	"SESSION_SECRET":"2134567865432",
	"DATABASE_URL":"file:./dev.db"
}
```

**Comment by andrecasal** [comment]
Just in case someone gets here, assuming a schema.prisma:
```
datasource db {
   url      = env("DATABASE_URL")
}
```

`import { PrismaClient } from '@prisma/client'` unconditionally tries to loads the `.env` file.

It then errors out if it doesn't find a `process.env['DATABASE_URL']` (whether or not it found an .env file to load).

Note: If you're `remix build`ing, `import { PrismaClient } from '@prisma/client'` by itself won't load the `.env` file because it's tree-shaken on the production build. You also need `const prismaClient = new PrismaClient()` to load the `.env` file.

**Comment by mcfriend99** [comment]
> If you're trying to run a production build of your app locally with .env files, you can install the `dotenv-cli` and update your start script:
> 
> "start": "dotenv -e .env.production remix-serve build"
> https://github.com/entropitor/dotenv-cli#readme

Didn't work

**Comment by mcfriend99** [comment]
> If you use Prisma, it will automatically load your .env variables:
> 
> 1. `npm i @prisma/client` and `npm i -D prisma`
> 2. Copy this to root.tsx:
> 
> import { Links, LiveReload, Meta, Scripts, ScrollRestoration } from '@remix-run/react'
> 
> import { PrismaClient } from "@prisma/client"
> const prismaClient = new PrismaClient()
> 
> console.log(JSON.stringify(process.env))
> 
> export default function App() {
> 	return (
> 		<html lang="en">
> 			<head>
> 				<Meta />
> 				<Links />
> 			</head>
> 			<body>
> 				<h1>Hello world</h1>
> 				<ScrollRestoration />
> 				<Scripts />
> 				<LiveReload />
> 			</body>
> 		</html>
> 	)
> }
> 3. Run `npm build` and `npm start`
> 4. Notice your .env variables will print to the server console:
> 
> {
> 	"SESSION_SECRET":"123456",
> 	"DATABASE_URL":"file:./dev.db"
> }
> It seems that as soon as `new PrismaClient()` runs, it will automatically load .env variables.
> 
> I'm wondering about the consequences of this 🤔

I'm using prisma and it didn't.
