### ISSUE TITLE
1.12 WebSocket connection to 'wss://.../socket' failed

### ISSUE THREAD

**Issue by atsolberg** [remix-run/remix#5348]
### What version of Remix are you using?

1.12

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I created a simple repository to produce the issue using 'just the basics' and 'express' options: https://github.com/atsolberg/remix-basic-express-with-ssl-v2-dev see README for details.

Starting with a basic remix app using express, I added self-signed certificate files, and in `server.js` used node's `https` `createServer` to create a server using the express app with the certificate https options.

- App expects to run on port `4242` instead of `3000` so start up with `PORT=4242 npm run dev` or change remix config `appServerPort` locally.
- Start chrome with some flags to ignore cert issues with self-signed certificates: 
  ```
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/foo --ignore-certificate-errors --ignore-ssl-errors --unsafely-treat-insecure-origin-as-secure=https://localhost:4242
  ```
- Then visit `https://localhost:4242`

---

**NOTE:** I use `localremix` instead of `localhost` by adding `127.0.0.1 localremix` to my `etc/hosts` file, and the self-signed certificate files in this repo were created referencing `localremix` as the common name (CN).  You might want to use your own certificate files or you can use `https://localremix:4242` by added `127.0.0.1 localremix` to your `etc/hosts` file like I did.  You can supply the directory path to your cert files using the `CERT_DIR` env var at startup: `CERT_DIR=Users/bob/my-certs PORT=4242 npm run dev`.   `server.js` expects the cert file names to be `key.pem` and `cert.pem`.

---

### Expected Behavior

- The client side live-reload web socket would connect over `wss:` protocal
- The `future: { unstable_dev: { port } }` option would force the client to connect on that port, it always seems to use a random port

### Actual Behavior

- The client side live-reload web socket connect always fails
- Even with`future: { unstable_dev: { port } }` option set, always seems to use a random port. 

### Client Side Error

![image](https://user-images.githubusercontent.com/2157412/216363439-218d2101-ccde-42d3-ad01-8a7395685bfc.png)

### Chrome App Error

```
[72201:19971:0202/093415.517540:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -107
```

**Comment by atsolberg** [comment]
One update, running with the old dev server (and using `remix watch` instead of `remix dev`), I still see the same connection failed error.  So issue might be inherent to both dev servers.

**Comment by pcattori** [comment]
Possible solution/workaround from a Remix discord community member:

> I had to hack around it with my own LiveReload since I am using it in a Docker container.  Basically I tell remix that my WS port is 8003 and set the LiveReload component port to 8004 so that it can connect to my Traefik load balancer to successfully terminate it.

**Comment by atsolberg** [comment]
**Update**  
I retried using a valid certificate signed with a certificate authority using this **AWESOME** tool [mkcert](https://github.com/FiloSottile/mkcert), just to make sure that using self-signed certificates was not the issue:

![image](https://user-images.githubusercontent.com/2157412/216781725-37f55bf7-9799-4e37-9912-cd9f513aaf97.png)

Unfortunately still seeing the ws connection failure, but at least I have non-sketchy certificates for my team now!

**Comment by atsolberg** [comment]
Update: It works!

Credit to [Eladchen](https://github.com/eladchen) https://github.com/remix-run/remix/issues/2859#issuecomment-1277467440 for the idea of using the remix app server to proxy websocket requests from the dev server to client.

Needed 3 things to make this work:

1. Edited the `node_modules/@remix-run/react/dist/components.js` `<LiveReload />` component so that is always used the `port` prop if provided, allowing me to set it to the express https server port instead of the dev server port. 

![image](https://user-images.githubusercontent.com/2157412/218498432-4a56a450-aba6-4259-bf7a-7a86a24790ff.png)

![image](https://user-images.githubusercontent.com/2157412/218496531-7694d597-ec5a-448f-b11c-5e15fd1bee8c.png)


2. Added a websocket to the https express app to relay messages from the dev server to the client.

![image](https://user-images.githubusercontent.com/2157412/218496902-3b66090c-3760-4f2e-9be3-36a8139624ef.png)

3. Edited `node_modules/@remix-run/dev/dist/devServer2.js` to allow me to set the protocol and host from new config properties so that `appServerOrigin` could be a valid url to my express https server.

![image](https://user-images.githubusercontent.com/2157412/218498157-b5d55da6-40da-48bc-b5e0-cfc057ae2262.png)

![image](https://user-images.githubusercontent.com/2157412/218497359-4bde9149-283e-4b37-a082-e1e03e956a8a.png)

After that I just needed to set an env var so that node would use `mkcert` as an additional certificate authority like browsers do: [NODE_EXTRA_CA_CERTS](https://github.com/FiloSottile/mkcert#using-the-root-with-nodejs) 

And then the requests from devServer2.js for the new asset manifest started working, and BAM!, working HMR with and express https server!

**Comment by Mange** [comment]
I seem to be having the same issue. None of the configuration options seem to be respected.

```js
// remix.config.js
{
	unstable_dev: {
	  // ...
	  port: 8002,
	},
	devServerPort: 8002,
	// ...
}
```

```jsx
<LiveReload port={8002} />
```

…and yet on every boot it will try a new random port and get a connection error, since my app server runs inside of a Docker container with limited port forwarding.

**Comment by pcattori** [comment]
Obsoleted by #6133
