### ISSUE TITLE
[Bug]: nested `<p>` tag in another `<p>` in a couple of examples

### ISSUE THREAD

**Issue by arpitdalal** [remix-run/remix#535]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

In the `examples/basic` and `examples/blog-tutorial`
1. run application on the dev server
2. open `console` from `devtools`
3. visit any one of these routes [localhost:3000/demos/params/shh-its-a-secret](http://localhost:3000/demos/params/shh-its-a-secret) or [localhost:3000/demos/params/this-record-does-not-exist](http://localhost:3000/demos/params/this-record-does-not-exist)

### Expected Behavior

No errors in the console other than HTTP errors such as `401` and `404`

### Actual Behavior

A warning saying that `<p>` should not be nested into another `<p>`

Exact warning:
`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

**Comment by arpitdalal** [comment]
closed in #533

**Comment by arpitdalal** [comment]
Actually, #533 only partially fixes it. #533 doesn't fix the blog-tutorial example

**Comment by ryanflorence** [comment]
Thank you for your help, but it looks like we've already fixed this.

If I'm wrong, please re-open this issue and we'll get it sorted out. Thanks!
