### ISSUE TITLE
`useParams` type should not return optional

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#5355]
### What version of Remix are you using?

1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

The `useParams` type returns a record where the values can be `string | undefined` instead of simply `string`. This is far from convenient from an end-user perspective and makes me wonder why I'm even able to do something like this:

```tsx
// { accountName?: string; projectId?: string }
const { accountName, projectId } = useParams<'accountName' | 'projectId'>();

<Link to={`/${accountName as string}/${projectId as string}`} />
```

...when it's return type is essentially the same as `useParams` without any type parameters:

```tsx
// Record<string, string | undefined>
const { accountName, projectId } = useParams();

<Link to={`/${accountName as string}/${projectId as string}`} />
```

### Expected Behavior

Instead, I would expect that putting in the extra work to add the type parameter would make those fields required in the return type so I don't have to use the nullish operator (or use an `as` assertion as seen above) later on:

```tsx
// { accountName: string; projectId: string }
const { accountName, projectId } = useParams<'accountName' | 'projectId'>();

<Link to={`/${accountName}/${projectId}`} />
```

### Actual Behavior

The return type still marks those properties as optional. I have to manually add an assertion to satisfy TS. This makes me wonder why that type parameter even exists in the first place. Sure, it makes it so I can't access arbitrary fields on `useParams` but the fields that I do specify are still marked as optional (which seems like undesired behavior).

**Comment by nicholaschiang** [comment]
If y'all agree with this change, I'd also be more than happy to implement it myself. Doesn't seem like it would be too hard to do (it seems to me like all it would take is a small one line change [here](https://github.com/remix-run/react-router/blob/0ce0e4c728129efe214521a22fb902fa652bac70/packages/react-router/lib/hooks.tsx#L258)).

**Comment by machour** [comment]
Remix is doing the right thing.

Consider this routes:

- app/routes/news.tsx
- app/routes/news/$slug.tsx

In the news.tsx file, if I use `const { slug } = useParams()`, `slug` will be undefined when I'm on "/news", and will equal "foo" if I'm on "/news/foo". 

So everything returned by useParams() can be undefined when not used in the route segment when the parameter is in the path. Hence the `undefined | string`

**Comment by nicholaschiang** [comment]
@machour whats the purpose of having the type parameter then if it doesn't do anything useful?

**Comment by machour** [comment]
Oh, you just have a little error.

You should do:

```jsx
const { slug } = useParams<{slug: string}>();
```

Here, you are correctly telling useParams: your return value is an object that has a string "slug" property, and you're reading slug by destructuring that return value.

**Comment by nicholaschiang** [comment]
ah, awesome, i'm stupid. 🤦

**Comment by nicholaschiang** [comment]
@machour actually, the type definition is still incorrect.

```ts
const { slug } = useParams<{ slug: string }>();
typeof slug; // this will still be string | undefined because useParams returns Partial<ParamsOrKey>
```

see [the implementation i linked to earlier](https://github.com/remix-run/react-router/blob/0ce0e4c728129efe214521a22fb902fa652bac70/packages/react-router/lib/hooks.tsx#L257-L261):

```ts
/**
 * Returns an object of key/value pairs of the dynamic params from the current
 * URL that were matched by the route path.
 *
 * @see https://reactrouter.com/hooks/use-params
 */
export function useParams<
  ParamsOrKey extends string | Record<string, string | undefined> = string
>(): Readonly<
  [ParamsOrKey] extends [string] ? Params<ParamsOrKey> : Partial<ParamsOrKey>
> {
  let { matches } = React.useContext(RouteContext);
  let routeMatch = matches[matches.length - 1];
  return routeMatch ? (routeMatch.params as any) : {};
}
```
...that should instead be:

```ts
/**
 * Returns an object of key/value pairs of the dynamic params from the current
 * URL that were matched by the route path.
 *
 * @see https://reactrouter.com/hooks/use-params
 */
export function useParams<
  ParamsOrKey extends string | Record<string, string | undefined> = string
>(): Readonly<
  [ParamsOrKey] extends [string] ? Params<ParamsOrKey> : ParamsOrKey
> {
  let { matches } = React.useContext(RouteContext);
  let routeMatch = matches[matches.length - 1];
  return routeMatch ? (routeMatch.params as any) : {};
}
```
...and you should probably update the `Params<T>` definition and the conditional type check here to be more consistent (i.e. so that `useParams<'slug'>()` works to return `{ slug: string }` as well instead of `{ slug?: string }` as it does rn).

**Comment by brophdawg11** [comment]
That PR simply split a large file into sub-files.  The last functional change to `useParams` typings was in https://github.com/remix-run/react-router/pull/8352 if you want to check there for historical reasoning behind this change (which unfortunately pre-dates my involvement with RR 😄)

**Comment by nicholaschiang** [comment]
gotcha. i think @ryanflorence put it well: https://github.com/remix-run/react-router/issues/8200#issuecomment-1023658322 🙂 

that comment makes sense. perhaps we should include it in documentation so y'all don't have to deal with people like me.
