### ISSUE TITLE
LiveReload without Scripts issue in v1.12.0

### ISSUE THREAD

**Issue by bjohn465** [remix-run/remix#5360]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

In Remix v1.12.0, when a page includes the `<LiveReload>` component, but not the `<Scripts>`, the live reload code errors because `window.__remixContext` is not defined.

Demonstration available here: https://stackblitz.com/edit/node-ddnmcr?file=app%2Froutes%2Findex.tsx,app%2Froot.tsx

It looks like this was introduced by commit [45ba8d6](https://github.com/remix-run/remix/commit/45ba8d6#diff-594d4b6ed5bd4abff7e9319566b5505b6a85753e665ff4d2113e888384a98377) and could be resolved by checking that `window.__remixContext` exists before attempting to access `window.__remixContext.dev`.

### Expected Behavior

I expect to be able to use `<LiveReload>` even if `<Scripts>` is not included.

### Actual Behavior

Instead, live reloading does not work without the `<Scripts>` component.

**Comment by jgentes** [comment]
I've run into this issue even with <Scripts> included, tested with 1.9, 1.10 and 1.11 with the same result, although I have to admit I'm not sure what changed to cause this to start happening :-/

```
Uncaught TypeError: Cannot read properties of undefined (reading 'dev')
    at remixLiveReloadConnect ((index):5:53)
```
That line is:
```
let port = (window.__remixContext.dev && window.__remixContext.dev.liveReloadPort) || 8002;
```

**Comment by jgentes** [comment]
I can confirm it's `1.12` that causes the issue - I had `"^1.9.0"` in my package json :(

**Comment by pcattori** [comment]
Fixed by https://github.com/remix-run/remix/pull/5339
