### ISSUE TITLE
Remix 1.12.0 Unable to load app: `Cannot read properties of undefined (reading 'v2_errorBoundary')`

### ISSUE THREAD

**Issue by karissekjw** [remix-run/remix#5368]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Context
- The remix template i've been working off is bluestacks
- I'm currently trying to update remix from `v1.7.6` to `v1.12.0`

### What I did
1. Updated `package.json` to remix `v1.12.0`
```json
  "dependencies": {
    "@remix-run/express": "^1.12.0",
    "@remix-run/node": "^1.12.0",
    "@remix-run/react": "^1.12.0",
    "@remix-run/server-runtime": "^1.12.0",
}
```
2. Ran `npm install`
3. Ran `npm run build`
4. Ran `npm run dev`
5. Go to `http://localhost:3000/` and the below error shows up.
```
TypeError: Cannot read properties of undefined (reading 'v2_errorBoundary')
    at /<file_dir>/build/server.js:38612:39
    at Array.map (<anonymous>)
    at Object.createStaticHandlerDataRoutes (/<file_dir>/build/server.js:38611:85)
    at Object.createRequestHandler2 (/<file_dir>build/server.js:38698:31)
    at createRequestHandler2 (/<file_dir>/build/server.js:39888:32)
    at /<file_dir>/build/server.js:43034:69
    at Layer.handle [as handle_request] (/<file_dir>/build/server.js:17891:9)
    at next (/<file_dir>/build/server.js:18060:17)
    at next (/<file_dir>build/server.js:18056:11)
    at next (/<file_dir>/build/server.js:18056:11)
```
It seems like `function createStaticHandlerDataRoutes(manifest, future, parentId) {}` method in `@remix/server-runtime/dist/routes.js` is receiving `nil` for `future` which caused the issue that I'm experiencing. 

### Expected Behavior

I've tried to create blue stacks project from a clean slate and `createStaticHandlerDataRoutes` seems to receive the following `future` value which allows the app to load correctly:
```javascript
{
  unstable_cssModules: false,
  unstable_cssSideEffectImports: false,
  unstable_dev: false,
  unstable_vanillaExtract: false,
  v2_errorBoundary: false,
  v2_meta: false,
  v2_routeConvention: false
}
```

### Actual Behavior

The error should not occur and the app should be able to run as per normal.

**Comment by machour** [comment]
@karissekjw usually this is caused by one of the remix deps still being on a prior version.
Are you devDependencies also up to date?

If that's the case, try `npm list |grep remix` to see if another non listed @remix-run dependency is outdated

**Comment by machour** [comment]
Also, I would advise, although not mandatory, to do an incremental update for remix, starting with 1.8.0.

This would allow you to go through all the changelogs (starting [here](https://github.com/remix-run/remix/releases#hd-63a91fc9)) and update your application to leverage the new features.

Of course, no need to bump through the bug fixing releases, so basically your upgrade path would be:

- 1.8.2: having read all changelogs from 1.8.0 to 1.8.2 and updated your codebase
- 1.9.0: having read the 1.9.0 changelog and updated your codebase
- 1.10.1: having read all changelogs from 1.10.0 to 1.10.1 and updated your codebase
- 1.11.1: having read all changelogs from 1.11.0 to 1.11.1 and updated your codebase
- and finally 1.12.0

**Comment by karissekjw** [comment]
Hey @machour thanks for the swift response. You're right, seems like I've missed out `@remix-run/dev`. Updated it accordingly and it works now. Thanks, appreciate the advice you've mentioned above 🙏 . 

Closing this issue since it's not a bug.
