### ISSUE TITLE
Sourcemap name are not consistent for remix build

### ISSUE THREAD

**Issue by rgmvisser** [remix-run/remix#5375]
### What version of Remix are you using?

1.7.5

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`npx remix build` 
Check the build folder with the chunk names

`npx remix build --sourcemap`
Check the build folder with **different** chunk names

### Expected Behavior

I expect the names of the chunks be the same for both commands, but just no mapping for the command without the --sourcemap flag.

### Actual Behavior

The names are different. 

This is an issue as I build and run my application without the `--sourcemap` (it's not recommended to have the source maps publically). I then upload my files to Sentry, but the files don't match, so Sentry can't link them to my errors.

**Comment by kiliman** [comment]
The way I do it is build production with `--sourcemap` then upload the map files and then finally delete them. I do this in my GitHub action. This way I have the correct source maps that match the build but will not be available to the client.

**Comment by rgmvisser** [comment]
Thanks for the response @kiliman ! I have looked at that option, but it's not the most secure one IMO. 
If things in the future change in the build process and I forget to update the deletion script, I might upload sensitive information.

**Comment by kiliman** [comment]
I would treat the upload and delete as part of the same process, but feel free to do what is most comfortable for you.

I imagine the chunk hash changes because source maps include the map path as a comment at the end of the file. This most likely affects the hash calculation since the files are no longer identical (even if the compiled output is the same).

**Comment by pcattori** [comment]
This is an inherent limitation of `esbuild` as enabling/disabling sourcemaps can alter how `esbuild` chunks compiled JS. We also cannot tell `esbuild` to _always_ produce sourcemaps and then delete them if you didn't have `--sourcemap` set as it results in perf overheads for other use-cases.

If you require chunked asset filenames to match, I would recommend the [approach outlined by @kiliman earlier](https://github.com/remix-run/remix/issues/5375#issuecomment-1513749161).
