### ISSUE TITLE
[Feature]: Allow running `remix setup` without a specific platform

### ISSUE THREAD

**Issue by edmundhung** [remix-run/remix#538]
### What is the new or updated feature that you are suggesting?

Right now the `remix setup` cli accepts two options: `node` and `cloudflare-workers` and default to `node` if not specified.

It would be nice if we can either:
(1) Have a 3rd option, e.g. `remix setup custom`, or 
(2) Make default skip the platform package (or silently ignore it if `@remix-run/node` is not installed for non-breaking behaviour..?) 

### Why should this feature be included?

Currently, Remix teaches everyone to import things from the `remix` package which relies on the magicExport feature from`remix setup`. However, the CLI does not work unless an official adapter is presented. This makes it non-trivial to experiment with custom adapters as server and clients exports cannot be re-exported from `remix` in this case.

**Comment by chaance** [comment]
Closing this, as we will soon be deprecating `remix setup` altogether in favor of direct imports from sub-modules. See the [release notes in 1.4.0](https://github.com/remix-run/remix/releases/tag/v1.4.0) for details.
