### ISSUE TITLE
Empty chunks

### ISSUE THREAD

**Issue by alexblack** [remix-run/remix#5394]
### What version of Remix are you using?

1.7.5

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

We seem to be getting "empty" chunks in our build like this:

```
import{b as o}from"/build/_shared/chunk-2LOM2E4Y.js";var p=o((r,e)=>{e.exports={}});export{p as a};
```

I think this is happening when we have server only files, who's types are being referenced in our client.  In this case its `api.queries.server.ts`, generated by `pg-typed`, and used in our loaders to pull data from the db, and then the return types show up in the loader types when consumed by the client.

### Expected Behavior

I expected no chunks to be produced when the chunks are empty

### Actual Behavior

Many effectively empty chunks, reducing web performance, causing the browser to make many many requests for tiny unnecessary files

**Comment by machour** [comment]
We already have a proposal to address this in https://github.com/remix-run/remix/discussions/5195
