### ISSUE TITLE
DEFER - Optional return function type interface is incorrect

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#5427]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

View the codesandbox:

https://codesandbox.io/p/sandbox/optimistic-http-sp5602?

The same function is returned twice in the loader, one being optional and the other required.

### Expected Behavior

The type for both should be the same except for an undefined on the optional function:

Required -

`Promise<SerializeObject<UndefinedToOptional<Example>>>`

Optional -

`Promise<SerializeObject<UndefinedToOptional<Example>>> | undefined`

### Actual Behavior

The optional property is lost, and the Promise is embedded inside the Type

Required -

`Promise<SerializeObject<UndefinedToOptional<Example>>>`

Optional -

`SerializeObject<UndefinedToOptional<Promise<Example>>>`

**Comment by TheRealFlyingCoder** [comment]
Bumping this I guess

**Comment by pcattori** [comment]
Fixed by #7104
