### ISSUE TITLE
Unexpected Server Error  Cannot read property 'registered' of null

### ISSUE THREAD

**Issue by jurajkrivda** [remix-run/remix#543]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [X] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [x] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1. Add ChakraProvider to Layout
2. Use any component from Chakra

### Expected Behavior

I expect to correct render the app

### Actual Behavior

I am getting an error: Unexpected Server Error. Cannot read property 'registered' of null

**Comment by alanaudi** [comment]
Hi, @jurajkrivda, I use remix@1.0.6 and it can render, take it a try 😀
But I found that hooks from chakra-ui might not work, do you have same issue ?
When I try `useColorMode` or `useDisclosure`, it failed 🙃

**Comment by chris-hinds** [comment]
Im using remix@1.0.6 and facing the same issue, I loaded the Chakra provider and tried to use the box component and just see the following error

```
TypeError: Cannot read properties of null (reading 'registered')
```

Looks like I'll be going back to nextJS fr this project.

**Comment by chris-hinds** [comment]
Looks like there is extra setup required for CSS-IN-JS libraries, more info here https://github.com/chakra-ui/chakra-ui/issues/5166

**Comment by machour** [comment]
This is now documented in chakra ui (https://github.com/chakra-ui/chakra-ui-docs/pull/412) so I'm closing this one.
