### ISSUE TITLE
Crash when `//` is used as Link's to

### ISSUE THREAD

**Issue by rpominov** [remix-run/remix#5440]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Add this code to a page `<Link to="//">...</Link>`
2. Open the page in the browser

Same problem with some other values of `to` for example `"http://"`, so I think this should be fixed by wrapping `new URL()` into a `try..catch` rather than checking for known fail cases.

### Expected Behavior

Page doesn't crash, instead `<a href="//">...</a>` is rendered

### Actual Behavior

The page crashes with a error `Failed to construct 'URL': Invalid URL`

<img width="1188" alt="Screenshot 2023-02-13 at 15 08 14" src="https://user-images.githubusercontent.com/825702/218442122-3372fdcd-8f32-4683-91e4-36471378ed61.png">

**Comment by rpominov** [comment]
To give more context: 

We at @webstudio-is have a case where the `to` value comes from user input. We would like to just have a link that doesn't work in this case instead of entire app crushing.

**Comment by krall12** [comment]
This sounds related to a bug I had filed a few months ago #4422 

Looks like they have it fixed for an upcoming version.

**Comment by brophdawg11** [comment]
This is fixed by https://github.com/remix-run/react-router/pull/10367 and will be available once Remix 1.16.0 is released.

**Comment by rpominov** [comment]
Great work! Thank you!
