### ISSUE TITLE
Relax version of Prettier in `package.json`

### ISSUE THREAD

**Issue by gustavopch** [remix-run/remix#5444]
### What version of Remix are you using?

v1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I upgraded Prettier in my project to v2.8.4, but I see that v2.7.1 keeps installed in parallel because it's a dependency of `@remix-run/dev`.

### Expected Behavior

Unless there's a good reason not to, Remix should use a `^` version for Prettier:
```diff
-  "prettier": "2.7.1",
+  "prettier": "^2.7.1",
```

### Actual Behavior

It's currently pinned to the specific `2.7.1` version.
https://github.com/remix-run/remix/blob/9adf87c663207e687fbb8e89d2ee4868504fc52c/packages/remix-dev/package.json#L59

**Comment by teetow** [comment]
Pretty sure I just ran into this.

I was trying to format code using the VSCode Extension "Prettier - Code formatter", which insisted that my use of `satisfies` in Typescript was a syntax error. Installing a more recent version of `prettier` as a devDependency fixed it, but that's not exactly ideal.

**Comment by Disorrder** [comment]
@teetow doesn't work for me. I've installed prettier manually, but still face error with `satisfies` operator
<img width="339" alt="image" src="https://github.com/remix-run/remix/assets/2883539/7f812edd-c4bc-49c5-9d64-f476d5766a00">
<img width="495" alt="image" src="https://github.com/remix-run/remix/assets/2883539/855db676-d802-4d00-8cad-5f572f80da41">

**Comment by MichaelDeBoey** [comment]
This will be fixed once #6488 is merged & released

**Comment by MichaelDeBoey** [comment]
Closed by #6488, which will be released in the next release
