### ISSUE TITLE
Error being handled differently for API Routes (client-side navigation vs directly hit)

### ISSUE THREAD

**Issue by raulfdm** [remix-run/remix#5451]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Open this Stackblitz project: https://stackblitz.com/edit/node-e4pggk;
2. wait it to install and run;
3. click in the "Projects" link;
4. see the ErrorBoundary message;
5. click in the "circle arrow" from Stackblitz to refresh that page with error (this emulates accessing that page directly instead client navigation)
6. see an error from the server instead

### Expected Behavior

I'd expect to my ErrorBoundary (or maybe the CatchBoundary) handling the error in both scenarios: accessing directly or via client-side navigation

### Actual Behavior

When I client-side navigate to a page that contains an error and has no page (only a redirect), the ErrorBoundary defined handles the error.

However, when I access that broken page directly, it throws a server error, skipping the ErrorBoundary (or even CatchBoundary)

**Comment by raulfdm** [comment]
I've posted this as a discussion topic 3 weeks (with a more detailed explanation): https://github.com/remix-run/remix/discussions/5235

**Comment by kiliman** [comment]
I posted a comment in your discussion.
