### ISSUE TITLE
Add ESM template

### ISSUE THREAD

**Issue by mcansh** [remix-run/remix#5452]

**Comment by mcansh** [comment]
started working on this https://github.com/remix-run/remix/tree/logan/esm-templates

**Comment by mcansh** [comment]
PR for express and netlify https://github.com/remix-run/remix/pull/5454

Fly, Remix, and Vercel templates all use `remix-serve` which doesn't currently support importing ESM files - i'll adjust remix-serve and then add those if desired

**Comment by jacob-ebey** [comment]
For the new node-esm template, can we require node 18 and use the built in `--watch` flag to remove a dependency on nodemon?

**Comment by mcansh** [comment]
> For the new node-esm template, can we require node 18 and use the built in `--watch` flag to remove a dependency on nodemon?

most definitely

**Comment by MichaelDeBoey** [comment]
@jacob-ebey @mcansh What about updating all templates to require Node 18 to make it consistent?

I would even suggest to make all remix packages to require Node 18 as well as 14 & 16 are EOL for some time now 🤔

**Comment by ctrlplusb** [comment]
So keen to see a remix project using `"type": "module"` in the package.json and with TypeScript configured to resolve and output ESM. I tried, but couldn't get it working.

**Comment by mcansh** [comment]
> So keen to see a remix project using `"type": "module"` in the package.json and with TypeScript configured to resolve and output ESM. I tried, but couldn't get it working.

the "express-esm" template in the linked PR works great for me on macOS, i'll double check windows. I'd love to get that merged if we can fix your issues :)

**Comment by ctrlplusb** [comment]
@mcansh I'll try again. When I tried running `"type": "module"`, I also set my TypeScript config to be `NodeNext` etc. I then tried running the project and it complained that the remix-serve / remix-express packages have CJS `require` statements, which aren't supported by ESM.

**Comment by lensbart** [comment]
> ah yea, you'll need to use a dedicated server for now https://github.com/mcansh/express-esm

Thanks for this suggestion!

Even with that approach, I get the same error as mentioned above for the `yarn dev:remix` command. The `yarn start` script however does work as expected.

> Error: require() of ES Module packages/app/build/index.js from node_modules/@remix-run/serve/dist/index.js not supported.
> Instead change the require of packages/app/build/index.js in node_modules/@remix-run/serve/dist/index.js to a dynamic import() which is available in all CommonJS modules.

**Comment by mcansh** [comment]
> > ah yea, you'll need to use a dedicated server for now https://github.com/mcansh/express-esm
> 
> 
> 
> Thanks for this suggestion!
> 
> 
> 
> Even with that approach, I get the same error as mentioned above for the `yarn dev:remix` command. The `yarn start` script however does work as expected.
> 
> 
> 
> > Error: require() of ES Module packages/app/build/index.js from node_modules/@remix-run/serve/dist/index.js not supported.
> 
> > Instead change the require of packages/app/build/index.js in node_modules/@remix-run/serve/dist/index.js to a dynamic import() which is available in all CommonJS modules.

sounds like you're missing `"type": "module"` in package.json

**Comment by lensbart** [comment]
Thanks for the quick reply! I do have `"type": "module"` in the `package.json` of my Remix app. I think [this](https://github.com/remix-run/remix/blob/150916c3dd0f092454dfa4c16a205692509c99c2/packages/remix-serve/index.ts#L32) `require()` is the culprit, and (if my understanding is correct) `@remix-run/serve` still gets used by the `dev:remix` script in https://github.com/mcansh/express-esm — it’s just the `start` script that uses the ESM-compatible `server.js` file.

**Comment by lensbart** [comment]
Another issue seems to be that `{ assert: { type: 'json' } }` as a second argument to dynamic `import()` seems to get stripped in `build/index.js`, even when `serverModuleFormat: 'esm'` is specified in `remix.config.js`

**Comment by mcansh** [comment]
> Thanks for the quick reply! I do have `"type": "module"` in the `package.json` of my Remix app. I think [this](https://github.com/remix-run/remix/blob/150916c3dd0f092454dfa4c16a205692509c99c2/packages/remix-serve/index.ts#L32) `require()` is the culprit, and (if my understanding is correct) `@remix-run/serve` still gets used by the `dev:remix` script in https://github.com/mcansh/express-esm — it’s just the `start` script that uses the ESM-compatible `server.js` file.

ah, are you using `unstable_dev`? the repo works for me using it

**Comment by mcansh** [comment]
> Another issue seems to be that `{ assert: { type: 'json' } }` as a second argument to dynamic `import()` seems to get stripped in `build/index.js`, even when `serverModuleFormat: 'esm'` is specified in `remix.config.js`.
> 
> This creates an error when running the app as ESM:
> 
> > TypeError: [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "packages/app/public/lang/en.json" needs an import assertion of type "json"

this part is due to our hmr stuff not supporting import assertions yet, i'll talk with @pcattori if we should add `@babel/plugin-syntax-import-assertions` - tried it locally and it's working ay-okay

**Comment by jacob-ebey** [comment]
I've updated the express template to ESM as part https://github.com/remix-run/remix/pull/6229

**Comment by ryanflorence** [comment]
@jacob-ebey correct me if I'm wrong, but everything is ESM in v2 so we can close thise.
