### ISSUE TITLE
create-remix@latest with Vercel set as the deployment target results in internal server errors at runtime

### ISSUE THREAD

**Issue by simonsteer** [remix-run/remix#5468]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Initialize a project using create-remix@latest and set vercel as the deployment target, push to github
2. Import github repo to Vercel & deploy

### Expected Behavior

Empty remix/vercel project template deploys successfully to Vercel and does not 500 when serving routes

### Actual Behavior

When deploying a remix project with Vercel set as the deployment target, the project deploys successfully, but does not succesfully serve routes at runtime due to internal server errors.

This is what's served instead of the index route:
![Screen Shot 2023-02-15 at 12 12 50 PM](https://user-images.githubusercontent.com/33757365/219102871-1b045eaa-6dac-4a02-ac42-d9b8579ca728.png)

This is what Vercel's function logs look like:
```
[GET] / 11:56:39:65

2023-02-15T16:56:40.277Z	c5ec4fa1-d893-48e3-ba0c-23443feee454	ERROR	TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at groupRoutesByParentId (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:19:10)
    at Object.createRoutes (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:31:67)
    at Object.createRequestHandler (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:27:25)
    at createRequestHandler (/var/task/node_modules/@remix-run/vercel/dist/server.js:34:28)
    at Object.<anonymous> (/var/task/api/__vc_handler.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
RequestId: c5ec4fa1-d893-48e3-ba0c-23443feee454 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

And this is the repository I imported into Vercel (generated with create-remix@latest):
https://github.com/simonsteer/test

Apologies if this is a duplicate or has already been raised!

**Comment by chuckstock** [comment]
Getting this same issue. Can't deploy my app to Vercel at the moment, becuase the function is crashing. Getting this error:
```
ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: Headers is not defined","reason":{"errorType":"ReferenceError","errorMessage":"Headers is not defined","stack":["ReferenceError: Headers is not defined","    at Object.getDocumentHeadersRR (/var/task/node_modules/@remix-run/server-runtime/dist/headers.js:38:10)","    at handleDocumentRequestRR (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:187:27)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at requestHandler (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:67:18)","    at Server.default (file:///var/task/apps/binding/build/server-node.mjs:68:20)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: Headers is not defined","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:539:35)","    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by lytovka** [comment]
@simonsteer @chuckstock – I experienced the same issue yesterday (using Remix v1.13.0). I've just redeployed my app to Vercel today, and it seems to be working now as expected.

**Comment by bhuynhdev** [comment]
Same issue here. It seems like the Vercel build output does not have the `api` directory?
![image](https://user-images.githubusercontent.com/55563202/221292500-68418d84-5a31-45b0-ad20-eaa17313ee82.png)

**Comment by chuckstock** [comment]
@lytovka ok i'll give that a try today! Thanks for the update.

**Comment by simonsteer** [comment]
> @simonsteer @chuckstock – I experienced the same issue yesterday (using Remix v1.13.0). I've just redeployed my app to Vercel today, and it seems to be working now as expected. You can try redeploying for your apps to see if serverless function crashing is fixed.

Just redeployed to Vercel as well and all seems fine. Closing this since it appears to have been an issue unrelated to Remix
