### ISSUE TITLE
Differences between tailwindcss in v1.13 vs v1.12

### ISSUE THREAD

**Issue by inssein** [remix-run/remix#5475]
### What version of Remix are you using?

1.13

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Build a new remix project, install tailwind and set `unstable_tailwind` to `true`.

### Expected Behavior

Vendor prefixes should be automatically added.

### Actual Behavior

Vendor prefixes are not applied.

Chances are this is totally expected behaviour, and easily fixed by setting `unstable_postcss` to `true` and adding the `autoprefixer` dependency + configuration, but just raising this because it was "free" in the previous installation process. I think tailwind must have been adding vendor prefixes by default.

**Comment by inssein** [comment]
Looks like this will be potentially resolved https://github.com/remix-run/remix/discussions/5017.

**Comment by machour** [comment]
Can confirm this. For people hitting this, as outlined by @inssein, the solution is to : 

- add autoprefixer to your dev dependencies
- add this post.config.js file : 
```js
module.exports = {
  plugins: [require("autoprefixer")],
};
```
- enable `unstable_postcss` in the `future` section of `remix.config.js`

**Comment by inssein** [comment]
Looks like this will get addressed here: https://github.com/remix-run/remix/issues/5315

**Comment by markdalgleish** [comment]
This flow is a bit more seamless in Remix v2 since both Tailwind and PostCSS are enabled by default. I've opened a PR to the v2 docs that better address the lack of vendor prefixing when using Tailwind in isolation: #7091.
