### ISSUE TITLE
`@apollo/client` always suggested to be added to `serverDependenciesToBundle` config (even if already added)

### ISSUE THREAD

**Issue by armandabric** [remix-run/remix#5483]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Here a reproduction repository: 

https://codesandbox.io/p/sandbox/relaxed-sea-qmnf15?selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A9%7D%5D&file=%2Fremix.config.js

### Expected Behavior

Do not suggest `@apollo/client` package as an ESM only package as [it seems to export a CommonJS version](https://github.com/apollographql/apollo-client/blob/dc17d11b05706be95f7d3cad3ad6311476565e87/package.json#L16-L18).

### Actual Behavior

With or without `@apollo/client` in the `serverDependenciesToBundle` config Remix is printing message in the console that lead to nowhere.

#### Without `@apollo/client` in the `serverDependenciesToBundle`

When you start the dev server (or the make a build):

```
$ pnpm build

> @my-package@ build /.../my-package
> remix build

Building Remix app in production mode...
@apollo/client is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
Built in 598ms
```

Even if `@apollo/client` seems to be CJS compatible, Remix propose to add to the `serverDependenciesToBundle` config.

#### With `@apollo/client` in the `serverDependenciesToBundle`

When you start the dev server (or the make a build):

```
$ pnpm build

> @my-package@ build /.../my-package
> remix build

Building Remix app in production mode...
@apollo/client is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
ts-invariant is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
zen-observable-ts is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
Built in 677ms
```

The `@apollo/client` package is suggested again (but should not).

**Comment by marwan38** [comment]
I have the same thing, but, now that I think about it.. it might be the inner packages.. like `@apollo/client/ssr`

**Comment by epitaphmike** [comment]
I had to add all the internal dependencies individually, run `build` then I was able to run `dev`. Had this issue with the `@wagmi` library after the update. I assume these is a way to wildcard the dependencies if you wanted to load everything.

**Comment by armandabric** [comment]
Still a thing

**Comment by ariofrio** [comment]
This seems to be [occuring for `mdast-util-to-markdown`, too](https://github.com/remix-run/remix/issues/109#issuecomment-1583083330). In this case, however, the dev server actually fails to run with the same error as if `mdast-util-to-markdown` hadn't been added to serverDependenciesToBundle in the first place.

**Comment by lensbart** [comment]
Same problem here.

**Comment by lensbart** [comment]
My workaround is to include `/@apollo\/client*/` instead of `'@apollo/client'`. Then I also had to include `'@wry/trie'`, `/ts-invariant*/` and `'zen-observable-ts'`, because these are transitive dependencies of the former (using `/ts-invariant*/` instead of `'ts-invariant'` due to the same problem).

**Comment by pcattori** [comment]
#6916 removed false-positive ESM warnings seen here
