### ISSUE TITLE
New dev server reloads page before it's ready when there are no changes

### ISSUE THREAD

**Issue by dmarkow** [remix-run/remix#5492]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Run any remix app set up to use the new dev server (I tested it on https://github.com/remix-run/examples/tree/main/_official-tutorial)
- `npm remix dev`
- Save/touch any file *without making changes*
- Browser reloads but the result is randomly one of:
  - Works perfectly
  - Whole page errors out with "This site can’t be reached"
  - Page refreshes, but certain assets, e.g. JS and CSS chunks, don't load. Console shows a combination of `ERR_CONNECTION_REFUSED`, `ERR_CONNECTION_RESET`, and `ERR_EMPTY_RESPONSE`

When there are no changes, the build hash doesn't change.  So`waitForAppServer` is called, fetches the server's current manifest, and immediately returns since the manifest matches. The problem is that `waitForAppServer` often runs before the actual file watcher restarts the server process, with just enough time for the dev server to grab the old manifest. This is ok when there actually are changes -- the manifest won't match, so it'll loop until they do, letting the server restart -- but causes this race condition when there are no changes.

### Expected Behavior

Page reloads should work the same whether there were changes or not.

### Actual Behavior

Random network errors. Here is a persisted log across 3-4 live reloads on the tutorial app. In every single reload, at least one file had trouble loading due to the server not being ready yet.

<img width="1123" alt="CleanShot 2023-02-16 at 18 15 27@2x" src="https://user-images.githubusercontent.com/8009/219517034-f720f8fc-8394-4807-bffd-371d731d0404.png">

**Comment by dmarkow** [comment]
Definitely still an issue if you do two quick saves in a row, had it happen on 1.15.0 yesterday.

**Comment by pcattori** [comment]
Obsoleted by #6133
