### ISSUE TITLE
[Bug]: Browser Bundles include @remix/server-runtime

### ISSUE THREAD

**Issue by milamer** [remix-run/remix#550]
### Which Remix packages are impacted?

- `@remix-run/dev`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1. install Remix
2. create resource route
3. use redirect or json
4. lookup browser build folder for `import_server_runtime`

I could not get tests to run on wsl2 or windows so here is just a patch to fix this:
```patch
diff --git a/node_modules/@remix-run/dev/compiler.js b/node_modules/@remix-run/dev/compiler.js
index be852a2..858d6b4 100644
--- a/node_modules/@remix-run/dev/compiler.js
+++ b/node_modules/@remix-run/dev/compiler.js
@@ -461,7 +461,17 @@ function browserRouteModulesPlugin(config, suffixMatcher) {
           };
         }
 
-        let spec = exports.length > 0 ? `{ ${exports.join(", ")} }` : "*";
+        if(exports.length === 0) {
+          return {
+          // Use an empty CommonJS module here instead of ESM to avoid "No
+          // matching export" errors in esbuild for stuff that is imported
+          // from this file.
+          contents: "module.exports = {};",
+          loader: "js"
+          }
+        }
+
+        let spec = `{ ${exports.join(", ")} }`
         let contents = `export ${spec} from ${JSON.stringify(file)};`;
         return {
           contents,

```

### Expected Behavior

Resource routes do not get bundled to the browser build.

### Actual Behavior

Resource routes are getting bundled to the browser build.

**Comment by Guria** [comment]
@milamer Thanks, this patch heled me to avoid a big Uncaught exception with my Resource route

**Comment by Guria** [comment]
Is there any reason it isn't yet fixed even in experimental releases?

**Comment by chaance** [comment]
Are still able to reproduce this in 1.1.0?

**Comment by anonrig** [comment]
I can reproduce the same error on a newly created Cloudflare pages setup on Remix.

```
Compiling worker to "/var/folders/w_/dmc3444j7q7gn2yzx7qystsr0000gn/T/functionsWorker.js"
✘ [ERROR] Could not resolve "@remix-run/server-runtime"

    build/index.js:23:159:
      23 │ import { createCookie, createCookieSessionStorage, createMemorySessionStorage, createSession, createSessionStorage, isCookie, isSession, json, redirect } from "@remix-run/server-runtime";
         ╵                                                                                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@remix-run/server-runtime" as external to exclude it from the bundle, which
  will remove this error.

/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1493
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
build/index.js:23:159: ERROR: Could not resolve "@remix-run/server-runtime"
    at failureErrorWithLog (/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1069:65)
    at buildResponseToResult (/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:1258:14
    at /Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/yagiz/.npm/_npx/8c55f4bc76fffd7b/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: {
        column: 159,
        file: 'build/index.js',
        length: 27,
        line: 23,
        lineText: 'import { createCookie, createCookieSessionStorage, createMemorySessionStorage, createSession, createSessionStorage, isCookie, isSession, json, redirect } from "@remix-run/server-runtime";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@remix-run/server-runtime" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@remix-run/server-runtime"'
    }
  ],
  warnings: []
}

Node.js v17.2.0
Build failed with exit code 1
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "dev:wrangler" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mcfadyeni** [comment]
Also occuring for me, seems to happen when I import any of the helper functions (`json`, `redirect`), even inside a regular route (i.e. even with a component).

**Comment by ycjcl868** [comment]
same issue in monorepo.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/13595509/152779236-e54306fa-3a89-42f5-b924-264c0740025d.png">

**Comment by Guria** [comment]
Any chance we can have it fixed? I don't believe impact of the issue is too low.

**Comment by kiliman** [comment]
This issue was based on a very old version. Are you having the issue on the latest 1.3.3?

If so, can you provide more details.

**Comment by kiliman** [comment]
Odd. I did a clean install and build ran just fine. Did you confirm that you have the proper packages installed in node_modules? Check `node_modules/@remix-run`
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/47168/160872306-26ff0139-2c91-4547-bdb7-3dc507f7abd4.png">

**Comment by goran-paunovic** [comment]
Same error here.
Windows 10, Node 16, Remix 1.3.3.
I have chosen express server when creating new app.

![image](https://user-images.githubusercontent.com/8568410/160888671-4da16687-1148-4d03-8ffe-9aab52944982.png)

**Comment by kiliman** [comment]
Can you show the directory listing for `node_modules/@remix-run`?

**Comment by nopitown** [comment]
Getting the same error following the instruction in the documentation. The package `@remix-run/server-runtime` is not present

**Comment by goran-paunovic** [comment]
> Getting the same error following the instruction in the documentation. The package `@remix-run/server-runtime` is not present

Same here.
When I installed `@remix-run/server-runtime` the error is gone.

**Comment by sfonua10** [comment]
I'm getting: ```✘ [ERROR] Could not resolve "remix"

    app/routes/posts/index.tsx:2:42:
      2 │ import { Link, json, useLoaderData } from "remix";```. This is with the indie stack

**Comment by johanwin** [comment]
> I'm getting: ✘ [ERROR] Could not resolve "remix"
> 
> ```
>       2 │ import { Link, json, useLoaderData } from "remix";.```
> 
>  This is with the indie stack
> ```

Regarding the indie stack, if you follow their example it seems it has been updated from `import { Link, json, useLoaderData } from "remix"` to this

'import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";'

Which now works for me

**Comment by chaance** [comment]
For those still having issues here, it's likely related to using imports from the `"remix"` module without running the `remix setup` script. As @johanwin noticed, importing directly from the sub-module should fix this, and all of our docs/examples/templates now show this usage for reference.

Take a look at our [release notes for 1.4.0](https://github.com/remix-run/remix/releases/tag/v1.4.0) for more details, as well as guidance on a script to help you update your import statements.
