### ISSUE TITLE
Unable to access env variables in Remix, even in a server file

### ISSUE THREAD

**Issue by NotoriousGOR** [remix-run/remix#5503]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I was using Shopify's version of Remix and ran into an issue where I tried to access an API key to be used in a newsletter signup form. However, I cannot access my env variables due to the error `process is not defined.`

app/env/env.server.ts:

    import {ZodFormattedError} from 'zod';
    
    const serverSchema = z.object({
      KLAVIYO_API_KEY: z.string(),
      KLAVIYO_GLOBAL_LIST_ID: z.string(),
      KLAVIYO_API_VERSION: z.string(),
    })
    
    const _serverEnv = serverSchema.safeParse(process.env);
    
    const formatErrors = (errors: ZodFormattedError<Map<string, string>, string>) =>
      Object.entries(errors)
        .map(([name, value]) => {
          if (value && '_errors' in value)
            return `${name}: ${value._errors.join(', ')}\n`;
        })
        .filter(Boolean);
    
    if (_serverEnv.success === false) {
      // eslint-disable-next-line no-console
      console.error(
        '❌ Invalid environment variables:\n',
        ...formatErrors(_serverEnv.error.format()),
      );
    
      throw new Error('Invalid environment variables');
    }
    
    export const env = {..._serverEnv.data};

routes/newsletter/subscribe.tsx:

    import {ActionArgs, json} from '@shopify/remix-oxygen';
    import { env } from '../../env/env.server';
    
    export async function action({request}: ActionArgs) {
      const email = (await request.formData()).get('email')?.toString() ?? '';
      try {
        const res = await subscribeToKlaviyoList(email);
    
        return res.json();
      } catch (error) {
        return json({error: error.message, ok: false});
      }
    }
    
    
    
    export async function subscribeToKlaviyoList(
      email: string,
      source = 'Home Page Footer',
    ) {
      const API_KEY = env.KLAVIYO_API_VERSION;
      const API_VERSION = env.KLAVIYO_API_VERSION;
      const LIST_ID = env.KLAVIYO_GLOBAL_LIST_ID;
    
      return await fetch(
        'https://a.klaviyo.com/api/profile-subscription-bulk-create-jobs/',
        {
          method: 'POST',
          headers: {
            accept: 'application/json',
            revision: API_VERSION ?? '2023-01-24',
            'content-type': 'application/json',
            Authorization: `Klaviyo-API-Key ${API_KEY}`,
          },
          body: JSON.stringify({
            data: {
              type: 'profile-subscription-bulk-create-job',
              attributes: {
                list_id: LIST_ID,
                custom_source: source,
                subscriptions: [
                  {
                    channels: {email: ['MARKETING']},
                    email,
                  },
                ],
              },
            },
          }),
        },
      );
    }

I've followed along with [this][1] example from Remix and [this][2] GitHub repo, but in both instances, they either aren't using env variables or the API key is hard coded. I would greatly appreciate any help.

     

  [1]: https://remix.run/docs/en/v1/hooks/use-fetcher
  [2]: https://github.com/remix-run/remix/blob/9b46b9025f534fc8e7bf4c4839ab46092505706e/examples/newsletter-signup/app/routes/newsletter.tsx

### Expected Behavior

Able to use env variables

### Actual Behavior

Error saying `ReferenceError: process is not defined`

**Comment by kiliman** [comment]
As mentioned on the Hydrogen repo {https://github.com/Shopify/hydrogen/issues/542], this is not a Remix error but how Hydrogen exposes the environment variables. `process.env` only works for Node-based environments.

You can access environment variables via the `context` object in your loaders/actions.

```ts
export async function loader({ request, context } : LoaderArgs) {
  const API_KEY = context.env.API_KEY
  ...
}
```
