### ISSUE TITLE
`remix watch` builds even when it can't resolve CSS imports

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5506]
### What version of Remix are you using?

1.8+

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

try to import a css file that doesn't exist:

```js
import href from "./does/not/exist.css";
```

Then run `remix watch`

```
$ remix watch
Watching Remix app in development mode...
💿 Built in 159ms
```

But it's all a lie! Remix build knows the truth!

```
$ remix build
Building Remix app in production mode...

✘ [ERROR] Could not resolve "./does/not/exist.css"

    app/root.tsx:8:26:
      8 │ import appStylesHref from "./does/not/exist.css";
        ╵                           ~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

`remix watch` should fail exactly like `remix build`.

This is more concerning because it means the code paths are taking a significant branch somewhere. Might want to dig deeper and see if that branch really needs to be happening. `remix watch` should be as identical to `remix build` as possible.

There's also a good chance we just goofed up surfacing errors in watch mode at the top somewhere.

### Actual Behavior

It reports that it built just fine.

This started happening in 1.8 and has persisted through 1.13 (I tried them all. Funny story, I went back one version at a time from 1.13, to 1.12, to 1.11, to 1.10, to 1.9, and then decided to do a binary search instead and went to 1.3, 1.6, 1.7 until 1.8. In an attempt to optimize my search I did nearly the worst possible search I could have done 🤣)

**Comment by pcattori** [comment]
Potentially fixed by https://github.com/remix-run/remix/pull/5441

**Comment by ryanflorence** [comment]
yep, tried `@nightly` and it's fine. that was easy.
