### ISSUE TITLE
`v2_routeConvention` does not work with the new `unstable_dev` server after HMR

### ISSUE THREAD

**Issue by Girish21** [remix-run/remix#5517]
### What version of Remix are you using?

0.0.0-experimental-0ec995c53

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have created a reproduction repo [Girish21/remix-hmr-v2-routes-bug](https://github.com/Girish21/remix-hmr-v2-routes-bug), which has the new `unstable_dev` (with HMR) and `v2_routeConvention` flags enabled.

Clone the repo, install the dependencies and run `npm run dev`. It should spin up the express server running on port `3000`.

### Expected Behavior

`routes/index` route should be rendered inside the `Outlet` at `root.tsx`, and should see the components rendered as part `routes/index`. And the new dev server (after HMR) should support `v2_routeConvention`.

### Actual Behavior

Components/JSX present in `root.tsx` renders as expected, but any other route defined using `v2_routeConvention` does not seem to be working and getting `404` logs in the server
```sh
No routes matched location "/build/_assets/tailwind-5XLWGL7Y.css" 
No routes matched location "/build/manifest-F7E4A618.js" 
No routes matched location "/build/entry.client-RPL7VCBZ.js" 
No routes matched location "/build/_shared/chunk-REDQPUWV.js" 
No routes matched location "/build/root-6EIC5E5D.js" 
GET /build/_assets/tailwind-5XLWGL7Y.css 404 - - 3.231 ms
GET /build/manifest-F7E4A618.js 404 - - 2.002 ms
GET /build/entry.client-RPL7VCBZ.js 404 - - 2.532 ms
GET /build/_shared/chunk-REDQPUWV.js 404 - - 2.999 ms
GET /build/root-6EIC5E5D.js 404 - - 3.246 ms
No routes matched location "/build/manifest-F7E4A618.js" 
```

**Comment by bluefire2121** [comment]
Second this. How do we get v2_routeConvention to work as shown in the docs?

**Comment by bluefire2121** [comment]
The issue seems related to windows file paths. Need universal monikers for file paths as various operation systems escape forward slash and backslash in different ways.

**Comment by iGoodie** [comment]
I can confirm that. When `future.v2_routeConvention` is set to `true`, Remix fails to discover routes correctly

**Comment by bluefire2121** [comment]
This has been fixed in the latest version, but the _landing._index folder structure as shown in the docs doesn't work. There's a separate issued filed for that bug.
