### ISSUE TITLE
instanceof Request on cloned request return false

### ISSUE THREAD

**Issue by tomer-rmor** [remix-run/remix#5520]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
export async function action({ request }: ActionArgs) {
  const cloned = request.clone()
  if (cloned instanceof Request) { // return false
    console.log("")
  }
}
```

### Expected Behavior

should return true

### Actual Behavior

return false

**Comment by jacob-ebey** [comment]
Thank you @tomer-rmor. I have merged this as part of https://github.com/remix-run/remix/pull/6512 with updated tests.
