### ISSUE TITLE
Remix esbuild browser build external builtinModules of node.js causes import AWS-sdk error

### ISSUE THREAD

**Issue by jackyleefu** [remix-run/remix#5521]
### What version of Remix are you using?

v1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

import AWS from "aws-sdk";

aws-sdk dependency [buffer](https://github.com/feross/buffer) and other package for the browser from nodejs buildinModule, Remix esbuild browser make it external causes bundle for browser error

### Expected Behavior

no error in browser

### Actual Behavior

In Browser
Uncaught Error: Dynamic require of "buffer/" is not supported

**Comment by markdalgleish** [comment]
I've merged a fix for this that will be going out in our v2 release.
