### ISSUE TITLE
`remix` CLI reports false positives of missing "node_modules" when invoked from a different directory

### ISSUE THREAD

**Issue by TooTallNate** [remix-run/remix#5535]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `cd` to your Remix project
    ```
    cd ~/my-test
    ```
3. Invoke Remix CLI located in a different project, or compiled from source located in this repository
    ```
    $ node ~/Code/remix-run/remix/packages/remix-dev/dist/cli.js build
    ```
4. See false positive `require.resolve()` warnings for missing modules, even though those modules are indeed installed
    ```
    Building Remix app in production mode...
    The path "@remix-run/react" is imported in app/entry.server.tsx but "@remix-run/react" was not found in your node_modules. Did you forget to install it?
    The path "react-dom/server" is imported in app/entry.server.tsx but "react-dom/server" was not found in your node_modules. Did you forget to install it?</span>
    Built in 190ms
    ```

### Expected Behavior

No `require.resolve()` warnings are printed, because the relevant packages do indeed exist within the project's `node_modules` directory.

### Actual Behavior

False positive warning messages are printed, such as:

```
The path "react-dom/server" is imported in app/entry.server.tsx but "react-dom/server" was not found in your node_modules. Did you forget to install it?
```

**Comment by MichaelDeBoey** [comment]
Fixed by #6181
