### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html".

### ISSUE THREAD

**Issue by quuu** [remix-run/remix#5542]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Initialize a new create-remix app using the Netlify deployment template

Deploy to netlify 

Visit the deployed site and you'll see a blank screen with this console error

<img width="630" alt="CleanShot 2023-02-22 at 17 32 10@2x" src="https://user-images.githubusercontent.com/32676955/220802255-19cbe9e0-09f3-48df-bbad-dc2ee5f9d7fc.png">

### Expected Behavior

expected to load

### Actual Behavior

<img width="630" alt="CleanShot 2023-02-22 at 17 32 10@2x" src="https://user-images.githubusercontent.com/32676955/220802255-19cbe9e0-09f3-48df-bbad-dc2ee5f9d7fc.png">

and a blank screen

**Comment by juniorforlife** [comment]
I'm running into the same issue with version 1.16.1. It does not happen every time but a considerable amount of times. Has anyone found a fix for this?

**Comment by mjsol12** [comment]
bump the same problem just today version 1.16.0, any update how the fix ?

**Comment by quuu** [comment]
> I'm running into the same issue with version 1.16.1. It does not happen every time but a considerable amount of times. @quuu have you found the fix for this?



> Reference in new


@juniorforlife  @mjsol12 

Hi, since making this thread, our company actually migrated off of Remix :(

But I believe I resolved this towards the end of our time on Remix by setting the netlify and remix server caching settings to "no cache" --

My suspicion is that on the Netlify side of things, requests from the same network told Netlify that the recent deploy is valid -- so when we did a new deploy and people were still on the old connection, Netlify didn't think it was time to invalidate the previously cached files and thus tried to send old files to a new visit of the site

I don't have any proof thats whats happening -- but anecdotally when testing by changing networks/ removing the cache settings, we didn't hit this issue for a while.

**Comment by juniorforlife** [comment]
@quuu sad to hear your company migrated off of Remix :( We're thinking of doing the same due to the lack of middlewares and recent problems with development server

**Comment by quuu** [comment]
@juniorforlife 

Yea, was hard to do but due to the issues we had while devving/ lack of community support -- it was a little too unstable for us

But after Remix we went to statically serving a Vite app, and it's been a huge improvement over the before Remix CRA and the Remix app

**Comment by aleksandarbasara** [comment]
We have the same issue on Netlify. I guess there is some issue with Netlify and the purge of the cache.

**Comment by ryanflorence** [comment]
Sounds like a caching issue with netlify, if you find out anything new, please let us know.
