### ISSUE TITLE
Space (or any non-encoded character) in route segment causes a hydration mismatch in Form action

### ISSUE THREAD

**Issue by frontsideair** [remix-run/remix#5599]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Use space in a route segment e.g. `/post/hello world`
2. Use a `Form` in that route

### Expected Behavior

The encoding or url should match on the client and the server and there should be no warning.

### Actual Behavior

I get a hydration warning `Warning: Prop `action` did not match. Server: "/post/hello world" Client: "/hello%20world"`

**Comment by brophdawg11** [comment]
This is resolved by https://github.com/remix-run/react-router/pull/10769 and should be available in Remix v2
