### ISSUE TITLE
Deferred data loads aren't cancelled when clicking a link while the current promise is pending

### ISSUE THREAD

**Issue by tom-sherman** [remix-run/remix#5609]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```tsx
import { defer } from "@remix-run/node";
import { Await, Link, useLoaderData } from "@remix-run/react";
import { Suspense } from "react";

const wait = (ms: number) => new Promise((res) => setTimeout(res, ms));

export function loader() {
  return defer({
    done: Math.random(),
    deferredRandom: wait(2000).then(() => Math.random()),
  });
}

export default function Index() {
  const { deferredRandom, done } = useLoaderData<typeof loader>();
  return (
    <>
      <Link to={`/${done}`}>Reload</Link>
      <div>Done: {done}</div>
      <Suspense fallback={<div>Loading...</div>}>
        <Await resolve={deferredRandom}>
          {(random) => <div>Random: {random}</div>}
        </Await>
      </Suspense>
    </>
  );
}
```

Repo here: https://github.com/tom-sherman/remix-deferred-cancellation-bug

1. Put the above code in the`$id` route
2. Open `/foo`
3. Open the network tab in the dev tools
4. Click the "refresh" link multiple times in quick succession

Additionally, you can also use back/forward on step 4. Previous fetches aren't cancelled.

### Expected Behavior

In-flight requests should be cancelled when a new request is made.

### Actual Behavior

In-flight requests are not cancelled.

**Comment by tom-sherman** [comment]
Ok this is now working for me and I have no idea why...

**Comment by tom-sherman** [comment]
Closing this as I think I just had some momentary issue.

**Comment by tom-sherman** [comment]
Reproduced it with some slightly different code.

**Comment by jacob-ebey** [comment]
In the latest version requests are aborted, but for some reason once a response begins streaming content back, is doesn't show up as "aborted" in the network tab, instead it's just ended and shows success even through the body didn't fully come over the network. Closing this issue, but if the problem persists or comes up in the future, please re-open or file a new issue.
