### ISSUE TITLE
`unstable_dev` never runs the app when used with the Remix App Server

### ISSUE THREAD

**Issue by janhesters** [remix-run/remix#5626]
### What version of Remix are you using?

1.14

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a new Remix project `npx create-remix@latest` and choose Remix App Server.

Then add the following Remix config:

```js
/* eslint-disable unicorn/prefer-module */

/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ['**/*.test.{ts,tsx}'],
  future: {
    v2_routeConvention: true,
    v2_meta: true,
    v2_errorBoundary: true,
    unstable_tailwind: true,
    unstable_dev: true,
  },
};
```

**Note:** `unstable_dev` alone breaks the dev script arleady.

### Expected Behavior

Remix server starts with HMR enabled.

### Actual Behavior

Remix gets stuck here and never starts.

```bash
$ npm run dev

> unstable-dev-test@1.0.0 dev
> remix dev

Loading environment variables from .env
💿 Built in 1.1s
```

**Comment by chuckstock** [comment]
Yeah I'm just getting and "Upgrade Required" message.

**Comment by duytbp** [comment]
Guys, it needs more than just enabling `unstable_dev` in remix.config to work.

Please refer to [v1.12.0 release notes](https://github.com/remix-run/remix/releases/tag/remix%401.12.0)

**Comment by janhesters** [comment]
@duytbp which are missing? I've seen others being able to activate [HMR with just `unstable_dev`](https://www.youtube.com/live/pp_WRUWUVjY?feature=share&t=367) 🤔

**Comment by duongdev** [comment]
@janhesters You and me both have `v2_routeConvention: true`, Kent doesn’t. Didn’t try but I think because of it.

**Comment by duytbp** [comment]
Maybe you should try with Express server instead of Remix App Server, it probably still doesn't work as mentioned in release notes.

Also in LiveReload there is `port` prop which you might want to update to match your dev port (by default it try to pick an unused port, which usually 3001).

In short:
1. Try express server
2. If still does not work, try set static ports in remix.config.js
   ```
    unstable_dev: {
      port: 3010,
      appServerPort: 3000,
    },
    ```
   and match it with LiveReload's port prop

**Comment by janhesters** [comment]
@duongdev I tried with only `unstable_dev` and it was broken.

**Comment by janhesters** [comment]
@duytbp Thanks for the guidance!

Tried that all, but that neither worked unfortunately.

**Comment by scottcorgan** [comment]
I can confirm that `unstable_dev` is not working for me either. 

I'm running an Arc build target, but using remix server locally.

**Comment by janhesters** [comment]
@duytbp Did a quick check and confirm. It seems only broken with the Remix App Server. I changed the topic of this issue.

**Comment by andrecasal** [comment]
Yep, this HMR/HDR doesn't seem to be working with Remix App Server even with:
```
unstable_dev: {
	port: 3010,
	appServerPort: 3000,
},
```

Keeping a lookout on this issue 📡

**Comment by tehfailsafe** [comment]
> We fixed the bug in Remix App Server in v1.14, so to my knowledge its possible to get this working now if you follow the instructions on [v1.14 release notes](https://github.com/remix-run/remix/releases/tag/remix%401.14.0).

I just tested this out on a fresh project @latest, and by default everything looks like its working in the terminal, but in the browser it just says "Upgrade required".  I read somewhere else that could mean the dev server and app server are out of sync and the client is responding too fast. For giggles I set `rebuildPollIntervalMs` to 1000 but it didn't change the outcome.

**Comment by fayez-nazzal** [comment]
I tried creating a new app using `npx create-remix@latest`, which is at `v1.15.0`, using the `unstable_dev` flag for the Remix App Server keeps the server hanging at the message:
```
💿 Built in ..s
 ```
And the app never loads on the browser.

With the Express server option, it works fine 👍

**Comment by janhesters** [comment]
@pcattori can confirm what @fayez-nazzal says, this is still broken 🙏

**Comment by pcattori** [comment]
@fayez-nazzal and @janhesters which template are you using?

Most templates are not equipped out-of-the-box for `unstable_dev`, so you'd need to edit `package.json` scripts to run the dev server in parallel with your app server, e.g. via `npm-run-all`

**Comment by janhesters** [comment]
@pcattori the bare minimum template 😊

**Comment by pcattori** [comment]
Obsoleted by #6133 

You should now be able to set `unstable_dev` future flag and Remix App Server template should work out-of-the-box.

**Comment by janhesters** [comment]
@pcattori Yes! Thanks a ton 🙏

**Comment by fayez-nazzal** [comment]
@pcattori You are awesome, thanks!
