### ISSUE TITLE
1.14.0: Build performance regression in browserRouteModulesPlugin

### ISSUE THREAD

**Issue by dmarkow** [remix-run/remix#5629]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Remix 1.14.0 introduced more complexity to browserRouteModulesPlugin. This has caused up to a 5x increase in build times, which is very noticeable when working in a large app. These times are roughly the same for an initial build and rebuild.

- 1.13.0: 1.9s
- 1.14.0 / old dev server: 4.2s
- 1.14.0 / new dev server: 8.7s

Throwing an [esbuild profile wrapper](https://github.com/evanw/esbuild/issues/1778#issuecomment-977522702) in, it's showing most the time is spent in this plugin. Since esbuild uses every core as much as possible, the actual 41 seconds in the first example is far less in real time. In the second example it's a tiny bit more, but something in there is causing the 2x speed increase. Adding in the new dev server (with HMR), it jumps another 2x on top of that (I'm unsure if that additional increase is in browserRouteModulesPlugin, hmrPlugin, or a combo of both).

Detailed output of each build below. I'll try to dig into a possible PR to improve this, but wanted to raise the issue in case anyone is seeing problems.

Remix 1.13.0 (same results with unstable_dev on or off):

```
± yarn remix dev
yarn run v1.22.19
$ /Users/dylan/dev/pfcs/node_modules/.bin/remix dev
[plugin: deprecated-remix-package]
  total: 649ms
   ├ start: 1ms
   └ onResolve: 648ms

[plugin: css-file]
  total: 122ms
   ├ start: 1ms
   └ onLoad: 121ms

[plugin: url-imports]
  total: 1ms
   └ start: 1ms

[plugin: remix-mdx]
  total: 79ms
   └ start: 79ms

[plugin: browser-route-modules]
  total: 41566ms
   ├ start: 1ms
   ├ onResolve: 14ms
   └ onLoad: 41551ms

[plugin: empty-modules]
  total: 8ms
   ├ start: 0ms
   ├ onResolve: 6ms
   └ onLoad: 2ms

[plugin: node-modules-polyfills]
  total: 224ms
   ├ start: 0ms
   ├ onResolve: 197ms
   └ onLoad: 27ms

💿 Built in 1.9s
```

Remix 1.14.0, unstable_dev turned off:

```
± yarn remix dev
yarn run v1.22.19
$ /Users/dylan/dev/pfcs/node_modules/.bin/remix dev
[plugin: deprecated-remix-package]
  total: 804ms
   ├ start: 1ms
   └ onResolve: 803ms

[plugin: css-file]
  total: 141ms
   ├ start: 4ms
   └ onLoad: 137ms

[plugin: url-imports]
  total: 0ms
   └ start: 0ms

[plugin: remix-mdx]
  total: 74ms
   └ start: 74ms

[plugin: browser-route-modules]
  total: 46621ms
   ├ start: 0ms
   ├ onResolve: 17ms
   └ onLoad: 46604ms

[plugin: empty-modules]
  total: 3ms
   ├ start: 0ms
   ├ onResolve: 2ms
   └ onLoad: 1ms

[plugin: node-modules-polyfills]
  total: 146ms
   ├ start: 0ms
   ├ onResolve: 133ms
   └ onLoad: 13ms

💿 Built in 4.2s # Remix actually doesn't output this on the old dev server, I had to patch it in
```

Remix 1.14.0, unstable_dev turned on:

```
± yarn remix dev
± yarn remix dev
yarn run v1.22.19
$ /Users/dylan/dev/pfcs/node_modules/.bin/remix dev
[plugin: deprecated-remix-package]
  total: 2972ms
   ├ start: 1ms
   └ onResolve: 2971ms

[plugin: css-file]
  total: 2108ms
   ├ start: 2ms
   └ onLoad: 2106ms

[plugin: url-imports]
  total: 0ms
   └ start: 0ms

[plugin: remix-mdx]
  total: 73ms
   └ start: 73ms

[plugin: browser-route-modules]
  total: 110992ms
   ├ start: 0ms
   ├ onResolve: 3ms
   └ onLoad: 110989ms

[plugin: empty-modules]
  total: 5ms
   ├ start: 0ms
   ├ onResolve: 3ms
   └ onLoad: 2ms

[plugin: node-modules-polyfills]
  total: 297ms
   ├ start: 0ms
   ├ onResolve: 99ms
   └ onLoad: 198ms

[plugin: remix-hmr]
  total: 13607ms
   ├ start: 0ms
   ├ onResolve: 9ms
   └ onLoad: 13598ms

💿 Built in 8.7s
```

### Expected Behavior

Build/rebuild times to stay the same (or improve!) in new releases.

### Actual Behavior

4-5x slower build times in 1.14.0

**Comment by dmarkow** [comment]
Some preliminary research, starting with 8-9s rebuild times on a 1.14.0 app.

- I thought switching to the async versions of `fileRead` would help, it actually slowed it down more. So that wasn't the bottleneck.
- Focused on `browserRouteModulesPlugin` to start. Turned off `unstable_dev` which got me down to 4s rebuilds.
- The expensive part of `browserRouteModulesPlugin` is the tranformations that remove server exports and apply HMR updates. Wrapping that in a cache (https://esbuild.github.io/plugins/#caching-your-plugin) helps on rebuilds so files don't get re-transformed. Rebuilds now back to 1.5-2s.
- Turning `unstable_dev` back on brought rebuild times back up to around 6s. `hmrPlugin` has a similar issue where it re-transforms every file on every build, regardless if it changed or now. Wrapping that in a cache as well brought me back down to 2s!
- This could probably be extended to a file system cache to help with initial rebuilds, but I think that might be more error prone than it's worth. The real time savings will be shortening the rebuild time.

I'll test this out on my app for a bit this morning, and if it seems to be holding up I'll work on a PR.

**Comment by jonschlinkert** [comment]
I haven't looked into root causes, but we're experiencing something similar. Average built time was 1-2s with 1.13.0, and with 1.14.x it's more than 20s. This was enough for us to downgrade back to 1.13.0.
