### ISSUE TITLE
Typescript only stack support

### ISSUE THREAD

**Issue by meza** [remix-run/remix#5632]
### What version of Remix are you using?

@latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. create a stack that is typescript only
2. use the stack with `npx create-remix@latest --template your/stack`
3. choose to not have typsecript
4. observe as remix tries to do transformations it can't

### Expected Behavior

I'd expect this question to simply not exist. It should be up to the stack maintainers to offer all the transformations that a user is allowed to do on them automagically

### Actual Behavior

Remix tries to remove the tsconfig and modify the remix config among other things.

Instead of allowing the custom stack to carry on, the user is greeted with a failure and no way of continuing.

**Comment by markdalgleish** [comment]
Thanks for raising this issue. The new version of `create-remix` that's being released soon with Remix v2 (#6887) no longer performs any automatic TS to JS transformations. This issue is a good example of why we've opted to remove this behaviour.
