### ISSUE TITLE
TypeScript `satisfies` on an export produces a syntax error when building in v1.14.0

### ISSUE THREAD

**Issue by huw** [remix-run/remix#5641]
### What version of Remix are you using?

v1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Use the `satisfies` keyword on any export that will get stripped by the browser modules plugin, like so (I prefer to use them with loaders and actions instead of casting):

```ts
export const meta = (() => ({
  charset: "utf-8",
  title: "Remix",
})) satisfies MetaFunction;
```

### Expected Behavior

The build should succeed.

### Actual Behavior

In v1.13.0, the build succeeds. However, in v1.14.0, the new `BrowserRouteModulesPlugin` parses the syntax tree on exports differently, particularly when running [`removeServerExports`](https://github.com/remix-run/remix/blob/9a9c955f241c5742d227542e13c7387b99d4628b/packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts#L16). It produces this error:

```
error: Build failed with 1 error:
error: /src/app/root.tsx: Missing semicolon. (36:3)  
34 |  charset: "utf-8",
35 |  title: "Remix",
36 | })) satisfies MetaFunction;
   |    ^
37 |
```

This is because `@babel/core` (and its dependency, `@babel/parser`) have not been upgraded to support TypeScript 4.9. In addition, `recast`’s dependency `ast-types` has also not been upgraded to support TypeScript 4.9.

The short-term workaround is to add the following to your top-level `package.json`:

```json
"resolutions": {
  "@remix-run/dev/@babel/core": "^7.20.0",
  "ast-types@0.15.2": "0.16.1",
}
```

This will override the versions in `@remix-run/dev` and resolve them to versions that support TypeScript 4.9. However, the solution for this repo is trickier, because `recast` hasn’t been updated to support `ast-types@^0.16.0` yet.

**Comment by huw** [comment]
There’s an additional error here when building with `unstable_cssSideEffectImports: true`, which uses `@babel/parser` at some point in the build step. We can fix that by adding:

```json
resolutions: {
  "@remix-run/dev/@babel/parser": "^7.20.0",
}
```

**Comment by ntrpy** [comment]
I ran into the same issue today, I'm glad you already found a workaround for this.

Adding ast-types to resolutions in package.json was enough in my case. 

` 
  "resolutions": {
    "ast-types": "^0.16.1"
  },
`

Oddly, the `satisfies` ts-operator worked for me defining a MetaFunction, LoaderFunction, LinksFunction and RouteComponent. But the compiler threw an error using it on ActionFunction.

**Comment by huw** [comment]
Yep, it’s likely that in this case your package manager would’ve resolved `^7.18.6` up to something after `7.20.0`. If Remix fix this issue they’ll need to bump the minimum version to `^7.20.0`.

**Comment by akomm** [comment]
So create remix sets up typescript package dependency which the builder pipeline doesn't even use. I was confused that type check passes but the build fails. Sounds to me like a terrible Idea. I have no control over the TS version, other than resolution override workaround.

**Comment by pcattori** [comment]
Remix now uses Typescript 5.0+ and Babel 7.21+, fixing this issue. No longer reproducible on 1.19.2.
