### ISSUE TITLE
`unstable_vanillaExtract` does not update via HMR when using `unstable_dev`

### ISSUE THREAD

**Issue by drewschrauf** [remix-run/remix#5642]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

We're already using `unstable_dev` and `unstable_vanillaExtract` for our project. When we attempted to upgrade to Remix v1.14.0, we found the new HMR behaviour applies to React components but not to CSS generated through Vanilla Extract. I don't know if this applies to `@remix-run/css-bundle` in general or is specific to Vanilla Extract.

[I've created a minimal reproduction](https://github.com/drewschrauf/remix-hmr-ve).

1. Start the app with `npm run dev`
2. Edit the text in `app/routes/index.tsx` from `Hello` to `Goodbye`
3. Note that the text updates without refreshing the browser
4. Edit the style in `app/routes/index.css.ts` from `blue` to `red`
5. Note that the color **does not** update

Log messages are visible in the browser window. The app has seen the `.css.ts` file has changed but it doesn't apply the update.

### Expected Behavior

New styles should apply without a browser refresh.

### Actual Behavior

New styles do not apply until a browser refresh.

**Comment by markdalgleish** [comment]
Thanks for raising this issue. The fix should be out in the next release.
