### ISSUE TITLE
Selected value of a select tag is incorrect after page reload in Firefox

### ISSUE THREAD

**Issue by zvin** [remix-run/remix#5646]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a page like this:

```typescript
import { useState } from "react";

export default function View() {
  const [selectedValue, setSelectedValue] = useState("1");
  return (
    <>
      <pre>{JSON.stringify({ selectedValue }, null, 4)}</pre>
      <select
        value={selectedValue}
        onChange={({ target: { value } }) => {
          console.log("selected", value);
          setSelectedValue(value);
        }}
      >
        <option value="1">one (disabled) selected value is {selectedValue}</option>
        <option value="2">two (enabled) selected value is {selectedValue}</option>
      </select>
      <input
        value={`selectedValue=${selectedValue} disabled=${selectedValue === "1"}`}
        readOnly={true}
        disabled={selectedValue === "1"}
      />
    </>
  );
}
```

 * open it in Firefox (tested on `v110.0.1`);
 * open the dev tools console;
 * select the option "two" in the select;
 * reload the page with CTRL + r (not CTRL + SHIFT + r).

### Expected Behavior

 * the selected option should be "one" as defined by `useState`;
 * there should be no `Prop disabled did not match` warning.

### Actual Behavior

 * the selected option is still "two" while the state `selectedValue` is `"1"`;
 * this also leads to a `Prop `disabled` did not match. Server: "null" Client: "true"` warning in the input below like in #4679.

This does not happen in Chrome.

**Comment by zvin** [comment]
One way to fix this is to add `autoComplete="off"` to both the `select` and `input` tags.
Not sure this is an issue with remix.

**Comment by brophdawg11** [comment]
I am pretty sure this is a dup of https://github.com/remix-run/remix/issues/4679 and potentially a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1847798

**Comment by brophdawg11** [comment]
Going to close this out in favor of #4679
