### ISSUE TITLE
Removing entry.client & entry.server causes remix dev to hang

### ISSUE THREAD

**Issue by jgentes** [remix-run/remix#5669]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Just testing the ability to use default client/server entry files. When I remove them, Remix installs `isbot` to my dependencies (would be nice to know why, otherwise it may get removed accidentally in the future) and hangs on yarn dev. Here's the console log from when it ran normally, then started failing after removing the client/server files:

![image](https://user-images.githubusercontent.com/1149470/222970661-04a8020e-3f57-49cd-a944-6b78b00bb5e7.png)

My `entry.client.tsx`:
```js
import { RemixBrowser } from '@remix-run/react'
import { hydrate } from 'react-dom'

hydrate(<RemixBrowser />, document)
```

My `entry.server.tsx`:
```js
import type { EntryContext } from '@remix-run/node'
import { RemixServer } from '@remix-run/react'
import { renderToString } from 'react-dom/server'

const handleRequest = (
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) => {
  const markup = renderToString(
    <RemixServer context={remixContext} url={request.url} />
  )

  responseHeaders.set('Content-Type', 'text/html; charset=utf-8')
  //responseHeaders.set('Cross-Origin-Embedder-Policy', 'require-corp')
  //responseHeaders.set('Cross-Origin-Opener-Policy', 'same-origin')

  return new Response(`<!DOCTYPE html>${markup}`, {
    status: responseStatusCode,
    headers: responseHeaders,
  })
}

export default handleRequest
```

### Expected Behavior

Remix should run properly without client/server entry files.

### Actual Behavior

See above

**Comment by huw** [comment]
To answer the `isbot` question, the default Remix `entry.server.tsx` file now includes `isbot` to determine whether to stream the response or immediately render it. This is new to recent versions of the templates, which use React Streaming SSR. If you created your project on an older version of the template you wouldn’t have that setup.

**Comment by mcansh** [comment]
> To answer the `isbot` question, the default Remix `entry.server.tsx` file now includes `isbot` to determine whether to stream the response or immediately render it. This is new to recent versions of the templates, which use React Streaming SSR.

bingo!

**Comment by mcansh** [comment]
based on your entry files, it appears you're using react 17, is that correct? if so, that's unfortunately unsupported with optional entries currently, but #5681 will bring that to you soon

**Comment by jgentes** [comment]
Got it, sorry I missed the React 18 requirement - I'll look at updating or try with the upcoming fix - thanks!

**Comment by jgentes** [comment]
I'm happy to report that upgrading to React 18 (and updating Emotion) did the trick. Removing the client and server entry files worked as expected, thanks!
