### ISSUE TITLE
Duplicate children keys in `getStylesheetPrefetchLinks`

### ISSUE THREAD

**Issue by grinkus-adapt** [remix-run/remix#5677]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Open [the sandbox](https://codesandbox.io/p/sandbox/elastic-volhard-pko1zw?file=%2Fapp%2Fstyles%2FComponentOfComponents.css&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A2%7D%5D) and devtools. Clear the console.
2. Hover over the "Foobar?" link with mouse (or focus with keyboard, etc).
3. See that there's a "Encountered two children with the same key, `/build/_assets/Component-O4OLHRZ6.css`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version." warning in the devtools console.

The issue is that we're importing the stylesheet in a component, that is imported in a few different places.

### Expected Behavior

No errors in the console.

### Actual Behavior

There's an error in the devtools console "Warning: Encountered two children with the same key, `/build/_assets/Component-O4OLHRZ6.css`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."

**Comment by grinkus-adapt** [comment]
I imagine doing something like the code below in [remix-react/links.ts](https://github.com/remix-run/remix/blob/9a9c955f241c5742d227542e13c7387b99d4628b/packages/remix-react/links.ts#L337) would resolve the issue, but I'm not totally sure if that wouldn't break anything.

```diff
diff --git a/packages/remix-react/links.ts b/packages/remix-react/links.ts
index 6c070d574..dc59eb38e 100644
--- a/packages/remix-react/links.ts
+++ b/packages/remix-react/links.ts
@@ -338,6 +338,15 @@ export async function getStylesheetPrefetchLinks(
     .flat(1)
     .filter(isHtmlLinkDescriptor)
     .filter((link) => link.rel === "stylesheet" || link.rel === "preload")
+    .filter(
+      // Dedupe links by rel and href
+      (link, indexToFind, linksArr) => {
+        let foundIndex = linksArr.findIndex(needle => {
+          return needle.href === link.href && needle.rel === link.rel;
+        });
+        return foundIndex === indexToFind
+      }
+    )
     .map((link) =>
       link.rel === "preload"
         ? ({ ...link, rel: "prefetch" } as HtmlLinkDescriptor)

```

**Comment by markdalgleish** [comment]
Thanks for raising this issue, and thanks for the suggested fix! I've opened a PR that goes a bit further than your suggested fix because this was actually a symptom of a deeper issue: https://github.com/remix-run/remix/pull/7060
