### ISSUE TITLE
unstable_dev HMR express on different port than 3000 is not working

### ISSUE THREAD

**Issue by pkasarda** [remix-run/remix#5758]
### What version of Remix are you using?

1.14.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```sh
npx create-remix@latest
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y
? Where would you like to create your app? 
remix-express-v2
? What type of app do you want to create?
Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets.
Express Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```

change package.json to
```
// package.json scripts
"dev": "run-p dev:*",
"dev:build": "cross-env NODE_ENV=development remix dev",
"dev:serve": "cross-env NODE_ENV=development nodemon --require dotenv/config --watch build server.js",
```
btw from release there was missing ` --require dotenv/config` part https://github.com/remix-run/remix/releases/tag/remix%401.14.0

update remix.config.js
```js
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  future: {
    v2_routeConvention: true,
    unstable_dev: true,
  },
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
};
```

create .env and put there 
```env
PORT=3005
```

and start it with npm run dev :-)

### Expected Behavior

able to run HMR on any port

### Actual Behavior

on PORT 3000 it will work correctly on 3005 HMR will not do anything no error or nothing

**Comment by xihayouyi** [comment]
// remix.config.js
module.exports = {
  future: {
    unstable_dev: {
      // Port for running your Remix app server
      // This can be overridden by a CLI flag: `remix dev --app-server-port 3021`
      // default: `3000`
      appServerPort: 3005,
    },
  },
};

**Comment by pcattori** [comment]
The options for configuring the new dev server have changed. `PORT` is no longer used by the new dev server.

See the **Options** section of the [1.16 release notes for details](https://github.com/remix-run/remix/releases/tag/remix%401.16.0).
