### ISSUE TITLE
ShouldRevalidateFunction's actionResult type doesn't match its contents

### ISSUE THREAD

**Issue by dmarkow** [remix-run/remix#5759]
### What version of Remix are you using?

1.14.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`ShouldRevalidateFunction`'s `actionResult` argument is of type `DataResult`, which is defined below. However, `actionResult` really just holds the data returned by the result.

So if my action returns `json({ok: true})` `actionData` will be `{ok: true}`. None of the keys from `SuccessResult` below are actually in the object. And if I return something like `json({error: "my error"}, {status: 422})`, there's no way to see that status code in my `shouldRevalidate` function, because all I get is `{error: "my error"}`. This means I have to bypass the type of `actionResult` and rely on the shape of the data, instead of using the HTTP status codes to know if my action was successful or not.

```typescript
export declare enum ResultType {
    data = "data",
    deferred = "deferred",
    redirect = "redirect",
    error = "error"
}
/**
 * Successful result from a loader or action
 */
export interface SuccessResult {
    type: ResultType.data;
    data: any;
    statusCode?: number;
    headers?: Headers;
}
/**
 * Successful defer() result from a loader or action
 */
export interface DeferredResult {
    type: ResultType.deferred;
    deferredData: DeferredData;
    statusCode?: number;
    headers?: Headers;
}
/**
 * Redirect result from a loader or action
 */
export interface RedirectResult {
    type: ResultType.redirect;
    status: number;
    location: string;
    revalidate: boolean;
}
/**
 * Unsuccessful result from a loader or action
 */
export interface ErrorResult {
    type: ResultType.error;
    error: any;
    headers?: Headers;
}
/**
 * Result from a loader or action - potentially successful or unsuccessful
 */
export declare type DataResult = SuccessResult | DeferredResult | RedirectResult | ErrorResult;
```

### Expected Behavior

Either `actionResult` should just by typed to `AppData` (which defaults to `any`) similar to `useActionData()`'s type, or the result should be returned in the `DataResult` format.

### Actual Behavior

`actionResult` is of type `DataResult` which doesn't match it's actual data.

**Comment by brophdawg11** [comment]
This is fixed by https://github.com/remix-run/react-router/pull/10779 and will be resolved with Remix v2
