### ISSUE TITLE
[Bug]: Add support for android

### ISSUE THREAD

**Issue by sayantan300** [remix-run/remix#576]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [X] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### Steps to Reproduce

Use termux from f-droid (their site: https://termux.org)
Install it on an android phone/android emulator.
Run the `npx create-remix@latest`
choose js, express.
Error:
```
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/my-remix-app/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /data/data/com.termux/files/home/my-remix-app/node_modules/esbuild/install.js:74
npm ERR!     throw new Error(`Unsupported platform: ${platformKey}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported platform: android x64 LE
npm ERR!     at pkgAndSubpathForCurrentPlatform (/data/data/com.termux/files/home/my-remix-app/node_modules/esbuild/install.js:74:11)
npm ERR!     at checkAndPreparePackage (/data/data/com.termux/files/home/my-remix-app/node_modules/esbuild/install.js:211:28)
npm ERR!     at Object.<anonymous> (/data/data/com.termux/files/home/my-remix-app/node_modules/esbuild/install.js:238:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-24T10_37_57_150Z-debug.log
Error: Command failed: npm install
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (/data/data/com.termux/files/home/.npm/_npx/5164864a48bff686/node_modules/create-remix/cli.js:200:19) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9199,
  stdout: null,
  stderr: null
}
```

PS: theres no real problem here, its just that esbuild doesnt has the android platform saved. Keep in mind that this platform (termux) is an linux emulator that can run anything (even real distro and their desktops) I dont think theres any boundary that can stop esbuild from compiling/building here.

I was actually checking remix on mobile and decided to give it a try on mobile itself. Everything will simply work here. Thank you.

### Expected Behavior

Project created successfully.

### Actual Behavior

esbuild fails to compile/build because it doesnt know about android platform.

**Comment by sayantan300** [comment]
I also just noticed that even if the command failed, it created/didnt delete the folder where I wanted to create remix app

**Comment by machour** [comment]
Seems to be fixed now https://github.com/evanw/esbuild/issues/204, if not, this needs to be reported to [`esbuild`](https://github.com/evanw/esbuild/)
