### ISSUE TITLE
App Tutorial (long) doesn't handle v2_routeConvention: true

### ISSUE THREAD

**Issue by hkarthik** [remix-run/remix#5777]
### What version of Remix are you using?

1.14.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Follow the App Tutorial (long)  [here](https://remix.run/docs/en/1.14.1/tutorials/jokes).

Once you reach the Routes section of the tutorial, you'll realize that your Outlet tags will not render.

Poking around I realized this is because the tutorial has not been updated to utilize V2 Route files: https://remix.run/docs/en/main/file-conventions/route-files-v2

Easy fix to switch remix.config.js to set 
`module.exports = {
  future: {
    v2_routeConvention: false,
  },
...`

Then the tutorial works as desired. Should add this to the top of the tutorial until the V2 routing switch is fully rolled out.

### Expected Behavior

Outlets created in root.tsx will render if using previous route filename convention

### Actual Behavior

Outlets created in root.tsx will not render if using previous route filename convention unless `v2_routeConvention` is set to false

**Comment by Ayush-v** [comment]
im new to remix and im facing the same issue and i am not able to figure out a simple way in the docs and no tutorial is there on the internet

**Comment by Ayush-v** [comment]
You can check these docs 
[Route File Naming (v2) docs](https://remix.run/docs/en/1.14.1/file-conventions/route-files-v2)

and if it comes to file naming you can name the files like below

/                        ------->    _index.tsx
/jokes               ------->     jokes.tsx (with <Outlet />) and u can also create a jokes._index.tsx file 
/jokes/:jokeId  ------->     jokes.$jokeId.tsx
/jokes/new      ------->    jokes.new.tsx
/login.              ------->     login.tsx

remix with v2 routes follow [Dot Delemiters](https://remix.run/docs/en/1.14.1/file-conventions/route-files-v2#md-dot-delimiters)

**Comment by buaiscia** [comment]
I'm having the same issue with nested routes for the short tutorial, and the docs for v2 routing don't offer any explicit example. So, for v1, /posts/$slug.tsx works fine, but not with v2. Can you point where nested dynamic routes are described, or how would they work? 
Thank you!

**Comment by MichaelDeBoey** [comment]
@hkarthik The templates are reverted to not use any future flags (yet), so Jokes tutorial should work again

@buaiscia Blog tutorial will be fixed by #5959
