### ISSUE TITLE
[Feature]: Add different css frameworks for create-remix app

### ISSUE THREAD

**Issue by sayantan300** [remix-run/remix#579]
### What is the new or updated feature that you are suggesting?

Add different css frameworks like tailwind, bulma, material, bootstrap and others.

### Why should this feature be included?

so there would be an official and easy way to make a project with them :sunglasses:

**Comment by jawojoey** [comment]
Yes pleeaaaase!!!!

**Comment by finnan444** [comment]
It will be a good idea to add an example with material ui (mui) in Documentation

**Comment by duvet86** [comment]
This is my remix material UI ssr integration
https://github.com/duvet86/remix-mui

**Comment by krnbr** [comment]
> This is my remix material UI ssr integration https://github.com/duvet86/remix-mui

example for express based setup??

**Comment by sergiodxa** [comment]
@krnbr all the code inside `app` should work regardless of the setup you used, only exception right now could be CF Workers if you used Node.js built-in modules, and that repo uses `@remix-run/serve` which uses Express internally so everything there should work for you.

**Comment by krnbr** [comment]
@sergiodxa 

css misses out when I click on back button using browser, and page styles for MUI are just lost, in case of the express based setup

**Comment by oliviertassinari** [comment]
The first iteration on MUI's side: https://github.com/mui-org/material-ui/pull/29952.

**Comment by Girish21** [comment]
hey, @oliviertassinari I tried with a similar implementation, https://github.com/Girish21/remix-css-in-js. The only problem is, when we land on "CatchBoundary" (let's say a 404 page), all the styles are lost for some reason 😕

**Comment by jansedlon** [comment]
Got the same issue. When I land on 404 and then go back, all styles are lost. Haven't figured out a solution yet

**Comment by pixelstew** [comment]
Anyone found a solution on this? Looking myself but no dice.

**Comment by lvauvillier** [comment]
@oliviertassinari @Girish21 @pixelstew I posted a workaround here (material-ui / emotion) : https://github.com/mui-org/material-ui/issues/30436#issuecomment-1003339715

**Comment by pixelstew** [comment]
Amazing, I have actually started using tailwind but have pasted it on the Remix discord. Could probably do with getting a PR or two in place to update docs.

**Comment by machour** [comment]
Instead of adding CSS framework selection to create-remix app (and add a maintenance burden on the team), we have some examples in this repository. Feel free to contribute yours by opening a PR 🙏🏼
