### ISSUE TITLE
`defer`/streaming SSR isn’t responding with the fallback UI on iOS Safari

### ISSUE THREAD

**Issue by huw** [remix-run/remix#5804]
### What version of Remix are you using?

v1.14.2 (repro on v1.11)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Load https://simple-remix-deferred-demo.fly.dev/ from [jacob-ebey/stupid-simple-remix-deferred-demo](https://github.com/jacob-ebey/stupid-simple-remix-deferred-demo/tree/main) (just an example of an easy hosted repro from a contributor) in Safari on iOS. After the initial load, also reload the page a few times.

If it helps, I am on the 16.4 beta but have seen this issue for non-beta minor releases since `defer` was introduced. I am able to reproduce it on other WebKit browsers on iOS, with extensions, content blockers and iCloud Private Relay disabled.

### Expected Behavior

The skeleton UI should be immediately visible, and the data should load a second later. When inspecting the source of the webpage, the response HTML from the initial request should include the HTML for the suspense fallback.

### Actual Behavior

The page waits a second and then loads all at once. When inspecting the source of the webpage, the fully-loaded HTML is present in the response instead of the fallback HTML.

A couple of notes that made this hard to diagnose:
- On the initial load it shows up quite quickly, but this is just because Safari preloads URLs and not because streaming is working there. If you want to see for yourself, you can try with a longer initial load, say 5 seconds.
- On reloads, it keeps the page as-is and just reloads a couple of the images. But you can tell that the actual request is taking longer by connecting to a Mac and using the Web Inspector, or just by observing the loading bar.

Here’s a video of a few different loading scenarios:

https://user-images.githubusercontent.com/2456132/225180800-7b58c50e-ddaa-4469-ab4c-ad7ee11b1611.mov

## Some more background & thoughts
I was originally splitting a normal webpage load into a deferred and awaited call, and was assuming that the awaited call was bottlenecking the page. But when I created a new loader with some deferred data, it became clear that I’d actually been seeing this issue for months.

I have _no idea_ how to diagnose and handle this issue, I have no idea whether it’s Remix, react-router, React, Safari, or whatever. I don’t really know if it’s even a bug and not something weird with my own setup (I’ve tried everything I can think of there), but I’m filing it in case a kind soul can and reproduce it :)

**Comment by sergiodxa** [comment]
Safari buffer the HTML response until it reach a certain kb size, if your HTML is smaller it will buffer it and give it time to your deferred data to finish, so this could be causing that behavior.

**Comment by huw** [comment]
@sergiodxa Really interesting! Found the same behaviour [on this repo](https://github.com/XiNiHa/streaming-ssr-showcase/commit/73e8df499dd47c1e9d089939c36bb58e04797ed6). I will investigate a bit later today and if that’s the fix I’ll close this as an upstream problem.

**Comment by huw** [comment]
Yeah, the only workaround I could find is to pad out the page to the rough limit for Safari, which seems to be around ~650B gzipped, but this is extremely annoying and there’s no good way to dynamically resize the pad (I tried transforming the output stream, but that just puts it at the end of the stream which Safari doesn’t count).

Very annoying! But definitely not something the Remix team can deal with.

**Comment by kpalmvik** [comment]
I recently ran in to this problem when trying to configure Remix to stream the HTML response. Just like OP I was a bit confused why streaming didn't work as described on iOS.

Eventually I found a [similar bug report for SvelteKit](https://github.com/sveltejs/kit/issues/10315) which had resulted in [WebKit Bug 252413:WebKit is too conservative in its first paint threshold](https://bugs.webkit.org/show_bug.cgi?id=252413)

This problem/bug/optimization (depending on how you see it) is obviously not something that Remix, or any other framework, can fix in itself.

However, consider if this should be documented in [Streaming](https://remix.run/docs/en/main/guides/streaming) to prevent more people from being confused.

**Comment by b2whats** [comment]
Solve
Add for safari html tag 
```js
// example react - 200 sequence  \u200b
const sp = '\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b\u200b'


<div style={{width: 0, height: 0}} dangerouslySetInnerHTML={{__html: sp}}></div>
```
