### ISSUE TITLE
[Feature]: Add Tailwind JIT mode in your docs

### ISSUE THREAD

**Issue by sayantan300** [remix-run/remix#581]
### What is the new or updated feature that you are suggesting?

Add Tailwind JIT mode method at https://remix.run/docs/en/v1/guides/styling

### Why should this feature be included?

Cause jit is a lot fast, that means remix will be a lot faster too!

**Comment by mnlfischer** [comment]
I want to point out that every user of tailwind should read the docs. 

> We encourage you to read the official Tailwind installation instructions as well.

In addition Jit Mode is in preview and I'm not sure if preview features should be official added.

**Comment by sayantan300** [comment]
> I want to point out that every user of tailwind should read the docs.
> 
> > We encourage you to read the official Tailwind installation instructions as well.
> 
> In addition Jit Mode is in preview and I'm not sure if preview features should be official added.

jit mode is used by everyone, and is shipping out with tailwind v3.

**Comment by mnlfischer** [comment]
Totally agree with you. It depends on waiting for v3 stable or recommend it now an edit it in future. If you like you can jump into the discussion in PR.

**Comment by mnlfischer** [comment]
can be closed @ryanflorence 
already done in your [Commit](https://github.com/remix-run/remix/commit/5a0108827f0d1ac001138dfb5e28624450a642f9)

**Comment by sayantan300** [comment]
ok
thanks
