### ISSUE TITLE
[Bug]: useLoaderData returns undefined

### ISSUE THREAD

**Issue by Xiphe** [remix-run/remix#582]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1. check out `git@github.com:Xiphe/remix-error-action-loader-undefined.git`
2. run `npm install && npm run dev`
3. open [localhost:3000/nested/new](http://localhost:3000/nested/new)
4. Click the button
5. See `Cannot read properties of undefined (reading 'demos')` which results from [this `useLoaderData`](https://github.com/Xiphe/remix-error-action-loader-undefined/blob/main/app/routes/nested.tsx#L59) returning undefined

### Expected Behavior

I would either expect the type of `useLoaderData` to include `undefined` or that it never returns `undefined` (unless thats what my loader responds with obviously ;)

### Actual Behavior

Currently, when a nested action throws an error and catches it. Then loaders of parent components are affected. 

I stumbled upon this during the Jokes app tutorial where im instructed to create a similar setup like the one in https://github.com/Xiphe/remix-error-action-loader-undefined and then throw an error from within the create new joke action.

Also happened during Kents livestream: https://youtu.be/hsIWJpuxNj0?t=17466

**Comment by Alarid** [comment]
Just realized you posted this before me! I also [opened an issue](https://github.com/remix-run/remix/issues/599) on the subject, also with a github repo to reproduce... Maybe we should regroup them?

**Comment by andmayorov** [comment]
https://github.com/remix-run/remix/issues/599#issuecomment-978364515

**Comment by Xiphe** [comment]
@Alarid sure! 

Moving to => https://github.com/remix-run/remix/issues/599
