### ISSUE TITLE
incorrect warning about index routes having child routes

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5828]
If you have a file system that looks like this:

```
routes/
  _index/
    route.tsx
    blocks/
      index.tsx
```

`remix build` throws an error:

> Error: Child routes are not allowed in index routes. Please remove child routes of _index

It does the same if you use `blocks/route.tsx` as well.

The code shouldn't be digging that deep in the first place to even register that there might a route definition. It should only be looking for routes at: `routes/*.tsx` and `routes/*/route.tsx`.

There's no reason for it to be digging deeper, you should be able to name things whatever you want once you're in a route folder aside from `folder/route.tsx` and `folder/index.tsx`.

**Comment by mcansh** [comment]
fixed by the improvements made in 1.15 https://github.com/remix-run/remix/pull/5634
