### ISSUE TITLE
HMR does not work when specifying a port

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#5834]
I recorded a loom to demonstrate the issue: https://www.loom.com/share/b9a88877d0a642cdbe305605212d1695

I tried a bunch of different combinations and it just appears that if you specify a `PORT` environment variable or use the `-p` flag, HMR will not work.

**Comment by pcattori** [comment]
Yea for `unstable_dev`, the `PORT` env var is vestigial. Should probably just ignore that env var for `remix dev` when using `unstable_dev`.

That said, you should be able to use the `--app-server-port` and `--port` flags for `remix dev` (again, assuming `unstable_dev` is enabled).

**Comment by kentcdodds** [comment]
That's great! I'll give that a shot next time I get in front of the keyboard. I guess we can leave this open as an issue to document this in `--help` and also to ignore the PORT env var or something. Thanks!

**Comment by pcattori** [comment]
Oh and I should mention that you can also set the app server port in `remix.config.js`:

```js
module.exports = {
  unstable_dev: {
    appServerPort: 4444
  }
}
```

or via flag as mentioned previously. Your choice.

All configurable options are detailed in [the release notes for v1.12.0](https://github.com/remix-run/remix/releases/tag/remix%401.12.0), though still need to write up some better docs.

**Comment by kentcdodds** [comment]
Awesome. I've also added `port: ''` to that config so it selects a random port instead of using the environment variable `PORT`.
