### ISSUE TITLE
[Feature]: Demonstrate how to integrate with nprogress?

### ISSUE THREAD

**Issue by dpyzo0o** [remix-run/remix#584]
### What is the new or updated feature that you are suggesting?

Sometimes when you have heavy operations in the route loader function, it takes some time before navigating to the new route. If there is no loading indicator on the screen it just feels slaggish. I suppose nprogress is a great fit here to indicate that something is happening before the navigating. Could you add a demo showing how to do this?

### Why should this feature be included?

A demo showing how remix works with nprogress

**Comment by sergiodxa** [comment]
You can use `useTransition` to know when to start Progress and when to complete it

```ts
let transition = useTransition()

useEffect(() => {
  // if it's not idle then it's submitting a form and loading the next location loaders
  if (transition.state !== "idle") {
    NProgress.start(); // so you start it
  } else {
    NProgress.done(); // when it's idle again complete it
  }
}, [transition.state])
```

Something like that, put it in the root route and it will work globally.

**Comment by dpyzo0o** [comment]
@sergiodxa Thanks, I will have a try.

**Comment by sergiodxa** [comment]
@dpyzo0o I just tried it in an app and it works, I wrote about the whole setup here https://sergiodxa.com/articles/use-nprogress-in-a-remix-app

**Comment by raymclee** [comment]
> @dpyzo0o I just tried it in an app and it works, I wrote about the whole setup here https://sergiodxa.com/articles/use-nprogress-in-a-remix-app

```
Argument of type '"idle" | "submitting" | "loading"' is not assignable to parameter of type 'DependencyList | undefined'.
  Type '"idle"' is not assignable to type 'DependencyList | undefined'.ts(2345)
(property) state: "idle" | "submitting" | "loading"
```

I'm using typescript and got this type error
