### ISSUE TITLE
HMR does not work for lazily imported components

### ISSUE THREAD

**Issue by rossipedia** [remix-run/remix#5845]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create new Remix project with `npx create-remix@latest`
2. Enable HMR by following the [1.14 instructions](https://github.com/remix-run/remix/releases/tag/remix%401.14.0)
3. Add a new component, and lazily import it from `app/routes/index.tsx`:
  ```tsx
  import { lazy } from 'react';
  const LazyComponent = lazy(() => import('~/app/components/LazyComponent'));

  // add it to the component in `app/routes/index.tsx`:
  return (
    ...
    <LazyComponent /> 
    ...
  );
  ```
   
4. Edit `app/routes/index.tsx` and observer that HMR works correctly and the UI is updated (change a `style` prop or something similar).
5. Edit the lazy component (`~/app/components/LazyComponent.tsx` in this example) 

[Example Repository](https://github.com/rossipedia/remix-hmr-lazy-bug)

### Expected Behavior

HMR works for the lazily imported component and the UI is updated without a page refresh

### Actual Behavior

HMR does not work for the lazy component, and the UI is not updated

**Comment by pcattori** [comment]
Cannot reproduce in 1.19.2. Changing `LazyComponent` (styles, markup, etc..) produces HMR'd content.
