### ISSUE TITLE
Routing V2 Convention nested folders error

### ISSUE THREAD

**Issue by MajorTom327** [remix-run/remix#5849]
### What version of Remix are you using?

v1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create thoses files and directory for the routing system.
```
routes
├── _index.ts
├── statistics/
│   └── index.tsx
└── statistics._index/
    ├── index.tsx
    └── StatBlock/
        ├── index.ts
        └── StatBlock.tsx
```

`statistics._index/index.tsx` is using the component (Not a route) `statistics._index/StatBlock/index` (Re-exported, in my case I got multiples components in this directory)

Run `yarn remix routes`

### Expected Behavior

Should generate the routes correctly and do not expect a subdirectory to be a subroute definition as defined in the documentation [Folders for Organization](https://remix.run/docs/en/1.14.3/file-conventions/route-files-v2#md-folders-for-organization) section

```jsx
<Routes>
  <Route file="root.tsx">
    <Route file="routes/index.tsx" />
    <Route path="statistics" file="routes/statistics/index.tsx">
      <Route index file="routes/statistics._index/index.tsx" />
    </Route>
  </Route>
</Routes>
```

### Actual Behavior

Running `yarn remix routes` throw an exception as remix handle the sub-directory as the v1 convention and the component directory is considered as a subroute and no subroutes can't be defined in a `_index` route.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/16199396/226354742-b37395ce-1d5c-448c-85be-b7a0bb86e861.png">

I made a simple reproduction project you can find here: https://github.com/MajorTom327/remix-route-v2

**Comment by irshadahmad21** [comment]
Duplicate of #5828

**Comment by MajorTom327** [comment]
True. Didn't saw that issue.
Closing.
