### ISSUE TITLE
Upgrade TypeScript to version 5

### ISSUE THREAD

**Issue by justb3a** [remix-run/remix#5871]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Try to upgrade typescript to version 5.x

```
    "typescript": "^5.0.0",
```

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @remix-run/eslint-config@1.14.3
npm ERR! Found: typescript@5.0.2

### Expected Behavior

Remix should be able to work with typescript version 5.  Multiple packages contain the following

```
  "devDependencies": {
    "typescript": "^4.7.4"
  },
  "peerDependencies": {
    "typescript": "^4.0.0"
  },
```

### Actual Behavior

Upgrading typescript is not possible:

```
npm WARN ERESOLVE overriding peer dependency                                                               
npm WARN While resolving: app@1.0.0                  
npm WARN Found: typescript@4.9.5                     
npm WARN node_modules/typescript                     
npm WARN   dev typescript@"^5.0.0" from the root project                                                   
npm WARN   5 more (@remix-run/eslint-config, ...)                                                          
npm WARN                                             
npm WARN Could not resolve dependency:               
npm WARN peerOptional typescript@"^4.0.0" from @remix-run/eslint-config@1.14.0                             
npm WARN node_modules/@remix-run/eslint-config                                                             
npm WARN   dev @remix-run/eslint-config@"^1.7.5" from the root project                  
```

**Comment by lpsinger** [comment]
Yup, `@remix-run/eslint-config` currently has a peer dependency on `typescript@^4.0.0`.

**Comment by MichaelDeBoey** [comment]
I created #5881 to add TS 5 support

**Comment by MichaelDeBoey** [comment]
Closed by https://github.com/remix-run/remix/commit/6b6ee66a2fef1a7b00ce4c95abed144ab80017e3 & #5881
