### ISSUE TITLE
Support ESM with @remix-run/dev

### ISSUE THREAD

**Issue by jasonkuhrt** [remix-run/remix#5886]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Have an ESM TS project
2. Try importing from `@remix-run/dev/server-build`
3. TS throws error: `Cannot find module '@remix-run/dev/server-build' or its corresponding type declarations.`

### Expected Behavior

`@remix-run/dev` should be an ESM package and thus have an explicitly defined set of entrypoints.

This fixes this issue (but then breaks the dev CLI):

```json
"type": "module",
  "exports": {
    ".": {
      "import": "./dist/index.js"
    },
    "./server-build": {
      "import": "./server-build.js",
      "types": "./server-build.d.ts"
    }
  },
```

### Actual Behavior

It isn't ESM.

<img width="759" alt="CleanShot 2023-03-23 at 10 03 34@2x" src="https://user-images.githubusercontent.com/284476/227228243-364e4bf4-84ee-4caf-abf5-30775159992d.png">

**Comment by jasonkuhrt** [comment]
Possibly related https://github.com/remix-run/remix/pull/4676

**Comment by zwn** [comment]
Is this still an issue? I am using 1.18.0 with ESM and it works as expected.

**Comment by pcattori** [comment]
Not reproducible in 1.19. For example [typechecking passes for the arc template](https://github.com/remix-run/remix/blob/main/templates/arc/server.ts#L2) (note: `skipLibCheck: true` must be set in the `tsconfig.json` to work around other unrelated problems)
