### ISSUE TITLE
codemod does not respond to --force flag

### ISSUE THREAD

**Issue by brad2014** [remix-run/remix#5896]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```sh
$  npx @remix-run/dev@latest  codemod  replace-remix-magic-imports --force
Error: /Users/brad/Projects/test has uncommitted changes
Stash or commit your changes before running codemods
To override this safety check, use the --force flag
```

### Expected Behavior

The codemod should run because the force flag was specified.

### Actual Behavior

Even though the --force flag was used, the command complains, telling me I need to use the --force flag.

**Comment by pcattori** [comment]
Could you try with the `--force` flag immediately after `codemod` (ie. before `replace-remix-magic-imports`)?

**Comment by MichaelDeBoey** [comment]
Closing this as we removed all codemods in v2 and we're only planning on fixing things that are really critical before v2 release
