### ISSUE TITLE
Websocket server error with express and https on localhost (live reload)

### ISSUE THREAD

**Issue by TimoWestland** [remix-run/remix#5899]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Setup a custom express server
- Use remix watch instead of remix dev
- Use node https to create a local https server with self signed certificates

### Expected Behavior

Live reload to work with an express server running on `https://localhost`

### Actual Behavior

The app loads fine but shows the following error and live reload is not working:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/3959082/227583751-7088a3e0-9705-4896-9f09-c316a5cbc892.png">

**Comment by joejemmely** [comment]
Related:
- #5348

**Comment by pcattori** [comment]
The new dev server (currently `unstable_dev` future flag) has options for configuring SSL.
