### ISSUE TITLE
LiveReload port prop won't override default using new dev server

### ISSUE THREAD

**Issue by garand** [remix-run/remix#5906]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Set the LiveReload component port prop to anything, eg. `<LiveReload port={4567} />`

### Expected Behavior

I expect the port prop to override the default behavior in the component. To me, it seems that this check is backwards or not correctly respecting the port prop. https://github.com/remix-run/remix/blob/main/packages/remix-react/components.tsx#L1600

My use case is that I am using Caddy server to have local SSL and I need to proxy the web socket port from a different port number, so I need the socket to connect through a different port than the actual web socket server is running on.

This used to work as expected before the new dev server introduction.

### Actual Behavior

The web socket connection still uses the default value set on `window.__remixContext.dev.liveReloadPort`, not the custom value set in the port prop.

**Comment by garand** [comment]
This appears to be related to these:

https://github.com/remix-run/remix/issues/5348
https://github.com/remix-run/remix/issues/4476

**Comment by mcansh** [comment]
are you also updating the `port` in `unstable_dev`? 

```diff
- unstable_dev: true
+ unstable_dev: {
+   port: 4567,
+ }

then you also shouldn't need to add the prop to `<LiveReload>`

**Comment by kj** [comment]
I'm also using Caddy. Remix 1.15.0. The `LiveReload` component always tries to connect to a random port (not accessible through Caddy) even though I set `{ unstable_dev: { port: 8002 } }`.

**Comment by pcattori** [comment]
You can now use the `--http-port` flag or `unstable_dev.httpPort` config to set the port for the new dev server. Note that this sets the port for the dev server, not your app server. You most likely shouldn't care about the dev server port at all unless you need to support SSL or configure networking e.g. Docker.

To edit your app server's port, do so normally as you would for your production server (e.g. in your `./server.js` file or via options available to `remix-serve`)
