### ISSUE TITLE
No matching version found for eslint-visitor-keys@^3.4.0.

### ISSUE THREAD

**Issue by emadaldin-baybars** [remix-run/remix#5942]
### What version of Remix are you using?

^1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- open your terminal 
- write `npx create-remix@latest`
- use default choices 
     * for the app type : `Just the basics`
     * where to deploy : `Remix app server`
     * typescript or javascript : whatever
     * npm install : `yes`

### Expected Behavior

All npm packages to be installed successfully 

### Actual Behavior

npm install process fails for this reason `No matching version found for eslint-visitor-keys@^3.4.0.`

**Comment by peschee** [comment]
Although I am not a remix user, I have run into the same issue. The `eslint-visitor-keys` has been updated in the latest ESLint `8.37.0` release in this PR (https://eslint.org/blog/2023/03/eslint-v8.37.0-released/):

https://github.com/eslint/eslint/pull/17030

I have been able to solve this issue on my end by clearing the local npm cache: `npm cache clean --force`

**Comment by alimaslax** [comment]
> Although I am not a remix user, I have run into the same issue. The `eslint-visitor-keys` has been updated in the latest ESLint `8.37.0` release in this PR (https://eslint.org/blog/2023/03/eslint-v8.37.0-released/):
> 
> [eslint/eslint#17030](https://github.com/eslint/eslint/pull/17030)
> 
> I have been able to solve this issue on my end by clearing the local npm cache: `npm cache clean --force`

Yep that worked. For anyone doing renovate bot / npm outdated. Clean your cache if you run into this issue
