### ISSUE TITLE
Code snippet in docs for Jokes tutorial is missing `useLoaderData` in import statement

### ISSUE THREAD

**Issue by georgefairbairn** [remix-run/remix#595]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

v1.0.4

### Steps to Reproduce

In the [Read from the database in a remix loader](https://remix.run/docs/en/v1/tutorials/jokes#read-from-the-database-in-a-remix-loader) section, the `useLoaderData` is missing from the import statement in the code snippet.

### Expected Behavior

`useLoaderData` should be in Remix import statement

### Actual Behavior

`useLoaderData` is not in Remix import statement

**Comment by machour** [comment]
PR available: https://github.com/remix-run/remix/pull/1534
