### ISSUE TITLE
CatchBoundary only works when the page also exports a component

### ISSUE THREAD

**Issue by frontendphil** [remix-run/remix#5951]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a global `CatchBoundary` in `root.tsx`
2. Create an `_index/index.ts` for a sub-route that only exports a `loader` but not a component
3. `throw` in the loader

### Expected Behavior

The root `CatchBoundary` renders with the respective error

### Actual Behavior

I see the error as plain text JSON. No `CatchBoundary` is triggered. As soon as the route exports a component, the `CatchBoundary` shows up.

**Why do you not export a component?**
The `index` isn't used for layouting and doesn't provide any value on its own. Inside the loader, we determine to which more specific route we should redirect the user.

**Comment by mcansh** [comment]
if you're not exporting a component, then it's considered a "resource route" and CatchBoundary nor ErrorBoundary will render as you could be sending anything in the response not just html

**Comment by brophdawg11** [comment]
As Logan said this is considered a resource route if no UI is exported.  If you're intending to `redirect` then you shouldn't ever want to see the root `CatchBoundary` and instead land on a UI-route after the redirect.  

This works for me in an `_index.tsx` file:

```jsx
import { redirect } from "@remix-run/node";

export function loader() {
  throw redirect("/test");
}
```

If you _sometimes_ want something to render at `/` and need to throw up to the root catch boundary, then you will need to add a default component export to turn it into a UI route.

```jsx
import { redirect } from "@remix-run/node";

export function loader() {
  if (condition) {
    throw redirect("/test");
  }
  throw new Response(null, { status: 404 });
}

// This tells Remix that we intend to render some form of UI at this route path, 
// even though we know it'll always be the root catch boundary since we only 
// ever throw from our loader
export default function component() {
  return null;
}
```
