### ISSUE TITLE
Stripping of "node:" prefix on node imports like 'node:util' breaks CloudFlare nodejs_compat

### ISSUE THREAD

**Issue by jasonkuhrt** [remix-run/remix#5954]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Have `import * as Util from 'node:util'; console.log(Util);` in a Remix app that targets CloudFlare.
2. Run `remix build`
3. Note how the build output has `'util'` instead of `'node:util'`. 
4. Have a `wrangler.toml` file that includes `compatibility_flags = ["nodejs_compat"]`
5. Run `$ wrangler dev --experimental-local` or `$ wrangler pages dev --experimental-local`
6. See an error in the terminal (see below)

### Expected Behavior

Do not strip `node:` since that is the modern syntax anyways but also because CloudFlare `nodejs_compat` needs it.

### Actual Behavior

```
✘ [ERROR] Could not resolve "util"

    build/index.js:19479:24:
      19479 │ import { inspect } from "util";
            ╵                         ~~~~~~

  The package "util" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.

```

**Comment by ivogt** [comment]
I am also looking for solution on this. We also can't use `node:async_hooks` which gets replaced with notimplemented stub.
Same thing applies to 1.16 .

Any option to work around this problem? Tries with remix-esbuild-override and separating AsyncLocalStorage in another package(re-export) but still no luck.

**Comment by jfsiii** [comment]
I didn't realize Remix was altering the `import`s but here's how we're using `compatibility_flags = [ "nodejs_compat" ]` and `remix-esbuild-override`


```
  withEsbuildOverride((option) => {
    if (option.bundle) {
      option.external = ['node:async_hooks'];
    }
```

**Comment by markdalgleish** [comment]
@jasonkuhrt The original issue when importing `node:util` seems to have already been fixed. If you upgrade your project and you're still having issues, let me know.

@ivogt @jsfiii The latest version of Remix doesn't polyfill `node:async_hooks` anymore (along with any other unimplemented polyfills). If you upgrade your project, your issue should be fixed too.

Also note that Remix v1.19.0 added a new `serverNodeBuiltinsPolyfill` option that gives you more fine-grained control over polyfills: https://github.com/remix-run/remix/releases/tag/remix%401.19.0

**Comment by jfsiii** [comment]
@markdalgleish Thanks for the ping here as well as the code to fix it in the first place. We upgraded to 1.19.0 a little while ago and can confirm it worked as advertised/expected.

**Comment by huseeiin** [comment]
this is still happening:

```
✘ [ERROR] Could not resolve "crypto"

    ../node_modules/@remix-run/node/node_modules/cookie-signature/index.js:5:21:
      5 │ var crypto = require('crypto');
        ╵                      ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.


✘ [ERROR] Could not resolve "stream"

    ../node_modules/stream-slice/index.js:3:24:
      3 │ var Transform = require('stream').Transform;
        ╵                         ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
```
