### ISSUE TITLE
[Feature]: Using const instead of let

### ISSUE THREAD

**Issue by Angelfire** [remix-run/remix#596]
### What is the new or updated feature that you are suggesting?

I've seen many examples in the documentation use patterns like this: 

```jsx
import { useLoaderData } from "remix";

export let loader = () => {
  return [
    {
      slug: "my-first-post",
      title: "My First Post"
    },
    {
      slug: "90s-mixtape",
      title: "A Mixtape I Made Just For You"
    }
  ];
};

export default function Posts() {
  let posts = useLoaderData();

  return (
    <div>
      <h1>Posts</h1>
    </div>
  );
}
```

And I still can't understand why not use `const` instead of `let`

### Why should this feature be included?

I don't see that in any case the `posts` variable is updated or re-declared and neither does the `loader` function. Probably I'm missing something...

**Comment by Angelfire** [comment]
I didn't mean it in the performance sense, it's for "security" to prevent the variable from being re-declared and this can eventually break everything... But yes, it is valid to use let if it is only an example

**Comment by sergiodxa** [comment]
I have been using `let` only for a few months now, I have never had an issue, anyway if you prefer `const` keep using it, this is 100% personal preference

**Comment by ryanflorence** [comment]
You can use const. We don't 😇
