### ISSUE TITLE
Hydration Error when using AdSense AutoAds

### ISSUE THREAD

**Issue by mh4ck** [remix-run/remix#5962]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Implement the AdSense code into a project and enable AutoAds on the AdSense Platform

### Expected Behavior

It should ignore the added iframes and elements from AdSense

### Actual Behavior

The whole website switches to client rendering.
AdSense adding the following things on runtime: 

- script tag https://partner.googleadservices.com/gampad/cookie.js
- script tag https://pagead2.googlesyndication.com/pagead/managed/js/adsense/..
- html element to the bottom of the body for automated anchor ads i guess <ins class="adsbygoogle adsbygoogle-noablate" data-adsbygoogle-status="done" style="display: none !important;" data-ad-status="unfilled">[.. fulled with iframe and stuff]</ins>
- iframe to the bottom of the body <ins class="adsbygoogle adsbygoogle-noablate" data-adsbygoogle-status="done" data-anchor-status="displayed" style="..">[.. fulled with iframe and stuff]</ins>

**Comment by machour** [comment]
@mh4ck We are well aware of the hydration issues, and have several issues tracking those.
I also know that the React team have been looking into this.

I'm going to close this issue to avoid having multiple open issues for the same problem.
Thank you for taking the time to report this nonetheless  🙏🏼
