### ISSUE TITLE
Example of Flat Routes in V2 Documentation Incorrect

### ISSUE THREAD

**Issue by codeser** [remix-run/remix#5970]
### What version of Remix are you using?

1.5

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Go to:
https://remix.run/docs/en/main/pages/v2

### Expected Behavior

In example it says that:

routes
├── auth
│   ├── login.tsx
│   ├── logout.tsx
│   └── signup.tsx
├── public
│   ├── about-us.tsx
│   ├── contact.tsx
│   └── index.tsx
├── dashboard
│   ├── calendar
│   │   ├── $day.tsx
│   │   └── index.tsx
│   ├── projects
│   │   ├── $projectId
│   │   │   ├── collaborators.tsx
│   │   │   ├── edit.tsx
│   │   │   ├── index.tsx
│   │   │   ├── settings.tsx
│   │   │   └── tasks.$taskId.tsx
│   │   ├── $projectId.tsx
│   │   └── new.tsx
│   ├── calendar.tsx
│   ├── index.tsx
│   └── projects.tsx
├── auth.tsx
├── public.tsx
└── dashboard.calendar.$projectId.print.tsx

Should become:

routes
├── _auth.login.tsx
├── _auth.logout.tsx
├── _auth.signup.tsx
├── _auth.tsx
├── _public._index.tsx
├── _public.about-us.tsx
├── _public.contact.tsx
├── _public.tsx
├── dashboard._index.tsx
├── dashboard.calendar.$day.tsx
├── dashboard.calendar.$projectId._index.tsx
├── dashboard.calendar.$projectId.collaborators.tsx
├── dashboard.calendar.$projectId.edit.tsx
├── dashboard.calendar.$projectId.settings.tsx
├── dashboard.calendar.$projectId.tasks.$taskId.tsx
├── dashboard.calendar.$projectId.tsx
├── dashboard.calendar.index.tsx
├── dashboard.calendar.new.tsx
├── dashboard.calendar.tsx
├── dashboard.projects.tsx
└── dashboard.calendar.$projectId.print.tsx

But this seems wrong
Many of the dashboard.calendar should be dashboard.projects
eg
dashboard.calendar.$projectId._index.tsx
should be 
dashboard.project.$projectId._index.tsx

### Actual Behavior

dashboard.calendar.$projectId._index.tsx
should be 
dashboard.project.$projectId._index.tsx

**Comment by MichaelDeBoey** [comment]
This was fixed in dcff4e81
