### ISSUE TITLE
Remix deferred bug blocks page transition and loaders when doing big data fetches

### ISSUE THREAD

**Issue by janhesters** [remix-run/remix#5977]
### What version of Remix are you using?

1.15

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

The core issue, is that `defer` blocks the next page load, if the promise within `defer` consists of multiple fetches requests in a nested route.

**Note 1:** Maybe this is expected behavior, and I simply understand the feature poorly. If that's the case, would you please explain what is going on?

**Note 2:** [Here](https://github.com/janhesters/remix-deferred-tests) is an example repo. Let me still go into the code in this issue, too.

1. Create a new remix project. `npx create-remix@latest` (and optionally install axios, however the bug occurs with `fetch`, or any other SDK that makes API requests, too).
2. Add `routes/deferred-tests._index.ts`:
  ```ts
  import type { LoaderArgs } from '@remix-run/node';
  import { redirect } from '@remix-run/node';
  
  export const loader = async ({ request }: LoaderArgs) => {
    const url = new URL(request.url).pathname;
    return redirect(url + '/foo');
  };
  ```
3. Add `/routes/deferred-tests.tsx`
  ```ts
  import type { LoaderArgs } from '@remix-run/node'; // or cloudflare/deno
  import { defer } from '@remix-run/node'; // or cloudflare/deno
  import { Await, Outlet, useLoaderData } from '@remix-run/react';
  import { Suspense } from 'react';

  export const loader = async ({}: LoaderArgs) => {
    console.log('loading critical', new Date().toISOString());
    const critical = await new Promise(resolve =>
      setTimeout(() => resolve('hello'), 1000),
    );
    console.log('loaded critical', new Date().toISOString());
    const nonCricital = new Promise(resolve =>
      setTimeout(() => resolve('world'), 10_000),
      );

    return defer({ critical, nonCricital });
  };

  export default function PackageRoute() {
    const data = useLoaderData<typeof loader>();

    return (
      <main>
        <h1>Let's locate your package</h1>
        <p>{data.critical}</p>

        <Suspense fallback={<p>Loading package location...</p>}>
          <Await
            resolve={data.nonCricital}
            errorElement={<p>Error loading package location!</p>}
          >
            {nonCricital => <p>{nonCricital}</p>}
          </Await>
        </Suspense>

        <Outlet />
      </main>
    );
  }
  ```
4. Add `/routes/deferred-tests.foo.tsx`
  ```ts
    import type { LoaderArgs } from '@remix-run/node';
  import { json } from '@remix-run/node'; // or cloudflare/deno
  import { defer } from '@remix-run/node'; // or cloudflare/deno
  import { Await, Form, useLoaderData } from '@remix-run/react';
  import { Suspense } from 'react';
  import {faker} from '@faker-js/faker';
  import { myTest } from '~/features/my-feature.server';

  export const loader = async ({}: LoaderArgs) => {
    console.log('loading critical foo', new Date().toISOString());
    const critical = await new Promise(resolve =>
      setTimeout(() => resolve('hello'), 500),
    );
    console.log('loaded critical foo', new Date().toISOString());

    const nonCritical = myTest();
    console.log('non critical', nonCritical)

    const photos = await fetch('https://jsonplaceholder.typicode.com/photos')
    .then(response => response.json())
    
    console.log('deferring', new Date().toISOString())
    return defer({ critical, nonCritical, myThing: faker.helpers.arrayElement(photos).title });
  };

  export const action = async () => {
    return json({});
  };

  export default function PackageRoute() {
    console.log('rendering', new Date().toISOString())
    const data = useLoaderData<typeof loader>();
    console.log('data', data);

    return (
      <main>
        <h2>This is the second stage.</h2>
        <p>{data.critical}</p>
        <p>My thing {data.myThing}</p>

        <Suspense fallback={<p>Loading package location...</p>}>
          <Await
            resolve={data.nonCritical}
            errorElement={<p>Error loading package location!</p>}
          >
            {nonCritical => <p>{nonCritical[0].title}</p>}
          </Await>
        </Suspense>

        <Form method="post" replace>
          <button type="submit">Submit</button>
        </Form>
      </main>
    );
  }
  ```
5. Modify `routes/_index.tsx` and add a link to the `foo` page.
  ```ts
  <Link to="/deferred-tests/foo">
    What happens when you load?
  </Link>
  ```  
6. Lastly, create the `myTest` function and import it, e.g. from `/features/my-feature.ts`:
  ```ts
  import axios from "axios";

  export async function wait(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  export async function myTest() {
    console.log('clicked', new Date().toISOString());
    await wait(1000);
    console.log('waited 2 seconds');
    const unanswered = Array.from({ length: 200 }, () => ({
      question: 'foo',
    }));
    await Promise.all(
      unanswered.map(({ question }) =>
        // retrieveEmbeddingFromS3ByUrl(question.embeddingsUrl),
        axios.get('https://jsonplaceholder.typicode.com/photos'),
      ),
    );
    console.log('starting my test', new Date().toISOString());
    await wait(2000);
    console.log('waited 2 seconds once');
    await Promise.all([wait(2000), wait(2000)]);
    console.log('waited 2 seconds again');
    return [{title: 'loaded'}];
  }
  ```
In essence, `myTest()` simply fetches hundreds of times to simulate a big fetch load. (This could've also been a single fetch request that gets a big payload. If you comment out:

```ts
await wait(1000);
console.log('waited 2 seconds');
```

And navigate from the main page to the `deferret-tests/foo` page, you can notice a delay (about 4 seconds on my M1 pro).

Whereas when you leave that code in, the transition is pretty much instant.

Therefore, the fetches are somehow blocking the page transition.

### Expected Behavior

Stacking fetches (are doing one big fetch request), should NOT block `defer` from loading properly. It should still show the critical UI instantly, and only wait for the non critical UI.

### Actual Behavior

The `critical` data (and the loaders in general) are delayed because of the big fetches.

AFAIK this only happens with nested routes, in an `<Outlet />`.

Note, adding something like `await wait(50);` before firing the fetches fixes the issue, while `await wait(10);` is NOT enough.

**Comment by NavaceSystem** [comment]
Here's a related repro: https://codesandbox.io/p/sandbox/smoosh-pine-7kwtrn

Essentially defer acts as normal fully blocking when using useNavigate to move around the app. I hope this is a bug because I'm not sure how we would get SPA like experience with filtering data without using a host of client side stuff (which I don't want to do and hence picked remix).

**Comment by jacob-ebey** [comment]
This is actually expected behavior because you are navigating to a location where the routes are already on-screen. In this case, deferred data is buffered to avoid a flash of loading state. You can find a bit more info about when fallbacks happen here: https://remix.run/docs/en/1.19.2/guides/streaming#when-does-the-fallback-render

**Comment by janhesters** [comment]
@jacob-ebey Thank you for your answer.

Hmm, in the docs you linked it says:

> So just keep this in mind: Deferred is 100% only about the initial load of a route and it's params.

In my example, the route is loaded for the first time. So I don't get how this is expected behavior.

Could you please elaborate?

**Comment by alexbu92** [comment]
@janhesters any updates to this issue? Having the same.
