### ISSUE TITLE
`v2_routeConvention` ignores `ignoredRouteFiles` in v1.15

### ISSUE THREAD

**Issue by janhesters** [remix-run/remix#5983]
### What version of Remix are you using?

Remix v1.15

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Enable all `V2` features in your Remix conf. Make sure you define `ignoredRouteFiles` to exclude for example colocated test files.

```js
/* eslint-disable unicorn/prefer-module */

/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  future: {
    v2_routeConvention: true,
    v2_meta: true,
    v2_errorBoundary: true,
    v2_normalizeFormMethod: true,
    unstable_tailwind: true,
    // unstable_dev: true,
  },
  ignoredRouteFiles: ['**/*.test.{ts,tsx}'],
};
```

In `routes` create a route and a test file. E.g. `my-route.tsx` and `my-route.test.ts`. Now import test only tools in that test file, eg.:

```ts
import {
  afterAll,
  afterEach,
  beforeAll,
  describe,
  expect,
  test,
  vi,
} from 'vitest';

describe('My test', () => {
  test('this breaks remix 😭', () => {
    expect(1).toBe(1);
  })
});
```

### Expected Behavior

The app compiles and loads.

### Actual Behavior

When you load any normal route, they crash:

```
TypeError: (0 , import_vitest.beforeAll) is not a function
    at Object.<anonymous> (/Users/dev/remix-projects/remix-app/app/routes/my-route.test.ts:89:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /Users/dev/remix-projects/remix-app/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/Users/dev/remix-projects/remix-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jan/dev/summarai/remix-app/node_modules/express/lib/router/route.js:144:13)
```

**Comment by kiliman** [comment]
`v2` convention is using a library called `glob-to-regexp`. It doesn't work quite the same as a traditional glob. Instead of `**` just use a single `*` (Remix isn't passing the flag  `globstar: true`). Also, doesn't like the multi-extension pattern.

https://www.npmjs.com/package/glob-to-regexp

I was able to get it working by setting the pattern to:
```ts
ignoredRouteFiles: ["*/*.test.ts", "*/*.test.tsx"],
```

https://github.com/remix-run/remix/blob/1350cf501e6bf56590880bca76bd835c42b5e813/packages/remix-dev/config/flat-routes.ts#L80-L82

**Comment by janhesters** [comment]
This works! Thanks a lot @kiliman

**Comment by vegar** [comment]
Is it a bug, then, that the default `create-remix` template both add `v2_routeConvention: true` and `ignoredRouteFiles: ["**/.*"]` pr default?

Should the `ignoredRouteFiles` be updated?

**Comment by vegar** [comment]
@kiliman - One more thing: The `glob-to-regexp`-project seems to be both abandoned and archived. Do you know the reasoning for taking it into use for a v2_ feature?

**Comment by kiliman** [comment]
From what I can tell, it was part of some performance enhancements by @mcansh. Apparently, standard globs were slow for large route trees. However, to switch to this package that isn't compatible with the globs syntax and, as you point out, seems to be abandoned feels like a regression.
