### ISSUE TITLE
[Docs]: Update Jokes tutorial to use v2 route convention

### ISSUE THREAD

**Issue by thomasgauvin** [remix-run/remix#5986]
### What version of Remix are you using?

1.15

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix@latest`
2. Adjust the `app/root.tsx` file, create the `app/routes/jokes.tsx` file, create the `app/routes/jokes/index.tsx` file as documented in the App tutorial https://remix.run/docs/en/1.15.0/tutorials/jokes#routes
3. `npm i`, `npm run dev`

### Expected Behavior

![image](https://user-images.githubusercontent.com/35609369/229364231-70b336f2-a4b8-457f-88ad-af4d2ec37241.png)

### Actual Behavior

![Screenshot 2023-04-02 at 11 55 10 AM](https://user-images.githubusercontent.com/35609369/229364246-7e39787b-719c-41fb-87fb-772bdf308623.png)
![FsuBiW7XoAQH2cE](https://user-images.githubusercontent.com/35609369/229364300-9551bc56-4b5d-4e4a-89d8-ed92f08b56ed.png)
![FsuDMHXWAAAq4k7](https://user-images.githubusercontent.com/35609369/229364301-63e1a63d-6ffc-494e-9a25-cd3f1bbe7e4c.jpeg)
![FsuDJn1WIAIWP8b](https://user-images.githubusercontent.com/35609369/229364302-aa548ef9-10c1-4c85-b7f7-10d983957cab.jpeg)

**Comment by thomasgauvin** [comment]
Related https://github.com/remix-run/remix/issues/5216 https://github.com/remix-run/examples/issues/196

**Comment by thomasgauvin** [comment]
After doing some digging, seems that the `create-next-app` defaults to using the v2 route convention but the tutorial has not been updated. You can adjust by turning off v2_routeConvention in remix.config.js 

![Screenshot 2023-04-02 at 12 20 02 PM](https://user-images.githubusercontent.com/35609369/229365564-ac9abaf0-d25d-4789-ba5e-bafa1ddb9787.png)

**Comment by MichaelDeBoey** [comment]
This is done in #6050
