### ISSUE TITLE
[Docs] - Preparing for v2 Doc on Site isn't rendering the `[ ]` brackets properly

### ISSUE THREAD

**Issue by superjose** [remix-run/remix#6002]
### What version of Remix are you using?

1.15

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Go to 
https://remix.run/docs/en/1.15.0/pages/v2#serverbuildtarget

Go to `serverBuildTarget`.
For every entry in the `serverMainFields` it should display an array, but it's instead displaying a string. 

I thought about opening a PR, but it's correct on the main [page](https://github.com/remix-run/remix/blob/main/docs/pages/v2.md)

Is the site rendering it wrong?

### Expected Behavior

`serverMainFields` property should display an array and is displaying a string instead.

![image](https://user-images.githubusercontent.com/8230270/230053990-4751c653-3b64-4461-8fe5-c1acc267efb9.png)

### Actual Behavior

`serverMainFields` should render an array.

**Comment by MichaelDeBoey** [comment]
This is now fixed
