### ISSUE TITLE
Typecheck for @remix-run/cloudflare-workers failure

### ISSUE THREAD

**Issue by kubens** [remix-run/remix#6010]
### What version of Remix are you using?

Latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create new Remix project, and run `npm run typecheck`:

`$  npx create-remix@latest`

```
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. 
Cloudflare Workers
? TypeScript or JavaScript? TypeScript
```

`$ npm run typecheck`

### Expected Behavior

Should not show errors

### Actual Behavior

It showing:

```
Found 44 errors in 4 files.

Errors  Files
     1  app/routes/_index.tsx:1
    27  node_modules/@cloudflare/workers-types/index.d.ts:4
     1  node_modules/@types/react/index.d.ts:2898
    15  node_modules/typescript/lib/lib.dom.d.ts:25
```

**Comment by AdiRishi** [comment]
I ran into this today too when setting up a new cloudflare pages project. Add the following to your `tsconfig.json` file
```json
{
    "exclude": ["node_modules"],
    "compilerOptions": {
        "skipLibCheck": true,
    }
}
```

**Comment by markdalgleish** [comment]
This should be fixed by https://github.com/remix-run/remix/pull/6925 which is due to go out in Remix v2.
