### ISSUE TITLE
Not documented changes in routing convention v2 between 1.13.0 and 1.15.0

### ISSUE THREAD

**Issue by lukejagodzinski** [remix-run/remix#6011]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've used Remix v1.13.0 with a new routing convention v2. And I had the following directories structure:

```
app/routes
├── _layout
│   ├── route.tsx
│   └── test
│       └── route.tsx
```

And going to /test displayed component from the `_layout/test/route.tsx` file inside the layout.
Now this is broken and to achieve the same effect I have to change structure to:

```
app/routes
├── _layout
│   └── route.tsx
├── _layout.test.tsx
```

I just can't nest my routes and have to keep the whole structure flat. Nothing was mentioned about that change in the release notes. Is it expected or is it a bug?

### Expected Behavior

I would assume that nesting routes should still work as it worked in 1.13.0.

### Actual Behavior

Nesting routes doesn't work anymore.

**Comment by mcansh** [comment]
the ability to nest before was a bug in the previous implementation

**Comment by lukejagodzinski** [comment]
I see. Thanks fror the clarification!
