### ISSUE TITLE
Unable to get custom error messaging from deferred promises in production

### ISSUE THREAD

**Issue by justinwaite** [remix-run/remix#6015]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a loader with a deferred promise that throws an error, with some error messages that you worked so hard to create 😄 
2. In your error element for `Await`, log out the error with `useAsyncError`
3. Test in dev and notice the error messages come through successfully
4. Test in prod and notice that all error messages are `Unexpected Server Error`

### Expected Behavior

I would expect that there would be a way to send _expected_ error messages from a deferred promise. In non-deferred data, you can throw a response instead of an error to get back custom messaging about errors. Throwing a response in a deferred promise causes `useAsyncError` to return undefined.

### Actual Behavior

The error message is always squashed to `Unknown Server Error`

**Comment by ahockersten** [comment]
This seems to reproduce whenever you throw from within any asynchronous `loader` function, not just when using `useAsyncError`. Here is an example repository that reproduces this:
https://stackblitz.com/edit/remix-run-remix-1dbxj8?file=app/routes/_index.tsx

Run `npm install && npm run build && npm run start` - you will see an empty "Application Error".

Run `npm install && npm run dev` - you will see the stack trace of the exception.

**Comment by justinwaite** [comment]
> This seems to reproduce whenever you throw from within any asynchronous `loader` function, not just when using `useAsyncError`. Here is an example repository that reproduces this:
> 
> https://stackblitz.com/edit/remix-run-remix-1dbxj8?file=app/routes/_index.tsx
> 
> 
> 
> Run `npm install && npm run build && npm run start` - you will see an empty "Application Error".
> 
> 
> 
> Run `npm install && npm run dev` - you will see the stack trace of the exception.

Yeah this is expected behavior. To get an error message across here, you can use an error boundary and throw a response (make sure to use v2 error boundary).

However if you are deferring data, and an error throws in that deferred promise, you cannot follow the same pattern. What you have to do instead is catch the error first, then return an object that specifies whether or or not the deferred promise succeeded. Then you have to branch your rendering logic inside Async to either render the happy path or the expected error. Unexpected errors will still be handled by the errorComponent prop on Async.

Essentially there is no built-in "CatchBoundary" to handle expected errors for deferred data.

**Comment by thomaswelton** [comment]
@justinwaite This is unrelated to this issue, but a follow up from your comment 

> Essentially there is no built-in "CatchBoundary" to handle expected errors for deferred data.

I'm migrating to use single fetch. And have a loader that makes an API request that may reject for non 200 responses, say a validation error for example.

Previously I could return this promise using `defer` and then get the error in my page component using `useAsyncValue` in the error fallback of `Await`
Now that defer is deprecated, if I return that promise in a bare object I get an unhandled promise rejection and the server crashes.

Are you saying that we can never allow a promise returned in a loader to reject? As this feels like what the `Await` component and `useAsyncValue` hooks are designed to handle.

Do you know of any documentation where this is specified, or examples of projects where this kind of error handling is done?
