### ISSUE TITLE
Unsupported errors when parallelizing promises with defer.

### ISSUE THREAD

**Issue by davidesigner** [remix-run/remix#6030]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Simplified demo code is here: https://gist.github.com/davidesigner/0e32db34d4308567e914184a2d67351f

### Expected Behavior

Parallelize api calls while supporting errors.

### Actual Behavior

- When api calls are not parallelized, errors are well caught.
- When parallelizing api calls, errors are not caught.
   ```shell
    UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<NodeResponse>
    ```

**Comment by jacob-ebey** [comment]
This should be fixed, please re-open or file a new issue if the problem persists.

**Comment by merthanmerter** [comment]
This still persists in v2.9.1

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

```
export async function loader({ request, params }: LoaderFunctionArgs) {
  const files = getFilesByParent(request, { parentId: params.id });
  // 👇 awaited promise should be the last one to get the full benefit of streaming
  const data = await getData(request, params);

  return defer({ data, files });
}
```
