### ISSUE TITLE
Use Inputmask plugin

### ISSUE THREAD

**Issue by jdnichollsc** [remix-run/remix#6033]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Installing Inputmask plugin https://github.com/RobinHerbots/Inputmask
- Try importing the library.

### Expected Behavior

Be able to use this browser library for masking inputs

### Actual Behavior

Output error:
> ReferenceError: navigator is not defined

It's weird because they are already validating if they can use the DOM: https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/canUseDOM.js
Like this other RemixJS example: https://remix.run/docs/en/1.15.0/guides/constraints#uselayouteffect

**Comment by mcansh** [comment]
a workaround for now is to lazy load inputmask in the use(Layout)Effect

```js
  React.useEffect(() => {
    async function load() {
      if (ref.current) {
        let { default: Inputmask } = await import("inputmask");
        console.log(Inputmask);
        let im = new Inputmask.default("999-999-9999");
        im.mask(ref.current);
      }
    }

    load();
  }, []);
```
