### ISSUE TITLE
Documentation for using defer() refers to wrong types & methods

### ISSUE THREAD

**Issue by tmcw** [remix-run/remix#6040]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Under "Alternatively, you can use the `useAsyncValue` hook:" [on the docs](https://remix.run/docs/en/1.15.0/guides/streaming#using-defer:~:text=Alternatively%2C%20you%20can%20use%20the%20%60useAsyncValue%60%20hook%3A), there's an example:

![CleanShot 2023-04-11 at 16 44 18@2x](https://user-images.githubusercontent.com/32314/231283858-37c0bdc6-e6b2-4cc9-be78-c26dadf38746.png)

Afaict, this is not quite right in a two different ways:

- There isn't a `SerializedFrom` type. There's only a `SerializeFrom` type (without the d)
- `useAsyncValue` is not generic, so it can't be given a type like this.

### Expected Behavior

This is just a documentation bug - the ideal behavior is for this example to compile

### Actual Behavior

- There is no export called SerializedFrom
- useAsyncValue gets one generic type when it should get zero

**Comment by machour** [comment]
@tmcw Thank you for helping making our documentation better 🙏🏼 
Should be fixed by #6243
