### ISSUE TITLE
Typings for createRemixStub should allow passing a regular loader

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#6054]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Do this:

```tsx
import { json, type DataFunctionArgs } from "@remix-run/node";
import { unstable_createRemixStub as createRemixStub } from "@remix-run/testing";

export async function loader(args: DataFunctionArgs) {
  return json({ hi: "there" });
}

createRemixStub([
  {
    path: "/example",
    loader,
  },
]);
```

Here's [a TypeScript Playground for this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKwM4QHYBo4wJ5gCmcAIgIYxkBiArhgMYzCYCCUA5qnAL5wBmUCCDgAiAAJRCIYAA8AtFDoB6DBAAmhEQG4AUKEixEcOqkoAjADaEA+vUkVCAJSmyAyjBpm4ZLncIPnaRl3Tx5+QWFxSSCFZRhCU2AMdm0dHUIZA3gfPAZ+OkZmDDgLCDINKAAKMg5UAC5SCmoCplZagEpEHTg4SQ8oYrRMSqQAC2AGkRhRwkkRHnbdbjS-AJdgjzNKgG1urp6esApRyaUMsnArESw9ntLy2Zue7huAXUWdIA)

### Expected Behavior

The types should be fine with this.

### Actual Behavior

You get the following error:

```
Type '(args: DataFunctionArgs) => Promise<TypedResponse<{ hi: string; }>>' is not assignable to type 'LoaderFunction'.
  Types of parameters 'args' and 'args' are incompatible.
    Type 'LoaderFunctionArgs' is not assignable to type 'DataFunctionArgs'.
      Property 'context' is optional in type 'LoaderFunctionArgs' but required in type 'DataFunctionArgs'.
```

**Comment by mcansh** [comment]
this is due to actually using React Router's MemoryRouter under the hood, where the types don't match because of RR not having a `context`.

the current workaround is
```js
loader: args => loader({...args, context: {}}),
```

but i'll take a look at patching that in the testing helpers :)

**Comment by kentcdodds** [comment]
Thanks!

**Comment by sergiodxa** [comment]
@mcansh maybe accept `AppLoadContext` in `createRemixStub` as a second and optional argument
```ts
import { json, type DataFunctionArgs } from "@remix-run/node";
import { unstable_createRemixStub as createRemixStub } from "@remix-run/testing";

export async function loader(args: DataFunctionArgs) {
  return json({ hi: "there" });
}

let context: AppLoadContext = { /* something here that match your AppLoadContext */ }

createRemixStub(
  [{ path: "/example", loader }],
  context
);
```
