### ISSUE TITLE
After deploying to the vercel, my remix app is only returning a white screen, even though it is working fine on localhost.

### ISSUE THREAD

**Issue by alikhantareen** [remix-run/remix#6091]
### What version of Remix are you using?

1.41.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have deployed the remix app on vercel and it was working fine. Recently, a couple of days ago, I pushed some changes to the main and the app hosted on to the vercel is only returning a white screen now. Routes are not working either. While, everything is working fine on localhost

### Expected Behavior

App should work on vercel like it is working on the localhost

### Actual Behavior

The app is displaying a white screen on vercel

**Comment by MichaelDeBoey** [comment]
Closing in favor of #6092
