### ISSUE TITLE
Meta v2 does not work with MDX pages

### ISSUE THREAD

**Issue by bndkt** [remix-run/remix#6101]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix app with Meta v2 enabled (v2_meta: true)
2. Creare an MDX route with meta data in the frontmatter (https://remix.run/docs/en/1.15.0/guides/mdx#routes)
3. Get error: "Error: The `v2_meta` API is enabled in the Remix config, but the route at ... returns an invalid value. In v2, all route meta functions must return an array of meta objects."

### Expected Behavior

If `v2_meta: true` is enabled in config, MDX routes should output meta from frontmatter using the v2 Meta format

### Actual Behavior

MDX routes seem to use v2 meta format regardless of feature flag

**Comment by dihamilton** [comment]
I came across this issue too with a fresh install - with some help from Discord I realised that the way of specifying meta properties has changed to array format in v2, so the following adaptation of the first example from the MDX Guide works for me:

```---
meta:
  - { title: My First Post }
  - { description: Isn't this awesome? }
headers:
  Cache-Control: no-cache
---

# Hello Content!
````

While https://remix.run/docs/en/main/pages/v2 does mention the change to using an array, it doesn't mention how that affects markdown routes. The best fix that could have helped me would be to:

- Update https://remix.run/docs/en/1.15.0/guides/mdx#routes to include v2 compatible examples.
- Update https://remix.run/docs/en/main/pages/v2 to mention how markdown routes need to change the way meta is specified in front matter.

**Comment by bndkt** [comment]
Hah, good catch @dihamilton, I didn't realize that you could just adjust the frontmatter to match the v2 meta format.

I would still question whether this is the way recommended by the Remix team because it sure looks a bit awkward. Wouldn't the more elegant solution be to leave the frontmatter as is and tweak the mapping that Remix does between MDX frontmatter and Remix meta data?

**Comment by ryanflorence** [comment]
[Docs show the correct way to do it](https://remix.run/docs/en/main/guides/mdx#routes).

The old mapping limited valid use cases, I agree the new way is more verbose, but it's also the precise meta tags you're adding instead of a Remix specific API, it's just HTML tags as a YAML.
