### ISSUE TITLE
v2_routeConvention breaks splat route and optional segment

### ISSUE THREAD

**Issue by Grandnainconnu** [remix-run/remix#6105]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

(You can execute `npm create @shopify/hydrogen@latest` and edit the `$.tsx` route with some logging, to see that it never reach)

Route architecture:

```
$.tsx
($lang).$shopId.orders.$token.authenticate.tsx
($lang)._index.tsx
($lang).account.activate.$id.$activationToken.tsx
($lang).account.login.tsx
($lang).account.recover.tsx
($lang).account.register.tsx
($lang).account.reset.$id.$resetToken.tsx
($lang).account.tsx
($lang).account_.address.$id.tsx
($lang).account_.edit.tsx
($lang).account_.logout.ts
($lang).account_.orders.$id.tsx
($lang).account_.orders.tsx
($lang).api.countries.tsx
($lang).api.newsletter.tsx
($lang).api.products.tsx
($lang).api.search.tsx
($lang).blog.$handle.tsx
($lang).blog._index.tsx
($lang).cart.tsx
($lang).catalogue.$collectionHandle.tsx
($lang).catalogue.bientot._index.tsx
($lang).catalogue.bientot.produits.$productHandle.tsx
($lang).catalogue.marques.$handle.tsx
($lang).catalogue.produits.$productHandle.tsx
($lang).catalogue.quadricycles.tsx
($lang).discount.$code.tsx
($lang).faq.tsx
($lang).qui-sommes-nous.tsx
($lang).recherche.tsx
($lang).resource.comment-choisir-sa-taille-de-velo.tsx
($lang).resource.comment-recycler-une-batterie-de-mobilite-electrique.tsx
($lang).resource.mon-empreinte-transport.tsx
($lang).resource.quizz-mon-empreinte-climat.tsx
($lang).resources-outils.tsx
($lang).subventions.$grantHandle.tsx
($lang).subventions._index.tsx
($lang).tsx
($lang)_.panier._index.tsx
($lang)_.panier.accessoires.tsx
($lang)_.panier.recapitulatif.tsx
($lang)_.panier.services.tsx
($lang)_.panier.tsx
[robots.txt].tsx
[sitemap.xml].tsx
```

`($lang).tsx` being a layout, `($lang).account.tsx` being a layout, `($lang)_.panier.tsx` being a layout

### Expected Behavior

`/anything` should match the `$.tsx` file 

### Actual Behavior

The `$.tsx` file is never reached, containing redirections for old routes before moving our website to remix

**Comment by kiliman** [comment]
The issue is that the splat route has the lowest priority. Because you have optional prefixes, those match before the splat route can handle it.

I suggest you handle the redirects from old to new routes *before* you hand it off to Remix. If you're using Express, you can do this from the server.js file.

**Comment by machour** [comment]
More precisely, your `/anything` request gets matched by `($lang)._index.tsx` or `($lang).tsx`

You could either follow @kiliman suggestion, or consider that one of the above files is your splat route (not sure which one get picked without trying).
