### ISSUE TITLE
Don't treat a route as a resource route if it only has an ErrorBoundary

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/remix#6106]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```jsx
import {
  Outlet,
  isRouteErrorResponse,
  useRouteError,
} from "@remix-run/react";

// this is required to make this a UI route, but we should be able to 
// default to this if no default is exported but a boundary is
// export default Outlet;

export function ErrorBoundary() {
  let error = useRouteError();
  // ...
}
```

### Expected Behavior

Any route exporting a default component, `ErrorBoundary`, or `CatchBoundary` is considered a UI route.

### Actual Behavior

Only routes exporting a default component are considered a UI route.

**Comment by kiliman** [comment]
Interesting. I wonder what scenarios you would want to export an `ErrorBoundary` but not a `default` UI component.

To me, I think it should be an error.

**Comment by brophdawg11** [comment]
The use-case I've seen is a singular top level error boundary in a pathless route below root - so it can still access valid loader data from the root loader (i18n info, etc.).  I think that might be the use-case Ryan was doing when he ran into it today.
