### ISSUE TITLE
Bug: Safari 14.1 - Unsupported operation when submitting multipart form

### ISSUE THREAD

**Issue by jstoone** [remix-run/remix#6117]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### About
I have created a new project using the indie stack and changed only the bare minimum, as to reproduce the bug. You can see the diff here: https://github.com/jstoone/remix-safari-multipart-form-bug/pull/1/files

### Requirements
- Safari 14.1 on Big Sur
   - **_I can supply BrowserStack users for one or two maintainers, if that's needed :v:_**

### Reproduce via repository
Clone the repository, and checkout branch with reproducible code:
```
git clone https://github.com/jstoone/remix-safari-multipart-form-bug --branch reproduce-bug
```

Change directory and install node modules:
```
cd remix-safari-multipart-form-bug && npm install
```

### Steps
1. Create user - http://localhost:3000/join
2. Create note - http://localhost:3000/notes/new 
3. Write note name
4. Select whichever file
5. Write description
6. Submit form

### Expected Behavior

I expected a new note to be created, regardless of whether I have selected a file or not.

### Description
Having filled out the form, and pressing "Save", the submission fails, and never reaches the Action:
1. The browser displays a stack trace
2. The console displays a `"NotSupportedError: The operation is not supported"" in console

_If the user does NOT select a file, the form will successfully save the note._

<details>
<summary>
Stacktrace:
</summary>

```
formData@ [native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:7842:159
asyncFunctionResume@[native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:8051:35
asyncFunctionResume@[native code]
runHandler@https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:3635:33
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:3667:32
asyncFunctionResume@[native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRRZ7F0Q.js:2741:40
asyncFunctionResume@[native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:2685:44
asyncFunctionResume@[native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRRZ7F0Q.js:2617:33
asyncFunctionResume@[native code]
https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:5351:23
submitHandler@https://good-tape.eu.ngrok.io/build/_shared/chunk-DRZ7F0Q.js:5626:15
callCallback2@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:3578:27
dispatchEvent@[native code]
invokeGuardedCallbackDevahttps://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js: 3603:37
invokeGuardedCallback@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:3637:44
invokeGuardedCallbackAndCatchFirstError@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:3640:38
executeDispatchahttps://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:6675:50
processDispatchQueueItemsIn0rder@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.is:6695:30
processDispatchQueue@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:6704:45
dispatchEventsForPlugins@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:6712:31
batchedUpdates$1@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.is:18412:22
batchedUpdates@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:3483:38
dispatchEventForPluginEventSystem@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:6835:25
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay@https://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:5166:46
dispatchEventahttps://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:5160:92
dispatchDiscreteEventahttps://good-tape.eu.ngrok.io/build/entry.client-AIWHXX37.js:5137:26
dispatchDiscreteEvent@[native code]
```
</details>

### Screenshots
> Stacktrace without error boundry, as seen in the collapsable summary above:

![image](https://user-images.githubusercontent.com/1711456/233421433-3b81bd21-104e-430d-9dfb-9eff32a4d216.png)

> Stacktrace/error from the developer console

![image](https://user-images.githubusercontent.com/1711456/233421752-461959c5-07c0-4db2-9d25-525384c88cec.png)

**Comment by jstoone** [comment]
I've wanted to move towards using streams more for our audio processing, so I've made a working example here, where the user submits an octet-stream via XMLHttpRequest and the action then wraps the `request.body` in a NodeJS Readable, which can be passed directly to `fluent-ffmpeg`.

If anyone's interested in this approach I've created another branch with a sample implementation:
-> https://github.com/jstoone/remix-safari-multipart-form-bug/pull/2

Having the above solution, means that I am no longer blocked on the above, but please don't hesitate letting me know if there's anything I can do to help debug the issue. I'm up for pairing if that's needed. :v:

**Comment by brophdawg11** [comment]
I can't reproduce this on OSX Ventura 13.5, Safari 16.6, so it seems like it may be an issue in that specific Safari version?  I'm unsure if Remix can do much to address this without more information on exactly what's failing on file uploads on Safari 14.

If you are able to track down any more information about what's causing this failure in Safari 14 we'd definitely accept a PR or guidance on if there's an underlying issue in Remix code.

**Comment by jstoone** [comment]
Definitely a Safari thing, and to be honest, don't think it's worth spending a lot of time on, as I can only imagine that it's going to be a path full of misleading rabbit holes.

So the reward to time spent ratio, is not looking great for this. And since I'm the only one (that I've seen) who's noticed this, I'm going to self-close, until something similar pops up.

But please don't hesitate reaching out or pinging me, if this bug or similar pops up again, and I'll gladly help debug and (co-)author a PR. ❤️
