### ISSUE TITLE
Node 20: Running any remix app returns TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by JacobJEdwards** [remix-run/remix#6118]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- run npx create-remix@latest
- my-remix-app
- Just the basics
- Remix App Server
- Typescript
- Yes
- cd my-remix-app
- npm run dev

### Expected Behavior

localhost:3000 shows initial remix screen

### Actual Behavior

Remix App Server started at http://localhost:3000 (http://192.168.1.82:3000)
TypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.set (node:internal/url:519:13)
    at Proxy.<anonymous> (/Users/jacobedwards/my-remix-app/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/jacobedwards/my-remix-app/node_modules/@remix-run/express/dist/server.js:57:17)
    at createRemixRequest (/Users/jacobedwards/my-remix-app/node_modules/@remix-run/express/dist/server.js:71:14)
    at /Users/jacobedwards/my-remix-app/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/jacobedwards/my-remix-app/node_modules/@remix-run/serve/dist/index.js:47:7
    at Layer.handle [as handle_request] (/Users/jacobedwards/my-remix-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jacobedwards/my-remix-app/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/jacobedwards/my-remix-app/node_modules/express/lib/router/route.js:140:7)
GET / 500 - - 100.150 ms

**Comment by nicksrandall** [comment]
I just ran into this when trying to upgrade to node v20.

**Comment by silas** [comment]
I fixed this for my project by updating to [@remix-run/web-fetch^4.3.4](https://www.npmjs.com/package/@remix-run/web-fetch^4.3.4) (see https://github.com/remix-run/web-std-io/pull/32)

**Comment by TheGreatAxios** [comment]
> 

For others who will run into this issue, additional confirmation that bumping to Node 20.0.0 results in this error

**Comment by machour** [comment]
@JacobJEdwards can you confirm that this a node 20 related issue?

**Comment by m5r** [comment]
I can confirm it happens with node 20 and not with node 18

**Comment by machour** [comment]
This should be fixed in 1.16.0, please reopen if this is still an issue!

**Comment by rajeshdavidbabu** [comment]
Can confirm that updating to 1.16.0 fixed it !

**Comment by NavaceSystem** [comment]
@machour I'm getting this on Node 20 after upgrading to v2. Could it have resurfaced?

**Comment by nhd2106** [comment]
1.16.0 fixed my problem too

**Comment by felangel** [comment]
I'm still seeing this issue using node 20 and remix 2.12.0

**Comment by toptal-dave** [comment]
I just saw this in Node 20 and Remix 2.11.1

**Comment by kiliman** [comment]
Are you calling `installGlobals({ nativeFetch: true })`

https://github.com/remix-run/remix/blob/main/CHANGELOG.md#undici

**Comment by machour** [comment]
@felangel @toptal-dave If this is still an issue for you, especially after reviewing @kiliman comment, please open a new issue with a reproduce case 🙏🏼
