### ISSUE TITLE
Observed an unusual scrolling issue with a screening effect on Mac Safari aswell as Chrome.

### ISSUE THREAD

**Issue by vishwajeetsinh7** [remix-run/remix#6127]
### What version of Remix are you using?

-

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[](url)

https://user-images.githubusercontent.com/75626747/233609148-497150d8-6323-4ca6-8078-22dafd5b732a.mov

### Expected Behavior

.

### Actual Behavior

<img width="1440" alt="Screenshot 2023-04-21 at 3 35 52 PM" src="https://user-images.githubusercontent.com/75626747/233609376-5c117e78-f576-4c91-8529-4a23ce83ef2f.png">

**Comment by machour** [comment]
Logged this on the private repo for the remix website, thanks!
