### ISSUE TITLE
loader vs action v2 Error Boundary

### ISSUE THREAD

**Issue by fatbattk** [remix-run/remix#6139]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Form `POST` to route vs `GET` route shows different error UI.

```ts
// simplified example.
export const loader = ({ request }: ActionArgs) => {
  throw new Response('Invalid request', { status: 403 });
};

export const action = ({ request }: ActionArgs) => {
  throw new Response('Test Error', { status: 403 });
};
```
Only the `action` throw uses the v2 `ErrorBoundary` component in root (although page HTTP code is `200`?).

### Expected Behavior

Both uses the same `ErrorBoundary` component.
![image](https://user-images.githubusercontent.com/1505013/233771221-41958dcb-174b-4606-9e97-b5fcee49fa05.png)

### Actual Behavior

Plain text response with HTTP status code.
![image](https://user-images.githubusercontent.com/1505013/233770841-6d774024-0f9c-4d6d-928c-e1f153e89a41.png)

**Comment by sergiodxa** [comment]
Does your route has a component? Or only a loader and action?

If a route doesn’t have a default export with a component it will be considered a resource route, if you send a GET to a resource route you get what the loader returns/throws without error boundaries handling thrown values.

**Comment by fatbattk** [comment]
Ah, thank you, the file did not have a component and is a [resource route](https://remix.run/docs/en/main/guides/resource-routes).
This feels like something that should be noted in the [ErrorBoundary docs](https://remix.run/docs/en/main/route/error-boundary-v2). Or is this mentioned elsewhere?

**Comment by machour** [comment]
Closing as this was not an issue.
