### ISSUE TITLE
Transitive Dependency Using Long-Deprecated Rollup Plugin

### ISSUE THREAD

**Issue by shellscape** [remix-run/remix#6144]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Hey folks. Just stopping by to let you know that the `css` package is using a rollup plugin by way of a transitive dependency, which has been deprecated for more than **3 years**, technically relies on a very old version of Rollup, and hasn't received any updates in as long.

```
→ pnpm why rollup-plugin-inject
Legend: production dependency, optional only, dev only

dependencies:
@remix-run/css-bundle 1.15.0
└─┬ @remix-run/dev 1.15.0
  └─┬ @esbuild-plugins/node-modules-polyfill 0.1.4
    └─┬ rollup-plugin-node-polyfills 0.2.1
      └── rollup-plugin-inject 3.0.2
```

`rollup-plugin-node-polyfills` has been stale for 4 years

`rollup-plugin-inject` has been stale and deprecated for 3 years

It might be worthwhile to fork https://github.com/remorses/esbuild-plugins to maintain the plugin you're using there, or roll your own using one of the more updated community node-builtins alternatives https://www.npmjs.com/search?ranking=maintenance&q=rollup%20node

I come to you as the rollup plugins lead maintainer, so I hope you'll take this report in earnest. 

### Expected Behavior

n/a

### Actual Behavior

n/a

**Comment by MichaelDeBoey** [comment]
We switched to using `esbuild-plugin-polyfill-node` in #5274, so you won't see the deprecation warnings once we release the next version

**Comment by shellscape** [comment]
Bueno
