### ISSUE TITLE
v2 routing splat route doesn't catch _index.(tsx|jsx) and neither does remix

### ISSUE THREAD

**Issue by outofthisworld** [remix-run/remix#6148]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. npx create-remix-app@latest
2. create $.(tsx|jsx) file in /routes
3. export a loader from $.(tsx|jsx) and throw a 404 response.

Code:
```jsx

import type { LoaderArgs } from "@remix-run/node";

export function loader({ request }: LoaderArgs) {
  throw new Response("Not found", { status:404 });
}
```

4. Create an error boundry at root.(tsx|jsx)
```jsx
export function ErrorBoundary() {
  const error = useRouteError() as { message?: string } | undefined | null;
  // when true, this is what used to go to `CatchBoundary`
  if (isRouteErrorResponse(error)) {
    return (
      <div>
        <h1>Oops</h1>
        <p>Status: {error.status}</p>
        <p>{error.data.message}</p>
      </div>
    );
  }

  // Don't forget to typecheck with your own logic.
  // Any value can be thrown, not just errors!
  let errorMessage = "Unknown error";
  if (error?.message) {
    errorMessage = error.message;
  }

  return (
    <div>
      <h1>Uh oh ...</h1>
      <p>Something went wrong.</p>
      <pre>{errorMessage}</pre>
    </div>
  );
}
```

5. In browser, render index route or '/' route.

Only reason I noticed this because I have a unique use case in which I don't need to have an index page. But also, i'd like to display a custom component when a 404 occurs. Only thing I can do now is either return a string with `new Response('xxx', {status:400})` or use `redirect('/some/unfound.route')`  so ErrorBoundry is actually hit.

### Expected Behavior

I would expect that either remix picks up that there's no index page, or the splat route would.

### Actual Behavior

In browser, render / route. Blank page is shown. Not picked up by splat or remix.

**Comment by kevinbailey25** [comment]
If you don't have a default export in your $ route, Remix thinks it's a resource route. So it just throws a 404 with no UI. If you want to have it end your ErrorBoundary, you need to put an empty default export in your $ route. So Remix knows you want to render UI. 

I do this pattern all the time. 

```tsx
export const loader = () => {
   throw new Response('Not found.', { status: 404 })
}

export default function Foo(){
   return <></>
}
```

**Comment by machour** [comment]
@kevinbailey25 is totally correct here

**Comment by outofthisworld** [comment]
I see okay - that makes a lot of sense. Thanks @kevinbailey25 @machour will close this as an issue.
