### ISSUE TITLE
Security Issue by @remix-run/dev with vulnerabilities by packages dependencies

### ISSUE THREAD

**Issue by dmitry-bret-iits** [remix-run/remix#6162]
### What version of Remix are you using?

@remix-run/dev - 1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

With `npm audit` i have follow vulnerabilities:

### vm2 vulnerable to sandbox escape   
Package: vm2   
Patched: in >=3.9.15
Dependency of @remix-run/dev
Path: @remix-run/dev > proxy-agent > pac-proxy-agent > pac-resolver > degenerator > vm2 
More info: https://www.npmjs.com/advisories/1091646

### http-cache-semantics vulnerable to Regular Expression Denial of Service
Package: http-cache-semantics
Patched: in >=4.1.1
Dependency of @remix-run/dev
Path: @remix-run/dev > xdm > got > cacheable-request > http-cache-semantics
More info: https://www.npmjs.com/advisories/1091807

 

### Expected Behavior

The critical and high dependencies are updated.

### Actual Behavior

The critical and high dependencies are not updated.

**Comment by mcansh** [comment]
we've been dealing with these recently and i'm happy to say on `1.16-pre.2` running `npm audit` returns `found 0 vulnerabilities` 🎉

**Comment by dmitry-bret-iits** [comment]
Hi @mcansh Thanks :)

**Comment by machour** [comment]
1.16.0 is out 🎉
