### ISSUE TITLE
[Bug]: Wrong error messages in error boundary demo

### ISSUE THREAD

**Issue by Schwefelhexa** [remix-run/remix#625]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.5

### Steps to Reproduce

1. Create a new project using `create-remix@latest`
2. Visit `http://localhost:3000/demos/params/shh-its-a-secret`

### Expected Behavior

An error message along the lines of

> Looks like you tried to visit a page that you do not have access to.
> Maybe ask the webmaster (hello@remix.run) for access.

should appear.

### Actual Behavior

The fallback error

> There was a problem with your request!
> 401 Unauthorized

is shown.

**Comment by machour** [comment]
Fixed by #611
