### ISSUE TITLE
Remix 1.16.0 new dev server prematurely exits incorrectly

### ISSUE THREAD

**Issue by aniravi24** [remix-run/remix#6268]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Run the dev server with the future flag in remix.config.js and run `remix dev` (and optionally run with a custom command `-c` flag).

```
future: { unstable_dev: true }
```

### Expected Behavior

Properly detect dependencies at the root of a monorepo. and also handle custom commands without expecting `@remix-run/serve` to be present.

### Actual Behavior

Two separate issues:
1. The detection of `@remix-run/serve` within a pnpm nx monorepo setup doesn't work correctly. My project has a single package.json at the root of the workspace and my app lives under a directory like `packages/remix-app`. When I comment out the code below that causes the exit, it runs perfectly fine, so I know it's a detection issue.
2. When a custom command is passed in, it exits if it fails to detect `@remix-run/serve` because it appears to ignore the custom command for some reason (possible that it's somehow not getting passed in, but it looks like I am).

Lines of code causing the issue are here:
https://github.com/remix-run/remix/blob/main/packages/remix-dev/cli/commands.ts#L543

**Comment by pcattori** [comment]
@aniravi24 can you elaborate about (2)? What error are you seeing?

**Comment by aniravi24** [comment]
> @aniravi24 can you elaborate about (2)? What error are you seeing?

Seems like it might be caused by Nx actually, cause running `npx remix dev` with the `-c` flag is working correctly. Doing more investigation!

**Comment by danestves** [comment]
I'm getting a similar error, after I make a refresh of the page, the web sockets just exit and doesn't connect anymore, I need to restart the server, and also the HMR doesn't work, I guess is because the web socket disconnects after that 

![](https://user-images.githubusercontent.com/31737273/235558166-e2bcba75-9beb-42b1-badc-54938f54e902.png)

**Comment by aniravi24** [comment]
> @aniravi24 can you elaborate about (2)? What error are you seeing?

Looks like it did have something to with Nx, it no longer happens. I fix the first problem now by passing in `remix-serve build` manually with the `-c` flag, which is fine.

**Comment by pcattori** [comment]
Ok so (2) is purely an NX thing. But (1) should still work out of the box for `pnpm`, so that's still a bug that should be fixed.

**Comment by pcattori** [comment]
@aniravi24 does running `pnpm list` from the root of your project _and_ from `packages/remix-app` show `remix-serve` as a dependency?

**Comment by aniravi24** [comment]
> @aniravi24 does running `pnpm list` from the root of your project _and_ from `packages/remix-app` show `remix-serve` as a dependency?
> 
> Trying to determine a reliable way to detect if `remix-serve` is installed in a `pnpm` project.

I do see `@remix-run/serve` when running `pnpm list` from the root of my monorepo, not from inside `packages/remix-app` though because no packages are listed inside of there, and I don't use `pnpm` workspaces.

I have a single package.json at the root of my monorepo to manage dependencies for all projects that live under `packages/`.

I don't think this is a pnpm specific problem (but I mentioned it just for context), as I could imagine my setup with yarn or npm would probably would exhibit the same behavior, since I'm not using the workspaces functionality of any package manager to manage my packages.

**Comment by rodbs** [comment]
I have the same issue with Remix 1.16.1 in a pnpm monrepo (without Nx)
`Error: remix dev is not supported for custom servers.`
Is there a way to fix it? thx

**Comment by pcattori** [comment]
@rodbs the old dev server (`unstable_dev` disabled) does not support custom servers. So if you are using a custom `server.js` (or whatever you have set as `serverEntryPoint` in your `remix.config.js`), you can't use `remix dev`. The alternate setup for legacy dev server is to use `remix watch` instead for live reload.

If on the other hand, you have `unstable_dev` enabled, then that would be a bug in Remix.

**Comment by rodbs** [comment]
@pcattori Thanks, I had `unstable_dev` disabled. When enabling it, it works!!
