### ISSUE TITLE
Remix 1.16 `unstable_dev` - problems with assets

### ISSUE THREAD

**Issue by ArekBartnik** [remix-run/remix#6271]
### What version of Remix are you using?

1.16

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `git clone git@github.com:ArekBartnik/remix-116-dev-assets.git`
2. `npm i`
3. `npm run dev`
4. go to `http://localhost:3000`

### Expected Behavior

It should show a page using Inter font and an icon after "Welcome to Remix".

| With `unstable_dev: true;` | Without `unstable_dev: true`|
|-|-|
|<img width="367" alt="image" src="https://user-images.githubusercontent.com/1569446/235552660-5c15b7d8-7f1f-437d-9607-194e90fdb1cf.png">| <img width="338" alt="image" src="https://user-images.githubusercontent.com/1569446/235552713-c59feb2b-2bad-4dc6-90cd-8135087be80f.png">|

Without new devserver paths to assets are relative but after turning this flag they change to absolute.

### Actual Behavior

There're 2 errors:
- for the fonts -> 404 `http://localhost:3001/fonts/InterV.var.woff2 net::ERR_ABORTED 404 (Not Found)`
- for the svg icon -> `Unsafe attempt to load URL http://localhost:3001/build/_assets/document-QP6N4QKU.svg from frame with URL http://localhost:3000/. Domains, protocols and ports must match.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/1569446/235552816-668a7c90-5461-41e5-983a-6ce2a11f233d.png">

**Comment by mikeybinns** [comment]
Just to note I'm also receiving the same "Domains, protocols and ports must match." error, and 404 errors on objects in the public folder (like fonts).

**Comment by pcattori** [comment]
@ArekBartnik unfortunately there is [no way for `<use/>` `href` to participate in CORS](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#usage_notes).

The alternative would be to proxy everything from our dev server, but that would require rearchitecting parts of the dev server. I'm happy to consider doing that, but that will take longer. In the meantime, inlining via Data URLs does the job.

**Comment by ArekBartnik** [comment]
@pcattori  I would like to understand why it was decided to serve files from a different origin? I think it's could be especially painful because "production" will be different (most assets are relative.)

**Comment by ArekBartnik** [comment]
@pcattori I've checked and svgs as dataulrs are blocked in Safari. Works in Chrome and Firefox. Here's a pen https://codepen.io/arekbartnik/pen/QWZqXzJ

**Comment by pcattori** [comment]
@ArekBartnik after some more thought, I realized that serving the assets from the dev server doesn't actually help all that much for making HMR faster (for complicated reasons I won't bring up here). Which means that the original purpose of serving assets from dev server is obsoleted. Going to think about this a little more, but leaning towards just serving everything from the app server. Simpler, more similar to prod, and only one domain, so no CORS or cross-domain shenanigans.

**Comment by pcattori** [comment]
Related: https://github.com/remix-run/remix/pull/6306
