### ISSUE TITLE
make DataLoader a generic to ensure the return type of loader is what you expect

### ISSUE THREAD

**Issue by mcansh** [remix-run/remix#63]
similar to how in next.js, `GetServerSideProps` is a generic, I think it would be helpful if `DataLoader` was also a generic to ensure what you return from a loader is what you expect, similarly it would be beneficial to also allow a custom Context type.

here's my patch-package diff

```diff
diff --git a/node_modules/@remix-run/core/data.d.ts b/node_modules/@remix-run/core/data.d.ts
index f9d7c6c..f8360f8 100644
--- a/node_modules/@remix-run/core/data.d.ts
+++ b/node_modules/@remix-run/core/data.d.ts
@@ -4,12 +4,12 @@ import { Response } from "./fetch";
 /**
  * Some data that was returned from a data loader.
  */
-export declare type AppData = any;
+export declare type AppData<T = any> = T;
 /**
  * An object of data returned from the server's `getLoadContext` function. This
  * will be passed to the data loaders.
  */
-export declare type AppLoadContext = any;
+export declare type AppLoadContext<T = any> = T;
 /**
  * The result from executing a data loader.
  */
@@ -17,12 +17,12 @@ export declare type AppLoadResult = Response | null;
 /**
  * A function that loads data for a route or the global data loader.
  */
-export interface DataLoader {
+export interface DataLoader<AppDataType = any, Context = any> {
     (args: {
-        context: AppLoadContext;
+        context: AppLoadContext<Context>;
         params: Params;
         url: URL;
-    }): AppData;
+    }): AppDataType;
 }
 /**
  * Loads data using the global data loader at `data/global.js`.
```

**Comment by ianwremmel** [comment]
I've been using the following to generate typed loaders with corresponding hooks. It's a little silly since it's a noop, but I'm not sure of any other way to ensure the hook matches the loader without some amount of manual typing. 

```ts
// make-loader.ts
import {DataFunctionArgs} from '@remix-run/server-runtime';
import {useLoaderData} from 'remix';

export type LoaderFunction<T> = (
  args: DataFunctionArgs
) => Promise<Response> | Response | Promise<T> | T;

interface MakeLoaderResult<T, R> {
  loader: LoaderFunction<R>;
  useLoaderData: () => R;
}

export function makeLoader<T, R>(
  loader: LoaderFunction<R>
): MakeLoaderResult<T, R> {
  return {
    loader,
    useLoaderData,
  };
}
```

```ts
// route.tsx
export const {loader, useLoaderData} = makeLoader(async ({request}) => ({
  flash: await loadFlashMessages(request),
}));
```

**Comment by jacob-ebey** [comment]
> I've been using the following to generate typed loaders with corresponding hooks. It's a little silly since it's a noop, but I'm not sure of any other way to ensure the hook matches the loader without some amount of manual typing.
> 
> ```ts
> // make-loader.ts
> import {DataFunctionArgs} from '@remix-run/server-runtime';
> import {useLoaderData} from 'remix';
> 
> export type LoaderFunction<T> = (
>   args: DataFunctionArgs
> ) => Promise<Response> | Response | Promise<T> | T;
> 
> interface MakeLoaderResult<T, R> {
>   loader: LoaderFunction<R>;
>   useLoaderData: () => R;
> }
> 
> export function makeLoader<T, R>(
>   loader: LoaderFunction<R>
> ): MakeLoaderResult<T, R> {
>   return {
>     loader,
>     useLoaderData,
>   };
> }
> ```
> 
>  ```ts
> // route.tsx
> export const {loader, useLoaderData} = makeLoader(async ({request}) => ({
>   flash: await loadFlashMessages(request),
> }));
> ```

`export const {loader, useLoaderData} = makeLoader(` is an effect. You should not do this.

We have the `json<Data>(data: Data, init: ResponseInit)` function for type safety here. I actually recommend you return a `Response` from loaders and actions and use the aforementioned `json` utility, this leaves room for easy growth / expansion of the functionality of the loader in the future. If you unit test that loader that returns an object, and need to add headers to the response, you've just broken all your tests that should still be passing.

**Comment by mcansh** [comment]
yeah this issue is mine and is way out of date 🥴
