### ISSUE TITLE
No loader is configured for ".svg" files

### ISSUE THREAD

**Issue by Jackardios** [remix-run/remix#6316]
### What version of Remix are you using?

0.0.0-nightly-6e23fcf-20230505

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Import any svg file in route
3. Get the error `No loader is configured for ".svg" files`

### Expected Behavior

svg should import without error

### Actual Behavior

when importing svg there is an error: "No loader is configured for ".svg" files"

**Comment by pcattori** [comment]
@Jackardios was this working for you on stable versions of Remix? (i.e. 1.15 or 1.16?)

Could you share where your SVG file is located (`public/`? within `app/`?) and how you import and use it?

**Comment by Jackardios** [comment]
@pcattori it works in 1.16.0, the problem only occurs in 0.0.0-nightly-6e23fcf-20230505

Svg file is located within `app/`.
The file where the error occurs looks like this:
```tsx
import * as React from "react";

import logoImage from "@/modules/common/assets/images/logo.svg";
import { Image } from "@/modules/design-system/components/Image";

export interface LogoProps
  extends Omit<React.ComponentPropsWithoutRef<"img">, "src"> {}

export const Logo: React.FC<LogoProps> = ({
  width = 158,
  height = 34,
  ...otherProps
}) => {
  return (
    <Image
      src={logoImage}
      width={width}
      height={height}
      {...otherProps}
    />
  );
};
```

**Comment by pcattori** [comment]
Does the error happen when running `remix build` or also with dev server? (and do you have `unstable_dev` enabled?)

**Comment by lauritzsh** [comment]
I'm also experiencing this on 0.0.0-nightly-c7ad951-20230508. Worked fine on stable. Only experiencing this when running with `unstable_dev`. My `.svg` is also located inside `app/`.

**Comment by dmarkow** [comment]
@pcattori As mentioned on discord, getting the exact same issue but with PNG files. Tried making a repro loading the same PNG file from the same relative path, and of course it's not breaking there, even copying over my exact same package.json and remix.config.js files. I'll need to try some other options for reproducing it.

It does seem to only happen running `remix dev`. `remix build` completes without any problems. So it may be somehow related to the dev server/HMR code.

**Comment by pcattori** [comment]
@dmarkow does the issue only happen with `unstable_dev` or also the old dev server?
