### ISSUE TITLE
Defer/Await type mismatch

### ISSUE THREAD

**Issue by K1NXZ** [remix-run/remix#6324]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Example:

```tsx
import { defer, type LoaderArgs } from "@remix-run/node";
import { Await, useLoaderData } from "@remix-run/react";

const getDate = async () => new Date();

export function loader({ params }: LoaderArgs) {
  return defer({
    date: getDate(),
  });
}

export default function Index() {
  const data = useLoaderData<typeof loader>();

  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <Await resolve={data.date}>{(date) => <p>The date is: {date}</p>}</Await>
    </div>
  );
}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/2119319/236588272-5b558a51-df51-42bb-a50c-377ed9e057a1.png)

Date being and rendering as a String.

### Actual Behavior

Date is a Date Object and throwing an Error:

`Error: Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead.`

**Comment by akamfoad** [comment]
As mentioned in [Remix Docs - Using Defer](https://remix.run/docs/en/1.16.0/guides/streaming#using-defer) you need to wrap `Await` component in Suspense, since the `data.date` is a promise it is not a valid React Children indeed.

And Remix typings seems correct to me, since the returned data from your deferred function call is a Date, it'll be 
 of type `Promise<Date>`, but when the promise is resolved, Remix will serialize the data, and sends it to the client, and when you serialize a Date it'll be converted to string representation of the date, you can then do `new Date(data.date)` on client; you should get back your date object if you want to use it that way or just use the string representation.

Here is a working example https://stackblitz.com/edit/remix-run-remix-bnnye5

**Comment by K1NXZ** [comment]
> As mentioned in [Remix Docs - Using Defer](https://remix.run/docs/en/1.16.0/guides/streaming#using-defer) you need to wrap `Await` component in Suspense, since the `data.date` is a promise it is not a valid React Children indeed.
> 
> And Remix typings seems correct to me, since the returned data from your deferred function call is a Date, it'll be of type `Promise<Date>`, but when the promise is resolved, Remix will serialize the data, and sends it to the client, and when you serialize a Date it'll be converted to string representation of the date, you can then do `new Date(data.date)` on client; you should get back your date object if you want to use it that way or just use the string representation.
> 
> Here is a working example https://stackblitz.com/edit/remix-run-remix-bnnye5

I see, thanks for clarifying. The typings are still confusing imo. The type that is shown can be different than it actually is to runtime without the suspense.

**Comment by brophdawg11** [comment]
These types seem accurate to me.  As @akamfoad mentioned the type is `Date` in the `loader` but once serialized it becomes a string.  I think the confusion you're seeing is due to the wrapper type, which includes the requires `Date->string` serialization

```tsx
export default function Index() {
  // The SerializeDeferred wrapper type is what reflects the serialization
  const data = useLoaderData<typeof loader>();
  //    ^? SerializeDeferred<{ date: Promise<Date> }>

  // Once you look inside, you see the string type
  console.log(data.date);
  //               ^? Promise<string>

  // You could also destructure it off
  const { date } = useLoaderData<typeof loader>();
  //      ^? Promise<string>

  // And then it's a string when used inside Await
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <Await resolve={date}>{(value) => <p>The date is: {value}</p>}</Await>
                                                     {/* ^? string */}
    </div>
  );
}

```
