### ISSUE TITLE
Decorators error after upgrading to 1.16.0

### ISSUE THREAD

**Issue by markdalgleish** [remix-run/remix#6353]
### Discussed in https://github.com/remix-run/remix/discussions/6326

<div type='discussions-op-text'>

<sup>Originally posted by **erandow** May  6, 2023</sup>
After upgrading remix to the latest version(1.16.0),
I get the following error after running project locally.]
`
The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'. [plugin css-side-effects-plugin]
`
I also set the `future.unstable_cssSideEffectImports: true` but the errors still exist.</div>

**Comment by markdalgleish** [comment]
@erandow I haven't been able to reproduce the issue. Could you please share a repro?

**Comment by markdalgleish** [comment]
@erandow It looks like the `decoratorsBeforeExport` option is deprecated: https://babel.dev/docs/babel-parser#plugins-options. This seems likely to do with an older version of `@babel/parser`. Are you able to confirm which version you're using?

**Comment by nakleiderer** [comment]
I had a similar issue when I upgraded only Remix, but it went away when I upgraded all outdated packages in my app. I imagine npm was picking up an older version of babel for one of my other dependencies.

**Comment by markdalgleish** [comment]
This shouldn't be an ongoing issue once #6390 goes out.

**Comment by markdalgleish** [comment]
@erandow Are you able to check your issue against the night release?

**Comment by erandow** [comment]
@markdalgleish, 
Thanks for creating an issue and trying to fix the issue. 
Sorry, I was offline and couldn't answer your questions. 

Thanks, It seems that there is no problem with the nightly release.
