### ISSUE TITLE
Remix is breaking when using with react-router-dom's link

### ISSUE THREAD

**Issue by pkalisiewicz** [remix-run/remix#6358]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Set up a Remix project
2. Install react-router-dom, or any library that consumes react-router-dom under the hood (such as component library)
3. Import the Link component and use it directly anywhere in the Remix app.
4. Observe the error related to the missing context for the library's basename.

### Expected Behavior

The Link component should render a component without any issues. This is because it should be using the upper context created by `RemixBrowser` (client-side) and `RemixServer` (server-side).

### Actual Behavior

The application breaks when using the Link component from react-router-dom directly in a Remix app. The error message mentions the missing context for the library's basename.

To better understand the issue, please refer to the following StackBlitz example

https://stackblitz.com/edit/remix-run-remix-kdzgmg?file=package.json,app%2Froutes%2F_index.tsx

**Comment by machour** [comment]
You are supposed to use Remix's Link from @remix-run/react

**Comment by pkalisiewicz** [comment]
How about if I am using a component library that fully relies on React-router-dom?
Do I need to update imports while building / consuming a package?

**Comment by machour** [comment]
Please use the Discussion tabs for Q&A 🙏
This issue tracker is meant to track bug in remix
