### ISSUE TITLE
Improve Lighthouse SEO Issues of the default template

### ISSUE THREAD

**Issue by amir-ziaei** [remix-run/remix#6376]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- run `npx create-remix` and follow along as below:
  - ? Where would you like to create your app? `wherever you want...`
  - ? What type of app do you want to create? `Just the basics` <---- important
  - ? Where do you want to deploy? `doesn't matter...`
  - ? TypeScript or JavaScript? `doesn't matter either...`
  - ? Do you want me to run npm install? `Yes`
- cd into your created remix app
- run `npm run build`
- run `npm start`
- open `http://localhost:3000` in an **incognito** chromium tab
- open Lighthouse and run a SEO test
- Notice the yellow score!
<img width="746" alt="image" src="https://github.com/remix-run/remix/assets/26747997/3137ab42-fc9b-4cb5-b1e9-f78e0dd471ab">

### Expected Behavior

The SEO score to be at least in the green zone.

### Actual Behavior

The SEO score is in the yellow zone.

----

### Why it matters

Though I agree this is just a starter template and nobody is gonna be actually using that, I believe first impressions are still important for better adoptability. Furthermore, fixing the reported SEO issues is quite easy.

**Comment by machour** [comment]
Hey @amir-ziaei, you're 100% right.
Would you like to make a pull request to fix this? 

Templates are here: https://github.com/remix-run/remix/tree/main/templates
I guess they're all affected since it's the same starter.

The PR should target the `main` branch.
Happy to assist if needed (and interested ofc)

**Comment by amir-ziaei** [comment]
> Hey @amir-ziaei, you're 100% right. Would you like to make a pull request to fix this?
> 
> Templates are here: https://github.com/remix-run/remix/tree/main/templates I guess they're all affected since it's the same starter.
> 
> The PR should target the `main` branch. Happy to assist if needed (and interested ofc)

Thanks, I guess I can raise a PR too. But here's the thing...
Besides, in the templates, I find the following code in some fixtures too which probably should be updated all-together:
```tsx
<div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
```
What do you think?

**Comment by machour** [comment]
Fixtures are used for automated internal tests as far as I know, the update is not really needed.
