### ISSUE TITLE
Esbuild inject adds all node globals for non-node environment

### ISSUE THREAD

**Issue by TrySound** [remix-run/remix#6380]
### What version of Remix are you using?

1.16

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Install esbuild, add esbuild-plugin-polyfill-node plugin. Import commonjs module from entry point. You'll see all polyfills to be included in resulting bundle.

This might be caused by this behavior. Basically esbuild cannot safely require es module from commonjs. So the entire idea to rely on esbuild to inject globals is not good since all remix code and dependencies is commonjs.

https://github.com/evanw/esbuild/issues/1697#issuecomment-947645782

### Expected Behavior

Unnecessary polyfills should not be included.
Remix should have a way to disable all polyfills (disabling only globals is not supported in plugin).

### Actual Behavior

Our worker bundle increased with 45kB of unused code.

**Comment by MichaelDeBoey** [comment]
We just published version `1.17.1-pre.0` which includes #6562 (a possible fix). If you'd like to take it for a test run please try it out and let us know what you think!

**Comment by TrySound** [comment]
Nice! Will try in a few days.
