### ISSUE TITLE
Style changes not reflected on browser until dev server is restarted (using sass) 

### ISSUE THREAD

**Issue by jlefebvre1997** [remix-run/remix#6386]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix project 
2. Setup sass the way it's explained in the docs : https://remix.run/docs/en/1.16.0/guides/styling#css-preprocessors
3. Add the link configuration in the `root.tsx` file pointing to the compiled css file 
4. Add some stuff in a scss file in the relevant folder and let sass compile it to css 

Note : When doing this I had all my scss files in a `assets/style` folder 

### Expected Behavior

When doing changes to a scss file, changes should be reflected on the browser, either without needing to refresh if there is some kind of HMR / live reload, or by refreshing the browser.

### Actual Behavior

Refreshing the browser does not reflect the changes. Restarting the remix dev server is needed for the changes to actually be seen. 

Note : I tried with plain css files as well and it didn't work either

**Comment by markdalgleish** [comment]
Are you able to share a repro?

It's possible this issue is solved by #6374. Would you be able to see if this is fixed against the nighly release `v0.0.0-nightly-ff40409-20230514`?

**Comment by dipsaus9** [comment]
It looks like the nightly release from #6374 does fix the issue. We encountered the same issue in our project, also ran a new Remix setup and there it is also fixed.

**Comment by pcattori** [comment]
@jlefebvre1997 the dev server only watches changes in the app directory (`app/` or whatever you configured it to). If you want to watch for changes elsewhere, use the [watchPaths option](https://remix.run/docs/en/1.16.0/file-conventions/remix-config#watchpaths)

**Comment by jlefebvre1997** [comment]
Oh, indeed @pcattori that was it, I added my assets path to the `watchPaths` option and it worked. Sorry for the inconvenience :bowing_man: closing now since it's "fixed"
