### ISSUE TITLE
[Bug]: Remix is starting on the same port as create-react-app and replacing the other frontend as long as its running

### ISSUE THREAD

**Issue by c0ntradicti0n** [remix-run/remix#639]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Start a CRA-app and Remix at the same time: 

```

 npm start

> react-scripts start

Attempting to bind to HOST environment variable: localhost
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://cra.link/advanced-config

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from ...
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
Compiled successfully!

You can now view panos in the browser.

  http://localhost:3000

Note that the development build is not optimized.
To create a production build, use npm run build.
```

And then start remix-react: 

```
> remix start

Remix App Server started at http://localhost:3000
```
(One time to reproduce I had to restart the create react again, but then the beheavior was stable, that all the time I opened some site I ended up on remix and after quitting I fell back to the other CRA)

### Expected Behavior

Remix should check not only for remix-apps themselves (it's not starting at the same time), but for processes listening on the port.

### Actual Behavior

We first thought, that the OS (macOS BigSur, 11.2.3) should prevent this, but no, there is a problem in node [https://medium.com/@eplawless/node-js-is-a-liar-sometimes-8a28196d56b6](https://medium.com/@eplawless/node-js-is-a-liar-sometimes-8a28196d56b6) That beheavior of the OS is dangerous for man in the middle attacks and for building pishing sites.

How remix looks for other processes on this port?

**Comment by mcansh** [comment]
we implemented a check for finding an unused port in remix dev in [1.2.0](https://github.com/remix-run/remix/releases/tag/v1.2.0)

I'm going to close this now, but feel free to re-open if you're still running into issues
