### ISSUE TITLE
HMR (unstable_dev in 1.16.0) loses TypeScript sourcemap support

### ISSUE THREAD

**Issue by barrymay** [remix-run/remix#6392]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

FYI - This was found when trying to see emotion work under Remix HMR/HDR (which it does! 😀) but when trying to debug a related issue, I saw this which makes the investigation harder.

## Show the Proper behavior  (by default)
- Clone https://github.com/barrymay/remix-examples.git (my fork of remix-run/examples)
- Open VSCode (or whatever IDE) under the **emotion** folder
- Go to branch [Test-HMR-on-latest-libraries](https://github.com/barrymay/remix-examples/tree/Test-HMR-on-latest-libraries)
- run `npm install` (updates to latest react/remix/emotion) and `npm run dev`
- In the browser that opens, the app will work as expected w/o HMR support
- In Chrome DevTools, hit Cmd-P and navigate to index.tsx (under /app/routes) 
- You'll see the expected typescript representation and be able to debug with it (PASS)

## Add HMR and show the failing behavior  
- Open remix.config.js, and uncomment
```js
  future: {
    unstable_dev: true
  }, 
```
- Run `npm run dev`
- App will start, HMR/HDR will work great
- In Chrome Devtools, hit Cmd-P and navigate to index.tsx
- The JS representation is shown in the source files (it's kinda hard to find in the first place)

### Expected Behavior

The TypeScript sourcemaps should be respected as they are without HMR on.  

### Actual Behavior

The TypeScript sourcemaps are not represented properly and only the underlying JS (and more) is shown.

**Comment by tgds** [comment]
Same here. No sourcemaps. I'm on 1.17.0

**Comment by WesleyYue** [comment]
Can confirm it occurs in 1.18.0 as well under `v2_dev`

**Comment by bmaycc** [comment]
I tried this today on 1.18.1, even with a barebones create-remix built app, and unfortunately same issue.   While the dev mode looks great, if it causes complexity on debugging, I'm fine to stay in non-dev mode.

**Comment by barrymay** [comment]
Tried today on 1.18.1, with a barebones create-remix app, and sadly same issue.    For developer efficiency, TS sourcemaps are a critical browser feature for debuggability of an app, so I can't move to remix DEV mode until this is sorted.

**Comment by bmaycc** [comment]
Tested the nightly my example - looks great @pcattori, thanks !

**Comment by jgentes** [comment]
I'm still seeing broken sourcemaps in `1.19.3`. My `remix.config.js` (setup for Cloudflare Pages):
```js
/** @type {import('@remix-run/dev').AppConfig} */
export default {
	ignoredRouteFiles: ['**/.*'],
	server: './server.ts',
	serverBuildPath: 'functions/[[path]].js',
	serverConditions: ['workerd', 'worker', 'browser'],
	serverDependenciesToBundle: 'all',
	serverMainFields: ['browser', 'module', 'main'],
	serverMinify: true,
	serverModuleFormat: 'esm',
	serverPlatform: 'neutral',
	serverNodeBuiltinsPolyfill: {},
	future: {
		v2_dev: true,
		v2_routeConvention: true,
		v2_errorBoundary: true,
		v2_meta: true,
		v2_normalizeFormMethod: true,
		v2_headers: true
	}
}
```
