### ISSUE TITLE
Unrecognized mode

### ISSUE THREAD

**Issue by marcus-sa** [remix-run/remix#6393]
### What version of Remix are you using?

16.1.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`NODE_ENV=preview remix build`

### Expected Behavior

Not to log `Unrecognized mode: preview` and exit.

### Actual Behavior

It logs `Unrecognized mode: preview` and exits without any context.

**Comment by akoenig** [comment]
Can confirm. Workaround for the moment seems like (for example) `NODE_ENV= remix build`

**Comment by markhker** [comment]
I have found a similar bug, when deploying to cloudflare pages if you set `NODE_ENV = production` in the environment variables section, and you use tailwind, the tailwind css file is not generated. It is solved by removing `NODE_ENV` from the env variables

**Comment by pcattori** [comment]
Fixed by #7113
