### ISSUE TITLE
Handling Image and SVG imports

### ISSUE THREAD

**Issue by chromonav** [remix-run/remix#64]
- in JS the import of images are not supported
- CSS imports from fonts do not work in dev.

Reference chats on discord: https://discord.com/channels/770287896669978684/770287896669978687/782297830559449088

**Comment by luan03** [comment]
Hi [chromonav](https://github.com/chromonav), is this issue still happening or it can be closed?

**Comment by machour** [comment]
Closing for now, feel free to reopen an issue if this still happen with latest releases
