### ISSUE TITLE
Unable to get HMR/ HDR for HTTPS express server - Could not reach Remix dev server at https://localhost:3001

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#6402]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Example repo of a new Remix Express app using HTTPS: https://github.com/cliffordfajardo/remix-express-https-hmr/tree/main

## 1. Install dependencies

```sh
npm i
```

## 2. Generate self-signed certs
Since we intend on using HTTPs, we need to create self-signed certificates.
After running the command below, you will be prompted to give answers to the openssl CLI tool that generates the cert `server.key` and `server.cert` file.

```sh
npm run gen-cert

# For details see this small blog post:  https://flaviocopes.com/express-https-self-signed-certificate/
```

## 3. Start the remix app
```sh
## NOTE: you will be prompted to fill in a few values from openssl CLI tool. See: https://flaviocopes.com/express-https-self-signed-certificate/
npm run dev
```

### Expected Behavior

The dev server should be reachable via HTTPS when passing https settings inside of `remix.config.js`
See sample repo: https://github.com/cliffordfajardo/remix-express-https- 

```js
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  // serverModuleFormat: "cjs",
  serverModuleFormat: "cjs",
  future: {
    unstable_dev: {
      httpScheme: 'https',
      httpHost: 'localhost',
      port: 15001,
    },
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
```

### Actual Behavior

```
> remix dev --no-restart -c "node server.js"

💿 Building...
💿 Built in 609ms
Waiting for app server (52766818)
> node server.js
Remix dev server ready
Express server listening https://localhost:15001
❌ Could not reach Remix dev server at https://localhost:3001
```

**Comment by cliffordfajardo** [comment]
Hey @pcattori,
I tried following the [unstable_dev-enabled templates](https://github.com/remix-run/remix/tree/templates_v2_dev/templates) referenced in the 1.16.0 release notes here:
https://github.com/remix-run/remix/releases/tag/remix%401.16.0

Most likely I'm not passing the right settings in remix.config.js?

Let me know how I can help! Happy to hop on Discord etc.
Once I'm able to get this working, I want to publish a HTTPs example and post in the [Remix Repo's Discussion's Show and Tell section](https://github.com/remix-run/remix/discussions/categories/show-and-tell-tips) so other folks using HTTPS can benefit 🙌

**Comment by pcattori** [comment]
Right now SSL / HTTPS is possible, but its tedious and error-prone. Luckily, proper SSL / HTTPS support is coming soon.

You can see https://github.com/atsolberg/compiled-remix-1.16.0/pull/1/files for how to patch Remix in the short-term, but expect out-of-the-box support for https to come before v2.
