### ISSUE TITLE
HMR not working in `cloudflare-pages` template

### ISSUE THREAD

**Issue by Jackardios** [remix-run/remix#6415]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix@latest --template https://github.com/remix-run/remix/tree/templates_v2_dev/templates/cloudflare-pages`
2. `npm run dev`
3. change something in the `/app/routes/_index.tsx` file
4. open console and see:
<img width="738" alt="console-error" src="https://github.com/remix-run/remix/assets/24757335/47ac2f61-1ca7-4e06-9013-34148873c4e4">

### Expected Behavior

HMR should work after changing the file

### Actual Behavior

After changing the file, HMR does not work, and an error appears in the console, the changes can only be seen if you manually reload the page. Perhaps this is due to the race condition #6286

**Comment by pcattori** [comment]
Can you manually `GET http://localhost:8788/build/routes/_index-<whatever hash>.js?t=<whatever timestamp>` in a separate browser window or via `curl`? Just to see if the app server can correctly serve that updated asset.

**Comment by Jackardios** [comment]
@pcattori Yes, it exists if you go manually along this path

**Comment by Jackardios** [comment]
@pcattori it looks like it really is due to a race condition. If you set timeout to logDevReady no error occurs:
```ts
// server.ts
import { logDevReady } from "@remix-run/cloudflare";
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import * as build from "@remix-run/dev/server-build";

if (process.env.NODE_ENV === "development") {
  setTimeout(() => logDevReady(build), 200);
}

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => ({ env: context.env }),
  mode: process.env.NODE_ENV,
});

```

**Comment by huw** [comment]
Hey, can you clarify whether you’re using Wrangler v2 or Wrangler v3? The reason being is that the new `--local` mode (v3; was `--experimental-local` in v2) doesn’t completely shut down the development server ([see the old behaviour here](https://github.com/cloudflare/workers-sdk/blob/5fd080c88ee7991cde107f8723f06ea2fd2c651d/packages/wrangler/src/dev/local.tsx#L406), which only applies to the old server).

Given that the old server is deprecated, I think the appropriate fix is to upgrade the Wrangler dependency in the v2 templates (I’ll suggest that fix over there)

**Comment by Jackardios** [comment]
@huw I am using wrangler v2. Did you manage to use version 3 with the remix? I am getting a strange error when I try to start the dev server:
`[ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.`

**Comment by huw** [comment]
@Jackardios try `npx workerd` and see what the output is. It’s likely you’re running into cloudflare/workerd#46.

**Comment by appden** [comment]
It works great for me with Wrangler v3.

> I am getting a strange error with it when I try to start the dev server:

@huw I got this too after upgrading to v3. I had to update my `wranger.toml` to remove `streams_enable_constructors` from the `compatibility_flags` because above that error you mentioned I got this: `The compatibility flag streams_enable_constructors became the default as of 2022-11-30`

**Comment by Jackardios** [comment]
@appden This seems to be related to the fact that `wrangler pages dev` cannot read `wrangler.toml`. I moved the configuration to the command call arguments and everything worked:
`wrangler pages dev ./public --compatibility-date 2022-04-05 --compatibility-flag streams_enable_constructors`

**Comment by Jackardios** [comment]
In general, I don't see a problem using the latest compatibility date:
`wrangler pages dev ./public --local --compatibility-date 2023-05-12`

**Comment by JarnoLeConte** [comment]
> @pcattori it looks like it really is due to a race condition. If you set timeout to logDevReady no error occurs:
> 
> ```ts
> // server.ts
> import { logDevReady } from "@remix-run/cloudflare";
> import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
> import * as build from "@remix-run/dev/server-build";
> 
> if (process.env.NODE_ENV === "development") {
>   setTimeout(() => logDevReady(build), 200);
> }
> 
> export const onRequest = createPagesFunctionHandler({
>   build,
>   getLoadContext: (context) => ({ env: context.env }),
>   mode: process.env.NODE_ENV,
> });
> ```

The solution above solved the issue for me. I'm using Wrangler 2.

**Comment by defjosiah** [comment]
FYI, I was able to reproduce this locally, I have a fix here:
https://github.com/remix-run/remix/pull/6767

**Comment by aaronadamsCA** [comment]
I've upgraded to v1.19.0 and I'm seeing this exact issue with Wrangler v3, unfortunately.

**Comment by defjosiah** [comment]
@aaronadamsCA 
I agree, there’s something funky going on, I don’t think it’s related to my change (verified locally that my change is applied)

I think it has something to do with this https://github.com/remix-run/remix/issues/6891

I applied the suggested change there NODE_ENV instead of build.dev, but I’m still seeing issues.

Does that change work for you?

**Comment by defjosiah** [comment]
I think it might have something to do with wrangler dev reloading the script at the same time that hmr is attempting to run.

**Comment by defjosiah** [comment]
Okay, I got it!

wrangler v3 + 1.19.0 + process.env.NODE_ENV works for me!

wrangler v2 doesn't work, and build.dev does not work

**Comment by aaronadamsCA** [comment]
Thanks @defjosiah. That's the same combination I'm using without success.

It seems the problem is with `watchPaths`, if I remove this from our config then HMR works. I'll have to file a separate issue when I get the chance.

**Comment by defjosiah** [comment]
If you can share a reproduction, I’d be happy to look at it!

**Comment by ankarhem** [comment]
I encountered this now and adding `watchPaths: ['app', 'server']` seems to work.

**Comment by tonydangblog** [comment]
I ran into a similar issue today with `wrangler@3.1.1` and `remix@1.19.2`. 

I chose Cloudflare **_Workers_** as my deploy target when using `npx create-remix@latest` and had the same HMR issue. However, when I switched to Cloudflare **_Pages_** instead, the HMR worked as expected. Leaving this here in case anyone else has the same situation!

**Comment by af** [comment]
I had the same issue (HMR not working) with Cloudflare workers, remix 1.19.3, and wrangler 3.7.0. The thing that resolved it for me was updating my `remix.config.js` with:

```
  serverConditions: ['workerd', 'worker', 'browser'],
```

Following this template: https://github.com/remix-run/remix/blob/main/templates/cloudflare-workers/remix.config.js
