### ISSUE TITLE
Unstable dev killing pid issue

### ISSUE THREAD

**Issue by AlemTuzlak** [remix-run/remix#6421]
### What version of Remix are you using?

v1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Unfortunately I do not know the precise reason this happened but here is the image of the issue, Pedro asked me to create an issue
![image](https://github.com/remix-run/remix/assets/18480956/47ae9ae8-76c5-43b3-877d-4341b646e2b0)

### Expected Behavior

Unstable dev doesn't crash

### Actual Behavior

Crashes

**Comment by mjadczak** [comment]
I can also confirm that it seems that often the dev server dies on Windows when a compilation error is encountered, and needs to be restarted manually, since v1.16.1.

**Comment by pcattori** [comment]
@AlemTuzlak do you know if this happens every time or just occasionally?

**Comment by AlemTuzlak** [comment]
@pcattori occasionally, but since I moved to v1.17 it happens a LOT less, before it was like every 1-4 rebuilds now its very rarely

**Comment by AlemTuzlak** [comment]
Unfortunately I can't give you exact metrics but the above are based on my experience in the last few weeks while I was trying it

**Comment by AlemTuzlak** [comment]
![image](https://github.com/remix-run/remix/assets/18480956/72e29d6c-0cb7-4e2c-99a9-290b2f57dbcb)
So I got this error again today. Not sure if this is the part referenced by the 1.19 release above so better for you to double-check @pcattori

**Comment by mjadczak** [comment]
Agreed, I am also still seeing this issue on the newest release (also on Windows).

**Comment by blackthought286** [comment]
On Windows 11 and was seeing this issue before updated to 1.19.0-pre.0. After the update I am not seeing the issue anymore.

**Comment by pcattori** [comment]
@AlemTuzlak @mjadczak can you try with `1.19.0-pre.4`?
