### ISSUE TITLE
Dynamic Routes in Short Blog Tutorial don't work

### ISSUE THREAD

**Issue by arjunbanker** [remix-run/remix#6423]
### What version of Remix are you using?

1.16.1 (latest)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Follow instructions from the top through https://remix.run/docs/en/main/tutorials/blog#dynamic-route-params

### Expected Behavior

Expect posts.$slug.tsx page to be loaded

### Actual Behavior

posts.tsx is loaded instead

**Comment by michaelgainyo** [comment]
That's odd. `post.$slug.tsx` should not match `posts.tsx`. Maybe you meant `posts.$slug.tsx`.

**Comment by arjunbanker** [comment]
> That's odd. `post.$slug.tsx` should not match `posts.tsx`. Maybe you meant `posts.$slug.tsx`.

thanks, fixed!

**Comment by brophdawg11** [comment]
I don't think the tutorial actually asks you to create a `posts.tsx` file anywhere.  If you're created a `posts.tsx` layout route, then maybe you forgot to include an `<Outlet />`?

Here's an example of a working `posts.$slug.tsx` route: https://stackblitz.com/edit/remix-run-remix-sio9wk

**Comment by arjunbanker** [comment]
The blog tutorial starter template already has a posts.tsx file and that is
what handles the route even to the more specific case, your example is
different than the blug tutorial.

**Comment by brophdawg11** [comment]
Where are you seeing that file?  The command to get started is:

```
npx create-remix@latest --template remix-run/indie-stack blog-tutorial
```

Which sets up your app using the indie stack which contains [these routes](https://github.com/remix-run/indie-stack/tree/main/app/routes), and does not contain a `posts.tsx` file?

I also double checked the gitpod link and it contains the same base routes as the indie stack?

You want 2 route files for the tutorial:

* `routes/posts._index.tsx` -> renders at `/posts`
* `routes/posts.$slug.tsx` -> renders at `/posts/[slug]`

**Comment by Zardw** [comment]
hello, I met a problem. The dynamic Segment doesn't work in blog toturial. 
![1](https://github.com/remix-run/remix/assets/117419340/36c2bbb9-2636-41f3-9878-3a8fa617920f)
![2](https://github.com/remix-run/remix/assets/117419340/f2739fee-15f1-4bcc-b882-5ac46636d4fb)

**Comment by kiliman** [comment]
@Zardw, that looks like the old v1 routing. If you have v2 routing enabled in *remix.config.js*, then this will not work. v2 routing no longer uses folders for nesting.

You need to change your routes:

- `routes/blogs/$slug.tsx` -> `routes/blogs.$slug.tsx`
- `routes/blogs/index.tsx` -> `routes/blogs._index.tsx`

**Comment by Zardw** [comment]
thanks a lot, it ok now. maybe the toturial video is old.

**Comment by kiliman** [comment]
Unfortunately, any tutorial/video older than six months will not work directly with recent Remix versions as they don't implement the coming v2 features.
