### ISSUE TITLE
Problem with metaV2 on MDX

### ISSUE THREAD

**Issue by EuSouVoce** [remix-run/remix#6427]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On any MDX
```mdx
---
meta:
  - title: My Blog
  - og:type: website
  - og:title:  My Blog
  - og:url: https://My.Blog/
  - description: Blablabla
  - og:description: blablabla
  - keywords: bla,bla,bla
  - robots: index,follow
  - googlebot: index,follow
---

# Content
```

### Expected Behavior

Output of ``<Meta />`` on root file

```html
<title>My Blog</title>
<meta name="og:type" content="website">
<meta name="og:title" content="My Blog">
<meta name="og:url" content="https://My.Blog/">
<meta name="description" content="Blablabla">
<meta name="og:description" content="blablabla">
<meta name="keywords" content="bla,bla,bla">
<meta name="robots" content="index,follow">
<meta name="googlebot" content="index,follow">
```

### Actual Behavior

```html
<title>My Blog</title>
<meta og:type="website">
<meta og:title="My Blog">
<meta og:url="https://My.Blog/">
<meta description="Blablabla">
<meta og:description="blablabla">
<meta keywords="bla,bla,bla">
<meta robots="index,follow">
<meta googlebot="index,follow">
```

**Comment by EuSouVoce** [comment]
I've had to change the default return after all the if's statements of the ``<Meta />`` component based on the ``@remix-run/react`` to render it correctly.
Here's what I've done.
```javascript
return (
            <meta
              key={JSON.stringify(metaProps)}
              name={`${Object.entries(metaProps)[0][0]}`}
              content={`${Object.entries(metaProps)[0][1]}`}
            />
          );
```

**Comment by EuSouVoce** [comment]
if anyone wants to use it, just download from [here](https://github.com/EuSouVoce/PatchedRemixMDXMetaV2)

I've grabbed the dist files from the @remix-run/react and deleted almost everything not related to the Meta component and changed the return of it.

**Comment by nakleiderer** [comment]
The YML is the example doesn't seem to follow the V2 convention. The YML should be equivalent to the JSON required for the API. 
```yml
meta:
  - title: My Blog # Should still work as is
  - name: "og:type" # You need to specify the attribute name and the value for every meta tag
    content: website
    
```

**Comment by EuSouVoce** [comment]
This way is counter intuitive, check docs.

**Comment by ryanflorence** [comment]
I agree it's counter intuitive but the intuitive approach blocks valid use cases, which was the whole motivation behind meta v2 🫣 We tend to prefer power > convenience
