### ISSUE TITLE
[Bug]: Incorrect blog path on admin screen in Blog tutorial 

### ISSUE THREAD

**Issue by RKRohk** [remix-run/remix#644]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.5

### Steps to Reproduce

 Follow the tutorial in [remix docs](https://github.com/remix-run/remix/blob/main/docs/tutorials/blog.md), go to the admin screen and click on a blog

### Expected Behavior

Should navigate to <base_url>/posts/<slug>

### Actual Behavior

Should navigate to <base_url>/admin/<slug>

Which can be fixed by changing the root/admin.tsx file from 

``` 
<ul>
    {posts.map((post) => (
            <li key={post.slug}>
              <Link to={post.slug}>{post.title}</Link>
            </li>
      ))}
</ul>
```

to 

``` 
<ul>
    {posts.map((post) => (
            <li key={post.slug}>
              <Link to={`/posts/${post.slug}`}>{post.title}</Link>
            </li>
    ))}
 </ul>
```

**Comment by kentcdodds** [comment]
Fixed :) Thanks!

**Comment by andrewmanullang** [comment]
Hey @kentcdodds I don't think the tutorial is updated yet

<img width="888" alt="image" src="https://user-images.githubusercontent.com/502997/167172233-c5dac576-1125-418d-b0a6-c4c5fe71bcab.png">

**Comment by kentcdodds** [comment]
That's actually part of the homework. You're supposed to make those pages be an "edit" page for the post.

**Comment by andrewmanullang** [comment]
> That's actually part of the homework. You're supposed to make those pages be an "edit" page for the post.

Aah, thanks.
