### ISSUE TITLE
Syntax error crashes dev server in 1.16.1

### ISSUE THREAD

**Issue by tgds** [remix-run/remix#6448]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

This is #5631 occurring again in 1.16.1. 

Run dev server with `unstable_dev: true`, save a file with a syntax error and the server crashes.

### Expected Behavior

As in 1.16.0, the server keeps running, but an error is printed in the console.

### Actual Behavior

Dev server crashes and it has to be restarted after the syntax error is fixed.

**Comment by andrecasal** [comment]
This is also happening to me. For someone with autosave like me, it's a horrible DX.
