### ISSUE TITLE
parent component useFetcher stucks loading, when unmounting sub component using another useFetcher

### ISSUE THREAD

**Issue by Reloadaxe** [remix-run/remix#6458]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I make a simple sandbox example here:

https://codesandbox.io/p/sandbox/relaxed-pine-cqtxe5?file=%2Fapp%2Froutes%2Fapp%2Findex.tsx%3A22%2C22

### Expected Behavior

component A should be loading and then stop loading after clicking the 'submit' button

### Actual Behavior

component A is loading indefinitly after clicking the 'submit' button

**Comment by brophdawg11** [comment]
This is fixed by https://github.com/remix-run/react-router/pull/10535 and should be available once 1.17.0 is released
