### ISSUE TITLE
tailwind didn't build whereas unstable_tailwind works

### ISSUE THREAD

**Issue by Jackeriss** [remix-run/remix#6501]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

my `remix.config.js`:
```javascript
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  publicPath: "/build/",
  serverBuildDirectory: "build",
  devServerPort: 8002,
  ignoredRouteFiles: [".*"],
  future: {
    v2_routeConvention: true,
    postcss: true,
    tailwind: true,
    unstable_dev: true,
  },
  serverDependenciesToBundle: [
    /^@douyinfe\/semi-ui/,
    /^@douyinfe\/semi-icons/,
    /^@douyinfe\/semi-illustrations/,
    /^@ant-design\/plots/,
    /^@antv/,
    /^lodash-es/,
  ],
};
```

### Expected Behavior

it should build tailwind correctly when using the `tailwind` config 

### Actual Behavior

when I start the dev server, the tailwind.css which loaded in the browser shows
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
and it was fine when I use `unstable_tailwind`

**Comment by machour** [comment]
@Jackeriss could you share the entire remix.config.js you are using?

Looks similar to #6465
