### ISSUE TITLE
Hydration error caused by scripts added to root.tsx

### ISSUE THREAD

**Issue by JarnoLeConte** [remix-run/remix#6513]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix app 
```
npx create-remix@latest

What type of app do you want to create? 
> Just the basics

Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment 
targets. 
> Remix App Server

TypeScript or JavaScript? 
> TypeScript

Do you want me to run `npm install`? 
> Yes
```
2. Replace `/app/root.tsx` with the following code
```
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
        <script
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
              function gtag() {dataLayer.push(arguments);}
              gtag('config','G-XXX');`,
          }}
        />
        <script
          type="text/javascript"
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXX`}
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <Outlet />
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}
```
3. Run the app
```
npm run dev  
```
4. Check the browser console for errors:

### Expected Behavior

No console errors

### Actual Behavior

Errors in console:

```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "" Client: "window.dataLayer = window.dataLayer || [];\n              function gtag() {dataLayer.push(arguments);}\n              gtag('config','G-XXX');"

Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

Whether or not the error occurs and what error message is shown depends a lot on the actual code base, such as:
- the order of scripts
- the content of the scripts
- what value is provided for **G-XXX** and **ca-pub-XXX**
- meta data v2

For example, in the app I'm currently working on I got the error `Warning: Prop type did not match. Server: "null" Client: "application/ld+json"`, which was triggered when I added a `script:ld+json` to the array exported from meta (v2), but when I searched for the origin of the problem I can narrow it down to the example provided above.

**Comment by brophdawg11** [comment]
Could you provide a reproduction of this issue?  The above steps do not cause any hydration issues for me...

**Comment by JarnoLeConte** [comment]
Here you can find my repository with a minimal reproduction:
https://github.com/JarnoLeConte/remix-hydration

Checkout the README.md for more details. 

To reproduce from scratch, do the following:

1. Create a new remix project
```sh
npx create-remix@latest

What type of app do you want to create? 
> Just the basics

Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment 
targets. 
> Remix App Server

TypeScript or JavaScript? 
> TypeScript

Do you want me to run `npm install`? 
> Yes
```
2. Open `/app/root.tsx` and add the following script below the `<Links />` tags:
```
<script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" />
```
3. Run the server `npm run dev`
4. Open browser (Chrome or Safari) at `http://localhost:3000`
5. The browser console shows the following messages:
![error](https://github.com/JarnoLeConte/remix-hydration/raw/main/ERROR.png)

**Comment by kiliman** [comment]
Those are typical hydration errors, especially if you're using Chrome extensions that modify the DOM. If you update to the latest React canary version, they have made some changes that minimize, if not eliminate, these hydration warnings.

**Comment by JarnoLeConte** [comment]
You are right, when I update the react packages `npm install react@18.3.0-canary-018c58c9c-20230601 react-dom@18.3.0-canary-018c58c9c-20230601` the errors do not occur anymore.

Isn't it strange that this isn't a problem in `Next` projects. Now I switched to Remix, I got this error. Both frameworks uses the hydration strategy. Or were these scripts in Next (in `_app.tsx` from Pages directory) always being rendered client-side? In that case it would make sense.

Is there anything I can do for now to avoid this problem, other than rendering the script on the client? I don't want to use `useEffect()` to make the script load dynamically because that will add an additional delay.

**Comment by kiliman** [comment]
This problem occurs primarily with Remix, as it renders the _entire_ HTML document. Many extensions modify the `<head>` or `<body>`, which causes issues during hydration. 

On the other hand, Next.js apps typically render inside a `<div id="root">` element, which is not normally modified before hydration.
