### ISSUE TITLE
Remix 1.16.1 Express Server doesn't load JS interactivity in Prod environment

### ISSUE THREAD

**Issue by morsmodr** [remix-run/remix#6514]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
// remix.config.js

  serverModuleFormat: "esm",
  future: {
    v2_errorBoundary: true,
    unstable_dev: true,
  },

// node scripts
"dev": "remix dev -c \"node server.js\"",
"remix-build": "remix build",
"remix-start": "cross-env NODE_ENV=production node ./server.js",
```

### Expected Behavior

Prod build should have js interactivity just like dev build

### Actual Behavior

There is no issue with `npm run dev`

For my production build I first run `npm run remix-build` and then `node server.js`

The page loads with server rendered react components but none of the interactive parts work ie tooltips, combobox react components do nothing on mouse clicks

I also see this error on production build in browser console for every page I navigate to
![Screenshot 2023-05-31 at 6 41 47 PM](https://github.com/remix-run/remix/assets/7231256/a51ac5e2-1b93-408a-a086-134778e6bfb5)

**Comment by brophdawg11** [comment]
This is hard to triage much further without a reproduction, but seems like it might be an issue with some library used by your app that's getting bundled.  Do you have anything calling an `install()` method?  Can you dig into the source maps a bit and see if you can narrow it down to where it's coming from?  Or start removing portions of the loaders/actions on the page it's happening on to see if you can find the problematic code?

**Comment by morsmodr** [comment]
Can confirm that the bug is with upgrade to either 1.16.0 or 1.16.1, because when I comment out `unstable_dev: true` from remix.config.js, js interactivity is back in production builds

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction?  The fact that `@remix-run/node` code is ending up in your browser confirms that server code is ending up in the client bundle, potentially from something being imported into a loader/action that is unable to be tree shaken out of the client bundle.

**Comment by morsmodr** [comment]
I have `import { json, redirect } from "@remix-run/node";` in my jsx files but also importing just `json` in `app/routes/api` like so:
`
// app/routes/api/get-filters.js
import { json } from "@remix-run/node";

export async function getFilters({}) {
 // get filters
 return json(filters)
}

// app/view/create-view.jsx
import { json } from "@remix-run/node";
import { getFilters } from "../api/get-filters";

export const loader = async({ request }) => {
 const filters = wait getFilters({ request });
 // get other pieces of data with api structure similar to above

 return json({
  filters,
  ...restOfData
 })
}
`

Can this pattern cause `@remix-run/node` to end up in server code landing in browser?

**Comment by brophdawg11** [comment]
It's possible - you are basically nesting calls to `json` at the moment which probably won't work as you expect.  If you want to re-use the `getFilters` logic I would extract that to a shared location that just returns the filters and then you can use it from both loaders.

I would need a minimal reproduction to debug further though.

**Comment by deflexable** [comment]
sadly am also having this exact issue, @morsmodr were you able to fix it?

**Comment by deflexable** [comment]
i ended up create new remix-app from scratch in remix 1.17.1, then copying all routes and utils files to the new project
