### ISSUE TITLE
Confusion when trying to run Cloudflare Workers-setup project locally

### ISSUE THREAD

**Issue by codewithkristian** [remix-run/remix#653]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [X] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.5

### Steps to Reproduce

1. Create a new project (`npx create-remix@latest`)
2. Select Cloudflare Workers + TypeScript config
3. Try to run local dev server so I can develop

### Expected Behavior

Able to visit `localhost:3000` and develop locally

### Actual Behavior

I'm confused on whether I'm supposed to run the Cloudflare Workers config locally, or if I should run Node or something similar locally, and then build out to Cloudflare Workers at the end. 

When I run `npm run dev` as per the Getting Started guide after setting up my project, the server seems to hang before setting up a port:

```sh
$ npm run dev

> dev
> remix watch

Watching Remix app in development mode...
💿 Built in 154ms
```

I see that it's running `remix watch` and that `remix dev` is another option, so I try to hit that directly:

```sh
$ npx remix dev
Could not locate @remix-run/serve. Please verify you have it installed to use the dev command.

# Install the package
$ npm i -D @remix-run/serve

# And try again
$ npx remix dev
Watching Remix app in development mode...
💿 Built in 156ms
Remix App Server started at http://localhost:3000
ReferenceError: self is not defined
    at Object.installGlobals (/Users/signalnerve/src/cloudflare-workers-test/node_modules/@remix-run/cloudflare-workers/globals.js:18:3)
    at Object.<anonymous> (/Users/signalnerve/src/cloudflare-workers-test/node_modules/@remix-run/cloudflare-workers/index.js:19:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/signalnerve/src/cloudflare-workers-test/node_modules/remix/platform.js:15:25)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
GET / 500 - - 27.294 ms
```

Now I have a URL/port (localhost:3000), but I'm getting the error `self is not defined` when I try and make requests to the localhost URL.

Might be misunderstanding the interplay between the adapters and local development, so let me know if this is user error! Excited to try out Remix though, so would love to help however I can.

**Comment by dindak** [comment]
After running `npm run dev` in one process, did you start a second process to run the miniflare server (scripted as `npm start`)?

Details: https://github.com/remix-run/remix/tree/main/packages/create-remix/templates/cloudflare-workers#development

Script: https://github.com/remix-run/remix/blob/8dabfa16b2b686201d4b0ac9fd6392ae818bd5a2/packages/create-remix/templates/cloudflare-workers/package.json#L9
