### ISSUE TITLE
[Feature]: Hope authentication support jwt

### ISSUE THREAD

**Issue by zwl1619** [remix-run/remix#654]
### What is the new or updated feature that you are suggesting?

Hope authentication support jwt.

### Why should this feature be included?

Server-side sessions come with pros and cons. Some users prefer the tradeoffs/benefits provided by client-side sessions (e.g. JWT).

This also makes it easier to choose alternative data stores (such as those unsupported by Prisma) without having to modify the auth system.

**Comment by sergiodxa-silverback** [comment]
You could create a JWT and store it in a cookie instead of storing the session inside a DB or something like that.

```ts
let sessionStorage = createCookieSessionStorage({
  cookie: {
    name: "session",
    path: "/",
    secrets: ["secret"],
    secure: process.env.NODE_ENV === "production"
  }
});

// to write it
let session = await sessionStorage.getSession(cookieHeader)
session.set("jwt", yourJwt)
let cookie = await sessionStorage.commitSession(session)

// to read the JWT
let session = await sessionStorage.getSession(cookieHeader)
let jwt = session.get("jwt")
let data = await parseJWT(jwt)
```

However, at that point you may not need JWT at all, just store the data directly in the sessionStorage returned by `createCookieSessionStorage` and you will have the same without adding a JWT serialize/parse step.

**Comment by codeAdityagithub** [comment]
@sergiodxa  Is the cookie created using the createCookieSessionStorage signed just like a jwt is signed? If yes, then which one is more secure the jwt or the default signed cookie? And is it ok if store properties like userId, username, image, prefs etc in the cookie session storage?
