### ISSUE TITLE
HMR | unstable_dev | unable to run dev server

### ISSUE THREAD

**Issue by nicholasglazer** [remix-run/remix#6542]
### What version of Remix are you using?

1.17.0-pre.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

os: 6.3.4-arch2-1
node: 20.2.0
by using this guide to enable HMR https://github.com/remix-run/remix/releases/tag/remix%401.14.0

```json
// package.json
  "scripts": {
    ...
    "dev": "run-p dev:*",
    "dev:build": "cross-env NODE_ENV=development remix dev",
    "dev:serve": "cross-env NODE_ENV=development nodemon --watch build node_modules/.bin/remix-serve build",
    ...
    }
```

```javascript
//remix.config.js
const {flatRoutes} = require('remix-flat-routes');

/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  routes: async defineRoutes => {
    return flatRoutes('routes', defineRoutes);
  },
  // appDirectory: 'app',
  // assetsBuildDirectory: 'public/build',
  // serverBuildPath: 'build/index.js',
  // publicPath: '/build/',
  serverModuleFormat: 'cjs',
  future: {
    unstable_dev: true,
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  serverDependenciesToBundle: [
    '@twind/core',
    ...
  ],
};

```

### Expected Behavior

both scripts up and running in parallel 

### Actual Behavior

im using pnpm by default, so by running `pnpm dev` im getting this error:
![1686055275_2023-06-06-18_11](https://github.com/remix-run/remix/assets/7410355/e01d3b26-065f-4a59-b468-3d9b8a3a2067)

by reinstalling packages with npm and run `npm run dev` I'll get this:
![1686055174_2023-06-06-18_09](https://github.com/remix-run/remix/assets/7410355/8836fc2d-7a69-4c8e-be82-5205e93a3aa1)

I tried 1.16.0 as well, same issue.

**Comment by brophdawg11** [comment]
@nicholasglazer The dev server had some pretty major changes in `1.16.0` so the guide you're using from `1.14.0` is likely outdated.  Can you try setting it up with the instructions in https://github.com/remix-run/remix/releases/tag/remix%401.16.0?

There's also this set of reference implementations from a community member that may be helpful: https://github.com/xHomu/remix-v2-server

**Comment by nicholasglazer** [comment]
Thanks a lot. I can confirm that HMR is working with remix-v2-server.
