### ISSUE TITLE
Prisma.JsonValue typescript bug after updating to 1.17.0

### ISSUE THREAD

**Issue by dT-Nick** [remix-run/remix#6558]
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Have a prisma schema model that uses the type 'Json' like so:
```prisma
model Example {
  json Json?
}
```

Get data from that model and return it from a loader, and use `examples` in the route component like so:
```tsx
export async function loader({}: LoaderArgs) {
  const examples = await db.example.findMany()
  
  return json({ examples })
}

export default function RouteComponent() {
  const loaderData = useLoaderData<typeof loader>()
  
  return (
    <div>
      {JSON.stringify(loaderData.examples[0].json)}
    </div>
  )
}
```

### Expected Behavior

Expecting the type of `loaderData.examples[0].json` to not cause a typescript error, like it didn't before the 1.17.0 update - guessing this is something to do with the new way types are simplified by `Serialize`.

### Actual Behavior

`loaderData.examples[0].json` has the following typescript error:
```
Type instantiation is excessively deep and possibly infinite. ts(2589)
```

Again this worked before 1.17.0, and when downgrading to 1.16.1 the error disappears.

**Comment by pcattori** [comment]
<img width="1689" alt="Screenshot 2023-06-08 at 3 14 29 PM" src="https://github.com/remix-run/remix/assets/1477317/7dbec354-99be-4c7c-8074-bdf0a59a59dd">

Unable to reproduce. Types are simplified (or in your words, "deconstructed"), but that's by design. But I do not get any warnings or errors about infinite type instantiation neither in my editor nor when running `tsc` to typecheck.

**Comment by DerJacques** [comment]
We are seeing the same issue on our end.
As soon as the data returned by Prisma returns a `Json` field, this error shows up.

Interestingly, we don't see the issue when we try to access the data directly, but when we start looping over it, the TS error pops up:

```
export async function loader({}: LoaderArgs) {
  const examples = await db.example.findMany()
  
  return json({ examples })
}

export default function RouteComponent() {
  const loaderData = useLoaderData<typeof loader>()
  
  return (
    <div>
      {JSON.stringify(loaderData.examples[0].json)}  // We have seen this not cause issues
      {loaderData.examples.map(example => example.id)} // This one results in the error. `.json` doesn't even have to be accessed.
    </div>
  )
}
```

**Comment by pcattori** [comment]
Can you reproduce within a [Typescript playground](https://www.typescriptlang.org/play)? Or provide details on what the `Example` type looks like?

**Comment by dT-Nick** [comment]
> Can you reproduce within a [Typescript playground](https://www.typescriptlang.org/play)? Or provide details on what the `Example` type looks like?

Example type doesn't seem to matter. Literally did the same as you in my above screenshots ([this comment](https://github.com/remix-run/remix/issues/6558#issuecomment-1582609968)) with: 
```tsx
const examples = {} as Prisma.JsonValue[]
```

And I'm still getting the same issue. I'll have a look and see if I can reproduce within a ts playground.

**Comment by pcattori** [comment]
Still not able to reproduce in Typescript playground

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKwM4QHZwL5wGZQQhwDkAAlAKYjAAeAtFAK4YD0GEAJpSQFCiRYiOE1SUAMhACG3KABEpMKTnyFi5KjQbM2VKQGMYffhhiUoeA5TgApdBgCCUKFICecSrTMZOqOE5dXAB47TAA1KQAbJkoAPkRsXhhXMGtQjAjo6wBeOFQYKGAMAHM4AB84DCYQACNzcrgaiAhIyiksCvSAeRrkSkMG9IC3BqrIyKSUtPsevoHcpABtAGlKdyK8gqLigF0AfgAuW3tMmJxeEzMLKzgAUVopcFbEXjg4YE4j-MKS15R7I7pU6UXiJXieQTwKSoVwYfT4FiGYCYOCRaSyAAUAEoXm99Jh8h4Hk9KKgjvdHmBWosdnBcjSLm8qDAmFAsGhMBikJ5Ka0-NgsaCLhDoPBuJYmJF4HhETBkVgAEoQJhmADCREgGEopmxuLg+IwhLRMnMCiUdJEYkkJvkiikQWSqQgeFR6PMsWxjNRlHgHz8uWNsjNUgAdDySagQyApGAMRjw1TKDjsvEE60Qx9BW9WKw3gA9PagoA

**Comment by dT-Nick** [comment]
[Here's a reproduction in Typescript playground.](https://www.typescriptlang.org/play?target=6&jsx=4&module=1&isolatedModules=true#code/JYWwDg9gTgLgBAbzgKwM4QHZwL5wGZQQhwDkAAlAKYjAAeAtFAK4YD0GEAJpSQFCiRYiOE1SUAMhACG3KABEpMKTnyFi5KjQbM2VKQGMYffhhiUoeA5TgApdBgCCUKFICecSrTMZOqOE5dXAB47TAA1KQAbJkoAPkRsXhhXMGtQjAjo6wBeOFQYKGAMAHM4AB84DCYQACNzcrgaiAhIyiksCvSAeRrkSkMG9IC3BqrIyKSUtPsevoHcpABtAGlKdyK8gqLigF0AfgAuW3tMmJxeEzMLKzgAUVopcFbEXjg4YE4j-MKS15R7I7pU6UXiJXieQTwKSoVwYfT4FiGYCYOCRaSyAAUAEoXm99Jh8h4Hk9KKgjvdHmBWosdnBcoskB8jiQAAwkAA0-0wzJI2B2FzeVBgTCgWDQmAxSE8lNafmwWNBFwh0Hg3EsTEi8DwiJgyKwACUIEwzABhIiQDCUUzY3FwfEYQlomTmBRKOkiMSSZ3yRRSILJVIQPCo9HmWLYgWoyjwD5+XJO2SuqQAOmlJNQyZAUjAGIxaaplBx2Xi+dayY+CreCZdvtTxILqEWLJ2yfFGD+rFYbwAentQUA)

Updated some config settings to match my tsconfig & was able to reproduce the error when trying to access `json` directly - not when looping through the data like DerJacques.

**Comment by dT-Nick** [comment]
Noticed @DerJacques was using an older version of typescript and now the issue is there when looping, but not when accessing json directly, as he initially described.

[Link](https://www.typescriptlang.org/play?target=6&jsx=4&module=1&isolatedModules=true&ts=4.9.5#code/JYWwDg9gTgLgBAbzgKwM4QHZwL5wGZQQhwDkAAlAKYjAAeAtFAK4YD0GEAJpSQFCiRYiOE1SUAMhACG3KABEpMKTnyFi5KjQbM2VKQGMYffhhiUoeA5TgApdBgCCUKFICecSrTMZOqOE5dXAB47TAA1KQAbJkoAPkRsXhhXMGtQjAjo6wBeOFQYKGAMAHM4AB84DCYQACNzcrgaiAhIyiksCvSAeRrkSkMG9IC3BqrIyKSUtPsevoHcpABtAGlKdyK8gqLigF0AfgAuW3tMmJxeEzMLKzgAUVopcFbEXjg4YE4j-MKS15R7I7pU6UXiJXieQTwKSoVwYfT4FiGYCYOCRaSyAAUAEoXm99Jh8h4Hk9KKgjvdHmBWosdnBcoskB8jiQAAwkAA0-0wzJI2B2FzeVBgTCgWDQmAxSE8lNafmwWNBFwh0Hg3EsTEi8DwiJgyKwACUIEwzABhIiQDCUUzY3FwfEYQlomTmBRKOkiMSSZ3yRRSILJVIQPCo9HmWLYgWoyjwD5+XJO2SuqQAOmlJNQyZAUjAGIxaaplBx2Xi+dayY+CreCZdvtTxILqEWLJ2yfFGD+rFYbwAentQUA)

**Comment by DerJacques** [comment]
Thanks for the great repro-case, @dT-Nick! Just wanted to add that I re-used an old sandbox, so that's why the TS version was 4.x. Locally we're using 5.0.4. Very strange that sometimes looping is the issue, while other times accessing the attribute directly is the issue.

**Comment by dT-Nick** [comment]
> Thanks for the great repro-case, @dT-Nick! Just wanted to add that I re-used an old sandbox, so that's why the TS version was 4.x. Locally we're using 5.0.4. Very strange that sometimes looping is the issue, while other times accessing the attribute directly is the issue.

Yeah looks like 5.0.4 and 4.9.5 have the error when looping, but 5.1.3 has the error when accessing it directly. :shrug:

**Comment by pcattori** [comment]
Got a [prototype for the fix in this playground](https://www.typescriptlang.org/play?target=6&jsx=4&module=1&isolatedModules=true&ts=4.9.5#code/JYWwDg9gTgLgBAbzgKwM4QHYBo4GUCmUwAhgDbABe+AYlBCHAL5wBmdDA5AAJT4jAAPALRQArhgD0GCABN8HAFAKYATzD44ASRYBRAI6iyqADwAVHAFUcATQC84gNbSA7tjgA5WxnwA3QgD44WwU4OAAKYwBxfzCASiDAyLh8ARh8DBlUOFM4AH44AEY4AC44ACZ4lLSM1BDwqJj420Tk1PTMuAs8wpLy+PzrXvcAbiUUyFg4VXVstXwZACV8VEgMVHwzVuqOxxcMILhdiFdA2zgAeX4YYzqllcx1rDqAIjRMZ4VAgDJEOreMOKlAAK7GA6zM-lGjFGCgkElY0AAxhpTHNUIiiGB4DAIHBUKAwOQWCopgALDTTfDKOZwEH4GCqCEHJAAbQA0nBgPsHPgVBAWNkALqlUzswVMOA-BDQpSUuAAKXQGBBoGAMGAfiCdQAPniYEQMABzHVwDCiEAAI0IJotEAgpHwxAwJtw+q5xtCuvc5qtUBNACE7Q6nSazaRSKM5e5MIrMCqrhqNGdxHIWFz5nBddRxIj1ZhM3iVJb7TCJAAqEJluAAAydKmrnKyMHJcEwpBJcubxHgiKdcAd8D5omSBm7GmrAAYG841aSawVq5W8PgNKSGWBUMU4agYMREQ4IH4oCxSMcAHSI+gSYgSAAsAE572UABwAZgAbBOJAUHxOJ-eCkrCRqRmTRUAAQQwFQmTOCctnaLIih+HJ8n1UQNFKFgjHwUt4TAXgGWAQghGAQ1pF4ECNAIIgyEoDZTFOOowMg6CGPgmopjEDR8jrEo6hyKoEIVJV4zVRNuhyYp+PYjpowwWNlSIBNNXybwjz40IBLaDikBxeVcHOdxAU5DAWEIToJXyLopM0mSshZcV8gcjTsjsuAWSOVwcDPHzPIwBzHOXGjyCoUxREJejAhs1zBI4pZiBkNsVHAqAoGIaCuTMqBOkCfIwi6WLZJjESlLElTTVEcNemokgQo2Cx-FiZzoq07YsggC1kHwXM8jqUIWVMcVCvsmraKoc5Ou664LAyfA028GRTAgc4sWATAyAhfxAskuA4VNCBm3dKZcUSuByQo0JQjpBloNGuqJq63NjBm1N00W5bVvW0hNqiuo4VaoSOse+B8juuiHqm57Zvm+YlpWvMMA2hjftCf63KBqbujB8bJqetjor2gGOIxnr8gQP74X6hwTLgHk+QFHJiCyUUHCG7SivkkrVXVcq1PM0pWdKbH6JZVnIQpiVor5v1SzLKt9MMvFCFquj3JgcKHVQQUwjXGANy3CRnCNs9KXRTEYFIJ1DTPaBDQkRLEVQCRSSdGRbQgBwJDKCQSZgVAzzXEBSAAYnViKhFN+Iy2AuVhbCiLNmG9y-O83yMCcY5-MFQVTl+Kmabp-khRFUW2bajxirjUqee4iqqqF5WxpFsWoVl+WDPcJXgtV32sjCaR4C5RFSFEGQjuIVL0tQeJXbgYemfWLJo8ooKVZx4HE-Z9rcZgXPyfzrlad5IvGeZ0u3LkhTRJr7ppd6QXV6bsxS-FmVYQrOAq2oaA4D7X3shwMAAUaozpM1-lBOA+EIDqFgERJsLt4ATw0MQQ4GA1r7BnM2GsKY5pvWrE8T+cAQDEB5GSCA6wTI4lbJ9RGpBIF0BgeqZYJkdyOhkGeSsS4dACGIOAB0pQkDEFKDuA0hoCw4JhjIZgQghCBEEbkYRbojSMCAivF6uCFpwxoUjdGO894SxBNAwgqhGz7UQag9BcBMFzmrBIvBOAeT4DAL-VAJFagH25MfBmLjUGvQWm5FmgU74C2FNkUuUJJR512vCQxjCSQAH0wTxN-hY-M1iax+PmNWM8y5EHtW0XQsIPgSA1lyNWGeGQ4C8BAIeccdiFoNjYPQMkGhxDoLqKLAuXjXJgPqRmJOgTujU1KNLQUCi4DcOHqPDYfUwmswIZdPpMg6ivxhHKFKFo1RpSgCobMGBcyWLOGEHyZ4J6Gk3OAlQDkmiBD8m3JcmhTLmQVp3dY3cqAyDgDIbsKC5QEVEFAfxFoSQoNPAlcyP89wIw4Z-Jc39sopF4RFGyVZqxygADIQHBVAAAIj8g4wtaD0GMJSIuYK5BQH8IuT+wFxjQGxDSQl7Ayib3LhsrZE9dk5gRrnYWNxbJJ2OT5M5Fy6zXISCZLKFxRB6xlbM-I4FnDEDVPMYw5wZVgBlYEAZcxFjLFWOCTK5kGqzNCFZU1vRFXKrSDINVGqtWzNKFalVtqGKfBhFyNIx49waAUilNKJIk7+vSsYBSAA1Mg6E5EqLlOGyNSY9SiILGaS05ldTu2DPsXUCkIY9WzUqYNJJdRhlICvHNO9mTuTZLyGmIj3RjNKHGkeGgVEKE9YQLCyIJk8L4RofenIZCKNEX8JUjalQRubQoVtdLJhMxUPs1g3LLHksIHEKJl41jwERb2i53CkUOmcmcFkSBgCDrgBwCcHAcD-FKBwDgjBBR1H+YClASowhIG3RFVAOBvlpAEcwMBeK0hMFiFOpQG6dxwAtKIMRZxpQ+KZcS0lAoV2UoUAOKDMHNAdDONB62n7NZnmIWAMIYQCP4Bua0fd+AzyntAwoCD8A0wCGZABrIiGQAsuQ-2LFFL-DofpKwQQ2GshnGY2ecj-tiOkfI5R8jtGZCxCAA)

**Comment by lukasa1993** [comment]
> > can you share patch-package file for this fix i want to test it on my workflow, i get this error on 1.17 as well but using prisma includes instead of JSON wonder if it fixes that case too
> 
> I'll put up a PR in a couple hours with this fix

works

**Comment by DerJacques** [comment]
Thank you very much, @pcattori! Really appreciate your quick turnaround on this one :)
