### ISSUE TITLE
[Feature]: Hope to add GraphQL.

### ISSUE THREAD

**Issue by zwl1619** [remix-run/remix#657]
### What is the new or updated feature that you are suggesting?

Hope to add GraphQL.

### Why should this feature be included?

Writing less code when develop a project.

**Comment by ryanbrwr** [comment]
If I'm not mistaken, @kentcdodds said that the LoaderFunction eliminates the need for GraphQL because you can just pick which fields to return in your LoaderData.

**Comment by sergiodxa** [comment]
You can use GraphQL already, but you don't need a GraphQL client-side library.

You can do this:

1. If you have a GraphQL endpoint already outside your Remix app you can grab any GraphQL request library like [graphql-request](https://github.com/prisma-labs/graphql-request) to do your queries or mutations from inside a loader (queries) or action (mutation).
2. If you are going to build a GraphQL endpoint inside your Remix app, you can use [Resource Routes](http://remix.run/docs/en/v1/guides/resource-routes) to setup a `/graphql` endpoint, and inside your loaders or actions you have two way to use that:
    1. Use graphql-request or similar libraries to request your own GraphQL endpoint (I don't recommend you this)
    2. Run the queries/mutations against the schema directly inside the loader/actions, this will going to be faster since you don't need to receive a request, send another to `/graphql`, send a response, receive the response in original loader/action and then send it back, instead you are just going to call a function

Ultimately, you are going to only use GraphQL server-side, so you will not need libs like Apollo, each loader runs a query to get all the data it needs that specific route and return it, then you use the data from useLoaderData.

**Comment by cj** [comment]
@zwl1619 you can use https://github.com/ds300/patch-package and my patch https://gist.github.com/cj/2c915d2729e43c8f2f4fdf2c65f60f23 to support graphql files 😄
