### ISSUE TITLE
shouldRevalidate does not work when HMR is enabled

### ISSUE THREAD

**Issue by eladchen** [remix-run/remix#6575]
### What version of Remix are you using?

1.17

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Use a checkout.tsx layout route, with a loader that fetches some data.

- checkout.tsx <-- This is the only one with a loader
- checkout
  - $invoice_id
    - shipping.tsx
    - confirm.tsx

which means the following paths:

/checkout/:invoice_id/shipping
/checkout/:invoice_id/confirm

### Expected Behavior

When navigating between the routes (using the useNavigate hook) and the layout route
exports a shouldRevalidate function that returns true, the layout route loader should be invoked again.

### Actual Behavior

The layout route loader isn't invoked when navigating.

**Comment by brophdawg11** [comment]
I'm not seeing this behavior - would you be able to provide a minimal reproduction?

https://stackblitz.com/edit/remix-run-remix-s9gzqk?file=app%2Froutes%2Flayout.tsx

**Comment by eladchen** [comment]
I'll make one

**Comment by bryanparadis** [comment]
In 1.17.1:

1. Load app
2. Press nav button
3. Edit and save file
4. Wait for rebuild/hmr
5. Press nav button again

```
routes.js:100 Uncaught (in promise) TypeError: needsRevalidation.has is not a function
    at Object.shouldRevalidate (routes.js:100:32)
    at shouldRevalidateLoader (router.ts:3411:41)
    at router.ts:3285:12
    at Array.filter (<anonymous>)
    at getMatchesToLoad (router.ts:3261:43)
    at handleLoaders (router.ts:1469:49)
    at startNavigation (router.ts:1302:56)
    at Object.navigate (router.ts:1140:18)
    at hooks.tsx:986:16
    at index.tsx:897:9
```

**Comment by eladchen** [comment]
Yes

**Comment by brophdawg11** [comment]
Can someone confirm if this is still an issue in the latest release now that the dev server has stabilized in `v2_dev`?  Please provide a minimal reproduction if so (I'm still unable to reproduce) and we can dig in 🙌
