### ISSUE TITLE
[Feature]: Hope for PWA.

### ISSUE THREAD

**Issue by zwl1619** [remix-run/remix#658]
### What is the new or updated feature that you are suggesting?

Hope for PWA.

### Why should this feature be included?

It is useful.

**Comment by sergiodxa** [comment]
If you create a [Service Worker](https://sergiodxa.com/articles/using-service-workers-with-remix) for your Remix app and add the [manifest.json](https://developer.mozilla.org/en-US/docs/Web/Manifest) you can easily make your Remix app a PWA.

Using lighthouse in Chrome you can check all the things you will need do add and configure to make it installable.

**Comment by 81mark** [comment]
I am trying to enable a service worker as per https://sergiodxa.com/articles/using-service-workers-with-remix
But in the entry.client file I cannot get the sw.js to register. 

Is there an more in-depth look at how the code should be integrated into that file. As I have tried a few different ways and it does not register?

Probably my fault,
thanks

**Comment by sergiodxa** [comment]
> I am trying to enable a service worker as per https://sergiodxa.com/articles/using-service-workers-with-remix But in the entry.client file I cannot get the sw.js to register.
> 
> Is there an more in-depth look at how the code should be integrated into that file. As I have tried a few different ways and it does not register?
> 
> Probably my fault, thanks

Are you seeing an error? It would be easier to help with a reproduction app, try to do it in https://remix.new.

**Comment by 81mark** [comment]
I do not see a direct error with the code wrapped in the IF statement.
However, if it's directly trying to register the serviceWorker it complains about navigator. being undefined.

I basically added it like so.

https://stackblitz.com/edit/node-btzgz9?file=app/entry.client.tsx

And had the sw.js in the public folder. I also had the manifest.json. which I have omitted here. It shows in my app, it's only the sw.js I am having issues with.

Maybe I am doing something wrong within the entry.client.tsx file?

**Comment by sergiodxa** [comment]
> 

@81mark I opened that link but I only see the default entry.client file, I also don't see the sw.js in the public folder, did you forget to save the app?

**Comment by 81mark** [comment]
For some reason it refuses to save properly. Even if I fork it.  I will post it here for now

So basically my entry.client.tsx

```
import { hydrate } from 'react-dom';
import { RemixBrowser } from 'remix';

hydrate(<RemixBrowser />, document);

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // we will register it after the page complete the load
    navigator.serviceWorker.register('/sw.js');
  });
}
```


And Service Worker sw.js inside the public folder is 

```
self.addEventListener('fetch', (event) => {
	let url = new URL(event.request.url);
	let method = event.request.method;

	// any non GET request is ignored
	if (method.toLowerCase() !== 'get') return;

	// If the request is for the favicons, fonts, or the built files (which are hashed in the name)
	if (
		url.pathname.startsWith('/favicons/') ||
		url.pathname.startsWith('/fonts/') ||
		url.pathname.startsWith('/build/')
	) {
		event.respondWith(
			// we will open the assets cache
			caches.open('assets').then(async (cache) => {
				// if the request is cached we will use the cache
				let cacheResponse = await cache.match(event.request);
				if (cacheResponse) return cacheResponse;

				// if it's not cached we will run the fetch, cache it and return it
				// this way the next time this asset it's needed it will load from the cache
				let fetchResponse = await fetch(event.request);
				cache.put(event.request, fetchResponse.clone());

				return fetchResponse;
			})
		);
	}

	return;
});

```

**Comment by 81mark** [comment]
@sergiodxa finally got the stackblitz to save

https://stackblitz.com/edit/node-f8epsn?file=app/entry.client.tsx

**Comment by 81mark** [comment]
My issue is limited to production by the looks of it, works on localhost, but on netlify or heroku the service worker is never called. If anyone has any info why that might be, I would greatly appreciate it.

**Comment by ShafSpecs** [comment]
I have created a package to assist with PWA inRemix: https://github.com/ShafSpecs/remix-pwa

Can try it out and give feedback, suggestions, or bug reports
