### ISSUE TITLE
Better error handling for missing dependencies

### ISSUE THREAD

**Issue by juniorforlife** [remix-run/remix#6589]
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Import a library that isn't installed (eg: axios)
2. UI on localhost will break and this error will be shown in browser console: 
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
`

### Expected Behavior

ErrorBoundary being called 

### Actual Behavior

UI breaks without showing any errors

**Comment by pcattori** [comment]
Cannot reproduce in 1.19:

<img width="1269" alt="Screenshot 2023-08-09 at 1 49 19 PM" src="https://github.com/remix-run/remix/assets/1477317/804128ae-3c96-4433-9595-2a9a5115d91c">
<img width="1263" alt="Screenshot 2023-08-09 at 1 49 30 PM" src="https://github.com/remix-run/remix/assets/1477317/271b0b8b-58a5-43ba-9200-edd68e351653">

If issue persists and you can share a reproduction, we can reopen.
