### ISSUE TITLE
OSX .DS_store hidden file created by osx when modifing files breaks remix routing

### ISSUE THREAD

**Issue by Jarrodsz** [remix-run/remix#6599]
### What version of Remix are you using?

1.17

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Open any folder in app/routes on osx with the FINDER.
2. Modify any files, OSX will automatically create a hidden file .DS_store with meta data ( dont ask my why )
3. start your remix app, it will now break with the error below

```
test:dev: Error: Invalid route module file: /Users/jordan/Desktop/turbo/apps/test/app/routes/.DS_Store
```

and

```
Error: Cannot add empty string to PrefixLookupTrie
```

### Expected Behavior

Remix should handle this case, in my case i converted from v1 to v2 routes and modified the filenames true the FINDER instead of using my IDEA ( something i do never) because it was faster.

### Actual Behavior

Remix does not neglect these hidden files could be a real bugger if you don't recall or don't know.

I moved all my routes out of the remix app folder before this error popped up 

```
test:dev: Error: Invalid route module file: /Users/jordan/Desktop/turbo/apps/test/app/routes/.DS_Store
```

This one could really screw you over.

**Comment by brophdawg11** [comment]
You can control what files are treated as "route" files using the [`ignoredRouteFiles`](https://remix.run/docs/en/1.17.0/file-conventions/remix-config#ignoredroutefiles) setting in `remix.config.js`, which comes default set to `ignoredRouteFiles: ["**/.*"]` to ignore hidden files such as these.  

I would check your remix config and see if you lost that setting.
