### ISSUE TITLE
Simplified port option in 1.17.1 can't be set to 3000

### ISSUE THREAD

**Issue by tmcw** [remix-run/remix#6617]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On a fresh install of Remix 1.17.1, with the Remix App Server, basic setup:

Start the server. Happily starts on 3000.

Try to set the port to 3000:

```
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverModuleFormat: "cjs",
  future: {
    unstable_dev: {
      port: 3000,
    },
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
```

Start the server:

```
➜  my-remix-app-3 npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 300ms
Waiting for app server (7e563cd5)
> remix-serve build/index.js
Remix dev server ready
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (/Users/tmcw/tmp/my-remix-app-3/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/Users/tmcw/tmp/my-remix-app-3/node_modules/@remix-run/serve/dist/cli.js:48:84)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

Try port 3009:

```
  future: {
    unstable_dev: {
      port: 3009,
    },
```

Server unexpectedly starts on port 3000:

```
➜  my-remix-app-3 npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 279ms
Waiting for app server (7e563cd5)
> remix-serve build/index.js
Remix dev server ready
Remix App Server started at http://localhost:3000 (http://10.175.189.80:3000)
App server took 113m
```

### Expected Behavior

The value of the `port` option should probably be the port that the server starts on, and it should be configurable to be 3000.

### Actual Behavior

If the `port` option is set to 3000, the server crashes. If it's set to a non-3000 value, the server runs on port 3000.

**Comment by pcattori** [comment]
There are two servers running in dev: the app server and the dev server.

Your app server is running on port 3000, so the dev server is correctly stating that the port is taken. You need to use a separate port for the dev server. My recommendation is to not configure the port for the dev server at all and let it pick a random open port, unless you have a specific reason (e.g. only certain ports are open for security reasons).
