### ISSUE TITLE
Use TSC

### ISSUE THREAD

**Issue by Doelfke** [remix-run/remix#6628]
Old issue was closed for no reason. 

While it's faster, it forces Typescript users (the majority of devs) to also run TSC, which negates the performance gains since you essentially need to compile it twice.

Choosing esbuild is not pragmatic or objectively a good idea.  It leads to bugs that can easily be avoided. It makes much more sense to wait an extra 100ms to ensure the code you wrote won't blow up production.

_Originally posted by @Doelfke in https://github.com/remix-run/remix/discussions/6456_

**Comment by MichaelDeBoey** [comment]
@sergiodxa Already mentioned why we can't use TSC in https://github.com/remix-run/remix/discussions/6456#discussioncomment-5982854
