### ISSUE TITLE
Yet another Yarn 3 PNP issue

### ISSUE THREAD

**Issue by georgiosd** [remix-run/remix#6640]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I started with the supposedly simple requirement, to share some TS code between two Remix apps. While I was successful at doing this quite easily, my problems started when I wanted to share a dependency (`remix-validated-form`) between the app and the library.

I have created a minimal repository showing the different behavior between yarn 1, yarn 3 with node-modules and yarn 3 pnp, here: https://github.com/zerotomvp/remix-ts-integrated-monorepo

`main` branch is yarn 1 and there are corresponding branches for yarn 3.

### Expected Behavior

That this easy to do and works with PnP.

### Actual Behavior

Yarn 1: all good
Yarn 3 node-modules: all good

Yarn 3 PnP strict gives:
```
Error: remix-validated-form tried to access @remix-run/server-runtime (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: @remix-run/server-runtime (via "@remix-run\server-runtime")
Required by: remix-validated-form@virtual:f6918c7a17927f97a2f127cf3302a79aa5ee57f720ae4a34ce46af5b0465c755b3be5b37a7c066c71c3b61711cc8975d28cd0ea7adb06a5bcfbe08cba89201d9#npm:5.0.1 (via C:\Users\georgiosd\Documents\remix-4\.yarn\__virtual__\remix-validated-form-virtual-c984298908\0\cache\remix-validated-form-npm-5.0.1-bd764c4e65-f9e52a4ff7.zip\node_modules\remix-validated-form\dist\)       
Ancestor breaking the chain: remix@workspace:remix
```
Yarn 3 PnP loose imports the `remix-validated-form` package twice, creating two different versions of its context, and thus not working.

**Comment by TheRealFlyingCoder** [comment]
Yeah I think I might have solved this using the packageExtensions setting in .yarnrc.yml:

```
packageExtensions:
    remix-validated-form@*:
        dependencies:
            '@remix-run/server-runtime': 'latest'
```

**Comment by brophdawg11** [comment]
This sounds like a problem with yarn pnp?  Is there something specific that Remix is doing that causes this?

**Comment by green-0-rabbit** [comment]
Hey @georgiosd,

The issue you're encountering is due to Yarn Berry's (v2 and above) strict dependency resolution. `remix-validated-form` doesn't declare `@remix-run/server-runtime` as a direct dependency, which Yarn Berry enforces.

**Solutions**:
1. **Contact `remix-validated-form` Maintainer**: The best long-term solution is for the library to explicitly list `@remix-run/server-runtime` in its `package.json` dependencies.
2. **Temporary Fix**: Adjust your `.yarnrc.yml` with a `packageExtensions` entry:
```yaml
packageExtensions:
  remix-validated-form@*:
    dependencies:
      '@remix-run/server-runtime': 'latest'
```

This behavior is a hallmark of Yarn Berry's design to ensure more predictable and reliable builds.

**Comment by georgiosd** [comment]
Thanks @green-0-rabbit, we had to drop remix on this project to meet a deadline, but I'll let the author know.

**Comment by georgiosd** [comment]
Hey @green-0-rabbit - @airjp73 did add the peer dependency - I guess in [this commit](https://github.com/airjp73/remix-validated-form/commit/273c178dc8b9c9f06f099cc9fd751d30cbdb0ac3) but I still get the error in the project repo I posted above (updated with new version).

Any ideas?

**Comment by green-0-rabbit** [comment]
Hey @georgiosd, I just tested with the new version of `@remix-validated-form/with-zod`. Every thing seems good. 
```
 remix-jokes yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide remix-validated-form (p63ddf), requested by @remix-validated-form/with-zod
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide zod (pa2323), requested by @remix-validated-form/with-zod
```

**Comment by georgiosd** [comment]
@airjp73 sounds like that's the issue?

**Comment by Master-Hash** [comment]
the `create-remix` package has similar problem：
```bash
yarn create remix --template remix-run/remix/templates/cloudflare-pages
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 966ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ which@npm:2.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrap-ansi@npm:8.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2s 46ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 3s 233ms

C:\Users\hash\AppData\Local\Temp\xfs-665cdaa8\dlx-11728\.pnp.cjs:10576
      Error.captureStackTrace(firstError);
            ^

Error: create-remix tried to access fs-extra, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: fs-extra
Required by: create-remix@npm:2.0.1 (via C:\Users\hash\AppData\Local\Temp\xfs-665cdaa8\dlx-11728\.yarn\cache\create-remix-npm-2.0.1-c0c278e50e-a7447c16b7.zip\node_modules\create-remix\dist\)
```
and a similar workaround:
```yaml
packageExtensions:
    create-remix@*:
        dependencies:
            'fs-extra': 'latest'
```

version: yarn@3.6.3, create-remix@2.0.1
