### ISSUE TITLE
Polyfill error after `1.17.1` upgrade

### ISSUE THREAD

**Issue by brandonpittman** [remix-run/remix#6644]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Upgrade to `1.17.1`
2. Add a `require` in a module

### Expected Behavior

Shouldn't trigger error

### Actual Behavior

Triggers an error like this:

```
Uncaught TypeError: Cannot assign to read only property 'Z_BEST_COMPRESSION' of object '#<Object>'
    at node-modules-polyfills-commonjs:zlib (node-modules-polyfills-commonjs:zlib:6:25)
```

Rolling back to `1.17.0` makes the error go away.

**Comment by NavaceSystem** [comment]
Getting something similar: 
```
No matching export in "node-modules-polyfills:querystring" for import "parse"
```

**Comment by omar-minka** [comment]
Getting this same error for a library which uses axios

**Comment by acidio** [comment]
I'm also getting the same error after I added:

```
import { parse } from '@conform-to/zod'

export async function action({ request }: ActionArgs) {
  const formData = await request.formData()
  const submission = parse(formData, { schema })
}
```

**Comment by MichaelDeBoey** [comment]
This will be fixed by #6562

**Comment by omar-minka** [comment]
@MichaelDeBoey that was already merged and is on version `1.17.1`, but that's the version that's having issues with `zlib`
Thar PR fixed `crypto`(For example I was having issues with `createHash`) but not `zlib`

**Comment by markdalgleish** [comment]
@brandonpittman Could you share a minimal repro?

**Comment by brandonpittman** [comment]
@markdalgleish 

I'm not sure what kind of repro I can do. It's a work system that processes brain scan images using [dicom-parser](https://www.npmjs.com/package/dicom-parser).

**Comment by scottwillman** [comment]
Hey @brandonpittman, I've been battling this same issue with the same error and just tracked it down to the `ObjectId` import of the most recent `mongodb` version (5.6.0). If I downgrade to 5.5.0 it goes away and all is well again. Any chance this scenario is causing your issue as well?

**Comment by brandonpittman** [comment]
@scottwillman Seems to be this require of `zlib` for me.

https://github.com/cornerstonejs/dicomParser/blob/b7755a8d81221f777a1b71926b6ab8ed7dcc0976/src/parseDicom.js#L74

**Comment by markdalgleish** [comment]
I'm confident this issue is fixed due to my upstream PR: https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/pull/120.

If you can get your project to resolve to [esbuild-plugins-node-modules-polyfill@v1.1.0](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/releases/tag/v1.1.0), can you let me know if it solves your issue?

**Comment by brandonpittman** [comment]
> If you can get your project to resolve to [esbuild-plugins-node-modules-polyfill@v1.1.0](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/releases/tag/v1.1.0), can you let me know if it solves your issue?

@markdalgleish I updated to 1.18 and 1.1.0 of the polyfills package seems to be getting resolved…and the error is gone. I think we can say this issue is solved.
