### ISSUE TITLE
npx create-remix fails in empty git repo directory

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/remix#6676]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
> mkdir temp
> cd temp
> git init
> npx create-remix .
🚨 The project directory must be empty to create a new project. Please clear the contents of the directory or choose a different path.
```

I think a directory with nothing but `.git/` can safely be considered empty.  This allows folks to start first with the git repo.

Original issue raised by @jacobparis in discord:

> My dev workflow is repo first 
> I make a new repo, then open it in a cloud dev environment and start mucking with it there
> There’s no time where I have any dev tools installed before the repo is created

**Comment by CGamesPlay** [comment]
My workflow involves using direnv to specify a node version that the project will use. That means I need to set up a `.envrc` in the directory before I even run `npx`. It would be great if there were just an argument like `--overwrite` that would suppress this error and have remix simply overwrite any files which already exist.

**Comment by jacobparis** [comment]
I'd be happy with that solution as well

**Comment by brophdawg11** [comment]
cc @markdalgleish who has been doing some work on the `create-remix` CLI recently - let's sync up on this sometime next week
