### ISSUE TITLE
State within a Form causing duplicate deletions

### ISSUE THREAD

**Issue by D-Pagey** [remix-run/remix#6682]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[remix-multi-select-repro](https://github.com/D-Pagey/remix-multi-select-repro/blob/main/app/routes/_index.tsx)

After installing dependencies and running app:

1.  select 2 or more items from combobox
2. click on any of the items to delete
3. 2 items will delete instead of one

If you console.log you will see that the delete function was called with 2x different values

https://github.com/remix-run/remix/assets/26827986/a5fec505-ea98-41d6-9486-4f82d85d5b99

### Expected Behavior

If you move the combobox outside the Form, then the delete works exactly as expected. Simply filtering out one item from state and resetting state.

### Actual Behavior

When the combobox is inside the Form, the delete function gets called twice. This _only_ happens if the setState function is present in the delete function. If you replace with a console.log then the function is only called once as it should.

```
  const deleteItem = (item: string) => {
    const filtered = selected.filter((existingItem) => existingItem !== item);
    setSelected(filtered); // remove this and works as expected
  };
```

**Comment by brophdawg11** [comment]
This isn't a Remix `Form` issue - it happens if you change that wrapping element to `<form>` or even `<div>`.  I believe the issue is wrapping your entire combobox inside a `<label>` - clicking on labels can trigger clicks on embedded inputs and I assume that's applying to the buttons as well.  Removing the wrapping label seems to fix the issue.

**Comment by D-Pagey** [comment]
Amazing, that fixed it for me, thanks!
