### ISSUE TITLE
Rendering dates to locale causes hydration errors.

### ISSUE THREAD

**Issue by Apsysikal** [remix-run/remix#6684]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I am rendering components containing dates and time. As for the user, to have it displayed in a nice format I wanted to use `toLocaleTimeString()`. This caused lots of hydration errors to occur once deployed, as the server then had a different locale than the devserver on my pc.

To improve server side rendering i added the following code to my loader.
```javascript
const preferredLocale = request.headers.get("accept-language")?.split(",")[0] || "de-DE";

...

return json({
  preferredLocale,
  event,
});
```

In my exported component I use the loader to get the locale and then updated my code to use it in the `toLocaleTimeString()` function.

```javascript
const { event, preferredLocale } = useLoaderData<typeof loader>();

...

<time>`${eventDate.toLocaleTimeString(preferredLocale)}`</time>
```

This works fine when I then deploy it and load the page for the first time. But after either refreshing `CMD + R` or using an action suddenly I get hydration errors again. I'm pretty sure it's these components are causing the errors as they went away when using `suppressHydrationWarning` on the time element.

### Expected Behavior

Hydration errors should not be appearing on subsequent page-refreshes.

### Actual Behavior

Hydration errors do be appearing on subsequent page-refreshes but not on the initial page load.

**Comment by giovannibenussi** [comment]
Is eventDate static? Or it's dynamic and this issue only happens when it changes? 

Have you think about rendering the formatted time on the loaders as suggested in this [SO answer](https://stackoverflow.com/a/75284932/2043736)?

You'd need to change your loader to this:

```js
const preferredLocale = request.headers.get("accept-language")?.split(",")[0] || "de-DE";
const stamp = eventDate.toLocaleTimeString(preferredLocale)

...

return json({
  stamp
});
```

And you component to this:

```js
const { stamp } = useLoaderData<typeof loader>();

...

<time>`${stamp}`</time>
```

I hope this helps!

**Comment by Apsysikal** [comment]
As remix stringifies dates in the `json()` function I convert it to a `Date` in the component and then render it with `toLocaleTimeString` or `toLocaleDateString` respectively.

Yes, I was thinking about what you're suggesting. I've also seen this blogpost [Server-side render dates across timezones with Remix](https://www.jacobparis.com/content/remix-ssr-dates) which I was kind of put off by, as it seems quite a lot of overhead to just render some dates.

**Comment by giovannibenussi** [comment]
Got it. In my case, I decided to just pass the locale to the component using a loader. I wrote the code below to replicate your issue, could you tell me if the solution works for you or if there's something else that I need to consider?

Here's there code, you can just copy-paste it in a route to test it locally:

```js
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

export async function loader({ request }: { request: Request }) {
  const preferredLocale =
    request.headers.get("accept-language")?.split(",")[0] || "de-DE";

  return json({
    preferredLocale,
  });
}

export default function Test() {
  const { preferredLocale } = useLoaderData<typeof loader>();
  const eventDate = new Date("August 19, 1975 23:15:30");

  return (
    <ul>
      <div>
        Current time:{" "}
        <time>{eventDate.toLocaleTimeString(preferredLocale)}</time>
      </div>
    </ul>
  );
}
```

**Comment by brophdawg11** [comment]
I don't think this has anything to do with Remix specifically?  If you are server-rendering dates/times you need to ensure that both the server and client render the same content to avoid hydration mismatches.  This is just a React SSR Hydration thing - nothing Remix specific.  Please correct me and reopen if I'm misinterpreting the issue.

Rendering dates/times across timezones between server/browser is indeed a tricky problem!

**Comment by kiliman** [comment]
@jacobparis has some great blog posts about this. Some sections talk about dates in particular.

https://www.jacobparis.com/content/remix-hydration-errors
https://www.jacobparis.com/content/remix-progressive-client-only
