### ISSUE TITLE
MaxListenersExceededWarning after upgrading to Remix v1.18.0

### ISSUE THREAD

**Issue by janhesters** [remix-run/remix#6694]
### What version of Remix are you using?

v1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I don't know how to reproduce unfortunately.

I only upgraded Remix and suddenly this issue is starting to pop up.

```
(node:6176) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

This seems to only happen when running the dev mode, not after building and running production mode.

### Expected Behavior

No memory leaks.

### Actual Behavior

Memory leaks.

**Comment by pcattori** [comment]
Were you previously using `unstable_dev: true`? And are you now using `v2_dev`?

Ideally, if you can share a link to your repo or a reproduction, that would make things even easier to help!

**Comment by janhesters** [comment]
@pcattori I was not using `unstable_dev: true`.

I unfortunately can't share any link. I tried reproducing in my Remix stack as well as a blank Remix project, but both worked fine.

The issue only happens in a proprietary repo that I can't share. So there might be a chance the issue is on me, but I verified, that it only happens after upgrading Remix and activating `v2_dev` 🤔 Maybe someone who can share their code can reproduce the issue at some point, otherwise, feel free to close this 🙏

**Comment by pcattori** [comment]
By default, the new dev server restarts your app server when rebuilds occur. If you are creating a listener or connection or anything in your server code (e.g. connecting to Prisma or setting up MSW), you may want to avoid recreating those every rebuild. This would require using the `--no-restart` flag as described here: https://remix.run/docs/en/main/other-api/dev-v2#keep-app-server-running-across-rebuilds

You can see the express template for an example of this setup: https://github.com/remix-run/remix/blob/main/templates/express/server.js#L56

**Comment by pcattori** [comment]
Remix v1.19 includes docs for how to configure `--manual` (https://remix.run/docs/en/main/guides/manual-mode).

Note that `--no-restart` was renamed to `--manual`.
