### ISSUE TITLE
x-remix-redirect responses are not ignored when route has changed

### ISSUE THREAD

**Issue by n8agrin** [remix-run/remix#6695]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

https://stackblitz.com/edit/remix-run-remix-yjcpcy?file=app%2Froutes%2F_index.tsx

**Note that this is not reproducible on stackblitz, as the loader response times seem to be too fast. Download and run locally with Fast3G network speed enabled**

* Download the reproduction remix app in the link
* Load /
* Set network speed to Fast3G
* click the link that says "link to e/123/456"
* After the /e/123/456 route loads, click the "Action" button, then quickly click the link below it that says "home"
* 💥  

If you hit the error you should see something like this:

<img width="3117" alt="image" src="https://github.com/remix-run/remix/assets/6043/a2a6da09-f30c-47e1-ae20-96c4b192881a">

### Expected Behavior

The core of the issue seems to be around timing of POST requests that respond with an x-remix-redirect header.

* If the POST request finishes,
* and simultaneously the user navigates to a new route,
* the POST request cannot be canceled (it's finished).
* Remix / Router cannot cancel it, so they respect the x-remix-redirect header, even though the url and route have changed.
* Remix dutifully triggers the loaders for the redirected route
* One of the routes (e.tsx in my repro) has a shouldRevalidate function which returns false
* This causes `undefined` to be returned and 💥 

I'd expect the finished POST request's response which includes the x-remix-redirect header to be ignored.

### Actual Behavior

What actually happens is the POST request's x-remix-redirect header is not ignored.

**Comment by n8agrin** [comment]
@brophdawg11 I was able to create a reproduction case for the issue I mentioned here: https://github.com/remix-run/react-router/issues/10473#issuecomment-1601996335 

Stackblitz seems to be running the loaders in something like a wasm nodejs runtime so adjusting the network speed doesn't have any effect and the repro is not possible in their env. It is trivial to reproduce locally on: 1.17.0, 1.17.1, 1.18.0 and remix/dev branch

**Comment by brophdawg11** [comment]
🙌 Thank you for the reproduction - that was super helpful in identifying the underlying issue!  This should be fixed by https://github.com/remix-run/react-router/pull/10674 and available in the next Remix release

**Comment by n8agrin** [comment]
@brophdawg11 thank you! This was a huge reliability issue for us. Having it resolved will be a major relief.
