### ISSUE TITLE
CDN Causing infinite reload

### ISSUE THREAD

**Issue by yarbsemaj** [remix-run/remix#6703]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Place your site behind a CDN, and don't include query params in the cache key, but forward them to the origin 
2. Visit a page with a cache header with query param, then again without
3. Page gets stuck in a infinite reload loop

Issue caused by this PR
https://github.com/remix-run/remix/pull/6409

### Expected Behavior

Page should not get stuck in a loop and should load normally 

### Actual Behavior

Page gets stuck in an infinite reload loop as the url on the cache page does not match the URL of the page you are loading

**Comment by n8agrin** [comment]
@brophdawg11 I think we should drop the search comparison part of #6409.

@yarbsemaj that would fix your issue, right?

I can open a pr today

**Comment by n8agrin** [comment]
@yarbsemaj see comment here: https://github.com/remix-run/remix/pull/6707#issuecomment-1609941966

**Comment by tatemz** [comment]
I also have seen infinite reloads when upgrading to 1.18, but I have not yet been able to confirm why. I see infinite reloading when running locally and not behind a CDN.

**Comment by brophdawg11** [comment]
I think #6707 is the correct fix here for CDN's ignoring search params so we're going to look into a patch release with that in it.

@tatemz Please reply if you can figure out your issue.  Turn on `Preserve log` in the Look in the Chrome dev tools console settings and look for this type of message indicating Remix is reloading due to a mismatch:

<img width="606" alt="Screenshot 2023-06-29 at 11 14 35 AM" src="https://github.com/remix-run/remix/assets/1609022/78f14393-20b9-49b3-b43d-ab2244bb5d26">

<br/><br/>

Another root cause we identified was mismatched versions of `@remix-run/server-runtime` and `@remix-run/react` so ensure that those are the same version and you don't have duplicates (via `npm ls [package]`)

**Comment by brophdawg11** [comment]
This should be available in `1.18.1` once released, but can be tested in `1.18.1-pre.0` currently.

**Comment by tatemz** [comment]
> I think #6707 is the correct fix here for CDN's ignoring search params so we're going to look into a patch release with that in it.
> 
> @tatemz Please reply if you can figure out your issue. Turn on `Preserve log` in the Look in the Chrome dev tools console settings and look for this type of message indicating Remix is reloading due to a mismatch:
> <img alt="Screenshot 2023-06-29 at 11 14 35 AM" width="606" src="https://user-images.githubusercontent.com/1609022/249846075-78f14393-20b9-49b3-b43d-ab2244bb5d26.png">
> 
> Another root cause we identified was mismatched versions of `@remix-run/server-runtime` and `@remix-run/react` so ensure that those are the same version and you don't have duplicates (via `npm ls [package]`)

Thanks @brophdawg11. My project is definitely showing this error in the console. Thanks for the lead. I am using Shopify Hydrogen and will have to track down the deps resolution through [their repo](https://github.com/Shopify/hydrogen/)

**Comment by brophdawg11** [comment]
@tatemz yeah we chatted with the Hydrogen team yesterday about that.  The issue boils down to hydrogen having an internal dependency on 1.17.1 but if you then update to 1.18.0 in your package.json, you can get a mismatch which causes this issue.  For now just make sure you've installed the same remix versions as hydrogen is using internally.  And then bump to 1.18.0 when they do.  We discussed plans to avoid this type of mismatch in the future as well.
