### ISSUE TITLE
dev 1.18.0 error when using React v17

### ISSUE THREAD

**Issue by SeanGroff** [remix-run/remix#6710]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Setup a basic Remix project that uses Remix 1.18.0 and React/React-dom version 17.
Someting like create remix app then downgrade React.
Enable the new HMR dev server in the remix config.
Run `npm run dev`

An error occurs: 

![Screenshot_2023-06-27_at_3 25 11_PM](https://github.com/remix-run/remix/assets/4367312/973c38a0-d931-4bb2-90ed-bd222ec5542f)

cc: @pcattori Issue filed as requested on Discord

### Expected Behavior

The dev server serves up the local site without errors

### Actual Behavior

Error "Could not resolve react-dom/client"

**Comment by pcattori** [comment]
Can you try adding a `.catch()` to the offending import within your `node_modules/`? Just to verify if that does anything.

```ts
// node_modules/@remix-run/dev/dist/config/defaults/entry.dev.ts

export default () => {
  import("react");
  import("react/jsx-dev-runtime");
  import("react/jsx-runtime");
  import("react-dom");
  import("react-dom/client").catch();
  import("react-refresh/runtime");
  import("@remix-run/react");
  import("remix:hmr");
};
```

**Comment by joshmedeski** [comment]
Hey @pcattori, I'm having the same problem and catching the `react-dom/client` import fixed it!

**Comment by pcattori** [comment]
@joshmedeski or @SeanGroff can either of you share a repro of a project running correctly in Remix 1.17.1? Trying to reproduce this locally to make sure `.catch()` fixes all cases, but having issues even getting that working.
