### ISSUE TITLE
Regression from 1.17.1, type from `loader` includes `undefined` keys

### ISSUE THREAD

**Issue by nullndr** [remix-run/remix#6714]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```tsx
export const loader = () => {
  if (Math.random() > 0.5) {
    return {
      foo: "foo",
    };
  }

  return {
    bar: "bar",
  };
};

export default function Index() {
  const loaderData = useLoaderData<typeof loader>();
  return <></>
}
```

### Expected Behavior

The type of `loaderData` should be

```ts
const loaderData: {
    foo: string;
} | {
    bar: string;
}
```

Like in remix 1.17.1

### Actual Behavior

The type of `loaderData` is now (in remix 1.18) the following:

```ts
const loaderData: {
    foo: string;
    bar?: undefined;
} | {
    bar: string;
    foo?: undefined;
}
```

This is a problem since in the new version we can no more discriminate the union with the following:

```ts
if ("bar" in loaderData) {
  loaderData.foo; // No error!!
}
```

**Comment by pcattori** [comment]
To get proper type inference, you should use the `json` utility:

```ts
export const loader = () => {
  if (Math.random() > 0.5) {
    return json({ foo: "foo" });
  }
  return json({ bar: "bar" });
};

export default function Index() {
  const loaderData = useLoaderData<typeof loader>();
  //         ^? { foo: string } | { bar: string }
  return <></>
}
```

**Comment by nullndr** [comment]
Sorry, but it does not solve the problem.

I'll show you a real world example:

```ts
export const loader = async ({ request, params }: LoaderArgs) => {
  const shopifyDomain = await getShopifyDomainSession(request);
  const id = getParamsId(params);

  const { status, ...audience } = await findAudience({ shopifyDomain, id });
  checkAudienceStatus({ status });

  if (audience.isDefault) {
    return json({
      audience,
    });
  }

  return json({
    id,
    audience,
  });
};
```

With the `json()` utility the return type of `loaderData` is the following:

```ts
const loaderData: {
    audience: {
        name: string;
        description: string | null;
        isDefault: boolean;
    };
}
```

Clearly, an error.

Also, I can't understand how `json()` is supposed to solve to problem in primis since it just wraps the type inside a `TypedResponse`.

**Comment by nullndr** [comment]
You can also test this [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMAyECGATdKAERxhzgF84AzKCEOAIgAEp0RgAPAWimQDsA9GxwBjGIwBQoSLERwAVqgj9KNOgxZsOPPkP4QCjOCdNnzFy+ck30nWfFErU8ADa4CUOAF44ACgBKHwA+RBsTJ34XeQAjHC8qXyQ4qAAuJhTGCnC4YGp-AFlSAAsAOigcfjx6QLhQgAZSgFYghEkzNhhkKFUlFT9k+MoAgG52ynHO7t7lfgHcvHSARgAaOBThsYoxyTsHOAJqHGRXeGoBcWAVOABJKrtatojnNw9CEjIfFAxsfHfSHAAHhgAE8wOgIPl3H8oMFAmMTIJBGYAHoAfkm6C6PTg-BOrkkFCAA)

**Comment by pcattori** [comment]
This isn't a Remix behavior, but just how Typescript works. Here's a [reproduction of your issue without any Remix parts](https://www.typescriptlang.org/play?#code/DYUwLgBAlgJhC8EA8AVANAPgBQA8BcEKAlAhhDgFAUg4AOA9gE6QDG9AdgM6TD0CGMEIwQQsJeGQDeVCBDZdIkiACM+wgL4ilqxgQBEOvepnQAZqICyfMAAsAdIz7sY9ALZiIZAAx2ArCWlZWUZwAFdGdmgYLG01CHUiAG4KWWNgsIiomKiCAEY0FTiE5PVkijAAT1oQCAANEQAlDPYUKpAkSur6c14BIQwKAHpBoIA9AH4gA).
