### ISSUE TITLE
CF Worker cannot use "nodejs_compat" with 1.18.0 (and previous versions) due to being polyfilled  as unsupported

### ISSUE THREAD

**Issue by ivogt** [remix-run/remix#6715]
### What version of Remix are you using?

1.18.0 (happens on all previous versions)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. npx create-remix@latest 
2. Choose Cloudflare Workers
3. Enabled  "node_compat" in wrangler toml 
   add: `compatibility_flags = [ "nodejs_compat" ]`
4. Add to server.ts
```ts
import { AsyncLocalStorage } from "node:async_hooks";
new AsyncLocalStorage();
```
5. try `nom run dev`
6. Error is displayed: 
```
service core:user:remix-cloudflare-workers: Uncaught Error: Node.js async_hooks module is not supported by JSPM core outside of Node.js
```

### Expected Behavior

Do not polyfill `node:async_hooks` for workers or allow config to exclude from being poly filled.

### Actual Behavior

`node:async_hooks` gets polyfilled by `node-modules-polyfills` which changes the module to unimplemented stub.

**Comment by ivogt** [comment]
Hi @markdalgleish , sorry for tagging you but I saw you are dealing with polyfills and wanted to bring this issue to your attention. `node_compat` is unusable with workers currently.

Due to the eco-system I suspect that one way to resolve it is to allow us to selectively set what gets polyfilled  for browser and server e.g. `serverPolyfills:['crypto'] / serverPolyfill:false` or similar. https://github.com/remix-run/remix/pull/6547 attempts to fix this but we still need an option to polyfill Crypto/Buffer and turning it all off brings different set of problems. 

Thank you.

**Comment by markdalgleish** [comment]
@ivogt Thanks for adding some more context! I've just opened a PR upstream to add support for this to the underlying esbuild polyfills plugin.

**Comment by evanderkoogh** [comment]
Am I correct in understanding that there still needs to be a small change made in Remix to read a `module` configuration item and pass that through to the polyfill library?

**Comment by markdalgleish** [comment]
Yes that's right. I'm also thinking we might want to exclude `async_hooks` by default in Remix when building for non-Node environments since it'll only ever throw an error at runtime anyway.

**Comment by evanderkoogh** [comment]
Yeah.. might be worth taking a peek in the codebase if there are other modules that will just throw.

**Comment by markdalgleish** [comment]
@ivogt I've opened a PR that should address this: #6814.
