### ISSUE TITLE
[Bug]: Jokes app returns password in pages

### ISSUE THREAD

**Issue by gaetansnl** [remix-run/remix#673]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### Steps to Reproduce

Login to https://remix-jokes.lol/jokes, open dev tools, reload the page

### Expected Behavior

No password in the page

### Actual Behavior

Password appear in the page
![IXwkhWosorQLWJnkUS1vL40yP](https://user-images.githubusercontent.com/8348807/143545508-a423abb2-01e9-40d8-8dc0-25742c3d43d2.png)

**Comment by matmilbury** [comment]
What does that mean that passwords appear 'in the page'? Where exactly?

**Comment by gaetansnl** [comment]
It appears in the page source
![image](https://user-images.githubusercontent.com/8348807/143549995-2779efed-760b-4f8e-b543-a72f42c8381b.png)

**Comment by airondumael** [comment]
This happens because the whole user data is being return in the loader function. Can be fix by limiting the data in the loader.  Created a [PR](#679) for it.

**Comment by ryanflorence** [comment]
thanks, follow #679 for this :)
