### ISSUE TITLE
Express adapter is unable to provide stack traces

### ISSUE THREAD

**Issue by DanielSchiavini** [remix-run/remix#6739]
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Create any Remix app
- Use the express adapter
- Raise an error in the loader
- The error stack trace shows a location in the built index.js file, with no relation to the source code

I created an example app here: https://stackblitz.com/edit/remix-run-remix-kyq5df?file=app%2Froutes%2F_index.tsx
Note how the _index file calls `null()` just to raise an exception.
The stack trace shows only `at Object.meta (/home/projects/remix-run-remix-kyq5df/build/index.js:168:16)`.

### Expected Behavior

Remix should allow express to use the `.map` file generated to find the original source file.
It is extremely important to any application developer to find the source of errors.
Without a stack trace we are left in the dark.

### Actual Behavior

The application shows an error in a built file. If you are running a docker container, that build file is not easily accessible and hard to trace back to the original source code.

**Comment by kiliman** [comment]
Hmm.. I see the same thing with the `meta` function, but errors in `loader` show the stack trace just fine. I wonder if it's because `meta` is included in both the server and client bundles.

<img width="1272" alt="image" src="https://github.com/remix-run/remix/assets/47168/ac6f9892-6c93-4a64-833a-d8302b3fa17e">

**Comment by pcattori** [comment]
Sourcemaps were fixed in #6762 and now errors in `meta` (and everywhere else) correctly show up with sourcemap'd files:



![Image](https://github.com/remix-run/remix/assets/1477317/721c819d-620c-402b-bda3-15103c7eb016)
