### ISSUE TITLE
Unable to get the no-restart express app server working using CommonJS

### ISSUE THREAD

**Issue by tgds** [remix-run/remix#6748]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've tried the new Express server template with no-restart dev app server set up, which works nicely. I wanted to give it a go with CJS, as that's what I'm using in my project and followed the [docs](https://remix.run/docs/en/main/other-api/dev-v2#keep-app-server-running-across-rebuilds) to set it up. 

1. Create a new project with the basic `Remix App Server` template
2. Create `server.js`:
```ts
const { createRequestHandler } = require("@remix-run/express");
const { broadcastDevReady, installGlobals } = require("@remix-run/node");
const chokidar = require("chokidar");
const express = require("express");
const morgan = require("morgan");

installGlobals();

const BUILD_PATH = "./build/index.js";
/**
 * @type { import('@remix-run/node').ServerBuild | Promise<import('@remix-run/node').ServerBuild> }
 */
let build = require(BUILD_PATH);

const app = express();

// Remix fingerprints its assets so we can cache forever.
app.use(
  "/build",
  express.static("public/build", { immutable: true, maxAge: "1y" })
);

// Everything else (like favicon.ico) is cached for an hour. You may want to be
// more aggressive with this caching.
app.use(express.static("public", { maxAge: "1h" }));

app.use(morgan("tiny"));

app.all("*", createDevRequestHandler());

const port = process.env.PORT || 3000;
app.listen(port, async () => {
  console.log(`Express server listening on port ${port}`);
  broadcastDevReady(build);
});

function createDevRequestHandler() {
  const watcher = chokidar.watch(BUILD_PATH, { ignoreInitial: true });

  watcher.on("all", async () => {
    // 1. purge require cache && load updated server build
    for (const key in require.cache) {
      if (key.startsWith(BUILD_PATH)) {
        console.log("key", key);
        delete require.cache[key];
      }
    }
    build = require(BUILD_PATH);
    // 2. tell dev server that this app server is now ready
    broadcastDevReady(build);
  });

  return async (req, res, next) => {
    try {
      //
      return createRequestHandler({
        build: build,
        mode: "development",
      })(req, res, next);
    } catch (error) {
      next(error);
    }
  };
}
```
3. run `remix dev --no-restart -c 'node ./server.js'`

### Expected Behavior

After making a change in a route, you should get HMR and HDR update in the browser and see the change.

### Actual Behavior

You get the rebuild message in the console:
```
 info  rebuilding... (~ app/routes/_index.tsx)
 info  rebuilt (93ms)
```
but you don't see the change in the browser.  The notification to the dev server seems to be sent correctly. 
Even after a full browser refresh, you don't get to see the update.

**Comment by mattf96s** [comment]
https://github.com/xHomu/remix-v2-server/tree/cjs-server.js

**Comment by israelss** [comment]
I have used the server from the repo @mattf96s has suggested, and this error ocurred randomly to me.
So until it gets fixed, I'll stay without v2 server + in remix v1.17.1

**Comment by pcattori** [comment]
@tgds `server.js` is for using a custom server, whereas you've indicated that your project uses the Remix App Server. These are mutually exclusive. Remix App Server does not support `--no-restart` so if you want that, you'll have to use a custom server.

That said, `remix dev --no-restart -c 'node ./server.js'` should still work here since that command uses `-c` to opt-out of Remix App Server.

**Comment by pcattori** [comment]
You are using a relative path for `BUILD_PATH`, but `require.cache` uses absolute paths. You can resolve your build path to an absolute path and that fixes the issue:

```diff
- const BUILD_PATH = "./build/index.js";
+ const path = require("path");
+ const BUILD_PATH = path.resolve("./build/index.js");
```

**Comment by tgds** [comment]
> You are using a relative path for `BUILD_PATH`, but `require.cache` uses absolute paths. You can resolve your build path to an absolute path and that fixes the issue:
> 
> ```diff
> - const BUILD_PATH = "./build/index.js";
> + const path = require("path");
> + const BUILD_PATH = path.resolve("./build/index.js");
> ```

thank you @pcattori, that was it!

I was basically following this line form the docs:
> If you're using CJS but looking at an ESM template, you'll need to swap out import cache busting with require cache busting:

The ESM template actually uses `const BUILD_PATH = "./build/index.js";`. It might be worthwhile to highlight that this has to be adjusted too.
