### ISSUE TITLE
remix --port argument is not working

### ISSUE THREAD

**Issue by everdimension** [remix-run/remix#6752]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
./node_mobules/.bin/remix dev --port 4001
```

### Expected Behavior

Dev server will start on port 4001

### Actual Behavior

Dev server starts on port 3000

---

This option is mentioned in the docs: https://remix.run/docs/en/1.18.1/other-api/dev#remix-dev---port
But it seems to take no effect

At the same time, setting `PORT` as an env variable works:

```
PORT=4001 ./node_mobules/.bin/remix dev
```

**Comment by WesleyYue** [comment]
@pcattori I'm confused about the response. OP is talking about the dev server, not the app server. I'm seeing this issue as well where --port does not affect the **dev** server.

**Comment by pcattori** [comment]
`remix dev` spins up _two_ servers: the app server and the dev server.

The dev server is a glorified compiler running in watch mode.
It is only responsible for rebuilding your app and performing hot updates.
It **is not** responsible for sending the SSR'd document, loaders, actions, etc...
Those are responsibilities of the app server.

The dev server has exactly _one_ endpoint: `/ping`.
That endpoint is used internally for coordinating hot updates.

If I run `remix dev --port 4004`, I can indeed send a `curl` to `/ping`:

<img width="443" alt="Screenshot 2023-07-15 at 8 03 46 PM" src="https://github.com/remix-run/remix/assets/1477317/609dcc84-50b1-43a9-a64d-4ad1e9d2b709">

👆 so `remix dev --port` is working correctly.

If you want to change the port your app runs on in development, you need to change your _app server_ port.
For example, if you are using `remix-serve` you can do:

```sh
remix dev -c "remix-serve --port 4001"
```

👆Note that `--port` is a flag for `remix-serve` (aka your app server), not a flag for `remix dev` itself

**Comment by WesleyYue** [comment]
Ah, I see, thank you for the clarification. I feel like this definition of "dev server" is a departure from what the term normally means, and I wonder if there might be a better term to make this more clear.

Separately, I think even with this new understanding, the documentation is still wrong? The documentation for `remix dev --port` linked in the OP says:

> Launches the app server on a given port.
> 
> By default, the port is set to 3000. If port 3000 is unavailable, the dev command will attempt to find another port that is open.

**Comment by pcattori** [comment]
The docs originally linked have this header:

<img width="824" alt="Screenshot 2023-07-15 at 10 58 12 PM" src="https://github.com/remix-run/remix/assets/1477317/bf53cbb4-9c6d-4d50-8737-fd78bbff8438">
