### ISSUE TITLE
Failed to run ESLint in projects that doesn't use TypeScript

### ISSUE THREAD

**Issue by akamfoad** [remix-run/remix#6753]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. On a non-TypeScript project that uses `^1.17.0`, upgrade to `1.18.1`
2. Run `yarn eslint ./app`
3. Observe ESLint fails due to this error:

```
➜ yarn eslint .\app\
yarn run v1.22.19
$ "C:\XXX\node_modules\.bin\eslint" .\app\

Oops! Something went wrong! :(

ESLint: 8.44.0

Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @remix-run/eslint-config#overrides[0]': Cannot find module 'typescript'
Require stack:
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\astUtils.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\index.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\rules\adjacent-overload-signatures.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\rules\index.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\index.js
- C:\XXX\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Referenced from: C:\XXX\node_modules\@remix-run\eslint-config\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\astUtils.js:30:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

JavaScript apps shouldn't need to install `typescript` to make ESLint work, the TypeScript ESLint plugins and Rules should be applied only when the project is actually uses TypeScript.

ESLint do the linting as configured correctly.

### Actual Behavior

From 1.18.0 and above JavaScript apps must install `typescript` to make ESLint work, the TypeScript ESLint plugins and Rules are  applied even though the project uses JavaScript and JSX only.

ESLint fails to run since typescript can't be found in the project, as the project doesn't use TypeScript but some ESLint plugins/rules depend on it.

```
➜ yarn eslint .\app\
yarn run v1.22.19
$ "C:\XXX\node_modules\.bin\eslint" .\app\

Oops! Something went wrong! :(

ESLint: 8.44.0

Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @remix-run/eslint-config#overrides[0]': Cannot find module 'typescript'
Require stack:
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\astUtils.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\index.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\rules\adjacent-overload-signatures.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\rules\index.js
- C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\index.js
- C:\XXX\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Referenced from: C:\XXX\node_modules\@remix-run\eslint-config\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\XXX\node_modules\@typescript-eslint\eslint-plugin\dist\util\astUtils.js:30:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### ESLint config

```json
{
  "extends": [
    "@remix-run/eslint-config",
    "@remix-run/eslint-config/node",
    "prettier"
  ]
}
```

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction of this issue?  I'm unable to reproduce when upgrading a simple JS project from `1.17.0` to `1.18.1`.  Even without a `typescript` dependency, it's still available for the linter as a nested dependency:

```
> npm ls typescript
test-eslint-117-2@ /Users/matt/me/shopify/repos/playgrounds/test-eslint-117-2
└─┬ @remix-run/eslint-config@1.18.1
  ├─┬ @typescript-eslint/eslint-plugin@5.61.0
  │ └─┬ tsutils@3.21.0
  │   └── typescript@5.1.6 deduped
  └── typescript@5.1.6
```

> JavaScript apps shouldn't need to install typescript to make ESLint work, the TypeScript ESLint plugins and Rules should be applied only when the project is actually uses TypeScript

We have plans to change up the CLI in v2 such that the JavaScript/TypeScript templates are better segmented and I expect we'll be removing the TS lint rules from the JS template in the process.

**Comment by akamfoad** [comment]
So I tried again, it was happening for 4 projects of mine. Looks like it only happens in projects that was boostrapped with older versions of the templates were typescript wasn't a dev dependency, probably around here, not sure which version they correspond to: https://github.com/remix-run/remix/blame/331678bd60e2376a604389f856f68a38e109fead/templates/remix/package.json 

Maybe it was 1.1.0 or versions around that, newer projects do not have that problem since typescript is defined in their template's devDependencies

**Comment by brophdawg11** [comment]
ok - glad that's working for you!  This process should be improves for new JS projects once we release the updated `create-remix` CLI in v2
