### ISSUE TITLE
Run seed.ts

### ISSUE THREAD

**Issue by mhanifmuhsin** [remix-run/remix#6765]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

run  : npx ts-node --require tsconfig-paths/register prisma/seed.ts

### Expected Behavior

Seed success 

### Actual Behavior

<img width="683" alt="Screenshot 2023-07-04 at 22 20 04" src="https://github.com/remix-run/remix/assets/68141840/be527433-32a0-4786-9f41-f2fe69feec24">

**Comment by brophdawg11** [comment]
This doesn't appear to be an issue in the core Remix repo but instead in an app template or stack, so I think this needs to be filed in the repo that's instructing you to run `npx ts-node --require tsconfig-paths/register prisma/seed.ts`.  

What is `fullstack-remix-one`?  

I know both https://github.com/remix-run/indie-stack or https://github.com/remix-run/blues-stack use a Prisma seed file as well.

**Comment by mhanifmuhsin** [comment]
[fullstack-remix-one](https://github.com/mhanifmuhsin/fullstack-remix-one.git) this is the repository i learned js and prisma ,
I think the problem is in "type": "module" in package.json, and it was already there when I installed Remix 1.18.1, 
if I remove the "type" : "module" then the seed is successful.
And my assumption is  [https://github.com/remix-run/indie-stack](https://github.com/remix-run/indie-stack) or [https://github.com/remix-run/blues-stack](https://github.com/remix-run/blues-stack) use a Prisma seed file as well, because there is no "type": "module" in package.json

**Comment by brophdawg11** [comment]
See https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension.  It looks like you need to either run `ts-node --esm`  or enable `compilerOptions.esModuleInterop` in your `tsconfig.js`

**Comment by mhanifmuhsin** [comment]
not working

**Comment by norayr93** [comment]
Having the same issue. Just installed the remix app and followed the docs - [Jokes tutorial](https://remix.run/docs/en/main/tutorials/jokes).
`npx ts-node --require tsconfig-paths/register prisma/seed.ts` throws the same exception as mentioned above.

**Comment by norayr93** [comment]
I will check, thanks. The interesting part is that I have followed remix tutorial and they include `"type": "module"` inside package.json.

**Comment by brophdawg11** [comment]
Which tutorial are you referring to?  The blog tutorial uses the [indie stack](https://github.com/remix-run/indie-stack/blob/main/package.json)  and the jokes app  uses the basic [Remix App Server template](https://github.com/remix-run/remix/blob/main/templates/remix/package.json).  Neither of those include `type:module` by default?

**Comment by iangregsondev** [comment]
Why has this been closed ?

This is still an issue.

If you remove the type:module then seed.ts works but npm run dev no longer works..

```
❯ npm run dev

> dev
> remix dev --manual


 💿  remix dev

(node:19590) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Error loading Remix config at /Users/ian/Development/remix/remix-jokes/remix.config.js
SyntaxError: Unexpected token 'export'
    at Object.readConfig (/Users/ian/Development/remix/remix-jokes/node_modules/@remix-run/dev/dist/config.js:72:13)
    at async Object.dev (/Users/ian/Development/remix/remix-jokes/node_modules/@remix-run/dev/dist/cli/commands.js:179:18)
    at async Object.run (/Users/ian/Development/remix/remix-jokes/node_modules/@remix-run/dev/dist/cli/run.js:192:7)

```

**Comment by iangregsondev** [comment]
What I did to get round it was , remove "type":module from the package.json

run the seed.ts as per the tutorial Jokes.

then add it back into the package.json otherwise

npm run dev

does not work

**Comment by mhanifmuhsin** [comment]
This is what I meant at that time, when I first reported this issue, thank you @iangregsondev , for caring about this issue, hopefully there will be a solution

**Comment by kiliman** [comment]
Instead of using `ts-node`, you should install `tsx` instead. It supports `type: "module"` directly.

```bash
npm install -D TSX
npx tsx prisma/dev.db
```

**Comment by iangregsondev** [comment]
Thanks @kiliman - works great!

**Comment by bbugh** [comment]
Hi, I came to report this issue. Following the tutorial exactly results in the error in the original post. `package.json` does have a `"type": "module"` line at that time in the tutorial.

Switching to tsx works, but it would probably be nice to fix the docs.

**Comment by brophdawg11** [comment]
Would you mind filing a new issue that includes the template you're leveraging and the specific spot in the docs that is giving issues and needs to be updated?  I've forgotten the specifics of the above but at the time, the templates being referenced were _not_ including `type:module` and thus everything was working as expected.

PRs are also welcome if it's as simple as changing a docs recommendation from `ts-node` to `tsx`.

**Comment by mhanifmuhsin** [comment]
Thank's ☺️

**Comment by mhanifmuhsin** [comment]
Thanks ☺️
