### ISSUE TITLE
Dev server v2 causes spurious restarts of Architect sandbox services, causing sluggish DX

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#6780]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Architect supports [sandbox plugins](https://arc.codes/docs/en/guides/plugins/sandbox) that implement the `sandbox.start` method to launch arbitrary background services. (For example, my own plugin [@nasa-gcn/architect-plugin-search](https://github.com/nasa-gcn/architect-plugin-search) starts up ElasticSearch to mock up Amazon OpenSearch).

If you are using the Remix `v2_dev` future feature with Architect and you have sandbox plugins, then every time that you change a file that triggers a rebuild (for example, a route module), it stops restarts _all_ of the sandbox services. This results in a very sluggish and unpleasant DX.

Turning off `v2_dev` fixes the issue: with the v1 dev server, the sandbox plugins are started _once_ when you launch `npm run dev`, and are _not_ restarted when you touch files that trigger rebuilds.

Here is an example project with a [trivial sandbox plugin](https://github.com/lpsinger/remix-bug-report-spurious-sandbox-starts/blob/dev-v2/plugin-example.js) that simply prints a message with `console.log` when it (re)starts.

- `v2_dev: true` - https://github.com/lpsinger/remix-bug-report-spurious-sandbox-starts/tree/dev-v2
- `v2_dev: false` - https://github.com/lpsinger/remix-bug-report-spurious-sandbox-starts/tree/dev-v1

### Expected Behavior

Run `npm run dev` and make some changes to route module files. You should see the log message `Starting example service` _only once_ at the startup of `npm run dev`, and you should not see that log message repeated as you are changing the route module files.

### Actual Behavior

On the example branch with `v2_dev: true`, you see the log message `Starting example service` when `npm run dev` starts, and then you see it again every time you save a change to a route module file.

**Comment by pcattori** [comment]
@lpsinger can you try using the `--no-restart` flag in your `dev` script? That should prevent restarts, but need to confirm that the sandbox plugin correctly sends dev ready messages during rebuilds.

**Comment by pcattori** [comment]
> That works! Should I make a PR for that?

@lpsinger  That'd be great! Thanks 🙏

**Comment by lpsinger** [comment]
> > That works! Should I make a PR for that?
> 
> @lpsinger That'd be great! Thanks 🙏

 #6781
