### ISSUE TITLE
Remix build fails with Vanilla Extract outside of root.tsx

### ISSUE THREAD

**Issue by jwpaine** [remix-run/remix#6794]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Fresh install remix: npx create-remix@latest
2. Install Vanilla Extract CSS: npm install -D @vanilla-extract/css
3. Per the Styling Guide, create a file `app/components/button/index.js` with the following:

```
import * as styles from "./styles.css"; 

export const Button = React.forwardRef(
  ({ children, ...props }, ref) => {
    return (
      <button
        {...props}
        ref={ref}
        className={styles.root}
      />
    );
  }
);
Button.displayName = "Button";
``` 

4. Create a file `app/components/button/styles.css.ts` with the following:

``` import { style } from "@vanilla-extract/css";

export const root = style({
  border: "solid 1px",
  background: "white",
  color: "#454545",
});
```

5. Import and use the `Button` component within `routes/_index.tsx` :

```
 import {Button} from "../components/button"
 
 export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <Button/>
    </div>
  );
}
```

### Expected Behavior

The project should compile and the button should assume appropriate styling.

### Actual Behavior

```
info  building...
X [ERROR] Transform failed with 1 error:
<stdin>:14:8: ERROR: Expected ">" but found "{" [plugin css-side-effects-plugin]

    app/routes/_index.tsx:20:23:
      20 │ import { Button } from "../components/button";
         ╵                        ~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssSideEffectImports.js:64:12:
      64 │       build.onLoad({
         ╵             ~~~~~~
``` 

## NOTE:
Vanilla-extract works as expected when imported into root.tsx:

1. Create file `root.css.ts` with the following:
``` 
import { style } from "@vanilla-extract/css";

export const root = style({
  background: "red",
  color: "#454545",
});
```

2. Add import to `root.tsx` :

``` 
...
import * as styles from "./root.css";
...
<body className={styles.root}>
...
```

On build, the background is red as expected.

**Comment by markdalgleish** [comment]
I had a look into this and it turns out it's an issue with HMR for `.js` files, not a Vanilla Extract issue. Looks like a fix for a different issue inadvertently fixed this issue too since we're now using the correct loader for `.js` files: https://github.com/remix-run/remix/pull/6762

I'm closing this as fixed. Just to confirm, can you check whether you're still experiencing this issue with the `1.19.0-pre.0` release? Updating to this pre-release fixes my local repro. Otherwise, if you're still having issues, let me know.
