### ISSUE TITLE
Assets referenced within linked style sheets vanish when dev rebuilds

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#6799]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Minimal reproducing example: https://github.com/lpsinger/remix-bug-report-assets-in-css

1. Create a Remix project.
2. Add a [regular style sheet](https://remix.run/docs/en/main/guides/styling#regular-stylesheets) that itself refers to an asset such as an image or a font. For example:
```css
.airplane {
    width: 400px;
    height: 400px;
    background-image: url('./airplane.jpg');
}
```

3. Import the style sheet in the root module:

```tsx
import styles from './style.css';

export const links: LinksFunction = () => [
  { rel: "stylesheet", href: styles },
];

...
```

4. Use the style in a route module:

```tsx
export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <h1>Welcome to Remix</h1>
      <div className="airplane">There should be an airplane image here</div>
    </div>
  );
}
```

5. Run `npm run dev` and view the site in an Incognito browser window.
6. Make some changes to a route module to trigger a rebuild. Close the browser window and view the site in a new Incognito window.

### Expected Behavior

Every time that `npm run dev` rebuilds and triggers a reload, the asset that is referred to in the style sheet should get copied over to the `public/build/_assets` and should be shown in the browser.

```
$ ls public/build/_assets/
airplane-U3W2FKRE.jpg   style-KT6W33UV.css
```

![Screenshot 2023-07-09 at 08 19 06](https://github.com/remix-run/remix/assets/728407/bb73cd06-122c-4bd5-89db-098ecbec2c5c)

### Actual Behavior

The referenced asset is only copied over on the _initial_ build when `npm run dev` first launches. Every time that you trigger a rebuild by making a change to a route module, the referenced asset is _deleted_ from the `public/build/_assets/` directory and is missing from the view in the browser.

```
$ ls public/build/_assets/
style-KT6W33UV.css
```

![Screenshot 2023-07-09 at 08 21 06](https://github.com/remix-run/remix/assets/728407/a335e31f-753b-44e7-ae67-8c0828e4daed)

**Comment by vcmiranda** [comment]
Same is happening to me but with fonts instead of images.

**Comment by pcattori** [comment]
@lpsinger do you know if this is a bug introduced in 1.18.1? or can you reproduce on older versions?

**Comment by SCasarotto** [comment]
This was not an issue in 1.17 for me but was in 1.18.1. I haven't tried to downgrade.
