### ISSUE TITLE
cloudflare: @cloudflare/workers-types is stale

### ISSUE THREAD

**Issue by elithrar** [remix-run/remix#6809]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Interact with any Cloudflare platform feature and observe the types are stale.

### Expected Behavior

Types are not stale.

### Actual Behavior

Remix currently pins to an old version of the https://github.com/cloudflare/workers-types repo - types are now generated from https://github.com/cloudflare/workerd/tree/main/types/defines

* The old versions are < 4.0 - e.g. https://github.com/remix-run/remix/blob/main/templates/cloudflare-workers/package.json#L21C1-L22C1 - `"@cloudflare/workers-types": "^3.19.0"`
* New versions are > 4.0 - e.g. `4.20230628.0` per https://www.npmjs.com/package/@cloudflare/workers-types?activeTab=versions

Ask: The next Remix point release should update these types - e.g. pin to `^4.0` to capture all types in the 4.x series.

**Comment by MichaelDeBoey** [comment]
This would be a breaking change, we'll update the types in v2 (which is done in #5732)
