### ISSUE TITLE
`fetcher.submit()` failing inside react-table 

### ISSUE THREAD

**Issue by eldiranym** [remix-run/remix#6829]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a simple column or two with React Table (https://github.com/TanStack/table). From there, using any interaction with a column through `fetcher.submit()` fails, but using `Form` works as expected

One example:
```
// actionColumn.tsx
export const actionColumn = (onEdit: (row: Action) => void) =>
 columnHelper.accessor("action", {
        header: "",
        cell: (props) => (
            <Action
                id={props.getValue()}
                name={props.row.original.name}
            />
        ),
});

//  action.tsx
export function Action({id, name}: props) => {
     const fetcher=useFetcher();
     return (
         <Button onClick={ () => fetcher.submit({id, name}, { method: "POST" } }>
             Click Me!
         </Button>
     )
}
```

This is just a dummy example of course, but any and all of our attempts so far to use the useFetcher within a column in a React Table from TanStack v8 has caused it to fail completely.

An example of an action that would work would be:
```
// action.tsx
export function Action({id, name}: props) => {
     return (
        <Form method="POST">
        <input type="hidden" name="id" value={id} />
        <input type="hidden" name="name" value={name} />
         <Button  type="submit">
             Click Me!
         </Button>
        </Form>
     )
}
```

### Expected Behavior

Both Form and fetcher.submit() should cause a submit.

### Actual Behavior

Form submits correctly, fetcher.submit() ends up canceling and never submitting

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction of the issue?  My hunch is that the components are being unmounted/remounted which would delete and recreate any fetchers created within.  

To confirm/deny this, I would try creating the fetcher at a higher level and passing it into the components as a prop, so it persist any unmounting/remounting done by react table.

**Comment by okalil** [comment]
I also experienced this issue, but wrapping cell callback with useCallback solved it for me
