### ISSUE TITLE
Server code pruning not working 

### ISSUE THREAD

**Issue by hungtcs** [remix-run/remix#6839]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1.  run `pnpm create create-remix@latest` or create via npm
2.  open `app/routes/_index.tsx` and append 

      ```ts
      // add on top
      import fs from 'fs';
      
      export async function loader() {
      
        console.log(`\n\nloader run...`);
        console.log({ fs });  // <- use fs or any other nodejs packages
        console.log('\n\n');
      
        return null;
      }
      ```

3. `npm run build` or `npm run dev`
4. open `public/build/routes/_index-[hash].js` or open in browser devtools network panel
5. check the js file content

### Expected Behavior

Server only code should be pruning from client code.

### Actual Behavior

1. if not use `fs` (or any nodejs package) in loader function it works fine, for instance, the generated code does not contain the test function

    ```ts
    function test() {
      console.log('test function run');
    }
    
    export async function loader() {
    
      console.log(`loader run...`, test);
    
      return null;
    }
    ```
    The generated  code is:
    ```js
    import { c as t, e as o } from "/build/_shared/chunk-DWFMXSZ6.js";
    var e = t(o()),
      i = () => [
        { title: "New Remix App" },
        { name: "description", content: "Welcome to Remix!" },
      ];
    function n() {
      return (0, e.jsx)("div", {
        style: { fontFamily: "system-ui, sans-serif", lineHeight: "1.8" },
        children: (0, e.jsx)("h1", { children: "Welcome to Remix" }),
      });
    }
    export { n as default, i as meta };
    ```

2. if use `fs`, `jsonwebtoken` (any more i tested), the generated code will contain dependent code, and browser may throw some error (eg. jsonwebtoken)

    ![image](https://github.com/remix-run/remix/assets/11692935/368f913f-3997-4899-9c75-204924d2a8f5)
    
    ![image](https://github.com/remix-run/remix/assets/11692935/23926655-7249-4143-81b6-4b31ead86455)

**Comment by hungtcs** [comment]
One possible solution is to use the dynamic import function to import the package, but I don't believe that is the correct solution.

```ts
export async function loader() {
  const jwt = await import('jsonwebtoken')

  console.log(`loader run...`, jwt);

  return null;
}
```

![image](https://github.com/remix-run/remix/assets/11692935/e19d2685-245f-478a-8c25-7a589b7d20c9)

**Comment by jkarttunen** [comment]
I could not repeat this.

1. I ran `npx create-remix` (it installed remix 1.81.1
2. added step 2
3. Run `npm run build`

I can only find the text `loader run` from server directory `/build`, but not from web build `/public/build`.

Are you sure you are not serving the wrong directory to client? Which server are you using?

**Comment by hungtcs** [comment]
Hello, I ran it again, and I encountered the same issue. I have created a repository to reproduce the problem. Please take a look at it (I didn't ignore the "public/build" folder that I built).

- <https://github.com/hungtcs/remix-server-code-pruning-test>

```
$ npx create-remix 
? Where would you like to create your app? remix-code-split-test
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? JavaScript
? Do you want me to run `npm install`? Yes
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠙ idealTree:@temp/remix-code-split-test: sill idealTree buildDeps
```

My environment is as follows (I am using the Windows Subsystem for Linux) :

```shell
$ npx envinfo --system --npmPackages   

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F
    Memory: 10.43 GB / 15.55 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  npmPackages:
    @remix-run/css-bundle: ^1.18.1 => 1.18.1 
    @remix-run/dev: ^1.18.1 => 1.18.1 
    @remix-run/eslint-config: ^1.18.1 => 1.18.1 
    @remix-run/node: ^1.18.1 => 1.18.1 
    @remix-run/react: ^1.18.1 => 1.18.1 
    @remix-run/serve: ^1.18.1 => 1.18.1 
    @types/react: ^18.0.35 => 18.2.15 
    @types/react-dom: ^18.0.11 => 18.2.7 
    eslint: ^8.38.0 => 8.45.0 
    isbot: ^3.6.8 => 3.6.12 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.0.4 => 5.1.6
```

**Comment by hungtcs** [comment]
> I could not repeat this with npm
> 
> 1. I ran `npx create-remix` (it installed remix 1.81.1, selected :  Just the basics / Remix app server / Javascript)
> 2. added step 2
> 3. Run `npm run build`
> 
> I can only find the text `loader run` from server directory `/build`, but not from web build `/public/build`.
> 
> Are you sure you are not serving the wrong directory to client? Which server are you using?

I may not describe clearly in some places. It does not contain the source code of the `loader` function, but it contains the source code of the `fs` that the loader function depends on.

**Comment by kiliman** [comment]
All imports from standard node libraries should be exported from a _*.server_ file. This will ensure that references to server code doesn't end up in the client bundle.
```ts
// libs/node.server.ts
export * as fs from 'node:fs';
export * as fsp from 'node:fs/promises';
```
```ts
// some/route.tsx
import fs from '~/libs/node.server'
...
```

**Comment by hungtcs** [comment]
@kiliman It totally works, I'm going to do it this way, thanks for your answer
