### ISSUE TITLE
[BUG]: Remix watch command forces NODE_ENV to development

### ISSUE THREAD

**Issue by jaidetree** [remix-run/remix#6841]
### What version of Remix are you using?

1.18

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a remix app using the express adapter
2. Run `NODE_ENV=test remix watch`
3. In a remix loader in root.tsx, add `console.log(process.env.NODE_ENV)`
4. In express, log `process.env.NODE_ENV`
5. Run the express app with `NODE_ENV=test node server.js` (or whichever command starts the server)

Hit a remix route and see what gets logged.

### Expected Behavior

- Express will print `test`
- The Remix route will also print `test`

### Actual Behavior

- Express will print `test`
- The Remix route will print `development`.

I traced it down and it seems the issue stems from the liveReload server used by the watch command:

1. The watch command calls `devServer.liveReload(config);` https://github.com/remix-run/remix/blob/8268142371234795491070bafa23cd4607a36529/packages/remix-dev/cli/commands.ts#L207
2. Which then calls `await watch(...)`
3. Which forces the mode\env var https://github.com/remix-run/remix/blob/8268142371234795491070bafa23cd4607a36529/packages/remix-dev/devServer/liveReload.ts#L48

**Comment by pcattori** [comment]
@jaidetree 🟢

**Comment by pcattori** [comment]
Fixed by #7117

**Comment by jaidetree** [comment]
Ack! I knew there was something I forgot to do 😅 Thank you!!
