### ISSUE TITLE
Failure on vercel integration while the build deployment was success

### ISSUE THREAD

**Issue by dellwatson** [remix-run/remix#6845]
### What version of Remix are you using?

1.14

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

deploy this repo into vercel:
https://github.com/dellwatson/remix-test-three

### Expected Behavior

it should shows error on build or work like in localhost

### Actual Behavior

while it's running on local and shows no error on building in the local+ vercel. 
the site https://remix-test-three-seven.vercel.app/ still produce error
and shows Unexpected Server Error

**Comment by ryanflorence** [comment]
Please follow the Vercel docs for deploying Remix to their service. They've got dedicated resources and libraries to make it a great experience:

https://vercel.com/docs/frameworks/remix
