### ISSUE TITLE
npm ERR! Missing script: "start" when choosing vercel deployment

### ISSUE THREAD

**Issue by tombohub** [remix-run/remix#6846]
### What version of Remix are you using?

1.18.1",

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

follow tutorial on: https://remix.run/docs/en/main/tutorials/jokes

1. npx create-remix@latest
2. chose these options:
```
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```
3. cd remix-jokes
4. npm run build
5. npm start

### Expected Behavior

To have running server

### Actual Behavior

error:

```
npm ERR! Missing script: "start"
....
```

content of package.json:

```json
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@remix-run/css-bundle": "^1.18.1",
    "@remix-run/node": "^1.18.1",
    "@remix-run/react": "^1.18.1",
    "@remix-run/vercel": "^1.18.1",
    "@vercel/node": "^2.10.3",
    "isbot": "^3.6.8",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.18.1",
    "@remix-run/eslint-config": "^1.18.1",
    "@remix-run/serve": "^1.18.1",
    "@types/react": "^18.0.35",
    "@types/react-dom": "^18.0.11",
    "eslint": "^8.38.0",
    "typescript": "^5.0.4"
  },
  "engines": {
    "node": ">=14.0.0"
  }
}
```

**Comment by tombohub** [comment]
Using Vercel doesn't give `npm run start` script?

**Comment by brophdawg11** [comment]
You can run the development server with `npm run dev`.  Since Vercel handles your prod servers I think `npm run start` is omitted in favor of using Vercels tooling to run the built application in production mode.
