### ISSUE TITLE
LiveReload not working

### ISSUE THREAD

**Issue by tombohub** [remix-run/remix#6847]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

follow tutorial: https://remix.run/docs/en/main/tutorials/jokes

1. npx create-remix@latest
2. chose these options:
```
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Remix Server 
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```
3. cd remix-jokes
4. Replace the contents of app/root.tsx with this:
```javascript
import { LiveReload } from "@remix-run/react";

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        />
        <title>Remix: So great, it's funny!</title>
      </head>
      <body>
        Hello world
        <LiveReload />
      </body>
    </html>
  );
}
```
5. try to change 'Hello World' to something else

### Expected Behavior

To live reload and see changes in browser

### Actual Behavior

Id doesn't live reload. I have to refresh browser manually to see changes

**Comment by pcattori** [comment]
Fixed by #6724 , available in `1.19.0-pre.4`
