### ISSUE TITLE
is:issue is:open Why remix is so slow?

### ISSUE THREAD

**Issue by eran-or** [remix-run/remix#6849]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

just run npx create-remix@latest --template remix-run/indie-stack blog-tutorial

open the project in the browser 
Go to the project code and then move to the browser with the keyboard to see the change. 
This is the build result after npm run dev command:
dev:serve
> binode --require ./mocks -- @remix-run/serve:remix-serve ./build

🔶 Mock server running
Remix App Server started at http://localhost:3000 (http://192.168.1.62:3000)
 info  app server ready (3.2s)
 info  hmr

How can someone work like this? 
(I've opened this as a bug because it's critical in those days when someone like jule verne can travel around the world in 3.2 seconds haha).

### Expected Behavior

should be instant like somewhere around 50ms.

### Actual Behavior

 info  app server ready (3.2s)

**Comment by cliffordfajardo** [comment]
3.2s for fresh template is a quite a bit of time 🤔 
curious, what are your computer's specs?
- Operating system, GB RAM, CPU?

**Comment by eran-or** [comment]
I'm working with old mac from 2013, but this is not the issue. When I met remix it was fast on the same computer, almost fast like create-react-app. But now, this is impossible. I have no other issues with other frameworks or speed in general. It's only remix, which the build takes a lot of time.
