### ISSUE TITLE
Remix unable to resolve dependencies deeper in its dependency tree

### ISSUE THREAD

**Issue by Tylerian** [remix-run/remix#6855]
### Context

This error appeared to me when installing Remix JS in a monorepo production setup using yarn workspaces. 

The monorepo in question contains different front-ends, each using their own framework (Next JS). I've been able to reproduce this bug within a minimal setup which is linked below.

### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone the [tylerian/remix-run-yarn-workspaces-error](https://github.com/Tylerian/remix-run-yarn-workspaces-error) repository which reproduces the bug within a minimal setup.
2. Run `yarn install` from the root folder.
3. Run `yarn dev` from the `/a` folder, which will run `remix dev` behind the scenes.
4. That's it, the bug will reproduce.

### Expected Behavior

Remix development server should start successfully:
```

 💿  remix dev

 info  building...
 info  built (249ms)
Remix App Server started at http://localhost:3000 (http://192.168.1.101:3000)

```

### Actual Behavior

Remix development server fails to start, throwing the error below:
```
 info  building...
✘ [ERROR] Could not resolve "@remix-run/react"

    ../node_modules/@remix-run/dev/dist/config/defaults/entry.dev.ts:11:9:
      11 │   import("@remix-run/react");
         ╵          ~~~~~~~~~~~~~~~~~~

  You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.
```

**Comment by Tylerian** [comment]
I observed shared dependencies with different versions between projects gets stored on nested `node_modules` folders due to the hoisting nature of yarn.

This causes the `@remix-run/*` dependencies to be scattered between the workspace's root `/node_modules` folder and the remix project `a/node_modules` project depending on whether they share different versions of the same dependencies with other workspace projects or not.

The bug arises when remix tries to import a dependency that's not in the same level of the dependency tree. In other words: when a remix dependency stored in the root `node_modules` folder tries to import another remix dependency stored in a project's folder such as `a/node_modules` it fails because it's searching it on the workspace's root `/node_modules` folder.

In fact, using the `nohoist` option from Yarn workspaces as shown below solves the import error because all the `@remix-run/*` dependencies are stored within the same level of the dependency tree, i.e: they're stored within the same `node_modules` folder.
```
{
  "private": "true",
  "workspaces": {
    "packages": ["a", "b", "c"]
  }
}
```

**Comment by pcattori** [comment]
Unable to reproduce on my machine after cloning https://github.com/Tylerian/remix-run-yarn-workspaces-error then running:

```sh
yarn install
cd a/
yarn dev
```

I'm on MacOS 13.4.1 and using Yarn v1.22.19 .

**Comment by dkrieger** [comment]
seeing the same error with bazel + rules_js trying to use the `remix` bin. what is the justification for having undeclared dependencies? tbh it seems like a bug that pnpm would allow this to link. seems like at the very least there are missing `peerDependencies`
