### ISSUE TITLE
v1.18.1 ESModule being detected as CommonJS Module --- The requested module  _ is a CommonJS module, which may not support all module.exports as named exports

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#6872]
### What version of Remix are you using?
- 1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?
- [X] Yes

### Your Example Website or App
https://stackblitz.com/edit/node-fovhbz

### Describe the Bug
When attempting to use `@reactflow` in a fresh remix app, I get the following error:

```
file:///Users/cfajardo/Downloads/react-flow-remix/build/index.js:212
import { ReactFlow } from "@reactflow/core";
         ^^^^^^^^^
SyntaxError: Named export 'ReactFlow' not found. The requested module '@reactflow/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@reactflow/core';
const { ReactFlow } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at file:///Users/cfajardo/Downloads/react-flow-remix/server.js:16:13
```

### Steps to Reproduce the Bug or Issue
Create a fresh remix app (or [visit this stackblitz link](https://stackblitz.com/edit/node-fovhbz))

**1.Create a fresh remix app in your terminal:**
```
$ ~/Downloads npx create-remix@latest
? Where would you like to create your app? ./remix-reactflow
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets.
Express Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
⠇ Creating your app…
```

**2.Install `@reactflow` packages**
```
@reactflow/core @reactflow/background @reactflow/controls
```

3.Setup `root.tsx`  file with the content of the entire code snippet below ... this is to import the css for reactflow

<details>

```tsx
import { cssBundleHref } from "@remix-run/css-bundle";
import type { LinksFunction } from "@remix-run/node";
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";

import reactflowStyles from "@reactflow/core/dist/style.css";

export const links: LinksFunction = () => [
  ...(cssBundleHref ? [{ rel: "stylesheet", href: cssBundleHref }] : [
    { rel: "stylesheet", href: reactflowStyles },
  ]),
];

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        <Outlet />
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}
```
</details>

**4. Copy this code into `app/routes/_index.tsx` to setup basic reactflow hello world app:**

<details>

```tsx
import type { V2_MetaFunction } from "@remix-run/node";
import {ReactFlow} from '@reactflow/core';


export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

const initialNodes = [
  { id: '1', position: { x: 0, y: 0 }, data: { label: '1' } },
  { id: '2', position: { x: 0, y: 100 }, data: { label: '2' } },
];
const initialEdges = [{ id: 'e1-2', source: '1', target: '2' }];

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <h1>Welcome to Remix</h1>
      <div style={{ width: '100vw', height: '100vh' }}>
        <ReactFlow nodes={initialNodes} edges={initialEdges} />
    </div>
    </div>
  );
}

```
</details>

### Expected behavior

Code should work since:
`@reactflow` is using named exports according to these docs: https://reactflow.dev/docs/concepts/packages/#reactflowbackground

`@reactflow/{background, controls, core}` seem to be publishing ESM ([github repo](https://github.com/wbkd/react-flow/tree/main/packages))?
<img height="400" src="https://github.com/wbkd/react-flow/assets/6743796/027a4ccd-c801-45e7-ae87-72358df5ee04" />

### Platform
- OS: MacOS, Chrome, latest remix (1.18.1), latest version of `@reatflow` 11.x

## References / Related
- https://github.com/wbkd/react-flow/issues/3238
- https://stackoverflow.com/questions/65511127/when-can-a-commonjs-named-export-be-imported-by-an-es-module

**Comment by cliffordfajardo** [comment]
This same error message happens with a fresh remix app when importing `lodash`
https://stackblitz.com/edit/node-s1pxmf?file=app%2Froutes%2F_index.tsx

<img width="1643" alt="image" src="https://github.com/remix-run/remix/assets/6743796/3002c552-4bc7-4a46-88d8-bb3da7c5ca62">

**Comment by pcattori** [comment]
Looking at `node_modules/@reactflow/core/dist/esm`, there are both `index.js` and `index.mjs`. Switching the `module` field and the `exports.imports` field to point to `index.mjs` instead of `index.js` solved the issue for me. So this looks like misconfigured `package.json` in `@reactflow/core`.

**Comment by penx** [comment]
Related:

- https://github.com/remix-run/remix/issues/8507
- https://github.com/pbeshai/use-query-params/issues/277

**Comment by cliffordfajardo** [comment]
Note: for me upgrading to latest remix + vite solved my issues
