### ISSUE TITLE
[Feature]: Dark mode toggle example

### ISSUE THREAD

**Issue by arvigeus** [remix-run/remix#688]
### What is the new or updated feature that you are suggesting?

An example of a toggle button that switches theme on demand.

### Why should this feature be included?

Showcases conditionally loading stylesheets

**Comment by sergiodxa** [comment]
Check this https://ebey.me/blog/dynamic-css-with-remix-resource-routes

**Comment by arvigeus** [comment]
Thank you, @sergiodxa! Although this looks like way too much work for something as simple as that. I think something like your example should be included in docs.

**Comment by abereghici** [comment]
@arvigeus I created an abstraction for themes here : https://github.com/abereghici/remix-themes

**Comment by arvigeus** [comment]
I finally implemented it in my project: <https://github.com/arvigeus/format-code>

Basically using cookies for css files, as @sergiodxa suggested. Also the [toggleTheme action](https://github.com/arvigeus/format-code/blob/master/app/routes/toggleTheme.ts) returns set of css variables, so the change is applied on the fly, without reloading. Caveat: the next Link clicked MUST reload the page, or the new page will still display the old theme.

I'll close this issue for now because this repo is already polluted enough.
