### ISSUE TITLE
Requests on non-existing css source maps using postcss on v1.18.1

### ISSUE THREAD

**Issue by TimoWestland** [remix-run/remix#6890]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Enable postcss in the remix.config.js.
Add postcss.config.js file
Use the remix/css-bundle package to load the generated css file.

See 404s on requested css-map files because they are not generated

<img width="848" alt="image" src="https://github.com/remix-run/remix/assets/3959082/87891291-f1e9-4898-82bc-b3cf956d7d03">

### Expected Behavior

No css source maps are requested unless source maps are enabled (can't seem to find any configuration options for this).

### Actual Behavior

Source maps that don't exist are requested by remix.

**Comment by TimoWestland** [comment]
Some more context:

I see now that for the css file generated by css modules there actually is a sourcemap file. However for any other css file that is imported in `root.tsx` and added in `links` a sourcemap url is added to the css file that ends up in `build/_assets`. 

Is there a way to disable this for these files?

**Comment by markdalgleish** [comment]
I think this may have been fixed in v1.19.0 Can you update to the latest version of all Remix packages (currently v1.19.1) and let me know if it resolves your issue?

**Comment by TimoWestland** [comment]
> I think this may have been fixed in v1.19.0 Can you update to the latest version of all Remix packages (currently v1.19.1) and let me know if it resolves your issue?

Sorry for the late reply, will give that a try and let you know!

**Comment by TimoWestland** [comment]
> I think this may have been fixed in v1.19.0 Can you update to the latest version of all Remix packages (currently v1.19.1) and let me know if it resolves your issue?

This fixes the issue! Thanks :)
