### ISSUE TITLE
v1.19.0 removes `build.dev`, breaking `logDevReady()` in Cloudflare

### ISSUE THREAD

**Issue by huw** [remix-run/remix#6891]
### What version of Remix are you using?

v1.19.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

(Firstly @pcattori I f**ing love the new dev server and feel like this is as great a place as any to show my appreciation. It’s hard work to keep this compatible with all the different runtimes and other frameworks have just given up on trying—I love that you haven’t!)

This one is fairly simple, I think it’s just an oversight. The Cloudflare template includes:

https://github.com/remix-run/remix/blob/14bdd98c6872762f1c54ae55f852ae2e4c9461e0/templates/cloudflare-workers/server.ts#L10-L12

But as of v1.19.0, `build.dev` no longer exists ([blame](https://github.com/remix-run/remix/commit/d7c026d2e8bcfc6b4dd10a3d9c14d5af643c1354#diff-4c05589aa34d1c57a18782e2120c5a2842258d48fd0bbe90932205aba5e2d559)). As such, my live reloads never trigger and I have a type error when I compile.

In the meantime, I’m gating on `process.env.NODE_ENV`, which I’ve been injecting into my Workers environment anyway.

### Expected Behavior

The CLI should print the build hash to the console, triggering a live reload.

### Actual Behavior

The CLI does not print the build hash to the console and live reloads don’t happen.

**Comment by huw** [comment]
@pcattori I was slightly mistaken; since `server.ts` is part of the Remix build it will automatically have `process.env.NODE_ENV` injected. As such, I’ve submitted #6912 to use that by default in the template.

**Comment by Ponjimon** [comment]
What about `process` not being defined and thus causing TypeScript to error in the IDE?

```
Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.ts(2580)
```

<img width="705" alt="Screenshot 2023-07-23 at 18 23 15" src="https://github.com/remix-run/remix/assets/770632/85c1128d-7220-4ca6-bb92-c4e8e44c1691">

It still runs,  but my IDE shows me this error and I'm not sure if installing `@types/node` is the best way to fix this

**Comment by pcattori** [comment]
@Ponjimon you can force types for `process.env` like so:

```ts
declare var process : {
  env: {
    NODE_ENV: string
  }
}
```

That way you don't need to rely on `@types/node` for non-Node runtimes.
This tells TS to expect `process.env` to be defined, but still relies on something else (i.e. Remix) providing `process.env` at runtime.

**Comment by Ponjimon** [comment]
Thanks, but shouldn't something like this be part of the template? It feels odd having a template that throws errors, even if it's not a runtime error

**Comment by huw** [comment]
No, my bad, Pedro is right—this change didn’t introduce `process.env` to that file, it just re-used it (the original definition was on the first errored line you have, in `createRequestHandler`).

`@remix-run/cloudflare-workers` (and countless other TypeScript packages) [implicitly depends on `@types/node`](https://github.com/remix-run/remix/blob/97d82db0556ba8b40518898a75d6838e0bf3ced1/packages/remix-cloudflare-workers/worker.ts#L1-L2), and the dependency itself has special status in the TypeScript compiler. I’m not sure how much work it would be to remove the dependency, but I have a modestly-sized Workers project and haven’t run into any major conflicts in practice. But you might be able to get away with just defining `process`.

**Comment by pcattori** [comment]
I'm planning to add `build.mode` to the Remix server build output that will contain the mode used when the server was built by the compiler. That will be public API (and not an implementation detail), so then checking `build.mode === 'development'` will work across runtimes, including CloudFlare. This improvement will probably land in v2.
