### ISSUE TITLE
dev_v2 = false is faster

### ISSUE THREAD

**Issue by matt-erhart** [remix-run/remix#6907]
### What version of Remix are you using?

1.19

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Start up the indie stack and set npm scripts ```"dev": "remix dev"``` (ie remove msw which was taking an extra 10 seconds per edit)
- Run it with dev_v2=true, edit text in notes.new.tsx, ~4 seconds to see change in the browser
- Run it with  dev_v2=false and it takes 300-500 ms to see change

dev_v2 appears to be restarting after each edit. 

I'm on windows 11, node 16.

Bonus side note:  Thanks for building such a well thought out framework that's basically leading the ecosystem. React/nextjs seem to have basically endorsed the approach, and are now catching up. I think remix has a simpler, more elegant design but nextjs has a big social/marketing advantage. With nextjs/react in experimental turmoil for the 3+ months, now might be the time to really nail the social aspects of getting a framework out. A comparison table with eg dev server perf (updated with each nextjs release) and more YT would really help me sell remix to the other engineers. 

### Expected Behavior

- v2 to be faster than v1
- dev server to show changes in 500ish ms (eg about as long as it takes to look over, but you don't have to match vite ms for ms).

**Comment by brainstormbuddy** [comment]
Thanks, @matt-erhart . I am a remix fun. I am very attracted remix's power. I'll review the issue and try to fix it.

**Comment by pcattori** [comment]
Can you share the timing reports by `remix dev` in your terminal? If you are seeing slow `app server ready` times, you can look into using manual mode (https://remix.run/docs/en/main/other-api/dev-v2#manual-mode).

**Comment by matt-erhart** [comment]
It was something like 300-500ms to build, and 3-4 seconds to restart the app server. V1 is working ok for me, so I probably won't go down the manual mode rabbit hole on v2. The main issue is that that v2 feels like a performance and/or setup time regression.

**Comment by pcattori** [comment]
`v2_dev` has to support more than `remix-serve`. Whereas `remix-serve` only supports Node and CJS, `v2_dev` supports _any runtime_ in _any JS format_. That added responsibility makes the setup for non-`remix-serve` apps a bit more onerous, but we're looking to make it easier to opt into.

For example, the current Express template already has everything wired up for you. So you could just copy that if you wanted.

Given that the "restarting app server is slow" issue is addressed via manual mode, going to close this.

**Comment by matt-erhart** [comment]
Will go take a look at the express template, sounds like the Indie Stack example app is not using the optimal DX setup for v2, maybe let KCD? or who ever authored them know? I use the real-ish app examples to get a sense of new libraries, so anyone else who does the same will assume remix has slow edit times if they spin up the Indie Stack atm. 

It sounds like in order to get all platforms to work without writing a compiler for each (months/quarters of work?), you needed to add a bit of copy paste and manual mode to get something working in the near term. This is honestly probably fine (but not legendary yet) if it's included in all the remix examples and doesn't really need to be changed. Manual does feel like library code I shouldn't be changing both because it's exposing choidar direct and because things become 'my responsibility' which implies that I shouldn't be doing it, but to get the best DX I should be doing it?

**Comment by kiliman** [comment]
I think part of the issue with the Indie stack is that it also launches the mock service worker server, so the initial startup isn't optimized for the new v2 dev server.

If you change the `dev` script to `"dev": "remix dev"`, you'll see that HMR works as expected, and it doesn't have to *reboot* the app server.

I also tested by ejecting from Remix App Server to Express, using my `rmx-cli eject-ras` script.

Changes
```json
  "scripts": {
    "dev": "remix dev -c \"node server.mjs\"",
  }
```
```diff
// server.mjs
import morgan from "morgan";

+import "./mocks/index.js";

installGlobals();
```

<img width="498" alt="image" src="https://github.com/remix-run/remix/assets/47168/d8add5fd-21a5-4777-91e8-0bdb518b4e4c">

**Comment by matt-erhart** [comment]
Can confirm good edit response times from ```npx create-remix@latest --template https://github.com/remix-run/remix/tree/main/templates/express remix_express```
