### ISSUE TITLE
`global` in not preserved in v2_dev server

### ISSUE THREAD

**Issue by koxu1996** [remix-run/remix#6914]
### What version of Remix are you using?

v1.19.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Follow App Tutorial, and focus on [Connect to the database](https://remix.run/docs/en/1.19.0/tutorials/jokes#connect-to-the-database) - it contains instruction how to preserve connection across server reload:

```ts
import { PrismaClient } from "@prisma/client";

let db: PrismaClient;

declare global {
  var __db__: PrismaClient | undefined;
}

// This is needed because in development we don't want to restart
// the server with every change, but we want to make sure we don't
// create a new connection to the DB with every change either.
// In production, we'll have a single connection to the DB.
if (process.env.NODE_ENV === "production") {
  db = new PrismaClient();
} else {
  if (!global.__db__) {
    global.__db__ = new PrismaClient();
  }
  db = global.__db__;
  db.$connect();
}

export { db };
```

Run application with `yarn dev`.

### Expected Behavior

Whenever code is changed and server reloaded, then old database connection should be reused. This works with `v2_dev: false`.

### Actual Behavior

`global` is undefined on every "live reload", so database connection is always recreated.

**Comment by pcattori** [comment]
By default with `v2_dev`, the app server is restarted whenever changes are made, which will not keep around stuff on `global`. You can use manual mode (https://remix.run/docs/en/main/guides/manual-mode) in conjunction with [`remember` utility][remember] to preserve `global` across rebuilds.

That said, the tutorial is a outdated when it comes to that. Going to take a pass at updating the tutorial to make this simpler.

[remember]: https://remix.run/docs/en/main/guides/manual-mode#keeping-in-memory-server-state-across-rebuilds

**Comment by andrzej-casper** [comment]
@pcattori Got it, thanks!

**Comment by ryanflorence** [comment]
does the tutorial tell you to use v2_dev?

**Comment by MichaelDeBoey** [comment]
@ryanflorence Jokes tutorial starts from Remix template, which has `v2_dev` enabled by default
But it should indeed be updated to use the new utility

**Comment by roblox34** [comment]
Awesome, I appreciate you keeping me in the loop! Can you give me some more details on the new tool and how it can help us update the tutorial?

**Comment by MichaelDeBoey** [comment]
@ryanflorence both Blog and Jokes tutorial are updated: https://github.com/remix-run/remix/pull/7161 & https://github.com/remix-run/remix/pull/7162
