### ISSUE TITLE
hmr not working on remix v1.19.1 when page default is anon arrow function

### ISSUE THREAD

**Issue by rolanday** [remix-run/remix#6935]
### What version of Remix are you using?

Remix 1.19.1

Running on macOS

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new project using the `npx create-remix@latest`
2. Start dev server, and make change to home page (`/_index.tsx`) -- hmr works as expected
3. Create a new route at `/test.tsx`, and make a change -- hmr not working (need to manually refresh page to see the change)

Here's the project (only change from as created is addition of `/app/routes/test.tsx`):

https://github.com/rolanday/remix-hmr-1.19.1

### Expected Behavior

To see changes reflected after updating a page w/o needing to manually reload.

### Actual Behavior

Changes not reflected for all routes.

**Comment by rolanday** [comment]
Works if change route default to be named function. I.e., 

this (works):
```
export default function Test() {
  return <div>test1</div>;
}

```
instead of this (doesn't hmr):
```
export default () => {
  return <div>test1</div>;
};
```

Credit and thanks to discord member xHomu for pointing this out.

**Comment by pcattori** [comment]
This looks like a limitation of React Refresh, not Remix: https://github.com/facebook/react/issues/21181
