### ISSUE TITLE
[Bug] (Docs): Right-clicking on Remix logo redirects you to an external link

### ISSUE THREAD

**Issue by awareness481** [remix-run/remix#697]
### Which Remix packages are impacted?

N/A

### What version of Remix are you using?

N/A

### Steps to Reproduce

1. Visit https://remix.run/docs/en/v1
2. Right-click on the remix logo (top left)

https://user-images.githubusercontent.com/12380586/143667266-7aa5d0b8-bd90-40a9-80bd-79ef867be086.mp4

I believe this might not be intended, but if it is I think it's worth considering whether it should be changed or not.

### Expected Behavior

For the right click context menu to show up

### Actual Behavior

You're redirected to https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c

**Comment by bruno-oliveira** [comment]
Can I pick this up?

**Comment by awareness481** [comment]
You should definitely pick this up *but* after the maintainers agree this is a bug :P

**Comment by derrxb** [comment]
I don't think this is a bug. It was intentional to give users access to high quality logo files. See https://twitter.com/remix_run/status/1463376283505598464?s=21

**Comment by bruno-oliveira** [comment]
Shall we close it then? :)

**Comment by awareness481** [comment]
Initially thought this might have been a leftover from pre-oss. I'm closing this per https://github.com/remix-run/remix/issues/697#issuecomment-981061570 but I still find it a bit annoying. I have a habit of `right click -> open link to new tab` instead of `ctrl/cmd + click` :P

**Comment by rafae2k** [comment]
I thought it was really annoying too, at least now i know it's intentional easter egg, but seems more like a bug 😅
