### ISSUE TITLE
ErrorBoundary loses route error in production

### ISSUE THREAD

**Issue by Ehesp** [remix-run/remix#6970]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

See: https://github.com/Ehesp/remix-error-boundary-issue

Notes:
 - This is using the Cloudflare Pages adapter, I haven't tried this to see if it's adapter specific or not.
 - This happens with both `v2_errorBoundary` set to true and false

My `routes/_index.ts` route [throws a simple error](https://github.com/Ehesp/remix-error-boundary-issue/blob/main/app/routes/_index.tsx#L3):

```ts
export const loader = async () => {
  throw new Error('Foo bar');
};
```

I have a simple ErrorBoundary in `root.tsx`:

```ts
export function ErrorBoundary() {
  const error = useRouteError();
  console.log('ERROR FROM BOUNDARY', error);
  return <div>Error</div>;
}
```

Note; this is also the same when using v1 error boundary with the error as a prop:

```ts
export function ErrorBoundary({ error }: { error: unknown }) {
  console.log('ERROR FROM BOUNDARY', error);
  return <div>Error</div>;
}
```

### Expected Behavior

During development (`npm run dev`), the error logged is correct (the `Foo bar` error instance).

```
ERROR FROM BOUNDARY Error: Foo bar
    at loader (80i7ughq5zj.js:16073:9)
    at callRouteLoaderRR (80i7ughq5zj.js:3329:22)
    at commonRoute.loader (80i7ughq5zj.js:3376:47)
    at runHandler (80i7ughq5zj.js:2408:105)
    at callLoaderOrAction (80i7ughq5zj.js:2434:22)
    at 80i7ughq5zj.js:2168:71
    at Array.map (<anonymous>)
    at loadRouteData (80i7ughq5zj.js:2168:55)
    at queryImpl (80i7ughq5zj.js:2048:26)
    at Object.query (80i7ughq5zj.js:2000:24) {
  stack: Error: Foo bar
    at loader (80i7ughq5zj.js:16073…:26)
    at Object.query (80i7ughq5zj.js:2000:24),
  message: Foo bar
}
```

During production (`npm run build && npm run start`) the error is:

```
ERROR FROM BOUNDARY Error: Unexpected Server Error {
  stack: undefined,
  message: Unexpected Server Error
}
```

### Actual Behavior

The error in production is consistent with that of development.

**Comment by brophdawg11** [comment]
Remix automatically strips error messages and stack traces in production for security reasons since you should not be leaking server-side error or stack information to the client.  If you need access to the un-sanitized error for logging/reporting you can access it via the `handleError` export: https://remix.run/docs/en/1.19.1/file-conventions/entry.server#handleerror

**Comment by Ehesp** [comment]
Ahh I see. I was hoping to throw a custom error and render the error message.

I guess I'll need to throw a response error then
