### ISSUE TITLE
REMIX_DEV_ORIGIN fails with default Remix App Server

### ISSUE THREAD

**Issue by dnsbty** [remix-run/remix#6971]
### What version of Remix are you using?

v1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix app with the following settings:

```
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Y
```

2. cd into the `my-remix-app` directory.

3. Start a tunnel to some domain with [ngrok](https://ngrok.com/) or [cloudflared](https://github.com/cloudflare/cloudflared)

4. Start the application with the `REMIX_DEV_ORIGIN` environment variable:

```
REMIX_DEV_ORIGIN=<YOUR_DOMAIN> npm run dev
```

### Expected Behavior

I would expect the development server to start successfully.

### Actual Behavior

I see the following logs:

```
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/ping"',
  error: Error: No route matches URL "/ping"
      at getInternalRouterError (/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/router/router.ts:4132:5)
      at Object.query (/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/router/router.ts:2631:19)
      at handleDocumentRequestRR (/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
      at requestHandler (/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at /Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/express/dist/server.js:39:28
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
}
No routes matched location "/ping"
POST /ping 404 - - 42.082 ms
Could not reach Remix dev server at https://<YOUR_DOMAIN>/ping (404)

/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/server-runtime/dist/dev.js:34
    throw Error(await response.text());
          ^
Error: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><title>Unhandled Thrown Response!</title></head><body><h1 style="font-family:system-ui, sans-serif;padding:2rem">404<!-- --> <!-- -->Not Found</h1><script>
              console.log(
                "💿 Hey developer👋. You can provide a way better UX than this when your app throws 404s (and other responses). Check out https://remix.run/guides/not-found for more information."
              );
            </script></body></html>
    at Object.broadcastDevReady (/Users/dennisbeatty/Code/my-remix-app/node_modules/@remix-run/server-runtime/dist/dev.js:34:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

And when I try to access the server in the web browser after that, nothing renders.

**Comment by pcattori** [comment]
Your logs show that `/ping` messages are getting sent to your app server, not the Remix compiler/dev server. So you are likely setting `REMIX_DEV_ORIGIN` to point to your app server instead of your dev server.

If you are running both app server _and_ Remix compiler/dev server behind a reverse proxy, you'll need to send `/ping` and `/socket` endpoints to the dev server, and everything else to your app server.

**Comment by dnsbty** [comment]
@pcattori is there a guide somewhere for how to do that? I'm just trying to do what it says in the documentation here: https://remix.run/docs/en/main/other-api/dev-v2#how-to-integrate-with-a-reverse-proxy

I'm setting up my reverse proxy pointed to port 3000. Do I need to setup nginx or something else to send `https://mydomain/ping` and `https://mydomain/socket` to a different port?

**Comment by dnsbty** [comment]
Thank you @pcattori! I just added https://mydomain/ping and https://mydomain/socket to the Cloudflare Tunnel pointing to `http://localhost:3001` and that got it working. For some reason I had thought that in v2 the Remix compiler/dev server was piggybacking off of the app server if you don't have a custom Express setup, but this makes more sense.

**Comment by O-Connects** [comment]
> Thank you @pcattori! I just added https://mydomain/ping and https://mydomain/socket to the Cloudflare Tunnel pointing to `http://localhost:3001` and that got it working. For some reason I had thought that in v2 the Remix compiler/dev server was piggybacking off of the app server if you don't have a custom Express setup, but this makes more sense.

@dnsbty Hi, Dude, I have the same issues as you, can you tell me how to fix it?

**Comment by dnsbty** [comment]
In the Cloudflare dashboard, I modified the "Public Hostname" section of my tunnel to look like this:

| Public hostname | Path | Service |
| --- | --- | --- |
| my.domain.com | ping | http://localhost:3001 |
| my.domain.com | socket | http://localhost:3001 |
| my.domain.com | * | http://localhost:3000 |

**Comment by O-Connects** [comment]
> In the Cloudflare dashboard, I modified the "Public Hostname" section of my tunnel to look like this:
> 
> Public hostname	Path	Service
> my.domain.com	ping	http://localhost:3001
> my.domain.com	socket	http://localhost:3001
> my.domain.com	*	http://localhost:3000

Thank you very much!
