### ISSUE TITLE
[Feature]: Add global search on https://remix.run/docs

### ISSUE THREAD

**Issue by akhil-gautam** [remix-run/remix#699]
### What is the new or updated feature that you are suggesting?

Add global search on the doc's site. It can be a custom search component or third-party integration like [Algolia](https://www.algolia.com/).

### Why should this feature be included?

A lot of information in doc is not visible in the left-navigation bar and is nested deep inside. In able to find things quickly and make life easy, a global search will be really appreciated.

**Comment by aganoza** [comment]
The docs have Algolia now
