### ISSUE TITLE
Incorrect version using npx

### ISSUE THREAD

**Issue by MonteKrysto** [remix-run/remix#6992]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`npx create-remix@latest`

### Expected Behavior

Remix should be installed to generate app

### Actual Behavior

npx is looking to install version 1.19.0 and throws this error

```
iMac:~/code|⇒  npx create-remix@latest
Need to install the following packages:
create-remix@1.19.1
Ok to proceed? (y) y
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @remix-run/dev@1.19.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by markdalgleish** [comment]
I wasn't able to reproduce this when running the same command. `@remix-run/dev@1.19.1` does exist on npm: https://www.npmjs.com/package/@remix-run/dev/v/1.19.1. I'm not sure why you'd be seeing this unless it's maybe some sort of local caching or network issue?
