### ISSUE TITLE
Latest Remix fails on bundling all server dependencies

### ISSUE THREAD

**Issue by Senjai** [remix-run/remix#7020]
### What version of Remix are you using?

1.19.1 (npx create-remix@latest as of Aug 1)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Perform the following command in sequence, in an empty folder. I was running node v19.7.0 and yarn v1.22.19 on MacOSX

```shell
npx create-remix@latest
```

Use the following configuration:

<img width="1314" alt="image" src="https://github.com/remix-run/remix/assets/1831235/30087eac-2a2b-44b7-8257-885a5b4955c7">

run `yarn` to install dependencies. `yarn build` and `yarn dev` should work.

Modify `remix.config.js` in the following fashion
```diff
diff --git remix.config.js remix.config.js
index 378d0fc..3b42ab6 100644
--- remix.config.js
+++ remix.config.js
@@ -5,6 +5,7 @@ export default {
   // assetsBuildDirectory: "public/build",
   // serverBuildPath: "build/index.js",
   // publicPath: "/build/",
+  serverDependenciesToBundle: [/.*/],
   serverModuleFormat: "esm",
   future: {
     v2_dev: true,
```

run `yarn dev`, it should work, it does not. 

### Expected Behavior

Running yarn dev after making the change to server dependencies to bundle yields the following output

```
yarn run v1.22.19
$ remix dev --manual -c "node server.js"

 💿  remix dev

 info  building...
 info  built (273ms)

file:///Users/richard/src/remix-experiments/serverbuilding/node_modules/source-map-support/source-map-support.js:2
var path = require('path');
           ^
Error: Dynamic require of "path" is not supported
    at file:///Users/richard/src/remix-experiments/serverbuilding/build/index.js:11:9
    at node_modules/source-map-support/source-map-support.js (file:///Users/richard/src/remix-experiments/serverbuilding/node_modules/source-map-support/source-map-support.js:2:12)
    at file:///Users/richard/src/remix-experiments/serverbuilding/build/index.js:17:50
    at node_modules/@remix-run/node/dist/index.js (file:///Users/richard/src/remix-experiments/serverbuilding/node_modules/@remix-run/node/dist/index.js:15:24)
    at file:///Users/richard/src/remix-experiments/serverbuilding/build/index.js:17:50
    at file:///Users/richard/src/remix-experiments/serverbuilding/app/entry.server.tsx:10:26
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

```

### Actual Behavior

Bundling all dependencies for the server is a common suggested fix (see https://github.com/remix-run/remix/discussions/2594#discussioncomment-4733564) for some module import errors. That said, it looks like the latest remix is using ESM as the build target for the server now.. I'm glad it is demonstrable with Remix itself as hopefully it will help limit the surface area for other packages also having issues. Admittedly I'm still new with many of these frontend build systems and apologize in advance if I've misunderstood something. I would expect this change to not introduce runtime errors on the server.

**Comment by divyeshsachan** [comment]
Facing the same issue as some packages we use in our existing project is not supported anymore in recent version of remix due to recent changes of serverModuleFormat: "esm" in remix.config.js and "type": "module" in package.json

Have to remove these settings to fallback to cjs.

Hopefully, remix team will take care of such issues before moving to v2.

**Comment by pcattori** [comment]
The `source-map-support` package is no longer built into Remix, so is fixed as part of the upcoming v2 release. You can try it now on `nightly`.

Going forward, it is now up to the user to configure it if they want or use any other source map tool.
