### ISSUE TITLE
v2_dev crashes with React17 + ESM

### ISSUE THREAD

**Issue by xHomu** [remix-run/remix#7021]
### What version of Remix are you using?

v1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

* Demo Repo: https://github.com/xHomu/remix-v2-server/tree/esm-server-react17
* Initial Report on Discord: https://discordapp.com/channels/770287896669978684/1135991368230109194

Change any of the following, and the template runs as expected:

* Update `react` and `react-dom` to "^1.18.2"
* Comment out `v2_dev` in remix.config.js
* Go with CJS instead: https://github.com/xHomu/remix-v2-server/tree/cjs-server.js-react17

I thought it might have been the default entry.server and entry.client, so I went ahead and grabbed the old react17 versions of the entry files, no luck: https://github.com/remix-run/remix/blob/d86cc1ed904ce98a04db3f9048f99ef6e710e9a4/templates/express/app/entry.server.tsx

### Expected Behavior

Dev server runs, hmr working as expect (with React 17 caveats).

### Actual Behavior

This error seems specific to the React 17 + ESM + v2 Dev Server combination, which results in the following errors:

![image](https://github.com/remix-run/remix/assets/84349818/fc352f7c-103a-4099-b0ec-535d209a3eae)

**Comment by xHomu** [comment]
@WillSmithTE

**Comment by jacob-ebey** [comment]
React 17 does not have an exports map, this means if you want to use react 17 in an ESM runtime you'll have to import the `/server` deep import as `react-dom/server.js`.

**Comment by pcattori** [comment]
We're dropping support for React 17 in Remix v2, so not planning to address this. That said, just because it isn't officially supported doesn't mean it _definitely_ won't work. I wouldn't be surprised if some `app/entry.server.tsx` could be crafted to get React 17 running

**Comment by ryanflorence** [comment]
Thanks Pedro. For a little more context on this decision there's a lot of good stuff we'll be bringing into v2 with v3_flags, and we don't want React 17 support making it all very difficult.
