### ISSUE TITLE
Deployment on Vercel is failing

### ISSUE THREAD

**Issue by mrzahidjabbar** [remix-run/remix#7024]
### What version of Remix are you using?

1.2.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

The project is deployed on Vercel and everything was working until I did some changes in a CSS file. I created a PR and found out Vercel deployment failed and I couldn't get a preview link.

The error reads, `Error: Cannot find module '/vercel/path0/node_modules/@remix-run/dev/dist/config.js'`. 

I've tried undoing the CSS changes and creating new PR from main branch but it still fails. 

### Expected Behavior

It should be deployed without any issues. I'm just making a few CSS changes.

### Actual Behavior

The Vercel deployment is failing

**Comment by brophdawg11** [comment]
If you've not changed Remix versions then I think this is likely a change in the Vercel environment/build pipeline and would need to be reported over there?  I know they do some stuff internally for the Remix builds - and 1.2.1 is a pretty old version so maybe their latest Remix build pipeline doesn't play nice with 1.2.1?

**Comment by ryanflorence** [comment]
This is pretty far behind. Please use Vercel's instructions for deploying to their service:

https://vercel.com/docs/frameworks/remix
