### ISSUE TITLE
[Feature]: Support for SASS/SCSS 

### ISSUE THREAD

**Issue by ashvin777** [remix-run/remix#707]
### What is the new or updated feature that you are suggesting?

Support for SASS/SCSS 

### Why should this feature be included?

SASS/SCSS is a very common framework that is used for the development of the styles.

**Comment by sergiodxa** [comment]
Right now you need to run the Sass/SCSS compiler as another process, take your files and output css inside the app directory so you can import them in your routes.

**Comment by ashvin777** [comment]
Running it seperatly seems to be an overhead, any plans to integrate in remix itself, to make it seamless? 

Maybe some plugins or addons?

**Comment by sbernheim4** [comment]
I'm able to run it pretty easily with this in my package.json

```
"scripts": {
    "sass": "sass --watch app/:app/"
}
```

and then just run `npm run sass`. You could also easily set up something like concurrently to run both the dev and sass commands together when you run `npm run dev`.

It doesn't make sense to me to have remix support scss/sass. They are not native web languages and one Remix's goals is to support and leverage the native aspects of web.

**Comment by sergiodxa** [comment]
> Running it seperatly seems to be an overhead, any plans to integrate in remix itself, to make it seamless?
> 
> Maybe some plugins or addons?

A few time the team said they don't want to add ways to extend the compiler so they are not tied to it, so probably something like plugins or addons which needs to make the compiler process more things are not going to become a things, at least not for a lot of time until they figure a way to let you do that without touching esbuild directly.

**Comment by itsMapleLeaf** [comment]
You could also consider compiling and serving Sass on the fly from a resource route. [I wrote a package to do this with postcss and tailwind,](https://github.com/itsMapleLeaf/remix-tailwind) and it works well so far. If speed is a concern, you can precompile in prod

Since I imagine Sass users have multiple CSS files, you could even use a dynamic route param and/or a splat route to read a dynamic path to a CSS file :shrug: there are possibilities

**Comment by MohammadHosseinBagheri** [comment]
I add   `"scripts": {
    "sass": "sass --watch app/:app/"
}` into package.json scripts and works for me.

**Comment by MohammadHosseinBagheri** [comment]
I add "scripts": { "sass": "sass --watch app/styles/" } into package.json scripts and works for me.

**Comment by MohammadHosseinBagheri** [comment]
I add `"scripts": { "sass": "sass --watch app/styles/" }` into package.json scripts and works for me.

**Comment by ashvin777** [comment]
Okay and how do we import in components ? Also do I need to ?

**Comment by sergiodxa** [comment]
@ashvin777 the SASS compiler should give you back a CSS file inside the `app` folder (e.g. inside `app/styles`), so now you can import it as any CSS file as the Remix docs explain here https://remix.run/docs/en/v1/guides/styling

**Comment by ashvin777** [comment]
Okay so I will have both the files always sitting in component/route folder, one with scss extension and other one with css extension. And you are saying that we just need to import CSS as a regular file. It would be great if I dont get to see both the files.

I like the idea of links, maybe we could link the SCSS file in it and linker might convert that to CSS at runtime ?

**Comment by ashvin777** [comment]
Like below
```

import styles from "./styles.scss";

export const links = () => [
  { rel: "stylesheet", href: styles, loader: "sass" }
];

```

**Comment by ashvin777** [comment]
Also, given the links structure, I don't think we will be able to support CSS/SASS Modules. The module pattern works differently, dont you think its somekind of limitation ?

**Comment by sergiodxa** [comment]
@ashvin777 I recommend you to put your CSS code in another folder of your SCSS, and ignore that folder with .gitignore.

The links function is not doing enough things to transform SCSS to CSS, actually, it doesn't even care what you are linking, it just receives an array of objects and ensure they are rendered as `<link />` tags.

And yeah, CSS Modules doesn't work for now.

**Comment by vuesets** [comment]
I think a plug-in development channel should be developed to enrich remix usage . 
Example for MDX file

**Comment by sergiodxa** [comment]
> I think a plug-in development channel should be developed to enrich remix usage .
> Example for MDX file

MDX is already supported

**Comment by ashvin777** [comment]
I am not sure why we support mdx and not sass/scss at first.

Its important that we enable the plugin path otherwise it can be hard for people to run multiple threads.

**Comment by sergiodxa** [comment]
> I am not sure why we support mdx and not sass/scss at first.
> 
> Its important that we enable the plugin path otherwise it can be hard for people to run multiple threads.

You can easily use SASS with a compiler outside Remix, AFAIK you can't do that with MDX, also in MDX they added more things like you can make a route be a MDX file and use front matter to add headers, links, etc. to the route as in a normal JS/TS file.

**Comment by vuesets** [comment]
In `remix.config.js` file, supports user defined plugin, or support user defined add plugin for project, that would be better.

**Comment by zbcoding** [comment]
Can someone add to the documentation that Remix Run does not support SCSS without extra workarounds, there are 0 results in the documentation right now.

**Comment by yomeshgupta** [comment]
If anyone is still struggling with running SASS with Remix run then it might help https://devtools.tech/blog/setting-up-sass-with-remix-run---rid---lXDyMjDSdDZDXxNcJ2ep

**Comment by craigcosmo** [comment]
> It doesn't make sense to me to have remix support scss/sass. They are not native web languages and one of Remix's goals is to support and leverage the native aspects of web.

There is nothing native about jsx, tsx, react, typescript, but remix still support them, I think you are confused.

**Comment by craigcosmo** [comment]
> https://devtools.tech/blog/setting-up-sass-with-remix-run---rid---lXDyMjDSdDZDXxNcJ2ep

that website is server error, not showing anything.

**Comment by craigcosmo** [comment]
> Okay so I will have both the files always sitting in component/route folder, one with scss extension and other one with css extension. And you are saying that we just need to import CSS as a regular file. It would be great if I dont get to see both the files.
> 
> I like the idea of links, maybe we could link the SCSS file in it and linker might convert that to CSS at runtime ?
> 
> Example -
> 
> ```js
> import styles from "./styles.scss";
> 
> export const links = () => [
>   { rel: "stylesheet", href: styles, loader: "sass" }
> ];
> ```

I need this solution. Please please make it happen.

**Comment by craigcosmo** [comment]
ok now

**Comment by machour** [comment]
There is now an example for sass integration: https://github.com/remix-run/remix/tree/main/examples/sass

**Comment by ABSanthosh** [comment]
> @ashvin777 I recommend you to put your CSS code in another folder of your SCSS, and ignore that folder with .gitignore.

If you are using VS Code, you can add these in workspace settings(.vscode/settings.json) to hide the css and css.map files
`{
  // The following will hide the js and map files in the editor
  "files.exclude": {
    "**/*.css": true,
    "**/*.css.map": true
  }
}
`

Files will be there in the directory and you will have to ref to .css to import the stylesheet but you don't have to see 2 files for each scss style sheet in vs code. Add it to .gitignore as well

**Comment by nadiTime** [comment]
have this setup working pretty good
```js
//.vscode/settings.json
{
  "files.exclude": {
    "**/*.css": true,
    "**/*.css.map": true
  }
}
```
```js
//package.json
"scripts": {
    "build": "run-s build:*",
    "build:css": "sass app/:app/ --style=compressed --no-source-map",
    "build:remix": "remix build",
    "dev": "run-p dev:*",
    "dev:css": "sass --watch app/:app/",
    "dev:remix": "remix dev"
}
```
```js
//remix,config.js
module.exports = {
  ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.scss", "**/*.css.map"]
};
```
then I can import the generated css file:
```js
import globalStylesUrl from "./styles/global.css";
```

only thing that is missing is the right map files for source files browser support, which is pretty annoying not being able to edit .scss files in the browser.

any idea how to achieve this?

**Comment by machour** [comment]
@nadiTime please use the discussion tab to ask for support.

**Comment by KingSora** [comment]
@ryanflorence @jacob-ebey @kentcdodds @mcansh @mjackson whats your opinion about a `esbuild` plugin for automatically transpiling `sass` files? I could create a PR which handles that. Since the plugin would only handle `scss` / `sass` extensions it wouldn't slow down `css` only projects and it would be completely opt-in.

**Comment by nadiTime** [comment]
@KingSora
Is it possible to add support for css maps?

**Comment by AurelianSpodarec** [comment]
Soo... how do you go about making Sass work in the Remix app? The link above is 404.

**Comment by gxxcastillo** [comment]
> Soo... how do you go about making Sass work in the Remix app? The link above is 404.

Try the updated link I posted earlier

**Comment by Denny966** [comment]
> Soo... how do you go about making Sass work in the Remix app? The link above is 404.

Use this link https://github.com/remix-run/examples/tree/main/sass
