### ISSUE TITLE
npx-f1140a64.sh: line 1: create-remix: command not found

### ISSUE THREAD

**Issue by deflexable** [remix-run/remix#7071]
### What version of Remix are you using?

am yet to install remix

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

run this ``npx create-remix@latest``

### Expected Behavior

to install latest remix project

### Actual Behavior

brought up this error: 

/var/folders/nt/23nnn1jn4xzdzjpzp1bnj9bh0000gn/T/npx-f1140a64.sh: line 1: create-remix: command not found

**Comment by pcattori** [comment]
Are node, npm, and npx installed correctly? Do you have a different `npx` command installed on your machine?

**Comment by deflexable** [comment]
@pcattori i was able to fix it by running 
``npm cache clean --force`` then 

``npm install -g create-remix@latest`` then 

``npx create-remix@latest``
