### ISSUE TITLE
Unable to install in Ubuntu the latest remix version

### ISSUE THREAD

**Issue by hebrod77** [remix-run/remix#7075]
### What version of Remix are you using?

Test it with 1.19.2 and 1.19.1 got the same result

### Are all your remix dependencies & dev-dependencies using the same version?

- [ ] Yes

### Steps to Reproduce

This is happening in Ubuntu 22.04.2 LTS (jammy) version.
Got node version: 14.21.3
And npm version: 6.14.18
I just execute: npm create-remix@latest or npm create-remix@1.19.1
and after some percentage I get this error:

internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/7556/lib/node_modules/create-remix/node_modules/deasync/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/7556/lib/node_modules/create-remix/node_modules/esbuild/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.17.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esbuild@0.17.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-05T02_27_18_216Z-debug.log
Install for [ 'create-remix@1.19.1' ] failed with code 1
root@frontmileniosoft1:/home/Projects/test# 
root@frontmileniosoft1:/home/Projects/test# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
root@frontmileniosoft1:/home/Projects/test# node 0v
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/home/Projects/test/0v'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Expected Behavior

Installation of remix app.

### Actual Behavior

Action fails.

**Comment by brophdawg11** [comment]
This looks like some sort of local `npm`/`npx` installation issue.  Can you try a fresh install of `node` via `npx`?  

Also, does this happen on node 16 or node 18?  Node 14 reached End of Life in April so it's not officially supported anymore.

**Comment by CostGranda** [comment]
Installed remix without any issue in Ubuntu, you are doing something wrong, check your global node installation
