### ISSUE TITLE
tailwind styles are not processed in v1.19.2 but are in v1.19.1

### ISSUE THREAD

**Issue by smorris1709** [remix-run/remix#7076]
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

npx create-remix@latest remix-app --template examples/tailwindcss install the deps and run now styles are present

if you change the deps to use v1.19.1 styles are back

### Expected Behavior

it should parse tailwind styles and add them to the style sheet

### Actual Behavior

its not parsing any tailwind styles

**Comment by markdalgleish** [comment]
I think you're inadvertently using Remix ~1.14.2 due to the incorrect version specified in the Tailwind example app. I've opened a PR fixing this: https://github.com/remix-run/examples/pull/315. In the meantime, if you manually update your app to use Remix 1.19.2, it should work.
