### ISSUE TITLE
Incorrect GET request on fetcher.submit with method post

### ISSUE THREAD

**Issue by divyeshsachan** [remix-run/remix#7079]
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Recently updgraded from remix 1.14.1 to 1.19.2

When a route has both loader and action exports, calling fetcher.submit with method post creates multiple network requests and is inconsistent.
It firsts makes correct POST request. and immediately a GET request is made to the same route which updates loaderdata and fetcher data twice and subsequent logic which relies on that data fails.

I've stripped down the code to minimal reproducible example,

Simply create an new remix example app
and update the code provided to see the behavior
![image](https://github.com/remix-run/remix/assets/5191867/e692ba7e-c4b2-416e-b95b-f10134484b7a)

### Expected Behavior

It should not make GET request upon fetcher.submit

### Actual Behavior

```
import { json, SerializeFrom, type V2_MetaFunction } from "@remix-run/node";
import { FetcherWithComponents, useFetcher } from "@remix-run/react";
import { useEffect, useState } from "react";

export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export const loader = async() => {
  return json("");
}

export async function action() {
  return json("")
}

export default function Index() {

  const fetcher = useFetcher();
  
  const startPolling = () => {
    console.log("CALLED")
    if (fetcher.state == "idle") {
      fetcher.submit({ _t : Date.now() },{ method: "post" });
    }
  }

  useEffect(() => {
    if (fetcher.state === "idle"){
      setTimeout(startPolling, 5000);
    }
  }, [fetcher]);

  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <h1>Welcome to Remix</h1>
    </div>
  );
}
```

**Comment by brophdawg11** [comment]
This is expected behavior, and isn't different between `1.14.1` and `1.19.2`.  Loaders are always re-called after any submission (a process called "revalidation") to ensure that your UI reflects any changes made during the submission.  You can opt-out of this via the route level `shouldRevalidate` export: https://remix.run/docs/en/1.19.2/route/should-revalidate
