### ISSUE TITLE
Types for unstable_createRemixStub don't accept DataFunctionArgs

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#7082]
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[Here's a TypeScript.com/play reproduction](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFCiSxwDecArgHaozIBGANlgD6uSshhZsIYAA8AyjFY8U6ETnGSZ8xXAC+cIiTgAiAAKUp0gLRQOAenFdg7AOZGA3HXDR4LGAE8wLDgAETFkADEOfGAIdgBBKGdUABo4ACtUWN19YlJTcxlrO3YIABMsdxoaAiiYGPY4YggYABkIZHKoAApkRNQALhCwyPZo2ISkgEpmGjg5xqwFKAaM2K6mHUmaHSqa0bqsvnbOnr7B0O4Rsfi+6aZZ+collcz2dc3tqtUxCSwLLR4XQA2g97vM4MBSoMjE0YEZkg85mAxAALaG2eGIuBHDpYKCDWFtXFQBHg3Ao4B8UqUdiDEHguZghlI1Ho1ioPGoWz9dl49jIEAVUnMuBYASC9gwQYAHlKwAAbnBbAA+YXMnGdNXzHRagC6wp1NF1kw8QA)

```ts
import * as React from 'react'
import { unstable_createRemixStub as createRemixStub } from "@remix-run/testing";
import { type DataFunctionArgs, json } from "@remix-run/node";

function rootLoader(args: DataFunctionArgs) {
    return json({})
}

function loader(args: DataFunctionArgs) {
    return json({})
}

createRemixStub([
  {
    id: "root",
    path: "/",
    loader: rootLoader,
    children: [
      {
        path: "/users/:username",
        element: <div />,
        loader, // <-- it doesn't like this
      },
    ],
  },
]);
```

It's fine with [this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFCiSxwDecArgHaozIBGANlgD6uSshhZsIYAA8AyjFY8U6ETnGSZ8xXAC+cIiTgAiAAKUp0gLRQOAenFdg7AOZGA3HXDR4LAFaoIdl19YlJTcxlrO3YIABMsd08GHzgYAE8wLDgAGQhkeKgAMQ58YECAQShndD0DMLMsCyj2W2JWcShEmgISmDKg4ggYXPysKAAKZCrUAC4cvILi9lKK6YBKZho4bbhKBSgg-0Dxph01mh0abt7+uD4FscnpuZHFm9XqjaYtnb3WA7gR3YJzOFyuqjEEkamgUPHGAG0ft8dnBgLE5kZBjAjAAaH7bMBiAAWGNsuPxdweUDmWNeYzxKNwROAfFilHYc0RKO2yO5BOJpNYqDGqFsMyFY3YyBACQZfLgWAEMvYMDmAB5YsAAG5wWwAPjlfPuoyghp2OjNAF05RaaJa1h4gA):

```ts
import * as React from 'react'
import { unstable_createRemixStub as createRemixStub } from "@remix-run/testing";
import { json } from "@remix-run/node";
import { type LoaderFunctionArgs } from "@remix-run/router"; // <-- not exported from @remix-run/node 🤔

function rootLoader(args: LoaderFunctionArgs) {
    return json({})
}

function loader(args: LoaderFunctionArgs) {
    return json({})
}

createRemixStub([
  {
    id: "root",
    path: "/",
    loader: rootLoader,
    children: [
      {
        path: "/users/:username",
        element: <div />,
        loader, // <-- no issue here
      },
    ],
  },
]);
```

### Expected Behavior

I expect to be able to define my loaders and actions with `DataFunctionArgs` and the `unstable_createRemixStub` API to accept them directly.

### Actual Behavior

I get a TypeScript error. Interestingly, `LoaderFunctionArgs` is only accessible via `@remix-run/router` and not `@remix-run/node`. Maybe that has something to do with it?

**Comment by MichaelDeBoey** [comment]
`LoaderArgs` is exported by `@remix-run/node` and is exactly what you're looking for I think

**Comment by kentcdodds** [comment]
I don't want to use LoaderArgs. I like DataFunctionArgs because it's a single import for both action and loader.

**Comment by brophdawg11** [comment]
Should be resolved in v2 via https://github.com/remix-run/remix/pull/7098

**Comment by kentcdodds** [comment]
Great! Thank you :)
