### ISSUE TITLE
Redirect on POST causes form submission

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#7107]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new page that has a `<Form>` and an `action` that returns a redirect to a second page.
2. Create the second page that also has a `<Form>` and an `action` that it submits to.
3. Submit the first page's form. Notice how it successfully redirects to the second page _but_ it also calls the POST on the second page's form (which is the undesired behavior).

### Expected Behavior

The redirection should only result in a GET to the second page. No POST request should be made.

### Actual Behavior

The first page's redirect (on form submission i.e. on POST) calls the second page's `action`.

**Comment by brophdawg11** [comment]
Can you provide a reproduction of this?  Only [307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) and [308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) redirects should preserve the method/body and POST to the redirected route.  301/302 should not.

I am seeing correct behavior in this simple reproduction: https://stackblitz.com/edit/remix-run-remix-e8dy88
