### ISSUE TITLE
Unable to use Node inspector on dev_v2 app server

### ISSUE THREAD

**Issue by hannesj** [remix-run/remix#7126]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Update to using v2 dev server by setting `future.v2_dev` to `true` in remix.config.js
2. Run the dev server by using `remix dev --debug`
3. Use the Node.js inspector to debug the application

### Expected Behavior

I would expect the debugger to be correctly attached and working.

### Actual Behavior

As the v2 dev server spawns a new process, the debugger is only [attached to the parent process](https://github.com/remix-run/remix/blob/main/packages/remix-dev/cli/commands.ts#L233) launching the app server, not the app server itself. This makes it impossible to debug the app server using the Node.js inspector.

**Comment by SCasarotto** [comment]
I also noticed this. I assumed I was doing something wrong but I did have it working in past versions.

**Comment by pcattori** [comment]
If you want to control your app server, you need to use the `-c` flag:

```sh
remix dev -c "remix-serve ./build"
remix dev -c "node ./server.js"
```

Then you can do whatever you would normally do to debug your app server:

```sh
remix dev -c "node --inspect node_modules/bin/remix-serve ./build"
remix dev -c "node --inspect ./server.js"
```
