### ISSUE TITLE
Node builtin polyfills not tree shaking correctly

### ISSUE THREAD

**Issue by ABuffSeagull** [remix-run/remix#7134]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Check this repo: https://github.com/ABuffSeagull/remix-node-tree-shake-bug
It's just importing 2 builtin modules: `node:assert/strict` and `node:process`. `node:assert/strict` is used directly in the loader, while `node:process` is exported from another file (notably *not* a `.server.ts` file).
This happens with basically every node builtin, with and without the `node:` prefix, as far as I can tell.

### Expected Behavior

Both `node:assert/strict` and `node:process` should be completely eliminated from the browser bundles.

### Actual Behavior

Only `node:process` is eliminated from the browser bundle. `node:assert/strict` is still being polyfilled.

**Comment by markdalgleish** [comment]
I've fixed this upstream, now released as a patch in `esbuild-plugins-node-modules-polyfill@1.3.1`: https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/blob/main/CHANGELOG.md#131---2023-08-14. You'll need to ensure your project is resolving this version.
