### ISSUE TITLE
HMR not working when default export is an anonymous function

### ISSUE THREAD

**Issue by tavoyne** [remix-run/remix#7139]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a new Remix app using `npx create-remix@latest`, replace the default-exported named function in the index route with anonymous function, start the dev server, and try changing the markup.

### Expected Behavior

Changes to the markup to be picked up.

(If this is expected, maybe it should be mentioned in the docs. Can do a PR in this case.)

### Actual Behavior

App is rebuilt but changes are not picked up by the browser.

**Comment by pcattori** [comment]
This is a [limitation of React Refresh](https://github.com/facebook/react/issues/21181), not Remix.
