### ISSUE TITLE
[Bug]: live reload rebuild twice when using tailwind watch

### ISSUE THREAD

**Issue by raymclee** [remix-run/remix#714]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

Follow the styling section for tailwindcss in remix doc

### Expected Behavior

live reload ignore the generated css file change

### Actual Behavior

[1] 💿 File changed: app/styles/app.css
[1] 💿 Rebuilding...
[1] 💿 Rebuilt in 226ms
[1] GET /form 200 - - 31.452 ms
[1] 💿 File changed: app/styles/app.css
[1] 💿 Rebuilding...
[1] 💿 Rebuilt in 170ms

**Comment by raymclee** [comment]
Im using jit mode

**Comment by edgesoft** [comment]
@raymclee This is not Remix specific. You can come around this using RSync

**Comment by edgesoft** [comment]
@raymclee I use tailwind like this

https://github.com/edgesoft/moaclayco

**Comment by raymclee** [comment]
@edgesoft thanks! It works

**Comment by ryanflorence** [comment]
Yeah, at the moment that's just how it is. I'm thinking we should debounce the rebuilds by like 100ms in our watcher and we'd be good.

**Comment by kentcdodds** [comment]
> debounce the rebuilds

Problem with this is it depends on how fast your machine is. May work $5k MacBooks at one debounce interval (that may even be too long), but for someone on an older/slower machine they may need more time.

I think we should explore a different approach. Having Tailwind support built-in could be one way :) Or support for customizing postcss a bit. That's one "compiler" that I don't expect we'll change in the future so it's probably safer to expose an experimental API for customizing.

**Comment by rkusa** [comment]
Instead of adding a workaround to Remix, it could also be an option to try to get postcss to not write files if their content didn't change (there is also existing issue for that https://github.com/postcss/postcss-cli/issues/320).

**Comment by kentcdodds** [comment]
> not write files if their content didn't change

This is the *real* solution 👍

**Comment by kentcdodds** [comment]
That issue isn't quite what we need. That issue just says: "if the input is the same as the output then don't save the file" but what we need is "if the output is the same as what's currently in the output then don't save the file." In any case, I'm going to look into implementing what we need.

**Comment by kentcdodds** [comment]
There we go :) https://github.com/postcss/postcss-cli/pull/417

**Comment by raymclee** [comment]
Is everyone using postcss-cli? I just tried to use tailwindcss instead of postcss-cli and it does cause rebuilding twice sometime but only reload once.
can anyone confirm with it?

**Comment by raymclee** [comment]
> Is everyone using postcss-cli? I just tried to use tailwindcss instead of postcss-cli and it does cause rebuilding twice sometime but only reload once. can anyone confirm with it?

ok still reload twice XD

**Comment by rkusa** [comment]
I am optimistic that the suggested change to postcss-cli lands eventually so if you are like me and want something now, but something that is very easy to migrate once the PR has landed, you can create a wrapper around the postcss-cli that 🙈-patches `fs.outputFile`:

In my case `bin/postcss.mjs`:
```js
#!/usr/bin/env node

import fs from "fs-extra";
import "postcss-cli/index.js";

const PREVIOUS_CONTENT = new Map();

const _outputFile = fs.outputFile;
fs.outputFile = async function outputFile(path, data) {
  const prev = PREVIOUS_CONTENT.get(path);
  if (prev && prev === data) {
    return; // unchanged
  }

  PREVIOUS_CONTENT.set(path, data);

  return _outputFile(path, data);
};
```

In my `package.json` script section:
```diff
- "build:css": "postcss --config ./config/ --dir app/styles styles/global.css",
+ "build:css": "./bin/postcss.mjs --config ./config/ --dir app/styles styles/global.css",
```

Once postcss CLI got the change, I am just going to remove the file and revert the `build:css` change.

Not pretty, but works at least for me for the time being.

**Comment by kentcdodds** [comment]
That workaround works for now, but for anyone coming to this issue later it's *very* temporary, and we'll have a better solution for this soon! Thanks @rkusa :)

**Comment by kentcdodds** [comment]
My PR was merged into postcss-cli!

If you update your version to 9.1.0 or greater you should no longer get a double-refresh when you save a file unless you actually do change the CSS (like in the Tailwind JIT case, if you change the class name on an element). In that case you'll still get the double-reload. @ryanflorence had some ideas of how to avoid that once and for all. But the nice this is with postcss-cli 9.1.0 you'll no longer get an unnecessary rebuild :)

**Comment by kentcdodds** [comment]
Just upgraded my app: https://github.com/kentcdodds/kentcdodds.com/commit/3f6637c2010a2821aba5358c84edbb7fd5d34047

I was able to remove the rsync workaround thing.

Here's how things worked without the rsync workaround before postcss-cli 9.1.0:

![image](https://user-images.githubusercontent.com/1500684/145642251-d8c210d5-09c0-44cc-8121-9fb37d6b9166.png)

And here's how things work now (still without the rsync workaround) with postcss-cli 9.1.0:

![image](https://user-images.githubusercontent.com/1500684/145642298-4cf16805-8c73-4b84-ad20-f09f1dcd60b9.png)

Much better :)

**Comment by kentcdodds** [comment]
If anyone wants to dig into the tailwind-cli to see whether this sort of change is necessary/would help that would be welcome :)

**Comment by babycourageous** [comment]
Thanks for this awesome improvement @kentcdodds !

**Comment by g3offrey** [comment]
@kentcdodds I just tried with Tailwind cli and it seems to rebuild twice even if there is no CSS changes.
Remix says that the CSS output file of Tailwind changed even if the content is the same ☹️

**Comment by raymclee** [comment]
> @kentcdodds I just tried with Tailwind cli and it seems to rebuild twice even if there is no CSS changes. Remix says that the CSS output file of Tailwind changed even if the content is the same ☹️

same here

**Comment by g3offrey** [comment]
I found a solution Tailwind side. The same way that you found one for PostCSS. I opened a PR here, if you want to check it out 😄 
https://github.com/tailwindlabs/tailwindcss/pull/6550

Also I created a reproduction repository https://github.com/g3offrey/reproduction-tailwind-duplication/

**Comment by g3offrey** [comment]
It should now be fixed for Tailwind CLI. I'll try again in the next 24 hours (when I can access my laptop). And if it works, I guess we could close the issue.

**Comment by g3offrey** [comment]
So I just tested it and it works fine now for the latest version of Tailwind CLI.
When you update content in TSX the Remix server restart once.
This is great 👍 

However if you add or remove a Tailwind class (so the CSS file changes) there is still a double rebuild. I think this is expected behavior at the moment. 

Do you think we can close this ticket @kentcdodds ? 😊

**Comment by girishk21** [comment]
would `devServerBroadcastDelay` in `remix.config` help to avoid that? 🤔

**Comment by g3offrey** [comment]
@girishk21 I wasn't aware of this configuration variable.
However as I understand it, it won't avoid to double build the project. It will only avoid to double refresh the browser.
It tells to wait X seconds before refreshing the browser.

**Comment by chaance** [comment]
Closing for now, as this is an inevitable issue if you're running multiple processes. `devServerBroadcastDelay` should help, and we'll have more to say on DX improvements here in the not-too-distant future.
