### ISSUE TITLE
Sub folders of `app/routes` are not respected in v2 routing.

### ISSUE THREAD

**Issue by Arcath** [remix-run/remix#7140]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Enable v2 routing
2. Create `app/routes/admin/_index.tsx` and `app/routes/admin/login.tsx`

I'm on Windows 10 with Node 20.

### Expected Behavior

`npx remix routes` should report the routes `admin` and `admin/login` pointed to those files.

### Actual Behavior

`npx remix routes` returns this:

```jsx
<Routes>
  <Route file="root.tsx">
    <Route index file="routes/_index.tsx" />
  </Route>
</Routes>
```

If I rename the files to `admin.login.tsx` and `admin._index.tsx` it works fine like this:

```
<Routes>
  <Route file="root.tsx">
    <Route path="admin" index file="routes/admin._index.tsx" />
    <Route path="admin/login" file="routes/admin.login.tsx" />
    <Route index file="routes/_index.tsx" />
  </Route>
</Routes>
```

**Comment by Arcath** [comment]
Just tried something else and `app/routes/admin/route.tsx` *is* detected as a route.

It appears that this is my mistake, doesn't help that I was looking at the epic stack for inspiration and didn't notice that it uses the flat routes package.

**Comment by kiliman** [comment]
In v2 routing, *all* routes must follow the flat routes convention. That is each segment is dot separated. By default, the route name is a file with extension.

`/admin/login` => `admin.login.tsx`

The only time you can use a folder in `v2` routing is for **colocation**. The route name is now the *folder* name, and the route module is a file inside named *route.tsx*. Any other files are ignored and treated as colocated files.

`/admin/login` => `admin.login/route.tsx` (colocate)

The `remix-flat-routes` package extends this routing convention to allow folders for **organization** as well as *colocation*.
