### ISSUE TITLE
{"stack":"Error: Failed to execute 'postMessage' on 'Window': (contractName, args, from, gas) => __awaiter(void 0, void 0, void 0, function* () {\r\n    const web3 = new web3_...<omitted>...}) could not be cloned.

### ISSUE THREAD

**Issue by zhanghanke** [remix-run/remix#7145]
### What version of Remix are you using?

1.3.6 (1.3.6.1000)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

when run the script: web3-lib.ts、ethers-lib.ts or any script with 'export function'

### Expected Behavior

run the script without error.

### Actual Behavior

{"stack":"Error: Failed to execute 'postMessage' on 'Window': (contractName, args, from, gas) => __awaiter(void 0, void 0, void 0, function* () {\r\n    const web3 = new web3_...<omitted>...}) could not be cloned.\n    at o.send (https://yann300.github.io/remix-script-runner/script-runner.js:2:137660)\n    at Object.<anonymous> (https://yann300.github.io/remix-script-runner/script-runner.js:2:147974)\n    at Generator.next (<anonymous>)\n    at o (https://yann300.github.io/remix-script-runner/script-runner.js:2:1253089)"}

**Comment by MichaelDeBoey** [comment]
Hello 👋
I think you may be in the wrong place. This GitHub repo is all about the Remix Web Framework which you can learn about at https://remix.run.
Closing this as you have mixed this up with the Remix IDE (https://remix-project.org) which is a completely different project.
