### ISSUE TITLE
V2 issue: RemixServer context types are not happy with EntryContext from remix-run/node

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#7239]
### What version of Remix are you using?

0.0.0-nightly-49e8da1-20230823

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[Here's the TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFCiSxwDeclAdgCZZQAqEAyjCjA2AczgBfOERLlKeGAFoOJAPSpuAN26160eCxgBPMFjgBRNkKMBhCFawAPeFJmkyAAUohgjxVABXNlU2CC4yOFVVOGNTVAAuOAAGADpUpMU2YFEACxgAGyNFABYATiwADg5kAEZFACYk+oBmJIqWunB9ZkwsH0d+LW5JaWJ3Lz7ffyDVeWpI6NisBOS0tMzsvMKS8qrahqbW9uaaGicGeC4CZAD8+DQjNlxpIPxgezgc5E58rGwARwCyxgAAoaABISiA4GJAFA1AwAA0EMoqEgbA0gmQMACqDsXESbACIAARtxkZDluiNAAJHBcKArOnIBmoCneXx2BzORKWaxcmBOJE0ACUzAhuHsCLgIGQUAA1gEwHAALysLCcbh8QTCMRg8HggA82H6gyg2igcEl3JgKqYHMcAqFUgCUHydqh8JgKVd+SkqgAfBSRadKWipVhmayUhpQWQnVZFDwTFgyIjyILnKo8iB8mQQyisDioGw4GwsAB3XrhjFYEFkQ0AQgAIgB5Gw8ACaAAVzJ8YLmAxEANQyuWKsDppgQ8EI7G4xKo6lYLE4vFhLAU8E5encFZLiNRvcUiQhiQ0IA):

```tsx
import * as React from 'react'
import { renderToString } from 'react-dom/server'
import { type EntryContext } from '@remix-run/node' // types: 0.0.0-nightly-49e8da1-20230823
import { RemixServer } from '@remix-run/react' // types: 0.0.0-nightly-49e8da1-20230823

export default async function handleRequest(
	request: Request,
	responseStatusCode: number,
	responseHeaders: Headers,
	remixContext: EntryContext,
) {
	const markup = renderToString(
		<RemixServer context={remixContext} url={request.url} />, // <-- error here
	)

	responseHeaders.set('Content-Type', 'text/html')

	return new Response('<!DOCTYPE html>' + markup, {
		status: responseStatusCode,
		headers: responseHeaders,
	})
}
```

### Expected Behavior

You should be able to pass context without issue

### Actual Behavior

You get the following error:

```
Type 'import("file:///node_modules/@remix-run/server-runtime/dist/entry").EntryContext' is not assignable to type 'import("file:///node_modules/@remix-run/react/dist/entry").EntryContext'.
  Types of property 'routeModules' are incompatible.
    Type 'RouteModules<EntryRouteModule>' is not assignable to type 'RouteModules'.
      'string' index signatures are incompatible.
        Type 'EntryRouteModule' is not assignable to type 'RouteModule'.
          Types of property 'meta' are incompatible.
            Type 'MetaFunction<unknown, {}> | V1_HtmlMetaDescriptor | undefined' is not assignable to type 'MetaFunction<unknown, Record<string, unknown>> | undefined'.
              Type 'MetaFunction<unknown, {}>' is not assignable to type 'MetaFunction<unknown, Record<string, unknown>>'.
                Types of parameters 'args' and 'args' are incompatible.
                  Property 'parentsData' is missing in type 'MetaArgs<unknown, Record<string, unknown>>' but required in type '{ data: any; parentsData: {} & RouteData; params: Params; location: Location; }'.
```

**Comment by brophdawg11** [comment]
huh - I don't know where `V1_HtmlMetaDescriptor` is coming from in there but I suspect that's the weasel

**Comment by brophdawg11** [comment]
Should be fixed by #7249 in tonights release

**Comment by kentcdodds** [comment]
Awesome! Thank you!

**Comment by sbaechler** [comment]
I just had this issue again with Remix 2.5.0. I noticed that in package.lock, `@remix-run/testing` resolved `@remix-run/node` version 2.5.1 while all others resolved to 2.5.0.

I fixed the issue by deleting package.lock and reinstalling all node modules.

**Comment by brophdawg11** [comment]
Huh - not entirely sure how that might happen - but if you find reproducible steps with installation or upgrades please open a new issue so we can take a look and see if we've got some deps wrong.

I created a utility for updating everything in lock step a while back that may be of use (I am too lazy to type them all out or manually update them all in `package.json` 😂 ): https://github.com/brophdawg11/upgrade-remix

**Comment by smyja** [comment]
> Huh - not entirely sure how that might happen - but if you find reproducible steps with installation or upgrades please open a new issue so we can take a look and see if we've got some deps wrong.
> 
> I created a utility for updating everything in lock step a while back that may be of use (I am too lazy to type them all out or manually update them all in `package.json` 😂 ): https://github.com/brophdawg11/upgrade-remix

Thanks
