### ISSUE TITLE
HMR not working with CloudFlare Workers template

### ISSUE THREAD

**Issue by sampolahtinen** [remix-run/remix#7240]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Run `npx create-remix@latest`
2. Define a location
3. Select `Just basics`
4. Where do you want to deploy? Choose `Cloudflare Workers`
5. TypeScript or JavaScript?: Choose `TypeScript`
6. Do you want me to run `npm install`?: Choose `yes`
7. After installation run the app with `npm run dev`
8. Introduce a change and navigate to: `http://127.0.0.1:8787/` for checking the changes

### Expected Behavior

After introducing a change in the codebase, HMR should reflect this in the browser as well.

### Actual Behavior

Changes are not being displayed and there is an error message displayed in the browsers console.

Browser console:
<img width="1706" alt="image" src="https://github.com/remix-run/remix/assets/19226286/3fa8c48b-8098-4aac-8a53-ee72d6fd93c7">

This error seems to be very close to what have solved in here: https://github.com/remix-run/remix/issues/6415

However, for Cloudflare workers you are not allowed to introduce any async-like code outside of the `fetch` definition.

Aside, HMR works nicely with Cloudflare Pages template.

**Comment by af** [comment]
Could you post your remix.config.js? I ran into a similar issue but resolved it with an update in my config, see https://github.com/remix-run/remix/issues/6415#issuecomment-1718405028

**Comment by sampolahtinen** [comment]
> Could you post your remix.config.js? I ran into a similar issue but resolved it with an update in my config, see [#6415 (comment)](https://github.com/remix-run/remix/issues/6415#issuecomment-1718405028)

Thanks for sharing the comment. This bug is present in the freshly created remix application using the templates. 

Thus, my `remix.config.js` file is the exact same what comes out from the templates:

```ts
/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  server: "./server.ts",
  serverConditions: ["workerd", "worker", "browser"],
  serverDependenciesToBundle: [
    // bundle verything except the virtual module for the static content manifest provided by wrangler
    /^(?!.*\b__STATIC_CONTENT_MANIFEST\b).*$/,
  ],
  serverMainFields: ["browser", "module", "main"],
  serverMinify: true,
  serverModuleFormat: "esm",
  serverPlatform: "neutral",
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
```

Seems that the `serverCondition` matches with yours 🤔 

There is also another issue which might be related with the dev server. When repeatedly triggering browser refresh, sometimes some chunks get stalled in `pending` state, blocking the browser from finishing with page loading. The browser tab keeps on displaying loading/spinner for minutes without finishing. @af have you experienced this?

This might be a topic for another issue once I gain a bit more data on this one.

**Comment by jasonkuhrt** [comment]
Maybe related https://github.com/cloudflare/workers-sdk/issues/3942

**Comment by sampolahtinen** [comment]
@pcattori would you have any ideas what might be causing this? Or any tips where to look in the code base if I were to debug this and/or coming up with a solution?

**Comment by af** [comment]
@sampolahtinen Yeah your config is almost identical to mine. The only extra bit I have is below- I doubt the difference is relevant but I'll paste it just in case:

```
  serverNodeBuiltinsPolyfill: {
    modules: {},
  },
```

**Comment by sampolahtinen** [comment]
> @sampolahtinen Yeah your config is almost identical to mine. The only extra bit I have is below- I doubt the difference is relevant but I'll paste it just in case:
> 
> ```
>   serverNodeBuiltinsPolyfill: {
>     modules: {},
>   },
> ```

No difference unfortunately

**Comment by sampolahtinen** [comment]
This issue is not present any longer with Remix v2.0.1 and Wrangler 3.10.1.

For future readers, if your changes are not being displayed in the browser, check the [docs](https://remix.run/docs/en/main/other-api/dev#hmr-react-fast-refresh-limitations) and specifically the point about components needing to be named instead of anonymous.
