### ISSUE TITLE
Warning esm-only package but server module format is esm

### ISSUE THREAD

**Issue by woody146** [remix-run/remix#7263]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I use any esm only package such as lodash-es, and set serverModuleFormat = 'esm' in remix.config.mjs
Then start dev server, it displays 
```
warn  esm-only package: lodash-es
```

### Expected Behavior

If I set serverModuleFormat = 'esm', remix should not display warning `esm-only package`

### Actual Behavior

Display warning `esm-only package`

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction of this?  If I do a fresh `npx create-remix@latest` and choose the Express template (which is ESM out of the box) and then add and import from `lodash-es`, I don't see this warning.

**Comment by woody146** [comment]
You can check it https://github.com/woody146/remix-example

**Comment by brophdawg11** [comment]
This is already resolved in Remix v2 which will be releasing soon.  I just tested on `2.0.0-pre.2` and confirmed there's no longer a warning.
