### ISSUE TITLE
bareImports.js does not handle ESM/TS path aliases

### ISSUE THREAD

**Issue by cyberwombat** [remix-run/remix#7275]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Given a path alias in TSConfig:
```
"paths": {
      "~/*": ["app/*"]
    },
```
and package.json set to:
```
"type":"module"
```
I get errors in remix run module `node_modules/@remix-run/dev/dist/compiler/server/plugins/bareImports.js` when doing an import in my code such as:
```
import { getLocaleFromRequest } from '~/lib/utils.js'
```
The code runs though. I am currently commenting out that error log. I am using this as part of [Shopify Hydrogen](https://github.com/Shopify/hydrogen) using their demo store but with type set to module. Works fine without that so I think something needs ESM addressing.

### Expected Behavior

No errors to be thrown

### Actual Behavior

<img width="739" alt="Screenshot 2023-08-28 at 7 34 48 AM" src="https://github.com/remix-run/remix/assets/777498/0cb3cc5f-7ec0-42fa-b44c-614bf04e9746">

**Comment by cyberwombat** [comment]
This is still an issue. I am on 2.3.0

**Comment by typytypytypy** [comment]
@cyberwombat did you figure out how to resolve this? I have the same issue
