### ISSUE TITLE
`shouldRevalidate` is skipped

### ISSUE THREAD

**Issue by buschco** [remix-run/remix#7310]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. export `shouldValidate` function that always returns false
2. call api that counts calls
3. navigate back and forward and watch counter go up

I also added a test that reproduces it [!7309](https://github.com/remix-run/remix/pull/7309)

### Expected Behavior

- `shouldValidate` should be called
- if `souldValidate` returns false `loader` should not be called

### Actual Behavior

- `shouldValidate` is not being called
- `loader` is executed

**Comment by brophdawg11** [comment]
Navigating away from and back to a route is not a revalidation, so `shouldRevalidate` is not called.  Coming back to a route is a fresh new instance of the route and therefore a fresh load of the data.  This is required because once a route is navigated away from, it's loader data no longer exists.  

Revalidations are when the loader data already exists and Remix is about to reload it after an `action`, or a `useRevalidator` call, or a search param update, etc.

**Comment by buschco** [comment]
Thanks for the reply. 

The docs are confusing/make false promises imo:

> This function lets apps optimize which routes data should be reloaded after actions and for client-side navigations.
from https://remix.run/docs/en/1.19.3/route/should-revalidate#defaultshouldrevalidate

**Comment by brophdawg11** [comment]
We always accept PRs to improve the docs!

**Comment by St2r** [comment]
Hello. Is there a way for using existed loader data, or just skip loader call when 'Navigating away from or back to a route'.

**Comment by brophdawg11** [comment]
It depends on whether the route remains or not during the navigation away and back.

If your route persists (such as the parent route in `/parent -> /parent/child -> /parent`), then your loader will be revalidated according to [`shouldRevalidate`](https://remix.run/docs/en/main/route/should-revalidate).

If the route disappears (such as `/parent -> /elsewhere -> /parent`) then you would need to implement [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) headers to use cached data
