### ISSUE TITLE
Directory import is not supported (internal MUI modules) 2.0.0-pre.3

### ISSUE THREAD

**Issue by telcy** [remix-run/remix#7314]
### What version of Remix are you using?

2.0.0-pre.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. install MUI
2. try to use some MUI component that internally does a directory import

(I will try to add a repro later)

### Expected Behavior

Directory imports should be handled by Remix. I am able to add `/index.js` to my own imports but I am unable to add `/index.js` to MUI internal imports.

### Actual Behavior

<img width="1068" alt="Screenshot 2023-08-30 at 23 05 31" src="https://github.com/remix-run/remix/assets/3081527/0dc064aa-8601-497d-9ae8-21c4b3eee190">

**Comment by pcattori** [comment]
@telcy is thie for a new project? or are you migrating an existing project to v2?

If migrating, what did you have your `serverModuleFormat` set to before migrating and did you change it to anything else after migrating?

**Comment by telcy** [comment]
exports seem to be an issue as well

```
export { default } from './Button';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Repro
https://github.com/telcy/remix-import-export-issue

**Comment by pcattori** [comment]
As a workaround, can you use `serverModuleFormat: "cjs"` in your `remix.config.js`?

**Comment by pcattori** [comment]
Related to https://github.com/mui/material-ui/issues/30671

**Comment by pcattori** [comment]
Yea I think you'll want to keep `serverModuleFormat` set to `cjs` if you are using MUI due to https://github.com/mui/material-ui/issues/30671

**Comment by pcattori** [comment]
Closing as this in inactionable in Remix until MUI provides better support for ESM

**Comment by U-4-E-A** [comment]
> Closing as this in inactionable in Remix until MUI provides better support for ESM

Can I ask what the actual problem is? I am having the same issue with certain other packages.
