### ISSUE TITLE
Can't set multiple `Set-Cookie` headers in an `action`

### ISSUE THREAD

**Issue by martinmckenna** [remix-run/remix#7334]
### What version of Remix are you using?

1.6.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Have your client reach out to a remix route that as an `action` like so:

```ts
import type { ActionArgs } from "@remix-run/node";
import { createCookie, json } from "@remix-run/node";

import { AUTH_COOKIE, AUTH_EXP_COOKIE } from "app/cookies"

export const setCookie = (key: string, value: any) => {
  const createdCookie = createCookie(key, {
    path: "/",
    sameSite: "lax",
  });
  return createdCookie.serialize(value);
};

export async function action({ request }: ActionArgs) {
  return json(
    {},
    {
      headers: {
        "Set-Cookie": await setCookie(AUTH_COOKIE, ""),
        // @ts-expect-error
        "Set-Cookie": await setCookie(AUTH_EXP_COOKIE, ""),
      },
    }
  );
}
```

2. Call endpoint
3. Check response headers in dev tools and see there is only 1 `Set-Cookie` header:

![Screen Shot 2023-09-04 at 4 22 53 PM](https://github.com/remix-run/remix/assets/7387001/dd24f772-d7e6-401f-a12d-b444b4015e23)

### Expected Behavior

See 2 `Set-Cookie` headers

### Actual Behavior

Only seeing 1 `Set-Cookie` header

**Comment by martinmckenna** [comment]
this was already brought up a while back after not working with `redirect`, but someone mentioned it wasn't working in `loader`s and now i'm seeing similar behavior in an `action`, so I figured i'd create a new issue:

https://github.com/remix-run/remix/issues/231#issuecomment-1218371334

**Comment by martinmckenna** [comment]
nvm fix is to create a `new Headers()` instance and add them that way:

```ts
  const authCookieHeaders = new Headers();
  authCookieHeaders.append("Set-Cookie", await setCookie(AUTH_COOKIE, ""));
  authCookieHeaders.append("Set-Cookie", await setCookie(AUTH_EXP_COOKIE, ""));

  return json(
    {},
    {
      headers: authCookieHeaders,
    }
  );
```

**Comment by MattyBalaam** [comment]
> nvm fix is to create a `new Headers()` instance and add them that way:
> 
> ```ts
>   const authCookieHeaders = new Headers();
>   authCookieHeaders.append("Set-Cookie", await setCookie(AUTH_COOKIE, ""));
>   authCookieHeaders.append("Set-Cookie", await setCookie(AUTH_EXP_COOKIE, ""));
> 
>   return json(
>     {},
>     {
>       headers: authCookieHeaders,
>     }
>   );
> ```

This throws a type error in TypeScript

<img width="478" alt="Screenshot 2023-09-28 at 13 47 35" src="https://github.com/remix-run/remix/assets/1246923/76a8335c-8868-493d-ac0a-eab3a01bba80">

**Comment by martinmckenna** [comment]
@MattyBalaam can you post your full code. Also i'm on typescript `5.2.2` if that makes a difference
