### ISSUE TITLE
If useLoaderData has nested structure, then TS infer is wrong

### ISSUE THREAD

**Issue by rlesniak** [remix-run/remix#7336]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[Go here ](https://www.typescriptlang.org/play?ts=5.1.6#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQokscA3nAFaoQB2cAvnCIlyAAUohgADwC0UAK7cA9NwgATLLQbho8NnNRYAMhGTqoAEWQxk-QcVJkxWCTPlLKeGJrpZJTeGgAnty4ggr4wDxwADYmZgAUAJSsdHBwlDByULycPPFs3FioMFiqAFyscLhZlNwwFYUA7nCWJUm2fIn0fHQ+fjpw6gTIctGE4TCRvBgQciUAwiSQhXXtLKlVPMWDVjYAvHD6RnFYFrsAPDCBYFgQBDEnUAB8Sb1piopwABYQAG6ncD+AK+pywABo4IFZnBGsBotE4AYsHAYF8rHAAAbVKC1GAYuDAdCtLAbVS7AB0hWKpTem242wKRRK5Uq2NxHTgBzJ1lpH2+QKggP+UAhyG4qkhs0FYEov0i+kx3OQlKZpXxhMxxSgwG4AHN8SpGuSNmysHVaRksrxzqpgL8nsU5AQCOdFLb7d06EA)

and hover over pointed places.

Result in runtime is obviously string, but if `useLoaderData` has nested structure, then parsing `Date` -> `string` isnt working

### Expected Behavior

In all places `current` should have `string` type

### Actual Behavior

When structure is nested, TS wrong infers types and returns object instead of primitive.

**Comment by brophdawg11** [comment]
`current` does have `string` in all places.  When you hover over `nested` the type you're seeing is not saying `nested.current` is a `Date`, it's saying that `nested` is of type:

```ts
SerializeObject<UndefinedToOptional<{ current: Date }>>
```

And the `SerializeObject` type is what does the conversion from `Date -> String`, so `nested.current` is always type `string`.

See [this updated playground](https://www.typescriptlang.org/play?ts=5.1.6#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQokscA3nAFaoQB2cAvnCIlyAAUohgADwC0UAK7cA9NwgATLLQbho8NnNRYAMhGTqoAEWQxk-QcVJkxWCTPlLKeGJrpZJTeGgAnty4ggr4wDxwADYmZgAUAJSsdHBwlDByULycPPFs3FioMFiqAFyscLhZlNwwFYUA7nCWJUm2fIn0fHQ+fjpw6gTIctGE4TCRvBgQciUAwiSQhXXtLKlVPMWDVjYAvHD6RnFYFrsAPDCBYFgQBDEnUAB8Sb1pqrsAdIXFpRtpikUcAAegB+DYfazfIolVSfapQWowf5pVGowEg8EbXBbXRwH6wipsBFIjpwA6Q5DYmpYOobDFgt7pLCZbJwc6qYAANyexTkBAI50UnJ53ToQA).

**Comment by rlesniak** [comment]
Why such behavior is correct?

**Comment by brophdawg11** [comment]
This is how TypeScript works.  The type of `nested` is a serialized version of an object with a `Date` field.  The serialization turns that date field a string.  

Here's a similar example using TS primitives: https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAKgFgSwHYHMoF4oCUIEcCuCAThACYA8A3gFBRQkHFkBcUAzsEcigDS1QB7MMAQCkAQwA2AflYcuqagF8AfNWoB6DbDjRQkKLpLs4AgO5sowXVCQQOZQQCMAVhADGwKOMsJLZhGsrGwADIRExKRCoTW0AMwQISVIoJwhuQWFRCUkeVPwva2gcRhIKFStwaClgCCJLa3EvNnx3OBitYKaoEOtuADpw7KioP1sBKEkxFDrvJEyInKgEpNJqSQhCxFRWeG4AblpOgD1pdU69hrgic0txebqbolSPcXw2PRshyMllxOTDD4XhB5gBbcSkaCxeh4QhlVIgYLFWFMcqVSDUPqoDBQGh0BhwlhQADkbAEoM22xQxOU1CAA
