### ISSUE TITLE
bug(templates): default entry.server.tsx fails type check with "Argument of type 'PassThrough' is not assignable to parameter of type 'BodyInit | null | undefined'."

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#7357]
### What version of Remix are you using?

2.0.0-pre.8

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Due to #7271, the default entry.server.tsx file fails type checking with the following error message from TypeScript:

`Argument of type 'PassThrough' is not assignable to parameter of type 'BodyInit | null | undefined'.`

### Expected Behavior

The file entry.server.tsx should have no TypeScript errors.

### Actual Behavior

See screen shot below from VS Code.
![Screenshot 2023-09-07 at 09 01 20](https://github.com/remix-run/remix/assets/728407/76520b9e-9ac7-484d-943c-98678c329533)

**Comment by brophdawg11** [comment]
Yeah I've noticed this on a few local tests too - just haven't gotten around to PR-ing it yet.  The fix, I'm pretty sure, is `Readable.toWeb(body) as ReadableStream`

**Comment by brophdawg11** [comment]
Fixed by #7361 - will be out in a prerelease shortly 👍
