### ISSUE TITLE
[Bug]: useTransition does not detect transition?

### ISSUE THREAD

**Issue by robertwt7** [remix-run/remix#737]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

Follow the [tutorial](https://remix.run/docs/en/v1/tutorials/blog), up until the end where the **Actions** area is, i tried to use `useTransition` but the state never change, thus the button label never change to "Creating..."

I'm very new to remix, just trying it out so please let me know if i'm wrong in any way.

Also the `console.log` doesn't show on the client side, i'm not sure why as well, it only shows on the server console
Code:
```
import { Form, redirect, useActionData, useTransition } from "remix";
import type { ActionFunction } from "remix";
import { createPost } from "../posts/post";
import invariant from "tiny-invariant";


export let action: ActionFunction = async ({ request }) => {
	await new Promise(res => setTimeout(res, 5000));

	let formData = await request.formData();

	let title = formData.get("title");
	let slug = formData.get("slug");
	let markdown = formData.get("markdown");

	let errors = {};
	if (!title) errors.title = true;
	if (!slug) errors.slug = true;
	if (!markdown) errors.markdown = true;

	if (Object.keys(errors).length) {
		return errors;
	}


	invariant(typeof title === "string");
	invariant(typeof slug === "string");
	invariant(typeof markdown === "string");
	await createPost({ title, slug, markdown });

	return redirect("/admin");
}


export default function NewPost() {
	const errors = useActionData();
	const transition = useTransition();
	console.log("What happened to transition: ", transition)
	return (
		<Form method="post">
			<p>
				<label>
					Post Title:{" "}
					{errors?.title && <em>Title is required</em>}
					<input type="text" name="title" />
				</label>
			</p>
			<p>
				<label>
					Post Slug:
					{errors?.slug && <em>Slug is required</em>}
					<input type="text" name="slug" />
				</label>
			</p>
			<p>
				<label htmlFor="markdown">Markdown</label>{" "}
				{errors?.markdown && <em>Markdown is required</em>}
				<br />
				<textarea rows={20} name="markdown" />
			</p>
			<p>
				<button type="submit">
					{transition.submission ? "Creating..." : "Create Post"}

				</button>
			</p>
		</Form>
	)
}
```

### Expected Behavior

`useTransition` to return correct state

### Actual Behavior

When i `console.log(transition)`, it only returns the state 1 time (at the server console, not at the client)

```
What happened to transition:  {
  state: 'idle',
  submission: undefined,
  location: undefined,
  type: 'idle'
}
```

**Comment by robertwt7** [comment]
Maybe it's related to #240? not sure.. has anyone else ever make `useTransition` work after form submission?

**Comment by robertwt7** [comment]
Solved from discord

**Comment by dante01yoon** [comment]
@robertwt7  I'm facing this issue right now. Could you give me links or piece of advice how you handled this?
