### ISSUE TITLE
typeof loader is unusable if loader has a conditional redirect inside

### ISSUE THREAD

**Issue by ivosabev** [remix-run/remix#7402]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```typescript
export async function loader() {
  if (someCondition) {
    return redirect('/some-page');
  }

  const data = {foo: 'bar'};

  return {data};
}

export default function Component() {
  const {data} = useLoaderData<typeof loader>();
  return <div />;
}
```

### Expected Behavior

`data` to be properly typed as `{data: {foo: string}}`

### Actual Behavior

Due to the redirect `TypedResponse<never>` is added to the loader return types, which is correct.

But the `useLoaderData` is never called if there is redirect and the data that it receives is always `{data: {foo: string}}`, so it is type wrong if you use the `typeof loader`. You can circumvent this if you add your own types, but it would be nice if this is solved by Remix itself, since this is a common use case.

```typescript
Promise<TypedResponse<never> | {
    data: {
        foo: string;
    };
}>
```

**Comment by corygibbons** [comment]
@ivosabev I've been getting around this by throwing the redirect instead of returning it.

```js
if (someCondition) {
  throw redirect('/some-page');
}
```

**Comment by kiliman** [comment]
Remix type inference only works for data returned via the `json` or `defer` helpers. If you return a `redirect`, then it's just a generic `Response` so that breaks type inference.

That's why you should always `throw` other `Response` objects.

https://github.com/remix-run/remix/blob/30bcd9e9dfbeda1707329da017f9ceccfac21521/packages/remix-server-runtime/responses.ts#L34-L36

**Comment by pcattori** [comment]
Closing as `throw`ing redirects is the intended way to author `loader`s and correctly excludes redirects from participating in type inference.
