### ISSUE TITLE
`type { UIMatch } from '@remix-run/router'` is different from `type { UIMatch } from '@remix-run/react'`

### ISSUE THREAD

**Issue by lensbart** [remix-run/remix#7438]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Compare both exports and observe that they are different:
* `UIMatch` from `@remix-run/router` takes two type arguments
* `UIMatch` from `@remix-run/react` takes one type argument

Probably the former should be used in both cases, since it’s more flexible.

### Expected Behavior

Both types are the same

### Actual Behavior

`!(`both types are the same`)`

**Comment by lensbart** [comment]
Additionally, it would be nice if other exported types (e.g. `LoaderFunction`) would be exported from just one Remix package (i.e., not from both `@remix-run/node` and `@remix-run/router`), if that makes sense.

**Comment by brophdawg11** [comment]
> It would be nice if other exported types (e.g. LoaderFunction) would be exported from just one Remix package

Only exporting from one package would make the layered approach of building Remix on top of React Router impossible.  `@remix-run/router` should be considered an implementation dependency so generally speaking you shouldn't be importing anything from there and shouldn't need it in your `package.json`.  If there are aspects you need in your application that are not exposed through something like `@remix-run/react` or `@remix-run/node` then please file a separate issue for those and we can see if something should be re-exported through a Remix-specific package.

**Comment by lensbart** [comment]
@brophdawg11 nice — thanks for that suggestion. `UIMatch` is the only reason I currently installed the `@remix-run/router` dependency.

**Comment by brophdawg11** [comment]
This is resolved by #7464 and will be available in the next release 👍
