### ISSUE TITLE
Remix v2 causes type errors for `mdx` components

### ISSUE THREAD

**Issue by Alex-Yakubovsky** [remix-run/remix#7448]
### What version of Remix are you using?

2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Using `create-remix` CLI, create an new project
2. Create a directory like `app/routes/example` within the project
3. Create the `mdx` file `app/routes/example/Foo.mdx` like:

```mdx
## Hello World
```

4. Import the new `mdx` file

```tsx
// app/routes/example/route.tsx
import Foo from './Foo.mdx'

export default function Route() {
  return <Foo /> // causes "JSX element type 'Content' does not have any construct or call signatures." error
}
```

### Expected Behavior

No Typescript error

### Actual Behavior

A type error

```
'Foo' cannot be used as a JSX component.
  Its type 'typeof import("*.mdx")' is not a valid JSX element type.ts(2786)
```

**Comment by Alex-Yakubovsky** [comment]
Worth also mentioning that downgrading to remix `1.19` makes the error go away

**Comment by markdalgleish** [comment]
I was able to get an error when using pnpm (not with npm), but it's a different error to the one you're reporting. Would you be able to share a repro with a lock file?

**Comment by markdalgleish** [comment]
Also, if you install `@types/mdx` at the root of your project, does it fix the issue?

**Comment by Alex-Yakubovsky** [comment]
Sure, here's the example repo: https://github.com/Alex-Yakubovsky/remix-mdx-type-error-example. I am indeed using `pnpm`.

> Also, if you install @types/mdx at the root of your project, does it fix the issue?

Yup, looks like that fixes the type error!

**Comment by markdalgleish** [comment]
Thanks for sharing the repro! I've just merged a fix that will go out in the next release.

**Comment by Alex-Yakubovsky** [comment]
Awesome, thanks for looking into this! I'll go ahead and close the issue.

**Comment by markdalgleish** [comment]
No worries! I've just checked your repro against the nightly release and it's looking good to me.
