### ISSUE TITLE
[bug] Search box in Remix v2 docs show links to v1 instead of v2

### ISSUE THREAD

**Issue by off99555** [remix-run/remix#7453]
### What version of Remix are you using?

v2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Go to https://remix.run/docs/en/2.0.0
And press Ctrl-K to open search box. Type in anything e.g. `meta` and you will see that all the links lead to v1 instead of v2.
![image](https://github.com/remix-run/remix/assets/15215732/916ae3f8-eb58-4494-abd0-fc214761cf13)

### Expected Behavior

Links should go to v2.

### Actual Behavior

Links go to v1.

**Comment by bluefire2121** [comment]
Perhaps the v2 links aren't indexed yet

**Comment by brophdawg11** [comment]
Thanks for the heads up!  

We updated the search index yesterday.

As for the dead 1.19.3 links, we've setup redirects from pages the existed in the v1 docs to the new pages in v2.  If you want to see the specific v1 versions you can update those URLs to poiont to the 1.19.3 release:

https://remix.run/pages/technical-explanation -> https://remix.run/docs/en/1.19.3/pages/technical-explanation
