### ISSUE TITLE
v2 - manual flag does not work with CJS server bundles

### ISSUE THREAD

**Issue by robertjpayne** [remix-run/remix#7480]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new basic remix app e.g. `npx create-remix`
2. Rename remix.config.js to remix.config.mjs
3. Change the `serverModuleFormat` to `cjs`
4. Edit `package.json` removing `"type": "module"`
5. Run `npm run dev`
6. Make changes in a route and refresh browser

### Expected Behavior

One should see the changes from edited files

### Actual Behavior

No changes are visible because the built in remix dev server with the manual flag only busts ESM caches and has no support or warnings for CJS server bundles.

**Comment by pcattori** [comment]
Fixed by #7487
