### ISSUE TITLE
HMR does not work with anonymous exports

### ISSUE THREAD

**Issue by moishinetzer** [remix-run/remix#7496]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

In a route file, instead of naming the route function, export it as default without a name:

```tsx
export default function () {
  return (
    <div>Hello World</div>
  )
}
```

1. Run the dev server.
2. Make some changes (either to the markdown or the styling)
3. Hit save

### Expected Behavior

HMR kicks in and hot-reloads the changed element/s

### Actual Behavior

Nothing happens. The page needs to be reloaded for changes to be reflected on screen.

### Reproduction Repository

https://github.com/moishinetzer/remix-broken-hmr-repro (Note: Run this locally - not on codesandbox)

**Comment by pcattori** [comment]
This is a limitation of React Fast Refresh (e.g. see the [`Limitations` section for Fast Refresh on Next's docs](https://nextjs.org/docs/architecture/fast-refresh#limitations)), not Remix. For React Fast Refresh to track component changes, those components need to be named.

**Comment by moishinetzer** [comment]
Thanks for the reply! Can we add this to the docs? It was a very tricky bug to find in the first place.

**Comment by pcattori** [comment]
> Thanks for the reply! Can we add this to the docs? It was a very tricky bug to find in the first place.

Good suggestion! Here's the PR: https://github.com/remix-run/remix/pull/7501
