### ISSUE TITLE
Element type invalid warning using useFetcher with a Form action

### ISSUE THREAD

**Issue by mateosantosdev** [remix-run/remix#7497]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

This is the failing code: (see the output)

```typescript
// app/routes/api.prueba.ts
import { json, type ActionFunctionArgs } from '@remix-run/node';
export async function action({ request }: ActionFunctionArgs) {
    return json({ error: false, ok: true });
}


// app/routes/basic.tsx
export default function Basic() {
    const fetcher = useFetcher();
    useEffect(() => {
        console.log(fetcher.state);
    }, [fetcher.state]);
    return (
        <fetcher.Form method="post" action="/api/prueba">
            <input type="submit" value="submit" />
        </fetcher.Form>
    );
}
```

But this is working as expected:

```typescript
// app/routes/basic.tsx
export async function action({ request }: ActionFunctionArgs) {
    return json({ error: false, ok: true });
}

export default function Basic() {
    const fetcher = useFetcher();
    useEffect(() => {
        console.log(fetcher.state);
    }, [fetcher.state]);
    return (
        <fetcher.Form method="post">
            <input type="submit" value="submit" />
        </fetcher.Form>
    );
}

```

### Expected Behavior

See in the console:
```
idle
submitting
idle
```

### Actual Behavior

The console output:
```
idle

submitting

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by brophdawg11** [comment]
Thanks for the reproduction!  It looks like this is a small regression with the React Router `route.lazy` integration - I'll get a fix in.  

I don't think this should cause any functional issues since this is just a warning on element creation and React will never try to render this element (since it's a resource route), but if it does you can probably workaround it by exporting an empty component from your resource route:

```js
export default function Component() {
  return null;
}
```

**Comment by mateosantosdev** [comment]
Thanks for the reply @brophdawg11 !

You are right. It didn't cause any functional issue, just a warning... 

I've tested your solution and it's working as expected.

**Comment by asciant** [comment]
For what it's worth, I am experiencing the same issue in 2.0.1 with resource routes. Exporting an empty component in the resource route removed the warning.

**Comment by theskillwithin** [comment]
I am still experiencing as well

**Comment by brophdawg11** [comment]
Can you provide a reproduction?  This warning goes away in 2.0.1 with the OP's example code.

**Comment by asciant** [comment]
Unfortunately I wasn't able to reproduce the error, there must have been an issue with the packages on my end (I had updated but must have been still using `2.0.0`). @theskillwithin did you have any luck?

**Comment by theskillwithin** [comment]
I am on 2.0.1 oddly this error only shows for me when hot reloading takes place (making a change in a file and hitting save).

I have found when I comment out line 48 here the problem goes away.  which is very odd.  not sure what to do

https://gist.github.com/theskillwithin/3c10783cac280e70263f4976ea5e23c9#file-loadmore-ts-L48
