### ISSUE TITLE
v2 - server code not pruned in route

### ISSUE THREAD

**Issue by akomm** [remix-run/remix#7505]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```sh
npx create-remix --template remix-run/remix/templates/remix
cd [project name]
npm i arangojs # other packages possible
```

Go to `app/routes/_index.tsx`
add 
```ts
import {aql} from "arangojs"
export function loader() {
  console.log(aql)
  return json({})
}
```

Open the page in browser and check network tab for `build/routes/_index-[hash].js` request and its contents:

You will find `node_modules/arangojs/*` modules being bundled with client.

### Expected Behavior

Server code not bundled

### Actual Behavior

Server code is bundled

**Comment by akomm** [comment]
Looks like a very old issue from 1.x to me (not sure if it was ever fixed). It can be to a degree worked around by create a function in a separate file that imports the server dependencies and then import the function into the route and use in loader, but doing it for anything from node_modules would be an absurd expectation.

**Comment by akomm** [comment]
@brophdawg11
```sh
rm -rf .cache build public/build
yarn build
```
and `public/build/_index-[hash].js` still contains the server code.
I think its not only `dev`

**Comment by pcattori** [comment]
Does the `package.json` for `arangojs` specify `sideEffects: false`?

If its not specified or set to `true`, then it will remain as side-effects cannot be robustly treeshaken.

If that's the case, you can re-export from a `.server.ts` file to work around that limitation of `arangojs`:

```ts
// arangojs.server.ts
export { aql } from 'arangojs'
```

Using a `.server.ts` file will force that code to be treated as server-only even if `arangojs` doesn't set `sideEffects: false`.

**Comment by akomm** [comment]
Yeah, they don't have it specified. Now it makes sense.

I initially used the .server.ts approach. The problem with this is that TS will always search for the shortest path and either not show the import option at all, or if shown, still import it after picking directly from the `node_modules`. So every import needs to me written manually. I'm not a big fan of the `.server.ts` to be honest.

Is it viable to add an option to remix.config to prune certain packages always from client code? Not necessary partial, just simply an package specifier?

**Comment by machour** [comment]
Closing this issue, as guidance was provided.
Please open a new conversation if your suggestion for a new option is still relevant 🙏🏼
