### ISSUE TITLE
Argument of type 'Element' is not assignable to parameter of type 'ReactNode'

### ISSUE THREAD

**Issue by ric980** [remix-run/remix#7514]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've upgraded Remix to version 2 and now I get the following type error in code that is not written by me:

> Argument of type 'Element' is not assignable to parameter of type 'ReactNode'. Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.

I've deleted and revealed again my entry.client.tsx and entry.server.tsx, but the error persists. Both files are untouched by me and both files has that same type error.

What am I missing?

Thank you.

### Expected Behavior

I should have no type errors on code generated by Remix.

### Actual Behavior

I get a type error.

> Argument of type 'Element' is not assignable to parameter of type 'ReactNode'. Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.

**Comment by kinday** [comment]
Getting the same error after upgrade for every `Form` component.

**Comment by Nedi11** [comment]
Same problem

**Comment by ric980** [comment]
Error no longer occurs with `"@types/react": "^18.2.25"`.

**Comment by perfectbase** [comment]
happening again in `18.2.39`. Downgraded to `18.2.38` and it worked.

**Comment by Thykof** [comment]
version `18.2.55` is fine

**Comment by nsmithdev** [comment]
I had an indirect dependency on @types/prop-types >= 15.7.8 in my package-lock.json file.

Adding @types/prop-types with version 15.7.7 fixed the problem
