### ISSUE TITLE
Flash of Unstyled Content in V2

### ISSUE THREAD

**Issue by martinmckenna** [remix-run/remix#7516]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. create v2 remix app with streaming and route-based CSS that is requested on route change
2. See flash of unstyled content between page loads

Here is an mp4 of my staging site that is running remix v1 (with no streaming). as you can see, there is no flash of unstyled content, even though the route CSS is being reloaded on each page route:

https://i.imgur.com/6V11Bd2.mp4

and here is a video of my production site (running remix v2 with streaming) and most of the time, the page margins and paddings and widths are jumping after the CSS was reloaded and applied:

https://i.imgur.com/EmZj6GO.mp4

FWIW, I also observed this only happens in chromium browsers

Regardless of the site, my methods for CSS have remained the same:

1. On initial load, the component-level CSS, which sets things like colors, padding and margins on buttons, links, menus, tables, etc are fine
2. Each route CSS file really only contains things like higher-level widths, margins, and paddings and this gets loaded on each route change
    * this is also why I'm only seeing a flash for the actual layout and not colors

### Expected Behavior

No flash of unstyled content

### Actual Behavior

flash of unstyled content

**Comment by martinmckenna** [comment]
if the answer to this is "this is the tradeoff with using APIs like `createReadableStreamFromReadable`," that's fine I suppose, but it'd be nice to have some kind of official message on whether this is expected behavior or not and maybe some tips to avoid this.

I feel like i'm just going to have to bundle ALL my CSS and not have any route-specific stuff

**Comment by martinmckenna** [comment]
one more thing i noticed - because this is happening, using anchors in the URL is basically rendered useless, if your page height is changing after the CSS is popping in, you'll land on a random spot on the page if trying to navigate to a specific link with an anchor

**Comment by Erij-Maherzia-BEN-BRAHIM** [comment]
The flash of unstyled content is not related to V2, I had the same issue with V1 and I resolved the issue by wrapping my routes with a loading component when the page isn't hydrated.
Here is an example of a loading component 👇🏻 
```js
import { type ReactNode } from "react";
import { useHydrated } from "remix-utils";

export function Loading({ children }: { children: ReactNode }) {
  const isHydrated = useHydrated();

  if (isHydrated) {
    return (
        <div className="animate-appear">{children}</div>
    );
  }
  return (
<div>Loading...</div>
  );
}

```

**Comment by moishinetzer** [comment]
Wrapping all pages in a loading spinner is inherently anti-remix and should not be used as the default - or the solution.

To contrast where this is intended, take a look at the [docs for streaming](https://remix.run/docs/en/main/guides/streaming) in remix.

Are there any updates on this issue?

**Comment by martinmckenna** [comment]
@brophdawg11 most minimal example of just some content `flex-flow: row`ing after route client render. More details in the README:

https://github.com/martinmckenna/remix-bug

**Comment by ngbrown** [comment]
@martinmckenna I don't think this is a bug in Remix per se. It's just that you are, with React, swapping out (with JS) the CSS link at the same time as changing the page content. The content immediately updates, but the CSS hasn't been parsed and applied yet. If you disabled JavaScript, either from removing `<Scripts />` or in dev tools, you shouldn't get the flash as the browser is then doing full page loads. In a full page load, the browser waits till the `.css` is fetched and parsed before displaying the new page content.

Most of my CSS is universal (using Tailwind, but irrelevant to discussion) and applied consistently on every page from `root.tsx`, so it is always applied for any new elements. I do have a route that loads some extra CSS and especially with network cache off the flash is visible.

Instead of using a JavaScript based loader like mentioned, use the cascading feature of styles so something hides the page, or some section of the page, until the the new CSS loads and un-hides the same element.

```css
// root.css - always loaded from `root.tsx`
.body { visibility:hidden; }
```

```css
// app.css / about.css / etc. - load per page and ensure it is placed after `root.css` in the list of links.
.body { visibility:visible; }
```

I'm sure there's more targeted and subtle ways to do this, but I think this is fundamentally what is happening. You should be able to come up with a happy solution for your page.

Other ideas: Try to combine all the styles into a single stylesheet. Consider using a style system with atomic classes that outputs a single file for entire site.

What Remix could do: Maybe pre-loading `.css` of other routes is possible like it currently does with `.js` files. This would prevent the non-cached delay, but not completely eliminate the possibility of a flash when swapping style sheets.

**Comment by martinmckenna** [comment]
@ngbrown yep totally understand this. but the issue is remix boasts about it's route-based styles, and if they provide an objectively worse experience, then it's not really a usable feature.

FWIW, i did end up combining my stylesheets into one that gets loaded on first visit, and it solved the problem, but either remix needs to figure this issue out or stop recommending people use route-loaded styles.

**Comment by azuisleet** [comment]
This same sort of issue exists for developers who want to split [i18next](https://github.com/sergiodxa/remix-i18next) strings into separate namespaces. You have to follow the same convention here of either combining all the assets/strings or preloading nearby assets in anticipation of navigation to another route.

Ideally there would be a mechanism for routes to specify assets necessary for the first render (after the initial page load) like style sheets and translation strings.

**Comment by brophdawg11** [comment]
This is a bug in Remix.  It got introduced when we switched the internals of Remix to use React Router's `route.lazy` functionality, where lazily loaded routes are losing the prefetch step for route-driven styles on subsequent navigations to those routes.  I'll get a fix up for this shortly 👍

**Comment by sourcec0de** [comment]
Hello 👋 

We're experiencing a similar issue to OP on `2.1.0-pre.0`.
This appears to be caused by our global stylesheet rendering twice.
![CleanShot 2023-10-12 at 16 18 50](https://github.com/remix-run/remix/assets/1580651/a2955cda-2780-4557-951e-ebbe0dd47cc9)

Here's a video that demonstrates the issue.
https://www.dropbox.com/scl/fi/06syjou7kxiyuqdso000a/flash-of-unstyled-content.mp4?rlkey=qogk2sfyre655ars6ry06hntv&dl=0

**Comment by brophdawg11** [comment]
@sourcec0de I don't think you're reporting the same issue.  Your video shows a FOUC on initial page load.  OP's issue was a FOUC on client-side navigations to lazily loaded routes with CSS with caching disabled.  Can you open a new issue with a reproduction so we can look into your initial load FOUC?

**Comment by martinmckenna** [comment]
@sourcec0de i'm assuming this will go away if you revert back to `hydrate` instead of `hydrateRoot`. I had that issue and that's how i solved it.

but definitely worth a new remix issue either way

**Comment by tb-b** [comment]
I'm still experiencing the same as @sourcec0de on 2.1.0

**Comment by brophdawg11** [comment]
@tb-b Could you open a new issue with a reproduction?

**Comment by AmreeshTyagi** [comment]
This flash issue is still coming with remix 2.3.1 and react@18.2.0.

So, I switched to `"react": "^18.3.0-canary-593ecee66-20231114", "react-dom": "^18.3.0-canary-593ecee66-20231114",` and it is completely gone. Though I still see rehydration issue in console logs, but screen flash (cls-> cumulative-layout-shift) issue is gone.
 
It confirms that flash issue is related to React not with Remix. 
I just followed this hydration issue thread. https://github.com/remix-run/remix/issues/4822#issuecomment-1829970584

**Comment by adaboese** [comment]
Thanks @AmreeshTyagi . I ended up deploying `18.3.0-canary-593ecee66-20231114` as well, and it fixed my issue as well.

Do you know what else changed in React v18.3?

Before:

<img width="1008" alt="Screenshot 2023-12-23 at 8 09 59 PM" src="https://github.com/remix-run/remix/assets/149027443/d58c69c5-8d82-493d-97cf-5a8fa8177d57">

After:

<img width="1005" alt="Screenshot 2023-12-23 at 8 09 51 PM" src="https://github.com/remix-run/remix/assets/149027443/66e15422-f621-4c81-9b19-74015e5f103b">

**Comment by sourcec0de** [comment]
Upgrading to 18.3.0-canary-338dddc08-20240307 resolves the issue

**Comment by Kallyan01** [comment]
i am using remix cloudflare setup , noticed this issue on first visit when page is not cached .

**Comment by Kallyan01** [comment]
The issue is resoled , I found that FOUC was happening because of third-party extension (Grammarly) , removed it and now FOUC gone in initial load ,
But  i have noticed another FOUC on the `ErrorBoundary` in `root.tsx`

`
export function ErrorBoundary() {
  const error = useRouteError();
  console.error(error);
  return (
    <html>
      <head>
        <title>Oh no!</title>
        <Meta />
        <Links />
      </head>
      <body>
        <Error/>
        <Scripts />
      </body>
    </html>
  );
}
`

**Comment by deadcoder0904** [comment]
@Kallyan01 i also have grammarly installed. i don't see anything in incognito window where all extensions are disabled.

i'm wondering if this happens only on localhost or production applications face the same FOUC issue.

**Comment by nilansaha** [comment]
> I am also seeing a Flash for a millisecond without styles when I switched from plain Remix to Vite based setup.
> 
> I didn't see it before Vite switch. Not using any canary versions.

Did you manage to fix it?

**Comment by deadcoder0904** [comment]
@nilansaha Nope I think. It works well incognito. I think it was a development only error.

**Comment by ChayceJRoss** [comment]
Had the same issue. Problem for me was <Link/> with 404 response, fixed when I fixed the url. I think the broken link was causing a hydration error (similar to what has been described in quoted reply). A little bit new to Remix, maybe there is some sort of error handling I should have included. 

> @martinmckenna I don't think this is a bug in Remix per se. It's just that you are, with React, swapping out (with JS) the CSS link at the same time as changing the page content. The content immediately updates, but the CSS hasn't been parsed and applied yet. If you disabled JavaScript, either from removing `<Scripts />` or in dev tools, you shouldn't get the flash as the browser is then doing full page loads. In a full page load, the browser waits till the `.css` is fetched and parsed before displaying the new page content.
> 
> Most of my CSS is universal (using Tailwind, but irrelevant to discussion) and applied consistently on every page from `root.tsx`, so it is always applied for any new elements. I do have a route that loads some extra CSS and especially with network cache off the flash is visible.
> 
> Instead of using a JavaScript based loader like mentioned, use the cascading feature of styles so something hides the page, or some section of the page, until the the new CSS loads and un-hides the same element.
> 
> ```css
> // root.css - always loaded from `root.tsx`
> .body { visibility:hidden; }
> ```
> 
> ```css
> // index.css / about.css / etc. - load per page and ensure it is placed after `root.css` in the list of links.
> .body { visibility:visible; }
> ```
> 
> I'm sure there are more targeted and subtle ways to do this, but I think this is fundamentally what is happening. You should be able to come up with a happy solution for your page.
> 
> Other ideas: Try to combine all the styles into a single stylesheet. Consider using a style system with atomic classes that outputs a single file for entire site.
> 
> What Remix could do: Maybe pre-loading `.css` of other routes is possible like it currently does with `.js` files. This would prevent the non-cached delay, but not completely eliminate the possibility of a flash when swapping style sheets.
