### ISSUE TITLE
UIMatch still has issues

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/remix#7518]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAzgNQIYBtgBMCiWApiEQHbwC+cAZlBCHAERREYDGMTA3AFCiRYiOAFcURALIYY7ABZEUAGjgBVAJJSZsuNToNmAAVYhgADwC0UEWQD0rDlz68a1zsAhlkKTXIDqwGFkAZWAAczIiXDUyCXIRAApeODgbGzg1OAB3DAo4GAhRcVUNaTk8gE8wIjh5VmUAIxF4dhyAchgkuBBS2QAuOAAlIhgRKDIAFUqiAB4YKYgaQskehQA+AG0yERB6oigAXUVeAEp+7q0vYp9ZaesAazIITLJlJBQwiKiYuP6hhwA6P6cQgkchUVaITrARbxOZVBZdHr-WQ5XDEOAAQgAvFjmBB6gArIicJhwAA+ZMRWmRqPRONxWywWGOkOSyVYIzGtGw4j4yUovChMIx8SY73CkWisS2pOAnnOchpZDRRGOLIQnXZw1GnhoPKIfJ0guS0Lg8QxqEwOAIxFIFHiCtkSpV-3FnylcTVrLZHJ13KwvM6As6vq5MCsBt4wZcZDcHjg+FMGHAxHi6s67A8KHgjoUcFxYmWWgUacNqTyslQNQwKDgGAqVTge3oUCy8k8YjloQr1XU1wbRAzWfgbsl3y2tdxuZQ-xowCwMD28VQ138gRCEq+0pExycWs5nkZWD4AqAA

### Expected Behavior

be able to use `UIMatch` from `@remix-run/react`

### Actual Behavior

can't use `UIMatch` from `@remix-run/react` due to some type overlap issues

**Comment by lensbart** [comment]
Same as mentioned [here](https://github.com/remix-run/remix/pull/7464#issuecomment-1730440329)

**Comment by ngbrown** [comment]
I will say that having different `UIMatch` exported from two different packages is confusing.

I have to use `import type { UIMatch as UIMatchRR } from "@remix-run/router";` on functions that dealing with the return from `useMatches()`.

I then use `import type { UIMatch } from "@remix-run/react";` in the actual routes so I can get the `UIMatch<typeof loader>` functionality.

I have a file that imports both, thus the `as` in the import.  I think it would be better to have two different type names from the beginning, or just make us do our own `SerializeFrom<typeof loader>`.

**Comment by brophdawg11** [comment]
> I will say that having different UIMatch exported from two different packages is confusing.

This is a requirement because `UIMatch.data` is serialized over the network in Remix, but not in RR - so we need the types to reflect that.

**Comment by brophdawg11** [comment]
@lensbart Thanks for the repro - this looks like a quick fix - we are accidentally [exporting](https://github.com/remix-run/remix/blob/main/packages/remix-react/index.tsx#L40) the RR version of `useMatches` from `@remix-run/react` instead of the [Remix wrapper](https://github.com/remix-run/remix/blob/main/packages/remix-react/components.tsx#L9910).  I'll get a PR up to fix this 👍

**Comment by brophdawg11** [comment]
This is resolved by #7551 and will be available in the next release
