### ISSUE TITLE
[Bug]: Can't start the remix server after stopping it

### ISSUE THREAD

**Issue by judicaelandria** [remix-run/remix#752]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

Start a remix server, working on the code, then stopping the server using ctrl +c and then starting it again

I'm using ubuntu 20.04 with nodejs 14.17 and yarn 1.22.15

### Expected Behavior

It should restart the server again

### Actual Behavior

![err remix](https://user-images.githubusercontent.com/46365844/143772266-3225b2a6-95b7-4b70-99d5-6cd6f5f17d33.png)

**Comment by dggsax** [comment]
Hi @judicaelandria I just opened a similar issue in #762. Could you take a glance at it and see if the repro-steps I've provided are similar with your current project (e.g. have you set up Prisma with your project)?

**Comment by SalTor** [comment]
For those using a unix based operating system (mac / linux) can do `lsof -i :8002` (change to any port being listed as being used, this will show you the process id that you can kill with `kill <put PID here>`

If the relevant process isn't being killed that's the larger issue here, but this will get you set in the right direction for re-starting the server

**Comment by judicaelandria** [comment]
> 

yes!this is the same problem

**Comment by judicaelandria** [comment]
> Hi @judicaelandria I just opened a similar issue in #762. Could you take a glance at it and see if the repro-steps I've provided are similar with your current project (e.g. have you set up Prisma with your project)?

Yes! this is the same problem

**Comment by sairaj2119** [comment]
You cal also kill the process on the port by `npx kill-port <port_number>` here you can do `npx kill-port 8002`

**Comment by judicaelandria** [comment]
yes, but still, need to fix this

**Comment by yesmeck** [comment]
I've submitted a [PR](https://github.com/remix-run/remix/pull/905) to fix this issue. A temperature workaround is adding the following code right after the Prisma client is initialized.

```js
db.$on('beforeExit', () => {
  process.exit(0);
});
```

**Comment by judicaelandria** [comment]
> I've submitted a [PR](https://github.com/remix-run/remix/pull/905) to fix this issue. A temporary workaround is adding the following code right after the Prisma client is initialized.
> 
> ```js
> db.$on('beforeExit', () => {
>   process.exit(0);
> });
> ```

we didn't use prisma FYI, it was just remix
