### ISSUE TITLE
Cannot set multiple cookies with express server

### ISSUE THREAD

**Issue by alisd23** [remix-run/remix#7527]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Reproduction here (branch: `multiple-cookie-headers`):
https://github.com/alisd23/remix-issues/tree/issue/multiple-cookie-headers

1. `npm install`
2. `npm run dev` to run with a custom express server
3. Open site (localhost:3000)
4. Click submit button and watch request *cookies* tab in dev tools.

### Expected Behaviour

The request caused by the form submit should cause *two* `Set-Cookie` response headers, as returned by the action, with different cookie names.

### Actual Behaviour

The cookie header values are not parsed correctly and are instead merged into one `Set-Cookie` response header, which the browser cannot understand, and therefore reads it incorrectly as one cookie value.

I think #7067 is related, but the issue didn't directly mention this, so I thought it was better in a separate issue w/ reproduction.

**Comment by alisd23** [comment]
And if this is already a known issue, does anyone know a workaround in the meantime?

**Comment by alisd23** [comment]
Ok so now I understand there's a `Headers` polyfill being loaded from `@remix-run/web-fetch` which makes sense.

So this is being loaded correctly when running with `remix-serve`, but the internal node (off-spec) implementation (undici?) is being used with the custom server.

After looking a bit close I can also see this exact thing mentioned in #7067, but not sure if the intermittent polyfill is expected behaviour or a bug.

**Comment by kiliman** [comment]
This is working correctly in Remix v2. I see that your example was still using v1.7.5.

<img width="1365" alt="image" src="https://github.com/remix-run/remix/assets/47168/b0992aa1-d5e1-4933-bce0-ee0713a2534f">

**Comment by alisd23** [comment]
Hi @kiliman, strange... I just checked my local node_modules for this reproduction and they're all using `2.0.1` and I'm still getting this issue.

<img width="532" alt="image" src="https://github.com/remix-run/remix/assets/5804010/0334474b-431f-461a-a35a-162f753d00b4">

Did you run the `npm run dev` task? That's the one with the custom server (i.e. not using remix-serve) - screenshot below with my results.

<img width="1792" alt="image" src="https://github.com/remix-run/remix/assets/5804010/cb94b2b2-6a9c-49c8-93cb-cd40dc8db004">

**Comment by kiliman** [comment]
Yes, and you can see the header `X-Powered-By: Express`
<img width="419" alt="image" src="https://github.com/remix-run/remix/assets/47168/33a7a296-fc73-40eb-bf64-f052bb59f787">

**Comment by alisd23** [comment]
What Node version are you running? I'm using `18.12.1`.

**Comment by kiliman** [comment]
It was version 20.6.1, but I set it to v18. I added it as a header.
<img width="375" alt="image" src="https://github.com/remix-run/remix/assets/47168/f48a504b-e190-4fb3-843e-4bbbcd36b8ff">

**Comment by alisd23** [comment]
Ok interesting. Upgrading to `18.17.1` fixed the issue so there must have been a change/fix to the `Headers` implementation in between those versions.

I mentioned earlier that it looks like a different global `Headers` implementations is loaded when using `remix-serve` (the `@remix-run/web-fetch` implementation) compared to a custom express server (default node implementation).

Is this expected behaviour or a bug?

**Comment by kiliman** [comment]
I'm not sure. I know that starting in v2 you must manually call `installGlobals()` if you're using a custom node server.

**Comment by alisd23** [comment]
Ahh, you're right I missed that from the migration notes. Missing that is definitely the cause of the issue in earlier versions of node 18.

I think as a minor docs change it would be good to add that info [here in the docs]https://remix.run/docs/en/main/other-api/dev#with-custom-app-server), not just in migration notes, for new users who otherwise would not see that.

Otherwise I think we can call that closed - thanks for the help 👍
