### ISSUE TITLE
import_node3.Headers is not a constructor

### ISSUE THREAD

**Issue by dani-mp** [remix-run/remix#7533]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I just upgraded Remix to v2 and I'm getting this error at runtime:
```
ERROR    Invoke Error     {
    "errorType": "TypeError",
    "errorMessage": "import_node3.Headers is not a constructor",
    "stack": [
        "TypeError: import_node3.Headers is not a constructor",
        "    at convertApigRequestToNode (/var/task/build/server.cjs:1112109:19)",
        "    at /var/task/build/server.cjs:1112156:21",
        ...
    ]
}
```
I'm using `@remix-run/serve` and `serverModuleFormat: "cjs"`.

I deployed my Remix site to AWS using SST.

### Expected Behavior

The server doesn't crash.

### Actual Behavior

The server crashes.

**Comment by brophdawg11** [comment]
Could you provide a minimal reproduction?

**Comment by dani-mp** [comment]
To fix this, I had to add `nodejs: { format: 'cjs' }` to my `RemixSite` construct in sst. This wasn't needed before.

My `remix.config.js` also included `serverModuleFormat: "cjs"`, given that the default now is `esm`.
