### ISSUE TITLE
Setting vercel maxDuration causes 404

### ISSUE THREAD

**Issue by Klingefjord** [remix-run/remix#7537]
### What version of Remix are you using?

v2.0 (confirmed it is the case on v1.9.0 as well)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
export const config = {
  maxDuration: 300,
}

export default async function loader() {
  return json({ message: "Hello world!" })
}
```

Deploy the following code on Vercel leads to a 404. Remove the `export const config = ...` and the loader works

### Expected Behavior

https://vercel.com/docs/functions/serverless-functions/runtimes

Setting ```export const config = {
  maxDuration: 300,
}``` leads to a 300s timeout on the route.

### Actual Behavior

The route returns a 404.

This is might be a Vercel bug but posting here as well.

**Comment by brophdawg11** [comment]
I do think this something Vercel would need to address.  Remix doesn't own the Vercel adapter any longer, nor does our compiler know anything about an exported `config` from a route.  Did you file a Vercel issue you could cross-link here?

**Comment by Klingefjord** [comment]
> I do think this something Vercel would need to address. Remix doesn't own the Vercel adapter any longer, nor does our compiler know anything about an exported `config` from a route. Did you file a Vercel issue you could cross-link here?

Yes, https://github.com/vercel/vercel/issues/10590

It seems like someone else replicated the bug on Next.js so probably not a remix issue. Closing this.

**Comment by smartraysam** [comment]
I am using remix framework
i have my serverless function in app/routes/api.chat.js "

am getting error
The pattern "app/routes/api.chat.tsx" defined in functions doesn't match any Serverless Functions inside the api directory.

I equally try setting this 
```
export const config = {
  maxDuration: 300,
}
```
in the api route but deployment was fail..

if i set it in app route  (root.tsx) deploy works but not sure if the maxDuration set in root.tsx will reflect on my api routes

**Comment by joshpachner** [comment]
Does following the instructions here not work?
https://vercel.com/docs/functions/configuring-functions/duration

especially regarding creating the vercel.json file?
