### ISSUE TITLE
Need to configure LiveReload protocol and remix dev origin independantly.

### ISSUE THREAD

**Issue by cairin** [remix-run/remix#7540]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

We run our dev server in a docker container using [tilt](https://tilt.dev/). This is to emulate our production environment locally, and because we need to run other services that remix talks to.

To achieve this we copy changed files into our docker file which triggers the dev server to reload.

Remix and the dev server are run from within the cluster, and we configure the dns at our gateway. So the browser always communicates with `https://myhost` which gets routed internally within the cluster to remix etc. Remix can then communicate with the dev server on localhost (within the cluster).

The problem is that with v2, the websocket that updates the browser from the dev server complains about mixed content (ws not wss), and the only way to fix this is to specify `REMIX_DEV_ORIGIN=https://myhost`. However, this inadvertently breaks our build system because `https://myhost` doesn't exist within the cluster - so the dev server can't ping the app server. This seems to be because the [hot reload protocol is being inferred pased on `REMIX_DEV_ORIGIN`](https://github.com/remix-run/remix/discussions/7475#discussioncomment-7038542).

To solve this we are currently patching `./node_modules/.pnpm/@remix-run+server-runtime@2.0.1/node_modules/@remix-run/server-runtime/dist/dev.js` with the follwing:

```js
/**
 * @remix-run/server-runtime v1.19.3
 *
 * Copyright (c) Remix Software Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

async function broadcastDevReady(build, origin) {
    let url = new URL("http://0.0.0.0:8002");
    url.pathname = "ping";
    let response = await fetch(url.href, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            buildHash: build.assets.version
        })
    }).catch(error => {
        console.error(`Could not reach Remix dev server at ${url}`);
        throw error;
    });
    if (!response.ok) {
        console.error(`Could not reach Remix dev server at ${url} (${response.status})`);
        throw Error(await response.text());
    }
}
function logDevReady(build) {
    console.log(`[REMIX DEV] ${build.assets.version} ready`);
}

exports.broadcastDevReady = broadcastDevReady;
exports.logDevReady = logDevReady;
```

This basically just hardcodes the dev origin to `http://0.0.0.0:8002` within `broadcastDevReady`. 

### Expected Behavior

Allow specifiying protocol for `<LiveReload />`  independantly of `REMIX_DEV_ORIGIN`. Or allow specifying independant origins for dev and app servers.

### Actual Behavior

No hdr/hmr.

**Comment by kiliman** [comment]
I think it would be helpful if we could simply pass the URL to the `LiveReload` component directly (use REMIX_DEV_ORIGIN as default).

BTW: Instead of patching server-runtime, you can simply copy the source for the `LiveReload` component and inline it your app. It's in `remix-react/components.tsx`

**Comment by cairin** [comment]
> I think it would be helpful if we could simply pass the URL to the LiveReload component directly (use REMIX_DEV_ORIGIN as default).

Yeah that sounds reasonable :+1: 

> BTW: Instead of patching server-runtime, you can simply copy the source for the LiveReload component and inline it your app. It's in remix-react/components.tsx

Thanks that works nicely.
