### ISSUE TITLE
templates/express always loads initial build

### ISSUE THREAD

**Issue by nullday0** [remix-run/remix#7542]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`npx create-remix --template remix-run/remix/templates/express`

### Expected Behavior

When I change any file, HMR works correctly and page reloads with new build.
But if I refresh the page (F5) then it will show me the initial build.

### Actual Behavior

It should show the latest build every time I refresh the page.

**Comment by nullday0** [comment]
I was going through the source code here - https://github.com/remix-run/remix/blob/main/templates/express/server.js#L80
And I saw this piece of code:
```
async function createDevRequestHandler(initialBuild) {
  let build = initialBuild;
...
```
The thing is that express will call createDevRequestHandler() on every new request, so it will reset build variable to initialBuild every time.

I changed that behaviour, so I made
```
const initialBuild = await reimportServer();
let currentBuild = initialBuild
```
and then 
```
async function handleServerUpdate() {
    // 1. re-import the server build
    currentBuild = await reimportServer();
    // 2. tell Remix that this app server is now up-to-date and ready
    broadcastDevReady(currentBuild);
  }
```
and also changed `build` to `currentBuild` in other places, and now it works as expected.

I'm not sure how it was supposed to work with current code in the repo. Please let me know what I am missing here.

**Comment by ngbrown** [comment]
I can confirm this issue. It also prevents updated actions from using the new version. It was a mistake in the template to call `createDevRequestHandler` repeatedly, it should just be called once. To that end, I opened a pull request at #7544.

**Comment by danielweinmann** [comment]
I can confirm that @ngbrown's solution on #7544 works. Thanks, @ngbrown 🚀
