### ISSUE TITLE
Possible MetaFunction bug

### ISSUE THREAD

**Issue by ErlendS** [remix-run/remix#7584]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### The problem: 
When passing the meta function an array for it to return, and one of the objects in the array has the property: "tagName: 'link'", it  causes an hydration error. 

### Steps to Reproduce
I tried creating a fork with a test to produce the bug: https://github.com/ErlendS/remix-possible-metafunction-bug/blob/main/integration/bug-report-test.ts

But the test passes...

However, when I created (what I believe to be) the exact same setup in stackblitz, the error appears: 
https://stackblitz.com/edit/remix-run-remix-rvjcj7?file=app%2Froutes%2F_index.tsx

**How to see the error:** 
- Open the stackbliz [link](https://stackblitz.com/edit/remix-run-remix-rvjcj7?file=app%2Froutes%2F_index.tsx).
- Click "Open in New Tab" in the top-right corner
- Check the console.

It should give out a warning like : `Warning: Expected server HTML to contain a matching <meta> in <head>.`

If you then go to the 'Network' tab and view the response from the document being returned by Remix, the `<head>` should contain `<link rel="icon" href="https://remix.run/favicon-32.png" type="image/png"/>`.

Continue to the 'Elements' tab and check the `<head>` in the document and you will see it is incorrectly rendering: `<meta rel="icon" href="https://remix.run/favicon-32.png" type="image/png">`

The server and client have mismatching tags.

------------- 
### Additional info:
I hope you don't mind, but since its not much code I thought I could add the code here to make it easier to view : 
```tsx
import { type MetaFunction, json } from "@remix-run/node";

export const meta: MetaFunction<typeof loader> = (loader) => {
  // ❌ this causes hydration error.
  const metaArray = loader.data?.metaArray
  if (metaArray) {
    return metaArray;
  }
  
  // The problem looks to be the objects in the array being mutated,
  // if we copy the objects in the array it works.
  // const copy = metaArray?.map((obj) => Object.assign({}, obj));
  // return copy

  return []
};

export async function loader() {

  // contrived example, but say you're on a $slug route and you need to do some checks to get the 'href' for the favIcon.
  const metaArray = [
    {
      tagName: 'link',
      rel: 'icon',
      href: 'https://remix.run/favicon-32.png',
      type: 'image/png',
    },
  ];

  return json({ metaArray });
}

export default function Index() {
  return (
    <div>
      <h1>Welcome to Remix</h1>
    </div>
  );
}

```

Looking a bit in the Remix code, I _think_ this might be the issue: https://github.com/remix-run/remix/blob/a20ae7fb0727212ac52bdc687513c61851ac4014/packages/remix-react/components.tsx#L516 

it could be when "tagName" is deleted, the reference object is mutated, therefore when the meta function runs again on the client it assigns the object as a meta tag. 

And _if_ this is the cause, it could possibly be fixed a few lines above: https://github.com/remix-run/remix/blob/a20ae7fb0727212ac52bdc687513c61851ac4014/packages/remix-react/components.tsx#L509C25-L509C34
by cloning the object so it doesn't point to the same object in memory.

### Expected Behavior

When the meta function receives the array it should return as a prop, and one of the objects in the array has the property: "tagName: 'link'", we should not get a hydration error. It should render a `<link>` tag on the server and on the client.

### Actual Behavior

The Meta component returns a `<link> tag on the server and <meta> on the client.`

**Comment by sergiodxa** [comment]
Are you using React canary?

**Comment by ErlendS** [comment]
No. The stackblitz example is using react 18.2.0

**Comment by brophdawg11** [comment]
I think you're correct in that the mutation is causing the issue, so subsequent renders don't pick up on tagName.  I think we can just change it to just destructure off the `tagName` separate from the rest of the props:

```jsx
if ("tagName" in metaProps) {
  let { tagName, ...rest } = metaProps;
  if (!isValidMetaTag(tagName)) {
    console.warn(
      `A meta object uses an invalid tagName: ${tagName}. Expected either 'link' or 'meta'`
    );
    return null;
  }
  let Comp = tagName;
  return <Comp key={JSON.stringify(rest)} {...rest} />;
}
```

I'll try to get a fix in for this soon 👍

**Comment by charklewis** [comment]
Thanks for looking into this @brophdawg11 and @ErlendS, I am having this issue too.
