### ISSUE TITLE
Tailwind classes missing WebKit extensions

### ISSUE THREAD

**Issue by pbudner** [remix-run/remix#7589]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Using the default Tailwind integration and just adding a Tailwind class that makes use of WebKit extensions (e.g., backdrop-blur).

### Expected Behavior

WebKit extension styles are added to the backdrop class resulting in a blurred div.

See expected behavior in the following Tailwind Playground: https://play.tailwindcss.com/Wv7yVxvejd

### Actual Behavior

WebKit extension styles are missing for backdrop class resulting in a non-blurred div.

See following CodeSandbox and compare Chrome and Safari (or use Web Inspector to see that -webkit-extensions are missing): https://codesandbox.io/p/sandbox/stupefied-dream-txcz99

**Comment by bluefire2121** [comment]
Follow the Tailwind documentation. Use autoprefixer. 

https://tailwindcss.com/docs/installation/using-postcss

**Comment by pbudner** [comment]
Thanks a lot! That helped fix my issue.

I tried it before using PostCSS and autoprefixer. However, it seems I had a wrong postcss.config.js in place: Using cjs, of course, you do not `default export` your postcss config but `module.exports` it.
