### ISSUE TITLE
handleError is not awaited (?) so it can't async transmit the error somewhere (sentry, webhook, ...)

### ISSUE THREAD

**Issue by xdivby0** [remix-run/remix#7606]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a Cloudflare pages project and call a webhook inside the `handleError` function (maybe even put a 1s delay to increase the odds of witnessing this issue).

Make sure to throw an un-caught error somewhere in a loader or action - you'll see that most of the time the webhook will not be triggered.

### Expected Behavior

The `handleError` function should be executed fully before terminating the process. To my knowledge, on cloudflare workers/pages this is the equivalent of executing the `handleError` fully before closing the response stream (it supports streaming) to the user request.a

### Actual Behavior

On Cloudflare pages, the isolate gets terminated without waiting for `handleError` to report to sentry or whatever network request you do inside there. This is an even bigger problem than non-cloudflare pages people think because on that serverless platform we don't have any other way of accessing logs. 

I am pretty sure the isolate terminates as soon as possible after having answered the user request since this is what the cloudflare workers were originally created for. Backend tasks that fill and extend over the request duration were not in mind. 

I also understand all the other platforms wouldn't want to await `handleError` - after all what the user should see doesn't depend on the sentry response or success/failure of the `handleError` in general.

If possible in any way, I'd be open to help to create a flag to implement the waiting as an opt-in option.

**Comment by BrandonNoad** [comment]
@xdivby0 this issue can be solved using `waitUntil`

https://developers.cloudflare.com/workers/runtime-apis/handlers/fetch/#contextwaituntil

In your `server.ts`, you can add `waitUntil` to your `AppLoadContext` using `getLoadContext`. Then `waitUntil` is available in `handleError`, and you can wrap your async operation with it.

**Comment by xdivby0** [comment]
That seems to work. Thank you @BrandonNoad
