### ISSUE TITLE
[Bug]: input events aren't working

### ISSUE THREAD

**Issue by matiasleidemer** [remix-run/remix#761]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.5

### Steps to Reproduce

Add an `onChange` prop to an input:

```jsx
<input type="text" onChange={(e) => console.log(e)} />
```

### Expected Behavior

I should see an event log in my browser's console.

### Actual Behavior

Nothing happened. I've tried other events and none seemed to work. First I thought I was doing something wrong, but the same code works in a regular `create-react-app`. 

Am I missing something, did I forget to include some JS or is this expected behavior? If so, how can I catch input events?

**Comment by matiasleidemer** [comment]
I was following https://github.com/remix-run/remix-jokes, and I've removed the `<Scripts />` tag from the root file. Adding it back fixed the issue.

**Comment by kentcdodds** [comment]
Looks like you found my mic drop moment early 😆

It may be a good idea for me to mention that earlier. As fun as it is to blow people's minds with how far they can go without even hydrating on the client, it does lead to a bit of a surprise for people trying more than what's in the tutorial 😅

**Comment by matiasleidemer** [comment]
Yeah, that might be a good idea indeed. TBH I wasn't sure what the `<Script />` was all about, but I guess I learned the hard way. Thank you for taking the time to reply 😄
