### ISSUE TITLE
🗺️ Client Data

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#7635]
- RFC: #7634
- Old PR: #5543

**Comment by brophdawg11** [comment]
This work is being done across a few PRs in a `feature/client-data` branch:

* Deprecate `DataFunctionArgs` - https://github.com/remix-run/remix/pull/8089

**Comment by brophdawg11** [comment]
This work also depends on this React Router PR: https://github.com/remix-run/react-router/pull/11033

**Comment by brophdawg11** [comment]
The above Remix PRs are merged to the feature branch, and the final PR is open in a draft state:

https://github.com/remix-run/remix/pull/8173

**Comment by brophdawg11** [comment]
Two more related PRs: 
* https://github.com/remix-run/remix/pull/8229
* https://github.com/remix-run/remix/pull/8236
