### ISSUE TITLE
Unexplained positions Object in Session Storage

### ISSUE THREAD

**Issue by Mischter-X** [remix-run/remix#7659]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [x] Yes

### Steps to Reproduce

    1. Set up a new Remix project using the Express template and start the dev server.
    2. Refresh the localhost:3000 page.
    3. Observe the positions object created in the Session Storage.

### Expected Behavior

No positions object should be created in the Session Storage, especially since there is no active Remix Session Storage in my application.

### Actual Behavior

A random positions object gets created in the Session Storage with peculiar values like:

{
  "vskh7l6cj0k":0,
  "0d1fd718q7":0,
  // ...and so on
}

Upon refreshing the page, either a new entry is added to the positions object or a single entry is created. This behavior is consistent across both Firefox and Chrome browsers.

Thank you in advance!

**Comment by brophdawg11** [comment]
This is created by the [`<ScrollRestoration>`](https://remix.run/docs/en/main/components/scroll-restoration) component and is used to ensure scroll positions persist across page reloads.  If you remove this component from `root.tsx`, the object will no longer be created in `sessionStorage`.
