### ISSUE TITLE
Remix throws “Error: Cannot find module” when trying to import from another workspace in `pnpm turborepo`

### ISSUE THREAD

**Issue by mayank1513** [remix-run/remix#7664]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Check out this question - https://stackoverflow.com/questions/77253606/remix-throwing-stange-errors-when-used-in-turborepo

1. clone this branch - https://github.com/mayank1513/react18-themes/tree/remix
2. run `pnpm dev --fiter remix-example`
3. See the error

2nd route: 
1. Build the example
2. cd into examples/remix
4. start the server `yarn start`
5. See the error

### Expected Behavior

It should run the example and start dev/production server on localhost

### Actual Behavior

It fails with strange errors.

**Comment by jrestall** [comment]
Your `remix.config.js` file should have `serverDependenciesToBundle: ["react18-themes"]` rather than the invalid option of `transpileModules`. 

I also had to add ` "zustand": "^4.4.3" and "persist-and-sync": "^0.1.1"` as dependencies to the remix app as pnpm doesn't seem to copy them to the app's node_modules. Adding to the root package.json might work also.

**Comment by mayank1513** [comment]
Try nextjs example. It works just fine.

**Comment by jrestall** [comment]
> Try nextjs example. It works just fine.

Yes because NextJS has been correctly configured with its transpileModules configuration option, you need to do the same with Remix's equivalent serverDependenciesToBundle option.

**Comment by mayank1513** [comment]
`serverDependenciesToBundle` doesn't work for me. And for Next.js, `transpileModules` with an empty array works just fine.

**Comment by mayank1513** [comment]
Resolved
