### ISSUE TITLE
create-remix Cannot read properties of null (reading 'firstChild')

### ISSUE THREAD

**Issue by beilo** [remix-run/remix#7689]
### What version of Remix are you using?

^2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

npm i
npm run dev
This is my minimal demo.
[my-remix-app.zip](https://github.com/remix-run/remix/files/12926130/my-remix-app.zip)

### Expected Behavior

I hope the code can run correctly.

### Actual Behavior

I'm a novice.
I just started by creating a project using `npx create-remix@latest`.
After running `npm run dev`, I noticed the following errors in the console of Chrome.
```
react-dom.development.js:86 Warning: Did not expect server HTML to contain a <div> in <html>.
    at html
    at App
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-3PTPITXR.js:3753:5)
    
Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
```

Then, as I added the Button code from antd in `app/routes/_index.tsx`, I came across the following errors.
```
TypeError: Cannot read properties of null (reading 'firstChild')
    at injectCSS (http://localhost:3000/build/routes/_index-X2P6BDMY.js:944:30)
```
However, if I remove all `<a>` tags in `app/routes/_index.tsx`, all the error messages above disappear, and the program can run normally, as shown below.
```
export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <Button>1</Button>
      <h1>Welcome to Remix</h1>
      <ul>
        <li>
          {/* <a
            target="_blank"
            href="https://remix.run/tutorials/blog"
            rel="noreferrer"
          >
            15m Quickstart Blog Tutorial
          </a> */}
or
<Link to={`https://remix.run/tutorials/blog`} target="_blank">15m Quickstart Blog Tutorial</Link>
        </li>
       
      </ul>
    </div>
  );
}
```

I feel confused. Can you please clarify what specifically is confusing you?
thanks！
Translation from GPT

**Comment by brophdawg11** [comment]
I do not see any hydration errors when I run the app.  This is usually caused buy Chrome extensions modifying the DOM before hydration. Can you try loading your app in an Incognito window without extensions and see if that fixes it?

**Comment by beilo** [comment]
@brophdawg11 You are right, everything works fine when I use Chrome's incognito mode.
thanks！

**Comment by hriziya** [comment]
I am facing the same error but only when my domain is proxy through cloudflare network. if I turn off the proxy and clear cache, the issue is gone. so my guess is this has something to do with cloudflare or a specific settings. 
I don't know the solution yet and so I can't use cloudflare with remix sites.
If someone knows the solution, please let me know. thanks
