### ISSUE TITLE
`useLoaderData` incorrectly inferring all properties from loader as `any`

### ISSUE THREAD

**Issue by 0t4u** [remix-run/remix#7700]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

The following code should allow useLoaderData to infer the correct types, as stated in documentation, but does not.

```ts
export const loader: LoaderFunction = () => {
	return json({
		string: "hi :)",
		number: 1,
		array: [
			"some",
			"random",
			"items",
		],
}

export default function Page() {
	const { string, number, array } = useLoaderData<typeof loader>();
	...
}
```

### Expected Behavior

The destructured values should be the type of `string`, `number`, and `string[]` respectively.

### Actual Behavior

The destructured values have an incorrect type of `any`. A type of `any` is still inferred when not destructuring the object, and returning an object without wrapping with the `json()` function.

**Comment by pcattori** [comment]
Setting `LoaderFunction `type for `loader` tells TS to not infer the type for `loader` and just use `LoaderFunction`, which is a wide type that doesn't know about your return value. If you remove `LoaderFunction` then [TS will correctly infer the type](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbwFYGcIDsC+cBmUIhwBEAAlAKYjAAeAtFAK7oD06EAJuUQFCiSyIGKcgBkIAQ05QAIuJjjseAsTKUa9JswriAxjB7dy1fvB0YU8ADYSpcALxwAFAEp7APkTcAkBRgMo6HCoGI4I3l7iAFzEABbAcJHORAA04QBG0QCMqV5eOtEA2uFeRGggXDm5RFDi6OwEKcVEwDCUKI25ALqpcHCYztyY3IbG0PCcOOIMlvA4THrAGHAACuIA5uQunnnm43Li9nBCojbkMvsAPDAAnmDkEDhw1pJnbi4A3Ny9ZugWiHAHbAOdj7L5wZjMXpQuAAPQA-GCfn8EHA0n1DiD5GCIdDevDEbt-jp0cDQb0cbj8ZggA):

```ts
export const loader = () => {
  return json({
    a: "hi :)",
    b: 1,
    c: ["some", "random", "items"],
  })
}
```

If you want to make sure that your `loader` adheres to the `LoaderFunction` type _and_ you want type inference, you can use [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html):

```ts
export const loader = (() => {
  return json({
    a: "hi :)",
    b: 1,
    c: ["some", "random", "items"],
  })
}) satisfies LoaderFunction
```

**Comment by 0t4u** [comment]
Setting the LoaderFunction type in  still allowed type inference in v1, perhaps this may be a regression?

**Comment by pcattori** [comment]
Here's a [reproduction without any Remix code](https://tsplay.dev/w6QLEW) showing how defining a function type overrides inference for a more specific return value in TS:

```ts
type Loader = () => Record<string, number>

const loader1: Loader = () => {
	return {a: 1}
}

type Result1 = ReturnType<typeof loader1>
//   ^? { [x: string]: number }

const loader2 = () => {
	return {a: 1}
}

type Result2 = ReturnType<typeof loader2>
//   ^? { a: number }
```
