### ISSUE TITLE
Flash of styled elements on page reload

### ISSUE THREAD

**Issue by tb-b** [remix-run/remix#7701]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
// root.tsx
import styles from "~/styles/styles.css";

export const links: LinksFunction = () => [
	...(cssBundleHref ? [{ rel: "stylesheet", href: cssBundleHref }] : []),
	{ rel: "stylesheet", href: styles },
];
```

```
// Avatar.tsx
import "filepond/dist/filepond.min.css";
```

- I've tried moving the css from Avatar to root, still seeing the same behaviour. 

### Expected Behavior

wait for all styles to be loaded before showing the content

### Actual Behavior

temporary flashing of the content on page reload

Video: https://share.cleanshot.com/4cmBKy1v

**Comment by brophdawg11** [comment]
I think we need a bit more information to look into this.  Can you provide a reproduction repository or stackblitz so we can see the entirety of the application including configs/components/route files/etc?  

It's also unclear what steps you are taking in the video.  Are you doing a reload via the browser reload button (or F5)?  Clicking the button to trigger a reload?  Do you have dev tools open and/or `Disable Cache` checked?

I setup as close of reproduction as I could given your code above and I do not see a FOUC on initial load or reloads.  The only way I could trigger one was hitting reload, waiting for the document request to finish, and then hitting the X to cancel the subsequent JS/CSS downloads (but I suspect that's not what you are doing 😄 ).

<img width="624" alt="Screenshot 2023-10-18 at 1 29 27 PM" src="https://github.com/remix-run/remix/assets/1609022/9ea018a2-9dc3-46d5-94e1-eec134ceca9a">

**Comment by Erij-Maherzia-BEN-BRAHIM** [comment]
I think this can help you to fix this problem
https://github.com/Xiphe/remix-island

**Comment by brophdawg11** [comment]
Closing due to no response from OP - happy to re-open if a reproduction can be provided!
