### ISSUE TITLE
Incorrect docs re: root ErrorBoundary in starter templates

### ISSUE THREAD

**Issue by jrr** [remix-run/remix#7713]
### What version of Remix are you using?

2.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1.  Read the [Error Handling doc](https://remix.run/docs/en/main/guides/errors#root-error-boundary) section about the root error boundary:

> If you used one of the starter templates you should already have an [ErrorBoundary](https://remix.run/docs/en/main/route/error-boundary) in your app/root.tsx file.

2. Look at your template-produced project and see that it doesn't have one. Generate a new template to make sure you're not missing something:

```
pnpx create-remix@latest my-app --no-install --no-git-init
```

### Expected Behavior

I expect that there's an ErrorBoundary I can build on.

### Actual Behavior

..but there's not!

```
grep ErrorBoundary -R my-app
```

I think this is the file in question:
https://github.com/remix-run/remix/blob/remix%402.1.0/templates/remix/app/root.tsx

Are root error boundaries still a thing?

**Comment by brophdawg11** [comment]
Thanks for the heads up!  The docs are incorrect here.  Since we have a built-in global error boundary, adding one to `root.tsx` in the templates would just mean there are now 2 default error boundaries.  I updated the wording on the docs to fix the mistake - should show up in a few minutes once the caches clear.

**Comment by brophdawg11** [comment]
> Are root error boundaries still a thing?

Absolutely!  We just don't put one in the templates but you can (and should) add one for your app!
