### ISSUE TITLE
useSubmit POST to parent route doesn't navigate anymore

### ISSUE THREAD

**Issue by ecrvich** [remix-run/remix#7714]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Code snippets assume:
```
import {useSubmit} from "@remix-run/react";
let submitter = useSubmit();
```

From /testbuilds route if I do this:

`submitter(formData, { method: "post", action: "/testbuilds/actions/build/run" });`

That posts to my /testbuilds/actions/build/run.tsx action handler AND navigates the browser to /testbuilds/actions/build/run (and renders the JSX from that page). So far so good, working as before.

Now in /testbuilds/actions/build/run.tsx, after the user is done interacting with the UI (clicks a button or whatever), I do this:

`submitter(formData, { method: "post", action: "/testbuilds" });`

This triggers the action handler in /testbuilds, but does NOT navigate the browser back to /testbuilds...it remains on /testbuilds/actions/build/run. **_In 1.9.0, it does indeed navigate back_** (we have been using this implementation for a year in production on virtually all of our pages). 

### Expected Behavior

useSubmit is documented as a POST-and-navigate combo. And it indeed works that way in 1.9.0, both from parent-to-child and from child-to-parent.

### Actual Behavior

In 1.19.3, useSubmit in the child-to-parent direction now only posts, it no longer navigates.

**Comment by ecrvich** [comment]
I've stumbled across another new behavior in trying to find workarounds and debug etc., and that is: the **root** route's useActionData() is returning the **child** route's action data, even though the root's ActionFunction is NOT getting called. That didn't happen in 1.9.0, and it has made debugging this really confusing (since I share some action props across the app, like "actionName")...and so root no longer knows if the actionData is from an action performed on a child or itself. That change may be by design, though, so that will require some redesign on my end.

After removing some action handling from root, the submit back to the /testbuilds route seems to only fail in terms of what the browser displays in the address bar (in both Chrome and Firefox). The dev console shows that my code thinks it is back on /testbuilds even though the browser still displays the child route.

The good news is I finally found a workaround for that...but it makes no sense to me why it would fix the address bar issue:

`setTimeout(submitter.bind(null, { method: "post", action: "/testbuilds" }), 1);`

This posts and navigates AND the browser address bar shows /testbuilds correctly. Remove the setTimeout wrapper, and the address bar remains as /testbuilds/actions/build/run. Confused shrug.

**Comment by kiliman** [comment]
I think if you want some help with this, you'll need to create an example showing this issue. It's a little difficult trying to piece together code and route structure from your description.

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction?  This is working as expected for me in [1.19.3](https://stackblitz.com/edit/remix-run-remix-ychae8) and in [v2](https://stackblitz.com/edit/remix-run-remix-znqrsn).

**Comment by ecrvich** [comment]
The setTimeout kludge fixes the issue and doesn't impact usage/performance, so I no longer need help per se. If I get time someday to create a standalone app that shows this, I will, but for now we are in crisis mode to get the app into a stable, deployable state after the Remix updates...the combo of the useActionData() behavior change and this bug put us a week behind schedule. And then we're going to dive into upgrading React from 17 to 18, and then immediately into Remix v2 migration.

@brophdawg11 It may require two levels of child depth, not sure yet. This has required many days of trial-and-error to figure out what was going on, partly due to the new useActionData behavior, which was messing up what the UI displayed. But in our case we have /testbuilds calling /testbuilds/actions/build/run with useNavigate, then run.tsx uses useSubmit to post to /testbuilds/actions/build/run/submit, and finally submit.tsx does the useSubmit to post back to /testbuilds. It's the last useSubmit post that fails to change the browser URL. And the only reason I discovered the setTimeout fix was because I attempted to convert useSubmit to a combo of useNavigate plus a timed-out followup call to useSubmit (navigate to /testbuilds to try to fix the browser address bar issue, then post the data). That revealed that only setTimeout was needed, I didn't have to do the pre-navigate.

I'm totally ok if you'd prefer to just close this, though, since we are out of the frying pan thanks to setTimeout, and it may be a while before I can work on trying to reproduce in a small standalone app.

**Comment by ecrvich** [comment]
So the slightly unusual thing about submit.tsx is that it's "sort of" a resource route in that it really only exists to perform an ActionFunction. It has no LoaderFunction, but it does have a default function with just "<></>", but that never gets called because ActionFunction will ALWAYS throw Response objects. Its Catch/ErrorHandlers do the useSubmit calls back to /testbuilds...that's why I originally thought this was a CatchHandler bug.

Thinking maybe the address bar issue is because the action completes more quickly with 1.19.3, I added an awaiting-sleep for a full second in the ActionFunction, but that doesn't fix the problem. It's only if CatchHandler calls submitter as a setTimeout callback. The (simplified) handler **_without_** the setTimeout fix looks like this:

```
export function CatchBoundary() {
	const submitter = useSubmit();
	const caught = useCatch();
	useEffect(() => {
		submitter(
			{
				actionType: Constants.CHILD_COMPLETE,
				title: "Submit completed",
				subtitle: caught.statusText,
			},
			{ method: "post", action: "/testbuilds" });
	}, []);
	return (<></>);
}
```

So I suspect there is some "catch up" issue with the fact that by the time the browser thinks submit.tsx is the current page, Remix has **_already_** post-and-navigated back to /testbuilds. Adding the setTimeout wrapper, even for just 1ms, gives the browser time to see/render the "<></>" nothingness from CatchBoundary's return value, and then acknowledge the useSubmit nav.

Oddly 1.9.0 never showed this behavior though...1.19.3 is "too fast" for browsers now I guess, ha!

**Comment by kiliman** [comment]
If you're having to resort to a bunch of "hacks" to get around supposed issues in Remix, I would consider that perhaps you're not using Remix properly. When I started using Remix, I had to "unlearn" some things, especially concerning React state management.

I think you would be better served if you took the time to create a repro showing how you're using Remix and the problems that you are having. Once the root cause is determined, it will probably simplify your app and give you more confidence moving forward.

**Comment by ecrvich** [comment]
No idea where the "bunch of hacks" comment is coming from. We just have this one minor workaround for this weird new useSubmit behavior. We've been using Remix over a year and LOVE it. Our redesigned app is a dream compared to our old CodeIgniter/PHP app. We've never had to do anything resembling a workaround for Remix behavior until we upgraded from 1.9.0 to 1.19.3.

Regardless, I've devised a super simple example that shows the issue and will attach the files shortly.

**Comment by ecrvich** [comment]
I trimmed everything down to just an ultra-simple root.tsx with one child route link (reports.tsx), and two children of reports...one **_without_** the setTimeout fix (which causes the address bar to "stick" on /reports/run1), one with the setTimeout wrapper (which causes the address bar to correctly switch back to /reports). Behavior is consistent on both Chrome and Firefox.

[sample.zip](https://github.com/remix-run/remix/files/13061396/sample.zip)

**Comment by ecrvich** [comment]
Good news! I upgraded to React 18 today, and tried removing my setTimeout fix...voila! No more sticking on the child page! I was on the latest version of React 17 before. So this is apparently a React 17 bug, not a Remix bug. Totally fine with closing this since we are going to be using React 18 from now on, and no longer need the setTimeout workaround.

**Comment by brophdawg11** [comment]
OK glad you got it worked out!
