### ISSUE TITLE
Suspense and streaming not working

### ISSUE THREAD

**Issue by manzaloros** [remix-run/remix#7715]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
import { defer } from "@remix-run/node";
import type { LoaderFunction } from "@remix-run/node";
import { Await, useLoaderData } from "@remix-run/react";
import { Suspense } from "react";

export const loader: LoaderFunction = () => {
  return defer({
    foo: Promise.resolve("bar"),
  });
};
const Qux = () => {
  console.log("fallback invoked!");

  return <>Loading!</>;
};

export default function Index() {
  const { foo } = useLoaderData<typeof loader>();
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <Suspense fallback={<Qux />}>
        <Await resolve={foo}>
          {(foo) => {
            return <div>{foo} from loader</div>;
          }}
        </Await>
      </Suspense>
    </div>
  );
}

```

### Expected Behavior

A console log of `fallback invoked!` should log while the awaited Promise is resolving.

### Actual Behavior

There is no console.log but the `bar` from the loader is returned correctly.

**Comment by cliffordfajardo** [comment]
I'm also having issues with defer, where its not rendering the `fallback` suspense component
Remix express template on Remix 2.1.0


Reproduction repo:
https://github.com/cliffordfajardo/remix-v2_1_0_express__template_big

routes/_index.tsx
```tsx
import { LoaderFunctionArgs, defer } from "@remix-run/node";
import { Await, useLoaderData } from "@remix-run/react";
import { Suspense } from "react";

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getUser = async () => {
  await sleep(4000)
  console.log('called getUser!')
  return "freddy"
}

export async function loader({ }: LoaderFunctionArgs) {
  return defer({
    foo: getUser,
  });
};


export default function Index() {
  const { foo } = useLoaderData<typeof loader>();

  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <Suspense fallback={<p>Fallback .....</p>}>
        <Await resolve={foo}>
          {(foo) => (
            <div>{foo} from loader</div>
          )}
        </Await>
      </Suspense>
    </div>
  );
}
```

**Comment by brophdawg11** [comment]
@manzaloros Already-resolved promises won't go into a fallback state, if you make the defer promise async it will render the fallback: 

```ts
export const loader: LoaderFunction = () => {
  return defer({
    foo: new Promise((r) => setTimeout(() => r("bar"), 1000)),
  });
};
```

@cliffordfajardo I think the issue in your repro is you aren't invoking `getUser` so it's handing a `function`, not a `Promise` to `defer()`

**Comment by cliffordfajardo** [comment]
O dear LOL - forgot to invoke it. LONG day ahaha. Thanks @brophdawg11

**Comment by cliffordfajardo** [comment]
Ok so @manzaloros and I were looking into this more and it looks like `fallback` prop does work when you inline something simple to it `<Suspense fallback={<p>loading...</p>}>`, 

but for some reason its not working when we pass it a [<Skeleton />](https://ant.design/components/skeleton) component from ant design library; we'll look into that; just updating this thread as we work through a solution and in case someone stumble upons this later

Issue doesnt need to be re-opened IMO

**Comment by mstapp** [comment]
This is still not working in v2.3.1 (`fallback` with simple inline HTML works, but not with a component). Should this issue get re-opened to reflect its status?

**Comment by brophdawg11** [comment]
It sounds like an issue with the specific component from ant design library.  Suspense works fine with a normal component: `<Suspense fallback={<Loading/>}>`
