### ISSUE TITLE
Express template throws ERR_FEATURE_UNAVAILABLE_ON_PLATFORM in dev mode

### ISSUE THREAD

**Issue by Leejjon** [remix-run/remix#7726]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On Ubuntu 22.04.3 LTS
With Node.js v18.14.1

I run: `npx create-remix@latest --template remix-run/remix/templates/express`
Then I try to run dev mode with: `npm run dev`

The following happens:
```
leejjon@leejjon-XPS-13-7390:~/projects/my-remix-app$ npm run dev

> dev
> remix dev --manual -c "node --watch-path server.js --watch server.js"


 💿  remix dev

 info  building...
 info  built (729ms)
node:fs:2313
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:399:5)
    at watch (node:fs:2313:11)
    at FilesWatcher.watchPath (node:internal/watch_mode/files_watcher:92:21)
    at node:internal/main/watch_mode:43:53
    at Array.forEach (<anonymous>)
    at node:internal/main/watch_mode:43:1 {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}

Node.js v18.14.1
```

I did google the error and found this:
https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform

But those answers tell me to use something newer than Node.js 14, which I already do.

I did upload the code generated by the template here:
https://github.com/Leejjon/my-remix-run

### Expected Behavior

To start devmode up just fine.

### Actual Behavior

```
node:fs:2313
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:399:5)
    at watch (node:fs:2313:11)
    at FilesWatcher.watchPath (node:internal/watch_mode/files_watcher:92:21)
    at node:internal/main/watch_mode:43:53
    at Array.forEach (<anonymous>)
    at node:internal/main/watch_mode:43:1 {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}
```

**Comment by brophdawg11** [comment]
Hm, this might be an ubuntu issue?  Node 18.14.1 worked for me on Mac OSX using your above steps:

```sh
~/playgrounds> n 18.14.1
  installing : node-v18.14.1
       mkdir : /Users/matt/n/n/versions/node/18.14.1
       fetch : https://nodejs.org/dist/v18.14.1/node-v18.14.1-darwin-arm64.tar.xz
     copying : node/18.14.1
   installed : v18.14.1 (with npm 9.3.1)
~/playgrounds> npx create-remix@latest --template remix-run/remix/templates/express temp
...
~/playgrounds> cd temp
~/playgrounds/temp> npm run dev

> dev
> remix dev --manual -c "node --watch-path server.js --watch server.js"


 💿  remix dev

 info  building...
 info  built (284ms)
(node:4180) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

And I could load http://localhost:3000 without issue

**Comment by Leejjon** [comment]
It's a Linux thing yes. According to the stackoverflow link I put in my post.

**Comment by brophdawg11** [comment]
I don't know if there's anything for Remix to "fix" here?  These are built-in node APIs which work for the vast majority of setups.  Have you tried using `nodemon` or `node-watch` to handle server restarts on Linux, and avoid the problematic node API?

**Comment by Leejjon** [comment]
I'm not too experienced with those. If remix wants to fix this or not depends on if the express template was meant to work cross platform. I guess I'll start trying these kind of options.

**Comment by Leejjon** [comment]
I found this project where nodemon is usable (it's also full typescript, so no server.js):
https://github.com/kayode-adechinan/remix-express-typescript

This approach gives some es modules errors with the latest remix though.

**Comment by brophdawg11** [comment]
I think the express template _does_ work in most cases as it currently stands and I think we prefer using the built-in `watch` instead of giving every `express` app a potentially unnecessary dependency in `nodemon` or something else. 

Do you know if this impacts _any_ attempt to run remix in dev mode on Linux?  Or is it a small subset/specific combination of Linux distro + node version?

One of the benefits of templates is they're only intended to be a starting point that you can tweak to your app needs.  If you are able to figure out the workaround for your Linux setup - maybe we can add a FAQ section to the template or something for edge case issues like this?

**Comment by Leejjon** [comment]
I only have one I have tried it out on the google cloud interactive console and get the same error.
![Screenshot from 2023-11-04 16-20-55](https://github.com/remix-run/remix/assets/1529142/716182fe-5fb5-4909-94b9-97380cb4dd72)

I think for people who run into, this they simply need to change the line:
```    "dev": "remix dev --manual -c \"node --watch-path server.js --watch server.js\"", ```
Into:
```    "dev": "remix dev --manual -c \"node ./server.js\"",```

Then the hot reloading just works for any TSX code in your Remix app, only code changes into the server.js files aren't picked up. For those you would need to restart the server. But I personally am not going to keep using the server.js anyway, but replace it by a server.ts and use nodemon to hot reload it.

**Comment by Leejjon** [comment]
Closing this issue as I'm no longer bothered by it. I'll probably use nodemon for my serious applications.

**Comment by paul-vd** [comment]
Upgrading to node 20 also works.
