### ISSUE TITLE
Link to a non-existent route gives blank page and going back gives an error

### ISSUE THREAD

**Issue by kush-daga** [remix-run/remix#7732]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Add a link to a route that doesn't exist
``` 
<NavLink to="/examples/dashboard">
        Overview
</NavLink>
```

In this case, the `/examples/dashboard` route does not exist. 

Click on this route and go back from the browser back button. 

### Expected Behavior

There should be a 404 page returned/rendered when you click on that link. When you go back, you should see the same page you were on before and not an error.

### Actual Behavior

When the link is clicked, I get a blank page instead of 404. This gets solved by adding an Error Boundary to catch all though, but ideally, it should have been a 404 browser page by default. I suspect this has something to do with client side routing. 

The bigger bug however is when I click on the browser back from this route, I get an error that says `Cannot read properties of null (reading 'appendChild')`

![image](https://github.com/remix-run/remix/assets/40840079/ee284596-494e-4778-9918-9538934a949a)

Here is a video showing the whole thing as well

https://github.com/remix-run/remix/assets/40840079/27398cde-86c9-4875-8db0-97ac7be6a1b3

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction?  Adding a 404 link to https://remix.new works as expected, showing the built-in default 404 error boundary and back-button routing also works as expected?

https://stackblitz.com/edit/remix-run-remix-xwspfu?file=app%2Froutes%2F_index.tsx

**Comment by kush-daga** [comment]
Correct, it works with the boiler plate. I think it has something to do with Clerk and its error boundary, not able to replicate that on stack blitz. Might have to look into my project itself. Thanks for the help and sorry for the misinformed issue!

**Comment by kush-daga** [comment]
Sorry, ignore the above message. I think I have found the root. 

![image](https://github.com/remix-run/remix/assets/40840079/797e83da-bb6c-4422-9dd3-d08e2f80770c)
Commenting these lines make the error go away, ill try to replicate this on stack blitz
