### ISSUE TITLE
no way to test Payable function

### ISSUE THREAD

**Issue by smithit2000** [remix-run/remix#7746]
### What version of Remix are you using?

The Latest One

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes, all in one file

### Steps to Reproduce

I deployed a contract, that had a payable function with also a String parameter. I deploy contract successfully, however I cannot test it. When I click on "Transact" button, I expect MetaMask to popup or somehow to enter the value -- but it does not happen. It just says "transact to contract xyz.newXyz pending" but nothing happen.

Using Injected Provider - Bespoke (Neon EVM) 

The browser is firefox.

### Expected Behavior

It should ask for value to pay in the transaction call.

### Actual Behavior

nothing happen

**Comment by ZipBrandon** [comment]
@smithit2000 I think you want the Remix Project that is here https://github.com/ethereum/remix-project

**Comment by smithit2000** [comment]
sry
