### ISSUE TITLE
TypeError: headers.get is not a function (vite / nightly)

### ISSUE THREAD

**Issue by ZipBrandon** [remix-run/remix#7819]
### What version of Remix are you using?

0.0.0-nightly-0c99349-20231027

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I annotated it at the top of the repo's readme but it uses @PhilDL fork of @sergiodxa's remix-i18next to address ESM issues. https://github.com/sergiodxa/remix-i18next/pull/155

1. Clone https://github.com/ZipBrandon/remix-vite
2. `npm i`
3. `npm run dev` and receive the error

### Expected Behavior

The route to load.

### Actual Behavior

```
  VITE v4.5.0  ready in 716 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

  ⚠️  Remix support for Vite is unstable
     and not recommended for production

TypeError: headers.get is not a function
    at Module.getClientLocales (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/libs/remix-i18next/dist/esm/lib/get-client-locales.js:7:34)
    at LanguageDetector.fromHeader (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/libs/remix-i18next/dist/esm/server.js:167:45)
    at LanguageDetector.detect (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/libs/remix-i18next/dist/esm/server.js:134:37)
    at async handleRequest (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/app/entry.server.tsx:29:13)
    at async handleDocumentRequestRR (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/node_modules/@remix-run/server-runtime/dist/server.js:212:12)
    at async requestHandler (/Users/lazerskates/DEVELOPMENT/forks/remix-vite/node_modules/@remix-run/server-runtime/dist/server.js:93:18)
    at async /Users/lazerskates/DEVELOPMENT/forks/remix-vite/node_modules/@remix-run/dev/dist/vite/node/adapter.js:184:20
    at async /Users/lazerskates/DEVELOPMENT/forks/remix-vite/node_modules/@remix-run/dev/dist/vite/plugin.js:413:13
```

**Comment by hi-ogawa** [comment]
There might be due to inconsistent `Request` polyfills setup in vite adapter.
`remix-i18next` seems to use `instanceof Request` check in https://github.com/ZipBrandon/remix-vite/blob/33a2a42596eac88381fc8fd2b8cc3b151113c687/libs/remix-i18next/dist/esm/lib/get-client-locales.js#L29-L34, but this is probably becoming false and ended up with `Request.get` which is `undefined`.

Adding this logging to the reprodcution, this is observed:

```tsx
export default async function handleRequest(
...
) {
  console.log("### Request", Request, request.constructor);
  console.log("### request instanceof Request = ", request instanceof Request)

// ### Request [class Request extends Body] [class NodeRequest extends Request]
// ### request instanceof Request =  false
```

It seems vite node adapter polyfills `Request` global from `@remix-run/node` (which in turn is from `@remix-run/web-fetch`), but adapter is constructing a different `Request` instance based on `undici`.

https://github.com/remix-run/remix/blob/33c64cbf5cac4112c884f3a3f169fa005af26f3d/packages/remix-dev/vite/node/adapter.ts#L8-L12

**Comment by markdalgleish** [comment]
Thanks for raising this issue! This should be fixed by https://github.com/remix-run/remix/pull/8062. It will be available in the next nightly release. If you could try it and report back, that would be super helpful!

**Comment by MagnumDuck** [comment]
I'm seeing a similar issue right now with Remix 2.8. `request.headers` are undefined. Works under `root.tsx, `routes/xxx.tsx` not so much.

```
// routes/xxx.tsx 
export async function loader(request: Request) {
  console.log("WHERE ARE MY HEADERS?!", request.headers);
  const user = await requireUser(request);
```

```
WHERE ARE MY HEADERS?! undefined
attempting to get user from request
Request headers are missing, without them, there is no session cookie
TypeError: Cannot read properties of undefined (reading 'get')
    at Authenticator.isAuthenticated (/home/magnum/Projects/remix/xxx/node_modules/remix-auth/build/authenticator.js:81:68)
```

Here's more information / a desperate call for help. 

https://discord.com/channels/770287896669978684/1213147694034460712
