### ISSUE TITLE
ErrorBoundary not called when there is no default export in route.tsx file

### ISSUE THREAD

**Issue by inithink** [remix-run/remix#7856]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

app/routes/_index/routes.tsx
```typescript
import type { ActionFunctionArgs } from "@remix-run/node";
import { redirect } from "@remix-run/node";

export const loader = async ({ request }: ActionFunctionArgs) => {
  throw new Error("??");
};
```

app/root.tsx
```typescript
// ...
export function ErrorBoundary() {
  return (
    <div>
      <div>1</div>
    </div>
  );
}
```

If I add some code to app/routes/_index/routes.tsx,
```typescript
export default function Page() {
  return null;
}
```
I can see expected screen.

### Expected Behavior

shows
<img width="2032" alt="image" src="https://github.com/remix-run/remix/assets/11436127/c2b9e059-ea9d-4cba-bb2a-f0c0e14fc3dd">

### Actual Behavior

shows
<img width="2032" alt="image" src="https://github.com/remix-run/remix/assets/11436127/70d822c9-4b48-44d3-a718-bbd7c5d52c3a">

**Comment by kiliman** [comment]
Routes without a default export are Resource Routes. These are not UI routes. `ErrorBoundary` is only rendered on UI routes.

**Comment by brophdawg11** [comment]
As @kiliman said, this is expected behavior since you've made `app/routes/_index/route.tsx` a [Resource Route](https://remix.run/docs/en/main/guides/resource-routes) by not defining a component - so it doesn't behave as part of the UI and instead behaves as an API endpoint which returns the response directly
