### ISSUE TITLE
[vite] CSS modules do not HMR

### ISSUE THREAD

**Issue by nurseiit** [remix-run/remix#7870]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Make any css modules changes after starting to use Vite. But as the [docs say](https://remix.run/docs/en/dev/future/vite#optionally-remove-remix-runcss-bundle): CSS modules should just work with Vite. But they do not play well with HMR.

### Expected Behavior

Any saved changes to `.module.css` files get HMR'd and the page has updated styles.

### Actual Behavior

All styles get reset after the save and the page needs to be hard refreshed to get new styles.

**Comment by nurseiit** [comment]
@pcattori thanks for the huge amount of work to make this transition possible!

I would love to contribute towards fixing this, any possible pointers from here? Thanks!

**Comment by pcattori** [comment]
Possible duplicated of https://github.com/remix-run/remix/issues/7853

**Comment by nurseiit** [comment]
> Possible duplicate of #7853

Confirming this is a duplicate, running on incognito fixes it. Thanks!
