### ISSUE TITLE
[Vite] URL With Encode Character Returns 404

### ISSUE THREAD

**Issue by Irvan789** [remix-run/remix#7871]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Rename `favicon.ico` to `favicon#1.ico`
2. Run development server with `npm run dev`
3. Open your browser `http://localhost:5173/favicon%231.ico`

### Expected Behavior

Browser showing image of `favicon#1.ico`
![image](https://github.com/remix-run/remix/assets/33544411/9a051346-df2b-4341-8c3d-195437cc3b6a)

### Actual Behavior

Browser showing 404 Not Found
![image](https://github.com/remix-run/remix/assets/33544411/709a259f-5b67-4008-a670-1218b9613e30)

**Comment by pcattori** [comment]
[Reproduced this in Vite w/o Remix](https://stackblitz.com/edit/vitejs-vite-koxnd2?file=public%2Fvite.svg) so this isn't a Remix-specific issue. If you'd like to pursue this, probably best to open an issue on the Vite github.
