### ISSUE TITLE
ReferenceError: React is not defined when using JS in Vite

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix#7885]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Start a new vite-based remix app

```sh
npx create-remix@nightly --template remix-run/remix/templates/unstable-vite
```

Add a route with a `.jsx` extension and navigate to it

See your browser blow up

### Expected Behavior

Router renders

### Actual Behavior

Route does not render unless you manually install @vittejs/plugin-react and update the config to be

```ts
import { unstable_vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [remix(), react()],
});
```

I'm pretty confident we don't want to users to manually have to import the `react` plugin. At a minimum, js/jsx should definitely work out of the box

**Comment by hi-ogawa** [comment]
I'm attempting to fix this issue in https://github.com/remix-run/remix/pull/7888
I think the workaround could work directly from local vite config by:

```tsx
import { unstable_vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [remix(), tsconfigPaths()],
  //
  // WORKAROUND
  //
  esbuild: {
    jsx: "automatic"
  }
});
```

**Comment by markdalgleish** [comment]
Fixed by https://github.com/remix-run/remix/pull/7888.
