### ISSUE TITLE
[Vite] Bun with custom server doesn't work correctly

### ISSUE THREAD

**Issue by ceopaludetto** [remix-run/remix#7887]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a simple `vite.config.ts` file:

```ts
import { unstable_vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [remix()],
});
```

2. Create a simple `server.ts` file with the following content:

```ts
import type { Serve } from "bun"

import { unstable_createViteServer } from "@remix-run/dev";

const devServer = await unstable_createViteServer();

export default {
  port: 3000,
  fetch: async (request) => new Response("Hello world!"),
} satisfies Serve;
```

3. Start the server:
```sh
bun run server.ts
```

4. Hit `http://localhost:3000`, you'll gonna see this screen:

![image](https://github.com/remix-run/remix/assets/30508218/b284ec66-702d-4844-917b-fceafbbbf270)

5. If you comment the `plugins: [remix()]` line in `vite.config.ts` you'll see that the "Hello world!" message works as expected. So I think that the remix plugin breaks Bun HTTP server, even if I use the express template the problem is the same, the server will only work if the remix plugin is removed from `vite.config.ts`

Reproduction link: https://codesandbox.io/p/sandbox/bun-vite-remix-bug-rfps6n?file=/vite.config.ts:5,1-6,1
Bun version: 1.0.7

### Expected Behavior

Vite server should work on Bun correctly

### Actual Behavior

Remix plugin breaks Bun HTTP server

**Comment by ceopaludetto** [comment]
Seems to work on Bun 1.0.19 and Remix 2.4.1

**Comment by pcattori** [comment]
Confirmed working w/ Bun v1.0.22 and Remix v2.5.0
