### ISSUE TITLE
Can not properly use PrimeReact UI library with Remix

### ISSUE THREAD

**Issue by AYastrebtsov** [remix-run/remix#7907]
### What version of Remix are you using?

latest(2.2.0)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Install remix with npx create-remix@latest
Install PrimeReact with npm install primereact

Import any component to page according to docs
`import { Button } from 'primereact/button'`

And render it on a page
`<Button label="This is Prime Button" />`
        

### Expected Behavior

Page renders with no errors.

### Actual Behavior

When trying to run dev server or prod build this  error happens:

Error: Directory import '/Users/andrey/Documents/pets/tourRM/node_modules/primereact/button' is not supported resolving ES modules imported from /Users/andrey/Documents/pets/tourRM/build/index.js
Did you mean to import primereact/button/button.cjs.js?

    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:319:17)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

If I import component as error suggests everything works, but a get this error from TypeScript

`Could not find a declaration file for module 'primereact/button/button.cjs.js'. '/Users/andrey/Documents/pets/tourRM/node_modules/primereact/button/button.cjs.js' implicitly has an 'any' type.
  If the 'primereact' package actually exposes this module, try adding a new declaration (.d.ts) file containing declare module 'primereact/button/button.cjs.js';`

I tried to get types from `node_modules`, but was unable to apply them. Right now I "solve" this problem with `@ts-ignore` which is far from ideal.

Can you guys check this out?
We as a company used and still using PrimeReact with Vite and Next and it  works as expected. And we can not switch to MUI or AntD or Chakra because they all use css-in-js which is not ideal for SSR.

Lately we also not happy with where Next.js is going and right now getting our feet wet with Remix, trying to understand if we could make the switch.

Thanks everyone in advance.

**Comment by brophdawg11** [comment]
Do you have a [`serverModuleFormat`](https://remix.run/docs/en/main/file-conventions/remix-config#servermoduleformat) set in your remix config?

**Comment by AYastrebtsov** [comment]
> Do you have a [`serverModuleFormat`](https://remix.run/docs/en/main/file-conventions/remix-config#servermoduleformat) set in your remix config?

No, I don't, but according to Remix docs  it is 'esm' by default, I tried 'cjs'as well, but result is still the same.

I also asked around about this problem in PrimeReact community, right now it seems that the issue is one their side.

They say that this issue should fi the problem

https://github.com/primefaces/primereact/pull/5237

So right now I am waiting for this issue to be merged. If after that everything is ok, I'll close this one.

**Comment by melloware** [comment]
Tomorrow I am going to try and test my fix locally and let you know how it goes

**Comment by cd4success** [comment]
> ### What version of Remix are you using?
> latest(2.2.0)
> 
> ### Are all your remix dependencies & dev-dependencies using the same version?
> * [x]  Yes
> 
> ### Steps to Reproduce
> Install remix with npx create-remix@latest Install PrimeReact with npm install primereact
> 
> Import any component to page according to docs `import { Button } from 'primereact/button'`
> 
> And render it on a page `<Button label="This is Prime Button" />`
> 
> ### Expected Behavior
> Page renders with no errors.
> 
> ### Actual Behavior
> When trying to run dev server or prod build this error happens:
> 
> Error: Directory import '/Users/andrey/Documents/pets/tourRM/node_modules/primereact/button' is not supported resolving ES modules imported from /Users/andrey/Documents/pets/tourRM/build/index.js Did you mean to import primereact/button/button.cjs.js?
> 
> ```
> at new NodeError (node:internal/errors:399:5)
> at finalizeResolution (node:internal/modules/esm/resolve:319:17)
> at moduleResolve (node:internal/modules/esm/resolve:945:10)
> at defaultResolve (node:internal/modules/esm/resolve:1153:11)
> at nextResolve (node:internal/modules/esm/loader:163:28)
> at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
> at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
> at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
> at link (node:internal/modules/esm/module_job:76:36)
> ```
> 
> If I import component as error suggests everything works, but a get this error from TypeScript
> 
> `Could not find a declaration file for module 'primereact/button/button.cjs.js'. '/Users/andrey/Documents/pets/tourRM/node_modules/primereact/button/button.cjs.js' implicitly has an 'any' type. If the 'primereact' package actually exposes this module, try adding a new declaration (.d.ts) file containing declare module 'primereact/button/button.cjs.js';`
> 
> I tried to get types from `node_modules`, but was unable to apply them. Right now I "solve" this problem with `@ts-ignore` which is far from ideal.
> 
> Can you guys check this out? We as a company used and still using PrimeReact with Vite and Next and it works as expected. And we can not switch to MUI or AntD or Chakra because they all use css-in-js which is not ideal for SSR.
> 
> Lately we also not happy with where Next.js is going and right now getting our feet wet with Remix, trying to understand if we could make the switch.
> 
> Thanks everyone in advance.

I'm facing this same issue at the moment.

**Comment by jiwonz** [comment]
I also have the same issue!
```
Error: Directory import 'myproject/node_modules/primereact/button' is not supported resolving ES modules imported from myproject/build/index.js
Did you mean to import primereact/button/button.cjs.js?
    at new NodeError (node:internal/errors:406:5)
    at finalizeResolution (node:internal/modules/esm/resolve:227:11)
    at moduleResolve (node:internal/modules/esm/resolve:845:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

**Comment by AYastrebtsov** [comment]
I migrated my project to Vite https://remix.run/docs/en/main/future/vite and PrimeReact and its types are working correctly now. Since Vite is going to be the default bundler for Remix, I think that it's OK to close this issue as resolved.

**Comment by U-4-E-A** [comment]
> I also have the same issue!
> 
> ```
> Error: Directory import 'myproject/node_modules/primereact/button' is not supported resolving ES modules imported from myproject/build/index.js
> Did you mean to import primereact/button/button.cjs.js?
>     at new NodeError (node:internal/errors:406:5)
>     at finalizeResolution (node:internal/modules/esm/resolve:227:11)
>     at moduleResolve (node:internal/modules/esm/resolve:845:10)
>     at defaultResolve (node:internal/modules/esm/resolve:1043:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
>     at link (node:internal/modules/esm/module_job:84:36)
> ```

Were you able to solve this? I have the same issue with a different library.

**Comment by AYastrebtsov** [comment]
Yes, we migrated our project to Remix Vite, and in our case PrimeReact works as it supposed to

**Comment by erufenix** [comment]
This fix for Remix in SPA mode doesn't work.

Does anyone know the solution?

I found a possible solution

`resolve: {
    alias: {
      'primereact/utils': 'primereact/utils/utils.esm.js'
    }
  },`

But it didn't work
