### ISSUE TITLE
Vite: `process.env` variables are not working inside loader

### ISSUE THREAD

**Issue by mikkpokk** [remix-run/remix#7934]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Define custom environment variable on .env file:

```text
TEST="Custom value"
REMIX_TEST="Custom value"
VITE_TEST="Custom value"
```

On root.tsx add loader

```javascript
export const loader: LoaderFunction = async (args) => {
    console.log(process.env.TEST) // outputs undefined
    console.log(process.env.REMIX_TEST) // outputs undefined
    console.log(import.meta.env.VITE_TEST) // outputs Custom value

     return {
         test: process.env.TEST, // outputs undefined
         remix_test: process.env.REMIX_TEST, // outputs undefined
         vite_test: import.meta.env.VITE_TEST, // outputs Custom value
     }
}
```

### Expected Behavior

Server side code should be able to read data from `process.env`. I believe using `import.meta.env.VITE_TEST` on SSR code reveals that variable to client side code as expected by Vite documentation.

Maybe I'm missing something? Or it's a bug?

### Actual Behavior

Trying to get any `process.env` variables inside loaders return always `undefined` instead.

**Comment by mikkpokk** [comment]
This is how my issue were solved:
`rm -rf ./node_modules && npm install`

Not sure what kind of cache lived and caused it

**Comment by mikkpokk** [comment]
Adding `import 'dotenv/config'` inside any `*.server.ts` file, which are used in all the routes, will fix the issue on dev server, but doesn't fix it on build.

**Comment by markdalgleish** [comment]
This was an oversight on my part as I misunderstood how Vite handles `.env` files. I should have a fix for this soon, but you can use this workaround in the meantime:

```ts
import { unstable_vitePlugin as remix } from "@remix-run/dev";
import { ConfigEnv, defineConfig, loadEnv } from "vite";

export default ({ mode }: ConfigEnv) => {
  // Here we add env vars from .env files to process.env.
  // Note the last arg is a blank string so that all env vars
  // are loaded, not just those starting with "VITE_"
  Object.assign(process.env, loadEnv(mode, process.cwd(), ""));

  return defineConfig({
    plugins: [
      remix(),
      // ...etc
    ],
  });
};

```

**Comment by markdalgleish** [comment]
This has been fixed in https://github.com/remix-run/remix/pull/7958 and will be available in the next release. If you'd like, you can update to the latest nightly to get this fix. If you're still having issues, let me know.

**Comment by mtin79** [comment]
HI there, upgraded to 2.3.0 and when i run `nom run build` and `nom run start` all the variables i have in .env are undefined when i try to get their values in `process.env.<VariableName>`

**Comment by markdalgleish** [comment]
@mtin79 Could you share a minimal repro?

**Comment by kolorfilm** [comment]
> This was an oversight on my part as I misunderstood how Vite handles `.env` files. I should have a fix for this soon, but you can use this workaround in the meantime:
> 
> ```ts
> import { unstable_vitePlugin as remix } from "@remix-run/dev";
> import { ConfigEnv, defineConfig, loadEnv } from "vite";
> 
> export default ({ mode }: ConfigEnv) => {
>   // Here we add env vars from .env files to process.env.
>   // Note the last arg is a blank string so that all env vars
>   // are loaded, not just those starting with "VITE_"
>   Object.assign(process.env, loadEnv(mode, process.cwd(), ""));
> 
>   return defineConfig({
>     plugins: [
>       remix(),
>       // ...etc
>     ],
>   });
> };
> ```

I tried that as well and I still not seeing any process.env variables in my react code.

It says: `Uncaught ReferenceError: process is not defined` when I try to log/access them.

**Comment by kiliman** [comment]
You can't access `process.env` inside your React components because they will render on both the client and the server, and the browser doesn't have access to `process`.

You'll need to send the desired environment variables from your root loader.

https://remix.run/docs/en/main/guides/envvars#browser-environment-variables

**Comment by AdityaSaroj** [comment]
> > This was an oversight on my part as I misunderstood how Vite handles `.env` files. I should have a fix for this soon, but you can use this workaround in the meantime:
> > ```ts
> > import { unstable_vitePlugin as remix } from "@remix-run/dev";
> > import { ConfigEnv, defineConfig, loadEnv } from "vite";
> > 
> > export default ({ mode }: ConfigEnv) => {
> >   // Here we add env vars from .env files to process.env.
> >   // Note the last arg is a blank string so that all env vars
> >   // are loaded, not just those starting with "VITE_"
> >   Object.assign(process.env, loadEnv(mode, process.cwd(), ""));
> > 
> >   return defineConfig({
> >     plugins: [
> >       remix(),
> >       // ...etc
> >     ],
> >   });
> > };
> > ```
> 
> I tried that as well and I still not seeing any process.env variables in my react code.
> 
> It says: `Uncaught ReferenceError: process is not defined` when I try to log/access them.

Did you manage to make this work?

**Comment by kolorfilm** [comment]
> > > This was an oversight on my part as I misunderstood how Vite handles `.env` files. I should have a fix for this soon, but you can use this workaround in the meantime:
> > > ```ts
> > > import { unstable_vitePlugin as remix } from "@remix-run/dev";
> > > import { ConfigEnv, defineConfig, loadEnv } from "vite";
> > > 
> > > export default ({ mode }: ConfigEnv) => {
> > >   // Here we add env vars from .env files to process.env.
> > >   // Note the last arg is a blank string so that all env vars
> > >   // are loaded, not just those starting with "VITE_"
> > >   Object.assign(process.env, loadEnv(mode, process.cwd(), ""));
> > > 
> > >   return defineConfig({
> > >     plugins: [
> > >       remix(),
> > >       // ...etc
> > >     ],
> > >   });
> > > };
> > > ```
> > 
> > 
> > I tried that as well and I still not seeing any process.env variables in my react code.
> > It says: `Uncaught ReferenceError: process is not defined` when I try to log/access them.
> 
> Did you manage to make this work?

Yes they implemented a fix in on of the last versions. See here: https://github.com/vitejs/vite/pull/15173
