### ISSUE TITLE
remix hydration errors

### ISSUE THREAD

**Issue by Alfredoes234** [remix-run/remix#7944]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Just initialising the project with
```
pnpm create remix@latest
```
and after it all installs run 
```
pnpm run dev
```
it proceeds to give you a hydration error even though I have changed nothing with it & im pretty sure this persisted accross systems

### Expected Behavior

I expected no hydration errors to be present in the browser console 

### Actual Behavior

Hydration errors in console which it didn't used to have.
![Screenshot from 2023-11-08 16-54-08](https://github.com/remix-run/remix/assets/114923333/44ecc2a0-9c6c-4370-8f91-e04e969d7628)

**Comment by Alfredoes234** [comment]
It has also persisted accross browsers

**Comment by kiliman** [comment]
This is a known React issue. You most likely have a browser extension that is modifying the DOM before hydration. Search this repo and you'll find many duplicate issues.

There are a couple of workarounds.

The simplest is to update to the latest React canary version (v18.3) which fixes the problem. 

You can also check out https://github.com/kiliman/remix-hydration-fix which lets you render the `<head>` and `<body>` separately.
