### ISSUE TITLE
[Bug]: Remix removing 3rd Party/ cross-site cookies on page refresh or page redirect/navigate

### ISSUE THREAD

**Issue by spencersmb** [remix-run/remix#796]
### What version of Remix are you using?

1.0.5

### Steps to Reproduce

Clone repo: https://github.com/spencersmb/remix-cookie-test

1. npm install
2. npm run dev
3: go to this url: http://localhost:3000/login?postType=post&previewPostId=8403
4. Login with the credentials listed on the login page
5. See cookies get saved in storage
6. Refresh the page
7. Look to see if cross-site cookies get removed

### Expected Behavior

Once a cookie is saved in browser storage, it should not be removed unless the developer writes code to do so, or a user deletes it manually. Nothing should be deleted automatically like this. I have another app built in next.js and cookies are not getting deleted no matter what domain they are from.

### Why is this needed

I can only speak to my wishlist need of being able to support Native Wordpress cookies so I can have a headless wordpress with a single sign on/ auth process between my frontend and DB. Allowing cross-site cookies would enable me to get Native Wordpress auth cookies from another domain like WpEngine, save them to the browser of my Remix App, and then make client side calls with Remix when I need Auth content. Client-side is still important here because I can pass cookies back and forth with a request without needing to actually read them on the server with Remix. It's still secure because I can't even read the cookie since its not from the Remix apps domain.

Having a single login is nice because when I'm drafting a post/page in Wordpress and I'm ready to preview it on my headless Wordpress, I can click the preview button and it opens up my headless app and automatically gets the draft using the auth data which is saved in the cross-site cookie. Otherwise when I click preview, the frontend app opens up and I get a second login window. At this point I would have to use JWT tokens for the front-end and then go to the wordperss DB login for the actual database dashboard. I'm sure there are other use cases for 3rd party cookies google, facebook, cloudflare just to name a few.

Thank you for your consideration.

### Actual Behavior

Once the cookie is saved in storage to the browser and the user is redirected or decides to refresh the page, the cross-site cookies are deleted.

Scenario 2: User logs in successfully. Cookies get saved. Refresh page - cookies are gone. Log in again but with purposely incorrect username so the api doesn't auth. The cookies from the first time show back up. Refresh page - cookies are gone.
Strange behavior.

**Comment by brophdawg11** [comment]
I'm unable to login to your reproduction app due to CORS issues.  If this is still an issue in current versions of remix can you provide a minimal reproduction of the issue?
