### ISSUE TITLE
`vite build` error --  Transform failed with 3 errors - Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#7969]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

**app-config.ts**
```ts
const getValue = async () => return 1;

export const some_value = await getValue()
```

**server.ts**
```ts
import {some_value} from './app-config.ts`
```

Then run `npm run build`

```
 195 modules transformed.
[vite:esbuild-transpile] Transform failed with 3 errors:
index.js:42:0: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 3 overrides)
index.js:54:0: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 3 overrides)
index.js:66:0: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 3 overrides)
```

### Expected Behavior

remix's vite plugin should detect the `tsconfig.json` settings that a user has in their remix project.
I have `"target": "ES2022",` in my `tsconfig.json` but its not being used for the build step 🤔

**Comment by cliffordfajardo** [comment]
I was able to solve this by adding this to my vite.config.ts file:

```
build: {
    target: "ES2022"
  },
```


## References
- vite discussion: https://github.com/vitejs/vite/issues/6985

**Comment by cliffordfajardo** [comment]
I was able to solve this by adding this to my vite.config.ts file:

```
build: {
    target: "ES2022"
  },
```
I used the ES2022 `target` value from my tsconfig.json file:
```
{
  "include": ["env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "target": "ES2022",
    "module": "ES2022",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },

    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}

```


## References
- vite discussion: https://github.com/vitejs/vite/issues/6985


@pcattori @markdalgleish - maybe the remix vite plugin should use tsconfig settings a user has?

**Comment by cliffordfajardo** [comment]
The error message referenced `firefox78`, so I did a grep in node_modules folder for that string and saw it came from vite
```sh
cd node_modules
grep -r "firefox78"

./vite/dist/node/constants.js:    'firefox78',
```
then that gave me an indication it was coming from vite. But I should have probably known that since this error happens when calling `vite build` 😄 
```
"build": "vite build && vite build --ssr",
```
Then I did a google search for the error: `vite Top-level await is not available in the configured target environment`
and it was nice seeing vite community provide answers 🙏

**Comment by markdalgleish** [comment]
Thanks for raising this.

This is strictly a Vite issue. We're wanting to keep Remix decoupled from your Vite config as much as possible, and this is a good example of something that you're free to configure yourself. If you want your Vite config to automatically sync with your tsconfig, this could be implemented as its own Vite plugin outside of Remix.

**Comment by SpencerDuball** [comment]
Just ran into this error with remix@2.5.1 while deploying with SST. The fix that worked for me was to set:

```ts
export default defineConfig({
  server: { port: 3000 },
  plugins: [remix(), tsconfigPaths()],
  optimizeDeps: { esbuildOptions: { target: "esnext" } }, // <-- Set this to resolve issue.
});
```

Got this solution from: https://github.com/mozilla/pdf.js/issues/17245

**Comment by vmaubert** [comment]
Hi.

Can we have a build target for the server bundle and another one for the client bundle?
I need a top-await during the startup, and I don’t want to set `target: esnext` for the browsers…

Thx!

**Comment by cliffordfajardo** [comment]
@vmaubert - i created a new remix discussion here since I still do find the `serverModuleFormat` and `build` top level vite options confusing

Would be good to get your input 🙏 
https://github.com/remix-run/remix/discussions/8856

**Comment by luzat** [comment]
@vmaubert Selecting a different build target the server build (SSR) seems to work like that:

```
export default defineConfig(({ isSsrBuild }) => ({
  plugins: [
    remix(),
    tsconfigPaths(),
  ],
  build: isSsrBuild ? { target: 'ES2022' } : {},
}))
```

This allows me to use top-level await in server code while not messing with browser code.
