### ISSUE TITLE
[Feature]: Server adapters for other framework？

### ISSUE THREAD

**Issue by fx109138** [remix-run/remix#799]
### What is the new or updated feature that you are suggesting?

Is there any plan to provide an official adapters for deploying with other node server framework, such as koa, fastify?
Or just provide API and be supported by the community?

### Why should this feature be included?

Now just 5 adapters that cannot  cover more user needs. If I want to support koa, what should I do?  Make a pull request for the remix to add @remix-run/koa or just create a personal repo?

**Comment by sergiodxa** [comment]
You can already build your own, in Discord someone shared an adapter for Fastify

**Comment by mcansh** [comment]
> You can already build your own, in Discord someone shared an adapter for Fastify

https://github.com/mcansh/remix-fastify 😬 (I'm personally not sure what our limits of remix scoped adapter is)
