### ISSUE TITLE
Shopify Remix App and POS UI extension

### ISSUE THREAD

**Issue by muhammadluqman101** [remix-run/remix#7993]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Hi,
I am building a shopify custom app with a checkout UI extension. I have used the cli to get started with the remix template. The checkout UI extension itself is working fine, but now I want to make a call to the admin to retrieve some data, i built an api for this under
app > api.updatesavedcartdata.jsx (ignore the naming)

import { json } from "@remix-run/node";
export async function loader({ request }) {
  return json(
    { data: "HELLO" }
  );
}

Now i am trying to call this api in my checkoutUI extension 

 
const response = await fetch(
      https://wise-casey-windows-novel.trycloudflare.com/api/updatesavedcartdata
    );
    console.log("helo", response);
 
Where https://wise-casey-windows-novel.trycloudflare.com/ is the cloudflare link it generates on using yarn run dev. When I do this I get a cors origin error on the checkout page where the checkout ui loads the error:

Access to fetch at 'https://wise-casey-windows-novel.trycloudflare.com/api/updatesavedcartdata' from origin 'https://cdn.shopify.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
 I tried changing and adding cors headers to the api response

export async function loader({ request }: ActionFunctionArgs) {
  return json(
    { data: "HELLO" },
    {
      headers: {
        "Access-Control-Allow-Origin": "*",
      },
    }
  );
}

But same error

Any help would be appreciated on implementing this. My final use case is reading the customer's tags or metafields to set a condition. If there are any alternative approaches to this that would be fine as well  (currently by calling the admin graphql with customerid in the api)

Thanks!

### Expected Behavior

The correct response should be

{"data":"HELLO"}

### Actual Behavior

Access to fetch at 'https://wise-casey-windows-novel.trycloudflare.com/api/updatesavedcartdata' from origin 'https://cdn.shopify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by mikkpokk** [comment]
it is not Remix related issue. Simple Google helps you out and explains what CORS is.

https://www.google.com/search?q=Access+to+fetch+at+from+origin+has+been+blocked+by+CORS+policy&oq=Access+to+fetch+at+from+origin+has+been+blocked+by+CORS+policy
