### ISSUE TITLE
[Bug]: No hot reload when serving with netlify

### ISSUE THREAD

**Issue by alanjhughes** [remix-run/remix#800]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [X] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

Init a project and select Netlify as the deployment

### Expected Behavior

Start the Netlify dev server and remix and have the page reload on file saves

### Actual Behavior

Browser has to be manually refreshed to see changes

**Comment by adyz** [comment]
Same here, any solutions?

**Comment by adyz** [comment]
I've modified the `dev` script from package json to 
```
"dev": "remix watch & npm run dev:netlify",
```
and now I run just `npm run dev` that starts remix and netflify. It also reloads the server when some server functions are changed.

You still need to hit that refresh button since at least on my project there is no hot reload mechanism.

**Comment by coreybruyere** [comment]
Came here to point this out - @adyz This looks like a work around for now

**Comment by coreybruyere** [comment]
Hot reload still doesn't work, have to manually refresh but don't have to stop `npm run dev` script with the suggestion above.

**Comment by mcansh** [comment]
looks like a build cache issue has crept its way in, I'll take a look. Sorry folks 🙏

**Comment by mcansh** [comment]
could you try this [netlify.toml](https://github.com/remix-run/remix/blob/dev/packages/create-remix/templates/netlify/netlify.toml) and make sure your `devServerPort` in remix.config.js is set to 8002

**Comment by alanjhughes** [comment]
Still have this issue. Tried your suggestion @mcansh and get server port clashes. When you start both scripts, following the README, it starts but no hot reloading. If you stop one and restart it you get a port clash. I got it working briefly by changing ports in the remix.config but when you start and stop again you are back to the same issue.

**Comment by alanjhughes** [comment]
Ok, so you can get it working if you use @mcansh suggested .toml and change the port of the remix.config every time before you run it

**Comment by alanjhughes** [comment]
Occasionally you will get this when it reloads
```
SyntaxError: /Users/alanjhughes/Developer/Projects/reppy-remix/netlify/functions/server/build/assets.json: Unexpected end of JSON input
  parse (<anonymous>)
  Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22)
  Module.load (node:internal/modules/cjs/loader:981:32)
  Function.Module._load (node:internal/modules/cjs/loader:822:12)
  Module.require (node:internal/modules/cjs/loader:1005:19)
  require (node:internal/modules/cjs/helpers:102:18)
  Object.<anonymous> (/Users/alanjhughes/Developer/Projects/reppy-remix/netlify/functions/server/build/index.js:445:32)
  Module._compile (node:internal/modules/cjs/loader:1101:14)
  Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  Module.load (node:internal/modules/cjs/loader:981:32)
```
