### ISSUE TITLE
`window.location.replace()` rolled back in firefox

### ISSUE THREAD

**Issue by gerbyzation** [remix-run/remix#8011]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've made a small project to repro this issue: https://github.com/gerbyzation/remix-repro-firefox-location-replace-rollback.
The app has the following snippet in `root.tsx`:
```js
  const navigation = useNavigation();

  useEffect(() => {
    if (navigation.location?.pathname === "/news") {
      console.log("replacing location with google.com");
      window.location.replace("https://www.google.com");
    }
  }, [navigation]);
```
On the homepage is a link to `/news`. 

```
$ git clone https://github.com/gerbyzation/remix-repro-firefox-location-replace-rollback
$ cd remix-repro-firefox-location-replace-rollback
$ npm install
$ npm run dev
```
After getting the app started locally, open up `http://localhost:3000` with firefox, click on the news link that appears on page

### Expected Behavior

When clicking the news link, the page should replace the location with google.com. Following these steps in Chrome or Safari gives the expected result.

### Actual Behavior

Firefox somehow navigates back to the current URL:

<img width="690" alt="Screenshot 2023-11-14 at 17 53 51" src="https://github.com/remix-run/remix/assets/2500973/20c0332b-b777-481c-8f65-48345b16eef3">

**Comment by gerbyzation** [comment]
For some context, what we're trying to do here is have the ability to reload the document for certain paths. We're running multiple applications on the same domain, so for example application A has a link `/news`, which is hosted on application B. When the app detects that we're visiting a path that belongs to another application it should cause a page refresh so the right appliation handles the request.

**Comment by brophdawg11** [comment]
This isn't so much a Remix issue but an issue without how Chrome/Firefox handle interruptions of the network requests with navigations.

When you start a navigation, Remix kicks off the loader and the JS module loads for the route JS chunks in parallel.  Then you're doing a `window.location.replace` _during_ a client-side Remix navigation (essentially while the Remix  requests are pending).  

In Firefox, they seem to abort the JS chunk request on your navigation, but they let the JS thread continue when the loader resolves (maybe it just finished fast enough) and then Remix can't find the route module for the `/news` route because the request was aborted so it does a hard refresh (which is sort of a last resort to "fix" the issue).

In Chrome maybe they interrupt the JS thread so that Remix never attempts to process the resulting route module/loader results?

But the core of the issue is you've got two things fighting each other to mange the URL (Remix and your code) which will always lead to issues.  

Instead, you should tell Remix through the supported mechanisms ([`redirect`](https://remix.run/docs/en/main/utils/redirect), [`redirectDocument`](https://remix.run/docs/en/main/utils/redirectDocument)) that you want a given route to redirect:

```ts
export function loader({ request }: LoaderFunctionArgs) {
  if (new URL(request.url).pathname === "/news") {
    return redirectDocument('https://google.com');
  }
  return json({});
}
```

**Comment by gerbyzation** [comment]
@brophdawg11 Thanks for the explanation! I'm familiar with `redirectDocument` and we've been using this in prod via a patch well before it was released as part of remix for some other usecases. The challenge here is that we need to respond to client-side navigation.

I suppose we could handle this on the server side as long as we make sure it always tries to call a loader, but we'd need to apply this to all loaders on a global level. Is there any advice on how to implement this, as there isn't a middleware layer yet?

**Comment by gerbyzation** [comment]
At the end of the day `redirectDocument` returns the `X-Remix-Reload-Document` in the loader response, the remix app processes this and in the end does the same what I try to do here outside of remix: modify the `window.location` object in the frontend. 

If modifying `window.location` during client-side nav is a problem, would it not make sense to expose a client-side API to trigger a document reload?

**Comment by kiliman** [comment]
They should add support for using `navigate()` to go to external URLs.

```ts
const navigate = useNavigate()
navigate('https://google.com')
```

**Comment by gerbyzation** [comment]
@kiliman In this example I used an external domain, but really we want to do this on the same domain. We run multiple apps on the same domain and need to route between them. So something like passing `reloadDocument: true` as an option to `navigate()` could help with that. 

Whether full/external domains should be supported is a good question, but possibly a separate consideration

**Comment by gerbyzation** [comment]
Started a discussion to propose adding `reloadDocument` to `navigate()` or something similar: https://github.com/remix-run/remix/discussions/8021

**Comment by brophdawg11** [comment]
The way I would recommend doing this today in one spot, without causing a router conflicts is to not interrupt the ongoing navigation.  So instead of doing this in an effect on the in-flight `navigation` - do it once the navigation completes and we render the destination route.

```
// $.tsx
export default function Component() {
  let location = useLocation();

  useEffect(() => {
    if (location.pathname === "/news") {
      window.location.replace("https://www.google.com");
    }
  }, [location]);

  if (location.pathname === '/news') {
    // Nothing to render at /news since we'll just be navigating away
    return null;
  }

  // Normal splat route rendering
}
```

**Comment by gerbyzation** [comment]
@brophdawg11 Handling this in the splat route would probably be sufficient if there is no overlap in routes between the applications. However route migrations from one app to another app is a common usecase, e.g. app B is a legacy application and has the /news page, which is being rebuild and eventually migrated to app A.

Adding this manually to relevant routes would be far from ideal, as that means that each time we have to update and coordinate for 2 applications plus the HTTP routing layer. In addition it means we might have to wait for loaders to finish before we can reroute.
