### ISSUE TITLE
create-remix v2.3.0 adds default `_index.tsx` file to template code even when `_layout._index.tsx` exists

### ISSUE THREAD

**Issue by andrelandgraf** [remix-run/remix#8040]
### Reproduction

Run `npx create-remix@latest` using a template that does not have an `_index.tsx` file.

Example:

```bash
npx create-remix@latest --template https://github.com/PacktPublishing/Full-Stack-Web-Development-with-Remix/tree/main/15-advanced-session-management/bee-rich/solution
```

Code: https://github.com/PacktPublishing/Full-Stack-Web-Development-with-Remix/tree/main/15-advanced-session-management/bee-rich/solution

Notice that the repo has a `routes/_layout._index.tsx` file, not a `routes/_index.tsx` file.

### System Info

```shell
create-remix v2.3.0

  System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 2.78 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
```

### Used Package Manager

npm

### Expected Behavior

No default template code is added to an existing template.

### Actual Behavior

Default `_index.tsx` is added.

**Comment by andrelandgraf** [comment]
@brookslybrand tried it, and it worked without issues. It could have been a one-time thing. Please close if it is not reproducible. 🙏

**Comment by brophdawg11** [comment]
yeah I ran the above too and I don't see an `app/routes/_index.tsx file` in my created app - so my guess is this was something else.  Maybe the destination directory already existed with `app/routes/_index.tsx`?
