### ISSUE TITLE
SSR assets code removed after build

### ISSUE THREAD

**Issue by paul-phan** [remix-run/remix#8041]
### Reproduction

The reproduction requires a real-world like app, for example, a migrated `indie/blues` stack that uses `sideEffect` import or dynamic import.
Previously, running `vite build -ssr` would generate a `build/index.js` file, and the server code would be placed in `build/assets` folder. However, it appears that the `build/assets` folder is now removed immediately after the build process is completed.
I believe it is because of the newly added `writeBundle` code: https://github.com/remix-run/remix/commit/8cd31d6543ef4c765220fc64dca9bcc9c61ee9eb#diff-476a4eef80e39b35b744a556f1aec1762581b6864177c5f3a7ec9717ff415c28R750-R823

![Screenshot 2023-11-17 at 12 31 26](https://github.com/remix-run/remix/assets/11459809/1e957168-bdf4-4fab-b5fd-b62cfac6318b)

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 88.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    bun: 0.5.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 117.1.58.135
    Chrome: 118.0.5993.117
    Safari: 17.2
  npmPackages:
    @remix-run/dev: 2.3.0 => 2.3.0 
    @remix-run/eslint-config: 2.3.0 => 2.3.0 
    @remix-run/express: 2.3.0 => 2.3.0 
    @remix-run/node: 2.3.0 => 2.3.0 
    @remix-run/react: 2.3.0 => 2.3.0 
    @remix-run/serve: 2.3.0 => 2.3.0 
    vite: 5.0.0 => 5.0.0
```

### Used Package Manager

npm

### Expected Behavior

SRR entry output should be `build/index.js` and `build/assets` folder.

### Actual Behavior

`build/assets` folder is missing/removed.

**Comment by hi-ogawa** [comment]
Thanks for reporting the issue.
I made a simpler reproduction here https://github.com/hi-ogawa/remix-reproduction-8041
Indeed, this is a regression from https://github.com/remix-run/remix/issues/8041 as I wasn't aware of code-split js during ssr build.
I thought removing `build/assets` in `writeBundle` is harmless, but probably remix can just leave that directory as is.

**Comment by hi-ogawa** [comment]
@paul-phan I'm hoping this next PR would fix the issue https://github.com/remix-run/remix/pull/8042, but it would be still helpful if you could provide a little more details about your app to spot potential edge cases.
For example, can you provide "vite manifest" of ssr build like I wrote in my reproduction README.md?
There should be a file either `build/manifest.json` (if vite 4) or `build/.vite/manifest.json` (if vite 5). I think this one is still left there without being deleted.

**Comment by paul-phan** [comment]
@hi-ogawa Thanks for the quick update; here is my `manifest.json` file with Vite 5 
[manifest.json](https://github.com/remix-run/remix/files/13393773/manifest.json)

**Comment by markdalgleish** [comment]
This should be fixed by https://github.com/remix-run/remix/pull/8042. It will be available in the next nightly release if you want to try it out and report back.

@paul-phan Looking at your manifest (thanks for sharing it, by the way!), the only files that will be deleted with the fix linked above will be `assets/playground-geHbun2U.css` and `assets/_virtual_server-entry-GEA9ZESU.css` so I'm confident this will fix your issue.

**Comment by hilja** [comment]
I was just majorly blocked by this. The nightly works great! 🔥

**Comment by lylest** [comment]
I still facing this issue how can I resolve it?

**Comment by geiszla** [comment]
We are having the same issue. The `build/server/assets` directory is empty (while the `build/client/assets` directory has the proper assets. The build logs also show the server assets being copied into the build directory, but they are missing after the build has finished.

![Image](https://github.com/user-attachments/assets/268d9483-c051-440a-ad37-a35d602dfc7b)

For now we are using the path to the client assets in production, but that requires conditional code for production and I assume if we remove these assets from the client, then the server will also stop working.
