### ISSUE TITLE
Types of property 'createdAt' are incompatible. Type 'string' is not assignable to type 'Date'.

### ISSUE THREAD

**Issue by ric980** [remix-run/remix#8044]
### Reproduction

1. Add a Prisma model with a field of type DateTime.
2. Get that model in the loader.
3. After useLoaderData the createdAt field is now string.
4. TS breaks.

This is my code:

```
  const posts = await getPosts()

  return json({posts})
}

export default function PostsRoute() {
  const {posts} = useLoaderData<typeof loader>()
```

This is the error I get:

Type 'JsonifyObject<{ id: number; slug: string; createdAt: Date;}>' is not assignable to type '{ id: number; slug: string; createdAt: Date;}'. Types of property 'createdAt' are incompatible. Type 'string' is not assignable to type 'Date'.

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.23 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 3.3.1 - ~/.volta/tools/image/yarn/3.3.1/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 119.0.6045.159
    Safari: 17.1
```

### Used Package Manager

yarn

### Expected Behavior

I expect that JsonifyObject will take care of the Date vs string conversions.

### Actual Behavior

I cannot use any Prisma model with a DateTime field.

**Comment by paulhmorris** [comment]
JSON only supports the following object types: object, array, string, number, boolean, null.

You can either stringify your date in the loader or use [remix-typedjson](https://github.com/kiliman/remix-typedjson)

**Comment by ric980** [comment]
Thanks, I found a good example of using `superjson`.
