### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/react-dom/index.js?v=622b9013' does not provide an export named 'createPortal'

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#8047]
### Reproduction

Currently upgrading a remix app to vite and getting an error from vite about it not being to find an export from a dependency I use in my app:

```
Uncaught SyntaxError: The requested module '/node_modules/react-dom/index.js?v=0f421ad3' does not provide an export named 'createPortal'
```

![image](https://github.com/remix-run/remix/assets/6743796/ca2f58d2-64e9-4dd6-8dd3-845b0c059750)

Whats strange is that I see the `createPortal` being imported with ESM syntax in the depedency I rely on:
(source code of [reactflow importing createPortal](https://github.com/search?q=repo%3Axyflow%2Fxyflow%20createPortal&type=code)), but vite isn't able to pull it out 🤔 

This seems like a vite / 3rd party package issue, but I decided to create this issue in case someone runs into similar looking errors when doing a remix vite upgrade

```
index.mjs?v=22134411:4 Uncaught SyntaxError: The requested module '/node_modules/use-sync-external-store/shim/with-selector.js?v=22134411' does not provide an export named 'default' (at index.mjs?v=22134411:4:8)
```

or
```
Uncaught SyntaxError: The requested module '/node_modules/react-dom/index.js?v=0f421ad3' does not provide an export named 'createPortal'
```

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.60 GB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.5.0 - ~/.volta/tools/image/node/20.5.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.8.0 - ~/.volta/tools/image/node/20.5.0/bin/npm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 114.0.5735.133
    Chrome Canary: 117.0.5849.2
    Safari: 17.1
  npmPackages:
    @remix-run/dev: ^2.3.0 => 2.3.0 
    @remix-run/eslint-config: ^2.3.0 => 2.3.0 
    @remix-run/express: ^2.3.0 => 2.3.0 
    @remix-run/node: ^2.3.0 => 2.3.0 
    @remix-run/react: ^2.3.0 => 2.3.0 
    @remix-run/v1-route-convention: ^0.1.4 => 0.1.4 
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

yarn

### Expected Behavior

.

### Actual Behavior

.

**Comment by cliffordfajardo** [comment]
Tried a few things but no success, but no success:
**vite.config.js**
```
  optimizeDeps: {
    include: [
      'reactflow'
    ]
  }
  

  optimizeDeps: {
    exclude: [
      'reactflow'
    ]
  }

  build: {
    target: "esnext",
  },
```

**Comment by cliffordfajardo** [comment]
Created issue in the relevant repo: https://github.com/xyflow/xyflow/issues/3637

**Comment by pcattori** [comment]
@cliffordfajardo have you tried using `cjs-interop-plugin` or any of the other workarounds listed in [`Vite > Troubleshooting > ESM/CJS`](https://remix.run/docs/en/main/future/vite#esm--cjs)?

**Comment by pcattori** [comment]
@cliffordfajardo if you are still having issues after trying `cjs-interop-plugin` and the other workarounds, then we can reopen this.

**Comment by cliffordfajardo** [comment]
Update:  I was able to migrate without issues on `@remix-run/*` version 2.6, which seems to have a ton of improvements over 2.3 😄 

remix [CHANGELOG](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v260)
