### ISSUE TITLE
Exporting an anonymous Route Component breaks live reload 

### ISSUE THREAD

**Issue by aymanosman** [remix-run/remix#8051]
### Reproduction

* Started with a fresh project using `npx create-remix@latest bug`
* Remove the function name `Index` from the exported Route Component in `/app/routes/_index.tsx`
* Observe that live reload is broken

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 202.70 MB / 32.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.16.0 - /opt/homebrew/bin/pnpm
    Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 119.1.60.114
    Chrome: 119.0.6045.159
    Edge: 117.0.2045.55
    Safari: 16.5
  npmPackages:
    @remix-run/css-bundle: ^2.3.0 => 2.3.0
    @remix-run/dev: ^2.3.0 => 2.3.0
    @remix-run/eslint-config: ^2.3.0 => 2.3.0
    @remix-run/node: ^2.3.0 => 2.3.0
    @remix-run/react: ^2.3.0 => 2.3.0
    @remix-run/serve: ^2.3.0 => 2.3.0
```

### Used Package Manager

npm

### Expected Behavior

Live Reload should work when an anonymous function is exported as a Route Component, or an error is displayed to indicate this is not supported.

### Actual Behavior

Live Reload does not work and no error is indicated.

**Comment by aymanosman** [comment]
This "bug" bit me a couple of times. It would be nice for this situation to emit a warning to the user.

I later found this behaviour is documented in the [Hot Module Replacement](https://remix.run/docs/en/main/discussion/hot-module-replacement#named-function-components) section of the docs. So it is not a bug, but maybe a small DX issue.

**Comment by pcattori** [comment]
Closing as this is documented and is a limitation of React Fast Refresh, not Remix.
