### ISSUE TITLE
Vite: Cannot load manifest during build

### ISSUE THREAD

**Issue by bk-tho** [remix-run/remix#8074]
### Reproduction

- Create a Remix v2.3.0 app in a workspace that is part of an npm workspaces project
- Follow the steps to opt into Vite support
- Run build

### System Info

```shell
macOS 13.5.2
Remix 2.3.0
Vite 5.0.0 (There is v4.5.0 installed as a transitive dep in another npm workspace of the same project)
```

### Used Package Manager

npm

### Expected Behavior

The build works without any errors

### Actual Behavior

- Error
  ```
  [remix-virtual-modules] Could not load virtual:server-manifest
  (imported by virtual:server-entry): ENOENT: no such file or directory, open
  '<PATH_TO_PROJECT_DIR>/public/build/manifest.json'
  ```
- It's true that the file is not present. There _is_ a `<PATH_TO_PROJECT_DIR>/public/build/.vite/manifest.json` instead

**Comment by markdalgleish** [comment]
Could you please share a minimal repro?

**Comment by cliffordfajardo** [comment]
@bk-tho - perhaps for the small reproducible example, you can create a new github repo with 2 super vanilla projects, 1 being the remix app using vite:

Command to create a new remix vite app:
```
npx create-remix@nightly --template remix-run/remix/templates/unstable-vite
```

**Comment by markdalgleish** [comment]
The manifest path is different between Vite 4 and 5.

- Vite 4: `<outDir>/manifest.json`
- Vite 5: `<outDir>/.vite/manifest.json`

It looks like the version of Vite that the Remix Vite plugin is resolving is v5 but you're trying to run the plugin against v4?

**Comment by bk-tho** [comment]
I just tried to create a minimal repro but can't seem to reproduce this error in a new project. I was able to fix the issue by deleting alle `node_module` folders and the `package-lock.json`. I thought this was a thing of the past but oh well 🤷‍♂️

@markdalgleish  While testing things I noticed that `@remix-run/dev@2.3.0` seems to be the last package in my project that causes an installation of `vite@4.5.0`. With a fresh install, this does not seem to cause any problems. Just an FYI.
```
❯ npm list vite                
├─┬ @vitejs/plugin-react@4.2.0
│ └── vite@5.0.1
├─┬ frontend@ -> ./frontend
│ ├─┬ @ladle/react@4.0.0
│ │ ├─┬ @vitejs/plugin-react-swc@3.5.0
│ │ │ └── vite@5.0.1 deduped
│ │ └── vite@5.0.1 deduped
│ ├─┬ @remix-run/dev@2.3.0                    |
│ │ ├─┬ @vanilla-extract/integration@6.2.4    |
│ │ │ ├─┬ vite-node@0.28.5                    |
│ │ │ │ └── vite@4.5.0                        |
│ │ │ └── vite@4.5.0                          |
│ │ └── vite@5.0.1 deduped
│ ├─┬ vite-tsconfig-paths@4.2.1
│ │ └── vite@5.0.1 deduped
│ └── vite@5.0.1 deduped
├─┬ landing-page@ -> ./landing-page
│ └── vite@5.0.1 deduped
└─┬ vitest@0.34.6
  ├─┬ vite-node@0.34.6
  │ └── vite@5.0.1 deduped
  └── vite@5.0.1 deduped
```

I'm closing this because it's resolved for me. Feel free to reopen if you want to investigate further.
