### ISSUE TITLE
[Bug]: Let's ignore .DS_Store within app/routes/

### ISSUE THREAD

**Issue by revelt** [remix-run/remix#811]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

If you open the routes folder with Mac Finder, Mac OS will create .DS_Store file there, which will freak out Remix:

![Screenshot 2021-11-30 at 20 33 15](https://user-images.githubusercontent.com/8344688/144123762-9c607bda-5191-4e87-8944-da1ff6d7acd6.png)

### Expected Behavior

[This line](https://github.com/remix-run/remix/blob/c56761e09d1aeb27c4d3d5374759fd1bb5f79dcf/packages/remix-dev/config/routesConvention.ts#L33) on "else" clause, should check, is the file whitelisted, `.DS_Store` for example.

### Actual Behavior

It's throwing a `new Error` but it seems it's not fatal, app keeps running.

**Comment by ryanflorence** [comment]
What is .DS_Store?

**Comment by ryanflorence** [comment]
Just kidding, we should probably ignore any `.dotfiles`

**Comment by Vivalldi** [comment]
In addition to ignoring `.dotfiles`, can we adjust the messaging to make it clear it's a warning?

Example use case would be a `readme.txt` file in a route collection that's left as a developer note

**Comment by MichaelDeBoey** [comment]
Fixed by #988

**Comment by revelt** [comment]
Good job!
