### ISSUE TITLE
HMR not working in Remix Express Vite Template

### ISSUE THREAD

**Issue by bmaycc** [remix-run/remix#8137]
### Reproduction

As specified in https://remix.run/docs/en/main/future/vite, when runnig Remix-Vite with express, the HMR change doesn't occur (and the page doesn't refresh either)

- Create a new express installation using `npx create-remix@latest --template remix-run/remix/templates/unstable-vite-express`
- Start the app using `npm install`, and `npm run dev`
- App will start on localhost:3000
- Try changing `app/routes/_index.tsx` (e.g. 'Welcome to Remix' -> 'Welcome to Remix123'), the page doesn't update.

If I run with Remix dev server
`npx create-remix@latest --template remix-run/remix/templates/unstable-vite`
and perform the same process, the HMR change works fine.

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.49 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.10.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @remix-run/dev: ^2.3.1 => 2.3.1 
    @remix-run/eslint-config: ^2.3.1 => 2.3.1 
    @remix-run/express: ^2.3.1 => 2.3.1 
    @remix-run/node: ^2.3.1 => 2.3.1 
    @remix-run/react: ^2.3.1 => 2.3.1 
    vite: ^5.0.0 => 5.0.2
```

### Used Package Manager

pnpm

### Expected Behavior

Remix Vite Express should reflect page updates in DEV mode, just like the non-Express version does.

### Actual Behavior

As mentioned above above, Remix/Vite when running under express is not reflecting changes.

**Comment by pcattori** [comment]
Cannot reproduce.

Tried:
- `npm` via `npx create-remix@latest --template remix-run/remix/templates/unstable-vite-express` then `npm run dev`
- `pnpm` via `pnpm dlx create-remix@latest --template remix-run/remix/templates/unstable-vite-express` then `pnpm dev`
- `pnpm` via `npx create-remix@latest --template remix-run/remix/templates/unstable-vite-express` (say "No" to install with `npm`) then `pnpm dev`

Could you post a reproduction on StackBlitz?

Here's a quick checklist of things that could be helpful:
- Is JS enabled in your browser?
- Do you have any warnings/errors in your terminal?
- Do you have any warnings/errors in your browser console?
- Do you have throttling on for your browser?

I actually forgot I had slow 3g turned on until I tried reproducing this and HMR was taking longer than usual 😅 disabled throttling and back to snappy HMR ⚡️

---

One thing I'm confused about: you listed `pnpm` as your package manager, but then used `npx`, `npm install`, and `npm run dev`. Did you mean to select `npm` as your package manager when filling out the bug report?

**Comment by bmaycc** [comment]
Thanks for the check @pcattori - oddly enough I can't reproduce the problem either now, so I'll close.  I'm having trouble on my emotion (css-in-js) case, so I'll see if I can get move this closer to that behavior and I'll re-raise that as needed (or hopefully just figure it ou!).

**Comment by bmaycc** [comment]
Followup on this, I realized my issue (and Stackblitz would have proved it too, so good tip):

When you have multiple separate projects going on the same desktop, be careful to watch for the blocked hmr port.  Vite defaults the HMR port to 24678, so make sure to have a different port setup per project, set in your vite.config.js

```
export default defineConfig({
  ...
  server: {
    hmr: {
      port: [your desired HMR port for your project],
    },
  },
  ...
});
```
