### ISSUE TITLE
Vitest – unable to import functions from files with `.server.ts` extensions

### ISSUE THREAD

**Issue by justinwaite** [remix-run/remix#8140]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-2jmzng?file=app%2Futil.server.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/css-bundle: 2.3.1 => 2.3.1 
    @remix-run/dev: 2.3.1 => 2.3.1 
    @remix-run/eslint-config: 2.3.1 => 2.3.1 
    @remix-run/node: 2.3.1 => 2.3.1 
    @remix-run/react: 2.3.1 => 2.3.1 
    @remix-run/serve: 2.3.1 => 2.3.1 
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

npm

### Expected Behavior

Vitest should be able to import functions from files with `.server.{ts,js}` extensions without issue.

### Actual Behavior

The following error is returned: `TypeError: <function name> is not a function`

Imports from files without .server extension work fine.

**Comment by hi-ogawa** [comment]
Thanks for reporting an issue with repro!

The issues with Vitest are reported in https://github.com/remix-run/remix/issues/8094, https://github.com/remix-run/remix/issues/8094 and the short term fix is to disable remix plugin conditionally by `process.env.VITEST`. 

I tested with your repro here https://stackblitz.com/edit/remix-run-remix-uqrj92?file=vite.config.ts
Would you check this fix would suffice for your use case?

**Comment by justinwaite** [comment]
Ah thanks for pointing those other issues out. I had done a brief search but didn't see the exact issue, though I imagine these are essentially the same issues with different error messages for some reason.

We can close this and track on the other issues.
