### ISSUE TITLE
Route dot notation. A terrible idea

### ISSUE THREAD

**Issue by mschipperheyn** [remix-run/remix#8158]
### Reproduction

I don't know who came up with this and why but it's a terrible idea. It leads to LOOOOONNNNNGGGGG hard to read route file names, a messy looking routes directory and hard to find routes. The amount of time I waste scrolling through that endless list of files to find the right one. Jeez!

### System Info

```shell
Remix 2.x
```

### Used Package Manager

yarn

### Expected Behavior

Just give me back folders please. And allow me to find stuff quickly and easily. This sucks.

### Actual Behavior

It feels like we're back in the nineties with some kind of memory optimization that is great for computers, but terrible for humans.

**Comment by mschipperheyn** [comment]
To be a bit more constructive. If it is relevant for Remix to have a flat list of routes, why not preprocess that list and convert a folder based structure to that list. Give people the option.

**Comment by brophdawg11** [comment]
This is a horribly rude, unconstructive, and uninformed issue.  File-system routing is very subjective and while you personally may not like the flat routes convention - the majority of Remix users prefer it and that is why it was chosen as the default in v2.

> Just give me back folders please

If you had read the [upgrade guide](https://remix.run/docs/en/main/start/v2#upgrading-without-changing-files), you would know that we did not force anyone to stop using the folder convention.  We went out of our way to extract the old convention and publish it as a package for folks like yourself who don't like the flat convention.

>  Give people the option

You can do anything you want with the [`routes`](https://remix.run/docs/en/main/start/v2#upgrading-without-changing-files) config.

There's are a bunch of popular community packages building on top of the `routes` configuration:

https://github.com/kiliman/remix-flat-routes
https://github.com/jacobparis-insiders/remix-custom-routes
https://github.com/brophdawg11/remix-json-routes

And if you don't like any of those, you are free to write your own and publish it for the community to benefit from.
