### ISSUE TITLE
Server-side rendering inserts NUL in cyrillic text

### ISSUE THREAD

**Issue by gigobyte** [remix-run/remix#8203]
### Reproduction

Cannot be reproduced. Unfortunately I'm creating this issue so that if anyone else encounters the same problem we can work on resolving it, I don't expect much to come out of it as of right now.

Simplified code:
```tsx
<input placeholder="Всички" />
```
In reality it's a [Mantine](https://mantine.dev/) TextInput component

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 45.54 GB / 62.61 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
  npmPackages:
    @remix-run/css-bundle: 2.3.1 => 2.3.1 
    @remix-run/dev: 2.3.1 => 2.3.1 
    @remix-run/eslint-config: 2.3.1 => 2.3.1 
    @remix-run/express: 2.3.1 => 2.3.1 
    @remix-run/node: 2.3.1 => 2.3.1 
    @remix-run/react: 2.3.1 => 2.3.1 
    @remix-run/server-runtime: 2.3.1 => 2.3.1 
    @remix-run/web-fetch: 4.4.1 => 4.4.1 
    vite: 5.0.2 => 5.0.2
```

### Used Package Manager

npm

### Expected Behavior

Cyrillic text is displayed without any intermediate characters.

### Actual Behavior

Remix sometimes returns a NUL character. When I revert the node version to 18.10.0 the server returns a NUL but then client-side React removes it. On node 20+ that does not happen. The NUL character is visible when cURLing the page and in the browser. I've been able to see the character in multiple browsers and devices, I'm also able to reproduce it locally by building the app with `remix dev` and in production.

cURL to a file:
![image](https://github.com/remix-run/remix/assets/8791446/03f97d48-f508-46f4-bde1-20cad406c6fa)

Browser:
![image](https://github.com/remix-run/remix/assets/8791446/14a2311e-4cdf-40eb-a54a-c6ca733227f8)

Devtools:
![image](https://github.com/remix-run/remix/assets/8791446/a1224ea3-7b13-48e2-b397-f1afbf07f4dd)

**Comment by gigobyte** [comment]
The issue got resolved on its own, I believe it was related to the Node version, cannot reproduce it on 21.4.0+

**Comment by tats-u** [comment]
@gigobyte If you use React 18.1–18.3, probably https://github.com/facebook/react/issues/31134#issuecomment-2416257221
