### ISSUE TITLE
[Feature]: docs website has an ugly scroll bar

### ISSUE THREAD

**Issue by Envov** [remix-run/remix#822]
### What is the new or updated feature that you are suggesting?

![image](https://user-images.githubusercontent.com/48908684/144202558-da818666-7cd3-490e-9738-7d66d82c59d8.png)

### Why should this feature be included?

Beauty is the primary productive force

**Comment by gautamkkk** [comment]
@ryanflorence @kentcdodds Is remix website and docs source code  open for contribution?

**Comment by MichaelDeBoey** [comment]
@gautamkkk The website currently isn't open sourced, but you can add contributions to the [docs folder](https://github.com/remix-run/remix/tree/main/docs) if you want to

**Comment by chaance** [comment]
Docs aesthetics are not a top priority at the moment, and we are likely to roll out a refreshed design in the near future anyway. Going to close the issue, but thanks for flagging!
