### ISSUE TITLE
Remix v-2.2.0 and above are not working smoothly with LazyLoading using npm package 'react-lazy-load-image-component' .

### ISSUE THREAD

**Issue by Anubhav-Joria** [remix-run/remix#8246]
### Reproduction

.

### System Info

```shell
System - Ubuntu 22
Browser - Chrome
```

### Used Package Manager

npm

### Expected Behavior

Actual image should be loaded when rendering for the first time instead of placeholder image.

### Actual Behavior

I was using 'react-lazy-load-image-component' for loading images in Remix. But after upgrading my Remix app to version 2.2.0. I faced issue in which when my page renders for the first time then it shows only the placeholder image of LazyLoadingComponent instead of actual image.
I tested and found that the issue arises when @remix-run/react is upgraded to v-2.2.0 or above, for below version it is working fine.

**Comment by brophdawg11** [comment]
Please provide a small reproduction of the issue so we can look into it

**Comment by Anubhav-Joria** [comment]
This is my JSX code in which i am wrapping my <img> inside LazyLoadComponent imported from  'react-lazy-load-image-component'.

<StyledDiv
      onClick={handleClick}
      outlined={outlined}
      size={size}
      height={height}
    >
      <LazyLoadComponent
        width="100%"
        height="100%"
        placeholder={
          <Grid
            container
            spacing={0}
            direction="column"
            alignItems="center"
            style={{ minHeight: "100%" }}
          >
            <Grid item xs={12}>
              <SvgIcon>
                <Image />
              </SvgIcon>
            </Grid>
            <Grid item xs={12}>
              <Typography color="inherit" variant="body2">
                Loading...
              </Typography>
            </Grid>
          </Grid>
        }
      >
        <img
          crossOrigin="anonymous"
          width="100%"
          height="100%"
          alt={`${title || ""} cover`}
          src={coverImgUrl}
        />
      </LazyLoadComponent>
    </StyledDiv>
    
Issue - Whenever i navigate to the page and render the image for the first time it only shows the placeholder UI of the  LazyLoadComponent.
The issue resolves when i scroll up and down or perform any actiivity.

This is the screenshot of the loading UI -
![Screenshot from 2023-12-09 21-15-42](https://github.com/remix-run/remix/assets/91547784/a3d26848-b754-4dd0-b5e5-42296e58ea68)

Please do let me know if u require anything else.
