### ISSUE TITLE
Defer does not work when navigating between child routes

### ISSUE THREAD

**Issue by andrelandgraf** [remix-run/remix#8256]
### Reproduction

I was able to reproduce it here: https://stackblitz.com/edit/remix-run-remix-fxk98l?file=app%2Froutes%2F%24id.tsx

- Navigate from `/` to `/a`. Notice that the deferred loader data is streamed and the fallback is shown (correct behavior).
- Navigate from `/a` to `/b`. Notice that the navigation only happens after the deferred data is resolved (incorrect behavior).

### System Info

```shell
Tried and reproduced it on Remix v2.0.0 and v2.3.1.
```

### Used Package Manager

npm

### Expected Behavior

Let's say we have an `$id` route, when navigating between different id parameters, (`/a` -> `/b`) then it should navigate to the new page once all non-deferred data has been loaded. The deferred loader data should be streamed, and the fallback be shown until resolved.

### Actual Behavior

When navigating between id parameters (`/a` -> `/b`), defer doesn't seem to work. It shows the old page (`/a`) until both the loader and deferred loader data are fetched.

**Comment by brophdawg11** [comment]
This is a common hiccup!  Remix is actually deferring properly here, but React's is re-using the Suspense boundary and not re-triggering the fallback since you're using the same component structure on /a and /b.  You can work around this by adding a key to the boundary to force react to render a fresh boundary and thus let the fallback re-appear:

```
<Suspense fallback="Loading deferred loader data..." key={useParams().id}>
```

**Comment by andrelandgraf** [comment]
Awesome, thanks for the explanation, @brophdawg11! Closing the ticket.

@ryanflorence, I think this could be worth documenting even though it's technically a React thing. Feels relevant to `defer` in Remix.

- https://remix.run/docs/en/main/guides/streaming
- https://remix.run/docs/en/main/guides/gotchas
