### ISSUE TITLE
Incorrect Command in Documentation

### ISSUE THREAD

**Issue by DenisJulio** [remix-run/remix#8257]
### Reproduction

clone the repository: https://github.com/DenisJulio/remix-tutorial
npm install
npm run dev

### System Info

```shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 1.00 GB / 7.45 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
npmPackages:
    @remix-run/dev: ^2.3.1 => 2.3.1 
    @remix-run/node: ^2.3.1 => 2.3.1 
    @remix-run/react: ^2.3.1 => 2.3.1 
    @remix-run/serve: ^2.3.1 => 2.3.1
```

### Used Package Manager

npm

### Expected Behavior

I was following the the tutorial in the Remix docs until the section: https://remix.run/docs/en/main/start/tutorial#the-contact-route-ui .
And entered the requested commands:

```
mkdir app/routes
touch app/routes/contacts.\$contactId.tsx
```
It was expected that I could continue to follow the tutorial.

### Actual Behavior

got the error:
```
❯ npm run dev                                                                   

> dev
> remix dev --manual


 💿  remix dev

 info  building...
✘ [ERROR] ENOENT: no such file or directory, open '/home/denisjulio/study/ts/remix-tutorial/app/routes/contacts./$contactId.tsx' [plugin browser-route-module]
```

**Obs.:**
In my try and error attempts, after removing the `\` in the file `contacts.\$contactId.tsx` the informed error disappeared and I was able to continue following the tutorial.

**Comment by DenisJulio** [comment]
I need to be fair, instead of pasting the commands through the command line I created the file in the file explorer, so the error could be totally on me for being a newbie, although I found it a bit confusing. I handle to you guys the decision to close the issue.

**Comment by brophdawg11** [comment]
Sorry this tripped you up!

> I created the file in the file explorer

Yeah - this would cause that issue.  The backslash is required in the CLI to avoid the dollar sign being interpolated as an environment variable on OSX/*nix systems.  I think the CLI is the most common case for this tutorial (given the `mkdir` and `touch` commands as well) so I think it's OK as it is.
