### ISSUE TITLE
🗺️  Server Bundles (formerly known as Server Builds (formerly known as Bundle Shredding))

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#8296]
- PR: https://github.com/remix-run/remix/pull/8332

- Cloudflare Pages
- Vercel build API

**Comment by B3nten** [comment]
netlify to round out the trifecta?

**Comment by pcattori** [comment]
https://github.com/remix-run/remix/pull/8596 removed `unstable_` prefix from server bundles, so this is just waiting for Vite to stabilize.

**Comment by markdalgleish** [comment]
Since this is primarily to support Vercel at the moment, I'd consider this open until the `adapter` API stabilises, but there's still a little more work left on that.
