### ISSUE TITLE
useFetcher load hangs with never ending loading state

### ISSUE THREAD

**Issue by KingSora** [remix-run/remix#8298]
### Reproduction

I've noticed in my fairly complex app that sometimes a `useFetcher` hangs with its `state` being `"loading"` forever or until a new action runs which revalidates it. After countless hours of debugging and searching I've found the issue.

**To reproduce it we need 3 things:**
- a fetcher which loads
- a fetcher which submits
- a revalidator

**Steps:**
1. the load fetcher runs
2. while the load fetcher runs the revalidator revalidates
3. while the load fetcher runs and the revalidator revalidates the submit fetcher submits
4. exactly when the submit fetcher submits the revalidators state is set to `idle`
5. wait until the submit fetchers state is set to `idle`
6. the load fetchers state is set to `loading` the whole time and will never change its state from this point on until a new action happens

**Here is an example on Stackblitz:**
https://stackblitz.com/edit/github-xk9p5y-tmtdq5?file=app%2Froutes%2Findex.tsx

In my app those things are happening in different components (auth modal etc.) which don't know about each other.

**Observations:**
If the revalidator doesn't run, the load fetcher doesn't hang.
Unfortunately not using the revalidator didn't fix the bug in my app, so there has to be another similar bug. I just wasn't able to reproduce it.

### System Info

```shell
Shouldn't matter
```

### Used Package Manager

npm

### Expected Behavior

The load fetcher should return some data eventually and set its state back to `idle` when that happens

### Actual Behavior

The load fetcher hangs forever or until a new action is triggered

**Comment by KingSora** [comment]
**Notes:**
For the bug in my app I could trace back the behavior to the following functions:
router.ts > handleFetcherAction > interruptActiveLoads > abortFetcher > controller.abort()

**Comment by the-rich-piana** [comment]
Also getting this issue with `    "@remix-run/react": "^2.3.1",`
`fetcher.submit` state stays `loading` `

**Comment by KingSora** [comment]
@brophdawg11 any news on this issue? I'm considering it somewhat crirical since the ux can really suffer from this. It should definitely get some attention.

**Comment by ItamarShDev** [comment]
Same here

**Comment by anhdd-kuro** [comment]
Same here, I think this is kind of critical issue and should get some attention too
But 5 months already !

**Comment by denbechka** [comment]
Caught similar behavior. But my case is a little different:
In this case I run `fetcher.submit`, after execution the loader of the route is called, but the result of this loader is redirect. After this action fetcher has a `loading` state

**Comment by knsakib** [comment]
Any update on this?

**Comment by darintanakaFN** [comment]
I'm seeing the same issue as well. Would be nice if we could get this fixed.

**Comment by stephanvebrian** [comment]
any update on this?

**Comment by defiled** [comment]
I'm seeing this too. Quite dissapointed because I was very excited about Remix otherwise, but have found the support to be lacking.

**Comment by Ian-inein** [comment]
Updates?

**Comment by brophdawg11** [comment]
Good news!  This was resolved by https://github.com/remix-run/react-router/pull/11839 which was released in RR 6.26.0 and included in [Remix 2.11](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v2110).

Here's an updated stackblitz showing the resolved issue on Remix 2.11.2: https://stackblitz.com/edit/github-xk9p5y-km2cyc
