### ISSUE TITLE
I can't use the twilio api

### ISSUE THREAD

**Issue by vawogbemi** [remix-run/remix#8331]
### Reproduction

import twilio from "twilio";

const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const client = twilio(accountSid, authToken);

client.messages
  .create({
      body: 'This is the ship that made the Kessel Run in fourteen parsecs?',
      from: process.env.TWILIO_NUMBER,
      to: '+16476675845'
  })
  .then((message: any) => console.log(message.sid));

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 866.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.0.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  npmPackages:
    @remix-run/css-bundle: ^2.0.1 => 2.0.1 
    @remix-run/dev: ^2.0.1 => 2.0.1 
    @remix-run/eslint-config: ^2.0.1 => 2.0.1 
    @remix-run/node: ^2.0.1 => 2.0.1 
    @remix-run/react: ^2.0.1 => 2.0.1 
    @remix-run/serve: ^2.0.1 => 2.0.1
```

### Used Package Manager

pnpm

### Expected Behavior

twilio api working

### Actual Behavior

when i first used require("twilio") i got a dynamic require error

i switched to import twilio and i got polyfill errors

I fixed the errors and now the remix just doesn't load the page that uses twilio. If I click a link to the messaging page, it just refreshes current page

**Comment by BryceBlankinship** [comment]
Where are you importing the package? If it has node dependencies it needs to be done in a filename.server.js file. That way remix can separate it into a server bundle and not the client one.

**Comment by vawogbemi** [comment]
@BryceBlankinship that make sense. I believe that’s what I’m missing. Do you have any examples of how I would implement a filename.server.js file for twilio?

**Comment by BryceBlankinship** [comment]
Plenty of examples in the official documentation

**Comment by vawogbemi** [comment]
So by: https://remix.run/docs/en/main/discussion/server-vs-client

Would the right step be to create a filename.server.ts and use require(“twilio) in the loader function of that file.

**Comment by BryceBlankinship** [comment]
No you should run whatever function you create in that file from a loader or action, you can require twilio as normal in the server file. You can think of the server file as an escape hatch to nodejs (along with actions and loaders), and everywhere else in remix code is the browser environment.

**Comment by brophdawg11** [comment]
It sounds like this is a dependency/`.server` issue.  I'm going to close it out for now but please re-open with a stackblitz reproduction if the above steps don't solve the issue (via https://remix.new)

**Comment by vawogbemi** [comment]
Yeah it was just an issue because I didn’t know how to use. Thank you so much @BryceBlankinship and @kiliman for helping me get it to work! ❤️
