### ISSUE TITLE
[Feature]: Pair down the template generated by create-remix to be minimal needed to get started

### ISSUE THREAD

**Issue by nareshbhatia** [remix-run/remix#835]
### What is the new or updated feature that you are suggesting?

Update create-remix to generate a template that is minimal and easy to understand.

### Why should this feature be included?

1. The template generated by create-remix is too large. I always have to delete a bunch of stuff and make tweaks to adapt to the specific requirements at hand.
2. Spinning up a new project becomes a chore. I would rather start with minimal "Hello world" app and add features as needed. Ideally the template should have just a home page with some text - no logos or other assets that I need to delete.
3. root.tsx is too complex and I don't understand every feature it is trying to provide (such as different layouts).

In general, it would be better to identify the various features that the current template is trying to demonstrate and introduce them via examples instead of overloading them in the template.

**Nice to have**

Document a way to extend the template. For example,
1. How to add other dependencies to package.json? (e.g. Prettier)
2. How to customize root.tsx and the index page?

**Comment by ryanflorence** [comment]
We intend to trim it down considerably soon, we just wanted it to serve as documentation for the launch.

In the mean time you can always make your own GitHub repo with the boilerplate you want and clone that instead of using `create-remix` :)

**Comment by machour** [comment]
The initial template is not simpler
