### ISSUE TITLE
`useFetcher()` should support URLs **not** defined in Remix 

### ISSUE THREAD

**Issue by Hansenq** [remix-run/remix#8363]
### Reproduction

I've provided a test that reproduces the issue. 
https://github.com/remix-run/remix/compare/main...Hansenq:remix-issue1:main

There are two tests defined: one tries to load a file using `fetch` and the other tries loading the same file using `useFetcher`. The former will succeed; the latter will error out. 

Trying to use `useFetcher` to make a network request to a URL that's valid, but not defined as a route in Remix will fail. This request will Error and take down the whole page. 

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 106.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1
  npmPackages:
    @remix-run/changelog-github: ^0.0.5 => 0.0.5
    @remix-run/web-fetch: ^4.4.2 => 4.4.2
    vite: ^5.0.0 => 5.0.0
```

### Used Package Manager

npm

### Expected Behavior

`useFetcher` should act like `fetch` and support fetching data from URLs, even if they're not defined as a route in Remix. The provided test demonstrates this with a static JSON file.

My use-case is because I have a reverse proxy in front of both my Remix server and a separate API server. My API server exposes additional URLs starting with `/api` (all other URLs go to Remix), and I'd like to use `useFetcher` to query URLs served at my API server. Right now I have to go back to `fetch`, which is not remix-y and less ergonomic.

### Actual Behavior

`useFetcher` throws an error and stops loading, taking the entire page with it. Here are the details of the error from the test: 

```
{
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/static/test.json"',
  error: 'Error: No route matches URL "/static/test.json"\n' +
    '    at be (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:2:8554)\n' +
    '    at Object.nm [as fetch] (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:1:18927)\n' +
    '    at Object.load (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:9:64401)\n' +
    '    at http://localhost:54686/build/routes/_index-LZR4UOCL.js:1:262\n' +
    '    at Si (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:9:24204)\n' +
    '    at _r (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:9:42230)\n' +
    '    at http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:9:40578\n' +
    '    at Ca (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:2:27298)\n' +
    '    at MessagePort.Ea (http://localhost:54686/build/_shared/chunk-2T5HRFH6.js:2:27689)'
}
```

**Comment by brophdawg11** [comment]
Remix's router is tightly coupled to it's routes and the loaders/actions so that it can handle automatic cancellation, revalidation, etc., so fetchers need to go through them.  Normally, this means just using a proxy route on the serrver, but in `2.4.0` we released the [Client Data APIs](https://remix.run/docs/en/main/guides/client-data) which let you do this proxying from the browser and own the `fetch` call:

```js
// app/routes/files.$.tsx
export function clientLoader({ params }) {
  return fetch(params["*"]);
}
```

```jsx
// Somewhere in your App
let fetcher = useFetcher();
fetcher.load('/files/static/test.json');
```
