### ISSUE TITLE
Pre-transform error: Server-only module referenced by client

### ISSUE THREAD

**Issue by gustavopch** [remix-run/remix#8367]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-ixwxbv?file=app%2Fentry.client.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/css-bundle: * => 2.4.1 
    @remix-run/dev: * => 2.4.1 
    @remix-run/node: * => 2.4.1 
    @remix-run/react: * => 2.4.1 
    @remix-run/serve: * => 2.4.1 
    vite: ^5.0.10 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

There should be no error when running with `npm run dev`, just like there's no error when running with `npm run build && npm run start`.

### Actual Behavior

This error occurs when the browser loads the page in development:
```sh
10:34:32 AM [vite] Internal server error: Server-only module referenced by client

    './monitoring.server.js' imported by 'app/monitoring.ts'

  * If all code in 'app/monitoring.ts' is server-only:

    Rename it to 'app/monitoring.server.ts'

  * Otherwise:

    - Keep client-safe code in 'app/monitoring.ts'
    - And move server-only code to a `.server` file
      e.g. 'app/monitoring.server.ts'

  If you have lots of `.server` files, try using
  a `.server` directory e.g. 'app/.server'

  For more, see https://remix.run/docs/en/main/future/vite#server-code-not-tree-shaken-in-development

  Plugin: vite:import-analysis
  File: /home/projects/remix-run-remix-ixwxbv/app/monitoring.ts
      at Context.resolveId (/home/projects/remix-run-remix-ixwxbv/node_modules/@remix-run/dev/dist/vite/plugin.js:685:13)
      at async Object.resolveId (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63675:32)
      at async TransformContext.resolve (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63380:23)
      at async normalizeUrl (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:61717:34)
      at async eval (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:61879:47)
      at async TransformContext.transform (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:61800:13)
      at async Object.transform (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63751:30)
      at async loadAndTransform (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:49432:29)
      at async viteTransformMiddleware (/home/projects/remix-run-remix-ixwxbv/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:59033:32) (x2)
```

# Extra context

What I'm trying to do is a monitoring module that exports a function that will have a different behavior depending on the environment, so I'm importing a `.server.ts` module inside a regular `.ts` module, but the import is dynamic and wrapped with `if (import.meta.env.SSR)`, so it's guaranteed it only happens on the server. Despite that, it causes this error saying the `.ts` module shouldn't reference a `.server.ts` module.

I believe it's a bug and not by design because it only happens when running with `npm run dev` – if I run with `npm run build && npm run start`, no error happens.

The issue may be related to Vite resolving the imports before stripping the code wrapped with `if (import.meta.env.SSR)`. I'd expect it to strip first. 🤔

# Relevant source code

https://github.com/remix-run/remix/blob/71f0e051d895807c349987655325c153903abad8/packages/remix-dev/vite/plugin.ts#L932-L1019

Pull request which introduced this behavior: https://github.com/remix-run/remix/pull/8267

People who wrote/reviewed the code and may know what's going on: @pcattori and @markdalgleish

Possibly related to: https://github.com/vitejs/vite/issues/5676

**Comment by gustavopch** [comment]
I'm using this plugin as a workaround and it seems to work well (adapted from https://github.com/vitejs/vite/issues/5676#issuecomment-968613433):
```diff
 export default defineConfig(({ command }) => ({
   plugins: [
+    {
+      name: 'import-meta-env-ssr',
+      enforce: 'pre',
+      transform(code, id, options) {
+        if (!options?.ssr && code.includes('import.meta.env.SSR')) {
+          return code.replace(/import.meta.env.SSR/g, 'false')
+        }
+      },
+    },
     remix({
       ignoredRouteFiles: ['**/.*'],
     }),
   ]
 })
```

**Comment by hi-ogawa** [comment]
> The issue may be related to Vite resolving the imports before stripping the code wrapped with `if (import.meta.env.SSR)`. I'd expect it to strip first

I think Vite/Esbuild currently doesn't do that during dev (https://github.com/vitejs/vite/blob/5684fcd8d27110d098b3e1c19d851f44251588f1/packages/vite/src/node/plugins/define.ts#L101-L106). So, Vite's import analysis will see `import('./monitoring.server.js')` and it runs various `resolveId` hooks including Remix plugin's `resolveId`, which then throws an error even though actual `import` won't happen on client code.

The reason why your `'import-meta-env-ssr'` plugin works is that, once it becomes `if (false)`, then default Vite/Esbuild transform (which runs before Vite's import analysis) will strip `import(...)` inside, so Vite's import analysis won't see that import anymore probably.

[Esbuild playground link](https://esbuild.github.io/try/#dAAwLjE5LjEwAABleHBvcnQgY29uc3QgbG9nID0gYXN5bmMgKG1lc3NhZ2UpID0+IHsKICBpZiAoZmFsc2UpIHsKICAgIGNvbnN0IHsgbG9nT25TZXJ2ZXIgfSA9IGF3YWl0IGltcG9ydCgnLi9tb25pdG9yaW5nLnNlcnZlci5qcycpOwogICAgbG9nT25TZXJ2ZXIobWVzc2FnZSk7CiAgfSBlbHNlIHsKICAgIGNvbnN0IHsgbG9nT25DbGllbnQgfSA9IGF3YWl0IGltcG9ydCgnLi9tb25pdG9yaW5nLmNsaWVudC5qcycpOwogICAgbG9nT25DbGllbnQobWVzc2FnZSk7CiAgfQp9Owo)

I think this is ultimately Vite's inconsistency issue, but probably this wasn't seen so critical on Vite itself because plugins `resolveId` won't throw in normal scenario.

--- 

> What I'm trying to do is a monitoring module that exports a function that will have a different behavior depending on the environment, so I'm importing a .server.ts module inside a regular .ts module, but the import is dynamic and wrapped with if (import.meta.env.SSR), so it's guaranteed it only happens on the server. Despite that, it causes this error saying the .ts module shouldn't reference a .server.ts module.

I think I would be missing the point of a whole `.server` convention, but if client/server code is already segregated via `improt.meta.env.SSR` mechanism, then you don't have to stick with `.server` convention anymore for this specific case?
For example, renaming to `monitoring.server.ts` to `monitoring-server.ts` would workaround this obviously...

**Comment by gustavopch** [comment]
> I think I would be missing the point of a whole .server convention, but if client/server code is already segregated via improt.meta.env.SSR mechanism, then you don't have to stick with .server convention anymore for this specific case?
For example, renaming to monitoring.server.ts to monitoring-server.ts would workaround this obviously...

In this minimal repro, it would work, but in the real project, the import chain is much more complex. I have many other `.server.ts` files which are also imported by other modules besides `app/monitoring.ts`, so some server code would certainly end up in the client bundle. The plugin workaround is safer.

---

I'm not sure if I'd be able to properly explain this problem in the Vite repo in a way that's agnostic to Remix, so I'll leave this to someone else if the maintainers consider this should be fixed there instead of here. And in that case, it would be helpful to mention this issue in the error message while Vite doesn't release a fix.

**Comment by pcattori** [comment]
@gustavopch check out https://github.com/pcattori/vite-env-only . we're going to recommend that as a "sharp knife" for users who have advanced use-cases like this

**Comment by pcattori** [comment]
Oh and here's a test example: https://github.com/remix-run/remix/blob/d34c7ce31740e758ed7d81f5fd54ebd424af20c0/integration/vite-dot-server-test.ts#L231-L293

**Comment by pcattori** [comment]
Docs now include reference to `vite-env-only`: https://remix.run/docs/en/main/future/vite#vite-env-only

And server-only error messages have been updated to point to the new docs: https://github.com/remix-run/remix/pull/8488
