### ISSUE TITLE
Refreshing the page in Dev mode not showing latest changes

### ISSUE THREAD

**Issue by ridwansameer** [remix-run/remix#8371]
### Reproduction

1. Clone a brand new Blues Stack template project
2. Build and run the dev server ( `yarn dev` ).
3. Change any line to see the changes reflected successfully with HMR Automatically
4. Refresh the page manually -> Now seeing older changes (Before the line was changed in step 3)

### System Info

```shell
Macbook Pro M1 Pro 2021
16GB RAM
macOS Monterey
Browsers: Arc, Microsoft Edge, Safari
```

### Used Package Manager

yarn

### Expected Behavior

When I refresh the page, I should see the updated changes

### Actual Behavior

When I refresh the page, I see the older changes

**Comment by VerioN1** [comment]
This is happening to me too, and also when I accidently save changes with exception, after fixing it - the server complains that the route doesn't exist anymore/

**Comment by ridwansameer** [comment]
Good to know I'm not the only one. Was very worried it was some combination of my machine/environment causing it.

**Comment by VerioN1** [comment]
Also here. very weird.

**Comment by brophdawg11** [comment]
Is this reproducible with a new Remix app via `npx create-remix`?  Or with other stacks such as the Indie Stack?  Unsure if this is a Remix issue or a Blues Stack issue and should be moved to that repository

**Comment by ridwansameer** [comment]
Oops! You are absolutely right. This does not happen with a brand new app from create-remix-app. My bad for posting this without giving that proper thought. Will close it now :)

**Comment by Qodestackr** [comment]
The development server will:
- Randomly decide to keep serving stale code even after changes
- Get completely stuck requiring manual restart
- Give you cryptic error messages about your route hierarchy
- Refuse to hot reload properly, especially with nested routes
- Take forever to rebuild when you touch anything loader-related

Lol delete node_modules and pray
