### ISSUE TITLE
Can't use `import.meta.env` in `server.ts` (also, app modules imported in `server.ts` aren't the same as when imported in `app/*`)

### ISSUE THREAD

**Issue by gustavopch** [remix-run/remix#8376]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-65dgzh?file=server.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: 2.4.1 => 2.4.1 
    @remix-run/express: 2.4.1 => 2.4.1 
    @remix-run/node: 2.4.1 => 2.4.1 
    @remix-run/react: 2.4.1 => 2.4.1 
    vite: ^5.0.10 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

Calling `logSomethingFromImportMetaEnv()` in `server.ts` should not crash.

### Actual Behavior

It crashes.

# Extra context

This is caused by a much deeper problem which is:
- when you import `app/lib.ts` from `app/root.tsx`, you're importing one module;
- when you import `app/lib.ts` from `server.ts`, you may think you're importing the same module, but it's really a **completely different module** (i.e. a "duplicate").

And this is not specific to Vite. The only thing specific to Vite here is the usage of `import.meta.env` (which I'm using to work around yet another problem as described in https://github.com/remix-run/remix/issues/8367). Even prior to Vite, I'd already see this issue manifest when I'd end up with mismatching instances where I'd expect singletons.

For example, suppose I have this file:
```ts
// app/queue.ts
export const queue = []
export const enqueue = value => queue.push(value)
```

And suppose I call `enqueue('foo')` in `server.ts` and `enqueue('bar')` in some other file inside the `app` folder, say `app/whataver.ts`. I'd expect I'd end up with a single queue with `['foo', 'bar']`. Instead, I'd end up with two different instances of `queue`, one containing `['foo']` (this one visible only to `server.ts`) and the other `['bar']` (this one visible to any file inside the `app` folder). As an analogy, as if `server.ts` were in a different dimension.

So... this issue manifests when reading `import.meta.env.SSR` because when it's read in "`server.ts`'s dimension", `import.meta.env` is `undefined` because in that dimension Vite wasn't there to set `import.meta.env`.

I hope this is clear enough. If it's not, maybe it'll be easier if we can discuss this synchronously in Discord first.

**Comment by pcattori** [comment]
If you want to use the same logic within Vite and outside of Vite, you'll need to handle the possibility of `import.meta.env` not existing yourself. For example:

```ts
const SSR = import.meta?.env?.SSR
if (SSR === undefined) return 'not in Vite'
return SSR ? 'Vite SSR=true' : 'Vite SSR=false'
```

In general, build tools and bundlers like Vite may choose to spin up additional processes, each with their own memory space. If you want to communicate across these processes/memory spaces (or with your own process like your custom server), you can use other mechanisms instead of relying on shared memory.

Given that we're running on top of Vite, there's nothing Remix can do to make these memory spaces shared as that outside the scope of a Vite plugin.
