### ISSUE TITLE
*.client.tsx error when importing with VITE Element type is invalid

### ISSUE THREAD

**Issue by Nedi11** [remix-run/remix#8378]
### Reproduction

https://stackblitz.com/~/github.com/Nedi11/remix-vite-spectrum

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 17.98 GB / 30.72 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.6.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.129
  npmPackages:
    @remix-run/css-bundle: 2.4.1 => 2.4.1 
    @remix-run/dev: 2.4.1 => 2.4.1 
    @remix-run/eslint-config: 2.4.1 => 2.4.1 
    @remix-run/express: 2.4.1 => 2.4.1 
    @remix-run/node: 2.4.1 => 2.4.1 
    @remix-run/react: 2.4.1 => 2.4.1 
    vite: 5.0.10 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

Import fro *.client.tsx import to work.

### Actual Behavior

Can\t import client only files when using vite. `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by hi-ogawa** [comment]
I don't think this is supposed to work (also on non Vite Remix) since your `Test` component is rendered during SSR but this is `undefined` on server due to `.client` file convention.

You could wrap with some sort of "client only" wrapper (https://remix.run/docs/en/main/guides/migrating-react-router-app#client-only-components) to avoid rendering on server:

https://stackblitz.com/edit/github-ax7u6h?file=app%2Froutes%2F_index.tsx

**Comment by Nedi11** [comment]
> I don't think this is supposed to work (also on non Vite Remix) since your `Test` component is rendered during SSR but this is `undefined` on server due to `.client` file convention.
> 
> You could wrap with some sort of "client only" wrapper (https://remix.run/docs/en/main/guides/migrating-react-router-app#client-only-components) to avoid rendering on server:
> 
> https://stackblitz.com/edit/github-ax7u6h?file=app%2Froutes%2F_index.tsx

It works on non vite remix, also it should work as described in docs

**Comment by Nedi11** [comment]
> I don't think this is supposed to work (also on non Vite Remix) since your `Test` component is rendered during SSR but this is `undefined` on server due to `.client` file convention.
> 
> You could wrap with some sort of "client only" wrapper (https://remix.run/docs/en/main/guides/migrating-react-router-app#client-only-components) to avoid rendering on server:
> 
> https://stackblitz.com/edit/github-ax7u6h?file=app%2Froutes%2F_index.tsx

I have used it without vite and it works (not sure of it was the latest version of remix though)

If .client doesnt work anymore this https://remix.run/docs/en/main/file-conventions/-client should be deleted

**Comment by hi-ogawa** [comment]
I tested with current non Vite Remix and I think I'm seeing the same error. Do you see there's something different in this repro?

https://stackblitz.com/edit/github-yjnyyh?file=app%2Froutes%2F_index.tsx

<details><summary>Reveal screenshot</summary>

![image](https://github.com/remix-run/remix/assets/4232207/15ae650b-6132-4bc7-9fd2-39e519f8d42e)

</details>

I started from opening https://stackblitz.com/github.com/remix-run/remix/tree/main/templates/remix which uses the template in https://github.com/remix-run/remix/tree/main/templates/remix.

**Comment by Nedi11** [comment]
> t non Vite Remix an

Upon second look you are right.
![image](https://github.com/remix-run/remix/assets/91092824/eaadadae-10c3-4144-b134-7c98c36b8349)

Closing this. Would be a nice feature though
