### ISSUE TITLE
TLS configuration ignored in remix dev server

### ISSUE THREAD

**Issue by kirjai** [remix-run/remix#8388]
### Reproduction

Unable to create repro for a dev server issue

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.35 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.volta/tools/image/node/18.18.2/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 9.8.1 - ~/.volta/tools/image/node/18.18.2/bin/npm
  Browsers:
    Brave Browser: 111.1.49.132
    Safari: 17.2.1
  npmPackages:
    @remix-run/css-bundle: ^2.4.0 => 2.4.0 
    @remix-run/dev: ^2.4.0 => 2.4.0 
    @remix-run/node: ^2.4.0 => 2.4.0 
    @remix-run/react: ^2.4.0 => 2.4.0 
    @remix-run/serve: ^2.4.0 => 2.4.0 
```

### Used Package Manager

npm

### Expected Behavior

providing `tlsKey` and `tlsCert` configuration either in `remix.config.js`
```js
dev: {
  tlsKey: "./key.pem",
  tlsCert: "./cert.pem",
},
```
or via the command line:
```sh
npm run dev -- --tls-key=./key.pem --tls-cert=./cert.pem
```
the expectation is that the dev server will be accessible via https.

### Actual Behavior

Unfortunately, as a result localhost isn't accessible via https still.

From what i could find in the code - the web socket dev server (usually running on port 3001) gets started with https, however the server that's started in `remix-serve` - seems to ignore the TLS configuration (and `REMIX_DEV_ORIGIN`).

i've found a manual workaround for those that are willing edit node_modules directly.
the file is `/node_modules/@remix-run/serve/dist/cli.js`. towards the end of the file - where `app.listen` calls are - we want to create an HTTPS server instead:
```diff
- let server = process.env.HOST ? app.listen(port, process.env.HOST, onListen) : app.listen(port, onListen);
+ let server = process.env.HOST ? app.listen(port, process.env.HOST, onListen) : https.createServer({
+    key: fs.readFileSync("./key.pem"),
+    cert: fs.readFileSync("./cert.pem"),
+  }, app).listen(port, onListen);
```
i personally don't use the `HOST` env var, so i'm fine with only editing the `else` part of the ternary.

in addition to that, you need to import the https module at the top of the file:
```js
var https = require('node:https');
```

happy to submit a PR, however I'm not convinced i've diagnosed the root issue correctly. perhaps only running https on the live reload server is intentional and the issue stems from elsewhere

**Comment by pcattori** [comment]
`remix-serve` is meant to be a minimal app server. To customize with TLS, you'll need your own server file like the one in the Express template.
