### ISSUE TITLE
useLoaderData error using createRemixStub after v2.1.0

### ISSUE THREAD

**Issue by romanmendez** [remix-run/remix#8403]
### Reproduction

I'm using `createRemixStub` to mock the `loader` in a route I'm testing using Vitest. I'm getting this error when running the test: 

`Error: useLoaderData must be used within a data router.  See https://reactrouter.com/routers/picking-a-router.`

This only happens after Remix v2.1.0. In version 2.1.0 the test runs without errors.

The error is caused by adding `useLoaderData` to the default export component of the route being tested. Here is an example of a component that will cause this error:
```ts
import { json } from '@remix-run/node'
import { useLoaderData } from '@remix-run/react'

export async function loader() {
	return json({ greeting: 'Hello, world!' })
}

export default function ProfileRoute() {
	const data = useLoaderData<typeof loader>()
	return <output>{data.greeting}</output>
}
```

And an example test that will trigger the error:
```ts
/**
 * @vitest-environment jsdom
 */
import { json } from '@remix-run/node'
import { createRemixStub } from '@remix-run/testing'
import { render, screen } from '@testing-library/react'
import { test } from 'vitest'
import { default as Greeting, type loader } from './$username.tsx'

test('The user profile when not logged in as self', async () => {
	const App = createRemixStub([
		{
			path: '/',
			Component: Greeting,
			loader(): Awaited<ReturnType<typeof loader>> {
				return json({
					greeting: 'Hello, world!',
				})
			},
		},
	])

	render(<App />)

	await screen.findByRole('status')
})
```

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M2
    Memory: 3.28 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.129
    Safari: 17.1.2
  npmPackages:
    @remix-run/css-bundle: ^2.1.0 => 2.4.1
    @remix-run/dev: 2.1.0 => 2.1.0
    @remix-run/eslint-config: 2.1.0 => 2.1.0
    @remix-run/express: ^2.1.0 => 2.4.1
    @remix-run/node: ^2.1.0 => 2.4.1
    @remix-run/react: ^2.1.0 => 2.4.1
    @remix-run/serve: ^2.1.0 => 2.4.1
    @remix-run/testing: 2.1.0 => 2.1.0
```

### Used Package Manager

npm

### Expected Behavior

`createRemixStub` should mock the `loader` and run the test without error.

### Actual Behavior

When `useLoaderData` is added to a component that is being mocked by `createRemixStub`, the test will throw: 
`Error: useLoaderData must be used within a data router.  See https://reactrouter.com/routers/picking-a-router.`

**Comment by kiliman** [comment]
I think you need to add the prop `initialEntries`

```ts
await render(<App initialEntries={['/']} />)
``` 

https://github.com/kiliman/remix-vite-template/blob/a98f77813e009757da2e2d7c03f5c499da324c3a/app/routes/counter.test.tsx#L16C9-L16C9

**Comment by romanmendez** [comment]
@kiliman only if the entry path is something other than root. The test works as soon as I take the `useLoaderData` hook out of the component, so I doubt it has anything to do with the path.

**Comment by chinanderm** [comment]
I, too, am experiencing this issue after upgrading to latest (v2.4.1).

**Comment by chinanderm** [comment]
Follow up: This ended up being due to an outdated version of `react-router-dom` in `node_modules`. I have a monorepo that leverages a single root `package.json` and has several Remix apps and one SPA app that uses `react-router-dom` directly, which is included in `package.json`. When upgrading to Remix v2.4.1, I didn't also update `react-router-dom` to match the version used by `remix`, so there was some dependency resolution funny business happening under the hood.

**Comment by brophdawg11** [comment]
@romanmendez This type of `must be used within a data router` error is almost always caused by duplicate versions of `react-router` as mentioned by @chinanderm.  Can you run `npm ls react-router-dom` and see if you have duplicate versions installed?  If you have `react-router-dom` in your `package.json`, it needs to be the same version used internally by `@remix-run/*` packages.

**Comment by romanmendez** [comment]
@brophdawg11 you're right! The issue was I was updating my Remix `dependencies` without updating my `devDependencies` which resulted in duplication of `react-router-dom` in the `@remix-run/testing` package:
<img width="702" alt="Screenshot 2024-01-04 at 08 47 53" src="https://github.com/remix-run/remix/assets/25204862/dece442b-5903-44e7-841c-e78b765603bb">

Updating all Remix packages to the same version fix the issue. Thank you!

**Comment by brophdawg11** [comment]
I forgot to do that enough times that I made an [`upgrade-remix`](https://github.com/brophdawg11/upgrade-remix) package to do it 😆 

```sh
> npx upgrade-remix 2.4.1
```

**Comment by HenriqueLimas** [comment]
@brophdawg11 shouldn't remix-run be a `peerDependency` of `remix-run/testing` so the script is not needed? Or at least remove the exact version and use `^` instead.
