### ISSUE TITLE
[Bug]: parseFrontMatter broke API and needs to be updated

### ISSUE THREAD

**Issue by movingelectrons** [remix-run/remix#841]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### Steps to Reproduce

Hi!  Love remix so far!  Following the tutorial, something changed recently in the yaml parser, something about using parse instead of safeParse, or something like that... anyways the fix is to do this:

      const { attributes } = parseFrontMatter(
        file.toString(), {allowUnsafe: true}
      )

instead of

      const { attributes } = parseFrontMatter(
        file.toString()
      )

didn't take me too long to figure it out, but some other noob like myself might run into this problem and give up on remix, and that might be a bad thing!  Might want to update the tutorial https://remix.run/docs/en/v1/tutorials/blog#creating-the-project

💿 Update getPosts to read from the file system 

in that section.  Thanks again for creating remix!!!

### Expected Behavior

not to error out when loading /posts

### Actual Behavior

errors out when loading /posts

**Comment by meehawk** [comment]
@jacob-ebey can I take this issue up? Though I wanted to point out that I tried the remix tutorial and haven't faced this issue yet

**Comment by machour** [comment]
Tracked in #2067
