### ISSUE TITLE
Docs Quick Start - Error thrown during Build and Run step

### ISSUE THREAD

**Issue by Matthew-Mallimo** [remix-run/remix#8456]
### Reproduction

Follow the [Quick Start](https://remix.run/docs/en/main/start/quickstart) guide.

Once you hit the [Build and Run](https://remix.run/docs/en/main/start/quickstart#build-and-run) step and you run the 
`npx remix-serve build/index.js` command, it fails with:

```
Error: Dev server origin not set
```

which is thrown from here
https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/dev.ts#L5

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 390.29 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 16.6
  npmPackages:
    @remix-run/dev: ^2.4.1 => 2.4.1 
    @remix-run/node: ^2.4.1 => 2.4.1 
    @remix-run/react: ^2.4.1 => 2.4.1 
    @remix-run/serve: ^2.4.1 => 2.4.1
```

### Used Package Manager

npm

### Expected Behavior

I would expect the server to startup properly.

### Actual Behavior

The server fails to start up with an error 
```
Error: Dev server origin not set
```

**Comment by brophdawg11** [comment]
I just followed the quick start steps and I'm unable to reproduce this with `npx remix-serve build/index.js`

I _can_ get this to happen with `NODE_ENV=development npx remix-serve build/index.js` since in dev mode `remix-serve` is expecting a dev server instance.  `NODE_ENV=development` is intended to be used via `npx remix dev` - not directly via `remix-serve`.

Can you check if you accidentally have `NODE_ENV` set in your environment?

**Comment by Matthew-Mallimo** [comment]
> I just followed the quick start steps and I'm unable to reproduce this with `npx remix-serve build/index.js`
> 
> I _can_ get this to happen with `NODE_ENV=development npx remix-serve build/index.js` since in dev mode `remix-serve` is expecting a dev server instance. `NODE_ENV=development` is intended to be used via `npx remix dev` - not directly via `remix-serve`.
> 
> Can you check if you accidentally have `NODE_ENV` set in your environment?

Yes I definitely did have `NODE_ENV=development`, and removing it does fix the issue! 

Maybe a small note in the code snippet for the serve command could mention that setting `NODE_ENV=development` isn't suggested would help

**Comment by brophdawg11** [comment]
If we see enough folks run into this I think we'd consider that, but so far I don't think it's been a common hiccup so going to wait and see.  Thanks for confirming that was the root issue!
