### ISSUE TITLE
`dev/server-build.ts` is missing `isSpaMode`

### ISSUE THREAD

**Issue by threepointone** [remix-run/remix#8497]
### Reproduction

I'm trying to update an existing 2.4.1 project to 2.5.0, and I see a typecheck failure. 
<img width="971" alt="image" src="https://github.com/remix-run/remix/assets/18808/56259bed-d40c-41e6-a2ad-5a2a1b83a31d">

I think it's because in this file https://github.com/remix-run/remix/blob/main/packages/remix-dev/server-build.ts, you need to add 
```ts
export const isSpaMode:boolean = undefined!;
```

My workaround is to rewrite my code like so: 

<img width="552" alt="image" src="https://github.com/remix-run/remix/assets/18808/ead57627-4397-466f-98b0-3fc4267873c0">

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 147.50 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.volta/tools/image/node/18.19.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/node/18.19.0/bin/npm
    pnpm: 8.6.12 - ~/.volta/bin/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun
  Browsers:
    Edge: 120.0.2210.133
    Safari: 17.1
```

### Used Package Manager

npm

### Expected Behavior

Typescript shouldn't complain with a standard template/starter kit. 

### Actual Behavior

Oh I went into detail in the reproduction. Typechecking fails.

**Comment by brophdawg11** [comment]
yeah the workaround mentioned above or `@ts-expect-error` are both fine for now until #8492 goes out next release. 
 there aren't any functional issues since these types of server apps aren't using spa mode
