### ISSUE TITLE
<Link> to anchor destroys action data

### ISSUE THREAD

**Issue by unleashy** [remix-run/remix#8512]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-qxplpu?file=app%2Froutes%2F_index.tsx

1. Submit the form with any text (or none, it doesn't matter)
2. `text: foobar` should show up, as per the action data
3. Click "focus on input". It's a `<Link to="#input">`, very simple.
4. `text: foobar` should disappear; the input probably won’t get focused

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 12.52 GB / 23.85 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 120.0.6099.217
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/dev: ^2.5.0 => 2.5.0
    @remix-run/node: ^2.5.0 => 2.5.0
    @remix-run/react: ^2.5.0 => 2.5.0
    @remix-run/serve: ^2.5.0 => 2.5.0
    vite: ^5.0.11 => 5.0.11
```

### Used Package Manager

yarn

### Expected Behavior

The action data should not change. The link should move focus to the input, as normal &lt;a href="#anchor"> does.

### Actual Behavior

The action data gets erased. Focus does not move to the input.

**Comment by Gauravjadhav22** [comment]
hi @unleashy , i would like to work on this, kindly assign

**Comment by kiliman** [comment]
Action data is only valid after the return of the action. If you want it to persist, you'll need to either `useState` or return the value from your loader.

As for `<Link to="#hash">`, links are meant for routes. Use a standard anchor `<a href="#hash">` for focus.

**Comment by unleashy** [comment]
Ah, `<a href="#hash">` does work, thank you 😅 I think I ended up overfocusing on using Link components.
