### ISSUE TITLE
ENV variable cannot be read on production build

### ISSUE THREAD

**Issue by erickhilda** [remix-run/remix#8515]
### Reproduction/Description

Hi I am trying to use remix for my new project by using indie stack as a starter and since I have my own backend already, I tried to remove all the file and fucntion relate to prisma and sqlite db. I keep the session storage mechanism to store my access-token. it is running smoothly during development, but I get this kind of error while trying to run a production. thank you.
<img width="1301" alt="Screenshot 2024-01-15 at 12 12 38" src="https://github.com/remix-run/remix/assets/33190658/271f103c-88b8-416f-8465-c56aa95794e3">

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 66.34 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.10.2 - ~/Library/pnpm/pnpm
    bun: 1.0.17 - /opt/homebrew/bin/bun
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @remix-run/css-bundle: ^2.4.0 => 2.4.0 
    @remix-run/dev: ^2.4.0 => 2.4.0 
    @remix-run/node: ^2.4.0 => 2.4.0 
    @remix-run/react: ^2.4.0 => 2.4.0 
    @remix-run/serve: ^2.4.0 => 2.4.0 
    vite: ^4.5.0 => 4.5.1
```

### Used Package Manager

pnpm

### Expected Behavior

The environment variable SESSION_SECRET to be available.

### Actual Behavior

The environment variable SESSION_SECRET is undefined.

**Comment by kiliman** [comment]
How are you defining your environment variables in production? Remix loads `.env` files only in development. It expects you to set up the variables on your hosting provider for production. 

For example, Fly.io uses `fly secrets` https://fly.io/docs/reference/secrets/

**Comment by erickhilda** [comment]
Hi @kiliman thank for the answer. It was oversight on my side, I was expecting that remix would load env from the .env file that was define on the root of the project. turn out it is need to be define on the on the hosting provider.
I will closed this as it is not a bug from remix side.
Thank you.
