### ISSUE TITLE
Collision of versions @testing-library/dom

### ISSUE THREAD

**Issue by Afsoon** [remix-run/remix#8516]
### Reproduction

Clone the repo, install the dependencies and launch the only test to see the behavior https://github.com/Afsoon/warning-remix-act

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 79.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.local/share/rtx/installs/node/20.2.0/bin/node
    npm: 9.6.6 - ~/.local/share/rtx/installs/node/20.2.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 16.3
  npmPackages:
    @remix-run/css-bundle: ^2.4.1 => 2.5.0
    @remix-run/dev: ^2.4.1 => 2.5.0
    @remix-run/node: ^2.4.1 => 2.5.0
    @remix-run/react: ^2.4.1 => 2.5.0
    @remix-run/serve: ^2.4.1 => 2.5.0
    @remix-run/testing: ^2.4.1 => 2.5.0
    vite: ^5.0.10 => 5.0.11
```

### Used Package Manager

npm

### Expected Behavior

Not see the warning:
`Warning: An update to RouterProvider inside a test was not wrapped in act(...).`

### Actual Behavior

If you `await` for a user event action using version 14, it will log that you have to wrap the code in `act`, which isn't required. 

After an investigation, we found the problem is the project has installed two different versions of `@testing-library/dom.` One version comes from `RTL-react`. 

The problem comes when you go to the [remix eslint package](https://github.com/remix-run/remix/blob/main/packages/remix-eslint-config/package.json#L36) and see you are using `eslint-plugin-jest-dom` v4. This version has `@testing-library/dom` set as a dependency instead of a peer dependency, so we are installing an old version that doesn't work with React 18. 

The fix is easy as it's upgrading the version to 5, as they had already fixed it: https://github.com/testing-library/eslint-plugin-jest-dom/issues/294. I can submit a PR.

**Comment by brophdawg11** [comment]
Can this be resolved with overrides?  It's hard to know if performing a major update to a dependency of `@remix-run/eslint-config` will pose unintended breaking changes on consumer apps.  We are planning to deprecate the `@remix-run/eslint-config` package in favor of much simpler eslint starter setups using industry "recommended" presets (see https://github.com/remix-run/remix/blob/main/templates/remix/.eslintrc.cjs).  So I don't know that performing a major dep update is something we want to undertake.

**Comment by silvenon** [comment]
I would also prefer to wait for simpler ESLint configs. @Afsoon in your repo I'm only getting the error for the missing `@testing-library/user-event`, after that I'm only getting the warning for deprecated CJS Vite. I'm not seeing the particular `act` warning you mentioned.

Btw, @brophdawg11 in the config you linked this override only targets `.js` ESLint config files:

```js
{
  files: [".eslintrc.js"],
  env: {
    node: true,
  },
},
```

I assume the target is the configuration file itself, and no nested ones, but this one is `.cjs`. In this case I recommend using `/* eslint-env node */` instead of this override, that way you don't have to worry about the extension.

**Comment by brophdawg11** [comment]
> I assume the target is the configuration file itself, and no nested ones, but this one is .cjs. In this case I recommend using `/* eslint-env node */` at the top of the file instead of this override, that way you don't have to worry about the file extension.

I think I could get on board with that or just a more flexible files glob like `['.eslintrc.[cm]?js'` - do you want to open a PR?  I'm not sure if I prefer one or the other personally.
