### ISSUE TITLE
[Bug]: CSS-in-JS is unable to style the error/catch handling component

### ISSUE THREAD

**Issue by vcnc-hex** [remix-run/remix#852]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

^1.0.6

### Steps to Reproduce

1. Go to [Codesandbox](https://codesandbox.io/s/charming-tharp-pxqpy-pxqpy) and run it.
2. Click to `GO TO 404 page` button. And notice that the button has a red color.
3.  Because the /404-unkown page doesn't exist, it renders the CatchBoundary component containing the button component. And notice, the button should be the same as the one used on the index page. (e.g. red color button)

### Expected Behavior

The red button should appear on the /404-unkown page.

### Actual Behavior

A button that is not styled red backgroud color.

**Comment by vcnc-hex** [comment]
IMO, this problem occurs because the root error handler component [unmount and mount](https://remix.run/docs/en/v1/guides/errors#root-error-boundary) it again. To solve the problem, it seems that we need to make the `css` created through `ServerStyleSheet` available to the client as well, or there must be a component that wraps the error handler and the root component in common way.

**Comment by lvauvillier** [comment]
@pixelstew I posted a workaround here (material-ui / emotion) : https://github.com/mui-org/material-ui/issues/30436#issuecomment-1003339715
