### ISSUE TITLE
[Bug]: Remix Quickstart extra credit | default form values aren't matching returned value from useLoaderData

### ISSUE THREAD

**Issue by bradgarropy** [remix-run/remix#854]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

1. `npm run dev`
2. Navigate to `/admin`
3. Click on `90s Mixtape`
4. Note the default field values
5. Click on `My First Post`
6. Note that the default field values did not change

### Expected Behavior

I would expect the default values for `slug`, `title`, and `markdown` would change based on what nested route was selected.

### Actual Behavior

The default values remain the same, despite the proper return of the `useLoaderData` hook.

**Comment by bradgarropy** [comment]
[Video](https://youtu.be/ptJI-EC1iOo)
[GitHub repository](https://github.com/bradgarropy/remix-quickstart)
[Hosted on Render](https://remix-quickstart.onrender.com)

**Comment by bradgarropy** [comment]
Thanks to @Girish21, he [explained](https://discord.com/channels/770287896669978684/771068344320786452/916001985801617451) to me what was going on. I'll summarize in my own words.

Changing the `defaultValue` attribute on an `input` or `textarea` will not cause React to rerender. In order to cause a rerender, we can add a `key` prop to the `form`. Then, any changes to the value passed to `key` will rerender the entire `form`.

```jsx
<Form key={post.slug} method="post">
  ...
</Form>
```

**Comment by coderfin** [comment]
I ran into the very same issue.  Nice little tidbit to learn.

**Comment by kevin4dhd** [comment]
you must specify in the start tutorial, I'm new to react and remix, I had to get here to know that I had to put a key form in the tex

**Comment by STAYWICKED** [comment]
Bro help
