### ISSUE TITLE
file upload not working on 2.5.0 remix

### ISSUE THREAD

**Issue by tenkus47** [remix-run/remix#8544]
### Reproduction

i upgraded remix to the latest version which is 2.5.0 now when i try to upload a file  and get it in actions. the below error message is coming.
ReferenceError: File is not defined     at <instance_members_initializer> (D:\work\monlam_ai_tools\node_modules\@remix-run\node\dist\upload\fileUploadHandler.js:143:20)

### System Info

```shell
File
```

### Used Package Manager

npm

### Expected Behavior

can u help

### Actual Behavior

file should get uploaded

**Comment by brophdawg11** [comment]
Can you provide a reproduction of the issue?

**Comment by binajmen** [comment]
I have a similar issue:
```
ReferenceError: File is not defined
    at /Users/binajmen/.../node_modules/@remix-run/server-runtime/dist/upload/memoryUploadHandler.js:44:7
```

**Comment by binajmen** [comment]
Hi @brophdawg11,

I reduced my project to a minimum reproduction:
https://github.com/binajmen/bug-remix-file-upload

**Comment by tenkus47** [comment]
sorry i couldnt reproduce the error because if I make a new app and try it it works . but I get the same error like @binajmen on old project even after upgrading remix to latest. any updates? on the issue?
thank you

**Comment by kiliman** [comment]
Make sure that ALL your Remix packages are the same version.

@brophdawg11 created a script to properly update Remix.
```bash
npx upgrade-remix
```
https://npmjs.com/package/upgrade-remix

**Comment by brophdawg11** [comment]
@binajmen It looks like your project isn't calling [`installGlobals()`](https://remix.run/docs/en/main/other-api/node#polyfills) to install the `File` polyfill.  Adding that to the top of your express server fixes the issue 👍 

@tenkus47 I believe this is likely your issue as well - if you are using a custom server please ensure you're installing the polyfills in your `server.js/ts` file

**Comment by imrostom** [comment]
`import { Form, useSubmit } from "@remix-run/react";

import {
  json,
  unstable_composeUploadHandlers as composeUploadHandlers,
  unstable_createFileUploadHandler as createFileUploadHandler,
  unstable_createMemoryUploadHandler as createMemoryUploadHandler,
  unstable_parseMultipartFormData as parseMultipartFormData,
} from "@remix-run/node";
import { Page } from "@shopify/polaris";


export async function action({ params, request }) {

  const uploadHandler = composeUploadHandlers(
    createFileUploadHandler({
      directory: "public/uploads",
      maxPartSize: 300000000,
    }),
    createMemoryUploadHandler(),
  );
  const formData = await parseMultipartFormData(request, uploadHandler);

  const image = formData.get("image");
  console.log(image)
  if (!image || typeof image === "string") {
    return json({ error: "something wrong", imgSrc: null });
  }


  return json({ status: false, message: "Please provide valid user data." });
}

export default function Index() {
  const submit = useSubmit();

  const handleFileUpload = (e) => {
    console.log(e.currentTarget.files);
    const formData = new FormData();
    formData.append("image", e.currentTarget.files[0]);
    submit(formData, { method: "post", encType: "multipart/form-data" });

  }

  return (
    <Page title="File Upload">
      <div className="container">
        <div className="MainArea">
          <div className="row">
            <div className="contact-form">
              <Form method="post" encType="multipart/form-data">
                <input type="file" name="image" id="image" onChange={handleFileUpload} />
              </Form>
            </div>
          </div>
        </div>
      </div>
    </Page>
  );
}
`

If also face this type of issue. my error code is `15:18:33 │ remix      │ ReferenceError: File is not defined
15:18:33 │ remix      │     at <instance_members_initializer> (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:143:20)
15:18:33 │ remix      │     at new NodeOnDiskFile (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:144:14)
15:18:33 │ remix      │     at /Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:131:12
15:18:33 │ remix      │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
15:18:33 │ remix      │     at async /Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/dist/formData.js:21:19
15:18:33 │ remix      │     at async Module.parseMultipartFormData (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/dist/formData.js:51:17)
15:18:33 │ remix      │     at async action (/Users/rostom/Shopify/trustsync-remix/app/routes/app.upload.jsx:22:20)
15:18:33 │ remix      │     at async Object.callRouteActionRR (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
15:18:33 │ remix      │     at async callLoaderOrAction (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/node_modules/@remix-run/router/dist/router.cjs.js:4166:16)
15:18:33 │ remix      │     at async submit (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/node_modules/@remix-run/router/dist/router.cjs.js:3520:16)
15:18:33 │ remix      │     at async queryImpl (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/node_modules/@remix-run/router/dist/router.cjs.js:3478:22)
15:18:33 │ remix      │     at async Object.queryRoute (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/node_modules/@remix-run/router/dist/router.cjs.js:3447:18)
15:18:33 │ remix      │     at async handleDataRequestRR (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/dist/server.js:122:20)
15:18:33 │ remix      │     at async requestHandler (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/server-runtime/dist/server.js:94:18)
15:18:33 │ remix      │     at async nodeHandler (/Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/dev/dist/vite/plugin.js:837:27)
15:18:33 │ remix      │     at async /Users/rostom/Shopify/trustsync-remix/node_modules/@remix-run/dev/dist/vite/plugin.js:840:15
`

**Comment by brophdawg11** [comment]
Could you provide a reproduction?

**Comment by k1sul1** [comment]
No repro from me either, but chiming in that I'm also suddenly seeing an influx of this error. I've used to getting it in local development every now and then but I've not seen it happen in a hosted environment (Vercel).

I tried submitting a form _without_ a file selected for upload and received `File is not defined` about 15 times in a row. I have a feeling that this somehow relates to the dev server. 

For what it's worth, we're on 2.8.1 and this is what our upload handler looks like>: 

```
const uploadHandler: UploadHandler = unstable_composeUploadHandlers(
  createS3UploadHandler('img'),
  unstable_createMemoryUploadHandler()
);

const formData = await unstable_parseMultipartFormData(
  request,
  uploadHandler
);
```

in which createS3UploadHandler streams the file to S3 and returns us some data in the form of a JSON blob.

**Comment by imrostom** [comment]
> Could you provide a reproduction?

please check this file, https://github.com/imrostom/shopify-image-upload/blob/main/app/routes/app.upload.jsx

i think it's shopify.server releted problem .

**Comment by brophdawg11** [comment]
If someone can provide a minimal reproduction of the issue we'd be happy to take a look

**Comment by imrostom** [comment]
> If someone can provide a minimal reproduction of the issue we'd be happy to take a look

Issue solved after adding `installGlobals();` in shopify.server.js

**Comment by starkblaze01** [comment]
> > If someone can provide a minimal reproduction of the issue we'd be happy to take a look
> 
> Issue solved after adding `installGlobals();` in shopify.server.js

Thanks this worked me also, the error was happening in production environment for me. When I tried running:
`npm dev` --> no error,
`cross-env NODE_ENV=production npm start` --> Upload error: ReferenceError: File is not defined
