### ISSUE TITLE
Vite plugin fails to import module for unknown reason

### ISSUE THREAD

**Issue by PatrykWalach** [remix-run/remix#8567]
### Reproduction

Failing with plugin:
https://stackblitz.com/edit/vitejs-vite-nsdsfs?file=app%2Froot.jsx
Works in pure vite:
https://stackblitz.com/edit/vitejs-vite-oji9ev?file=main.js

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: ^2.5.1 => 2.5.1 
    @remix-run/node: ^2.5.1 => 2.5.1 
    @remix-run/react: ^2.5.1 => 2.5.1 
    vite: ^5.0.11 => 5.0.12
```

### Used Package Manager

npm

### Expected Behavior

I'd expect `rescript/lib/es6/js_promise2.js` to get imported or receive a meaningful error  

### Actual Behavior

I receive generic error
```
15:24:28 [vite] Error when evaluating SSR module /app/root.jsx: failed to import "rescript/lib/es6/js_promise2.js"
|- undefined

15:24:28 [vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "/app/root.jsx"
|- undefined
```

**Comment by pcattori** [comment]
I'm not super familiar with ReScript, but it'd be worth trying to replicate this with vanilla Vite running an SSR build. By default,  Vite only builds for the client, whereas Remix uses Vite to build a client _and_ a server build, so comparing vanilla Vite w/o SSR to Remix is not as insightful as comparing Vite + SSR to Remix.

**Comment by hi-ogawa** [comment]
Vitest also has a similar issue with rescript https://github.com/vitest-dev/vitest/issues/4635 and it's likely that this is better handled on rescript side https://github.com/rescript-lang/rescript-compiler/issues/6503

**Comment by pcattori** [comment]
Closing as this looks like a general ReScript + Vite issue and unrelated to Remix. If any parts of this relate directly to Remix, we can open this issue back up.
