### ISSUE TITLE
Remix executes vite plugins twice

### ISSUE THREAD

**Issue by sdorra** [remix-run/remix#8578]
### Reproduction

* [StackBlitz](https://stackblitz.com/github/sdorra/remix-vite-plugin?file=vite.config.ts)
* [GitHub repository](https://github.com/sdorrra/remix-vite-plugin)

I'm trying to write a vite plugin to build a Remix integration for [Content Collections](https://www.content-collections.dev), but it looks like that remix executes vite plugins twice. The example above prints some messages to the console, as you can see all messages are printed twice.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 16.57 GB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 21.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.1 - /opt/homebrew/bin/pnpm
    Watchman: 2024.01.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.5.1 => 2.5.1
    @remix-run/node: ^2.5.1 => 2.5.1
    @remix-run/react: ^2.5.1 => 2.5.1
    @remix-run/serve: ^2.5.1 => 2.5.1
    vite: ^5.0.0 => 5.0.12
```

### Used Package Manager

pnpm

### Expected Behavior

Vite plugins are only executed once. The example above should only print:

```text
vsp: create plugin
vsp: configResolved
vsp: configureServer
vsp: buildStart
```

on `pnpm run dev`.

### Actual Behavior

Vite plugins are executed twice. The example above prints:

```text
vsp: create plugin
vsp: configResolved
vsp: create plugin
vsp: configResolved
vsp: configureServer
vsp: buildStart
vsp: configureServer
vsp: buildStart
```

on `pnpm run dev`.

**Comment by pcattori** [comment]
This is expected. Remix runs Vite twice: once for the client and once for the server. This will be true for any SSR framework built on top of Vite, not just Remix. You can use [Vite's `ssr` option for plugins](https://vitejs.dev/guide/ssr.html#ssr-specific-plugin-logic) to distinguish between the two.

If you use the server bundles feature, you may get even _more_ invocations of Vite as each bundle is a separate Vite compilation.
