### ISSUE TITLE
Loading handlers from Drizzle server schemas into a route results in "Server-only module referenced by client"

### ISSUE THREAD

**Issue by 684efs3** [remix-run/remix#8608]
### Reproduction

I am using Drizzle ORM with Remix+Vite. I have a user.schema.js file with a handler of say getUserById(). If I use this in a regular route, inside the loader, I get a server-only module referenced by client error.

### System Info

```shell
Remix 2.5.1 with vite 5.0.12. drizzle-orm 0.29.3 and planetscale/database 1.14.0
```

### Used Package Manager

yarn

### Expected Behavior

Do not expect to have issues importing user.schema.js (from drizzle) into a regular route. 

### Actual Behavior

Getting vite error:

```
[vite] Internal server error: Server-only module referenced by client

 Remix automatically removes server-code from these exports:
    `loader`, `action`, `headers`
```

It appears that this happens when a function from a `.server.js` file is imported but not used.

**Comment by pcattori** [comment]
The error message should include a link to https://remix.run/docs/en/main/future/vite#splitting-up-client-and-server-code . Have you tried following the steps outlined there?

**Comment by 684efs3** [comment]
using `serverOnly$` works! Thank you!
