### ISSUE TITLE
[Bug]: Seeminlgy invalid app.arc file generate when running npx create-remix@latest

### ISSUE THREAD

**Issue by mxro** [remix-run/remix#862]
### Which Remix packages are impacted?

`create-remix`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

v14.17.6

### Steps to Reproduce

- Run `npx create-remix@latest`
- Select deployment through AWS using architect

### Expected Behavior

A valid `./app.arc` is generated.

### Actual Behavior

The following `app.arc` is generated:

```
@app
remix-architect-app

@http
/*
  method any
  src server

@static

# @aws
# profile default
# region us-west-1
```

I don't know much about the architect framework and this file format. But this looks quite different to me compared to the examples provided on the Architect documentation.

**Comment by machour** [comment]
The app.arc file seems valid.
