### ISSUE TITLE
[Feature]: Graceful port suggestion if 3000 is taken

### ISSUE THREAD

**Issue by jaredpalmer** [remix-run/remix#863]
### What is the new or updated feature that you are suggesting?

Suggest a new port if 3000 is being used		

### Why should this feature be included?

Currently it fails and leaks a fairly comment error to the end user

<img width="1237" alt="CleanShot 2021-12-02 at 16 24 42@2x" src="https://user-images.githubusercontent.com/4060187/144505418-d63d6317-2b7e-40fc-915e-44b6b7fb0788.png">
s

**Comment by chenc041** [comment]
There are two pr to this question 😁
[auto change dev server port ](https://github.com/remix-run/remix/pull/844)
[Check if the specified port is in use](https://github.com/remix-run/remix/pull/746)

**Comment by machour** [comment]
Fixed in https://github.com/remix-run/remix/pull/871
