### ISSUE TITLE
useLoaderData converts JSX Element into javascript object 

### ISSUE THREAD

**Issue by anonimusprogramus** [remix-run/remix#8670]
### Reproduction

- Go to https://stackblitz.com/edit/remix-run-remix-tge114
- Clink link to **User A**, it's ok
- Clink link to **User B**, it's error

### System Info

```shell
System:
  OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
  CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Memory: 884.71 MB / 3.28 GB
  Container: Yes
  Shell: 5.0.17 - /bin/bash
Binaries:
  Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
  npm: 8.15.0 - ~/.local/share/pnpm/npm
  pnpm: 8.14.1 - ~/.local/share/pnpm/pnpm
  bun: 1.0.7 - ~/.bun/bin/bun
Browsers:
  Brave Browser: 121.1.62.153
  Chrome: 121.0.6167.85
npmPackages:
  @remix-run/css-bundle: ^2.5.1 => 2.5.1 
  @remix-run/dev: ^2.5.1 => 2.5.1 
  @remix-run/node: ^2.5.1 => 2.5.1 
  @remix-run/react: ^2.5.1 => 2.5.1 
  @remix-run/serve: ^2.5.1 => 2.5.1
```

### Used Package Manager

pnpm

### Expected Behavior

We have 2 routes: `/user-a` and `/user-b`

Both routes has **same data source**, ie. object containing string and JSX element

Route `/user-a` imports data **directly**, route `/user-b` gets data from **useLoaderData**

Both routes should show info

### Actual Behavior

Route `/user-b` **failed**, showing error:

`Error: Objects are not valid as a React child (found: object with keys {type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.`

**Comment by sergiodxa** [comment]
You can’t return JSX from a loader, the loader runs server side and the result is serialized using JSON.stringify so it can travel across the network, this causes your issue.

**Comment by brophdawg11** [comment]
Closing this as this is an invalid usage of loaders - which have to return serializable responses such as JSON or text.  I would return the _data_ you need to render in the JSON (`textColor`, `message`) and then render the `span` in your component accordingly:

```
<li>
  signature: 
  <span style={{ color: loaderData.user.textColor }}>
    {loaderData.use.message}
  </span>
</li>
```

Otherwise, if you _need_ to render the JSX on the server you can use `renderToString` and then use `dangerouslySetInnerHTML` in your component.
