### ISSUE TITLE
CSS modules don't work outside routes

### ISSUE THREAD

**Issue by commscheck** [remix-run/remix#8679]
### Reproduction

Stackblitz: https://stackblitz.com/edit/remix-run-remix-zvzmya?file=app%2Froutes%2Fexample%2Froute.tsx

Open the `/example` route in the preview

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 111.13 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @remix-run/css-bundle: ^2.6.0 => 2.6.0
    @remix-run/dev: ^2.6.0 => 2.6.0
    @remix-run/node: ^2.6.0 => 2.6.0
    @remix-run/react: ^2.6.0 => 2.6.0
    @remix-run/serve: ^2.6.0 => 2.6.0

Note: I use "Arc" (chromium) as my default browser which didn't get listed above.
```

### Used Package Manager

npm

### Expected Behavior

* `/app/components/purple-box/purple-box.module.css` contains the `.purpleBox` class
* `/app/components/purple-box/purple-box.tsx` imports `purple-box.module.css` and applies `.purpleBox` to the component
* `/app/routes/example/example.module.css` contains the `.yellowBox` class
* `/app/routes/example/route.tsx`:
  * Imports and displays a `<PurpleBox />` component
  * Imports `example.module.css` and applies the `.yellowBox` class to a div.

I expect that both CSS classes are applied to their respective divs.

### Actual Behavior

The CSS module file inside `/app/routes` applies correctly, but the CSS module file inside `/app/components` isn't included in the `cssBundleRef` in `root.tsx`.

**Comment by cythrawll** [comment]
Isn't this just the known issue here: https://github.com/evanw/esbuild/issues/1370
that's mentioned in the bottom here under limitations? https://remix.run/docs/en/main/styling/bundling

I fixed the stackblitz example by changing the export in your purple-box/index.ts to: `export { PurpleBox } from './purple-box';
`

**Comment by commscheck** [comment]
@cythrawll you're right, apologies, I missed that note at the end of the page. Cheers!
