### ISSUE TITLE
tiny typo in jokes tutorial

### ISSUE THREAD

**Issue by jimmythigpen** [remix-run/remix#8683]
### Reproduction

Go to https://remix.run/docs/en/main/tutorials/jokes#seo-with-meta-tags

The second paragraph includes sentence "Why don't you go through and add a useful few meta tags to the following routes:"

### System Info

```shell
System:
    OS: macOS 12.7.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.57 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 1.22.17 - ~/.asdf/shims/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    @remix-run/css-bundle: ^2.5.1 => 2.5.1
    @remix-run/dev: ^2.5.1 => 2.5.1
    @remix-run/node: ^2.5.1 => 2.5.1
    @remix-run/react: ^2.5.1 => 2.5.1
    @remix-run/serve: ^2.5.1 => 2.5.1
```

### Used Package Manager

npm

### Expected Behavior

This sentence should probably read "Why don't you go through and add a few useful meta tags to the following routes:"

### Actual Behavior

The second paragraph includes sentence "Why don't you go through and add a useful few meta tags to the following routes:", the words seem out of order by mistake.

**Comment by brophdawg11** [comment]
Thanks!  Addressed in b5d6b001a7b6995379f6b2c2301024d4a0ae8ac6
