### ISSUE TITLE
Cannot upload file with unstable-vite template

### ISSUE THREAD

**Issue by Varkoff** [remix-run/remix#8724]
### Reproduction

1. Create a new repo using the unstable vite template. (`npx create-remix@latest --template remix-run/remix/templates/unstable-vite`) or go to https://stackblitz.com/~/github.com/Varkoff/remix-vite-file-upload

2. Add a small file (less than 100MB) and hit submit

3. Get thrown an error
```sh
ReferenceError: File is not defined
    at /Users/dev/dev/toto/node_modules/@remix-run/server-runtime/dist/upload/memoryUploadHandler.js:44:7
```
In stackblitz, the error is 

```sh
[vite] Internal server error: `line` must be greater than 0 (lines start at line 1)
```

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M2 Pro
    Memory: 124.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.3
  npmPackages:
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/node: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0 
    @remix-run/serve: ^2.6.0 => 2.6.0 
    vite: ^5.0.0 => 5.1.0
```

### Used Package Manager

npm

### Expected Behavior

A file being successfully uploaded in memory or in a directory.

### Actual Behavior

An error being thrown while parsing the formData using `unstable_parseMultipartFormData`

**Comment by brophdawg11** [comment]
We don't currently install the global polyfills by default in the vite dev server, so you can add them in your vite config by calling `installGlobals`: <https://remix.run/docs/en/main/future/vite#migrating-from-remix-app-server>

**Comment by wmik** [comment]
@brophdawg11 Any idea how to solve this on the netlify template?

**Comment by wmik** [comment]
Ooh wow I think I identified the issue

So...

The default netlify template uses the netlify remix adapter *(at the time of writing version 2.2.0)* which after a bit of investigation uses `createReadableStreamFromReadable` from the remix-run/node package. 

The project used styled-components *(at the time of writing version 6.1.8)* which needed a small adjustment in `entry.server.ts` to handle a [hydration issue](https://stackoverflow.com/questions/72754600/remix-hydration-failed-ui-on-server-and-client-do-not-match)

After reverting to the original it looks like things work as expected but unfortunately migrating away from styled-components for now.
