### ISSUE TITLE
Remix + vite using v1 routing (`@remix-run/v1-route-convention`) doesnt work? 

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#8744]
### Reproduction
I created a repo containing

1. fresh unmodified remix-vite express app
2. modified remix-vite express app attempting to use @remix-run/v1-route-convention

Github Repo: https://github.com/cliffordfajardo/bug-remix-vite-using-v1-routing/tree/main

![CleanShot 2024-02-13 at 12 15 03@2x](https://github.com/remix-run/remix/assets/6743796/2f8fdae8-38ee-489a-9213-55783526668c)

## Reproduction Steps
1.Create a new remix app using vite express
```
npx create-remix --template remix-run/remix/templates/unstable-vite-express
```
4. install `[@remix-run/v1-route-convention](https://github.com/remix-run/v1-compat-utils)`
5. Rename `routes/_index.ts` to `routes/index.ts`

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 116.60 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.volta/tools/image/node/20.5.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 9.8.0 - ~/.volta/tools/image/node/20.5.0/bin/npm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.139
    Chrome Canary: 117.0.5849.2
    Safari: 17.3.1
  npmPackages:
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/express: ^2.6.0 => 2.6.0 
    @remix-run/node: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0 
    @remix-run/v1-route-convention: ^0.1.4 => 0.1.4 
    vite: ^5.0.0 => 5.1.1
```

### Used Package Manager

npm

### Expected Behavior

After creating a fresh remix app, I should be able to use `[@remix-run/v1-route-convention](https://github.com/remix-run/v1-compat-utils)` package

### Actual Behavior

Remix + Vite doesnt seem to work with [@remix-run/v1-route-convention](https://github.com/remix-run/v1-compat-utils)

```
npm run dev

/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/config/flat-routes.js:38
    if (!value) throw new Error("Cannot add empty string to PrefixLookupTrie");
                      ^

Error: Cannot add empty string to PrefixLookupTrie
    at PrefixLookupTrie.add (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/config/flat-routes.js:38:23)
    at flatRoutesUniversal (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/config/flat-routes.js:141:18)
    at Object.flatRoutes (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/config/flat-routes.js:97:23)
    at Object.resolveConfig (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/config.js:164:33)
    at async updateRemixPluginContext (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/vite/plugin.js:314:9)
    at async config (/Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/@remix-run/dev/dist/vite/plugin.js:506:7)
    at async runConfigHook (file:///Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:68149:25)
    at async resolveConfig (file:///Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:67608:14)
    at async _createServer (file:///Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:64224:20)
    at async file:///Users/cfajardo/Downloads/bug--remix-vite-using-v1-routing/remix_2_6_0_v1_routes/server.js:12:7
```

**Comment by markdalgleish** [comment]
I wasn't able to reproduce this issue, both manually and when running your repro.

I've pushed my attempt at a manual reproduction here. Can you check whether this works for you? https://github.com/markdalgleish/remix-vite-express-with-v1-routes

By the way, I noticed that a sync `routes` function in your Remix Vite plugin options is incorrectly flagged as a type error, so I've opened a PR to fix this: https://github.com/remix-run/remix/pull/8745

**Comment by kiliman** [comment]
@cliffordfajardo Do you set the `ignoredFilePatterns` to ignore dotfiles?
```ts
/** @type {import(https://github.com/remix-run/remix/tree/master/packages/remix-dev).AppConfig} */
module.exports = {
  // Tell Remix to ignore everything in the routes directory.
  // We'll let `createRoutesFromFolders` take care of that.
  ignoredRouteFiles: ["**/*"],
  routes: (defineRoutes) => {
    // `createRoutesFromFolders` will create routes for all files in the
    // routes directory using the same default conventions as Remix v1.
    return createRoutesFromFolders(defineRoutes, {
      // If you're already using `ignoredRouteFiles` in your Remix config,
      // you can move them to `ignoredFilePatterns` in the plugin's options.
      // ignore dotfiles
      ignoredFilePatterns: ["**/.*", "**/*.css"],
    });
  },
};
```

**Comment by cliffordfajardo** [comment]
> Do you set the ignoredFilePatterns to ignore dotfiles? - @kiliman 
For the `PrefixLookupTrie`  error, the problem was indeed due to having a `.DS_STORE` file inside of `routes` folder, so I just deleted it the file

I was curious about the `ignoredRouteFiles: ["**/*"]` at the root of the config and `ignoredFilePatterns` inside of `createRoutesFromFolders` - they dont work when using them inside of `vite.config.js`

Created a bug reproduction repo
https://github.com/cliffordfajardo/bug-remix-v1-routing-vite-config

<img width="1780" alt="image" src="https://github.com/remix-run/remix/assets/6743796/95df9b47-f0f3-4e52-8f02-1a82f3b00f08">

**Comment by markdalgleish** [comment]
@cliffordfajardo Looks like you also need to exclude dotfiles in `ignoredRouteFiles`:

```ts
remix({
  ignoredRouteFiles: ["**/*", "**/.*"],
  routes: (defineRoutes) => {
    return createRoutesFromFolders(defineRoutes, {
      ignoredFilePatterns: ["**/.*", "**/*.css"],
    });
  },
})
```

**Comment by markdalgleish** [comment]
I've fixed this in the v1-route-convention readme: https://github.com/remix-run/v1-compat-utils/tree/main/packages/v1-route-convention

**Comment by markdalgleish** [comment]
I've also opened a PR updating all the Vite templates to set `ignoredRouteFiles` to `["**/.*"]` to avoid this issue coming up in that context too: https://github.com/remix-run/remix/pull/8800
