### ISSUE TITLE
Remix <ScrollRestoration /> messing with url fragment scrolling position

### ISSUE THREAD

**Issue by danthegoodman1** [remix-run/remix#8754]
### Reproduction

When using scrollrestoration in root.tsx, and clicking on an a tag for a url fragment, the browser snaps to the initial scrolling position of the page load. For example go to https://aspiring.dev/posts/frontlink, scroll down, and click on any header, it snaps the scrolling to the top. But if you click on it again, or load that page directly, it scrolls to the expected position.

If I comment out the scroll restoration component it works as expected, but obviously that's not ideal. How can I solve this? Obviously I can't see url fragments on the server so I can't conditionally render the scrollrestoration component.

The a tag is part of a dangerously insert html from an HTML string from the loader:

Minimal example for an otherwise default nodejs Remix app (this has tailwind installed as well, [original Github](https://github.com/danthegoodman1/aspiring.dev)):

```tsx
import { json } from "@remix-run/node"
import { useLoaderData } from "@remix-run/react"
import { renderToString } from "react-dom/server"

export async function loader() {
  const jsx = (
    <div>
      <h2
        style={{
          marginBottom: "2000px",
        }}
      >
        Top padding content
      </h2>
      <a href="#something">
        <h1 id="#something">Hey there</h1>
      </a>
    </div>
  )
  const rendered = renderToString(jsx)
  return json({
    rendered,
  })
}

export default function Post() {
  const data = useLoaderData<typeof loader>()
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: data.rendered,
      }}
    />
  )
}

```

If you click on the A tag at the bottom, you can see it snap back to the top, but if you reload or click again it scrolls to the bottom.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.48 GB / 64.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
```

### Used Package Manager

npm

### Expected Behavior

Scrolling does not snap to top on first click

### Actual Behavior

First click scroll snaps to top, on second click it scrolls as expected. Navigating directly to URL with fragment works as expected.

**Comment by brophdawg11** [comment]
I don't think I'm seeing what you're describing?  What browser were you using?

When I go to the page and scroll down (no hash):

![Screenshot 2024-02-15 at 10 11 11 AM](https://github.com/remix-run/remix/assets/1609022/2ff30ad8-fc5a-4ac0-8f99-0c7aee7aebe6)

And then click the "We can share functions too" heading, it scrolls to that anchor as expected:

![Screenshot 2024-02-15 at 10 11 19 AM](https://github.com/remix-run/remix/assets/1609022/44a46ebe-d6eb-412a-a6c1-518ede7a00c9)

**Comment by danthegoodman1** [comment]
Hi, I pushed an update to remove `<ScrollRestoration />` on that page in the meantime. I've switched it back so you can take a look @brophdawg11 , and I've also attached a recording. Note that you generally have to scroll decently down, somtimes if you don't scroll far enough I've noticed it just doesn't move. In the recording, you can see the second time I click the link it scrolls to the location expected

https://github.com/remix-run/remix/assets/17806508/2b46bf40-9bef-4311-b500-7b00d60302d8

**Comment by brophdawg11** [comment]
It looks like this is specific to raw `<a>` tags (not `<Link>`, so React Router is not aware of them) used on an otherwise Remix/RR-hydrated site.  An `<a>` that only changes the hash triggers a `popstate` event but it's not popping back or forward to any known location so the new `location` (with the hash) ends up inadvertently/incorrectly inheriting a `location.key = "default"` and then it gets out of whack trying to restore to positions keyed by that (default it the key for the very first page of a new session).

I'll dig in a bit deeper to our `history` abstraction and see if this is something we can/should be detecting but the easiest way to fix/workaround it for now is to make Remix/React Router aware of those link navigations.  You can do this by detecting `<a>` clicks at a higher level and proxying them through React Router:

```jsx
let navigate = useNavigate();
...
return (
  <div
    onClick={(e) => {
      if (
        !e.defaultPrevented &&
        e.target.tagName === "A" &&
        e.target.getAttribute("href") != null
      ) {
        e.preventDefault();
        navigate(e.target.getAttribute("href"));
      }
    }}>
    ...
  </div>
);
```

That prevents the browser from sending the `popstate` event in the first place and React Route will now know about the navigation and treat it as a new location - and fall through to scrolling to the hash when it doesn't find a prior scroll position.

This is basically exactly what we do on the React Router and Remix websites - here's our more comprehensive solution to the snippet above: https://github.com/remix-run/react-router-website/blob/main/app/components/delegate-markdown-links.ts

**Comment by danthegoodman1** [comment]
That makes sense, but I won't be able to do that with the `renderToString` loader method I was doing since I can't stick react hooks in there.

**Comment by brophdawg11** [comment]
You would do it in the component rendering the HTML so the clicks from the rendered HTML bubble to the wrapper listener:

```tsx
export default function Post() {
  const data = useLoaderData<typeof loader>();
  const navigate = useNavigate();
  return (
    <div
      onClick={...}
      dangerouslySetInnerHTML={{
        __html: data.rendered,
      }}
    />
  )
}
```

**Comment by danthegoodman1** [comment]
The behavior seems different, but also incorrect. You can only see it in the last one, but after the first one that scrolls back to the top, they all do a slight flicker up.

https://github.com/remix-run/remix/assets/17806508/e67d6ded-1250-4c52-bb17-339e87bdafcd

with code 
```tsx
export default function Post() {
  const data = useLoaderData<typeof loader>()
  useNavigate()
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: data.rendered,
      }}
    />
  )
}
```

**Comment by brophdawg11** [comment]
If you can put together a minimal reproduction I can take a look (I'm on vacation next week so after that).  We're pretty confident this approach works though since it's been in use on our production sites for quite some time now :)
