### ISSUE TITLE
Duplicate inlined style during initial render in vite dev server

### ISSUE THREAD

**Issue by fire332** [remix-run/remix#8759]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-x8esh3?file=app%2Froutes%2F_index.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.6.0 
    @remix-run/node: * => 2.6.0 
    @remix-run/react: * => 2.6.0 
    vite: ^5.1.2 => 5.1.2
```

### Used Package Manager

npm

### Expected Behavior

The only style tag in `<head>` should be from vite.

### Actual Behavior

2 style tags with duplicate content in `<head>`. Triggering an HMR update (i.e. by editing a file in the app folder) will cause the style tag from remix to disappear. Triggering a page reload will cause the extra style tag to reappear.

**Comment by fire332** [comment]
Note: issue occurs with `react@canary` as well.

**Comment by hi-ogawa** [comment]
I think this is working intended. I wrote it in this discussion before https://github.com/remix-run/remix/discussions/8070#discussioncomment-7625870 and the 1st style (SSR-ed by Remix) is necessary since the 2nd one is injected on the client. For the 2nd one alone, it would cause FOUC.

I wonder if having a duplicate css might cause some specificity/priority issue and break style, but I haven't seen that so far.

**Comment by pcattori** [comment]
Closing as this behavior is intended as a way to prevent FOUC during development and is standard practice for fullstack frameworks (e.g. [Astro](https://github.com/withastro/astro/blob/7bdcfb750ae5e8a9e2a0ee68c7ac03b82215d08f/packages/astro/src/vite-plugin-astro-server/route.ts#L471-L472), [SvelteKit](https://github.com/sveltejs/kit/blob/cd6db35a6974d11c65f82d06cb9e86047ab8f8f6/packages/kit/src/exports/vite/dev/index.js#L186-L187), etc.)
