### ISSUE TITLE
Meta function getting called when it shouldn't

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#876]
### What version of Remix are you using?

v1.0.3

### What version of Node are you using? Minimum supported version is 14.

NONE! CF Workers!

### Steps to Reproduce

1. Have a meta function that reads `data`.
2. Make sure the route does *not* have its own error boundary
3. Throw a response (404)

### Expected Behavior

The meta function shouldn't get called if the route doesn't have an error boundary.

### Actual Behavior

The meta function gets called even though it's not used.

**Comment by berrylover03** [comment]
> ### Which Remix packages are impacted?
> * [x]  `remix` (Remix core)
> * [ ]  `create-remix`
> * [ ]  `@remix-run/architect`
> * [ ]  `@remix-run/cloudflare-workers`
> * [ ]  `@remix-run/dev`
> * [ ]  `@remix-run/express`
> * [ ]  `@remix-run/netlify`
> * [ ]  `@remix-run/node`
> * [ ]  `@remix-run/react`
> * [ ]  `@remix-run/serve`
> * [ ]  `@remix-run/server-runtime`
> * [ ]  `@remix-run/vercel`
> 
> ### What version of Remix are you using?
> v1.0.3
> 
> ### What version of Node are you using? Minimum supported version is 14.
> NONE! CF Workers!
> 
> ### Steps to Reproduce
> 1. Have a meta function that reads `data`.
> 2. Make sure the route does _not_ have its own error boundary
> 3. Throw a response (404)
> 
> ### Expected Behavior
> The meta function shouldn't get called if the route doesn't have an error boundary.
> 
> ### Actual Behavior
> The meta function gets called even though it's not used.

Bug
