### ISSUE TITLE
Cannot parse multiple cookies from the same header

### ISSUE THREAD

**Issue by br0p0p** [remix-run/remix#8769]
### Reproduction

Stackblitz: https://stackblitz.com/~/github.com/br0p0p/remix-cookie-bug

- Run `node cookiebug.mjs` in the terminal
- You will see an `AssertionError` meaning the second cookie in the header did not parse correctly

I also included a version using `installGlobals()` (`cookiebug-withglobals.mjs`) which has the same behavior.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/css-bundle: ^2.6.0 => 2.6.0 
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/node: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0 
    @remix-run/serve: ^2.6.0 => 2.6.0
```

### Used Package Manager

npm

### Expected Behavior

I would expect the `cookie.parse()` function to be capable of handling multiple cookie values in one string as returned by `headers.get()` (this means `request.headers.get()` and `response.headers.get()` as well)

To me, this use case is in line with the "use the platform" ethos. However, there may be good reasons this isn't supported. 

```ts 
const headers = new Headers();

headers.append("Set-Cookie", await firstCookie.serialize({ value: 1 }));
headers.append("Set-Cookie", await secondCookie.serialize({ value: 1 }));

headers.get("Set-Cookie") === "firstCookie=eyJ2YWx1ZSI6MX0%3D; Path=/; HttpOnly; SameSite=Lax, secondCookie=eyJ2YWx1ZSI6Mn0%3D; Path=/; HttpOnly; SameSite=Lax"

// Parses correctly
await firstCookie.parse(headers.get("Set-Cookie"))

// Returns `null`
await secondCookie.parse(headers.get("Set-Cookie"))
```

### Actual Behavior

The `cookie.parse()` function correctly parses the first cookie but fails to parse the second

**Comment by brophdawg11** [comment]
You shouldn't be parsing the `Set-Cookie` response header - that is what sets the cookie in the browser.  You should be parsing the incoming Request `Cookie` header, which would look something like this:

```js
const parsedFirstCookie = await firstCookie.parse("firstCookie=eyJ2YWx1ZSI6MX0%3D; secondCookie=eyJ2YWx1ZSI6Mn0%3D");
const parsedSecondCookie = await secondCookie.parse("firstCookie=eyJ2YWx1ZSI6MX0%3D; secondCookie=eyJ2YWx1ZSI6Mn0%3D");
```

```sh
> node cookiebug.mjs
...
firstCookie: { value: 1 }
secondCookie: { value: 2 }
```
