### ISSUE TITLE
[Docs]: Follow a consistent style for the tutorial code

### ISSUE THREAD

**Issue by meehawk** [remix-run/remix#881]
### What is the new or updated feature that you are suggesting?

While this might not be a high priority, following through the tutorials, I've noticed the code follows inconsistent styling, "semi-colons at some places and not at the rest". There are ways to lint the markdown code sections to enforce consistent code styling for examples. Gatsby used to do something similar on their older website

### Why should this feature be included?

For any new developer, following a consistent styling guide for their code is a good practice. While the focus on Remix might not be this, it would be nice if we could push this as one of our values too.

**Comment by chaance** [comment]
Happy to accept a PR anywhere where you think we can improve the docs. This issue is a bit too broad to be much help so I'm going to close it. Feel free to tag me directly in any PR requests to improve inconsistencies with our docs.
