### ISSUE TITLE
2.7.0 : MUI named import generate error

### ISSUE THREAD

**Issue by raskyer** [remix-run/remix#8828]
### Reproduction

Clone : https://github.com/raskyer/remix-bug
npm run dev
`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 16.48 GB / 31.73 GB
  Binaries:
    Node: 20.9.0 - ~\AppData\Local\fnm_multishells\26476_1708451566467\node.EXE
    npm: 10.1.0 - ~\AppData\Local\fnm_multishells\26476_1708451566467\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/dev: ^2.7.1 => 2.7.1
    @remix-run/express: ^2.7.1 => 2.7.1
    @remix-run/node: ^2.7.1 => 2.7.1
    @remix-run/react: ^2.7.1 => 2.7.1
    vite: ^5.1.0 => 5.1.3
```

### Used Package Manager

npm

### Expected Behavior

I want to be able to import : `import Button from '@mui/material/Button` as stated in : 
https://mui.com/material-ui/getting-started/usage/
without issue.

### Actual Behavior

I have the following error : 
`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by QzCurious** [comment]
Hi @pcattori, I'd love to let you know that `ssr.noExternal: ["@mui/material"]` won't be working. 

![image](https://github.com/remix-run/remix/assets/38932402/b0eb6764-4891-40c4-875c-bc8d10d4ffb7)


In addition, I was able to make it work by `cjsInterop({ dependencies: ["@mui/material/*"] })`. I don't know but the `/*` IS NECESSARY.

_BTW, I'm not any familiar with ESM/CJS problem but trying to get luck on this issue._

**Comment by pcattori** [comment]
@QzCurious could you try bundling `@mui/*` dependencies only in production as [suggested in this template](https://github.com/kiliman/remix-vite-mui/blob/main/vite.config.ts#L10)?

**Comment by QzCurious** [comment]
For production build, it works. And for your convenience, [here](https://github.com/QzCurious/mui-remix-vite/blob/8e862167fc41843f00eeabf440a3870c7c018a2b/vite.config.ts#L10-L29) is a reproduction code I used for testing it.

Curious about the [suggestion](https://github.com/kiliman/remix-vite-mui/blob/main/vite.config.ts#L10), why would we only configuring it for production and make it unusable for local dev?

**Comment by QzCurious** [comment]
The conditional `ssr.noExternal` configuration inspired me to try `remix-serve ./build/server/index.js` for a build bundle. Turns out I need combine both `ssr.noExternal`, `cjsInterop` to make both dev and production server working.

Here's how it should be configured:

```js
export default defineConfig({
  // dev: failed; build: success; remix-serve: failed
  // https://github.com/kiliman/remix-vite-mui/blob/aee050114dae1b01d35276a7d7641d5df45fcfba/vite.config.ts#L10
  ssr: {
    noExternal: process.env.NODE_ENV === "production" ? [/^@mui\//] : [],  // or  `['@mui/**']`
  },

  plugins: [
    remix(),
    tsconfigPaths(),
    // dev: success; build: success; remix-serve: failed
    process.env.NODE_ENV === "development" &&
      cjsInterop({
        dependencies: ["@mui/material/*"],
      }),
  ],
});
```
