### ISSUE TITLE
Tailwind not working with Vite

### ISSUE THREAD

**Issue by TranquilMarmot** [remix-run/remix#8832]
### Reproduction

I tried to set this up on StackBlitz, but I don't think that's set up to run Vite yet 😖 

I started a new Remix project using:

```sh
pnpx create-remix@latest --template remix-run/remix/templates/vite-cloudflare
```

I'm running the dev server with:

```sh
remix vite:dev
```

I followed exactly the instructions here:

https://remix.run/docs/en/main/styling/tailwind

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 51.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.asdf/installs/nodejs/21.6.1/bin/node
    Yarn: 1.22.21 - ~/.asdf/installs/nodejs/21.6.1/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.1 - ~/.asdf/installs/nodejs/21.6.1/bin/pnpm
    bun: 1.0.26 - ~/.asdf/shims/bun
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.1
  npmPackages:
    @remix-run/cloudflare: ^2.7.1 => 2.7.1 
    @remix-run/cloudflare-pages: ^2.7.1 => 2.7.1 
    @remix-run/dev: ^2.7.1 => 2.7.1 
    @remix-run/react: ^2.7.1 => 2.7.1 
    vite: ^5.1.0 => 5.1.3 
```

### Used Package Manager

pnpm

### Expected Behavior

Tailwind CSS should be compiled + show up in the browser

### Actual Behavior

If I try and use any Tailwind `className`s, then I get the following error on the server:

```
Error: No route matches URL "/@tailwind%20base;@tailwind%20components;@tailwind%20utilities;"
```

And on the client I see:
```
GET http://localhost:5173/@tailwind%20base;@tailwind%20components;@tailwind%20utilities; net::ERR_ABORTED 404 (Not Found)
```

If I try and build the project using `remix vite:build` I get:

```
x Build failed in 334ms
Error [RollupError]: "default" is not exported by "app/tailwind.css", imported by "app/root.tsx".
file: {my_project}/app/root.tsx:2:2
1: import {
2:   Links,
     ^
3:   Meta,
4:   Outlet,
```

**Comment by TranquilMarmot** [comment]
Never mind, there are some instructions for this here:
https://remix.run/docs/en/main/future/vite#enable-tailwind-via-postcss

It might be worth pointing to that from https://remix.run/docs/en/main/styling/tailwind as a warning if you're using Vite 🤔

**Comment by devjmetivier** [comment]
@TranquilMarmot Are you sure that you resolved this? I'm having the exact same issue with the starter template and getting absolutely nowhere.

**Comment by kiliman** [comment]
@devjmetivier I found that getting Tailwind JIT to work with Vite HMR, you need to use React Canary to fix the hydration issues.

See my template `remix-vite-template` for setup.

https://github.com/kiliman/remix-vite-template

**Comment by twentynine12** [comment]
I spent ages on this yesterday (using the remix netlify template and Remix v2.7.2) and eventually got tailwind working using the instructions in the 'Future' Vite section.  Regular CSS did work but again there was an error with the CSS as the import needed updating (adding '?url').

The documentation seems a bit muddled as following the instructions to add tailwind or regular css to a newly created remix project requires you to go through the Future / Vite docs which isn't clear.

**Comment by nikolailehbrink** [comment]
For anyone landing here, I struggled with that myself so here is a quick step by step guide, how to setup Tailwind with Remix + Vite. This setup was done on top of `npx create-remix@latest --template remix-run/remix/templates/vite` mentioned [here](https://remix.run/docs/en/main/future/vite#getting-started):
1. Install TailwindCSS
    ```sh
    npm install -D tailwindcss postcss autoprefixer
    ```
2. Generate your tailwind.config and postcss.config
    ```sh
    npx tailwindcss init -p
    ```
3. Configure template paths
    ```ts
    // tailwind.config.js
    /** @type {import('tailwindcss').Config} */
    export default {
      content: ["./app/**/*.{ts,tsx}"],
      theme: {
        extend: {},
      },
      plugins: [],
    }
    ```
4. Add the Tailwind directives to your CSS
    ```css
    /* app/globals.css */
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
    ```
5. Add stylesheet to root.tsx
    ```tsx
    // app/root.tsx
    import { LinksFunction } from "@remix-run/node";
    // using the explicit URL import is important here: https://vitejs.dev/guide/assets.html#explicit-url-imports
    import styles from "@/globals.css?url";
    
    export const links: LinksFunction = () => [
      { rel: "stylesheet", href: styles },
    ];
    ```

**Comment by imyuanli** [comment]
> 对于任何登陆这里的人来说，我自己都在为此苦苦挣扎，所以这里有一个快速的分步指南，如何使用 Remix + Vite 设置 Tailwind。此设置是[在此处](https://remix.run/docs/en/main/future/vite#getting-started)提到的之上完成的。我还创建[了这个样板仓库](https://github.com/nikolailehbrink/retail)，您可以使用它来让 TailwindCSS 在混音中具有自动类排序功能：`npx create-remix@latest --template remix-run/remix/templates/vite`
> 
> 1. 安装 TailwindCSS```shell
>    npm install -D tailwindcss postcss autoprefixer
>    ```
> 2. 生成 tailwind.config 和 postcss.config```shell
>    npx tailwindcss init -p
>    ```
> 3. 配置模板路径```ts
>    // tailwind.config.js
>    /** @type {import('tailwindcss').Config} */
>    export default {
>      content: ["./app/**/*.{ts,tsx}"],
>      theme: {
>        extend: {},
>      },
>      plugins: [],
>    }
>    ```
> 4. 将 Tailwind 指令添加到您的 CSS 中```css
>    /* app/globals.css */
>    @tailwind base;
>    @tailwind components;
>    @tailwind utilities;
>    ```
> 5. 将样式表添加到 root.tsx```tsx
>    // app/root.tsx
>    import { LinksFunction } from "@remix-run/node";
>    // using the explicit URL import is important here: https://vitejs.dev/guide/assets.html#explicit-url-imports
>    import styles from "./globals.css?url";
>    
>    export const links: LinksFunction = () => [
>      { rel: "stylesheet", href: styles },
>    ];
>    ```

This works for me, thank you. But I think the Remix team should have configured it when creating-remix, after all, tailwind has been automatically installed, otherwise it really takes time to find the answer.
