### ISSUE TITLE
[Bug]: qrcode on error feature on homepage leads to 404

### ISSUE THREAD

**Issue by renhiyama** [remix-run/remix#885]
### What version of Remix are you using?

no need

### What version of Node are you using? Minimum supported version is 14.

no need

### Steps to Reproduce

goto homepage, scroll down to error feature, scan the qr code

### Expected Behavior

Rick roll maybe?

### Actual Behavior

https://remix.run/docs/en/v0.20/api/app#errorboundary
Looks like it was something but its 404 now. Please get it updated (to rickroll if possible :D)

**Comment by renhiyama** [comment]
*Scanning QR code fills you with determination*
:smile:

**Comment by fishel-feng** [comment]
The new link for the document maybe this  [https://remix.run/docs/en/v1/api/conventions#errorboundary](https://remix.run/docs/en/v1/api/conventions#errorboundary )

**Comment by mcansh** [comment]
sorry for the delay, updated QR code is being deployed now
