### ISSUE TITLE
Link with button on top still triggers

### ISSUE THREAD

**Issue by WillSmithTE** [remix-run/remix#8861]
### Reproduction

https://github.com/WillSmithTE/remix-playground-10

https://github.com/remix-run/remix/assets/26863411/0e6cc564-e804-411f-a339-50a4f6ac1790

1. Open a Button which opens a Dialog (both components from shadcn). The button sits on top of a Link
2. The dialog opens correctly
3. On closing the dialog, the Link hits

I have no idea if this is a remix thing, but it works with an anchor tag. The test case looks weird but it's based on a real example, e.g. like a reddit thread where the thread is the anchor tag but the upvote button sits on top
<img width="439" alt="image" src="https://github.com/remix-run/remix/assets/26863411/a99ba511-ecf3-4ce2-b6fb-6e796f20d505">

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 97.73 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.184
    Safari: 17.1
  npmPackages:
    @remix-run/dev: ^2.7.2 => 2.7.2 
    @remix-run/express: ^2.7.2 => 2.7.2 
    @remix-run/node: ^2.7.2 => 2.7.2 
    @remix-run/react: ^2.7.2 => 2.7.2 
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

The Link doesn't do anything

### Actual Behavior

The Link triggers after closing the dialog

**Comment by woble** [comment]
Looks like improper composition, i.e. nothing to do with Remix. You put dialog as well the button inside the Link, so any interaction will trigger the link.

**Comment by brophdawg11** [comment]
yeah if your button/dialog are inside the link then clicks will propagate like any other DOM event.  You probably just need to stop propagation: https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

**Comment by WillSmithTE** [comment]
@brophdawg11 i should've mentioned, i'm stopping propagation and default in the onClick

https://github.com/WillSmithTE/remix-playground-10/blob/main/app/routes/_index.tsx#L23

just added a codesandbox

https://codesandbox.io/p/github/WillSmithTE/remix-playground-10/main?import=true

**Comment by brophdawg11** [comment]
I see it in the `openDialog` handler, but not on the close dialog code.  I added it to a click handler on `DialogPrimitive.Close` and it fixes the issue?

**Comment by WillSmithTE** [comment]
ahhhh thanks. i exposed the radix overlay props to the shadcn dialog and can stop it that way with the onClick. thank you!

https://github.com/WillSmithTE/remix-playground-10/commit/a4549ecee34ed38d11e8794c81f62aef9f4caf73#diff-8bd8555c577836673951723e36b75ebd6b5ffbb87f0220c01a5b1149c8c7f525R42

**Comment by woble** [comment]
Unsure why you insist on composing it the way you do, because it's simply incorrect, as per my original comment. You only end up getting to have to remedy it with all kind of hacks that shouldn't be necessary in the first.

**Comment by WillSmithTE** [comment]
can you explain more what you mean? like this?

```
const [showDialog, setShowDialog] = useState(false);
return (
    <div>
      <Link to="/blog" className="p-20 bg-blue-600">
        <Button onClick={openDialog} variant="outline">
          Edit Profile
        </Button>
    </Link>
    <Dialog open={showDialog} onOpenChange={setShowDialog}>
          <DialogContent
            className="sm:max-w-[425px]"
            overlayProps={{
              onClick: (e) => {
                e.stopPropagation();
                setShowDialog(false);
              },
            }}
          >
            <DialogHeader>
              <DialogTitle>Edit profile</DialogTitle>
              <DialogDescription>
                Make changes to your profile here. Click save when you're done.
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-4 items-center gap-4">
                <p>some stuff</p>
              </div>
            </div>
            <DialogFooter>
              <Button type="submit">Save changes</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
    </div>
  );

**Comment by WillSmithTE** [comment]
> avoid nesting interactable elements as you have originally, especially if they have different intents

this would be nice, but i'm not going to change the UI to suit the tech. it's a pretty common pattern, e.g. see the reddit screenshot from the original post

For the dialog, i did experiment with moving it outside the Link, but the Button and Link are separated by 2 levels of component heirarchy. i don't want to pass a bunch of props around, and this button is also in various places. it "owns" the dialog, so it feels right to have it in the same place. 

i also experimented with a "global" dialog triggered by a hook shared through the whole app, but i don't love that, and i still have to `stopPropagation` onClick anyway, just not onClose then, so i don't think the tradeoff is worthwhile. it's not like the dialog is within the anchor in the dom anyway because of the portal

**Comment by woble** [comment]
> this would be nice, but i'm not going to change the UI to suit the tech. it's a pretty common pattern, e.g. see the reddit screenshot from the original post

This is what you are trying to do, i.e. placing a button that does one thing (opening a dialog) inside a link that does entirely something else (navigate to a url) and then for some reason trying to prevent the link from doing something in certain situation. It has nothing to do with Remix or React for that matter.

https://jsitor.com/_4esuHO2uS

It's hard to tell what's happening from the screenshot since we don't know how the HTML is composed, but I am confident they don't have the buttons insides anchors.

> For the dialog, i did experiment with moving it outside the Link, but the Button and Link are separated by 2 levels of component heirarchy. i don't want to pass a bunch of props around, and this button is also in various places. it "owns" the dialog, so it feels right to have it in the same place.

Not knowing what kind of props you are trying to pass around and why makes it difficult to recommend something, it does however seem like you should rethink the architecture of your React components (again, nothing to do with Remix).

At the end of the day it's up to you how you compose your application. So I will leave it at that.
