### ISSUE TITLE
Hydration errors with `export Layout` in root

### ISSUE THREAD

**Issue by THOUSAND-SKY** [remix-run/remix#8862]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-zvdek1?file=app%2Froot.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/css-bundle: * => 2.7.2 
    @remix-run/dev: * => 2.7.2 
    @remix-run/node: * => 2.7.2 
    @remix-run/react: * => 2.7.2 
    @remix-run/serve: * => 2.7.2
```

### Used Package Manager

npm

### Expected Behavior

I would expect no hydration errors, same as without the Layout export.

### Actual Behavior

There's a bunch of hydration errors. Am I using it wrong?

```
Warning: Expected server HTML to contain a matching <div> in <#document>.
```

**Comment by aaronadamsCA** [comment]
[I noticed the same problem](https://github.com/remix-run/remix/pull/8709#issuecomment-1957689553)—it seems to me `Layout` only works with the Vite dev server.

**Comment by brophdawg11** [comment]
This is fixed by https://github.com/remix-run/remix/pull/8842 and will be available in the next release
