### ISSUE TITLE
cannot create a /server route

### ISSUE THREAD

**Issue by deflexable** [remix-run/remix#8884]
### Reproduction

1. create a route like `_nav.server.jsx` in the routes folder where `_nav` has an `<Outlet />` in it.
2. write some content on `_nav.server.jsx`.
3. visit `/server` route in the browser

### System Info

```shell
System:
    OS: macOS 12.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 214.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 16.6
  npmPackages:
    @remix-run/css-bundle: ^2.6.0 => 2.6.0 
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/express: ^2.6.0 => 2.6.0 
    @remix-run/node: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0
```

### Used Package Manager

npm

### Expected Behavior

i created a route like `_nav.server.jsx` where `_nav` has an `<Outlet />` in it. when i visited `/server` route in the browser it should properly render the content written in `_nav.server.jsx`

### Actual Behavior

instead it shows a blank screen and logging a warning to the console that says: `Matched leaf route at location "/server" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.`. i renamed _nav.server.jsx to _nav.users.jsx and visited /users in the browser and the content displayed properly.

from remix.run doc https://remix.run/docs/en/main/discussion/server-vs-client#forcing-code-out-of-the-browser-or-server-builds i think remix is treating any file that ends with .server.js or .server.jsx as a server only code

how can i have a route with /server

**Comment by jrestall** [comment]
Does escaping the URL to avoid Remix's *server.jsx convention help such as `_nav.[server].jsx`?
