### ISSUE TITLE
[Bug]: Cypress E2E test route navigation - "failed to execute 'insertBefore' on 'Node'" crash 

### ISSUE THREAD

**Issue by Sendouc** [remix-run/remix#889]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [X] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

Tested on 14.15.4 and 16.9.1

### Steps to Reproduce

Reference repo: https://github.com/Sendouc/cypress-test-2

1) Create new Remix app (tested Express and Remix Server starters)
2) Install latest Cypress version
3) Add a simple test that navigates to another route e.g.

```js
describe("Test crash", () => {
  it("test", () => {
    cy.visit("http://localhost:3000");
    cy.contains("Nested Routes, CSS loading/unloading").click();
    // crashes after clicking so the test never passes
    cy.contains("About Us");
  });
});
```

4) When trying to run the test the app crashes:

![image](https://user-images.githubusercontent.com/38327916/144724001-cacca979-17d0-4f4d-b228-d54417c82e1a.png)

Note 1. The browser is only using the Cypress extension
Note 2. I'm unable to reproduce this crash when using the app outside of the test.
Note 3. Tested on two different computers.

### Expected Behavior

Test runs without a crash.

### Actual Behavior

App crashes with the following stack trace: 

![image](https://user-images.githubusercontent.com/38327916/144724034-feab9cd8-7c5f-4ed5-8888-96177c13c344.png)

**Comment by AndreasSundman** [comment]
I've got this problem as well after upgrading to cypress 9. Downgraded to cypress@8.7.0 and the problem disappears. Seems to only happen with .click() on <Link> with cypress 9 and above. Clicks works if it's just ui clicks.

**Comment by Sendouc** [comment]
I'm not having this issue anymore (latest Remix + Cypress) so going to close. Maybe someone else can reopen with their own reproduction if it still happens to them.

**Comment by LANCENET** [comment]
🎉

**Comment by johnflux** [comment]
This happened to me on cypress 9.0.0, and create-react-app

**Comment by machour** [comment]
@johnflux this is a pretty old and closed issue. Please open a new one with more details if you are facing a problem 🙏

**Comment by johnflux** [comment]
Yeah unfortunately I don't have any further details at the moment.  Will investigate and create a new bug if I find out anything.
