### ISSUE TITLE
Manifest is not created if `buildDirectory` is set to `lib`

### ISSUE THREAD

**Issue by moltar** [remix-run/remix#8890]
### Reproduction

https://github.com/moltar/remix-vite-manifest-bug-repro

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 237.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @remix-run/dev: ^2.7.2 => 2.7.2 
    @remix-run/node: ^2.7.2 => 2.7.2 
    @remix-run/react: ^2.7.2 => 2.7.2 
    @remix-run/serve: ^2.7.2 => 2.7.2 
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

Manifest to be created, regardless of the build directory name.

### Actual Behavior

Manifest is not created if the build directory name is `lib`.

**Comment by markdalgleish** [comment]
I wasn't able to reproduce this. Using your repro, I got the same output in both `build` and `lib`:

<img width="168" alt="Screenshot 2024-02-27 at 12 33 14 pm" src="https://github.com/remix-run/remix/assets/696693/131660a4-0771-416a-88a8-1f5bcf2b80a1">

**Comment by moltar** [comment]
Oh, yes, you are totally right!!

I have been led astray by another bug (local to my project).

And on top of that, the right command to check for contents is `tree -a lib` (using the `-a` flag, which shows hidden files). Which when using, I do see the manifest file too. 👍🏼 

But why I was even looking into this was related to something else.

Sorry for the confusion and thank you for clarifying it.

**Comment by markdalgleish** [comment]
No worries! Thanks for following up on the issue.
