### ISSUE TITLE
Firebase: actions aren't getting submitted form data

### ISSUE THREAD

**Issue by yuraji** [remix-run/remix#89]
Submitted form data isn't getting through to an action.
Neither locally with emulators, nor when deployed to Firebase.

As a workaround, I'm able to get the submitted form data by passing request to action through context:
https://github.com/yuraji/2021-02-remix-firebase/commit/94417c2a6a26e7de836947b74d8aa4b60768f006

Related Discord discussion: https://discord.com/channels/770287896669978684/777863722592501780/808989213634592769

**Comment by ccssmnn** [comment]
Similar to #211

**Comment by machour** [comment]
Closing in favor of #211 that yields a better explanation
