### ISSUE TITLE
Remix returns a 500 for POST requests against routes without an action instead of a 405

### ISSUE THREAD

**Issue by BillBrower-Shopify** [remix-run/remix#8905]
### Reproduction

Create a standard remix app with one route. The route should have a loader and no action. Make a POST request to the route and notice that a 500 is returned

I attempted to make a new Remix app on StackBlitz and write a curl command for this reproduction but StackBlitz doesn't accept POST requests

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 75.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.dev/yarn/1.22.19/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.69
    Edge: 122.0.2365.52
    Safari: 17.3
  npmPackages:
    @remix-run/cloudflare: 2.4.1 => 2.4.1 
    @remix-run/cloudflare-workers: 2.4.1 => 2.4.1 
    @remix-run/dev: 2.4.1 => 2.4.1 
    @remix-run/eslint-config: 2.4.1 => 2.4.1 
    @remix-run/react: 2.4.1 => 2.4.1 
    @remix-run/server-runtime: 2.4.1 => 2.4.1 
    @remix-run/testing: ^2.4.1 => 2.4.1 
    vite: 4.5.2 => 4.5.2
```

### Used Package Manager

yarn

### Expected Behavior

Remix should return a 405 since the route exists but the method is not supported. Similarly, Remix should return a 405 for GET requests to a route with an action but no loader

### Actual Behavior

Remix returns an unhandled server error

**Comment by brophdawg11** [comment]
I'm not able to reproduce this - we do have [logic](https://github.com/remix-run/react-router/blob/main/packages/router/router.ts#L3120) to return a 405 here which is what I'm seeing in my reproduction:

```sh
> npx create-remix@latest temp -y
> cd temp
> echo "export const loader = () => ({value: 0});
export default function Component() { return <h1>Loader</h1>; }" > app/routes/loader.tsx
> npm run dev
```

Then in a separate tab I can curl a POST and get the 405:

```sh
> curl -X POST http://localhost:3000/loader -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/607.1.40 (KHTML, like Gecko) Version/9.1.2 Safari/607.1.40" -I
HTTP/1.1 405 Method Not Allowed
content-type: text/html; charset=utf-8
Vary: Accept-Encoding
Date: Tue, 27 Feb 2024 17:38:47 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

Is that 405 getting lost somewhere upstream in the Hydrogen setup?

FWIW I also tested with `npm run build`/`npm run start` and get the same 405 response to rule out a dev/prod difference.
