### ISSUE TITLE
Redirects silently fail to a route that has an import error

### ISSUE THREAD

**Issue by cha0s** [remix-run/remix#8915]
### Reproduction

Repository: https://github.com/cha0s/remix-eat-error

**Heads up**: This is using the **`vite-express`** template and happens in **dev mode**.

There is only one commit on top of the output from `npx create-remix@latest --template remix-run/remix/templates/vite-express` at https://github.com/cha0s/remix-eat-error/commit/60640efde5590dd395171337c927aa20ce9b26c6

Steps:

- Clone repository and `npm install`
- `npm run dev`
- Go to browser and try to click the submit button

---

P.S. I did try to create a test for you guys, but the test wouldn't even build because of the import/export issue! This may be specifically a dev mode bug.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 12.58 GB / 31.31 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.0.17 - ~/.bun/bin/bun
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chromium: 122.0.6261.69
  npmPackages:
    @remix-run/dev: ^2.7.2 => 2.7.2 
    @remix-run/express: ^2.7.2 => 2.7.2 
    @remix-run/node: ^2.7.2 => 2.7.2 
    @remix-run/react: ^2.7.2 => 2.7.2 
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

There should be some sort of error output about the incorrect import/export.

### Actual Behavior

The redirect to `/test` silently fails and lands the user back on `/` with no output.

**Comment by brophdawg11** [comment]
We will now be logging an error to the console in #8932 (you may need `Preserve Log` checked to see it though).  This will be included in the next release
