### ISSUE TITLE
useMatches returns a new object for each call even though the matches are stable and are not changing

### ISSUE THREAD

**Issue by meglio** [remix-run/remix#8945]
### Reproduction

Step 1. Create a hook that depends on the matches returned by `useMatches()`:

```js
export function use_application_global_data() {
  const matches = useMatches();
  const memoized_global_data = useMemo(() => {
    const num_matches = matches.length;
    // put a breakpoint on the line above and 
  }, [matches]);
}
```

Step 2. Create any component that uses this hook: `use_application_global_data()`

Step 3. Add the component to the page 10 times.

Step 4. When you debug, you'll see that the instance of `matches` always changes even though it is the same page, and the heavey calculation of the value that is supposed to be memoized is called repeatedly at least 10 times, one per each instance of hte component used on the same page.

This triggers the heavy calculation of the memoized global data, and, as a result, `useMemo()` does not help - because it depends on the always-changing `matches` returned by `useMatches`.

Because it is the rendering of the same page, I would expect `useMatches()` to return the same object, so that it can be used as a dependency for `useMemo()`.

### System Info

```shell
System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (10) arm64 unknown
    Memory: 4.43 GB / 6.77 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 3.6.4 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  npmPackages:
    @remix-run/dev: ^2.7.2 => 2.7.2
    @remix-run/eslint-config: ^2.7.2 => 2.7.2
    @remix-run/node: ^2.7.2 => 2.7.2
    @remix-run/react: ^2.7.2 => 2.7.2
    @remix-run/serve: ^2.7.2 => 2.7.2
    vite: ^5.1.4 => 5.1.4
```

### Used Package Manager

yarn

### Expected Behavior

`useMatches()` to return the same object until the matches actually get changed, so that I can use the returned value as a dependency of `useMemo()`.

### Actual Behavior

When you debug, you'll see that the instance of `matches` always changes even though it is the same page, and the heavey calculation of the value that is supposed to be memoized is called repeatedly at least 10 times, one per each instance of hte component used on the same page.

This triggers the heavy calculation of the memoized global data, and, as a result, `useMemo()` does not help - because it depends on the always-changing `matches` returned by `useMatches`.

Because it is the rendering of the same page, I would expect `useMatches()` to return the same object, so that it can be used as a dependency for `useMemo()`.

**Comment by brophdawg11** [comment]
This is because each component instance calls the hook again and creates a new `useMemo` instance which are unaware of each other - this is just how React hooks work.

Instead, you would need to lift this hook up to a single location and provide the shared data to each component instance via a prop or context.  

`useMatches` is [memoized](https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/hooks.tsx#L919) internally and if you create a wrapper around `useMatches` with `useMemo` it will not re-run on re-renders if the matches don't changes.  Here's an example of this in action: https://stackblitz.com/edit/remix-run-remix-zuqu7v?file=app%2Froutes%2F_index.tsx

**Comment by meglio** [comment]
Thanks, fixed by wrapping the content of `<Layout>` into a React Context.
