### ISSUE TITLE
Initial URL (/vaults) does not match URL at time of hydration (/manage), reloading page...

### ISSUE THREAD

**Issue by renzor-fist** [remix-run/remix#8976]
### Reproduction

Hello, we have an app encountering the following error on any page using `redirect` within a loader. The current page's URL never updates to the redirect URL and instead enters an infinite redirect loop.
```
Initial URL (/vaults) does not match URL at time of hydration (/manage), reloading page...
```

However, the error only occurs when deployed to a Cloudflare Pages custom domain (e.g. `app.vaultusfinance.io`). 

The error *does not occur* on either the CF Pages deployment url (xxx.yyy.pages.dev)  nor in local development (via Wrangler).

On our production site, any loader that hits a redirect produces the error. For example, visiting https://app.vaultusfinance.io/manage produces the error. The `/manage` route has a thin loader that checks for a session token and throws a redirect unless found.

```
// routes/manage._index.ts
import {
  json,
  redirect,
  type LoaderFunctionArgs,
  type MetaFunction,
} from "@remix-run/cloudflare"

export async function loader({ request, context }: LoaderFunctionArgs) {
  const session = store.getSession(request)
  if (!await session.getUser()) {
    throw redirect('/vaults')
  }

  return json(...)
}
```
```
// routes/vaults._index.ts
export async function loader({ request, context }: LoaderFunctionArgs) {
  const caller = await createServerCaller({ context, request })

  return json({
    vaultsData: await caller.vaults.allVaults(),
  })
}
```

We've found the error is produced with any flavor redirect and we feel that we've exhausted our testing options. Any information or advice would be greatly appreciated.
```
export async function loader({ request, context }: LoaderFunctionArgs) {
    // throw redirect('/vaults')
    // return redirect('/vaults')
   return new Response(null, {
    status: 302,
    headers: {
      Location: "/vaults",
    },
  })
}
```

### System Info

```shell
"@remix-run/cloudflare": "2.8.0",
"@remix-run/cloudflare-pages": "2.8.0",
"@remix-run/css-bundle": "2.8.0",
"@remix-run/dev": "2.8.0",
"@remix-run/react": "2.8.0",
```
```
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.00 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.114
    Chrome: 122.0.6261.94
    Safari: 16.6
```

### Used Package Manager

pnpm

### Expected Behavior

Successfully redirect from `/manage` to `/vaults` on a Cloudflare custom domain (ex. app.vaultusfinance.io/manage to app.vaultusfinance.io/vaults)

### Actual Behavior

app.vaultusfinance.io/manage enters a redirect loop when it encounters the `redirect` function or manual redirect Response within a loader

**Comment by brophdawg11** [comment]
I think this is an issue with your deployment configuration somewhere.  Are you doing any proxying on the server side?  Or is it possible cloudflare is serving up a cached response for the wrong url?

Remix sends up the URL the server HTML is rendered for in `__remixContext` and the HTML returned by `/manage` claims it was SSR'd for the root route `/`:

![Screenshot 2024-03-05 at 11 22 08 AM](https://github.com/remix-run/remix/assets/1609022/7c8c7e3c-d7d7-426d-bff5-0e20f87a5983)

It's also not returning a 3xx redirect, but a 200 success - so it seems like a request to `/manage` is returning a successful SSR'd HTML response from `/`, not the redirect you shoudl be getting from `/manage`.
