### ISSUE TITLE
Fetcher data missing when JavaScript is not enabled

### ISSUE THREAD

**Issue by penx** [remix-run/remix#8979]
### Reproduction

https://stackblitz.com/~/github.com/penx/remix-run-fetcher-progressive-enhancement

https://github.com/penx/remix-run-fetcher-progressive-enhancement

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (5) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.8.0 
    @remix-run/node: * => 2.8.0 
    @remix-run/react: * => 2.8.0 
    @remix-run/serve: * => 2.8.0 
    vite: ^5.1.0 => 5.1.5
```

### Used Package Manager

npm

### Expected Behavior

If a fetcher.Form is submitted without JavaScript, the form data should be made available via useFetcher in the response.

This may be a bug, as I would expect the action data to be available in my recreation, but more broadly what I am trying to achieve is:

- A form that posts to an action at a different endpoint (due in part to having multiple forms on the same page).
- Should use progressive enhancement, functionality should fall back to form posts if JavaScript is not available.
- The action returns a validation error if unsuccessful, or a redirect if it is successful.
- If a submit without JavaScript returns a validation error from the action, this validation error should be shown to the user alongside the form that was used to submit.

Note that useFetcher is specifically called on out the progressive enhancement page:

https://remix.run/docs/en/main/discussion/progressive-enhancement#simplicity

### Actual Behavior

Submitting with JavaScript works as expected.

After submitting without JavaScript and receiving a validation error from the action, fetcher.data is undefined.

**Comment by penx** [comment]
A much simpler recreation is as follows:

```tsx
import { json } from '@remix-run/node';
import { useFetcher } from '@remix-run/react';

export async function action() {
  return json({ error: 'Not implemented' });
}

export default function Index() {
  const fetcher = useFetcher<typeof action>();
  const isDeleting = fetcher.state !== 'idle';

  return (
    <fetcher.Form method="post">
      <button disabled={isDeleting} type="submit">
        {isDeleting ? 'Deleting...' : 'Delete'}
      </button>
      {fetcher.data?.error ? (
        <div>Error during delete: {fetcher.data.error}</div>
      ) : null}
    </fetcher.Form>
  );
}
```

Note this works fine with JavaScript enabled, but the fetcher data is not available if JavaScript is not available.

**Comment by kiliman** [comment]
Fetchers are imperative and meant to be used with JavaScript. Although `<fetcher.Form>` does render a native `<form>`, without JavaScript this will create a full page navigation and be treated as a regular form post, so the `action` data will be available via `useActionData()`

So you should do something like this:
```ts
const actionData = useActionData<typeof action>()
const fetcher = useFetcher<typeof action>()
// data will be from fetcher or fallback to actionData
const data = fetcher.data ?? actionData
```

See https://stackblitz.com/edit/remix-run-remix-zcapcn?file=app%2Froutes%2F_index.tsx

**Comment by brophdawg11** [comment]
This is expected behavior - fetchers are strictly client-side-only/stateful/in-page enhancements via JS.  They don't exist on the server due to the stateless nature so there's no way to "hydrate" them.  A `<fetcher.Form>` falls back to a normal `<Form>` navigation when JS is unavailable so if you need to return data you'll be able to access it through `useActionData` in the non-JS scenario.  If you need to tie the data to a specific fetcher form, I would include a hidden input in the form and echo it back in the action data so you know that it came from the fetcher.

**Comment by brophdawg11** [comment]
lol - what @kiliman said!

**Comment by penx** [comment]
> so the action data will be available via useActionData()

>  if you need to return data you'll be able to access it through useActionData in the non-JS scenario


My fetcher.Form action is set to a sub route. The default export from the sub route is a component that returns null, so you get the same form when posting to the sub route. When you post without javascript, it loads the subroute, but the actionData in the parent route is still undefined.

**Comment by penx** [comment]
My understanding at the moment is it's not possible to build a page that:

- has multiple forms pointing to different actions
- server side validation or errors returned are returned from multiple actions
- validation can be shown to the user without JavaScript

That's fine if so, I'll just have to put all this in one action. I was hoping to use multiple actions to make the code easier to understand, and the progressive enhancement section and fetcher sections of the docs made me think this would be the route to take.

**Comment by sergiodxa** [comment]
> has multiple forms pointing to different actions

It's possible, just don't use useFetcher if you care about PE, use normal <Form> component and from your action return a redirect so if the user reloads the page it won't re-submit the form.

> server side validation or errors returned are returned from multiple actions

You will need to add the errors to the session.flash so you can later read it again in a loader and return it to the UI.

> validation can be shown to the user without JavaScript

Same as before, set the validation errors in session.flash

---

My recommendation is to always let forms post to the same action, if you want to re-use an action code move the business logic to a function and re-use that, it makes everything simpler and now you can use useActionData to get the result of the action even without JS.

Another recommendation is that unless you know the users will have JS disable you shouldn't pay too much attention to that, I don't meant to ignore PE, just ignore JS disable case, you could SSR disabled any button that needs JS to work and then enable it again after hydration.

**Comment by penx** [comment]
> from your action return a redirect so if the user reloads the page it won't re-submit the form

👍 we're redirecting when a delete or create is successful. Validations or errors are not a redirect.

> You will need to add the errors to the session.flash 

Great idea, hadn't thought of that, thanks.

> My recommendation is to always let forms post to the same action, if you want to re-use an action code move the business logic to a function and re-use that, it makes everything simpler and now you can use useActionData to get the result of the action even without JS.

This makes sense, I think this is the route I need to take, given the limits above. Either composing actions by importing and calling other actions directly (perhaps?), or just writing underlying utility functions to do the CRUD operations for each entity.

> Another recommendation is that unless you know the users will have JS disable you shouldn't pay too much attention to that

I'd agree if this was an isolated case on an existing app, but I'm starting a new project and trying to get a pattern that we can repeat across the app for all entities, so _ideally_ that pattern would work without JavaScript.

> SSR disabled any button that needs JS to work

We're using your ClientOnly component (thanks yet again 😀) for a "copy to clipboard" button as this is enhanced functionality rather than core. For things that are core functionality such as a delete button (no other way to do them in the app) I would prefer they are visible up front and work when JavaScript is not available, if there was the option to build it that way.

**Comment by penx** [comment]
I now realise I can achieve this by having a form in a layout route (entity.tsx), and then a second form in an index route (entity._index.tsx), each with their own loader, action, errors and validation - then use Outlet context if I need to pass something from the layout to the index route.

I have the list entity and delete entity in the layout route, the create entity in the index route, and then a successful creation message in a third route (entity.created.tsx).
