### ISSUE TITLE
using `remix routes` with remix-flat-routes + vite breaks

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/remix#8986]
### Reproduction

run `remix routes` with a route that works with remix-flat-routes and see the output miss all routes that remix doesn't understand by default

### System Info

```shell
sh: envinfo: command not found
```

### Used Package Manager

pnpm

### Expected Behavior

for remix to understand all routes including from remix-flat-routes

### Actual Behavior

seems to assume the config still exists in `remix.config.js`

**Comment by kiliman** [comment]
This is fixed in v2.8.1, which should be released soon.

https://github.com/remix-run/remix/pull/8916
