### ISSUE TITLE
[Bug]: http status 426 Upgrade Required 

### ISSUE THREAD

**Issue by hannadrehman** [remix-run/remix#899]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [X] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

```
npx create-remix@latest
# choose Remix App Server
cd [whatever you named the project]
npm run dev
```

even tried running 
```
npm run postinstal
```

### Expected Behavior

opening  http://localhost:8002/ should run the server and serve the starter page

### Actual Behavior

getting http code 426 Upgrade Required

**Comment by hannadrehman** [comment]
had to run `yarn start:dev` also with `yarn dev`

**Comment by jacob-ebey** [comment]
Yep, not a bug. You are trying to connect to the remix dev server. This is not your application, but rather a websocket server responsible for broadcasting code changes to the browser for auto reloading in dev.
