### ISSUE TITLE
`useFetcher().Form` scrolls to top of the page even when `preventScrollReset` is used

### ISSUE THREAD

**Issue by grinkus-adapt** [remix-run/remix#8991]
### Reproduction

1. Go to https://stackblitz.com/edit/remix-run-remix-hztd2p
2. In the browser panel you'll see a link to the subpage -- navigate to it.
3. In the subpage there hopefully will be enough content for scrollbar to appear; Scroll to the bottom of the page and try submitting the form using the three buttons in red block at the bottom right-hand side of the screen.
4. It seems that a consecutive submission of the form forces the page to scroll to top. I'm not sure when or why this happens, it seems to be time-sensitive, you might need to tweak the timeout value in `app/routes/redirectme.tsx` to reproduce the behavior. I can reproduce the same issue by clicking on the "Redirect with fetcher.Form" button using the return key on the keyboard (by simply pressing it down and waiting a bit).

https://github.com/remix-run/remix/assets/12794717/0874e869-35be-4c34-92d2-082d44132a97

Might be related to #3145 and #4265.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.8.0 
    @remix-run/node: * => 2.8.0 
    @remix-run/react: * => 2.8.0 
    @remix-run/serve: * => 2.8.0 
    vite: ^5.1.0 => 5.1.5
```

### Used Package Manager

npm

### Expected Behavior

The page scrollbar should stay where it is and the page should not scroll to top no matter which button (or how fast) is clicked.

### Actual Behavior

The page sometimes scrolls to top.

**Comment by brophdawg11** [comment]
This is resolved by https://github.com/remix-run/react-router/pull/11999 and will be available in the next release
