### ISSUE TITLE
[Bug]: Half-baked documentation in the Routing documentation page

### ISSUE THREAD

**Issue by yoavporat** [remix-run/remix#902]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

v1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

Look at the documentation at https://remix.run/docs/en/v1/guides/routing under nested routes.
There are some `TODO`s left out

### Expected Behavior

I'd expect the live documentations to hold valid examples over placeholders. 

### Actual Behavior

Placeholders for future example are live.

**Comment by machour** [comment]
The routing documentation have been rewritten by @ryanflorence, enjoy!

https://remix.run/docs/en/v1/guides/routing
