### ISSUE TITLE
[Bug]: @remix-run/serve sets high `max-age` and `immutable` cache header on everything 

### ISSUE THREAD

**Issue by sheepsteak** [remix-run/remix#903]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

* Build and start an application in production that has some resources in the `public` (remix blog)
* See in dev tools that everything in `public` folder is served with a high `max-age` and `immutable`

![image](https://user-images.githubusercontent.com/1379888/144753439-bcb6ac73-335d-4782-a0eb-7dbcfe0c9b66.png)

### Expected Behavior

Only files in `public/build` should have long, immutable caching as they are fingerprinted. The `express` starter template separates the two (although it has issues with the ordering of `express.static` as shown in https://github.com/remix-run/remix/issues/677 and fixed in https://github.com/remix-run/remix/pull/678):

https://github.com/remix-run/remix/blob/57949fe0d73f79811b207fb435657da93f5306d6/packages/create-remix/templates/express/server/index.js#L13-L17

Files in the base `public` folder should have a low `max-age` of `1h` like elsewhere so that favicons, images, fonts, etc. can be updated as needed.

### Actual Behavior

Due to this line everything in `public` gets the same cache headers:

https://github.com/remix-run/remix/blob/57949fe0d73f79811b207fb435657da93f5306d6/packages/remix-serve/index.ts#L10

This is fine for the built application files in `public/build` as they are fingerprinted but not for resources like `favicon.ico`that might need to change.

**Comment by mcansh** [comment]
hey @sheepsteak this was fixed in #2363 and released in v1.3.2
