### ISSUE TITLE
View transitions are not triggered on action redirect

### ISSUE THREAD

**Issue by jahvi** [remix-run/remix#9047]
### Reproduction

1. Go to https://stackblitz.com/edit/remix-run-remix-i4nryu?file=app%2Froutes%2F_index.tsx
2. Click Submit (view transition doesn't work)

Changing the `Form` to `<Form action="/redirect" method="POST" unstable_viewTransition>` does work as expected.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.22 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.11 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.128
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.8.1 => 2.8.1
    @remix-run/node: ^2.8.1 => 2.8.1
    @remix-run/react: ^2.8.1 => 2.8.1
    @remix-run/serve: ^2.8.1 => 2.8.1
    vite: ^5.1.0 => 5.1.0
```

### Used Package Manager

pnpm

### Expected Behavior

View transitions should trigger between redirects

### Actual Behavior

View transitions are not triggered

**Comment by JasonColeyNZ** [comment]
I also am experiencing this with a redirect from a loader. I have a parent route that checks for a child route id, if none is present it finds the first id and redirects to this using standard redirect. I would think that the redirect utility should have the unstable_viewTransition as an option?

**Comment by brophdawg11** [comment]
This is fixed by https://github.com/remix-run/react-router/pull/11925 and will be available in the next Remix release 👍
