### ISSUE TITLE
process.env.DATABASE_URL is hard coded after vite build and will that considered as leakage?

### ISSUE THREAD

**Issue by ipv6sq** [remix-run/remix#9048]
### Reproduction

If you use vite + remix, 
``` typescript
// Previous in test.tsx
const db = `db@${process.env.DATBASE_URL}`

// After build, ignore the VITE_prefix thing
const db = `db@realhostport` (the var has been swapped in build time!)
```

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 638.41 MB / 32.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    Watchman: HEAD-cb47c8f - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 17.4
  npmPackages:
    @remix-run/dev: ^2.7.1 => 2.8.1
    @remix-run/eslint-config: ^2.0.0 => 2.8.1
    @remix-run/node: ^2.7.1 => 2.8.1
    @remix-run/react: ^2.7.1 => 2.8.1
    @remix-run/serve: ^2.7.1 => 2.8.1
```

### Used Package Manager

npm

### Expected Behavior

This is super concerning, it means all env should be present during build time not production run time in order to get it run

Does that mean the envs and secrets will be part of the bundle js and could be downloaded for clients? If so that would be a disaster.

I tried to use process.env.VAR in tsx pure client components and it get interpolation in build time as well.

### Actual Behavior

Build env gets hard coded and interpolated into client and server js files.

**Comment by brophdawg11** [comment]
Can you provide a small reproduction?  I'm not seeing this behavior on a fresh vite app.  

In my server build I see un-interpolated values (used in a loader in this case):

```js
const db = `db@${process.env.SECRET_VALUE}`
```

And even if I include that in client code via the component (which you shouldn't), I still see uninterpolated values that will resolve to `undefined` due to the empty `process.env` shim

```js
var n={};function s(){const o=`db@${n.SECRET_VALUE}`;
```
