### ISSUE TITLE
using the default .eslintrc.js does not lint any files that exist in .server or .client folders

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/remix#9068]
### Reproduction

Using the vite template eslint fails to lint any files in app/.client or app/.server

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.00 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.4 - ~/.asdf/installs/nodejs/20.11.1/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 17.4
  npmPackages:
    @remix-run/dev: 2.8.1 => 2.8.1 
    @remix-run/eslint-config: 2.8.1 => 2.8.1 
    @remix-run/node: 2.8.1 => 2.8.1 
    @remix-run/react: 2.8.1 => 2.8.1 
    @remix-run/serve: 2.8.1 => 2.8.1 
    vite: 5.1.6 => 5.1.6
```

### Used Package Manager

npm

### Expected Behavior

eslint lints correctly with default remix config

### Actual Behavior

eslint lints incorrectly with default remix config

**Comment by brophdawg11** [comment]
This is default `eslint` behavior when a folder begins with a dot.  Their docs give you some options but the simplest IMO is to change your folder names so they don't start with a dot: `app/whatever.client/`

https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file

![Screenshot 2024-03-18 at 10 41 36 AM](https://github.com/remix-run/remix/assets/1609022/314e26d3-72c0-400a-ad6a-9baa37b6b90b)

**Comment by lifeiscontent** [comment]
@brophdawg11 I'm specifically talking about updating the templates. you guys made changes to the tsconfig.json https://github.com/remix-run/remix/blob/main/templates/vite/tsconfig.json#L5-L8 why not the eslintrc?

**Comment by lifeiscontent** [comment]
@brophdawg11 yep, can do, I've figured out how to get this working in my own project, and `ignorePatterns` is a config key in the `.eslintrc.cjs` that can be used instead rather than passing CLI args
