### ISSUE TITLE
@remix/node should not be forced to install polyfills

### ISSUE THREAD

**Issue by GiveMe-A-Name** [remix-run/remix#9078]
### Reproduction

In [@remix/node](https://github.com/remix-run/remix/blob/main/packages/remix-node/globals.ts#L46-L70), there has a globalInstall function.
```js
export function installGlobals() {
  global.File = NodeFile;

  global.Headers = NodeHeaders as typeof Headers;
  global.ReadableStream = NodeReadableStream;
  //...
}
```
In this function,  global.ReadableStream will replace by NodeReadableStream whether global.ReadableStream already was exist.

But in some case, it would cause different instance in a context.

Like this:

```js
import { installGlobals } from "@remix-run/node";

const req = new Request('http://localhost:8080') // provided by node v18, bun or worker runtime.

installGlobals();

console.log("req is instance of Request: ", req instanceof Request); // req is instance of Request: false
```

### System Info

```shell
System:
    OS: macOS 13.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 125.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/node
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.6
  npmPackages:
    @remix-run/node: ^1.12.0 => 1.13.0
```

### Used Package Manager

npm

### Expected Behavior

It should like: 
```js
export function installGlobals() {
  if(!global.File) {
    global.File = NodeFile;
  }
  
  if(!global.ReadableStream) {
   global.ReadableStream = NodeReadableStream;
  }
  
  //...
}

```

### Actual Behavior

```js
export function installGlobals() {
  global.File = NodeFile;

  global.Headers = NodeHeaders as typeof Headers;
  global.ReadableStream = NodeReadableStream;
  //...
}
```

**Comment by brophdawg11** [comment]
Nothing _requires_ polyfill usage in Remix - it's up to you whether you call [`installGlobals`](https://remix.run/docs/en/main/start/v2#installglobals).  We enable it by default when using `remix-serve`, but if you want to use the built-ins you can use your own express server and remove [this line](https://github.com/remix-run/remix/blob/main/templates/express/server.js#L28).  

From what I've heard, you probably don't want to use the built-ins on Node 18 (buggy) but folks have had much more success with the built-ions on Node 20.
