### ISSUE TITLE
Vite thinks certain modules are CommonJS with Remix

### ISSUE THREAD

**Issue by fire332** [remix-run/remix#9097]
### Reproduction

Broken (with Remix): https://stackblitz.com/edit/remix-run-remix-namaq5?file=app%2Froutes%2F_index.tsx
Working (no Remix): https://stackblitz.com/edit/vitejs-vite-dbuogf?file=src%2Fmain.ts

These are both stock stackblitz templates but with `ts-luxon` added and imported.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.8.1 
    @remix-run/node: * => 2.8.1 
    @remix-run/react: * => 2.8.1 
    @remix-run/serve: * => 2.8.1 
    vite: ^5.2.2 => 5.2.2
```

### Used Package Manager

npm

### Expected Behavior

No errors.

### Actual Behavior

```log
[vite] Internal server error: [vite] Named export 'DateTime' not found. The requested module 'ts-luxon' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ts-luxon';
const {DateTime} = pkg;
```

**Comment by hi-ogawa** [comment]
This is more like Vite SSR (or NodeJS) issue/limitation than Remix issue. Your 2nd reproduction is Vite browser, so it works differently.

Vite SSR tries to preserve NodeJS import semantics to surface the same error during dev as build. For example, you can see the following code doesn't work on Node:
https://stackblitz.com/edit/remix-run-remix-sfssok?file=repro.mjs

```tsx
// node repro.mjs

// -- not ok
// import { DateTime } from 'ts-luxon';
// console.log(DateTime)

// -- ok
import lib from 'ts-luxon';
console.log(lib.DateTime);
```

One workaround Vite provides is to use `ssr.optimizeDeps + noExternal` to pre-process `ts-luxon` and make esm version of it internally. For example, this config should work for this particular case:
https://stackblitz.com/edit/remix-run-remix-sfssok?file=vite.config.ts

```tsx
export default defineConfig({
  plugins: [remix(), tsconfigPaths()],
  ssr: {
    optimizeDeps: {
      include: ["ts-luxon"]
    },
    noExternal: ["ts-luxon"]
  }
});
```
