### ISSUE TITLE
[bug] Relative `redirect` is not behaving as expected.

### ISSUE THREAD

**Issue by alexanderson1993** [remix-run/remix#91]
Suppose you have the following page structure:

/app/routes/index.js
/app/routes/page1.js
/app/routes/page1/page2.js

And in page2.js, you have the following action:

```js
export let action: Action = async () => {
  return redirect("..");
};
```

When that action is called, you would expect the browser to navigate from `/page1/page2` to `/page1`. However, it is currently navigating all the way back to `/`.

> Note: Earlier today, the app wouldn't even build with a relative redirect, with a very unhelpful Rollup "Unexpected token" error. I was able to resolve the error by removing that action altogether. Later, when I was testing it again to make this issue, I wasn't able to reproduce that error.

**Comment by zachdtaylor** [comment]
I just noticed an inconsistency with browser vs Remix behavior here. If there's no js on the page, the `redirect('..')` works as expected and goes from `/page1/page2` to `/page1`. If there is js on the page, then it goes all the way back to `/`.

**Comment by oliverjam** [comment]
Yeah I just hit this problem too. The mismatch between the no-js and js experience is especially concerning, since it makes this impossible to work around. Some of our users will get the wrong result whichever way we go.

**Comment by mcansh** [comment]
@oliverjam can you open a PR with a failing test case? 🙏 https://github.com/remix-run/remix/blob/dev/integration/bug-report-test.ts
