### ISSUE TITLE
docs: Invalid link for `Splat Route` at `Not found handling`

### ISSUE THREAD

**Issue by tryonelove** [remix-run/remix#9110]
### Reproduction

1. Open [Not found (404) handling](https://remix.run/docs/en/main/guides/not-found) page
2. Look for `Splat route` link
![image](https://github.com/remix-run/remix/assets/20541870/7d905a29-654d-4e9d-8bc7-b366d2e30bca)
3. Follow the link for `Splat route`
4. There's no mention of `Splat` at all

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 11.96 GB / 31.93 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/css-bundle: ^2.8.1 => 2.8.1 
    @remix-run/dev: ^2.8.1 => 2.8.1 
    @remix-run/node: ^2.8.1 => 2.8.1 
    @remix-run/react: ^2.8.1 => 2.8.1 
    @remix-run/serve: ^2.8.1 => 2.8.1
```

### Used Package Manager

pnpm

### Expected Behavior

Not sure what's expected by design, I'd consider [Route File Naming](https://remix.run/docs/en/main/file-conventions/routes#splat-routes) as an answer, or at least a paragraph that describes Splats in the Route Configuration.

### Actual Behavior

No `Splat route` information on the `Route Configuration` page

**Comment by brophdawg11** [comment]
Thanks!  Fixed in https://github.com/remix-run/remix/commit/b85643d09e5dc58a8506d155f8c5e66cb1c82d7c
