### ISSUE TITLE
SPA mode index.html default meta tags

### ISSUE THREAD

**Issue by Isos9** [remix-run/remix#9121]
### Reproduction

Hi, I have a pretty simple remix setup based on Netlify template.

```
export default defineConfig({
	plugins: [remix({ ssr: false }), netlifyPlugin(), tsconfigPaths()]
});
```
You can see that I enabled SPA mode.
When I generate the index.html on build, I would expect that at least my meta tags from root route are included in the server build step, but it's not the case.
why is it always the default ones?

the server entrypoint is the default spa one:

```
export default function handleRequest(
	request: Request,
	responseStatusCode: number,
	responseHeaders: Headers,
	remixContext: EntryContext
) {
	let html = renderToString(<RemixServer context={remixContext} url={request.url} />);
	html = '<!DOCTYPE html>\n' + html;
	return new Response(html, {
		headers: { 'Content-Type': 'text/html' },
		status: responseStatusCode
	});
}
```

Thanks

### System Info

```shell
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.37 GB / 15.35 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - /run/user/1000/fnm_multishells/633358_1711209975664/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - /run/user/1000/fnm_multishells/633358_1711209975664/bin/npm
    bun: 1.0.31 - ~/.bun/bin/bun
  npmPackages:
    @remix-run/dev: ^2.8.1 => 2.8.1
    @remix-run/node: ^2.8.1 => 2.8.1
    @remix-run/react: ^2.8.1 => 2.8.1
    @remix-run/serve: ^2.8.1 => 2.8.1
    vite: ^5.0.0 => 5.1.3
```

### Used Package Manager

bun

### Expected Behavior

```
<head>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width,initial-scale=1,viewport-fit=cover"
  />
  <title>My Title</title>
  <meta name="description" content="my description" />
</head>
```

### Actual Behavior

```
<head>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width,initial-scale=1,viewport-fit=cover"
  />
  <title>Loading...</title>
</head>
```

**Comment by brophdawg11** [comment]
I think you are probably missing a [`HydrateFallback`](https://remix.run/docs/en/main/route/hydrate-fallback) export from your root route file - this is all that is rendered on the server build in [SPA mode](https://remix.run/docs/en/main/future/spa-mode#what-is-spa-mode):

> The index.html is generated from the `HydrateFallback` component in your `root.tsx` route. The initial "render" to generate the `index.html` will not include any routes deeper than root. This ensures that the `index.html` file can be served/hydrated for paths beyond `/` (i.e., `/about`) if you configure your CDN/server to do so.

In order to avoid duplication of the app shell between the `HydrateFallback` and the default component, you can use the root [`Layout` export](https://remix.run/docs/en/main/file-conventions/root#layout-export).
