### ISSUE TITLE
`maxPriorityFeePerGas` is not set when remix does `eth_sendEstimateGas`, while `maxFeePerGas` is set. If `maxFeePerGas` is set, the other should be set as well

### ISSUE THREAD

**Issue by KillariDev** [remix-run/remix#9129]
### Reproduction

1) Go to https://remix.ethereum.org/
2) Attempt to deploy a contract to mainnet
3) Observe from traffic that `eth_sendEstimateGas` is sent to wallet with `maxFeePerGas` field but no `maxPriorityFeePerGas` field.

### System Info

```shell
Windows 11
Chrome
Metamask
```

### Used Package Manager

npm

### Expected Behavior

`eth_sendEstimateGas` request with both fields

### Actual Behavior

`eth_sendEstimateGas` request with only one of the fields

**Comment by kiliman** [comment]
I believe you're looking for the Ethereum Remix IDE repo. This the Remix Web Framework.

https://github.com/ethereum/remix-ide
