### ISSUE TITLE
[Bug]: Environment Variable Configuration on the Official Guides Not Working

### ISSUE THREAD

**Issue by weissleon** [remix-run/remix#914]
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.17.6

### Steps to Reproduce

1. install dotenv package using npm.
2. create .env file and add variable.
3. add the following script to the package.json =>   "dev": "node -r dotenv/config node_modules/.bin/remix dev",
4. run "npm run dev"

### Expected Behavior

The environment variables should be loaded without any errors thrown in the console.

### Actual Behavior

After I run the script, I get the following error message in the console.

---
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-app-template@ dev: `node -r dotenv/config node_modules/.bin/remix dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remix-app-template@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by vadimegorov13** [comment]
Hello @weissleon, I couldn't figure out why this bug occurs, but I found a workaround for it.

1. Change dev script back to
`"dev": "remix dev"`

2. Import dotenv to root file (root.tsx or root.jsx)
`import * as dotenv from 'dotenv';

dotenv.config();`

3. Use your environment variables wherever you want. For example, I did this for my firebase config:
`export const config = {
  apiKey: process.env.API_KEY,
  authDomain: process.env.AUTH_DOMAIN,
  projectId: process.env.PROJECT_ID,
  storageBucket: process.env.STORAGE_BUCKET,
  messagingSenderId: process.env.MESSAGING_SENDER_ID,
  appId: process.env.APP_ID,
};
`

Good luck!

**Comment by antoinerey** [comment]
For what it's worth, I also had this error when using pnpm to install dependencies, and it does not need `dotenv` to fail.

```bash
pnpm create remix some-project # Do not automatically run npm install
cd some-project
pnpm install
```

Then, set `node node_modules/.bin/remix dev` to the package.json, and run `pnpm dev`.

---

@weissleon, it works great with `yarn` though. So, I'd suggest using it for now if that's possible for you.

**Comment by richmeij** [comment]
@vadimegorov13 While that works, the whole point of using it in the dev script is to only use it during dev.

@antoinerey It fails for me using yarn as well. I'm using Windows though, so that might be the problem. @weissleon Are you using Windows as well by any chance?

**Comment by richmeij** [comment]
This definitely has to do with Windows. I guess it has to do with the Windows shell and the scripts not working correctly together.
As a workaround, if you change the dev script to point to the actual remix dev cli, it works for me:

`"dev": "node -r dotenv/config ./node_modules/@remix-run/dev/cli.js",`

**Comment by weissleon** [comment]
@vadimegorov13 Thank you for your suggestion 👍. However, as @richmeij said, it would be manually injecting codes that are to be removed in the production.

**Comment by weissleon** [comment]
> This definitely has to do with Windows. I guess it has to do with the Windows shell and the scripts not working correctly together.
> 
> As a workaround, if you change the dev script to point to the actual remix dev cli, it works for me: `"dev": "node -r dotenv/config ./node_modules/@remix-run/dev/cli.js",`

@richmeij 
Yes, I am currently using Windows 10.

I have tested your workaround, and yes it works! Thank you so much! 👍🎉

Still, I believe this issue should be remained open as 
1) Remix team should be aware of this issue and either correct the error or update the Docs.
2) this workaround should be shared by everyone struggling with environment variables in Windows until the team resolves this issue.

Again, thank you @richmeij 👍

**Comment by loke-dev** [comment]
I have worked on a project on macos for a while and started it up on a windows machine today and had this exact issue. Changing the dev script to `node -r dotenv/config ./node_modules/@remix-run/dev/cli.js` made it work. Thank you!

**Comment by nick-krantz** [comment]
@richmeij Your workaround worked for me on Windows as well! Thank you!

**Comment by mkizka** [comment]
It also worked with [dotenv-cli](https://www.npmjs.com/package/dotenv-cli).
```
"dev": "dotenv -- remix dev"
```

**Comment by marvinwu** [comment]
i had this issue with mac + pnpm as well , switch to mac+npm resolved this issue

**Comment by mkizka** [comment]
Remix now loads .env file! 🎉 https://github.com/remix-run/remix/pull/2063
