### ISSUE TITLE
"Server-only module referenced by client" after upgrading to 2.7.1

### ISSUE THREAD

**Issue by btomaj** [remix-run/remix#9143]
### Reproduction

https://stackblitz.com/~/github.com/btomaj/shopify-app-template-remix-testing/tree/component

Building will throw an error

### System Info

```shell
  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
    Memory: 8.69 GB / 11.99 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

npm

### Expected Behavior

Can build

### Actual Behavior

> 7:21:26 pm [vite] Pre-transform error: Server-only module referenced by client
> 
> '~/shopify.server' imported by 'app/routes/components/Component.tsx'
> 
> See https://remix.run/docs/en/main/future/vite#splitting-up-client-and-server-code

**Comment by kiliman** [comment]
In Remix, only _routes_ can contain `loader` and `action` exports. 

You are treating `Component.tsx` as a route, but it is not a valid route filename. Since you have a folder, you are using `colocation`, so the route module needs to be named `route.tsx` (`app/routes/components/route.tsx`)
https://remix.run/docs/en/main/file-conventions/routes#folders-for-organization

Since Remix doesn't see it as a valid route module, it complains that you're importing from a server module. 

If this is meant to be a shared component, then move it out of the `routes` folder.

**Comment by btomaj** [comment]
@kiliman based on what you’re saying, I’m a little confused how I’m meant to implement [Full Stack Components](https://www.epicweb.dev/full-stack-components).

**Comment by kiliman** [comment]
See my example here

⚡ StackBlitz https://stackblitz.com/edit/remix-run-remix-zv9ujq

**Comment by btomaj** [comment]
> See my example here
> 
> ⚡ StackBlitz https://stackblitz.com/edit/remix-run-remix-zv9ujq

@kiliman I can't get that to run. It prints this in console

>

>  [callSiteLocation@
> depd@
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13780
> @
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:14872
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:15558
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:13457
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:54:10539
> executeUserEntryPoint@https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:125:736
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:318:173
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:318:186
> _0x2b0ec5@https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:350:56035
> _0x365317@https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:352:101942
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:352:620043
> @https://remixrunremixzv9ujq-amga.w-corp-staticblitz.com/blitz.d0228c83.js:371:1287]
