### ISSUE TITLE
useLoaderData hook issue while running in dev mode

### ISSUE THREAD

**Issue by DisruptLive** [remix-run/remix#9168]
### Reproduction

I created an basic Remix V2 app for use in testing by running `npx create-remix@latest`

I wrote a simulated API backend method in a file stored at the root of my application titled `./data/notes.js` which simply returns JSON data as retrieved from a JSON file:

```
export async function getStoredNotes() {
  const rawFileContent = await fs.readFile('notes.json', { encoding: 'utf-8' });
  const data = JSON.parse(rawFileContent);
  const storedNotes = data.notes ?? [];
  return storedNotes;
}
```

The client side consists of 2 simple routes, `index` and `notes` which both use `NavLink` components for navigation between the 2 routes:

```
import { NavLink } from '@remix-run/react';
...
<NavLink to="/">Home</NavLink>
<NavLink to="/notes">Notes</NavLink>
```

In the `notes` route, i have the following `loader` function which makes a call to my simulated API method:

```
import { getStoredNotes } from '~/data/notes';
...
export const loader:LoaderFunction = async () => {
  try {
    const notes = await getStoredNotes();
    return json(notes);

  } catch (error) {
    return json({ errorMessage: 'Failed to retrieve stored notes.', errorDetails: error }, { status: 400 });
  }
}
```

In the `notes` main component function i receive that data using the `useLoaderData` hook and attempt to print the returned JSON data to the console:

```
export default function NotesView() {

  const notes = useLoaderData<typeof loader>();

  console.log(notes);

  return (
    <main>
      <NoteList notes={notes as Note[] || []} />
    </main>
  )
}
```

When i run an `npx run build` and subsequently `npx run serve` on my local machine, the JSON data loads and prints to the console correctly:

`{"notes":[{"title":"my title","content":"my note","id":"2024-03-28T05:22:52.875Z"}]}`

Subsequently while still running `serve` navigating between the 2 routes client side work as expected and i see the same JSON data print to the console successfully.

**The Issue only occurs when i use `npx run dev` during development testing as follows:**

Initial page load rendered on the dev server works as expected and prints the JSON to the console, however, when i subsequently navigate client side by clicking the `NavLink` component links, i am seeing a strange result print to the console:

```
export const notes = [
    {
        title: "my title",
        content: "my note",
        id: "2024-03-28T05:22:52.875Z"
    }
];
```

Quite literally a JavaScript object declaration is what prints to the console just like that.
Is this the expected behavior, a bug in V2, or a missing configuration option or setting?

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 39.54 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 123.1.64.113
    Chrome: 123.0.6312.87
    Safari: 17.3.1
    Safari Technology Preview: 17.4
```

### Used Package Manager

npm

### Expected Behavior

When running in development mode via `npx run dev` and i navigate to a route client side via a `NavLink` or `Link` and JSON is retrieved via the `useLoaderData` hook, the expected JSON response should be in JSON format.

### Actual Behavior

When running in development mode via `npx run dev` and i navigate to a route client side via a `NavLink` or `Link` and JSON is retrieved via the `useLoaderData` hook, the actual response is not in JSON format, but rather is returned as a JavaScript object declaration.

**Comment by DisruptLive** [comment]
I outlined how to reproduce the issue albeit i did not include all of the code. How else or what else would you like me to provide?

**Comment by kiliman** [comment]
@DisruptLive I commented on your StackOverflow post with a link to ⚡️StackBlitz showing that I wasn't able to get an error, so there seems to be something odd with your project.

https://stackblitz.com/edit/remix-run-remix-xhfw3r?file=app%2Froutes%2Fnotes.tsx

**Comment by kiliman** [comment]
The `.server` folder is because you used Node API `node:fs`, etc. Those should only run on the server. 

https://remix.run/docs/en/main/discussion/server-vs-client#server-modules

BTW: It's not a _hidden_ folder. It's actually a suffix (*.server). So can be `services.server`, `models.server`, or even `.server` (_blank_.server)

I don't think it's due to the location of the _notes.json_ file. You didn't specify in your question, so I just guessed.

**Comment by brophdawg11** [comment]
This is where a working reproduction would be helpful - that way we are looking at _exactly_ the same setup

**Comment by brophdawg11** [comment]
This looks like default behavior of the Vite dev server.  By default it will resolve files from the root of your project folder, so `http://localhost:5173/notes.json` would resolve the file contents.  

It seems that it also allows extension-less loads and matches `http://localhost:5173/notes` to the `notes.json` file and exposes it as a JS module.  So when you route to that URL Vite is serving that file before it reaches the Remix code to load the notes.  You can replicate this behavior and load `package.json` as a module via `http://localhost:5173/package`.

You can control what directories Vite will serve via the [config file](https://vitejs.dev/config/server-options.html#server-fs-allow) if that's of any help, but otherwise yeah I think moving the `notes.json` file into `app/` or `mocks/` or something is the right call.

**Comment by brophdawg11** [comment]
It looks like this is the default behavior per https://vitejs.dev/config/shared-options.html#resolve-extensions.  You could add your own config without `.json` to resolve this as well.  Feels like that probably shouldn't be in there by default IMO 🤷

**Comment by iudchenko** [comment]
Just want to thank you guys for the comments in this thread, as I had similar issues. The example code is from the course [Remix.js - The Practical Guide ](https://www.udemy.com/course/remix-course/?couponCode=ST7MT41824) by Maximilian Schwarzmüller. The course is great, but it was done with Remix v1 and in v2 the code would need some adjustments to work correctly.

**Comment by tfreeborn** [comment]
Big thank you from me as well!  I am doing the same Maximilian Schwarzmüller course and am dealing with the same issue.  It seems if you get one of these courses for a big discount, they tend to be frustratingly outdated.
