### ISSUE TITLE
[Feature]: Cloudflare Pages Adapter

### ISSUE THREAD

**Issue by mehmetcansahin** [remix-run/remix#919]
### What is the new or updated feature that you are suggesting?

Cloudflare Pages Adapter support

### Why should this feature be included?

We can create a full stack app with the functions support coming to cloudflare pages. We need new adapter support to use Remix.

**Comment by bradleyg** [comment]
Would be great to support Pages! Announcement [here](https://blog.cloudflare.com/cloudflare-pages-goes-full-stack/), and docs [here](https://developers.cloudflare.com/pages/platform/functions).

**Comment by dane-stevens** [comment]
This would be awesome!

**Comment by mehmetcansahin** [comment]
PR: https://github.com/remix-run/remix/pull/985 Thanks @jacob-ebey @MichaelDeBoey

**Comment by mehmetcansahin** [comment]
I am closing this issue. Development was completed within 1 week. Thank you for this development. @jacob-ebey @MichaelDeBoey @mjackson I hope it will be merged to master branch as soon as possible.
