### ISSUE TITLE
Relative path does not resolve correctly with flat file routes with redirect

### ISSUE THREAD

**Issue by kenn** [remix-run/remix#9196]
### Reproduction

Related to https://github.com/remix-run/remix/issues/9139

Create a new project

```zsh
npx create-remix@latest
```

then create two routes — `app/routes/a.b.c.tsx` and `app/routes/a.b.e.tsx`

`app/routes/a.b.c.tsx`
```tsx
import { Form, redirect } from '@remix-run/react'

export async function action() {
  return redirect('../e')
}

export default function Page() {
  return (
    <>
      <Form method="post">
        <button>Go</button>
      </Form>
    </>
  )
}
```

`app/routes/a.b.e.tsx`
```tsx
export default function Page() {
  return <>Success!</>
}
```

Now, go to `http://localhost:5173/a/b/c` and click the submit button.

You'll be redirected to `http://localhost:5173/e` instead of `http://localhost:5173/a/b/e`, which I would expect.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M3
    Memory: 108.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Brave Browser: 123.1.64.109
    Chrome: 123.0.6312.59
    Safari: 17.3.1
  npmPackages:
    @remix-run/dev: ^2.8.1 => 2.8.1 
    @remix-run/node: ^2.8.1 => 2.8.1 
    @remix-run/react: ^2.8.1 => 2.8.1 
    @remix-run/serve: ^2.8.1 => 2.8.1 
    vite: ^5.1.0 => 5.2.6
```

### Used Package Manager

pnpm

### Expected Behavior

I would expect to be redirected to http://localhost:5173/a/b/e

### Actual Behavior

Redirected to http://localhost:5173/e

**Comment by brophdawg11** [comment]
Redirects in Remix and React Router are relative to the Route Hierarchy by default: https://reactrouter.com/en/main/start/overview#relative-links

Your route files create a route tree of:

```sh
> npx remix routes
<Routes>
  <Route file="root.tsx">
    <Route index file="routes/_index.tsx" />
    <Route path="a/b/c" file="routes/a.b.c.tsx" />
    <Route path="a/b/e" file="routes/a.b.e.tsx" />
  </Route>
</Routes>
```

So when you `redirect('../e')` from the action in the route for `/a/b/c` you are going "up one route" to the root, then going to `e` which lands you at `/e`.  If you added a parent route file `routes/a.b.tsx` then you'd have the proper Route hierarchy for this approach.

Or, if you want URL-segment relative links, in the React component/shooks there's a `relative="path"` option  for this (https://reactrouter.com/en/main/components/link#relative) but that doesn't exit for redirect which is just a wrapper around `new Response(null, { status: 3xx, ... })`.

For redirects, you can do it with the URL constructor:

```ts
export function loader({ request }: LoaderFunctionArgs) {
  let currentUrl = request.url.endsWith("/") ? request.url : `${request.url}/`;
  let redirectUrl = new URL("../e", currentUrl).pathname;
  return redirect(redirectUrl);
}
```

**Comment by brophdawg11** [comment]
I'm not sure what you mean by "depending on internals"?  

I don't think we'll extend `relative="path"` to `redirect` because in hindsight after we shipped that API we realized how easy it would be to do in user-land via something like the above (`let to = new URL("../e", window.origin + useLocation().pathname).pathname` and `<Link to={to} />`)

**Comment by kenn** [comment]
"depending on internals" — depending on how the route files are structured, not on the path string itself. As you mentioned I might decide to add `routes/a.b.tsx` for a different reason, and now the relative links that depended on the current behavior are now broken. It's a brittle system, and people are likely using it (if ever) without knowing it's going to break that way.

So that's why I asked "is anyone happy with how relative paths resolve today?"

Backward compatibility aside, making the public user-facing API more intuitive and unified between server and client feels like a happy path (pun intended) for everyone.

**Comment by brophdawg11** [comment]
I wouldn't consider those internals - since you define the route hierarchy.  

Your described issue goes both ways - relative paths (as well as absolute paths) are _always_ brittle if you alter your URLs.

The relative routing is currently unified - all routes are relative to the route hierarchy which is a core feature of v6 and nested routing (https://reactrouter.com/en/main/start/overview#relative-links).  It's only the opt-in `path=relative` behavior that is not unified in `redirect`, and will likely remain as such for the reason explained above.
