### ISSUE TITLE
[Feature]: Expose something like usePrefetchBehavior to allow programmatic prefetching

### ISSUE THREAD

**Issue by bogas04** [remix-run/remix#921]
### What is the new or updated feature that you are suggesting?

Currently prefetching is limited to using `<Link />` or `LinksFunction`, however at times we do want to prefetch a route and its assets in an effect (say on click of a button based on a condition).

```tsx
function Component () {
  const navigate = useNavigate();

  function handleClick () {
    if (condition1) {
     navigate("route");
     return;
    }
    alert("Error!");
  }

  return <button onClick={handleClick}>Click Me</button>
}
```

suggestion:

```tsx
function Component () {
  const navigate = useNavigate();
  const {prefetch} = usePrefetchHandler("route");

  useEffect(() => {prefetch()}, [prefetch]);

  function handleClick () {
    if (condition1) {
     navigate("route");
     return;
    }
    alert("Error!");
  }

  return <button onClick={handleClick}>Click Me</button>
}
```

### Why should this feature be included?

Basically for ergonomics. I understand this can be worked around (even better) by properly using `LinksFunction` or rendering a dummy `<Link to="route" prefetch="render" />` based on a condition, but same could be argued for `<Navigate />` and `useNavigate()`, yet they both do exist.

**Comment by sergiodxa** [comment]
You could render a `<link rel="prefetch" as="data" href="path" />` in the body without using the LinksFunction or rendering a Link component, actually the Link component does that.

**Comment by bogas04** [comment]
Will it also prefetch the data and css of that particular path?

**Comment by sergiodxa** [comment]
@bogas04 if you want to prefetch the data and links and code you can use the (undocumented) `PrefetchPageLinks` component, you use it this way:
```tsx
<PrefetchPageLinks page="/my/page/full/path" />
```
It will just render the link[rel=prefetch] tags without rendering an anchor tag, note the `page` props needs to be the full path of the page you want to prefetch, with any query string so it can prefetch the data correctly.

**Comment by bogas04** [comment]
Ah, this is great! Thanks a lot. Any way I can assist in documenting it?

**Comment by sergiodxa** [comment]
@bogas04 you could send a PR documenting it

**Comment by bogas04** [comment]
Created a PR https://github.com/remix-run/remix/pull/948 @sergiodxa. Also another one for the CLA https://github.com/remix-run/remix/pull/949

**Comment by sergiodxa** [comment]
@bogas04 you can sign the CLA in the same PR you send your changes

**Comment by bogas04** [comment]
Thanks! I've pushed the CLA commit to same PR.

**Comment by bogas04** [comment]
This was merged.

https://remix.run/docs/en/v1/api/remix#prefetchpagelinks-
