### ISSUE TITLE
[Feature]: Effort for Translations (Spanish)

### ISSUE THREAD

**Issue by patternina** [remix-run/remix#922]
### What is the new or updated feature that you are suggesting?

I would like to set up an effort to translate the Remix Docs into Spanish.

### Why should this feature be included?

This should be considered to have the documentation available for Spanish-native language speakers.

**Comment by machour** [comment]
Closing in favor of this discussion: https://github.com/remix-run/remix/discussions/3686
Please comment there if you're still interested.
