### ISSUE TITLE
Vitest looks for package.json in every workspace when using vitePlugin

### ISSUE THREAD

**Issue by btomaj** [remix-run/remix#9243]
### Reproduction

Using `vitest.workspaces.ts` with
```javascript
export default [
    "tests/*/vitest.config.{ts,js}",
];
```
and putting the following in a `vitest.config.ts` file
```javascript
import rootConfig from "../../vite.config";
export default mergeConfig(rootConfig, defineConfig({
 ...
});
```
when the root `vite.config.ts` file from Remix contains
```javascript
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig, type UserConfig } from "vite";

export default defineConfig({
  ...
  plugins: [
    remix({
      ignoredRouteFiles: ["**/.*"],
    }),
    tsconfigPaths(),
  ],
  ...
}) satisfies UserConfig;
```
causes the following error because Vite or Vitest looks for `package.json` in every workspace directory
> Error: Could not read package.json: Error: ENOENT: no such file or directory, ...

Using `react()` instead of `remix()` for `plugins: []` doesn't cause this error, so I hypothesise that `vitePlugin` from `@remix-run/dev` looks for `package.json` in the workspace directories, causing this error.

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M3
    Memory: 1.24 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.22 - ~/Library/Mobile Documents/com~apple~CloudDocs/Projects/custom-registration-form.nosync/node_modules/.bin/yarn
    npm: 9.8.1 - ~/Library/Mobile Documents/com~apple~CloudDocs/Projects/custom-registration-form.nosync/node_modules/.bin/npm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.4.1
  npmPackages:
    @remix-run/dev: ^2.7.1 => 2.8.1 
    @remix-run/eslint-config: ^2.7.1 => 2.8.1 
    @remix-run/node: ^2.7.1 => 2.8.1 
    @remix-run/react: ^2.7.1 => 2.8.1 
    @remix-run/serve: ^2.7.1 => 2.8.1 
    @remix-run/testing: ^2.7.1 => 2.8.1 
    vite: ^5.1.3 => 5.2.8
```

### Used Package Manager

npm

### Expected Behavior

Vitest runs the tests, and Vite/Vitest doesn't look for `package.json` in the workspace directories.

### Actual Behavior

Vite/Vitest is looking for `package.json` in the workspace directories.

**Comment by hi-ogawa** [comment]
Normally users don't need to include Remix plugin for Vitest, so the general recommendation is to disable it as described in https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook
Do you have some issues with disabling it?

**Comment by btomaj** [comment]
Thank you @hi-ogawa I had missed that part of the documentation. That solved my problem.
