### ISSUE TITLE
[Bug]: useSubmitImpl() not respects incoming query search when using POST

### ISSUE THREAD

**Issue by jacargentina** [remix-run/remix#927]
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

17.0.1

### Steps to Reproduce

- `routes/myform.tsx` which is navigated like this `http://localhost:3000/myform?returnUrl=/blog`
- myform.tsx calls `submit({values: ...}, {method: 'post'})`
- myform.tsx action simply returns null
- URL now is missing the `returnUrl=/blog` query string

### Expected Behavior

URL should remain unchanged and maintain its query string

### Actual Behavior

URL only points to the plain route, without any query string

**Comment by machour** [comment]
Tracked in #931

**Comment by mcansh** [comment]
🤖 Hello there,

We just published version `v1.6.8` which includes a fix for this. If you'd like to take it for a test run please try it out and let us know what you think!

Thanks!
