### ISSUE TITLE
redirect with 307 does not work as expected

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/remix#9310]
### Reproduction

Go to https://stackblitz.com/edit/remix-run-remix-bxuuhs?file=app%2Froutes%2F_index.tsx
Click submit and see that `actionData` is not populated

**Context**
I've removed `<Scripts />` from root.tsx to turn JavaScript "off"

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.1 
    @remix-run/node: * => 2.9.1 
    @remix-run/react: * => 2.9.1 
    @remix-run/serve: * => 2.9.1 
    vite: ^5.1.0 => 5.2.10
```

### Used Package Manager

npm

### Expected Behavior

I'd expect the 307 redirect to work

### Actual Behavior

405 Method Not Allowed

**Comment by sergiodxa** [comment]
This is expected, when you do a redirect after a POST, the browser sends a new GET to the target location, so any response body sent by the POST is lost.

**Comment by lifeiscontent** [comment]
@sergiodxa it seems 307 doesn't work correctly either. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

I've updated accordingly

**Comment by brophdawg11** [comment]
You're losing the [`?index`](https://remix.run/docs/en/main/guides/index-query-param) query param when you do `Location: url.pathname` so the POST that is re-sent is trying to hit the root route action and there isn't one, so you're getting a 405.  If you need to re-POSt to the same action you'll need to append `?index` to your `Location` header (and then avoid redirect loops in some way 😉 ).

**Comment by lifeiscontent** [comment]
@brophdawg11 @sergiodxa I guess what I'm wondering is how I could potentially achieve something like this as highlighted by @ryanflorence in roadmap 9. https://youtu.be/fHel4d-It5Q?list=PLXoynULbYuEDR_w8LJKRIkGheWpFfiMiR&t=757
