### ISSUE TITLE
useLoaderData<typeof loader> returns type JsonifyObject<T> rather than T

### ISSUE THREAD

**Issue by jasperdunn** [remix-run/remix#9321]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-wtn1cs?file=app%2Froutes%2F_index.tsx
Mouse over the variable `data`: `const data = useLoaderData<typeof loader>();`

I also tried casting:

```ts
const data = useLoaderData() as Foobar;
```

I get this error message:

```
Conversion of type 'JsonifyObject<Foobar>' to type 'Foobar' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

### System Info

```shell
System:
    OS: macOS 13.6.6
    CPU: (12) arm64 Apple M2 Max
    Memory: 537.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.0.0 - ~/.nvm/versions/node/v22.0.0/bin/node
    npm: 10.5.1 - ~/.nvm/versions/node/v22.0.0/bin/npm
    bun: 1.1.0 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 124.0.6367.79
    Safari: 17.4.1
  npmPackages:
    @remix-run/cloudflare: ^2.8.1 => 2.8.1 
    @remix-run/cloudflare-pages: ^2.8.1 => 2.8.1 
    @remix-run/dev: ^2.8.1 => 2.8.1 
    @remix-run/react: ^2.8.1 => 2.8.1 
    vite: ^5.1.0 => 5.2.6
```

### Used Package Manager

npm

### Expected Behavior

I expect `useLoaderData<typeof loader>` to return `T` instead of `JsonifyObject<T>`

### Actual Behavior

useLoaderData<typeof loader> returns type JsonifyObject<T> rather than T

**Comment by brophdawg11** [comment]
This is expected behavior because your JSON object is serialized over the network via `JSON.stringify`, so `JsonifyObject` handles the conversions that happen there - such as converting `Date`'s to `strings`'s.  You'll still see that `data.ok` is a boolean after the `JsonifyObject` transformation.

**Comment by jasperdunn** [comment]
Ok, then what approach should I take then to get the type checker working then?

Thanks

**Comment by jasperdunn** [comment]
Ahhh, I didn't understand the problem properly.

My issue is this:

```ts
type Foobar = { createdTimestamp: Date };

export const loader = () => {
  return json({ createdTimestamp: new Date() });
};

 const data = useLoaderData<typeof loader>();
 const data2: Foobar = data;
```

```
Type 'JsonifyObject<Foobar>' is not assignable to type 'Foobar'.
  Types of property 'createdTimestamp' are incompatible.
    Type 'string' is not assignable to type 'Date'.
```

**Comment by jasperdunn** [comment]
Okay I kept digging through old issues...

Seems like one solution is to use [remix-typedjson](https://github.com/kiliman/remix-typedjson), it works well for me.
Would be nice to have this functionality built into remix, at least some official documentation on possible solutions to this common issue.

**Comment by kiliman** [comment]
Yes. That's the reason I wrote `remix-typedjson`

However, the new _Single Fetch_ feature in Remix v2.9 solves this natively. 

https://github.com/remix-run/remix/blob/main/CHANGELOG.md#single-fetch-unstable

**Comment by jasperdunn** [comment]
Nice, that looks promising!

**Comment by ckpinguin** [comment]
I tried with   v3_singleFetch: true but still seeing about the same error as @jasperdunn  (v.2.13 here). So I guess remix-typedjson is still a thing?
