### ISSUE TITLE
Single Fetch: bad behavior in promises that resolve to `undefined` and `null`

### ISSUE THREAD

**Issue by gustavopch** [remix-run/remix#9325]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-wfeots?file=app%2Froutes%2F_index.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.1 
    @remix-run/node: * => 2.9.1 
    @remix-run/react: * => 2.9.1 
    @remix-run/serve: * => 2.9.1 
    vite: ^5.1.0 => 5.2.10
```

### Used Package Manager

npm

### Expected Behavior

- Returning a promise that resolves to `null` from the loader shouldn't crash when resolved on the client.
- Returning a promise that resolves to `undefined` from the loader shouldn't hang on the client.

### Actual Behavior

- It crashes.
- It hangs.

**Comment by jacob-ebey** [comment]
Null should be safe if you upgrade `turbo-stream` in your project to the latest version. Undefined is an issue with the `<Await>` component and will be fixed in a react-router release.

**Comment by brophdawg11** [comment]
This should be available in the next release

**Comment by brophdawg11** [comment]
`2.9.2` is released - https://github.com/remix-run/remix/releases/tag/remix%402.9.2
