### ISSUE TITLE
Single Fetch: missing type for useLoaderData<typeof clientLoader>()

### ISSUE THREAD

**Issue by rphlmr** [remix-run/remix#9331]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-43pane?file=app%2Froutes%2F_index.tsx

- hover `clientLoaderData` 

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.1 
    @remix-run/node: * => 2.9.1 
    @remix-run/react: * => 2.9.1 
    @remix-run/serve: * => 2.9.1 
    vite: ^5.1.0 => 5.2.10
```

### Used Package Manager

npm

### Expected Behavior

` useLoaderData<typeof clientLoader>();` should be typed.

### Actual Behavior

` useLoaderData<typeof clientLoader>();` is of type `never`

**Comment by rphlmr** [comment]
The reason is `single-fetch.d.ts`.
```ts
  export function useLoaderData<T>(): T extends LoaderFunction_SingleFetch
    ? SingleFetchSerialize_V2<T>
    : never;

  export function useActionData<T>(): T extends ActionFunction_SingleFetch
    ? SingleFetchSerialize_V2<T>
    : never;

  type LoaderFunction_SingleFetch = (
    args: LoaderFunctionArgs
  ) => Promise<DataFunctionReturnValue> | DataFunctionReturnValue;

  type ActionFunction_SingleFetch = (
    args: ActionFunctionArgs
  ) => Promise<DataFunctionReturnValue> | DataFunctionReturnValue;
```

Extends for the generics of `useLoaderData` and `useActionData` don't match with `args` of `clientLoader` (`ClientLoaderFunctionArgs`)

**Comment by rphlmr** [comment]
Possible fix:
Add a `ClientLoaderFunctionArgs_SingleFetch` to use instead of `ClientLoaderFunctionArgs`?
```ts
type ClientLoaderFunctionArgs_SingleFetch = Omit<ClientLoaderFunctionArgs,'serverLoader'> & {
  serverLoader: <T = AppData>() => ReturnType<T>;
};

type ClientLoaderFunction_SingleFetch = ((
  args: ClientLoaderFunctionArgs_SingleFetch,
) => ReturnType<LoaderFunction_SingleFetch>) & {
  hydrate?: boolean;
};
```
Then, add it on hooks
```ts
type SingleFetchSerialize_V2<T extends LoaderFunction_SingleFetch | ClientLoaderFunction_SingleFetch | ActionFunction_SingleFetch> =
  Awaited<ReturnType<T>> extends TypedDeferredData<infer D> ? D :
  Awaited<ReturnType<T>> extends TypedResponse<Record<string, unknown>> ? SerializeFrom<T> :
  Awaited<ReturnType<T>>;

export function useLoaderData<T>(): T extends
  | LoaderFunction_SingleFetch
  | ClientLoaderFunction_SingleFetch
  ? SingleFetchSerialize_V2<T>
  : never;
```

**Comment by kiliman** [comment]
Yeah, there will always be some friction when adding _future_ API without breaking the existing types. At least TypeScript has a way to override these type definitions.

In addition, I think Remix needs to add ones for the updated `LoaderFunctionArgs` and `ActionFunctionArgs` so that `response` is not optional (since it isn't when single fetch is enabled).

https://github.com/remix-run/remix/discussions/9326

**Comment by brophdawg11** [comment]
This should be resolved by the introduction of `defineLoader`/`defineAction` in https://github.com/remix-run/remix/pull/9372.  We'll have a prerelease out soon for validation.

**Comment by brophdawg11** [comment]
`2.9.2` is released - https://github.com/remix-run/remix/releases/tag/remix%402.9.2
