### ISSUE TITLE
Single fetch: allow setting a `nonce` on `StreamTransfer`'s `script` tags

### ISSUE THREAD

**Issue by haines** [remix-run/remix#9359]
### Expected Behavior

We have a CSP in place which requires a nonce on inline scripts, so we need to add that to the `script` tags created [in the `StreamTransfer` component](https://github.com/remix-run/remix/blob/bd6a30601107798d6771cf166417e2034691a9c4/packages/remix-react/single-fetch.tsx#L75-L95).

### Actual Behavior

There is no way afaict to set the nonce for these scripts.

**Comment by 0927777696** [comment]
> ### Expected Behavior
> 
> We have a CSP in place which requires a nonce on inline scripts, so we need to add that to the `script` tags created [in the `StreamTransfer` component](https://github.com/remix-run/remix/blob/bd6a30601107798d6771cf166417e2034691a9c4/packages/remix-react/single-fetch.tsx#L75-L95).
> 
> ### Actual Behavior
> 
> There is no way afaict to set the nonce for these scripts.

hi
![IMG-20240503-WA0006.jpg](https://github.com/remix-run/remix/assets/166762251/3f3bc712-b655-477a-91d9-f95038ca338e)

**Comment by brophdawg11** [comment]
This fix is available in `2.9.2-pre.1` if you'd like to give it a shot and see if it resolves your issue!  Here's the draft release notes: https://github.com/remix-run/remix/blob/release-next/CHANGELOG.md#v292

**Comment by brophdawg11** [comment]
`2.9.2` is released - https://github.com/remix-run/remix/releases/tag/remix%402.9.2
