### ISSUE TITLE
[Feature]: Support meta http-equiv tag

### ISSUE THREAD

**Issue by canac** [remix-run/remix#941]
### What is the new or updated feature that you are suggesting?

I would for like Remix to allow me to add a [`<meta http-equiv>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv) tag to my page via the meta export.

### Why should this feature be included?

I would like for the meta export to support `http-equiv` because there doesn't appear to be any other way to add a `<meta http-equiv>` tag a single route.

If this change sounds good, I'm happy to put together a PR adding a special case for http-equiv. I could add [`charset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset) too for good measure if that's desired.

**Comment by fillon** [comment]
@canac Did you find a solution?

**Comment by canac** [comment]
@fillon No, I did not. I ended up just using a JavaScript redirect instead of http-equiv refresh.

**Comment by MichaelDeBoey** [comment]
Closed by #2331
