### ISSUE TITLE
Single Fetch: json serialization is unstable

### ISSUE THREAD

**Issue by lilouartz** [remix-run/remix#9421]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-ioniz1?file=app%2Froutes%2F_index.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.2 
    @remix-run/node: * => 2.9.2 
    @remix-run/react: * => 2.9.2 
    @remix-run/serve: * => 2.9.2 
    vite: ^5.1.0 => 5.2.11
```

### Used Package Manager

npm

### Expected Behavior

No error

### Actual Behavior

Error:

```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "[{\"@context\":\"https://schema.org\",\"name\":\"Hello, World!\"}]" Client: "[{\"name\":\"Hello, World!\",\"@context\":\"https://schema.org\"}]"
```

Note that the reason I am passing `meta` as loader property is because it was described as solution to https://github.com/remix-run/remix/issues/9418

The issue appears because serialized JSON values have different property order.

**Comment by lilouartz** [comment]
I can somewhat workaround this by changing my server-side object declaration to match what client renders, i.e.

```ts
{
  name: 'Hello, World!',
  '@context': 'https://schema.org',
},
```

But this is finicky and problematic because I have ESLint rule that auto sorts properties alphabetically.

**Comment by lilouartz** [comment]
I think in my case it is the properties that start with `@`.

**Comment by jacob-ebey** [comment]
I believe I have addressed this with turbo-stream@2.2.2. I can no longer reproduce it in the stackblitz: https://stackblitz.com/edit/remix-run-remix-eliwev?file=package.json

**Comment by brophdawg11** [comment]
I think the serialization is still unstable in a slightly different manner - just not surfacing this specific meta/json+ld issue.  Here's a simplified repro on `2.2.3`: https://stackblitz.com/edit/remix-run-remix-bbrwkg?file=app%2Froutes%2F_index.tsx

**Comment by jacob-ebey** [comment]
Added some better tests and addressed it here: https://github.com/jacob-ebey/turbo-stream/pull/45

**Comment by brophdawg11** [comment]
👍 Awesome - the above stackblitz is fixed with `turbo-stream@2.3.0` via the solution in https://github.com/remix-run/remix/issues/9421#issuecomment-2135549260.

**Comment by brophdawg11** [comment]
`turbo-stream@2.3.0` will be the default version in Remix `2.11.2` (currently in prerelease, stable release later this week) so you won't need your own `turbo-stream` dependency in your `package.json` once upgrading 👍

**Comment by lilouartz** [comment]
Thank you!
