### ISSUE TITLE
request.signal is never fired in dev server

### ISSUE THREAD

**Issue by DanielBaulig** [remix-run/remix#9438]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-jkyczz?file=app%2Froutes%2Fstream.tsx

Based on discussion: https://github.com/remix-run/remix/discussions/8461

The effects of the bug are twofold: 
- Actual abort signal behavior cannot be tested and verified using the dev server.
- The dev server might leak resources that should have been freed when the request was cancelled.

Not that the bug only applies to the dev server. Using the express server the request abort signal is fired correctly.

### System Info

```shell
See Stackblitz
```

### Used Package Manager

npm

### Expected Behavior

Dev server should print 'Received Abort!' when the response gets cancelled a second in.

### Actual Behavior

Silence.

**Comment by remorses** [comment]
Faced the same issue, this is very important please fix
