### ISSUE TITLE
Error Boundary <Links> conflicting with Root <Links>

### ISSUE THREAD

**Issue by steevehook** [remix-run/remix#9446]
### Reproduction

When adding ErrorBoundary to root, and adding <Scripts> to it, it will conflict with Scripts inside Root especially when linking from an Error page to the App page, the styles will just break in development mode. Removing them fixes the issues for production mode, however in development mode I am left without any rendered styles as vite renders them differently in Dev mode.

### System Info

```shell
OSX
```

### Used Package Manager

npm

### Expected Behavior

I want styles to work in both development and production modes for both the normal App routes and the Error boundary pages

### Actual Behavior

At the moment the solution is to comment out Links, which will do the trick for production, but in development mode, ErrorBoundary is pretty much left without styles, while in production mode, sometimes navigating between links after hard reloading will throw styles away

**Comment by machour** [comment]
Hey @steevehook, thank you for filling this issue.
Could you help us by providing a simple repository reproducing the problem you're encountering? 🙏🏼
