### ISSUE TITLE
Single fetch: Throwing a response stub with a 4xx status causes a turbo-stream error 

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/remix#9471]
### Reproduction

Thrown error response stubs are properly handled on data requests but not on document requests - see https://github.com/remix-run/remix/pull/9454 and https://github.com/remix-run/remix/pull/9479

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Expected Behavior

Thrown response stubs hydrate up as `ErrorResponse` instances for use with `useRouteError`/`isRouteErrorResponse`

### Actual Behavior

`turbo-stream` tries to serialize the `ReponseStub` instance and errors

**Comment by haines** [comment]
We ran into a similar case with a redirect response stub in a resource route: https://github.com/remix-run/remix/pull/9479
