### ISSUE TITLE
Vite + Express: Error: No route matches URL

### ISSUE THREAD

**Issue by HenrikFricke** [remix-run/remix#9473]
### Reproduction

1. Create a new Remix project with Vite and Express
2. Start dev server
3. Open http://localhost:3000/config.js

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 354.27 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.pkgx/nodejs.org/v20.12.2/bin/node
    npm: 10.2.4 - ~/.pkgx/npmjs.com/v10.2.4/bin/npm
  Browsers:
    Chrome: 125.0.6422.60
    Safari: 17.0
  npmPackages:
    @remix-run/dev: ^2.9.2 => 2.9.2
    @remix-run/eslint-config: ^2.9.2 => 2.9.2
    @remix-run/express: ^2.9.2 => 2.9.2
    @remix-run/react: ^2.9.2 => 2.9.2
    @remix-run/testing: ^2.9.2 => 2.9.2
    vite: ^5.2.11 => 5.2.11
```

### Used Package Manager

npm

### Expected Behavior

Remix with Vite and Express should handle 404 gracefully without throwing errors. On production, it's quite normal to receive requests from bots trying to access confidential information (like configs, .env, etc.). What I get in the logs for those requests: 

```sh
Error: No route matches URL "/config.js"
    at getInternalRouterError (/Users/…/node_modules/@remix-run/router/dist/router.cjs.js:4676:59)
    at Object.query (/Users/…/node_modules/@remix-run/router/dist/router.cjs.js:3394:19)
    at handleDocumentRequest (/Users/…/node_modules/@remix-run/server-runtime/dist/server.js:223:35)
    at requestHandler (/Users/…/node_modules/@remix-run/server-runtime/dist/server.js:142:24)
    at async /Users/√/node_modules/@remix-run/express/dist/server.js:41:22
No routes matched location "/config.js"
GET /config.js 404 - - 17.249 ms
```

### Actual Behavior

The server should not emit any errors for those requests to keep the logs clean and meaningful.

**Comment by brophdawg11** [comment]
You can control these logs:

* You can control the remix handler logs via [`handleError`](https://remix.run/docs/en/main/file-conventions/entry.server#handleerror)
* There is also a `console.log` in the default error boundary, so to get rid of that you should provide your own `ErrorBoundary` in `root.tsx` (if you haven't already)
* `No routes matched location "/config.js"` is a dev-only message from the react router render so that will not show up in production
* `GET /config.js 404 - - 17.249 ms` is from the default `morgan` logger `(app.use(morgan("tiny"))`), so you control that in your express server as well

**Comment by HenrikFricke** [comment]
@brophdawg11 Hey, thanks for your answer. I'll look into it. 

> No routes matched location "/config.js" is a dev-only message from the react router render so that will not show up in production
Hm, I can see the log output also on production. We run our Remix app in production and set `NODE_ENV` to `production`. But still, I can see the log output `Error: No route matches URL "/hazelcast/rest/cluster"`

**Comment by HenrikFricke** [comment]
So I implemented a simple `handleError` function to ignore the error coming from react router. 

```ts
export function handleError(error: Error) {
  if (error.message.startsWith('No route matches URL')) {
    return;
  }

  console.error(error);
}
```

Honestly, it feels wrong to implement the condition 🤔
