### ISSUE TITLE
Infinite loop on unhandle error using Layout Export with ErrorBoundary

### ISSUE THREAD

**Issue by michenly** [remix-run/remix#9553]
#### This is the positive case with no Layout, but AppShell wrap around App & ErrorBoundary
1. Go to https://stackblitz.com/edit/remix-run-remix-jfuwjb
2. See the error loaded in browser
----------

#### This is the negative case with Layout Export ###
1. Go to https://stackblitz.com/edit/remix-run-remix-jfuwjb
2. Quit dev server
3. Rename root-with-layout.tsx to root.tsx
4. Open dev tool with console open
5. Start dev server
6. Click the link to see the error showing up in page

Following the example from https://remix.run/docs/en/main/start/tutorial to set up a base example use example here https://remix.run/docs/en/main/file-conventions/root to setup Layout Export and ErrorBoundary

This might be related to this close issue https://github.com/remix-run/remix/issues/1678#issuecomment-2127085554 but no longer related to React version.

### System Info

```shell
I can reproduce this with 
- Node 18 and Node 20
- React 18
- Remix 2.8 & 2.9
```

### Used Package Manager

npm

### Expected Behavior

That unhandle error would cause Application error in browser using Layout export

### Actual Behavior

Unhandle error cause infinite loading using Layout export

**Comment by brookslybrand** [comment]
It looks like [there's a note](https://remix.run/docs/en/main/file-conventions/root#layout-export) about using `useLoaderData` inside of `Layout`

> useLoaderData is not permitted to be used in ErrorBoundary components because it is intended for the happy-path route rendering, and its typings have a built-in assumption that the loader ran successfully and returned something. That assumption doesn't hold in an ErrorBoundary because it could have been the loader that threw and triggered the boundary! In order to access loader data in ErrorBoundary's, you can use useRouteLoaderData which accounts for the loader data potentially being undefined.
> 
> Because your Layout component is used in both success and error flows, this same restriction holds. If you need to fork logic in your Layout depending on if it was a successful request or not, you can use useRouteLoaderData("root") and useRouteError():

So I don't think this is a bug, but I do get that the error message is a little confusing. I'm not sure if there's anything we can do to improve the error. Probably a question for @brophdawg11

**Comment by frandiox** [comment]
>So I don't think this is a bug, but I do get that the error message is a little confusing. I'm not sure if there's anything we can do to improve the error.

The same thing happens with `useRouteLoaderData("root")`, though, which is mentioned as something valid.

Weirdly enough, the infinite loop disappears if you pass `errorElement` to Await: `<Await resolve={...} errorElement={'something-non-nullish'}>`. It might not be forwarding the error properly to the Suspense boundary if `errorElement` is missing (or it has `null` or empty string).

**Comment by michenly** [comment]
The example had been updated without the use of `useLoaderData`

**Comment by brophdawg11** [comment]
The underlying issue here ends up being that `Layout` was throwing initially due to the invalid promise value being returned - but then when `Layout` was rendered again using the `ErrorBoundary` it would throw again.  This would result in us trying to render the built-in default Remix error boundary as children of `#document` since we skip the `<html>` shell due to the presence of a root `Layout`.  The DOM rejects this and puts React into the infinite loop.

I think the fix in the PR is safe to detect this scenario when the `Layout`/`ErrorBoundary` combo re-threw but the guidance should be that `Layout`/`ErrorBoundary` _should never throw_ or else it defeats the purpose of using them since they'll be ignored.  If `useRouteLoaderData` is used in `Layout` during an error render to bypass the `can't useLoaderData in an ErrorBoundary` limitation, then it should be very defensive to avoid bubbling further.

**Comment by michenly** [comment]
Got it! I can definitely make sure `Layout/ErrorBoundary should never throw`
A great caveat to note and makes a lot of sense once its explain.

Thank you so much for taking the time @brophdawg11 ! 

Might be worth it to mentioned in [this doc](https://remix.run/docs/en/main/file-conventions/root) along side of `A note on useLoaderDatain the Layout Component` ?

**Comment by brophdawg11** [comment]
Good call!  Added in https://github.com/remix-run/remix/pull/9581

**Comment by michenly** [comment]
Note that https://github.com/remix-run/remix/pull/9566 will fix the infinite loop and falling back to the minimal root layout when `Layout` throw.
