### ISSUE TITLE
Error: The render was aborted by the server without a reason.

### ISSUE THREAD

**Issue by MoSattler** [remix-run/remix#9571]
### Reproduction

Open the stackblitz and wait for 10s

[Stackblitz](https://stackblitz.com/edit/mosattler-remix-repro-defer-search-params-njpsxx?file=app%2Froutes%2F_index.tsx)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 1.61 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/nevados/dashboard/node_modules/.bin/yarn
    npm: 10.2.3 - ~/nevados/dashboard/node_modules/.bin/npm
    pnpm: 9.1.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.0
  npmPackages:
    @remix-run/dev: 2.8.1 => 2.8.1 
    @remix-run/eslint-config: 2.8.1 => 2.8.1 
    @remix-run/express: 2.8.1 => 2.8.1 
    @remix-run/node: 2.8.1 => 2.8.1 
    @remix-run/react: 2.8.1 => 2.8.1 
    @remix-run/serve: ^2.8.1 => 2.9.2 
    @remix-run/server-runtime: 2.8.1 => 2.8.1 
    @remix-run/testing: 2.8.1 => 2.8.1 
    @remix-run/v1-meta: ^0.1.3 => 0.1.3 
    vite: ^4.5.3 => 4.5.3
```

### Used Package Manager

npm

### Expected Behavior

Not to break

### Actual Behavior

It breaks with the message 
> Error: The render was aborted by the server without a reason.

**Comment by brophdawg11** [comment]
This can be controlled via the `<RemixServer abortDelay>` prop in your `entry.server.tsx` file.  The value used by the default implementations is 5 seconds.  If you don't currently have an `entry.server.tsx` file you can expose it via `npx remix reveal entry.server`

I added some docs for this in https://github.com/remix-run/remix/pull/9577 for clarity

**Comment by MoSattler** [comment]
Thank you, @brophdawg11, for pointing that out!

If I may suggest, it would be beneficial to have a clearer error message indicating a timeout in such cases.
