### ISSUE TITLE
`defer` does not work on search param navigation

### ISSUE THREAD

**Issue by MoSattler** [remix-run/remix#9572]
### Reproduction

https://stackblitz.com/edit/mosattler-remix-repro-defer-search-params-8ejfsy?file=app%2Froutes%2F_index.tsx

1. Open the stackblitz and notice how `defer`, `<Suspense />` and `<Await />` work as expected
2. Click the button to trigger a search param change
3. Notice how `defer` is not working, and the loader is waiting for promise to resolve. Suspense is not triggering fallback.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 58.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.1.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.0
  npmPackages:
    @remix-run/dev: ^2.9.2 => 2.9.2 
    @remix-run/node: ^2.9.2 => 2.9.2 
    @remix-run/react: ^2.9.2 => 2.9.2 
    @remix-run/serve: ^2.9.2 => 2.9.2 
    vite: ^5.1.0 => 5.2.12
```

### Used Package Manager

npm

### Expected Behavior

`defer` should work on search param change

### Actual Behavior

`defer` is not working on search param change

**Comment by MoSattler** [comment]
@brophdawg11 here is a repro illustrating the issue without using Suspense at all: https://stackblitz.com/edit/mosattler-remix-repro-defer-search-params-x4jr7s?file=app%2Froutes%2F_index.tsx

**Comment by brophdawg11** [comment]
> This issue is primarily related to `defer` and not to Suspense

> In the case of a search param navigation, the navigation won't execute (and hence not pass ANY data to useLoader) until the last promise in loader is resolved.

Correct - this is proper behavior and is a design decision made for the handling of `defer` as outlined in [the docs](https://reactrouter.com/en/main/guides/deferred#when-does-the-suspense-fallback-render>). This will no longer be the case with single fetch so you can adopt that via `future.unstable_singleFetch` if you really need to bypass this limitation of `defer`.

**Comment by MoSattler** [comment]
Alright, thank you for your help on this @brophdawg11

**Comment by andrewbarnesweb** [comment]
I don't think is covered at all in the Remix docs anymore? I see a lot of comments regarding this confusion. 

Hopefully React Router 7 consolidation will help get it all a bit clearer.
