### ISSUE TITLE
Root App component is mounted twice in dev mode with vite

### ISSUE THREAD

**Issue by pawelgalazka** [remix-run/remix#9573]
### Reproduction

1. Create Remix app: `npx create-remix@2.9.2`
2. In `App` component within `app/root.tsx` add the following hook:

```js
useEffect(() => {
  console.log('mount')
}, [])
```
3. Run app in the dev mode: `npm run dev`
4. Open up the browser with working app and inspect the console in chrome dev tools

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 101.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - ~/.asdf/installs/nodejs/20.6.0/bin/node
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 125.1.66.110
    Chrome: 125.0.6422.142
    Safari: 16.6
  npmPackages:
    @remix-run/dev: ^2.9.2 => 2.9.2 
    @remix-run/node: ^2.9.2 => 2.9.2 
    @remix-run/react: ^2.9.2 => 2.9.2 
    @remix-run/serve: ^2.9.2 => 2.9.2 
    vite: ^5.1.0 => 5.2.12
```

### Used Package Manager

npm

### Expected Behavior

Root App component should be mounted only once in dev mode

### Actual Behavior

Root App component is mounted twice in dev mode

**Comment by wouterds** [comment]
Related? https://github.com/remix-run/remix/issues/9406

**Comment by MoSattler** [comment]
This is expected React behaviour
> To help surface these issues, React 18 introduces a new development-only check to Strict Mode. This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount. - [React Docs](https://legacy.reactjs.org/docs/strict-mode.html#ensuring-reusable-state)

It wont happen in production
