### ISSUE TITLE
Link prefetch calls loader despite the presence of clientLoader

### ISSUE THREAD

**Issue by nramovs-sr** [remix-run/remix#9575]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-s2qdww

Hover on link to 'Other', in network devtools you can see a request for loader, and server log shows that loader was called.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.2 
    @remix-run/node: * => 2.9.2 
    @remix-run/react: * => 2.9.2 
    @remix-run/serve: * => 2.9.2 
    vite: ^5.1.0 => 5.2.12
```

### Used Package Manager

npm

### Expected Behavior

When using `<Link to="" prefetch="intent">`, prefetch will fetch the `loader` from network, while navigating to that page will correctly only call `clientLoader`. 

In case of using clientLoader as https://remix.run/docs/en/main/guides/client-data#skip-the-hop, that caused double network requests and result from `loader` is discarded.

### Actual Behavior

Either call clientLoader, or no loader at all.

When adding a clientLoader to existing route I would expect that loader _data request will never trigger again unless I explicitly call serverLoader, even if I forget to remove prefetch from Link elements

**Comment by MatthewVaccaro** [comment]
Hello! I am on remix "^2.16.2" and I am seeing this behavior

I have two files
> dashboard.tsx (Parent)
>dashboard.bottle.$id.tsx (Child)


_dashboard.tsx_
```tsx
export async function loader() {
//  ...fetches data
  return data
}

export const shouldRevalidate: ShouldRevalidateFunction = () => false;

export default function Index() {
  const bottles = useLoaderData<typeof loader>();
  return (
    <div>
      <Outlet />
      <ol className="flex flex-col gap-3">
        {bottles.map((juice) => (
          <Link prefetch="intent" key={juice.id} to={`bottle/${juice.id}`}>
            <li>
              <ProductCard sizes={juice.sizes} name={juice.name} />
            </li>
          </Link>
        ))}
      </ol>
    </div>
  );
}
```

_dashboard.bottle.$id.ts_
```tsx

export async function loader({ params }: LoaderFunctionArgs) {
 //...logic
return data
}

export default function Route() {
  return (
    <DrawerContainer>
      <DrawerContents />
    </DrawerContainer>
  );
}
```

useLoaderData is used inside of the DrawerContents and is unique to the path.

In this, I will see logs that show the data is being loaded but even after the prefect, it still fetches again. How can I fix this?
