### ISSUE TITLE
[Bug]: Css in component resolve error

### ISSUE THREAD

**Issue by 3lang3** [remix-run/remix#959]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.9.1

### Steps to Reproduce

create a remix project:
```bash
npx create-remix@latest
```
**(IMPORTANT)add ui lib**
```bash
yarn add react-vant@next
```
update page:
```tsx
// app/routes/index.tsx
import { Button } from 'react-vant'

<Button>Hello remix</Button>
```

### Expected Behavior

Normal rendering

### Actual Behavior

![企业微信20211209-122030](https://user-images.githubusercontent.com/7098719/145333847-927122fb-7f07-4e05-81d6-9fc438474c21.png)

**Comment by 3lang3** [comment]
`react-vant` There are imported CSS files in `Button`

https://github.com/3lang3/react-vant/blob/9de2ee8e055dde1b004b323902b1db3ce5e22147/packages/react-vant/src/button/index.tsx#L1-L4

> The compiled NPM package is a CSS file

**Comment by ryanflorence** [comment]
Remix doesn't support node modules that expect a bundler to be configured a certain way (to process and somehow automatically include a `*.less` file).

The third party needs to get that import out of their distributed file and provide a css file to import to work with Remix.

```js
import { Button } from "pkg"
import href from "pkg/styles.css"
```

**Comment by 3lang3** [comment]
but it's work fine with nextjs
