### ISSUE TITLE
Symbols decoding issue

### ISSUE THREAD

**Issue by dmitryuck** [remix-run/remix#9608]
### Reproduction

I load a .json file from public directory with Japan text In loader function, like this:
`賞品獲得に挑戦しよう`

but in component I see like this:
`è³žå“ç²å¾—ã«æŒ‘æˆ¦ã—ã‚ˆã†`

I added "application/json; charset=UTF-8" in loader Response but it doesn't help

```
 return new Response(JSON.stringify({ ok: true, data }), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
    },
  });
```

The same when I use:
```
 const headers = new Headers();
 headers.append("Content-Type", "application/json; charset=UTF-8");
 json({ ok: true, data }, { headers });
```

I found that fetch loads correct text, so I believe this happens between response and useLoaderData<typeof loader>();

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 11.75 GB / 15.55 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.3.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
```

### Used Package Manager

yarn

### Expected Behavior

Symbols in component should looks like the origins in .json file

### Actual Behavior

I see a different symbols for Japan text after put it in frontend

**Comment by sergiodxa** [comment]
I tried to [replicate with here](https://stackblitz.com/edit/remix-run-remix-c1f3mu?file=app%2Fdata.json,app%2Froutes%2F_index.tsx) but it seems to work.

I'm doing a console.log of the data from the imported `.json` file in the loader and the component body, and I'm also rendering the data in the UI and in all cases I see the correct text.

Check if you have `<meta charSet="utf-8" />` in your `app/root`.

**Comment by dmitryuck** [comment]
Yes, you are right, I haven't set `<meta charSet="utf-8" />` in your `app/root`.
Thank you for quick response.
