### ISSUE TITLE
Quirrel is not working with the latest Remix Build

### ISSUE THREAD

**Issue by hamzasgd** [remix-run/remix#9612]
### Reproduction

yarn add quirrel
yarn build
yarn start

### System Info

```shell
Chrome
Ubuntu
```

### Used Package Manager

yarn

### Expected Behavior

On the dev server its working fine but after making a build giving error

### Actual Behavior

SyntaxError: The requested module 'quirrel/remix.mjs' does not provide an export named 'Queue'

**Comment by pcattori** [comment]
Looks like Quirrel is configured incorrectly: https://publint.dev/quirrel@1.14.1

**Comment by HeinKoZin** [comment]
Any updates on this?

**Comment by pcattori** [comment]
Ultimately this is an issue with Quirrel, so you could file an issue there instead.

Closing as we have documented [workarounds/troubleshooting for ESM/CJS misconfigurations detailed in our docs](https://remix.run/docs/en/main/guides/vite#esm--cjs).
