### ISSUE TITLE
Using React.lazy for a component can cause the styles to disappear when navigating to another route with the same component.

### ISSUE THREAD

**Issue by raRaRa** [remix-run/remix#9630]
### Reproduction

Visit https://stackblitz.com/edit/remix-run-remix-qvtusu?file=app%2Froutes%2F_layout.play.tsx
1. Run `npm run build`
2. Run `npm run start`

3. Click on the 'Designer' link.
4. Refresh the page
5. Now click on the 'Play' link. Note how the styles for the slideshow have disappeared. If you refresh the page it will be displayed fine.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 250.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.62
    Safari: 17.3.1
```

### Used Package Manager

npm

### Expected Behavior

Expected the styles to remain for the slideshow.

### Actual Behavior

It seems like Remix removes the css file from the head when navigating from Designer to Play, which causes the styles to disappear for the slideshow.

**Comment by DarkIntaqt** [comment]
Hi, may I asked why this was closed? I can replicate your bug and I have a very similar issue
