### ISSUE TITLE
flat is not function when run i android 9

### ISSUE THREAD

**Issue by shaodahong** [remix-run/remix#9635]
### Reproduction

official demo

### System Info

```shell
android 9
```

### Used Package Manager

npm

### Expected Behavior

 android 9 work fine

### Actual Behavior

break in android 9

**Comment by shaodahong** [comment]
and when i use `@vitejs/plugin-legacy` solve it, still not work

**Comment by brophdawg11** [comment]
Please provide the specific error you're receiving and ideally a minimal reproduction

**Comment by shaodahong** [comment]
> Please provide the specific error you're receiving and ideally a minimal reproduction

`p.concat(...).map(...).flat is not a function` Error message with Sentry , and when i search have many `flat` use

<img width="330" alt="image" src="https://github.com/remix-run/remix/assets/14831261/887f29ac-03ac-4fa2-98c2-c63d9cf042a3">

**Comment by brophdawg11** [comment]
Ah ok - you can fix this by polyfilling APIs you need - [`Array.prototype.flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility) has very good browser support so it's not something Remix would polyfill internally.  I would recommend checking out [core-js](https://github.com/zloirock/core-js#ecmascript-array) or https://polyfill.io/

**Comment by shaodahong** [comment]
> Ah ok - you can fix this by polyfilling APIs you need - [`Array.prototype.flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility) has very good browser support so it's not something Remix would polyfill internally. I would recommend checking out [core-js](https://github.com/zloirock/core-js#ecmascript-array) or https://polyfill.io/

Thanks, finally, I manually imported core-js to solve it, but the problem is that each change becomes dangerous. Does remix plan to support the @vitejs/plugin-legacy plugin?

**Comment by brophdawg11** [comment]
I'm not familiar with that plugin - can you not just add it to your vite config alongside the Remix plugin?  If that doesn't work, I would open a new issue with a reproduction of that plugins incompatibility.

**Comment by brophdawg11** [comment]
⚠️ Scratch that - DO NOT USE polyfil.io - https://sansec.io/research/polyfill-supply-chain-attack

**Comment by shaodahong** [comment]
> I'm not familiar with that plugin - can you not just add it to your vite config alongside the Remix plugin? If that doesn't work, I would open a new issue with a reproduction of that plugins incompatibility.

I spent a bit of time looking at @vitejs/plugin-legacy and it seems to do post-processing on the build target's html to make it compatible with older browsers, if there were a way to get that working it seems like the browser compatibility of remix would be incredibly strong

https://github.com/vitejs/vite/blob/3af02bde7e7f26889d5c0eb300219c43ed1293ad/packages/plugin-legacy/src/index.ts#L560
