### ISSUE TITLE
[Bug]: Could not locate @remix-run/serve. Please verify you have it installed to use the dev command.

### ISSUE THREAD

**Issue by nkrmr** [remix-run/remix#965]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.18.2

### Steps to Reproduce

I used Yarn V2 into a Lerna monorepo, and after make "yarn" on root project i had this message when i tried to launch remix app.
<img width="918" alt="Screenshot 2021-12-09 at 11 58 52" src="https://user-images.githubusercontent.com/686395/145384195-3f186294-28d6-4829-8228-3a26fedec389.png">
 
<img width="508" alt="Screenshot 2021-12-09 at 12 16 49" src="https://user-images.githubusercontent.com/686395/145386761-c71df0dc-ba5b-4e7d-b647-04ce60857533.png">

### Expected Behavior

Launch Remix app

### Actual Behavior

Could not locate @remix-run/serve. Please verify you have it installed to use the dev command.

**Comment by AlonGvili** [comment]
The same just after i run npm I

**Comment by AjayPoshak** [comment]
The same thing happened to me because I was running it on node version 10. Upgrading it to v14 then doing `npm install` fixed it.

**Comment by arekgotfryd** [comment]
Same for me on node version v12.14.0

**Comment by lvauvillier** [comment]
Try to install express as well, this was the issue for me.

The try/catch block contains two require: `@remix-run/serve` and `express`

https://github.com/remix-run/remix/blob/1fd70960e4d88740df5bf407a6ba2cd2b9549459/packages/remix-dev/cli/commands.ts#L146

**Comment by machour** [comment]
@arekgotfryd remix is node >= 14 only

@nkrmr do you still have this issue with the last release ?
