### ISSUE TITLE
Opt out from scroll restoration on a per Link basis

### ISSUE THREAD

**Issue by mschipperheyn** [remix-run/remix#9654]
### Reproduction

Sorry

### System Info

```shell
@remix-run 2.9.1
```

### Used Package Manager

yarn

### Expected Behavior

When you use `<ScrollRestoration />` it globally enables scroll restoration. Very useful. You can manually opt out from this by using `window.scrollTo(0, 0)` in a `useEffect`. On the link `Link` component you can _optin_ to scroll restoration but if you set `preventScrollReset={false}`, you don't _opt out_ from scroll restoration. 

This requirement is a very common behavior on list view > detail page. You generally want to go to the top of the page, be it a form or a detail page. Seem like a very common scenario to me without a good declarative solution. 

The alternative is to capture the `onClick` event, but isn't that something remix tries to get away from?

### Actual Behavior

`preventScrollReset={false}` doesn't optout from global scroll restoration behavior.

**Comment by brophdawg11** [comment]
I don't understand the issue/question?  A reproduction would be helpful.

You should not be using `window.scrollTo(0, 0)` in conjunction with `<ScrollRestoration>` - you should use one or the other.

> preventScrollReset={false} doesn't optout from global scroll restoration behavior.

[`preventScrollReset`](https://reactrouter.com/en/main/components/scroll-restoration#preventing-scroll-reset) is not for opting out of scroll _restoration_ - it is strictly for opting out of _resetting_ the scroll position back to the top of the page if a restoration position cannot be found.

Restoration is driven by the scroll restoration key, which defaults to `location.key`, but is configurable via [getKey](https://reactrouter.com/en/main/components/scroll-restoration#getkey) - so I think that is what you likely want to reach for.

**Comment by brophdawg11** [comment]
ok - if that doesn't work for you - please provide a small reproduction of the UI/ behavior you're looking for and we can use that to try to come up with a solution.
