### ISSUE TITLE
cross-env listed as both dependency and dev-dependency in the express template

### ISSUE THREAD

**Issue by arekmaz** [remix-run/remix#9668]
### Reproduction

https://github.com/remix-run/remix/blob/main/templates/express/package.json#L34

### System Info

```shell
*
```

### Used Package Manager

npm

### Expected Behavior

cross-env ideally should be listed only once and as a normal dependency

### Actual Behavior

I created a fresh fly-io app and after deployment I got "cross-env not found" error after running the default "npm start", after short investigation, it's listed 2 times in both "dependencies" and "devDependencies" section which apparently breaks it

after removing it from "devDependencies" and reinstalling modules I got it working

**Comment by brophdawg11** [comment]
Would you lie to submit a PR to remove it from the `devDependencies`?

**Comment by arekmaz** [comment]
sure there it is

https://github.com/remix-run/remix/pull/9680
