### ISSUE TITLE
Infer types of the loader function

### ISSUE THREAD

**Issue by mellson** [remix-run/remix#97]
It would be nice to infer the type of the loader function when using `useRouteData`.
I'm not sure how the internals of remix work, so I don't know if there's anywhere one could hook (pun intended) into the place where the actual loading occurs.

Anyway, here is a small utility that could help someone else needing an easy way to get the types.

This code (placed in a helper file somewhere):
```typescript
import { LoaderFunction } from "@remix-run/data";
import { useRouteData } from "@remix-run/react";

type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
export type LoaderType<T extends LoaderFunction> = Awaited<ReturnType<T>>;

export function useTypedRouteData<T extends LoaderFunction>(loader: T) {
  return useRouteData<LoaderType<typeof loader>>();
}

```

allows the user to get the types in one of two ways:
1 - Add the type to the existing hook `let data = useRouteData<LoaderType<typeof loader>>()`
2 - Use the provided wrapper `let data = useTypedRouteData(loader)`

This should work equally well with promises and responses. But there's probably a lot of edge cases I'm not thinking of right now.

**Comment by joshmedeski** [comment]
I got something working. I made the following changes.

1. Drop the loader `LoadFunction` type on the `loader` function and use the `DataFunctionArgs` argument type. This is so Typescript can infer the return type of `loader`.

```ts
import { DataFunctionArgs } from '@remix-run/server-runtime'

export const loader = async ({ params }: DataFunctionArgs) => {
  invariant(params.movieId, 'expected params.movieId')
  const details = await new Tmdb().movie.getDetails(params.movieId)
  return { details }
}
```

2. Create a `useInferredRouteData` reusable type. This extends the `useLoaderData` function and infers the returned type from the promise.

```ts
export function useInferredRouteData<
  T extends (args: DataFunctionArgs) => any
>() {
  return useLoaderData<Awaited<ReturnType<T>>>()
}
```

3. Include `typeof loader` as the generic on the `useInferredRouteData` hook.

```ts
export default function Index() {
  const { details } = useInferredRouteData<typeof loader>()
```

**Warning:** I realize that this is incomplete. If you have conditional response types on the loader function you may run into errors with this code. But it's great for a happy path and the `useInferredRouteData` type can be separated so it can be easily reused.

**Type Name Suggestion:** I'd also suggest to the remix team that `DataFunctionArgs` be changed to `LoaderFunctionArgs` to better match the API.

**Comment by itsMapleLeaf** [comment]
> **Type Name Suggestion:** I'd also suggest to the remix team that `DataFunctionArgs` be changed to `LoaderFunctionArgs` to better match the API.

I thought the same too at first, but I figure called that because the same args are also used for the `action` function

**Comment by itsMapleLeaf** [comment]
Related to the subject, here are a set of typed helpers I've written up that I'm making good use of: https://gist.github.com/itsMapleLeaf/0521a21e5e24419ce90d447e7ceede70
