### ISSUE TITLE
Multiple actions on a page browser support issue

### ISSUE THREAD

**Issue by sebastien-comeau** [remix-run/remix#9704]
### Reproduction

Here is my reproduction repository: [GitHub](https://github.com/sebastien-comeau/remix-multiple-forms), based on Remix's [Multiple Forms example](https://github.com/remix-run/examples/tree/main/multiple-forms). My repo uses the latest version of Remix, and I was able to reproduce the issue in both Remix v1 and v2. The issue seems to occur with browsers that do not support the [SubmitEvent: submitter property](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter). I reproduced it with Firefox 74 since I can't install Safari on Windows.

We are aware that these are older browsers, but our application must support them to serve Canadian citizens, and it is challenging to force users to update their browsers. Safari 15.4 was released on March 14, 2022, and we believe supporting at least Safari 15 is necessary. User metrics indicate this issue also occurs with other browsers that lack submitter support, including:

- Safari 14 with over 50% of the errors collected
- Safari 15 (version 15.4 has full support for the submitter property)
- Safari mobile 14
- Safari mobile 15
- Chrome Mobile 125

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 5.21 GB / 15.69 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @remix-run/dev: ^2.10.0 => 2.10.0
    @remix-run/node: ^2.10.0 => 2.10.0
    @remix-run/react: ^2.10.0 => 2.10.0
    @remix-run/serve: ^2.10.0 => 2.10.0
    vite: ^5.1.0 => 5.3.3
```

### Used Package Manager

npm

### Expected Behavior

When a page in Remix contains multiple actions and a user submits a form, the form data should include the `intent` key, with the value corresponding to the intent value of the action submitter.

### Actual Behavior

The actual behavior is that the `intent` key is not present in the form data.

**Comment by brophdawg11** [comment]
We have some lightweight code that attempts to detect lack of `submitter` support [here](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/dom.ts#L313).  Any chance you'd be willing to do some step through debugging in there to see if you can help identify where that's not working right in those cases?  

There is also a more extensive polyfill available in https://github.com/jenseng/formdata-submitter-polyfill that may solve the issue for you

**Comment by sebastien-comeau** [comment]
@brophdawg11, as you mentioned, support for the `submitter` parameter in FormData is relatively new (since last year). We encountered this situation and opted to handle it manually instead.

In this example, I'm using the `useFetcher` hook:
```typescript
function handleSubmit(event: SyntheticEvent<HTMLFormElement, SubmitEvent>) {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);

    // Get the clicked button's value and append it to the FormData object
    const submitter = event.nativeEvent.submitter as HTMLButtonElement | null;
    invariant(submitter, 'Expected submitter to be defined');
    formData.append(submitter.name, submitter.value);

    fetcher.submit(formData, { method: 'POST' });
}
```

My issue arises with browsers that do not support `SubmitEvent.submitter`, such as Safari versions prior to 15.4. I have explored the [FormData submitter polyfill](https://github.com/jenseng/formdata-submitter-polyfill) and found that I should polyfill the submitter property of the SubmitEvent using the [event-submitter-polyfill](https://github.com/idea2app/event-submitter-polyfill) package.

Next, I need to test this with the `event-submitter-polyfill`.

**Comment by brophdawg11** [comment]
Great!  This sounds like the polyfill will handle your issue then?  Can this issue be closed out?

**Comment by sebastien-comeau** [comment]
The issue with SubmitEvent can be resolved by using the [Event Submitter polyfill](https://github.com/idea2app/event-submitter-polyfill).

I tested this with Firefox version 74, and the problem was resolved. It would be a good idea to add a note about this in the documentation. This problem should eventually disappear as users update their browsers to the latest versions, which is beyond our control at this point.

The issue can now be closed.

**Comment by brophdawg11** [comment]
Would you like to open a PR to the docs to mention this?

**Comment by sebastien-comeau** [comment]
> Would you like to open a PR to the docs to mention this?

Sure! I forked the repo but I'm not sure how I can run the documentation locally and test my changes locally. Do you have any instructions?

**Comment by brophdawg11** [comment]
I wouldn't worry about previewing them locally - you can just edit the markdown and we can handle previewing during PR to keep it easy.

You _can_ preview locally by running the [remix website](https://github.com/remix-run/remix-website) and choosing the `local` option from the docs dropdown but you don't have to for simple docs upsates 👍

**Comment by sebastien-comeau** [comment]
@brophdawg11 pull request #9737 has been created.
