### ISSUE TITLE
Expose the `ResponseStub` type

### ISSUE THREAD

**Issue by IgnisDa** [remix-run/remix#9709]
I would like to use the `ResponseStub` to be able to extract a function that redirects.

**Comment by brophdawg11** [comment]
We're still considering some changes to the `ResponseStub` approach (https://github.com/remix-run/react-router/issues/11707, https://www.youtube.com/watch?v=f5z_axCofW0) so for now I would just duplicate the type locally

```ts
export type ResponseStub = {
  status: number | undefined;
  headers: Headers;
};
```

**Comment by brophdawg11** [comment]
This is no longer relevant as the response stub API has been removed
