### ISSUE TITLE
`<Form>` submission crashes page when no `<input>`s with a `name` attribute are present

### ISSUE THREAD

**Issue by AjaniBilby** [remix-run/remix#9715]
### Reproduction

https://github.com/AjaniBilby/remix-js-bug-report

1. `npm run dev`
2. Goto page
3. Hit submit form
4. Hit I don't want it to crash
5. Hit submit form

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 16.92 GB / 31.92 GB
  Binaries:
    Node: 21.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Expected Behavior

The form to not crash when submitting without any `<input>` elements

### Actual Behavior

Submitting a `<Form>` crashes if there are no `<input>` elements with a name the page crashes

**Comment by brophdawg11** [comment]
This looks like a bug in Chrome from what I can tell.  This code throws an exception in Chrome, but works fine in Safari, Firefox, and node v20:

```js
await new Request('http://localhost/', { method: 'post', body: new FormData() }).formData()
```

I would probably add a hidden input to your form to prevent this error in Chrome browsers, but I don't think this is necessarily something Remix should be trying to handle.

**Comment by AjaniBilby** [comment]
I only found it because I had a bug in a component where it wasn't setting the`<input>` to have a name.

Thanks for the look over!
