### ISSUE TITLE
Remix not properly aborting requests on single fetch

### ISSUE THREAD

**Issue by jcheese1** [remix-run/remix#9729]
### Reproduction

Head here:  https://stackblitz.com/edit/remix-run-remix-hkvxdu?file=vite.config.ts 
- open devtools and go to the network tab
- add unstable_singleFetch and see the requests not aborting as you type

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.10.2 
    @remix-run/node: * => 2.10.2 
    @remix-run/react: * => 2.10.2 
    @remix-run/serve: * => 2.10.2 
    vite: ^5.1.0 => 5.3.3
```

### Used Package Manager

npm

### Expected Behavior

The requests should properly abort on subsequent quick requests. Heres a video:

with single fetch enabled (bug):
https://github.com/remix-run/remix/assets/15570714/d323709c-9a13-4841-8c63-dee7ce3b75d4

without single fetch (intended):
https://github.com/remix-run/remix/assets/15570714/5659ce8e-6caa-4acd-957c-88b36d74f6e3

### Actual Behavior

All the requests are pending even on subsequent requests. should abort.

**Comment by brophdawg11** [comment]
Thanks for the reproduction!

**Comment by jcheese1** [comment]
thank you for the quick fix!
