### ISSUE TITLE
useRoutes and matchRoutes give different results in remix

### ISSUE THREAD

**Issue by SalahHamza** [remix-run/remix#9746]
### Reproduction

https://stackblitz.com/~/github.com/SalahHamza/remix-router-issue?file=app/spa/index.tsx

-----

I recently migrated a react-router app using the [react-router migration guide](https://remix.run/docs/en/main/guides/migrating-react-router-app), everything works perfectly until we introduce some new remix routes that conflict with SPA's routes.
```
app/
├── spa/
  │   └──index.tsx
├── routes/
  │   ├── _index.tsx
  │   ├── $.tsx
  │   └──$slug.tsx
  └── root.tsx
```

With the SPA content looking something like this (way more complicated in real app, so can't be migrated quickly):
```jsx
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/example" element={<ExamplePage />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
```
(I also tried defining the routes using `useRoutes` check the StackBlitz environment)

The goal is to have `$slug.tsx` match all `/:slug` routes except for the `/example` living in the SPA, in order to allow that I defined a route like this:
```ts
export default defineConfig({
  plugins: [
    remix({
      routes(defineRoutes) {
        return defineRoutes((route) => {
          // we want /example to be handled by the catch-all
          route("/example", "routes/$.tsx");
        });
      },
      // ...
    }),
    // ...
  ],
});
```
But to my surprise it's actually sending us to the home page `/` in the SPA.

One way I was able to make things work as expected is by doing the following, which I don't think is ideal:
```tsx
const routes = [
  {
    path: "/",
    element: <HomePage />,
    index: true,
  },
  {
    path: "/example",
    element: <ExamplePage />,
  },
  {
    path: "*",
    element: <NotFound />,
  },
];

  const location = useLocation();
  // routes here is the
  const matchedRoute = matchRoutes(routes, location.pathname);

  if (!matchedRoute || matchedRoute.length === 0) {
    return <Navigate to="/404" />;
  }

  return matchedRoute[0].route.element; // returns the correct route element
```
This means that `matchRoutes` and `useRoutes` don't work the same way.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (5) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: ^2.10.2 => 2.10.2 
    @remix-run/node: ^2.10.2 => 2.10.2 
    @remix-run/react: ^2.10.2 => 2.10.2 
    @remix-run/serve: ^2.10.2 => 2.10.2 
    vite: ^5.1.0 => 5.3.3
```

### Used Package Manager

npm

### Expected Behavior

For the `Routes`/`Route` components to route normally when used in conjunction with route configuration and routes files and for `matchRoutes` and `useRoutes` to have the same result.

### Actual Behavior

`useRoutes` and `matchRoutes` have different results

**Comment by brophdawg11** [comment]
This is because you are defining `/example` as a route of it's own and then rendering `MigratedSpa` from inside it.  The `/example` portion of the URL has already been matched/consumed in the Remix route tree by the time it reaches your SPA so there is no portion of the URL left to match and thus it matches the index route.

Effectively, you are creating a combined Remix + SPA route tree that looks like this and you would need a pathname of `/example/example` to match down into the `example` path in the SPA app

```jsx
<Routes>
  <Route path=""> // root route
    ...
    <Route path="example" element={<MigratedSPA />} /> // remix vite.config.tx route
  </Route>
</Routes>

function MigratedSPA() {
  return (
    <Routes>
      <Route path="/" element={<HomePage/>} />
      <Route path="/example" element={<ExamplePage/>} /> // SPA route
      <Route path="*" element={<NotFound/>} />
    </Routes>
  );
}
```

I'm curious why you can't just put the example route component into a Remix module file instead of sending it through the splat route?

```jsx
// routes/example.tsx
export default function Component() {
  return <Example />
}
```

If that is not an option, I would suggest moving Remix "slug" routes one by one as static route segment files (i.e., `routes/some-slug-value.tsx`) until you've been able to move them all and then moving them to `routes/$slug.tsx` once all single-URL segment slug routes are migrated.

**Comment by SalahHamza** [comment]
Okay, that makes perfect sense

> I'm curious why you can't just put the example route component into a Remix module file instead of sending it through the splat route?

That will need a couple of adjustments before being able to do so, but that's the end goal definitely. For now I'll go with a prefix for the slug routes `/s.$slug.tsx` to remove the conflicts until we are able to migrate the conflicting routes.

Thanks @brophdawg11 for taking the time for this 🙏
