### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.ts(2589) when using readonly

### ISSUE THREAD

**Issue by punkpeye** [remix-run/remix#9776]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-msgs25?file=app%2Froutes%2F_index.tsx

### System Info

```shell
N/A
```

### Used Package Manager

pnpm

### Expected Behavior

No type error.

### Actual Behavior

Getting error:

> Type instantiation is excessively deep and possibly infinite.ts(2589)

**Comment by punkpeye** [comment]
The only code necessary to replicate is this:

```ts
export const loader = defineLoader(async () => {
  type RecentChat = {};

  const recentChats: readonly RecentChat[] = [];

  return {
    recentChats,
  };
});

const Route = () => {
  const data = useLoaderData<typeof loader>();
};
```

**Comment by lilouartz** [comment]
@brophdawg11 I am facing the same issue. This is a blocker for adopting `turbo-stream`.

**Comment by lilouartz** [comment]
I dug into types. Looks like fixing this is super simple:

```diff
- type Serializable = undefined | null | boolean | string | symbol | number | Array<Serializable> | 
+ type Serializable = undefined | null | boolean | string | symbol | number | Array<Serializable> | ReadonlyArray<Serializable> | 
{
    [key: PropertyKey]: Serializable;
} | bigint | Date | URL | RegExp | Error | Map<Serializable, Serializable> | Set<Serializable> | Promise<Serializable>;
```

**Comment by punkpeye** [comment]
This fixed the issue!

**Comment by lilouartz** [comment]
@brophdawg11 @jacob-ebey Can this me merged upstream?

At the moment, I have to patch local node_modules every time I update Remix.

**Comment by brophdawg11** [comment]
`defineLoader` is going away in favor of a better type story soon so this will be resolved once that lands

**Comment by punkpeye** [comment]
> `defineLoader` is going away in favor of a better type story soon so this will be resolved once that lands

That's great news, but apps that currently rely on `defineLoader` cannot lint properly.

**Comment by brophdawg11** [comment]
It's an unstable API [not intended for production use](https://remix.run/docs/en/main/guides/single-fetch).  `// @ts-expect-error` is your friend here 😄

**Comment by punkpeye** [comment]
What `defineLoader` and `defineAction` have been replaced with?

How do I type them?

**Comment by 0t4u** [comment]
> What `defineLoader` and `defineAction` have been replaced with?
> 
> How do I type them?

They have been completely removed and not longer required, but the single fetch types need to be enabled, although type inference is broken for me (see https://github.com/remix-run/remix/issues/9970).

ref: https://github.com/remix-run/remix/blob/main/CHANGELOG.md#improved-single-fetch-type-safety-unstable

**Comment by punkpeye** [comment]
@0t4u see https://github.com/remix-run/remix/discussions/9969#discussioncomment-10607083
