### ISSUE TITLE
unstable_data response headers not set

### ISSUE THREAD

**Issue by ziimakc** [remix-run/remix#9822]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-stsale?file=app%2Froot.tsx

### System Info

```shell
-
```

### Used Package Manager

npm

### Expected Behavior

Response headers should be set:
```
  feResHeaders.append('X-YQQQ', 'xxxxxxxxxxxxx');
  feResHeaders.set('X-q', 'xxxxxxxxxxxxx');
```

### Actual Behavior

Response headers not set

**Comment by brophdawg11** [comment]
Single Fetch data requests use the [`headers`](https://remix.run/docs/en/main/route/headers) API the same way document requests do.

https://stackblitz.com/edit/remix-run-remix-8dw1je?file=app%2Froutes%2F_index.tsx

See also
* https://github.com/remix-run/remix/blob/main/CHANGELOG.md#removed-response-stub-in-single-fetch-unstable
* https://remix.run/docs/en/main/guides/single-fetch#headers

**Comment by brophdawg11** [comment]
You can absolutely set headers using `unstable_data` - via the `headers` API.  Remix runs all of your loaders in parallel a document or single fetch data request.  Remix cannot know how to merge the different headers you return from those loaders, so you need to implement that merging logic in `headers`.  If you look at my stackblitz example above, it has the following simple implementation to just use the loader headers.

```js
export const headers: HeadersFunction = ({ loaderHeaders }) => {
  return loaderHeaders;
};
```

**Comment by ziimakc** [comment]
I would suggest to add default root headers merging function for templates to avoid this confusion.
