### ISSUE TITLE
useLoaderData types broken if unstable_data is conditionally used

### ISSUE THREAD

**Issue by michaelgmcd** [remix-run/remix#9826]
### Reproduction

With the following loader:

```typescript
export const loader = unstable_defineLoader(async ({ request }) => {
  const isBot = isbot(request.headers.get('user-agent'));

  // Prevents making a session for every bot request
  if (isBot) {
    return { notification: null };
  }

  const session = await sessionStorage.getSession(request.headers.get('Cookie'));
  const notification = session.get('notification') ?? null;

  return unstable_data({ notification }, { 'Set-Cookie': await sessionStorage.commitSession(session) });
});
```

`const { notification } = useLoaderData<typeof loader>();` returns a type issue. The issue exists because of the conditional use of `unstable_data`. If I remove the "isBot" block, the type issue is gone.

<img width="863" alt="Screenshot 2024-08-04 at 9 01 46 PM" src="https://github.com/user-attachments/assets/339ab2a1-6088-49c5-9620-03aa245ea062">

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.85 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /opt/n/bin/node
    npm: 10.8.1 - /opt/n/bin/npm
    pnpm: 9.4.0 - /opt/n/bin/pnpm
    Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
```

### Used Package Manager

pnpm

### Expected Behavior

No type issue. In the use case above, `notification` would be `NotificationType | null`

### Actual Behavior

Type issue attached above.

**Comment by michaelgmcd** [comment]
Opened a PR, but it was wrong. Using this for now. If someone can confirm it works, I'll open another PR:
```typescript
type Unwrap<Input> = Input extends DataWithResponseInit<infer D> ? D : Input;

  export type Serialize<T extends Loader | Action> =
    Awaited<ReturnType<T>> extends TypedDeferredData<infer D>
      ? D
      : Awaited<ReturnType<T>> extends TypedResponse<Record<string, unknown>>
        ? SerializeFrom<T>
        : Awaited<ReturnType<T>> extends DataWithResponseInit<unknown> | Serializable
          ? Unwrap<Awaited<ReturnType<T>>>
          : Awaited<ReturnType<T>>;
```

**Comment by michaelgmcd** [comment]
The following works for us. Happy to make a PR. "Unwrap" naming could be improved.
```typescript
type Serializable =
    | undefined
    | null
    | boolean
    | string
    | symbol
    | number
    | Serializable[]
    | { [key: PropertyKey]: Serializable }
    | bigint
    | Date
    | URL
    | RegExp
    | Error
    | Map<Serializable, Serializable>
    | Set<Serializable>
    | Promise<Serializable>;

  type DataFunctionReturnValue =
    | Serializable
    | DataWithResponseInit<Serializable>
    | TypedDeferredData<Record<string, unknown>>
    | TypedResponse<Record<string, unknown>>;

  export type Unwrap<T extends DataFunctionReturnValue> =
    T extends TypedDeferredData<infer D>
      ? D
      : T extends TypedResponse<Record<string, unknown>>
        ? SerializeFrom<T>
        : T extends DataWithResponseInit<infer D>
          ? D
          : T;

  export type Serialize<T extends Loader | Action> =
    Awaited<ReturnType<T>> extends DataFunctionReturnValue
      ? Unwrap<Awaited<ReturnType<T>>>
      : Awaited<ReturnType<T>>;
```

**Comment by brophdawg11** [comment]
This is resolved by #9999 and will be included in the next release 👍

**Comment by zbinlin** [comment]
@brophdawg11 I have same issue in remix v2.14.0

``` Typescript
import { type LoaderFunctionArgs, data } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

export const loader = async () => {
	return data({
		foo: "bar",
	}, {
		headers: {
			"Set-Cookie": "Foo=Bar",
		},
	});
};

export default function Index() {
	const loaderData = useLoaderData<typeof loader>();
	// ^^^ The `loaderData` type is JsonifyObject<DataWithResponseInit<{ foo: string }>>
	// Expect JsonifyObject<{ foo: string }>
}
```

**Comment by goodeats** [comment]
> @brophdawg11 I have same issue in remix v2.14.0
> 
> ```ts
> import { type LoaderFunctionArgs, data } from "@remix-run/node";
> import { useLoaderData } from "@remix-run/react";
> 
> export const loader = async () => {
> 	return data({
> 		foo: "bar",
> 	}, {
> 		headers: {
> 			"Set-Cookie": "Foo=Bar",
> 		},
> 	});
> };
> 
> export default function Index() {
> 	const loaderData = useLoaderData<typeof loader>();
> 	// ^^^ The `loaderData` type is JsonifyObject<DataWithResponseInit<{ foo: string }>>
> 	// Expect JsonifyObject<{ foo: string }>
> }
> ```

I was running into this too and what solved it for me was combining these two parts from [Essential Typescript for React](https://www.jacobparis.com/content/react-ts):

- Use ReturnType and Awaited
- Use Omit to remove props when you override them.

So something like:

```ts
type LoaderData = Omit<Awaited<ReturnType<typeof loader>>, 'foo'> & {
	foo: string
}

const loaderData = useLoaderData<LoaderData>();
```

I'm sure this will be patched at some point, but this seems to work in the meantime.
