### ISSUE TITLE
BUG: useId generates duplicate IDs on initial render (ssr)

### ISSUE THREAD

**Issue by SimonMfroy** [remix-run/remix#9841]
### Reproduction

Steps To Reproduce :
-- To see the error : https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fwww.copinesdevoyage.com%2F#l1c2874
-- Or go to https://www.copinesdevoyage.com/ and disable JS
-- The duplicated ids will be found on avatars

### System Info

```shell
System:
    OS: macOS 14.0
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.99
    Safari: 17.0
  npmPackages:
    @remix-run/css-bundle: ^2.9.1 => 2.9.1
    @remix-run/dev: ^2.9.1 => 2.9.1
    @remix-run/eslint-config: ^2.9.1 => 2.9.1
    @remix-run/express: ^2.9.1 => 2.9.1
    @remix-run/node: ^2.9.1 => 2.9.1
    @remix-run/react: ^2.9.1 => 2.9.1
    @remix-run/server-runtime: ^2.9.1 => 2.9.1
    vite: ^5.2.11 => 5.2.11
```

### Used Package Manager

npm

### Expected Behavior

useId should produce a unique ID, ensuring that no two components have the same ID.

### Actual Behavior

On the initial render, useId hook generates duplicate IDs

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction via https://remix.new?
