### ISSUE TITLE
Top Suspense fallback not work

### ISSUE THREAD

**Issue by shaodahong** [remix-run/remix#9852]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-lqep5m?file=app%2Froutes%2F_index.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.11.1 
    @remix-run/node: * => 2.11.1 
    @remix-run/react: * => 2.11.1 
    @remix-run/serve: * => 2.11.1 
    vite: ^5.1.0 => 5.4.0
```

### Used Package Manager

npm

### Expected Behavior

Suspense fallback should be always show

### Actual Behavior

1. open preview in new tab（page visit）
2. refresh page some times
3. fallback is not visible as expected, and sometimes just flashes

But if you arbitrarily input one character above Suspense or arbitrarily input one character in an element of Loading, you can see that the fallback works properly after refreshing the page again

**Comment by shaodahong** [comment]
I'm using the latest version of the chrome browser. The actual project works well in safari, but I can't open stackblitz in safari, so I'm not sure if this example is also good in safari

**Comment by codeAdityagithub** [comment]
The following code works as expected:

function Index() {
  const { getData } = useLoaderData();
  return (
    <>
      <Suspense fallback={<p>loading...</p>}>
        <Await resolve={getData}>{(data) => <div>{data.name}</div>}</Await>
      </Suspense>
    </>
  );
}

The loader was showing but your <Loader /> component has wrong css 😅.

**Comment by codeAdityagithub** [comment]
The following code works as expected:

```jsx

function Index() {
  const { getData } = useLoaderData<typeof loader>();
  return (
    <>
      <Suspense fallback={<p>loading...</p>}>
        <Await resolve={getData}>{(data) => <div>{data.name}</div>}</Await>
      </Suspense>
    </>
  );
}
```
The loader was showing but your component has wrong css 😅.

**Comment by shaodahong** [comment]
> The loader was showing but your component has wrong css 😅.

@codeAdityagithub Thank you for your answer, Where is the wrong css shown? I see that Safari and Firefox both show it, and what I need is an empty div to implement loading animation

**Comment by codeAdityagithub** [comment]
Never mind, The css is correct there was a bug with my first run in stackblitz. This seems to run just fine theres no problem on my side.

**Comment by shaodahong** [comment]
> Never mind, The css is correct there was a bug with my first run in stackblitz. This seems to run just fine theres no problem on my side.

@codeAdityagithub Have you tried opening a new tab and refreshing it? I have now shortened the setTimeout time. It's almost 100% reproducible when it's less than 500.
<img width="897" alt="image" src="https://github.com/user-attachments/assets/863be144-7b32-4919-a1aa-9be75b2e40b0">

**Comment by codeAdityagithub** [comment]
I think I got it, but its weird. The loading component didn't show up when I opened the app in new tab, but when i added a "." inside the empty divs  of the loader :
```jsx
const Loading = () => {
  return (
    <section className="app-loader">
      <div className="bouncing-loader">
        <div>.</div>
        <div>.</div>
        <div>.</div>
      </div>
    </section>
  );
};
```
and added styles to blend in these dummy "." 
```css
.bouncing-loader > div {
            ...prevstyles,
            color: #8385aa;
          }
```
and this seems to work. 

This is such a weird and unexplainable behaviour.

**Comment by shaodahong** [comment]
It is very strange and makes me unsure whether  this is a react problem or a chrome problem. It seems to be a strange phenomenon that occurs when rendering tags without any characters
