### ISSUE TITLE
getInternalRouterError for missing POST endpoint instead of 405 Method Not Allowed

### ISSUE THREAD

**Issue by kenn** [remix-run/remix#9863]
### Reproduction

* Default Vite project, **without** `action` defined in `root.tsx`
* Hit `POST` at `/` emulating malicious attack
* Get `getInternalRouterError` which is a server error, not a client error

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 117.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.0.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Brave Browser: 127.1.68.141
    Chrome: 127.0.6533.119
    Safari: 17.5
  npmPackages:
    @remix-run/dev: ^2.11.1 => 2.11.1 
    @remix-run/express: ^2.11.1 => 2.11.1 
    @remix-run/node: ^2.11.1 => 2.11.1 
    @remix-run/react: ^2.11.1 => 2.11.1 
    vite: ^5.3.5 => 5.3.5
```

### Used Package Manager

pnpm

### Expected Behavior

Silently return `405 Method Not Allowed` to the client without triggering error reporting such as Sentry.

POST was made by a malicious attack attempt from a random client, thinking it's a PHP server.

### Actual Behavior

A server error thrown:

```
Error: You made a POST request to "/" but did not provide an `action` for route "root", so there is no way to handle the request.
    at getInternalRouterError
```

**Comment by brophdawg11** [comment]
> without triggering error reporting such as Sentr

I'm not sure what you are asking for here.  Do you want to filter this from going to Sentry?  You can control server-side error handling via [handleError](https://remix.run/docs/en/main/file-conventions/entry.server#handleerror)

**Comment by kenn** [comment]
My point is that it's not a server error. Client (status code `400`-`499`) errors should be reported to the client, not to the server owner. (minimal access log would suffice, definitely not the backtraces)

For instance, you could hit a random URL such as `https://my-remix-site.org/non-existent-path`, and it should just respond `404 Not Found` to the client. You don't want to get notified for it, and frameworks should handle those client errors.

**Comment by brophdawg11** [comment]
> Client (status code 400-499) errors should be reported to the client, not to the server owner

Strong disagree :).  "Client error" means that the request was in error (as opposed to the server code having a bug), but that doesn't mean the server owner should not be notified.  These 4xx errors may be a sign of something gone wrong - there's a bunch of good examples in https://httptoolkit.com/blog/how-and-why-to-monitor-http-client-errors.

> it should just respond 404 Not Found to the client. You don't want to get notified for it

Why not? Your application may not - but what if I want to know about a spike in 404s on the server to see if I published a dead link somewhere?  It's not Remix's call to make as to whether or not to log 4xx errors - we can only give applications the information needed to decide what's best for their use case.

> I also feel there should be a catch-all method to ignore all client errors

There is:

```js
export function handleError(error) {
  if (isRouteErrorResponse(error) && error.status < 500) {
    return;
  }
  // ...
}
```

**Comment by kenn** [comment]
Thanks! I see you have a good counter point of view — I've updated my code to handle specific client errors rather than blanket catch-all.

```ts
export function handleError(error, { request }) {
  if (request.signal.aborted) return
  if (isProd && isRouteErrorResponse(error) && [404, 405].includes(error.status)) return

  Sentry.captureException(error)
  console.error(error)
}
```

**Comment by kenn** [comment]
Ah, I just got another error report, and realized that it's considered as `400 Bad Request`, not `405 Method Not Allowed` — that's why it slipped through. (405 is safer to ignore than 400)

I think this is a bug — should we reopen this issue? What do you think?

```js
{
  data: Error: You made a GET request to "/api/xxx" but did not provide a `loader` for route "routes/api+/xxx", so there is no way to handle the request.,
  error: {
    message: You made a GET request to "/api/xxx" but did not provide a `loader` for route "routes/api+/xxx", so there is no way to handle the request.,
    name: Error,
    stack: ...
  },
  internal: true,
  status: 400,
  statusText: Bad Request
}
```

**Comment by brophdawg11** [comment]
I think these are ok as-is - plus it would potentially be a breaking change to alter the status.

We use 405 for the `action` scenario because without an action, in no-case is a POST request acceptable by the path.

But in the `loader` scenario, it's more nuanced.  If the `routes/_index` route doesn't have a `loader`, then `GET http://localhost:5173/?_data=routes%2F_index` is invalid because it's a targeted request to a specific route without a loader, but `GET http://localhost:5173/` is valid to load the HTML document.

[405 is defined as](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses):

> The request method is known by the server but is not supported by the target resource

So IMO the `GET` method is supported by the target resource `/` but just not in this specific use-case driven by the query params.

**Comment by kenn** [comment]
> So IMO the `GET` method is supported by the target resource `/` but just not in this specific use-case driven by the query params.

Fair, but my second case is at a resource route POST `/api/xxx`, not `/`. Also FWIW, I set `unstable_singleFetch` turned on.

In my case, it's intentional to not have a `GET` method for that — it's an action that receives `application/json` and causes mutation in the database, so it makes sense to return 405 for `GET`.

**Comment by kenn** [comment]
Hmm, I don't think it's a good idea to add such a boilerplate code to all API resource routes, just because some random bots might hit the system with non-existent `GET` requests.
