### ISSUE TITLE
Loader function not executed after redirect to same url with different search params after update to remix v2

### ISSUE THREAD

**Issue by KatharinaMadiwe** [remix-run/remix#9865]
### Reproduction

In our action function after submitting a form, we are redirecting to the same url with different search params. 
This problem occured after our update to remix v2, in remix v1 this was working fine.

```
export const action: ActionFunction = async ({ request }) => {
  try {
    ... 
    const headers = await someMethodToGetRedirectUrl();

    return new Response(null, { status: 302, headers });

  } catch (error) {
   ...
  }
};
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.31 GB / 15.86 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @remix-run/dev: ^2.10.2 => 2.11.1
    @remix-run/eslint-config: ^2.10.2 => 2.11.1
    @remix-run/node: ^2.10.2 => 2.11.1
    @remix-run/react: ^2.10.2 => 2.11.1
    @remix-run/serve: ^2.10.2 => 2.11.1
    @remix-run/v1-route-convention: ^0.1.4 => 0.1.4
```

### Used Package Manager

npm

### Expected Behavior

The redirect is successfull and the loader function is executed.

### Actual Behavior

The url in the browser is changed, but the loader function is not executed. We also don't see the status 302 in the browser developer tools.

**Comment by brophdawg11** [comment]
Please provide a minimal reproduction so we can look into the issue
