### ISSUE TITLE
cannot use non-standard HTTP methods within action

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/remix#9887]
### Reproduction

I was trying to build a WebDAV server, but as it turns out, remix only supports standard HTTP methods, and CalDAV uses `PROPFIND`

is there any chance you guys would be willing to loosen the restrictions? or is there a way I could handle `PROPFIND` http method some how in current remix?

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.16 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.asdf/installs/nodejs/20.5.1/bin/node
    npm: 9.8.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.7.1 - ~/.asdf/installs/nodejs/20.5.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.5
  npmPackages:
    @remix-run/cloudflare: 2.11.2 => 2.11.2 
    @remix-run/cloudflare-pages: 2.11.2 => 2.11.2 
    @remix-run/dev: 2.11.2 => 2.11.2 
    @remix-run/react: 2.11.2 => 2.11.2 
    @remix-run/testing: 2.11.2 => 2.11.2 
    vite: 5.4.1 => 5.4.1
```

### Used Package Manager

pnpm

### Expected Behavior

I'd expect to be able to handle non-standard HTTP methods

### Actual Behavior

only standard HTTP methods are supported.

**Comment by jacobparis** [comment]
The default Remix app server is just a small Express server that binds remix to `app('*', createRemixRequestHandler`

What would the process be for making express handle your custom methods?

**Comment by lifeiscontent** [comment]
@jacobparis realizing now that I probably should of opened the issue in react-router, but this is it:

https://github.com/remix-run/react-router/blob/main/packages/router/router.ts#L3498

**Comment by lifeiscontent** [comment]
if `ErrorBoundary` or some other handler existed in the scenario that remix doesn't know what to do, it would be ideal

**Comment by lifeiscontent** [comment]
nevermind, I figured out I could handle it in the entry.server.ts
