### ISSUE TITLE
clientLoader hydration message shows in SPA that doesn't use clientLoader

### ISSUE THREAD

**Issue by joryphillips** [remix-run/remix#9897]
### Reproduction

1. Fork https://github.com/joryphillips/macarons, a Remix SPA project using React 19.0.0-rc-a960b92c-20240819 so that HMR works, that does not include any clientLoader functions
2. Use `npm run dev` to see console message mentioned below
3. Use `npm run build` and then serve it to also see console message in [hosted build](https://macarons-ui.com) 

The message is
```
💿 Hey developer 👋. You can provide a way better UX than this when your app is running `clientLoader` functions on hydration. Check out https://remix.run/route/hydrate-fallback for more information.
```

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 1.24 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Safari: 17.6
  npmPackages:
    @remix-run/css-bundle: 2.11.2 => 2.11.2 
    @remix-run/dev: 2.11.2 => 2.11.2 
    @remix-run/eslint-config: 2.11.2 => 2.11.2 
    @remix-run/node: 2.11.2 => 2.11.2 
    @remix-run/react: 2.11.2 => 2.11.2 
    @remix-run/serve: 2.11.2 => 2.11.2 
    vite: ^5.4.1 => 5.4.1
```

### Used Package Manager

npm

### Expected Behavior

SPA project with no clientLoader functions should not have console message about clientLoaders, *especially in the final build*

### Actual Behavior

SPA project with no clientLoader functions is showing console message about clientLoaders in both dev and build

**Comment by brophdawg11** [comment]
This message should probably be tweaked so it's not specific to `clientLoader` but the message is accurate.  In SPA mode even without client loaders - your application has to load all of the JS bundles before it can render anything to the user.  Without a `HydrateFallback` you just show the user a completely blank white screen while all of that is loading.  Remix encourages you to add a root `HydrateFallback` to show them some sort of loading message or spinner or something.  That `HydrateFallback` ends up in the initial index.html document so it shows to the user immediately.

**Comment by joryphillips** [comment]
I was wondering if that might be the case. 

I did try adding a HydrateFallback but for some reason my app got stuck on that and never hydrated. I'll take another look at that.

**Comment by CodeSmith32** [comment]
For the record, I just had the exact same issue @joryphillips had initially:

After adding a `HydrateFallback` export, it would only load the fallback, and not the app.

The fix: export a `Layout` component from `root.tsx` (if you don't already) and **add `<ScrollRestoration />` and `<Scripts />` inside the layout `<body>`**. Without these two components, it will get stuck on the fallback.

e.g.,

```tsx
export default () => <Outlet />;

export const Layout = ({children}: {children: React.ReactNode}) => {
  return (
    <html>
      <head>
        <meta charset="utf8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>My App</title>
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        {/***** Required *****/}
        <ScrollRestoration />
        <Scripts />
        {/********************/}
      </body>
    </html>
  );
}

export const HydrateFallback = () => {
  return <>...</>;
}
```
