### ISSUE TITLE
Remix Serve calls installGlobals() 

### ISSUE THREAD

**Issue by swalker326** [remix-run/remix#9904]
### Reproduction

In this app I use @mjackson/multipart-parser which highlights the issue, everything works fine when running in dev after removing `installGlobals()` call but when I `pnpm build & pnpm start` installGlobals() is called for me. 

https://github.com/swalker326/multipart-build-issue

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1017.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    pnpm: 9.7.1 - ~/.nvm/versions/node/v20.2.0/bin/pnpm
    bun: 1.1.24 - /opt/homebrew/bin/bun
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.6
  npmPackages:
    @remix-run/dev: ^2.11.2 => 2.11.2 
    @remix-run/node: ^2.11.2 => 2.11.2 
    @remix-run/react: ^2.11.2 => 2.11.2 
    @remix-run/serve: ^2.11.2 => 2.11.2 
    vite: ^5.1.0 => 5.4.0
```

### Used Package Manager

pnpm

### Expected Behavior

When running `pnpm start` the app should not call `installGlobals()` or there should be a way to tell it to not call `installGlobals()`

### Actual Behavior

installGlobals is run via the remix-serve cli causing unexpected behavior changes in prod vs dev environment

**Comment by brophdawg11** [comment]
This is by design in Remix v2 because at the time v2 was released the native fetch wasn't good enough to rely on it for `remix-serve`.  Any changes to that would be a breaking change.  You can opt out of `installGlobals` by using a custom express server where you have full control :)

**Comment by brophdawg11** [comment]
FWIW I am pretty sure the plan is to remove it from `react-router-serve` in RR v7 since Node 20 is active LTS now

**Comment by swalker326** [comment]
Could there be a future flag for it?
