### ISSUE TITLE
single-fetch `useLoaderData()` evaluates to `null` when redirecting to same URL when `shouldRevalidate` returns false 

### ISSUE THREAD

**Issue by sapter** [remix-run/remix#9906]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-is4wn4
1. Start on home page
2. Click on "Go to subpage" (should navigate to and open `/subroute`)
3. Click on "Home". (should navigate to and open index/root `/` route again) 
4. Click on "Go to subpage" again. (should see error in screenshot below)

The error happens when the following conditions are true:
1. Child route loader throws a `redirect`
2. Child route has a `shouldRevalidate` function defined (and potentially returns `false`)

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 65.55 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.5
```

### Used Package Manager

npm

### Expected Behavior

`useLoaderData` is not `null`

### Actual Behavior

`useLoaderData` is null
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/bdf060da-55e3-43a3-9048-80ac4528e0a4">

**Comment by brophdawg11** [comment]
This looks like it's because the `_routes` param is sticking around unintentionally.  I'll get a fix in for that but in the meantime I think you could workaround it if you deleted that from the redirect URL you are constructing.
