### ISSUE TITLE
[Bug]: Error importing built-in node dependencies in Blog tutorial

### ISSUE THREAD

**Issue by fullstackjedi** [remix-run/remix#996]
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

Following the [developer blog tutorial](https://remix.run/docs/en/v1/tutorials/blog#creating-blog-posts), try to import either `fs` or `path` modules:

```ts
import path from "path";
import fs from "fs/promises";
import parseFrontMatter from "front-matter";

export type Post = {
  slug: string;
  title: string;
};

// relative to the server output not the source!
const postsPath = path.join(__dirname, "..", "posts");

export async function getPosts() {
  const dir = await fs.readdir(postsPath);
  return Promise.all(
    dir.map(async filename => {
      const file = await fs.readFile(
        path.join(postsPath, filename)
      );
      const { attributes } = parseFrontMatter(
        file.toString()
      );
      return {
        slug: filename.replace(/\.md$/, ""),
        title: attributes.title
      };
    })
  );
}
```

### Expected Behavior

Code working as expected

### Actual Behavior

An uncaught error is happening with the following message:

```
Uncaught TypeError: Failed to resolve module specifier "fs/promises". Relative references must start with either "/", "./", or "../".
```

Although the page is rendering properly, I am getting an "Uncaught Error" as the title (check below screenshot):

![image](https://user-images.githubusercontent.com/3157426/145696437-5854f932-aaa8-47e3-b8ae-272d794db64b.png)

**Comment by david-genger** [comment]
I am getting an error similar to this but the page is not loading. I am using the default `npx create-remix@latest` without any code change at all and I selected netlify when prompted. After deploying I am getting this.
![image](https://user-images.githubusercontent.com/12090146/145700600-e22b0211-a92d-44e0-8892-25fd4b497256.png)

Here is the URL to my deploy,
https://vigilant-euclid-6d6f07.netlify.app/

**Comment by tschaub** [comment]
I'm seeing the same error in all versions back to 0.21.0 (didn't try 0.20.0).  Curious if some people are able to follow the [quickstart](https://remix.run/docs/en/v1/tutorials/blog) without getting the error.

In case it helps others find the issue, at version 1.1.1, the page renders with the following **Application Error** for me:
```
TypeError: Cannot read properties of undefined (reading 'root')
    at RemixRoute (http://localhost:3000/build/_shared/chunk-MO7LPQZP.js:4706:19)
    at renderWithHooks (http://localhost:3000/build/entry.client-36IGYYIU.js:11068:26)
    at mountIndeterminateComponent (http://localhost:3000/build/entry.client-36IGYYIU.js:13188:21)
    at beginWork (http://localhost:3000/build/entry.client-36IGYYIU.js:13975:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3000/build/entry.client-36IGYYIU.js:3678:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/build/entry.client-36IGYYIU.js:3703:24)
    at invokeGuardedCallback (http://localhost:3000/build/entry.client-36IGYYIU.js:3737:39)
    at beginWork$1 (http://localhost:3000/build/entry.client-36IGYYIU.js:17084:15)
    at performUnitOfWork (http://localhost:3000/build/entry.client-36IGYYIU.js:16312:20)
    at workLoopSync (http://localhost:3000/build/entry.client-36IGYYIU.js:16266:13)
```

And at the top of the browser console:
```
Uncaught TypeError: Failed to resolve module specifier "fs/promises". Relative references must start with either "/", "./", or "../".
```

**Comment by tschaub** [comment]
I notice that if I remove the `<Scripts>` from `app/root.jsx`, the page loads without an error.  The `<Scripts>` in `app/root.jsx` came with `npx create-remix@latest` - the suggested starting point in the quickstart.

The tutorial does suggest "Add a link to posts in app/root.tsx" and "you might want to just delete everything that's there."  I took this to be a typo and instead added the link to `app/routes/index.tsx` and deleted everything else that was there.  But perhaps it was necessary to remove everything in `app/root.tsx` instead.

**Comment by lukahartwig** [comment]
I tried to reproduce this on CodeSandbox and also by following the quickstart guide locally but was not able to. [It seems to work fine for me](https://codesandbox.io/s/romantic-cache-gbs73?file=/app/post.ts).

Could you try to create a minimal repo that reproduces the bug?

**Comment by tschaub** [comment]
@lukahartwig - Here is a CodeSandbox reproducing the issue: https://codesandbox.io/s/remix-996-71hmu

You should be able to see the issue when navigating to the [posts route](https://71hmu.sse.codesandbox.io/posts).

The sandbox I created is based on what you get running `npx create-remix@1.1.1` (which is `latest` today) and then following the steps in https://remix.run/docs/en/v1/tutorials/blog.

It looks like the sandbox that you created is based on the remix-starter sandbox.  There are quite a few differences - not sure which are significant.  One probably significant difference between your sandbox and the one I created is that the one I created has a `app/routes/posts/index.jsx` route.  This is the route that demonstrates the issue.  Starting from your sandbox, I can reproduce the issue by updating `app/root.jsx`, `app/routes/index.jsx`, and `app/routes/posts/index.jsx`.  Here is another sandbox that is a modified version of yours that also demonstrates the issue: https://codesandbox.io/s/strange-rain-5vfmd (see the [posts route](https://5vfmd.sse.codesandbox.io/posts)).

**Comment by tschaub** [comment]
I notice that if I rename `app/post.js` to `app/post.server.js`, the example works.  This feels like it cannot be the right change, but here is what I did to get it to work: https://github.com/remix-run/remix/compare/main...tschaub:blog-update

And a working sandbox: https://codesandbox.io/s/remix-996-rename-post-js-to-post-server-js-jsg79?file=/README.md:0-48 (the [posts route](https://jsg79.sse.codesandbox.io/posts) no longer errors).

**Comment by elkevinwolf** [comment]
@tschaub's fix worked for me.

**Comment by zxuqian** [comment]
I encountered the same problem with the same code. I kept the code in `app/root.jsx` and added `<Link to="/posts">Posts</Link>` to `routes/index.jsx`. 

After import `path`, `fs/promises` node modules, the error occurred:

> Uncaught TypeError: Failed to resolve module specifier "path". Relative references must start with either "/", "./", or "../".

**Comment by mbrochh** [comment]
I'm getting this error as well. Only way to fix it for me is to remove `<Scripts />`

**Comment by selbekk** [comment]
Ah okay, so if you want to use node specific packages, you need to use them in a .server.ts suffixed file.

Thanks!

**Comment by machour** [comment]
The developer blog tutorial got revamped, and this is not applicable anymore.
