### ISSUE TITLE
TypeError: Inter-TransformStream ReadableStream.pipeTo() is not implemented

### ISSUE THREAD

**Issue by liho00** [remix-run/remix#9978]
### Reproduction

```
// app/routes/api.chat.ts

import type {ActionFunctionArgs} from '@vercel/remix';
import {createOpenAI} from '@ai-sdk/openai';
import {streamText} from 'ai';

export const config = {runtime: 'edge'};


const openrouter = createOpenAI({
  apiKey:
    'xxx',
  baseURL: 'https://openrouter.ai/api/v1',
});
export async function action({request}: ActionFunctionArgs) {
//   const {messages} = await request.json();
console.log('request', request)
  const result = await streamText({
    model: openrouter('qwen/qwen-2-7b-instruct'),
    // messages,
    prompt:
      'How to make a chatbot that can answer questions about the weather?',
  });
  console.log('result', result)

  return result.toDataStreamResponse();
  
}
```

reproduction repository
https://github.com/liho00/hydrogen-storefront

### System Info

```shell
AI_APICallError: Failed to process successful response
    at postToApi (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/@ai-sdk/openai/node_modules/@ai-sdk/provider-utils/dist/index.mjs:117:13)
    at OpenAIChatLanguageModel.doStream (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/@ai-sdk/openai/dist/index.mjs:302:50)
    at fn (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:335:23)
    at /Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:18:22
    at _retryWithExponentialBackoff (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:37:12)
    at startRoundtrip (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:300:13)
    at fn (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:377:11)
    at /Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:18:22
    at action (/Users/liho/Desktop/epray/hydrogen-sep/epray/app/routes/api.chat.ts:25:18)
    at callRouteAction (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/.vite/deps_ssr/@remix-run_server-runtime.js:3125:16) {
  cause: 'TypeError: Inter-TransformStream ReadableStream.pipeTo() is not implemented.\n' +
    '    at /Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/@ai-sdk/openai/node_modules/@ai-sdk/provider-utils/dist/index.mjs:100:10\n' +
    '    at postToApi (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/@ai-sdk/openai/node_modules/@ai-sdk/provider-utils/dist/index.mjs:105:20)\n' +
    '    at OpenAIChatLanguageModel.doStream (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/@ai-sdk/openai/dist/index.mjs:302:50)\n' +
    '    at fn (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:335:23)\n' +
    '    at /Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:18:22\n' +
    '    at _retryWithExponentialBackoff (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:37:12)\n' +
    '    at startRoundtrip (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:300:13)\n' +
    '    at fn (/Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:377:11)\n' +
    '    at /Users/liho/Desktop/epray/hydrogen-sep/epray/node_modules/ai/dist/index.mjs:18:22\n' +
    '    at action (/Users/liho/Desktop/epray/hydrogen-sep/epray/app/routes/api.chat.ts:25:18)'
}
```

### Used Package Manager

npm

### Expected Behavior

able to call the stream sse endpoint without issues

### Actual Behavior

hitting error when calling sse endpoint with the error message of TypeError: Inter-TransformStream ReadableStream.pipeTo() is not implemented

**Comment by liho00** [comment]
https://github.com/vercel/ai/issues/2972

**Comment by liho00** [comment]
@brophdawg11 should this is a bug? vercel sdk collaborator mentioned its very basic, should be supported

**Comment by brophdawg11** [comment]
This looks like something not supported on Cloudflare (specifically `Inter-TransformStream ReadableStream`).  

* This thread states it's not supported but planned: https://community.cloudflare.com/t/running-into-unimplemented-functionality/77343/4
* But I don't sere it mentioned anywhere here: https://developers.cloudflare.com/workers/runtime-apis/streams/

The thread contains a workaround that may be useful

**Comment by jacob-ebey** [comment]
Your project has some very mis-configured dependency versions. Fixing those up gets you a bit further, but the mini-oxygen runtime does not support TransformStream. This is something you could probably ask the hydrogen / oxygen team to enable.

Here is an updated repo with deps configured correctly, but running into the runtime limitations: https://github.com/jacob-ebey/hydrogen-ai-toolkit
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/3ef2277b-7382-43b9-9d46-56824fa67c68">

**Comment by liho00** [comment]
> This looks like something not supported on Cloudflare (specifically `Inter-TransformStream ReadableStream`).
> 
> * This thread states it's not supported but planned: https://community.cloudflare.com/t/running-into-unimplemented-functionality/77343/4
> * But I don't sere it mentioned anywhere here: https://developers.cloudflare.com/workers/runtime-apis/streams/
> 
> The thread contains a workaround that may be useful

@brophdawg11 
I did not attached it with a domain name, how can you relate it with cloudflare tho?

its running on localhost man.

Did you run the reproduction repository or not?

How come you close the issue immediate without correct justification.

@jacob-ebey 
You made the point out, i guess its hydrogen/oxygen issues as well... 
Thanks for your explanation and the review of the repository!
