### ISSUE TITLE
[SIngleFetch 2.12.0] Cannot declare module "@remix-run/server-runtime" when using pnpm

### ISSUE THREAD

**Issue by kesoji** [remix-run/remix#9981]
### Reproduction

pnpm dlx create-remix@latest pnpm-test

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 49.34 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - ~/.local/share/mise/installs/node/22/bin/node
    npm: 10.8.2 - ~/.local/share/mise/installs/node/22/bin/npm
    pnpm: 9.10.0 - ~/.local/share/mise/installs/node/22/bin/pnpm
    bun: 1.1.26 - ~/.local/share/mise/installs/bun/latest/bin/bun
  Browsers:
    Brave Browser: 117.1.58.127
    Chrome: 128.0.6613.137
    Safari: 17.6
  npmPackages:
    @remix-run/dev: ^2.12.0 => 2.12.0
    @remix-run/node: ^2.12.0 => 2.12.0
    @remix-run/react: ^2.12.0 => 2.12.0
    @remix-run/serve: ^2.12.0 => 2.12.0
    vite: ^5.1.0 => 5.4.4
```

### Used Package Manager

pnpm

### Expected Behavior

As changed in 2.12.0, we can declare and extend "@remix-run/server-runtime" and useLoaderData returns deserialized data (AWESOME!).

https://remix.run/docs/en/main/guides/single-fetch#enable-single-fetch-types

### Actual Behavior

Weh using pnpm, server-runtime is missing in node_modules/@remix-run and failing to extend Future interface.
![CleanShot 2024-09-13 at 08 03 22@2x](https://github.com/user-attachments/assets/8d5aeb42-11c3-43fc-a4dd-63f3aaf2f388)

**Comment by brophdawg11** [comment]
This is due to pnpm's added strictness over npm.  For now, you can install `@remix-run/server-runtime` as a dependency and we'll be re-exporting this `Future` type through the other packages (`@remix-run/node`, `@remix-run/cloudflare`, etc) in the next release and you'll augment the interface through them.
