### ISSUE TITLE
create-remix ends with "Oh no! Failed to initialize git."

### ISSUE THREAD

**Issue by zdrummond** [remix-run/remix#9986]
### Reproduction

1. Go to StackBlitz and start a vanilla Node env
2. type `npx create-remix@latest` at the terminal 
3. Select Init git repo, and Install deps

Result ([example at StackBlitz](https://stackblitz.com/edit/stackblitz-starters-tgktw7?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter))

```
❯ npx create-remix@latest
Need to install the following packages:
create-remix@2.12.0
Ok to proceed? (y) 
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

 remix   v2.12.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./remix-start

      ◼  Using basic template See https://remix.run/guides/templates for more
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

      ✔  Dependencies installed


      ▲  Oh no! Failed to initialize git.
```

### System Info

```shell
Stackblitz

 System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Expected Behavior

Expected, complete without the git failure

### Actual Behavior

Completes with " ▲  Oh no! Failed to initialize git."

**Comment by brophdawg11** [comment]
Can you run this with `--debug` and paste the output?  This is usually an issue with git on the local machine...

I just confirmed this is working fine for me locally.

![Screenshot 2024-09-16 at 9 45 31 AM](https://github.com/user-attachments/assets/3ad5c502-eb64-462b-8538-46de076bc895)

**Comment by zdrummond** [comment]
FWIW, ran with --debug, turned out that my SSH agent was not running, so failed with exit code 128. So not an issue with Remix. Thanks!

**Comment by Radi8co** [comment]
If anyone is still experiencing the issue, just configure the git with your name and email to fix it.
