### ISSUE TITLE
Remix:dev rebuild too long

### ISSUE THREAD

**Issue by LuckyArdhika** [remix-run/remix#9988]
### Reproduction

![image](https://github.com/user-attachments/assets/12443c51-b819-4236-b61f-38e11c9cdd35)

- "remix dev -c \"npm run dev:server\""
- remix started, now try to make a changes in a file...
- remix rebuild (see image above)

it takes about 26s :/

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Celeron(R) N4100 CPU @ 1.10GHz
    Memory: 531.97 MB / 3.83 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @remix-run/dev: ^2.9.2 => 2.9.2
    @remix-run/node: ^2.9.2 => 2.9.2
    @remix-run/react: ^2.9.2 => 2.9.2
    @remix-run/serve: ^2.10.2 => 2.10.2
    vite: ^5.1.0 => 5.3.1
```

### Used Package Manager

npm

### Expected Behavior

Remix build must be faster

### Actual Behavior

Remix build very sloww

**Comment by brophdawg11** [comment]
Can you provide a working reproduction repo where rebuild's are taking this long so we can investigate further?

**Comment by pcattori** [comment]
@LuckyArdhika your logs indicate that you are using the classic esbuild-based compiler and dev server. These were known to have many issues including slow startup and rebuilds. These are inherent limitations of the classic compiler and dev server.

In fact, this was one of the primary reasons we've switched to Vite. Any further dev server improvements will only be done on the Vite plugin.

See https://remix.run/docs/en/main/guides/vite and https://remix.run/docs/en/main/guides/vite#migrating for details.
